### ISSUE TITLE
Your Pool API is unstable

### ISSUE THREAD

**Issue by endeffects** [DeFiCh/app#1002]
Your pool api is really unstable, i'm receiving alot of 503 errors here

https://api.defichain.io/

Please fix this!

**Comment by izzycsy** [comment]
Hi @endeffects , try using: [DeFiChain Mainnet](https://mainnet.defichain.io/#/DFI/mainnet/home) or [cryptoID](https://chainz.cryptoid.info/dfi/) , the latter might be more stable based on user reports. 

In the future, you may also enquire on [DeFiChain Telegram (EN)](https://t.me/defiblockchain) to check if other users are facing similar issues. Thank you.

**Comment by endeffects** [comment]
I need to use the Pool Api and not the Blockchain one.

**Comment by endeffects** [comment]
@izzycsy could u please reopen the issue, it is stil unresolved and due the fact that you are providing a financial api you should take more care about uptime and stability of your services.

**Comment by izzycsy** [comment]
Hi @endeffects , update [v2.6.0](https://github.com/DeFiCh/app/releases/tag/v2.6.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @endeffects , thanks for your feedback, it should be fixed by now. If the issues persists, can you take a screenshot and provide links to the relevant respective sites that are not working, thank you.

**Comment by endeffects** [comment]
Thank you, i had no more issues over the last 36 hours.

**Comment by endeffects** [comment]
@izzycsy The pool api does not deliver any subgraph data since hours.

**Comment by izzycsy** [comment]
Hi @endeffects , update [v2.6.1](https://github.com/DeFiCh/app/releases/tag/v2.6.1) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @endeffects , can you take a screenshot and provide links to the relevant respective sites that are not working, it would help with the investigation, thank you.

**Comment by izzycsy** [comment]
Hi @endeffects , update [v2.6.2](https://github.com/DeFiCh/app/releases/tag/v2.6.2) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by endeffects** [comment]
Thank you, it works again.
