### ISSUE TITLE
Can a wallet be recovered with its address ?

### ISSUE THREAD

**Issue by StressedGhost** [DeFiCh/app#1012]
I had a wallet once and sadly I ended up loosing it. I still have its address... can It be recovered ?

**Comment by izzycsy** [comment]
Hi @StressedGhost , the address won't be sufficient, you need the` wallet.dat` to recover the wallet.

**Comment by izzycsy** [comment]
Hi @StressedGhost , update [v2.6.0](https://github.com/DeFiCh/app/releases/tag/v2.6.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. This comment is to notify you about the update.

**Comment by thedoublejay** [comment]
@StressedGhost if you're talking about the public address, then you can't. You need to either have the wallet.dat, private key or the mnemonic seed.

**Comment by izzycsy** [comment]
Hi @StressedGhost , update [v2.6.1](https://github.com/DeFiCh/app/releases/tag/v2.6.1) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._
