### ISSUE TITLE
Test AccountToUtxosTx execution failed: tx must have at least one input from account owner

### ISSUE THREAD

**Issue by octron0300** [DeFiCh/app#1016]
Why i can't send  DFI on my Cake Defi? Now writes  "Test AccountToUtxosTx execution failed: tx must have at least one input from account owner".  I sent DFI many times to this address dZduNaC6jXq8QSynEGtRQhPRXauJM9P5kK . My address Defi Wallet dKoZU6YgCwJR8jJezipjAoWygsqeFnrxbk

 I have UTXO 1.00082829 and Token 20.205938 . I only send 20 Token. Writes    Test AccountToUtxosTx execution failed: tx must have at least one input from account owner

#### What are your environment parameters?

- DeFi Wallet Version: v2.6.0
- Operating System (OS): windows 10, intel core i7, 16gb ram
- Current free storage capacity: 155GB ssd
![Снимок экрана (59)](https://user-images.githubusercontent.com/88514249/128427183-2684c0f1-b290-44e9-b19e-66ba4980b8b5.png)
![Снимок экрана (60)](https://user-images.githubusercontent.com/88514249/128427193-ccb50d29-a90f-41b4-a438-51935f70c25a.png)
![Снимок экрана (61)](https://user-images.githubusercontent.com/88514249/128427197-dce45323-d377-488a-965b-ca3c322d8188.png)

#### Anything else we need to know?

sendtoaddress dKoZU6YgCwJR8jJezipjAoWygsqeFnrxbk 0,01 3308c4b480769a3126d2c65be00c310f5d24618dc204c6d7e7e648f8ac758d61   Ik have only one address

**Comment by octron0300** [comment]
I managed to withdraw through Mac Book.  In windows10  3times reinstaleed the wallet, nothing succeeded.

**Comment by izzycsy** [comment]
Hi @octron0300 , can you try the following: 

Send 1 tokenDFI to yourself:

1. Copy your address (dKoZ...)
2. Click send DFI
3. Input 1 DFI
4. Paste the address
5. Send to yourself (dKoZ...) 
5. Try sending your 20 tokens again, or a smaller amount 

By sending to yourself, you're converting your tokenDFI to utxoDFI. utxoDFI is used for transaction fees.

More details here:

**Comment by izzycsy** [comment]
Hi @octron0300 , update [v2.6.1](https://github.com/DeFiCh/app/releases/tag/v2.6.1) is out.  Please read through the release notes before updating. This comment is to notify you about the update.

**Comment by izzycsy** [comment]
Hi @octron0300 , update [v2.6.2](https://github.com/DeFiCh/app/releases/tag/v2.6.2) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @octron0300 , update [v2.6.3](https://github.com/DeFiCh/app/releases/tag/v2.6.3) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._
