### ISSUE TITLE
Very long synchronization times since updating to 2.6.0

### ISSUE THREAD

**Issue by auxilio-ab** [DeFiCh/app#1019]
#### Actual behavior:
Synchronizing the blockchain needs a multiple of the time it used to before updating to 2.6.0. In the log files there is a huge number of "network error" entries. Syncing the wallet on a daily basis (~3000 blocks per day) took about 15-30 minutes. Since updating to 2.6.0 syncing this amount of blocks takes several hours.

#### Expected behavior:
Syncing times as before or faster than now

#### How to reproduce it (as minimally and precisely as possible):
- Updated to 2.6.0
- Synced whole blockchain (didn't use snapshot)
- Syncing got extremely slow from ~90% upwards
- When opening the wallet syncing takes several hours (even over night it doesn't finished)

#### What are your environment parameters?

- DeFi Wallet Version: 2.6.0
- Operating System (OS): Win10 21H1
- Current free storage capacity: 80 GB

#### Anything else we need to know?
no

[ab3d_defichain_2.6.0_logs.zip](https://github.com/DeFiCh/app/files/6954083/ab3d_defichain_2.6.0_logs.zip)

**Comment by izzycsy** [comment]
Hi @auxilio-ab , try turning off your firewall and checking that your internet connection is stable when using the DeFi Wallet app. Syncing from 0% will take very long, as you experienced, hence the purpose of Snapshot. But since you're already at 90%, just let it load, and if you need to be away from your PC, quit the app properly first and continue syncing when you're back, the app should start at where you left off.

**Comment by Goldbuddha** [comment]
Hi, i have exactly the same problem since the update to 2.6.0. It is synchronizing really slow. I am at 99,83%. It would take hours to be at 100%. Before the update it took me around 10 min to synchronize 24h.
Cant use the app because of that problem.

**Comment by auxilio-ab** [comment]
@izzycsy I fully agree with you, that syncing the whole chain takes a huge time. It took me about two days. But syncing just the last day takes several hours to get to 100%. Starting the Wallet one or two days later, it's the same again. Syncing is very slow. And in accordance to your answer to @Goldbuddha's post, at least on my site nothing has changed. Not the PC, not the internet connection, only DeFi Wallet was updated. So the slow synchronization times since 2.6.0 must be somehow related to the changes in the app. 

I'm updating to 2.6.1 now. I'll keep you informed whether there have been some performance improvements or not.

**Comment by auxilio-ab** [comment]
@izzycsy 

this is the current result after about two hours and I'm far away from beeing finished with syncing. But for the sake of completeness, this time it's a bit more than one day, as I have been away a few days.

13.08.21 23:11 1090568 / 1098136  99.31%
13.08.21 23:12 5x Network Error Message
14.08.21 00:12 1090903 / 1098261 99.33%  -> number of blocks (max block number) is toggling between last block on blockchain and inital value (1098136) from time to time
14.08.21 00:50 1091492 / 1098320 99.38%

I let it run through the night again. I'm pretty sure it's not finished in the morning (same as the last two or three times)

**Comment by auxilio-ab** [comment]
@izzycsy unfortunately my local db was damaged as Windows installed some updates during the night. I downloaded the snapshot now and started syncing the missing ~1300 blocks. Even this rather small amout took ~2,5 hours to sync. As written above, normally syncing ~2500 blocks took ~30 Mins before installing the update.

**Comment by Goldbuddha** [comment]
after installing the update to 2.6.1 synchronization goes a tiny little bit faster than before (just like izzycsy reported). It takes still a lot more time than before the update from 2.5.9 to 2.6.0. Nothing changed to the hardware or internet connection.
I even installed the wallet on mac and windows - an both systems the same problem. 
Hope for the next update. Or is it possible to find a download for the older version that worked properly?

**Comment by memzila** [comment]
I think it could be a problem with the chain and not the actual version. It probably has started some days ago. Very slow synching. I haven‘t startet the app the last 3 days and updated yesterday to 2.6.1. That is were i have noticed the very slow synching

**Comment by memzila** [comment]
I thought first probably problems with recent windows updates, but @Goldbuddha mentioned same problems also on mac so it is more likely a problem with the chain

**Comment by jpressler** [comment]
same issue here since the 1.8.0 node and 2.6.0 wallet update. even with the new 1.8.1 and 2.6.1 versions. no firewall, or internet issue, since nothing changed. maybe chain has not many nodes at 1.8.1 for syncing? any settings, tweaks available?

**Comment by 2horney** [comment]
I have been syncing for more than 24 hours. Also applied the last snapshot. Am now block 1102404 stopped at 99.96%. Sync no longer continues and suddenly all my credit has disappeared. What should I do now?

**Comment by thedoublejay** [comment]
There are some updates on the node side that might fix this issue. Need to do some testing first on the app before releasing it. https://github.com/DeFiCh/ain/issues/670

**Comment by thedoublejay** [comment]
Hey everyone, app 2.6.2 has been releeased - https://github.com/DeFiCh/app/releases/tag/v2.6.2. It's using the latest node 1.8.2. Please check if your sync issues has been resolved. Thanks!

**Comment by memzila** [comment]
Thanks @thedoublejay. I have read in release notes that spv is enabled in this version. Are the network errors with spv fixed on windows or is still the Parameter Spv=0 needed that it is working without network issues?

**Comment by jpressler** [comment]
> Hey everyone, app 2.6.2 has been releeased - https://github.com/DeFiCh/app/releases/tag/v2.6.2. It's using the latest node 1.8.2. Please check if your sync issues has been resolved. Thanks!

Thanks a lot. Just did the upgrade and sync is running much faster.
Before i had approx. 10 Blocks synced per minute, now it's ~300. A great improvement

**Comment by Goldbuddha** [comment]
Now its working fine again. Thank you!

**Comment by memzila** [comment]
It is working again. Thanks

**Comment by auxilio-ab** [comment]
I can also confirm, it's working fine again. Thx.
