### ISSUE TITLE
Unable to send BTC: JSON value is not an integer as expected

### ISSUE THREAD

**Issue by foobyte82** [DeFiCh/app#1026]
#### Actual behavior:
Error: JSON value is not an integer as expected when attempting to send 0.01220197 BTC to external wallet address.

#### What are your environment parameters?

- DeFi Wallet Version: 2.6.2 and 2.6.3-RC1
- Operating System (OS):  Windows
- Current free storage capacity: 500gb+

#### Anything else we need to know?
[log.zip](https://github.com/DeFiCh/app/files/7017175/log.zip)

What a disappointing start by storing BTC in this app to have it freeze and being unable to transfer it out or do anything else (dex) with it.

**Comment by foobyte82** [comment]
I would like to add that I created a BTC address within DeFi Wallet, funded it from an exchange and now this is stuck and I can't transfer it out again. Is there any CLI command I can use to transfer the funds?

**Comment by Joel1981** [comment]
I have the same problem and want to get a solution too. 
how did you find out that problem the fee parameter?

**Comment by thedoublejay** [comment]
@foobyte82 @Joel1981 Can you check if your wallet is locked? If not, you can try to do it on CLI.

spv_sendtoaddress 'your address' amount

**Comment by foobyte82** [comment]
@thedoublejay The wallet was unlocked. I figured out the command to send the funds via CLI but it returned the same error. 
The issue is the fee parameter because as variable type the function is setup to be a BigNumber (BTC fee), however the fee calculation is based on a satoshi value. I could have changed the fee parameter type to int and feed it a satoshi value to move my funds but without knowing the size and also being new to all of this, I didn't want to risk over- or underpaying. Has a pointer to where the issue is, at least how I observed it during debugging.

@Joel1981 Here is a workaround on how I transfered my funds out: 

1. Unlock the wallet
2. Go into the BTC wallet and click on "Receive" to view your address. Write it down!
3. Use the CLI to dump your private key for this address using this command: `dumpprivkey "address"`
4. Write down the private key!
5. Install Exodus Wallet and setup a BTC wallet. Once it has been created and selected, click the 3 red dots on the right side for the menu options. In the dropdown select "Move Funds" and then paste your private key to recover said funds to your exodus wallet. 

The DeFi Wallet just has an issue with the calculation and passing of the BTC fee for the transaction. As a work around you just use Exodus to move your funds and be done with this. In the end it was my fault for not knowing what SPV is, as the release clearly thats that SPV is in beta. However, if I see a feature in a stable release I tend to use it without thinking about it. Perhaps a disclaimer within the Wallet would have been nice. I spent 4 hrs debugging and raging because I thought I just lost 500 € after using DeFi Wallet for the first time. Either way, the workaround worked for me, the bug still needs to be fixed for other users though.

**Comment by Joel1981** [comment]
Thank you very much for your information!
I tried your solution but when i type the command the answer is: private key for „adress“is not known.
I am sure i typed the correct wallet adress. You have an idea whats wrong?

**Comment by foobyte82** [comment]
> Thank you very much for your information!
> I tried your solution but when i type the command the answer is: private key for „adress“is not known.
> I am sure i typed the correct wallet adress. You have an idea whats wrong?

Did you use `spv_dumpprivkey "address"` and replace _address_ with your actual BTC wallet address? See Step 2.

**Comment by Joel1981** [comment]
> @thedoublejay The wallet was unlocked. I figured out the command to send the funds via CLI but it returned the same error.
> The issue is the fee parameter because as variable type the function is setup to be a BigNumber (BTC fee), however the fee calculation is based on an Int (satoshi value). I could have changed the fee parameter type to int and feed it a satoshi value to move my funds but without knowing the message size and also being new to all of this, I didn't want to risk over- or underpaying.
> 
> @Joel1981 Here is a workaround on how I transfered my funds out:
> 
> 1. Unlock the wallet
> 2. Go into the BTC wallet and click on "Receive" to view your address. Write it down!
> 3. Use the CLI to dump your private key for this address using this command: `spv_dumpprivkey "address"`
> 4. Write down the private key!
> 5. Install Exodus Wallet and setup a BTC wallet. Once it has been created and selected, click the 3 red dots on the right side for the menu options. In the dropdown select "Move Funds" and then paste your private key to recover said funds to your exodus wallet.
> 
> The DeFi Wallet just has an issue with the calculation and passing of the BTC fee for the transaction. As a work around you just use Exodus to move your funds and be done with this. In the end it was my fault for not knowing what SPV is, as the release clearly states that SPV is in beta. However, if I see a feature in a stable release I tend to use it without thinking about it. Perhaps a disclaimer within the Wallet would have been nice. I spent 4 hrs debugging and raging because I thought I just lost 500 € after using DeFi Wallet for the first time. Either way, the workaround worked for me, the bug still needs to be fixed for other users though.

Please can you take a look at my answer. The solution not worked for me. Do you have i idea?

**Comment by thedoublejay** [comment]
> > @thedoublejay The wallet was unlocked. I figured out the command to send the funds via CLI but it returned the same error.
> > The issue is the fee parameter because as variable type the function is setup to be a BigNumber (BTC fee), however the fee calculation is based on an Int (satoshi value). I could have changed the fee parameter type to int and feed it a satoshi value to move my funds but without knowing the message size and also being new to all of this, I didn't want to risk over- or underpaying.
> > 
> > @Joel1981 Here is a workaround on how I transfered my funds out:
> > 
> > 1. Unlock the wallet
> > 2. Go into the BTC wallet and click on "Receive" to view your address. Write it down!
> > 3. Use the CLI to dump your private key for this address using this command: `spv_dumpprivkey "address"`
> > 4. Write down the private key!
> > 5. Install Exodus Wallet and setup a BTC wallet. Once it has been created and selected, click the 3 red dots on the right side for the menu options. In the dropdown select "Move Funds" and then paste your private key to recover said funds to your exodus wallet.
> > 
> > The DeFi Wallet just has an issue with the calculation and passing of the BTC fee for the transaction. As a work around you just use Exodus to move your funds and be done with this. In the end it was my fault for not knowing what SPV is, as the release clearly states that SPV is in beta. However, if I see a feature in a stable release I tend to use it without thinking about it. Perhaps a disclaimer within the Wallet would have been nice. I spent 4 hrs debugging and raging because I thought I just lost 500 € after using DeFi Wallet for the first time. Either way, the workaround worked for me, the bug still needs to be fixed for other users though.
> 
> Please can you take a look at my answer. The solution not worked for me. Do you have i idea?

Before you do the dump of private key, can you check if the wallet is unlocked? @Joel1981

**Comment by thedoublejay** [comment]
@Joel1981 @foobyte82 This has been fixed with the latest app update today [v2.6.3](https://github.com/DeFiCh/app/releases/tag/v2.6.3)

**Comment by Joel1981** [comment]
When is the rollout of 2.6.3?

**Comment by Joel1981** [comment]
![image](https://user-images.githubusercontent.com/89238663/130517531-87271ab6-2cf5-4818-9da6-3f7291cb7231.jpeg)

**Comment by Joel1981** [comment]
Still doesn't work. Now it shows no reason anymore.

**Comment by Joel1981** [comment]
@foobyte82 you are king! It worked. Thank you so much!
