### ISSUE TITLE
Sent real BTC to App Wallet and it does not arrive even after 10 confirmations.

### ISSUE THREAD

**Issue by muctobi** [DeFiCh/app#1027]
> i know after a bit of research now, that this feature is new.
but i have sent some BTC to a BTC receive address where it never arrived.

please warn other users and help me to retrieve the funds.

I have Wallet App 2.6.2 on OSX Big Sur.

Kind Regards

<img width="653" alt="Bildschirmfoto 2021-08-19 um 23 07 05" src="https://user-images.githubusercontent.com/45494638/130143988-351cc96a-b637-43fa-9f28-00d7d76670ec.png">

<img width="616" alt="Bildschirmfoto 2021-08-19 um 22 50 24" src="https://user-images.githubusercontent.com/45494638/130143872-8f52675f-c01c-4763-8369-d4cf0bb09aef.png">

**Comment by thedoublejay** [comment]
@muctobi Do you have a link for the tx from explorer?

**Comment by thedoublejay** [comment]
@muctobi we will check this. But in the meantime, can you type on the App Console `spv_getbalance` to see if you have the balance on your wallet

**Comment by muctobi** [comment]
Hi JJ Adonis,

i have downloaded Version 2.6.2 from the Website after 2.6.1 was not synchronizing.

There was no label at all that this is a not stable BETA release.
I don’t understand how even a simple Messenger or Office Software is able to label that properly but not Defichain which is handling customer money.

TX ID is:
https://btc1.trezor.io/tx/4010894e8413d38369769c56ae74e299b506eac44bfdefe3d9ed2d8760366ab5

spv_getbalance = 0

spv_dumpprivkey bc1qk7ea9s4lkgzjdlk0k05673nqeu4z2zujkh99n9 = Private key for address bc1qk7ea9s4lkgzjdlk0k05673nqeu4z2zujkh99n9 is not known


This is a year of my savings. I really hope that you can help me to recover these funds.
And please stop other people from using this feature. This is irresponsible for anyone trusting your product and reputation.

Kind Regards

Tobias

**Comment by thedoublejay** [comment]
@muctobi we're currently investigating it. We'll let you know immediately once we have some updates

**Comment by muctobi** [comment]
Thank you very much. 

Please let me know if you need any further logs or data from my App.

I installed the app on a brand new OSX Big Sur Mac Book Air with M1 Processor.

**Comment by Bushstar** [comment]
If your wallet is encrypted/locked please run `walletpassphrase` first to unlock it and then run `spv_dumpprivkey`. Let us know if that then dumps your private key, DO NOT post it here if it does.

**Comment by Bushstar** [comment]
@muctobi If your wallet is encrypted/locked please run `walletpassphrase` first to unlock it and then run `spv_dumpprivkey`. Let us know if that then dumps your private key, DO NOT post it here if it does.

**Comment by muctobi** [comment]
Hi should i type:

walletpassphrase followed by my wallet Password?

**Comment by Bushstar** [comment]
It is as follows with timeout replaced by the number of seconds to unlock your wallet.

walletpassphrase PASSWORD timeout

https://bitcoincore.org/en/doc/0.16.0/rpc/wallet/walletpassphrase/

**Comment by muctobi** [comment]
yes now it showed me a private key :-)

that means i can retrieve the funs like with a paper wallet?

**Comment by Bushstar** [comment]
Correct, with the private key you have access to that address and can get the funds back one way or another. Keep a copy of that private key. I'm working on a solution in the DeFiChain wallet now as we may have been able to recreate your problem.

**Comment by Bushstar** [comment]
@muctobi can you please post here the output of the command `spv_syncstatus`?

**Comment by thedoublejay** [comment]
@muctobi I believe you're using Mac. Can you try this steps:
1. Close the app first. Go to your blockchain folder - `~/Library/Application Support/DeFi/wallets/wallet_map.json` 
2. Backup that file somewhere, then delete it on the folder
3. Next, you need to find out the `.defi` conf file. You can check this - https://defichain-wiki.com/wiki/Delete_.defi
4. When you open it, it should look something like this
![image](https://user-images.githubusercontent.com/25013382/130211036-268a7ef7-a862-48ff-b86a-851ebf4f048a.png)
5. change spv=1
6. run the app again
7. wait a bit for the SPV to resync (30 mins). Then check if your BTC balance is updated

**Comment by muctobi** [comment]
{
  "connected": true,
  "current": 696682,
  "estimated": 696682
}

**Comment by muctobi** [comment]
i exported the funds successfully to a external Wallet
thank you very much for your help!

**Comment by izzycsy** [comment]
Hi @muctobi , update [v2.6.3](https://github.com/DeFiCh/app/releases/tag/v2.6.3) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._
