### ISSUE TITLE
Atomic Swap: Maker bot not accept my offer

### ISSUE THREAD

**Issue by angelocastiglione** [DeFiCh/app#1029]
Hello to all i view several time the video of U-Zyn for explain how to use atomic swap but I have isse for using because after send my offer to maker bot, this not accept my offer and is not possible for me continue with the atomic swap.

In this case the BOT is maker and have BTC and I am taker that i have dBTC

I sent this command

icx_makeoffer {"orderTx":"92eed77c9369775760e15b7a73690c7c5d6080488f1589a1e4463e2d3e15fbf3","amount":0.00001,"ownerAddress":"MYADDRESSDFI","receivePubkey":"MYADDRESSBTCPUBKEY","expiry":240}

and receive a response with TXID

But for check if the maker bot accept my offer i send this command

icx_listhtlcs {"offerTx":"TXID RECEIVED BEFORE"}

with no response, also on the guide https://github.com/DeFiCh/app/discussions/998 explain more easy what is the result that i neeed to see.

I am stop with atomic swap, I hope to find a solution for continue.
![Schermata da 2021-08-22 12-00-51](https://user-images.githubusercontent.com/82758166/130351948-7ffe3739-ab0e-4aa5-a302-8bc4298f5f19.png)

**Comment by izzycsy** [comment]
Hi @angelocastiglione , at step 3 where you were stuck, could it be you're missing **icx_listhtlcs `'`{"offerTx":"TXID RECEIVED BEFORE"}`'`** ? Also, are you using Mainnet or Testnet?

**Comment by angelocastiglione** [comment]
I am using Mainet with Defi Wallet 2.6.2

If you using the APP you need to remove the code ' 

See attachment of the video.

![Schermata da 2021-08-22 23-34-39](https://user-images.githubusercontent.com/82758166/130370726-04a8bbb8-a1a9-4f36-bce2-07e35449066b.png)

**Comment by ShengguangXiao** [comment]
Hi @angelocastiglione, there was some issue with the icx maker bot previously, we fixed it and restarted it, could you try to run again and share your txid with us?

**Comment by angelocastiglione** [comment]
Yesss now icx_listhtlcs {"offerTx":"TXID"} is working 

The txid is 2e7eb4137ac42b7508b96c08d71b7e91f5ebacdecced8de7fb6f77220cffba7b

I go to next step 

spv_createhtlc TAKER-BTC-PUBKEY MAKER-BTC-PUBKEY 80 HASH

bet response to me with this error

JSON value is not a string as expected

**Comment by ShengguangXiao** [comment]
`spv_createhtlc` command, all the parameters are string.

**Comment by angelocastiglione** [comment]
I need to wait a solution or this command is not correct?

spv_createhtlc TAKER-BTC-PUBKEY MAKER-BTC-PUBKEY 80 HASH

**Comment by angelocastiglione** [comment]
the correct command is 

spv_createhtlc TAKER-BTC-PUBKEY MAKER-BTC-PUBKEY "80" HASH

**Comment by angelocastiglione** [comment]
Can you check if the bot maker is freeze? Not accept again my request.

You can see my txid 4c7fbfa750d73b1d4860a29b1b7ba4b82744f1c4a547d90551279f279f074056

**Comment by izzycsy** [comment]
Hi @angelocastiglione , good to hear, has your issue been resolved?

**Comment by angelocastiglione** [comment]
I think the boot is freeze again 25/08/2021 because I send new offer and not reply to me.

**Comment by izzycsy** [comment]
Hi @angelocastiglione @Mark76DefiChain , update [v2.6.3](https://github.com/DeFiCh/app/releases/tag/v2.6.3) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by Mark76DefiChain** [comment]
> @angelocastiglione Thanks for your information. The node is out of sync and make the icx make bot runs into problem, need to fix it. We manually executed the steps on maker side, now you should can continue on step (8).

Is the node synced again?

**Comment by ShengguangXiao** [comment]
> > @angelocastiglione Thanks for your information. The node is out of sync and make the icx make bot runs into problem, need to fix it. We manually executed the steps on maker side, now you should can continue on step (8).
> 
> Is the node synced again?

Yes

**Comment by izzycsy** [comment]
Hi @angelocastiglione @Mark76DefiChain , update [v2.7.0](https://github.com/DeFiCh/app/releases/tag/v2.7.0) is out, this is a **mandatory update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @angelocastiglione @Mark76DefiChain , update [v2.7.1](https://github.com/DeFiCh/app/releases/tag/v2.7.1) is out, this is a **mandatory update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._
