### ISSUE TITLE
My backup file was broken how to fix

### ISSUE THREAD

**Issue by Tommylam8** [DeFiCh/app#1031]
#### What are your environment parameters?

- DeFi Wallet Version: 
- Operating System (OS): 
- Current free storage capacity:

**Comment by angelocastiglione** [comment]
You can create new file of your wallet with import of the private key

**Comment by Tommylam8** [comment]
I do not have private key

**Comment by angelocastiglione** [comment]
You can try to export your private key, go to conolle (make sure that is unlocket the wallet) 

dumpprivkey "your address"

You can read the wiki guide

https://defichain-wiki.com/wiki/Private_key_read_out_of_the_app

you dont have a backup of your wallet?

**Comment by Tommylam8** [comment]
I'm getting this error

**Comment by izzycsy** [comment]
Hi @Tommylam8 , do you have another `wallet.dat`? May I know the following: 
DeFi Wallet Version:
Operating System (OS):

**Comment by Tommylam8** [comment]
No

**Comment by izzycsy** [comment]
Hi @Tommylam8 , you can try and see if there's another wallet.dat and restore from there. if you did not specify where you saved your wallet.dat, there should be additional backups here: 

**On Windows: DeFi Blockchain folder**
C:\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\

**On Mac: Blockchain folder** 
/Users/<username>/Library/Application Support/Defi/wallets/

<img width="822" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/130600377-4721cb6b-f86c-457c-a791-6374f30bdf09.png">

Guide on how to [Restore Wallet from Backup](https://github.com/DeFiCh/app/discussions/988)

**Comment by izzycsy** [comment]
Hi @Tommylam8 @angelocastiglione , update [v2.6.3](https://github.com/DeFiCh/app/releases/tag/v2.6.3) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._
