### ISSUE TITLE
Better default token sorting

### ISSUE THREAD

**Issue by prasannavl** [DeFiCh/app#1035]
A potential way to sort tokens by default for balances, liquidity, etc: 

- Non zero tokens
  - Primary: DST followed by LP
  - Secondary: Value (balance total, liquidity, etc)
  - Tertiary: Name 
- Zero tokens
  - Primary: DST followed by LP
  - Tertiary: Name

**Comment by izzycsy** [comment]
Hi @prasannavl , thanks for your feedback, will inform the team.
