### ISSUE TITLE
MAX' button shows wrong Max-values

### ISSUE THREAD

**Issue by Darkman-Q-Tester** [DeFiCh/app#1038]
OS Version: Windows 10  (21H1, Build 19043.1165)
Wallet App Version: 2.6.

Issue:
Add liquidity 'MAX' button shows wrong Max-values. The Wallet App will always display the last used Max values but not the real available balance.

Expected behavior:
When ever I go to Liquidity (select pair, click +ADD MORE, and click on MAX for Input) I would expect the correct Max value should be calculated from the available balance.

Steps to Reproduce:
- Go to Liquidity
- select a pair e.g. BTC-DFI
- click +ADD MORE
- click on MAX for Input 
--> last used Max values will be displayed not the real available balance

Workaround:
After the wrong Max value is displayed go to Transactions screen then come back to Liquidity and click Max again --> now it will show the correct available Max values from real available balance.

![grafik](https://user-images.githubusercontent.com/77509687/132545433-c0966977-ce04-4a53-8d6d-22ce56f36048.png)

**Comment by izzycsy** [comment]
Hi @Darkman-Q-Tester , thank you please give us time to investigate.

**Comment by izzycsy** [comment]
Hi @Darkman-Q-Tester , issue seems resolve.

**Comment by izzycsy** [comment]
Hi @Darkman-Q-Tester , update [v2.7.0](https://github.com/DeFiCh/app/releases/tag/v2.7.0) is out, this is a **mandatory update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._
