### ISSUE TITLE
min relay fee not met, 190 < 223 (code 66)

### ISSUE THREAD

**Issue by squizzer1** [DeFiCh/app#1039]
#### Actual behavior:
I cant send dfi.
Error code: min relay fee not met, 190 < 223 (code 66)

#### What are your environment parameters?

- DeFi Wallet Version: 2.6.4
- Operating System (OS): Windows 10
- Current free storage capacity: 58,2GB
[1.log](https://github.com/DeFiCh/app/files/7131094/1.log)

**Comment by RobinTorque** [comment]
Hi Robin here from DFX.swiss

We have exactly the same problem. No more transactions are possible. We actually wanted to pay out customer funds, but we always get this error. 
<img width="409" alt="Bildschirmfoto 2021-09-08 um 20 02 11" src="https://user-images.githubusercontent.com/65536965/132568079-ce5bce68-9f76-4267-857c-baacb0fcee15.png">

![photo_2021-09-08_20-49-24](https://user-images.githubusercontent.com/65536965/132568250-3bc036f7-183d-4a60-9de5-61f6c45c7d76.jpg)


Operating system Mac OS
Wallet: 2.6.4

**Comment by Corvinusss** [comment]
I'm also having this issue as well on windows 10
![image](https://user-images.githubusercontent.com/90349834/132570007-326ae7d2-9ca4-41a8-a9d9-8f4cf1edf11f.png)

**Comment by izzycsy** [comment]
Hi @squizzer1 @Corvinusss , if possible please .zip and send your logs as it'll help with investigation. Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/132573578-460cd303-f0ed-447a-a962-fe1ffcf7f17f.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/132573584-34b970e3-bc10-4e7e-ab40-be002b860de6.png">


Hi @RobinTorque , well received, thank you.

**Comment by squizzer1** [comment]
Here the file.
[1.zip](https://github.com/DeFiCh/app/files/7131456/1.zip)

**Comment by exmattix** [comment]
I have the same problem, I was on version 2.6.3 there was a message about missing UTXO, after updating I got the min relay fee issue.... 
Windows 10
I can upload my logs as well, tomorrow.

**Comment by derstrecker** [comment]
Same here. 
macOS 11.5.1
Version 2.6.4
Could send some coins some hours ago, but now this failure message.

**Comment by Flocki417** [comment]
I have the same issue on macOS Version 2.6.3

**Comment by ollo-berlin** [comment]
Same here.
Win 10 
Version 2.6.4

**Comment by pmjlaw** [comment]
Good morning, same issue here, using macOS 11.5.2 and DeFI wallet v 2.6.3
Please find attached the logs.
Thanks!
[Untitled.log](https://github.com/DeFiCh/app/files/7134089/Untitled.log)

**Comment by OtenMoten** [comment]
Same here. 

OS: `Ubuntu 20.04`
DEFI-App Version: `2.6.4`

**Comment by thedoublejay** [comment]
Hi @RobinTorque, can you run `getnetworkinfo` from CLI and paste the response here? Or you can send it to Bella also thanks

**Comment by OMeinert** [comment]
Here is mine:
DeFi Wallet v2.6.0 
Node v1.8.1
getnetworkinfo
{
  "version": 1080100,
  "subversion": "/DeFiChain:1.8.1/",
  "protocolversion": 70018,
  "localservices": "0000000000000409",
  "localrelay": true,
  "timeoffset": 0,
  "networkactive": true,
  "connections": 8,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00001,
  "incrementalfee": 0.00001,
  "localaddresses": [],
  "warnings": ""
}

**Comment by OMeinert** [comment]
and here is the second one

getnetworkinfo
{
  "version": 1080300,
  "subversion": "/DeFiChain:1.8.3/",
  "protocolversion": 70018,
  "localservices": "0000000000000409",
  "localrelay": true,
  "timeoffset": 0,
  "networkactive": true,
  "connections": 8,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00001,
  "incrementalfee": 0.00001,
  "localaddresses": [],
  "warnings": ""
}

**Comment by 2Dsirecrypto** [comment]
Same issue on windows 10

**Comment by RobinTorque** [comment]
> Hi @RobinTorque, can you run `getnetworkinfo` from CLI and paste the response here? Or you can send it to Bella also thanks

@thedoublejay @izzycsy 
of course, just tried again. 

<img width="1440" alt="Bildschirmfoto 2021-09-09 um 13 59 22" src="https://user-images.githubusercontent.com/65536965/132681962-f036c2c2-0b5f-470c-b656-000014ed8a03.png">

<img width="1440" alt="Bildschirmfoto 2021-09-09 um 13 59 38" src="https://user-images.githubusercontent.com/65536965/132682000-bede3c55-ea45-4ea2-8da0-5f4b4bca65ca.png">

Node v1.8.3


getnetworkinfo
{
  "version": 1080300,
  "subversion": "/DeFiChain:1.8.3/",
  "protocolversion": 70018,
  "localservices": "0000000000000409",
  "localrelay": true,
  "timeoffset": 0,
  "networkactive": true,
  "connections": 8,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00001,
  "incrementalfee": 0.00001,
  "localaddresses": [],
  "warnings": ""
}

**Comment by MTNST-AL** [comment]
Hey guys, i get the same Error when i tried converting Token to UTXO with accounttoutxos:

DeFi Wallet v2.6.3 
Node v1.8.2
getnetworkinfo
{
  "version": 1080200,
  "subversion": "/DeFiChain:1.8.2/",
  "protocolversion": 70018,
  "localservices": "0000000000000409",
  "localrelay": true,
  "timeoffset": 0,
  "networkactive": true,
  "connections": 8,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00001,
  "incrementalfee": 0.00001,
  "localaddresses": [],
  "warnings": ""
}

**Comment by ollo-berlin** [comment]
I hope this helps you

DeFi Wallet v2.6.4 
Node v1.8.3
getnetworkinfo
{
  "version": 1080300,
  "subversion": "/DeFiChain:1.8.3/",
  "protocolversion": 70018,
  "localservices": "0000000000000409",
  "localrelay": true,
  "timeoffset": -3,
  "networkactive": true,
  "connections": 8,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00001,
  "incrementalfee": 0.00001,
  "localaddresses": [
    {
      "address": "2a02:8109:b23f:bc66:27:d7d2:812a:d234",
      "port": 8555,
      "score": 4
    }
  ],
  "warnings": ""
}

**Comment by Workoholic-Jap** [comment]
same here

DeFi Wallet v2.6.3 
Node v1.8.2
getnetworkinfo
{
  "version": 1080200,
  "subversion": "/DeFiChain:1.8.2/",
  "protocolversion": 70018,
  "localservices": "0000000000000409",
  "localrelay": true,
  "timeoffset": 0,
  "networkactive": true,
  "connections": 8,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00001,
  "incrementalfee": 0.00001,
  "localaddresses": [
    {
      "address": "2001:1c04:3b16:7a00:5c1b:e6e6:7f62:6945",
      "port": 8555,
      "score": 1
    },
    {
      "address": "2001:1c04:3b16:7a00:d978:db83:11c0:6e36",
      "port": 8555,
      "score": 1
    }
  ],
  "warnings": ""
}

**Comment by thunderstorm99** [comment]
I can confirm, I have the same issue on MacOS

**Comment by exmattix** [comment]
I fixed my problem (maybe just temporary) by using the DEX, after that I was able to send some funds, ill edit my post when I try another sending on another day.

**Comment by worldyturtle** [comment]
Same error as others
[DeFi Logs 2021-9-9.log](https://github.com/DeFiCh/app/files/7138712/DeFi.Logs.2021-9-9.log)


DeFi Wallet v2.6.4 
Node v1.8.3
getnetworkinfo
{
  "version": 1080300,
  "subversion": "/DeFiChain:1.8.3/",
  "protocolversion": 70018,
  "localservices": "0000000000000409",
  "localrelay": true,
  "timeoffset": 0,
  "networkactive": true,
  "connections": 8,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00001,
  "incrementalfee": 0.00001,
  "localaddresses": [],
  "warnings": ""
}

**Comment by Corvinusss** [comment]
> I fixed my problem (maybe just temporary) by using the DEX, after that I was able to send some funds, ill edit my post when I try another sending on another day.

Wow, this somehow worked on my side as well.

**Comment by dell1503** [comment]
> I fixed my problem (maybe just temporary) by using the DEX, after that I was able to send some funds, ill edit my post when I try another sending on another day.

Didnt work for me.
I Swaped some ETH to DFI
then do again send transaction. Didn't work for me.

**Comment by nordi6000** [comment]
I have same error. Windows 10 
DeFi Wallet V 2.6.4
![image](https://user-images.githubusercontent.com/49670309/132750940-3a477228-5011-43be-8ce7-771f397a8148.png)

Here my Log files, hope will help you.

[Error_2.6.4.zip](https://github.com/DeFiCh/app/files/7139282/Error_2.6.4.zip)

**Comment by Timo258** [comment]
Gleiches Problem hier mit Windows 7
min relay fee......(code66)
sieht so aus, daß gerade niemand DFI auszahlen kann?

**Comment by pmjlaw** [comment]
Hi Folks, are there any updates? Kindly prioritise this feature, core functionality that needs to be available 24/7. Thanks a lot for you hardwork, you are the best!

**Comment by ollo-berlin** [comment]
> Gleiches Problem hier mit Windows 7
> min relay fee......(code66)
> sieht so aus, daß gerade niemand DFI auszahlen kann?

Der Tip hier mit der DEX hat bei mir auch funtioniert.  Ich habe DFI in der Wallet zu LTC Token geswappt dann zu Cake gesendet und von da zu Binance.

**Comment by Timo258** [comment]
Ok, das geht dann wohl nur mit Cake Account, wo man die anderen Token hinsenden kann.

**Comment by Timo258** [comment]
> > Gleiches Problem hier mit Windows 7
> > min relay fee......(code66)
> > sieht so aus, daß gerade niemand DFI auszahlen kann?
> 
> Der Tip hier mit der DEX hat bei mir auch funtioniert. Ich habe DFI in der Wallet zu LTC Token geswappt dann zu Cake gesendet und von da zu Binance.

**Comment by prasannavl** [comment]
Hi everyone - thanks for the report on this. We're investigating this, however here's some quick context and potential workarounds: 

**Context**

What I _think_ is happening here, from quick glance, while the team is trying to reproduce the exact conditions to find out the cause: For every transaction, there is a calculation on the node before it submits the transaction (precisely when it's submitted to the mempool), to verify that the tx fee is greater than the `minrelayfee` [1]. However, while using certain specific methods, such as `accounttoutxos` and certain txs, this calculation doesn't match up - my _current guess_ is it's only happening for certain large txs that ends up getting created.  

We're still investigation what the exact conditions of this cause this. More on this soon. 

**Workarounds**

1. One possible workaround as mentioned above is to use the DEX that spends DFI (specifically one that ends up consolidating your utxos). The app internally uses an utxo consolidator, so that it takes a lot of these tiny amounts that you have and then consolidate them into one. This should very likely unblock the above error condition. 

Say if you have say 100 DFI made up of 20 utxos and 80 DFI tokens and you're unable to move the tokens. Using up, say 90 or 95 DFI in a DEX transaction will force the utxo consolidator to kick in. This can be a conversation back and forth, or a move into liquidity and then back out again if you have an equal token pair.  

The other options are more involved: 

2. Second option, is to provide the utxo input manually, with as low number of inputs as possible.  

3. If the minrelaytxfee was raised manually (which I don't see in the above comments - so I wouldn't recommend this for those users): lowering the `minrelaytxfee` by using in the `defi.conf` or back to the default, this can also get this moving again. (Note, however, if it's lowered below the default, this will very likely appear to have worked, but it's possible this tx might never get relayed to a miner to be included in a block and might just be stuck in the mempool, which then has to be cleared up. So wouldn't recommend doing this unless you're sure about what you're doing). 

While none of the above methods posses any direct risk to your funds, please only do the last two if you know what you're doing. 

And please note, these are just workaround to help unblock this scenario - we'll investigate this to have a better solution soon. 

---

[1] `minrelaytxfee` is a fee that's by default set to `0.00001000` by each node. If the transactions fees are below this, the node will choose not relay that transaction to other nodes (how transactions get propogated across the network until a miner can actually mine it in a block). In an ideal scenario, the tx that's created by either the node (or the app) should be above this.

**Comment by Timo258** [comment]
Ok, das geht dann wohl nur mit Cake Account, wo man die anderen Token hinsenden kann.

**Comment by memzila** [comment]
I have the same issue with version 2.6.3 on window 10

**Comment by prasannavl** [comment]
Hi everyone - thanks for the reports on this. We're investigating this - and please disgard my previous reply. It was incorrect - apologies. 

**Context**

What I _think_ is happening here, from quick glance, while the team is trying to reproduce the exact conditions to find out the cause: For every transaction, there is a calculation on the node before it submits the transaction (precisely when it's submitted to the mempool), to verify that the tx fee is greater than the `minrelayfee` [1]. However, while using certain specific methods, such as `accounttoutxos` and certain txs, the estimation for fees don't match up - my _current guess_ is it's only happening for certain specific txs. We're still investigating the exact conditions of this cause this. More on this soon - appreciate your patience. 

---

[1] `minrelaytxfee` is a fee that's by default set to `0.00001000` by each node. If the transactions fees are below this, the node will choose not relay that transaction to other nodes (how transactions get propogated across the network until a miner can actually mine it in a block). In an ideal scenario, the tx that's created by either the node (or the app) should be above this.

**Comment by mrgrauel** [comment]
The DEX work around doesn't work for me. Please keep us updated @prasannavl

**Comment by pmjlaw** [comment]
Unfortunately the work around in any case is costly if you plan to transfer your funds, had to pay 25 USDT (DEX: DFI-->USDT, Wallet-->CAKE´and from CAKE to exchange :(

**Comment by edgeball** [comment]
> Unfortunately the work around in any case is costly if you plan to transfer your funds, had to pay 25 USDT (DEX: DFI-->USDT, Wallet-->CAKE´and from CAKE to exchange :(

then use LTC instead

**Comment by Workoholic-Jap** [comment]
Das Workaround über BTC und dann nach Cake hat geklappt. Ist zwar teuer, aber wenigstens erledigt.

**Comment by mrgrauel** [comment]
@Bushstar I suppose it's not on the Mainnet yet? I still receive the error message. If not, do you have an ETA?

<img width="381" alt="image" src="https://user-images.githubusercontent.com/148758/132832903-af252f23-b93a-481c-975c-5a5cc99aa18a.png">

**Comment by thedoublejay** [comment]
We'll have an app release today to use the latest node version. We'll keep you posted

**Comment by thedoublejay** [comment]
Hey everyone, the new app version `v2.6.5` is now available. It is using the latest node with the fix for `min relay fees` . It's still on pre-release as we want to make sure that the issue has been fully resolved. Since it's an intermittent one, we would like to ask your help if this fixes the issue.  - https://github.com/DeFiCh/app/releases/tag/v2.6.5

**Comment by izzycsy** [comment]
Remember to backup your `wallet.dat` before testing `v2.6.5`.

**Comment by lraphael** [comment]
Tested with v2.6.5 and successfully fixes the problem (Mac OS X)

**Comment by RobinTorque** [comment]
I also just tested with v2.6.5 and the problem was fixed. 🥳

**Comment by nordi6000** [comment]
@izzycsy the problem with sending is fixed. 

But my Bitcoin in the (Beta) Wallet is missing :( 
![image](https://user-images.githubusercontent.com/49670309/132883112-27f78e71-2a4b-4dbb-8941-5413d3c6e17a.png)

Here my BTC address  :  bc1qrqczhshp2eumnluguw5h3ffvneef6grjc89esa

They must have 
![image](https://user-images.githubusercontent.com/49670309/132883267-3f8b9d30-a7d8-456f-a235-d79d6a6c4eb5.png)

**Comment by OtenMoten** [comment]
Works with App version `2.6.5` on my Ubuntu `20.04`
