### ISSUE TITLE
Cake defi 5 year freezer reward

### ISSUE THREAD

**Issue by TroFabian** [DeFiCh/app#1040]
#### What are your environment parameters?

- DeFi Wallet Version: 
- Operating System (OS): 
- Current free storage capacity:

**Comment by wmbst** [comment]
Cake is a company in Singapore. For Cake support, please contact the support directly at cake.

I am just a user like you, but I think i answer your questions best to my knowledge. For the 5 year freezer, cake hat to set up new master nodes which are frozen. New master nodes do not generate any income the first day. As Cake is forwarding the income to its users, the reward on the first day is lower. Please also check the cake telegram channels. everything was communicated there. At the auto-renew means, that you will automatically refreeze in 5 years for another 5 years. I don't think you want this so set it to off.

But as I said, for official Cake support and official answers please use the Cake support channels the next time.
