### ISSUE TITLE
After update 2.6.5 my BTC value in the BTC (beta wallet) missing

### ISSUE THREAD

**Issue by nordi6000** [DeFiCh/app#1043]
I install the Version 2.6.5 to fix the problem with the fee.
After the installation my BTC credit is 0.000000 
![image](https://user-images.githubusercontent.com/49670309/132921505-860558ec-50a9-4fe1-94c0-64136df9b832.png)

My BTC address: bc1qrqczhshp2eumnluguw5h3ffvneef6grjc89esa
![image](https://user-images.githubusercontent.com/49670309/132921590-391a6fa4-07a6-4275-aaaa-5e9e619f262d.png)

You can see the the balance of  0.0001 BTC in the Bitcoin explorer.
![image](https://user-images.githubusercontent.com/49670309/132921692-b38b1e58-ae60-4a1f-8a8b-af517fd93e46.png)

[Error_2.6.5.zip](https://github.com/DeFiCh/app/files/7146649/Error_2.6.5.zip)

- DeFi Wallet Version: 2.6.5
- Operating System (OS): Windows 10
- Current free storage capacity: HD 150GB / RAM 16 GB

**Comment by izzycsy** [comment]
Hi @nordi6000 , thanks for opening an issue. Please give us time to investigate.

**Comment by m1at1** [comment]
I also have this issue. For info: I had a crash on my linux machine, thenforce  re-indexed the wallet, then updated. ALl DFI balances working and showing. BTC beta wallet balance shows zero but all the transactions are as before.

**Comment by prasannavl** [comment]
Hi @nordi6000, @m1at1 - could you please help us with the following from the console in the app:  

1. `spv_getbalance`: Please let us know if the balance outpupt for this is also zero, just to make sure. 

1. `spv_syncstatus`: Please share this output. Both the current and estimated needs to be in sync with the bitcoin block height ideally (atleast above blockheight where your txes exist), otherwise the in-built SPV wallet may not be synced properly. If this is not, running `spv_rescan <rescan_from_blockheight>`, or just `spv_rescan 0` to rescan it all can help fix that.
  
1. `spv_getalladdresses`: Please run this and and check if your address is included in this output (No need to share this, just a yes/no for if your address is included in here).

**Comment by nordi6000** [comment]
Hi @prasannavl , I try but my balance show 0 look at the picture.

![image](https://user-images.githubusercontent.com/49670309/133787313-a4f889ba-daee-4fe1-a50e-efa97077acb7.png)

**Comment by m1at1** [comment]
On Fri, 17 Sept 2021 at 10:36, Prasanna Loganathar ***@***.***>
wrote:

> Hi @nordi6000 <https://github.com/nordi6000>, @m1at1
> <https://github.com/m1at1> - could you please help us with the following
> from the console in the app:
>
>    1.
>
>    spv_getbalance: Please let us know if the balance outpupt for this is
>    also zero, just to make sure.
>
>

>
>    1. Zero
>    2.
>
>    spv_syncstatus: Please share this output.
>
> { "connected": true, "current": 700939, "estimated": 700939 }
Correlates with recent blocks @ https://live.blockcypher.com/btc/

**Comment by nordi6000** [comment]
Hi @m1at1 look here...

![image](https://user-images.githubusercontent.com/49670309/133790329-8249b8a8-66f2-4d06-a27f-2b92aad4adcf.png)

**Comment by m1at1** [comment]
Hi Prasanna,

spv_rescan 0

fixed the problem, once the blocks were re-synched,

Matt

**Comment by nordi6000** [comment]
Hi @prasannavl okay, now I have my balance back. I think the spv_rescan 0 is working by me too. Thanks @m1at1 

![image](https://user-images.githubusercontent.com/49670309/133800600-565fa653-1411-49e4-8098-6c2d4f93a810.png)

**Comment by m1at1** [comment]
Maybe a refresh button &loading bar for the spvwallet could be included in
a future update?

**Comment by prasannavl** [comment]
Glad to hear the spv resync fixed it. 

Thank you for both the feedback and early adoption while the feature is in beta! The team is actively monitoring the user experiences and exploring how integrate these in the next interations.

**Comment by angelocastiglione** [comment]
Yes is working also for me, I have reinstalled OS + Defi Wallet and import my wallet with a backup .dat 

My balance DFI is ok but see BTC at zero :-(

For first i have type spv_getalladdresses and see that on the list my BTC address

Then use spv_rescan 0 and after few minute my balance BTC is displayed correclty.

Thanks for big support.
