### ISSUE TITLE
Not Able to swap BTC for DFI via DEX 

### ISSUE THREAD

**Issue by gwestcot** [DeFiCh/app#1045]
I have deposited BTC into the DeFi wallet and the balance is showing just fine in the balance area of the wallet. However, when I go to swap it for DFI in the DEX it shows my BTC balance as being zero. I would really love to get a few masternodes going but I need to swap to DFI with the DEX. Any help on this would be greatly appreciated.

- DeFi Wallet Version: 2.6.5
- Operating System (OS): Windows 10 Pro
- Current free storage capacity: 8.83 TB

**Comment by izzycsy** [comment]
Hi @gwestcot , at the moment BTC is a Beta feature (please use at your own discretion), hence you're unable to swap native BTC into any token within the app. If you would like to do so, you've to use Atomic Swap, which I would recommend if you're trying out the **Atomic Swap** feature. 

If you'd like to create a masternode, I would suggest that you send BTC to the DeFi app via CakeDeFi. Basically when sending tokens from CakeDeFi to DeFi app, your tokens will become wrapped (i.e. dBTC, dETH, dUSDT...), from there, you'll be able to swap to DFI. 

Providing the [DeFiChain Masternode](https://t.me/DeFiMasternodes) group for your reference, in there you'll be able to understand more about setting up a Masternode.

**Comment by Atomicwallettech** [comment]
> I have deposited BTC into the DeFi wallet and the balance is showing just fine in the balance area of the wallet. However, when I go to swap it for DFI in the DEX it shows my BTC balance as being zero. I would really love to get a few masternodes going but I need to swap to DFI with the DEX. Any help on this would be greatly appreciated.
> 
> 
> 
> - DeFi Wallet Version: 2.6.5
> 
> - Operating System (OS): Windows 10 Pro
> 
> - Current free storage capacity: 8.83 TB
> 
> 
> 
> 
> 
> 

Have you been able to swap now

**Comment by izzycsy** [comment]
Hi @gwestcot @Atomicwallettech , update [v2.7.0](https://github.com/DeFiCh/app/releases/tag/v2.7.0) is out, this is a **mandatory update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @gwestcot @Atomicwallettech , update [v2.7.1](https://github.com/DeFiCh/app/releases/tag/v2.7.1) is out, this is a **mandatory update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @gwestcot , closing this as it's not an issue at the moment, you can check out plans for 2022 via [YouTube](https://www.youtube.com/watch?v=DvY9kTTjzU8), ask on the community channels; [DeFiChain Telegram (EN)](https://t.me/defiblockchain) / [Reddit](https://www.reddit.com/r/defiblockchain/new/). Rest assured that your feedback has been sent to the team. Thank you for your valued feedback.
