### ISSUE TITLE
cannot send dfi tokens from the desktop application

### ISSUE THREAD

**Issue by belmaati** [DeFiCh/app#105]
Hello, I am unable to send challenged tokens from my desktop application wallet to another address. on the other hand it is possible to send usdt. but not dfi tokens

**Comment by izzycsy** [comment]
Hi @belmaati may I know what OS you're using? Could you describe your user flow more? Are you on Mainnet / Testnet? We need more details in order investigate how to reproduce this issue. Thank you!

**Comment by thunderstorm99** [comment]
This is what helped me. https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/

**Comment by izzycsy** [comment]
@belmaati did you manage to follow the steps that @thunderstorm99 sent?

**Comment by izzycsy** [comment]
Hi @belmaati , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue w new information (include screenshots) and your app logs. Thank you.
