### ISSUE TITLE
Mac OS 11.6: DST balances are displayed as 0, only DFI displayed

### ISSUE THREAD

**Issue by MichaelStaa** [DeFiCh/app#1053]
Did you finds a solution, because I have the same expiriense with 2.6.5. on Mac OS 11.6

_Originally posted by @MichaelStaa in https://github.com/DeFiCh/app/issues/1051#issuecomment-948811467_

**Comment by izzycsy** [comment]
Thanks @MichaelStaa . In the mean time, can you double check in your `defi.conf` that; 

```
spv=0
gen=0
```
<img width="735" alt="defi conf gen0" src="https://user-images.githubusercontent.com/65014479/140043672-a728e2e0-e8a4-4272-9f5b-d705b642a858.png">

If it's not, change it to 0 and save the file. Do not move the `defi.conf` out of it's original folder. 

——————————————
To find the `defi.conf` on Mac, **Go to Folder** and search: 
`/Users/username/Library/Application Support/DeFi/.defi/`

<img width="459" alt="Mac - Go To Folder" src="https://user-images.githubusercontent.com/65014479/140044168-7de42acd-6969-4a76-bb6d-800e5aa014a1.png">
<img width="439" alt="Go to Folder   Defi" src="https://user-images.githubusercontent.com/65014479/140044196-9b9f1146-16c9-4610-94c7-67f7c64b4b5c.png">

**Comment by MichaelStaa** [comment]
<img width="376" alt="Bildschirmfoto 2021-11-03 um 12 19 56" src="https://user-images.githubusercontent.com/92943489/140051435-3552f528-8ad5-488a-9d78-f235bf84a86e.png">
IT IS IN THE RIGHT FOLDER AND LOOKS LIKE YOURS !

**Comment by izzycsy** [comment]
Hi @MichaelStaa , thanks for the confirmation. Might I also check, what RAM and CPU are you operating with of your Mac? Could you a screenshot of your resource usage?

**Comment by MichaelStaa** [comment]
<img width="1280" alt="Bildschirmfoto 2021-11-05 um 10 29 25" src="https://user-images.githubusercontent.com/92943489/140489041-9212b2d4-c643-400e-b784-d4f1b74e51f8.png">
yes of course 
<img width="1280" alt="Bildschirmfoto 2021-11-05 um 10 29 15" src="https://user-images.githubusercontent.com/92943489/140489057-ac8a10ad-cc4e-4ec5-ad9f-c90d69776273.png">
<img width="1280" alt="Bildschirmfoto 2021-11-05 um 10 27 13" src="https://user-images.githubusercontent.com/92943489/140489058-2c9165b9-46ac-4318-b39d-84556b3708c1.png">
<img width="710" alt="Bildschirmfoto 2021-11-05 um 10 19 22" src="https://user-images.githubusercontent.com/92943489/140489059-61a4e4e7-86bb-4e08-8edc-65895f31f2a3.png">
<img width="500" alt="Bildschirmfoto 2021-11-05 um 10 18 08" src="https://user-images.githubusercontent.com/92943489/140489061-0892ff2f-367c-43eb-acc2-8674ff4a8922.png">

**Comment by MichaelStaa** [comment]
anything else you need ?

**Comment by izzycsy** [comment]
Hi @MichaelStaa , thank you. Based on your specifications, your Core m3 is a pretty slow processor, which leads to explain why your synchronisation is slow, but it should still sync. 

However, if your RAM usage is being almost maxed out — eg. running multiple applications on your MacBook, it's very likely the DeFi app will get slowed down exponentially (to the point that it won't function properly). Also, SSD (regardless of any kind), it can become taxing based on the factors explained above. 

Please give us time to further investigate why the GUI is displaying 0 for your other dTokens.

**Comment by izzycsy** [comment]
Hi @MichaelStaa , update [v2.7.0](https://github.com/DeFiCh/app/releases/tag/v2.7.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by MichaelStaa** [comment]
Hi have done the update and nothing has changed ! So where we are now ? how can I get to my tokens ? 
<img width="1136" alt="Bildschirmfoto 2021-11-12 um 15 19 38" src="https://user-images.githubusercontent.com/92943489/141481822-f67a77ad-8018-465e-8c1d-a1245b5b6a7a.png">
<img width="1136" alt="Bildschirmfoto 2021-11-12 um 15 19 18" src="https://user-images.githubusercontent.com/92943489/141481835-560d6cd9-301d-46a0-be0f-d793805acc12.png">

**Comment by izzycsy** [comment]
Hi @MichaelStaa , update [v2.7.1](https://github.com/DeFiCh/app/releases/tag/v2.7.1) is out, this is a **mandatory update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Can you update to the latest and see if the balances are reflected?

**Comment by MichaelStaa** [comment]
Well, yes I have updated, but nothing has changed :(
<img width="1213" alt="Bildschirmfoto 2021-11-15 um 16 14 17" src="https://user-images.githubusercontent.com/92943489/141808496-353a20e7-b98c-455b-b85b-019b59ac43bd.png">
<img width="1213" alt="Bildschirmfoto 2021-11-15 um 16 04 15" src="https://user-images.githubusercontent.com/92943489/141808505-896ec0ee-a481-49a8-a3cb-5be364fbc048.png">

**Comment by izzycsy** [comment]
Hi @MichaelStaa , thanks for the follow up, can you save your app & binary log, `.zip` it and send it here for investigation please. Thank you.

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/142182522-5652359e-e32b-4c77-b4d5-39440db5f15d.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/142182537-13bf5fdc-c82a-4440-8e4b-e4b82aad7679.png">

**Comment by MichaelStaa** [comment]
ok, here please 
[Uploading Archiv.zip…]()

**Comment by izzycsy** [comment]
Hi @MichaelStaa , thank you, please give us time to investigate.

**Comment by MichaelStaa** [comment]
> Hi @MichaelStaa , thank you. Based on your specifications, your Core m3 is a pretty slow processor, which leads to explain why your [synchronisation was slow](https://github.com/DeFiCh/app/issues/1051#issuecomment-948811467), but it should still sync.
> 
> However, if your RAM usage is being almost maxed out — eg. running multiple applications on your MacBook, it's very likely the DeFi app will get slowed down exponentially (to the point that it won't function properly). Also, SSD (regardless of any kind), it can become taxing based on the factors explained above.
> 
> Please give us time to further investigate why the GUI is displaying 0 for your other dTokens.
> 
> Can you in the mean time, restart your Mac, and **launch only** the DeFi App. Is the problem still persisting?

Is there any recommendations for mac - as I am looking into a new one now !

**Comment by izzycsy** [comment]
Hi @MichaelStaa , you could consider the [Macbook Pro 13inch (512GB?)](https://www.apple.com/shop/buy-mac/macbook-pro/13-inch). Mac's core processors are all M1 chip, so it's up to you on how much memory storage you'll need.

**Comment by MichaelStaa** [comment]
Hi izzycsy, I have order a new on as you mentioned (512GB)! Waiting to arrive beginning of December. I will let you now how it works after receiving.

**Comment by izzycsy** [comment]
Hi @MichaelStaa , congrats! In the mean time, please backup your wallets folder (if you did not specify another location), for Mac: you may find it here: 
Mac — Go to Folder: 
`/Users/<username>/Library/Application Support/Defi/wallets/` 

Full guide here: https://github.com/DeFiCh/app/discussions/988

**Comment by MichaelStaa** [comment]
now that I have a MacBook Pro I have installed the latest on a fresh machine. (2.7.3). All is much faster but even I can see "Liquidity" on the first page "Guthaben" I can not see my dTokens. All seems to be the same as prior and this is now since the update from 2.5 to 2.6 and further! 
<img width="176" alt="Bildschirmfoto 2021-12-03 um 14 31 40" src="https://user-images.githubusercontent.com/92943489/144611461-808eb384-4653-44bc-9177-feb696792e76.png">
<img width="176" alt="Bildschirmfoto 2021-12-03 um 14 29 21" src="https://user-images.githubusercontent.com/92943489/144611467-a791f32a-293e-4285-807b-2baf32752c82.png">
<img width="176" alt="Bildschirmfoto 2021-12-03 um 14 28 59" src="https://user-images.githubusercontent.com/92943489/144611468-df833547-7b9c-4899-bba9-b864c9dc5fe9.png">
<img width="176" alt="Bildschirmfoto 2021-12-03 um 14 50 21" src="https://user-images.githubusercontent.com/92943489/144613387-65188603-c864-4667-ada3-2f73773d8f39.png">

**Comment by MichaelStaa** [comment]
Ok, sorry but it seems I was to quick - or not waiting long enough. Well have a look it looks like all dTokens are back 
Thx 
new machine is working ! 
<img width="176" alt="Bildschirmfoto 2021-12-03 um 16 19 59" src="https://user-images.githubusercontent.com/92943489/144627388-efac558f-142c-4369-b4a3-437b85f27c85.png">

**Comment by MichaelStaa** [comment]
Mhhm picture is not showing ?! 
<img width="1136" alt="Bildschirmfoto 2021-12-03 um 16 23 29" src="https://user-images.githubusercontent.com/92943489/144627592-cb605f2a-ec7f-4b3b-ae3e-c7fc72514083.png">

**Comment by MichaelStaa** [comment]
will check with defiincome and if all is good - close

**Comment by izzycsy** [comment]
Hi @MichaelStaa , glad your issue has been resolved, just for your information, the latest version is [v2.7.3](https://github.com/DeFiCh/app/releases/tag/v2.7.3). Please remember to backup your `wallet.dat` often. Thank you, I'll be closing this issue.
