### ISSUE TITLE
Deactivate SPV in next wallet release by default

### ISSUE THREAD

**Issue by Mark76DefiChain** [DeFiCh/app#1059]
Please deactivate the SPV / native Bitcoin function by default in the next release. Too many people thinks they could send native BTC to the wallet and use the DEX

**Comment by izzycsy** [comment]
Hi @Mark76DefiChain , thanks for your feedback, will notify the team for consideration.

**Comment by izzycsy** [comment]
Hi @Mark76DefiChain , update [v2.7.0](https://github.com/DeFiCh/app/releases/tag/v2.7.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Mark76DefiChain , update [v2.7.1](https://github.com/DeFiCh/app/releases/tag/v2.7.1) is out, this is a **mandatory update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by AltCoiFish** [comment]
I am against it , as this feature should be developed further integrating it into DEX. 
I will open a new enhancement issue asking for this feature, as this enables true decentralization without CAKE involvement.
