### ISSUE TITLE
Defi wallet v2.6.5 not loading after upgrade to Mac OSX 12.0.1

### ISSUE THREAD

**Issue by stevemccann** [DeFiCh/app#1062]
#### Actual behavior:

When opening the app, it stays stuck at the loading screen. Does not appear to do anything.

#### Expected behavior:

When the app starts, after 20 or 30 seconds it will load the wallet interface.

#### How to reproduce it (as minimally and precisely as possible):

1. Upgrade Mac OSX to 12.0.1
2. Try to open Defi Wallet

#### What are your environment parameters?

- DeFiCh/app Version: 2.6.5
- Operating System (OS): Mac OSX 12.0.1 
– RAM (GB): 32
– CPU (Intel Core i5/i7/etc.): i7 2.6 GHz 6-core
- Current free storage capacity: 119 GB

#### Anything else we need to know?

I'm pretty sure the first time after upgrading, it worked. Now even after restarting, it's not working.

**Comment by izzycsy** [comment]
Hi @stevemccann , can you try restarting your Mac, and launch only the DeFi App. 

If the problem still persisting, may I know:
1. What RAM and CPU are you operating with of your Mac? 
2. Could you a screenshot of your resource usage? 
3. Kindly _.zip_ your app & binary log and send them for investigation please

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/140677269-9166c3e7-1d18-4c63-8cf3-827d98e3b943.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/140677278-b8203544-72ba-4721-b65e-35f21cc7b4dd.png">

**Comment by stevemccann** [comment]
I've attached the logs. Looks like somehow my defid dissappeared from /Applications/DeFi Wallet.app/Contents/Resources/binary/mac/defid

[2021-11-07 22:06:28.681] [IPC-RENDERER-error] [startBinary] "/Applications/DeFi Wallet.app/Contents/Resources/binary/mac/defid file not available"

[defichain_logs-1062.zip](https://github.com/DeFiCh/app/files/7494016/defichain_logs-1062.zip)

**Comment by izzycsy** [comment]
Hi @stevemccann , can you double check that you're missing defid, on Mac it's located here:
`/Users/username/Library/Application Support/DeFi/.defi/` 

If your defid is missing, you'll likely need to reinstall to resolve this. **Please backup** the `wallets` folder and store (copy & paste) it in another directory in your Mac; eg. `Documents`. 

<img width="269" alt="Menu bar   Backup Wallet" src="https://user-images.githubusercontent.com/65014479/140680801-8a8e7f50-2475-4de5-bda3-4ece900a19eb.png">


If you did not specify where to store your `wallet.dat`, you can find it in the `/Defi` folder, more details below.
In the wallets folder you'll likely see `wallet-bak-123456789` as well, these are additional backups. 

##### For Mac, it's located here:  Go To Folder
`/Users/<username>/Library/Application Support/Defi/wallets/`

<img width="459" alt="Mac - Go To Folder" src="https://user-images.githubusercontent.com/65014479/120080051-a8647180-c0e9-11eb-93b6-4af29d0c0da0.png">

<img width="822" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/120079154-3722bf80-c0e5-11eb-8722-b62bb308948a.png">


Refer to [this guide](https://github.com/DeFiCh/app/discussions/964) to reinstall.

**Comment by izzycsy** [comment]
Hi @stevemccann , update [v2.7.0](https://github.com/DeFiCh/app/releases/tag/v2.7.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. This comment is to notify you about the update.

**Comment by izzycsy** [comment]
Hi @stevemccann , update [v2.7.1](https://github.com/DeFiCh/app/releases/tag/v2.7.1) is out, this is a **mandatory update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @stevemccann , update [v2.8.4](https://github.com/DeFiCh/app/releases/tag/v2.8.4) is out, this is a **recommended update**. Kindly `backup wallet` and read through the release notes before updating. _This comment is to notify you about the update._
