### ISSUE TITLE
Snapshot download in Windows 11 not working

### ISSUE THREAD

**Issue by Garkh** [DeFiCh/app#1063]
#### Actual behavior:
The app freezes when i try to download a snapshot.

#### Expected behavior:
The Screen to download snapshots appears when i click on "Download Snapshot".

#### How to reproduce it (as minimally and precisely as possible):
1. Fresh install DeFiCh/app under Windows 11.
2. Start App and click "Download Snapshot"

#### What are your environment parameters?
- DeFiCh/app Version: 2.7.0
- Operating System (OS): Windows 11 Pro Insider Preview
– RAM (GB): 12
– CPU (Intel Core i5/i7/etc.): Intel Core i7-5600U
- Current free storage capacity: 207GB

#### Anything else we need to know?
I think this is a windows 11 only problem.
When i look at the App Logs i get a entry with the message:
Error: Command failed: wmic logicaldisk get Caption,FreeSpace,Size,VolumeSerialNumber,Description  /format:list
Der Befehl "wmic" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

The german part of the message says command "wmic" not found.
I researched a bit and found out that "wmic" was removed in windows 11 dev build.

Edit: I uploaded my App Logs
[app.log](https://github.com/DeFiCh/app/files/7514292/app.log)
.

**Comment by thedoublejay** [comment]
Hi @Garkh I'm using Windows 11 also and snapshot works fine for me. What's your Windows 11 build version?

**Comment by Garkh** [comment]
Hey thanks for your reply.
I'm currently using build "22494.1000".

Do you have a "wmic.exe" in your "C:\Windows\System32\wbem"-Folder?
What happens, when you type "wmic" in powershell?

**Comment by izzycsy** [comment]
Hi @Garkh , update [v2.7.1](https://github.com/DeFiCh/app/releases/tag/v2.7.1) is out, this is a **mandatory update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by thedoublejay** [comment]
@Garkh Yes I have this folder

**Comment by izzycsy** [comment]
Hi @Garkh , update [v2.14.0](https://github.com/DeFiCh/app/releases/tag/v2.14.0) is out, this is a **recommended update**. Kindly `backup wallet` and read through the release notes before updating. Do note that [v2.13.0](https://github.com/DeFiCh/app/releases/tag/v2.13.0) is mandatory. Kindly `backup wallet` and read through the release notes before updating.

I'll be closing this issue in the mean time. You may reopen this issue if there's new information (include screenshots) and your app logs. Thank you.
