### ISSUE TITLE
BTC are not displayed in the wallet after update to 2.7.0

### ISSUE THREAD

**Issue by nordi6000** [DeFiCh/app#1065]
Update DeFi Wallet from 2.6.5 to 2.7.0 

after update my 0.001 BTC in the (Beta) Wallet are missing. 

I try

spv_getbalance
0
spv_syncstatus
{
  "connected": true,
  "current": 438000,
  "estimated": 709266
}

spv_rescan 0
null

![image](https://user-images.githubusercontent.com/49670309/141346215-35239cbe-9cb8-44e8-b2f0-b392e081ef50.png)

- DeFiCh/app Version: 2.7.0
- Operating System (OS):  Windows 10
– RAM (GB):  16 GB
– CPU (Intel Core i5/i7/etc.):  Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
- Current free storage capacity: 380 GB

**Comment by izzycsy** [comment]
Hi @nordi6000 , can you try restarting your app and type this in the CLI:
`spv_rescan 672683`

**Comment by izzycsy** [comment]
Hi @nordi6000 , can you try the following: 
1. Restart app
2. In CLI type `spv_rescan 672683`
3. Type `sync_syncstatus` to make sure that scanning is progressing from block 672,683 and above. All Bitcoin TXs in the wallet will be in a Bitcoin block above that height.

**Comment by nordi6000** [comment]
Hi @izzycsy , thank you for you support. I load my backup (wallet.dat) file again and than with spv_rescan 0 the balance was good.

Think you can close the issue...
