### ISSUE TITLE
Tokens not arriving in my wallet

### ISSUE THREAD

**Issue by Ausafari** [DeFiCh/app#107]
Hi,
I sent the below transaction (see screenshots) last night as a test to the wallet address I set up in your DeFi app.
The tokens haven't arrived, which is surprising - and yes I have refreshed the balance in the wallet app.
I checked again this morning - nothing.
I then tried to reset the wallet and now the app won't even synchronise (it's been stuck on the below Block for well over an hour this morning).
![defi-wallet-stuck](https://user-images.githubusercontent.com/75756887/101685749-dd392980-3ab3-11eb-852f-b963f1a052da.jpg)

I've included the logs below too, as advised on this page: https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-Defi-App . However the config log can't be sent, as the file extension is .config, which is not supported by this site.

![defi-wallet-address](https://user-images.githubusercontent.com/75756887/101684923-da8a0480-3ab2-11eb-92a1-fe3dbfea78ed.jpg)
![defi-wallet-01](https://user-images.githubusercontent.com/75756887/101684932-df4eb880-3ab2-11eb-83d0-8c5847144585.jpg)
[app_log.log](https://github.com/DeFiCh/app/files/5668565/app_log.log)
[binary_log.log](https://github.com/DeFiCh/app/files/5668562/binary_log.log)

Please advise what to do next to resolve this issue.
Thanks!

**Comment by izzycsy** [comment]
Hi @Ausafari , thank you for your feedback, your balances should appear after synchronization is completed. 
Have you tried `Reindex option`? 
When syncronization is complete, you may then `Import Wallet` / `Restore Wallet` via mnemonic seed. 

If you're not on the latest v2.1.3, you may download it here <https://github.com/DeFiCh/app/releases/tag/v2.1.3>. 

<img width="1017" alt="201112 Reindex" src="https://user-images.githubusercontent.com/65014479/101876773-f03d1e00-3bc7-11eb-85c1-6317931d5db9.png">

**Comment by Ausafari** [comment]
Hi, thanks for your help. 
No - I haven't tried the ReIndex option and the synchronisation has gone nowhere for the past 48hrs+. That is, it is sitting on block 474985 and has not moved. I am using the latest version of the wallet - and even deleted the app and re-installed it to see if that might help - to no avail.
So, should I try the ReIndex option before synchronisation happens - given that process has gone nowhere for the past 48hrs+?

**Comment by Ausafari** [comment]
I have gone ahead and used the ReIndex option. The good news is:
. Synchronisation completed successfully.
. I was able to restore my wallet using the mnemonic phrase.
The bad news:
. My DFI balance still shows zero, when it should show 700DFI.

**Comment by izzycsy** [comment]
@Ausafari glad to hear your synchronization is successful. 
In the CLI, you can check your balance by typing: 
`getbalance` — UTXO DFI, DFI that you receive / send to your Defi app
`gettokenbalances` — DFI

The sum of both are your DFI displayed in your wallet.

You may try clicking on another tab in the wallet, sometimes the app lags so the balances are not displayed for awhile.

**Comment by Ausafari** [comment]
Thanks - the balance of 700 DFI is now appearing after I clicked another tab in the wallet. Thanks for your help. Now all I need to do is work out how to undertake Liquidity Mining on the app, as I am going around and around in circles, with no luck whatsoever. :/

**Comment by izzycsy** [comment]
Hi @Ausafari , good to know! You may actually join the Telegram Channel and learn more the community, or ask questions that you might have. Here's a quick how-to on LM <https://defichain.com/learn/liquidity-mining-how-to/>.
