### ISSUE TITLE
Node v2.2.0 - CLI error when typing "help"

### ISSUE THREAD

**Issue by brotwal** [DeFiCh/app#1070]
Hey there, 

just tested the CLI with the new desktop wallet (v2.7.1 and node v2.2.0) and when typing "help" i get the following error: "reward address change is disabled for Fort Canning".
What's happening here? Is it something serious, that a few commands got exchanged internally? In general: Is somebody else experiencing this issue?

Thx in advance

**Comment by thedoublejay** [comment]
Hi @brotwal, it's not a serious issue but we have already raised it on the node side. Please refer to this ticket - https://github.com/DeFiCh/ain/issues/903

**Comment by izzycsy** [comment]
Regarding the issue [`help rpc not working with 2.2.0`](https://github.com/DeFiCh/ain/issues/903), we can further discuss on the issue there. We would like to keep same issues in one thread. Closing with comment. Thank you.
