### ISSUE TITLE
Snapshot downloads into ~/snapshot

### ISSUE THREAD

**Issue by thunderstorm99** [DeFiCh/app#1072]
#### Actual behavior:
Snapshot are being downloaded to ~/snapshot

#### Expected behavior:
Snapshots should be placed into ~/.defi/snapshot as to not interfere with the host system

#### How to reproduce it (as minimally and precisely as possible):
1. Start a fresh install of DeFi Wallet
2. Download a snapshot

#### What are your environment parameters?

- DeFiCh/app Version: 2.7.1
- Operating System (OS): Linux
- RAM (GB): 16
- CPU (Intel Core i5/i7/etc.): Core i5
- Current free storage capacity: Enough

#### Anything else we need to know?
I already proposed a pull request to fix this issue. See https://github.com/DeFiCh/app/pull/1066

**Comment by thedoublejay** [comment]
Hi @thunderstorm99, I saw your PR and will check and test to see if we can include it on our next build.

**Comment by thunderstorm99** [comment]
@thedoublejay the pull request had a small error that you merged into main. The fix is already in place and needs to be re-committed.
