### ISSUE TITLE
How can I use the second DFI-Adress in my wallet to send DFI

### ISSUE THREAD

**Issue by SKapi1985** [DeFiCh/app#1075]
#### How to reproduce it (as minimally and precisely as possible):

When receiving DFI, you can easily select your address:
![grafik](https://user-images.githubusercontent.com/84380674/142415724-37a2a181-82c0-4cf1-b468-08798a0fc63a.png)

When sending DFI, however, you cannot select a sending address and the first address is selected by default.
![grafik](https://user-images.githubusercontent.com/84380674/142415822-a64a2121-4fb9-41f8-b95e-edafdd10afbb.png)

I haven't found a function anywhere to change the default address. Please help! Thank you very much.

#### What are your environment parameters?

- DeFiCh/app Version:
- Operating System (OS): 
– RAM (GB): 
– CPU (Intel Core i5/i7/etc.): 
- Current free storage capacity:

**Comment by SKapi1985** [comment]
OK, I saw it was related to problem #913 that I couldn't send anything specifically from my second address. Now I have noticed that the credit from several addresses is combined when sending. But as an improvement for the app, it would make sense to be able to choose exactly which account you want to send DFI from. For example, if you want to separate several accounts for family members or private and business accounts. Thank you.

**Comment by izzycsy** [comment]
Hi @SKapi1985 , your feedback has been conveyed to the team, however I do not have a timeline on whether and when this would be implemented. Just wanted to update you before this thread becomes stale. Rest assured that it'll be considered by the team. There are [plans](https://github.com/DeFiCh/wallet/issues/910) for multi addresses — like in the comment you mention. If you want a quicker access to this feature, I would suggest [DeFiChain Light Wallet](https://github.com/DeFiCh/wallet). You can download from the app store, **Create Wallet** then transfer you funds to continue where you left off. 

Do note that the Desktop app and Light Wallet are built differently, hence you won't be able to Restore via Wallet Backup on the mobile wallet. Thank you for your patience.
