### ISSUE TITLE
White Window at DEX adding value to exchange pair DFI- dTESLA

### ISSUE THREAD

**Issue by OKnr66** [DeFiCh/app#1078]
#### What are your environment parameters:
DEFIChain Wallet 2.7.2
Windows 10 64 BIT

#### Anything else we need to know?:
DEX: DFI -> dUSD -> OK Second: dUSD -> dTESLA is also okay.

**Comment by OKnr66** [comment]
https://user-images.githubusercontent.com/76753391/143218320-34d24dad-522f-47d1-8749-9aafe69aa5c2.mov

Video shows behaviour. Sorry during conversion it has been 90 degree flipped. But it can be recognized.

**Comment by OKnr66** [comment]
Maybe it is solved with the next version, because 2 swaps will be included! If it is so, you can close it.

**Comment by thedoublejay** [comment]
Hi, currently we will not yet support composite swaps on the next app update due to some issues. But for now, you can do poolswaps to achieve this - https://github.com/DeFiCh/app/releases/tag/v2.7.3

**Comment by izzycsy** [comment]
Hi @OKnr66 , has your issue been resolved?

**Comment by Ironcheese** [comment]
I have the same issue with Version 2.8.1 and by just selecting the "dGME" Token on "Add Liquidity".
As soon as I select the dGME Token in the right dropdown list, the whole app goes blank white.

If I select dGME on the left list, the right list wont populate and stay empty.
