### ISSUE TITLE
Update pool pair listings

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/app#1079]
#### Actual behavior:
1. LP are missing Total Liquidity (USD) on desktop app
2. no further pages that displays the other pool pair available
<img width="748" alt="Screenshot 2021-11-29 at 10 26 20 PM" src="https://user-images.githubusercontent.com/65014479/143894297-e72eb718-2a65-478d-aa3e-838a1a344b01.png">

3. LP for DUSD-DFI not shown yet, up till dUSDC-DFI
<img width="749" alt="Screenshot 2021-11-29 at 10 33 08 PM" src="https://user-images.githubusercontent.com/65014479/143894848-89b4da26-0491-408d-9a11-de738ffd5fdb.png">

#### Expected behavior:
• All Liquidity Pool tokens to reflect `Total Liquidity (USD)`, if exceed threshold, bring to next page

#### How to reproduce it (as minimally and precisely as possible):
• Liquidity > scroll to view

#### What are your environment parameters?

- DeFiCh/app Version: v2.7.2
- Operating System (OS): MacOS 10.15.7

**Comment by Darkman-Q-Tester** [comment]
Please fix this as fast as possible, we need the other pairs like SPY-DUSD, BABA-DUSD, ...

**Comment by thedoublejay** [comment]
Updated on https://github.com/DeFiCh/app/releases/tag/v2.7.3 @Darkman-Q-Tester
