### ISSUE TITLE
Sync performance very poor

### ISSUE THREAD

**Issue by amainz** [DeFiCh/app#1082]
Performance is pretty poor to sync blocks since the last app versions. I cannot keep up with updating the blocks. I always start with a snapshot. 
I started with a gap of 2500 blocks to current block. After 2 hours running I got only progress of 400 blocks closer to current block since more blocks are created every minute.

#### What are your environment parameters?

- DeFiCh/app Version: 2.7.3
- Operating System (OS): Win10
– RAM (GB): 16 GB (used 7 GB)
– CPU (Intel Core i5/i7/etc.): i5 (load 40%)
- Current free storage capacity: 50 GB (SSD)

#### Anything else we need to know?

[defilogs.zip](https://github.com/DeFiCh/app/files/7647936/defilogs.zip)

**Comment by izzycsy** [comment]
Hi @amainz , you can use [snapshot for faster synchronization](https://github.com/DeFiCh/app/discussions/899). Alternatively, switch to [DeFiChain Light Wallet](https://github.com/DeFiCh/wallet) on your mobile phone to save the hassle of running a full node wallet.

**Comment by amainz** [comment]
> 

I always start with a snapshot, but even this small amount of missing blocks cannot be handled in a short timeframe. This remaining syncing is really slow.

**Comment by izzycsy** [comment]
Hi @amainz , running less applications on your PC when the app is syncing the last few blocks would help, also good internet connection.

**Comment by Esmiraldana** [comment]
I have exactly the same issue. But I have a gaming PC with 8 Core and 500mb internet. What is going on since 2.73 this wallet ia unusable. 
Is there any link to download an older version maybe that is faster?

**Comment by amainz** [comment]
@izzycsy I posted above the system utilization of my PC. As well the DSL bandwidth is not used at all. This is not a problem. The block syncing rate is extremely low since the last releases. Before it was also not good, but now you cannot sync properly. Can you please investigate?

**Comment by Esmiraldana** [comment]
Is there any older version after the last hardfork that is working faster? sb can provide download links?

**Comment by izzycsy** [comment]
Hi @amainz @Esmiraldana , thanks for your feedback, for your safety and security I do not recommend installing older version / deleting any files you're unfamiliar with, do keep your `wallet.dat` safe. Our team is constantly working on improving the app and solving its issues. Please give us time to investigate. Thank you for your understanding.

**Comment by izzycsy** [comment]
Hi @amainz @Esmiraldana , update [v2.8.0](https://github.com/DeFiCh/app/releases/tag/v2.8.0) is out, this is a **mandatory update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @amainz @Esmiraldana , update [v2.8.1](https://github.com/DeFiCh/app/releases/tag/v2.8.1) is out, this is a **recommended update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by amainz** [comment]
@izzycsy I do not see any improvements in the last 2 versions regarding the performance. Still poor.

**Comment by Esmiraldana** [comment]
same for me!

**Comment by izzycsy** [comment]
Hi @amainz @Esmiraldana , did you [`reindex wallet`](https://github.com/DeFiCh/app/discussions/899)? 

<img width="271" alt="Menu bar   Re-index Wallet" src="https://user-images.githubusercontent.com/65014479/145728862-34680d16-500b-4549-82d7-6d42b8d8a3ab.png">

**Comment by amainz** [comment]
@izzycsy I am using all the time the snapshot since the sync performance is very poor. 

As per your request I restarted the syncing via "reindex wallet". Attached the results after 6 hours (not even reached 50% of all blocks). 
![defi_sync](https://user-images.githubusercontent.com/29411467/146006335-9b7c04a1-d075-4072-8ab5-eecf9c1fc763.png)


You can see sync rate is less that 200 blocks per minute. Out of experience the sync rate is much lower when you are in the 90% range (snapshot start).
My PC is stable with all resources nothing at limit at all.

**Comment by izzycsy** [comment]
Hi @amainz , can you try the latest update: [v2.8.3](https://github.com/DeFiCh/app/releases/tag/v2.8.3) 
Kindly backup your wallet.dat and read through the change log before updating

**Comment by amainz** [comment]
Hi @izzycsy
Thank you for the update. I did an update to v2.8.3 and started with the snapshot. Sync rate is at 10 blocks/min, so still a poor performance.
Please keep me posted on progress of this issue.

**Comment by izzycsy** [comment]
Hi @amainz , can you try the latest update: [v2.8.4](https://github.com/DeFiCh/app/releases/tag/v2.8.4)

Kindly backup your wallet.dat and read through the change log before updating. This is a **recommended** update.

**Comment by amainz** [comment]
Hi @izzycsy
Not better after update. Sync rate is at 12 blocks/min only.

**Comment by izzycsy** [comment]
Hi @amainz , if it's at 12 blocks /minute ; that's actually quite fast.

**Comment by amainz** [comment]
Hi @izzycsy,
Considering the gap from the last update and its snapshot I would need now 17 hours to sync to current status plus the blocks done at this time too. This is really slow.
As you can see on the excel table above the sync rate per minute was 12x more at lower block levels.

**Comment by amainz** [comment]
Hi @izzycsy ,
I just used the "Defi Portfolio" and updated the blockchain via this app. The sync rate is at 240 blocks/min with "Defi Portfolio". After the update of the blockchain I opened "Defi Wallet" app  and everything is updated. It seems that the "Defi Wallet" App has this low sync issue.

**Comment by izzycsy** [comment]
Hi @amainz , thanks for the update, our team will continue to look into the issue.

**Comment by izzycsy** [comment]
Hi @amainz @Esmiraldana , update [v2.9.1](https://github.com/DeFiCh/app/releases/tag/v2.9.1) is out, this is a **mandatory update**. Kindly `backup wallet` and read through the release notes before updating.

**Comment by amainz** [comment]
@izzycsy Hi, 
I tried this version when it came out directly. No improvement in performance.

**Comment by izzycsy** [comment]
Hi @kjb92 , the latest version is [v2.10.0](https://github.com/DeFiCh/app/releases/tag/v2.10.0). Do you have other `wallet.dat` files? If you did not specify where you saved your `wallet.dat` on your Mac, it will be located here:

For Mac — Go to Folder:
`/Users/<username>/Library/Application Support/Defi/`

<img width="459" alt="Mac - Go To Folder" src="https://user-images.githubusercontent.com/65014479/161915160-29ecd213-6eda-4ad4-a2df-caf2161c3db2.png">

<img width="439" alt="Go to Folder   Defi" src="https://user-images.githubusercontent.com/65014479/161915177-aeaa8c78-cec1-4af3-98ac-d6830bbb59d8.png">

<img width="823" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/161915217-59fff463-83f3-46d4-af77-156411a559b6.png">

In the **wallets** folder you'll likely see wallet-bak-123456789 as well, these are additional backups. Full guide on how to Restore Wallet: #988

**Comment by nippur72** [comment]
I have this issue since long time, six months or more. I have a fast Windows machine and fast connection. If I open Window's task manager, I see that the "defid" process has a very high CPU load (which is unusual). 

I updated to v2.11.0 but nothing changed.

**Comment by izzycsy** [comment]
Hi @nippur72 @amainz @Esmiraldana , update [v2.11.0](https://github.com/DeFiCh/app/releases/tag/v2.11.0) is out, this is a **mandatory update**. Kindly `backup wallet` and read through the release notes before updating. 

After updating and synchronizing to 100%, if you face the same issue, kindly send your app log & node log. 

<img width="275" alt="1 App logs" src="https://user-images.githubusercontent.com/65014479/163754361-dfde531c-c094-413b-93be-39aaa77790cd.png">

<img width="547" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/163754366-d8c8a415-0414-496d-b9e4-b84f36450c1e.png">

Transferring issue to [DeFiCh/ain](https://github.com/DeFiCh/ain/issues).

**Comment by nippur72** [comment]
Attached are my v2.11.0 logs as it's still slow to synch: [app_and_node_logs.zip](https://github.com/DeFiCh/app/files/8504295/app_and_node_logs.zip)

Below a screenshot of task manager where you can see defid is eating CPU time:
![image](https://user-images.githubusercontent.com/2598443/163773855-e7b1aea7-219f-4638-81a5-843b6c2cd917.png)

**Comment by amainz** [comment]
@izzycsy The sync performance is 0 blocks/hour. I see a lot of network errors in the logs. So, it is even worse with this version. 
Attached the logs.
[Defi_logs.zip](https://github.com/DeFiCh/app/files/8507028/Defi_logs.zip)

Thank you for your help.

**Comment by izzycsy** [comment]
Hi @nippur72 @amainz @Esmiraldana , update [v2.12.0](https://github.com/DeFiCh/app/releases/tag/v2.12.0) is out. 
1. Please **backup wallet** 
2. Update to v2.12.0 
3. Select [Reindex Wallet & sync with snapshot ](https://github.com/DeFiCh/app/discussions/899)

**Comment by amainz** [comment]
@izzycsy Same as before: syncing in not working. 0 blocks synced after 35 minutes. Logs attached
[Defi_logs.zip](https://github.com/DeFiCh/app/files/8638083/Defi_logs.zip)
 
Is your team actually working on this bug? I see only the request each time a new version comes out to re-check, but nothing is in the change logs about this bug. No offense.

Thank you for your support.

**Comment by kjb92** [comment]
Hey everyone, I was one of the people who had this issue now for several months too and just yesterday I was able to fix it! My wallet is now running super smooth. I'm not sure if it will work for you as well, but I'll just share what I did and maybe you are lucky too: 

So, I'm running the wallet on macOS. I did the latest update to v.2.12.0 as @izzycsy told us to — BUT this time, what I did BEFORE installing the new app version was **manually deleting all the data the app has created so far on my computer**. On a mac you will find all this app data in the "application support" folder (finder-> go to folder). There, the app installs 2 folders named "defi" and "defi-wallet". I deleted both of them. **CAUTION**: make sure you saved a copy of your wallet-backup file(s) (.dat) before doing that. I chose the very first backup file I ever created for my wallet, saved it somewhere else and then went on with deleting those two folders. I thought: "hey, let's just reset everything" (— I tried the reindex wallet action in the app before and it didn't work for me, spent hours and days trying to synch it, so this time I thought: let's do it the hard way!) — **and that actually worked**! After deleting the 2 folders, I installed the latest app version, pulled the latest snapshot, waited for the synch to be completed and then imported my wallet-backup file. After just a few minutes all my assets were there and the node was synched completely! And the wallet usability since then is just outstanding now: sending funds out, adding liquidity, etc. — I'm getting a whole new experience with this app now! :D 

Now, I'm definitely no expert on this, but I seems like there was something messed up somewhere in all the "data clutter" and manually deleting all of that and re-installing the app from scratch somehow solved it for me. (however, re-indexing or synching the node from scratch before did not do the job). I hope you are as lucky as I am! Let me / the others know if it worked for you as well or not.

@izzycsy hope this helps you and your team as well?

**Comment by izzycsy** [comment]
Hi @kjb92 , good to hear! Yes, what you did was [reinstall DeFiChain app](https://github.com/DeFiCh/app/discussions/964). But as you mentioned it's key to **backup your wallets folder** as without it you wouldn't be able to restore wallet. We are not responsible for your wallets, so please remember to backup often! Thank you @kjb92 . 

> The first half of this guide will show you [how to backup wallet](https://github.com/DeFiCh/app/discussions/988)

Hi @amainz yes, we try to make sure you're on the latest version and see if you're still facing the same issue, in extreme cases, we would suggest what @kjb92 did. In case user makes a mistake and forgets to backup. You can try what @kjb92 did. Please follow the steps thoroughly. 

cc: @nippur72 @Esmiraldana

**Comment by amainz** [comment]
Hi @izzycsy ,
I deleted the whole installation on my windows computer and re-installed the defi-app and started with the snapshot.
Surprisingly, the sync for the remaining blocks was done in 10 minutes and the sync was completed.
Now, I had the option to install my backup wallet. After that step the syncing of blocks stopped. After 1 hour, no additional block has been synced.
So, the syncing issue occurs only after I installed my backup walltet. Hope this helps for the triage.

Here the logs: 
[Defi_logs.zip](https://github.com/DeFiCh/app/files/8645615/Defi_logs.zip)

Thank you for your help.

**Comment by izzycsy** [comment]
Hi @amainz , update [v2.13.0](https://github.com/DeFiCh/app/releases/tag/v2.13.0) is out, this is a **mandatory update**. Kindly `backup wallet` and read through the release notes before updating.

You may refer to the 2nd part of this guide to [Restore Wallet from Backup](https://github.com/DeFiCh/app/discussions/988). 

<img width="823" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/172090907-7f5a185f-f80d-40a7-8667-1c58a6bf3191.png">
 
^ Inside your `wallets` folder should contain other `wallet.dat` backups, try restoring from those additional backups. You can find them via this file route: 
Windows — C:  `\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets`

**Comment by amainz** [comment]
Hi @izzycsy
Finally I was able to sync completely after downloading the snapshot.
Sync rate is at 20 blocks/minute. Not fast, but I could reach the last block, which did not work the past releases.

So, further improvements on the performance would be great.

Thank you.

**Comment by izzycsy** [comment]
Hi @amainz , thanks for the update, sync rate getting slow is expected as the difficulty per block increases; it's part of running a full node wallet. I would suggest moving to [Light Wallet](https://github.com/DeFiCh/wallet), you can download it from App Store / Play Store. 

An FYI, The DeFiChain [Light Wallet app](https://github.com/DeFiCh/wallet)'s & [Desktop app](https://github.com/DeFiCh/app)'s restoration methods are irrelevant; meaning to say you can't load the 24 words from mobile app on to the desktop app and neither can you load the `wallet.dat` from the desktop to mobile. If you would like to use the mobile app (**saving the hassle of running a full node wallet**), you'll have to create a new wallet and transfer your funds to the mobile app. The team is currently working on integrating the mobile & desktop app — so you can use the same 24 words account concurrently. As for now, these are 2 independent applications. 

I'll be closing this issue in the mean time. You may reopen this issue if there's new information (include screenshots) and your app logs. Thank you.
