### ISSUE TITLE
Rewards are not included in history when "up to block height" block value is changed

### ISSUE THREAD

**Issue by ab3dat** [DeFiCh/app#1084]
#### Actual behavior:
When I try to export the transaction history with option "include rewards" activated, the export also includes the rewards. 
But as the export fails when trying to export more than 2100000 transactions, I tried to export with value "up to block height" set to 1300000. Even if "include rewards" is set and no matter how I tried to set the values in the dialog ("up to" first, than number of transactions or vice versa or activating the "include rewards" at the beginning or end), the export does not inlcude the rewards.

#### Expected behavior:
Either, it is possible to export more than 2100000 transactions, which may also be a problem of too less memory (export sometimes needs more than 12 GB of RAM)
or
the exported transaction history covers the rewards too, even if exported from a block somewhere in between.

#### How to reproduce it (as minimally and precisely as possible):
Only the not working way is described here:
1) Open transaction, wait until loaded
2) Activate "include rewards" option, wait until loaded
3) Open "Export wallet data" dialog
4) Set "up to block height" value to, e.g. 1250000 (or one of the last block height values of the last log file startet from max. block height)
5) Set number of transactions, wait until export button gets active
6) Activate option "include rewards" and wait until export button gets activate again (NOTE: this doesn't by far take nearly as long, as if you try to export 2000000 transactions incl. rewards from max. block height)
7) Click export and save data -> only transcation without rewards are shown

#### What are your environment parameters?

- DeFiCh/app Version: 2.7.3
- Operating System (OS): Win 10
– RAM (GB): 16 GB
– CPU (Intel Core i5/i7/etc.): Core i7
- Current free storage capacity: 117 GB

#### Anything else we need to know?
It already worked in the past, I think with version 2.5.x or so

[ab3d_logs.zip](https://github.com/DeFiCh/app/files/7660736/ab3d_logs.zip)

**Comment by izzycsy** [comment]
Hi @ab3dat , could you transfer your comment to [Export Button is clickable too early](https://github.com/DeFiCh/app/issues/979), we can further discuss/follow up on the issue there. We would like to keep same issues in one thread. The team is aware of this issue.Thank you.
