### ISSUE TITLE
Removal of vault collateral not possible 

### ISSUE THREAD

**Issue by derstrecker** [DeFiCh/app#1085]
#### Actual behavior:
While removing collateral in an active vault with a loan I receive the error message „Error Code 0 400“ as attached; 
![Uploading 9D38BE80-1CA6-4DB8-ABDB-D7402F922347.jpeg…]()
in the DFX wallet. 
I had 470% over collateralised with at 150% loan scheme, trying to remove 1-2% of dBtc to achive a 50%+ value of the Dfi-part. Thos would not have let to a liquidation.

#### Expected behavior:
Should remove Collateral.

#### How to reproduce it (as minimally and precisely as possible):
- Remove Collateral in the DFX Light Wallet. Collateral 49% DFI and 51% dBTC.

#### What are your environment parameters?

- DeFiCh/app Version: DFX Wallet v0.17.1
- Operating System (OS): iOS mobile
– RAM (GB): -
– CPU (Intel Core i5/i7/etc.): iPhone 12 Pro Max
- Current free storage capacity: enough 
![04659619-11F0-4101-A2BA-2DBDB82FBC04](https://user-images.githubusercontent.com/90353867/144849600-a2540f8a-39ee-4eaf-8e3b-222025d58165.jpeg)

**Comment by izzycsy** [comment]
Hi @derstrecker , this GitHub is for DeFi desktop app issues. For DFX issues you may enquire with them @ https://t.me/DFXswiss.

**Comment by derstrecker** [comment]
This issue happens exactly with the DeFiChain mobile wallet, too. And I found out, if DFI > other collateral, then a removal is working of any collateral. But if DFI < other collateral, means DFI is below 50%, denn the removal of the other 50%+ collateral is not working. May you reopen the issue or should I post another one?
