### ISSUE TITLE
Vault History

### ISSUE THREAD

**Issue by salomonkarsten** [DeFiCh/app#1086]
In case one gets liquidated, how to see the related liquidation transaction. I found nothing searching my transactions using the desktop wallet or listaccounthistory command. Please advise or improve a vault history feature.

**Comment by izzycsy** [comment]
Hi @salomonkarsten , thanks for your feedback. There's no history for vault at the moment, it will be closed when liquidated.

**Comment by salomonkarsten** [comment]
@izzycsy so why does the help function show this command? Further it would be great to get a history espeacially of the interest rate collateral and loan.  Same result as getvault but from a specific block. Is that possible?

**Comment by izzycsy** [comment]
Hi @salomonkarsten , `listaccounthistory` is to list the latest transactions related to the user’s address. You may see what's in store for Vault on [DeFiCh/wallet](https://github.com/DeFiCh/wallet). Thank you.
