### ISSUE TITLE
I did not see any LM rewards for the dTokens yesterday.

### ISSUE THREAD

**Issue by kmeans27** [DeFiCh/app#1092]
Hello, I received awesome LM rewards after the launch. But yesterday almost no rewards were coming in.

I did swap some tokens and added them to the liquidity pool. Can you check my adress & check if my liquidity is successful added into the pool?

adress: dQkTkboCsUFXfSrNXMy18jZqVAV3TEoBKr

Thank you so much! Love the project :-)

**Comment by izzycsy** [comment]
Hi @kmeans27 , you can check it yourself with the txid on [DeFiScan](https://defiscan.live/). There was a stall in the blockchain yesterday, which requires an update of the app, please update and it sync to 100% — should be fixed. Latest version [v2.8.0](https://github.com/DeFiCh/app/releases/tag/v2.8.0)

**Comment by kmeans27** [comment]
Hi @izzycsy thank you for your message. So this is just a temporary error? All the rewards will be payed out as planned?

Have a nice day ahead! :-)

**Comment by izzycsy** [comment]
Hi @kmeans27 , yes, basically everything went on pause during the stall; no blocks no rewards. It should reflect by now, for latest updates please refer to [DeFiChain Telegram (EN)](https://t.me/defiblockchain).
