### ISSUE TITLE
BTC not in the wallet

### ISSUE THREAD

**Issue by nWiZ11** [DeFiCh/app#1093]
#### How to reproduce it (as minimally and precisely as possible): yesterday at (7.12.2021, 20:37:59) i send to my wallet 0,00188521 BTC with the Defichain 2.7.3. This was my first wallet s
[Archiv.zip](https://github.com/DeFiCh/app/files/7677470/Archiv.zip)
tatus. Because i downloaded it 01.12.21. Today was the update to Defichain 2.8 and now my BTC are not there. And when i make the Backups (i have 3 of them) the BTC is still not there.

 And yesterday with the Defichain version 2.7.3 i can´t make a backup because there was a problem with a Error. I cant log yesterday because this error. I don´t remember the error it was like : false block reported or something like this. And now with the 2.8 i can log in, but my BTC is not there.

#### What are your environment parameters?

- DeFiCh/app Version: 2.7.3 and 2.8
- Operating System (OS): 11.4
– RAM (GB): 8GB
– CPU (Intel Core i5/i7/etc.):  M1 CHIP
- Current free storage capacity: 345 GB

**Comment by supervolot** [comment]
Hi did you try to rescan ? (setting > show wallet helper options > rescan

**Comment by izzycsy** [comment]
Hi @nWiZ11 , update [v2.8.1](https://github.com/DeFiCh/app/releases/tag/v2.8.1) is out, this is a **recommended update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. Can you check?

**Comment by chk-** [comment]
Hi,
I am having the same issue, but with other versions of DeFi Wallet!
Yesterday I sent some BTC to my wallet. It was the first time, so an address was created. I received the sent BTC and saw the correct BTC amount in my wallet.
Today, I updated to v2.8.1 and downloaded the snapshot and synced. If I go to BTC addresses, it is showing my BTC address which I created yesterday and telling it was created "an hour ago"!
Then I sent some BTC again for checking, if then the correct total amount would show up, but only the today sent amount is shown. https://www.blockchain.com/btc/address/.... is showing the correct total BTC amount, but not my DeFi Wallet.

**Comment by Bushstar** [comment]
@chk- @nWiZ11 

- In CLI type `spv_rescan 672683`
- Type `spv_syncstatus` to make sure that scanning is progressing from block 672,683. All Bitcoin TXs in the wallet will be in a Bitcoin block above that height.

**Comment by chk-** [comment]
Thank you @Bushstar for your advice. I will keep it in evidence for next time;-)
I did a complete rescan this time.

By the way, is there a time horizon, when the BTC beta wallet will be usable for sending to external wallets?

**Comment by izzycsy** [comment]
Hi @chk- , at the moment for native BTC being sent to DeFiChain desktop app, it can only be for send (to and fro from your BTC address on BTC Network) & swapping of BTC to dBTC, and vice versa. This is also known as [Atomic Swap](https://github.com/DeFiCh/icx-makerbot). Users from the community have already open a discussion on this: https://github.com/DeFiCh/app/discussions/1083

**Comment by Braccus89** [comment]
Hello, I have a similar problemin the new version of the windows app #1116 

after input : spv_rescan 672683 -->  the program returns zero

DeFi Wallet v2.8.4 
Node v2.5.0

spv_rescan 672683
null

after input : spv_syncstatus -->  

the program returns    
{
  "connected": true,
  "current": 671475,
  "estimated": 718633
}

but the program does not scan and the problem persists!

**Comment by chk-** [comment]
Repeat your input of "spv_syncstatus" and you will see a progress on the return value "current". This takes some time until the resync is done.

**Comment by chk-** [comment]
> @chk- @nWiZ11
> 
> * In CLI type `spv_rescan 672683`
> * Type `spv_syncstatus` to make sure that scanning is progressing from block 672,683. All Bitcoin TXs in the wallet will be in a Bitcoin block above that height.

This is a so useful hint because very often happens after updating the app!
