### ISSUE TITLE
Snapshot stuck @ Block 1428368

### ISSUE THREAD

**Issue by JoergHoffmann** [DeFiCh/app#1094]
#### How to reproduce it (as minimally and precisely as possible): 

 1. try to open the app
2. get failure message: credit failure request failed with status code 503
3. try to make backup- failed
4. make snapshot 
5. update to 2.8.0
5. try to reindex the wallet- failed
6. use snapshot Snapshot wird ausgepackt von C:\Users\Admin\AppData\Roaming\DeFi Blockchain\snapshot\snapshot-mainnet-1428368.zip
7. snapshot stands still at 1428368

#### What are your environment parameters?

- DeFiCh/app Version: 2.8.0
- Operating System (OS): WIN 11
– RAM (GB):  16 GB
– CPU (Intel Core i5/i7/etc.): i7
[Configs.zip](https://github.com/DeFiCh/app/files/7678367/Configs.zip)

- Current free storage capacity: 434 GB

#### Anything else we need to know? 

[Configs.zip](https://github.com/DeFiCh/app/files/7678375/Configs.zip)

**Comment by RainerBlessing** [comment]
My snapshot is stuck at 1429877. The last time I had this, there was an advice to change/delete files in the defichain folder, but I can't remember what it was.

**Comment by chregg** [comment]
I have the same issue. Snapshot is stuck at 1429877.

**Comment by NMF1812** [comment]
Same here. I am stuck at 1429877

**Comment by xXPaseoXx** [comment]
same here at 1429877

**Comment by Gilli1545** [comment]
Same here at 1429877 on my notebook. I copied the blockcchain from my desktop pc to the notebook and it worked. Probably a snapshot with the 1429877 will work.

**Comment by MrB3x3F** [comment]
same here, is there somewhere a snapshot to use which is newer than monday?

**Comment by kmeans27** [comment]
mine stuck @ 1429877

**Comment by Unicornlove87** [comment]
same here at 1429877 ! also on the Notebook

**Comment by Unicornlove87** [comment]
solved!

take this Snapshot
https://defi-snapshots-europe.s3.eu-central-1.amazonaws.com/snapshot-mainnet-1430890.zip

and install it like here

https://defichain-wiki.com/wiki/Fullnode#Create_and_use_backup_for_blockchain_data

**Comment by kmeans27** [comment]
How do you install the snapshot? I don't get it

**Comment by Unicornlove87** [comment]
its in the wiki, scroll down

**Comment by MrB3x3F** [comment]
thanks @Unicornlove87 it is working with the newer snapshot

**Comment by Svile30** [comment]
I m maked New installation wallet, with snapshot from before 3days  and still stuck on same block 1429877

**Comment by Unicornlove87** [comment]
> 

dude dont be so stupid... read the text above! You have to be download an another snapshot manual

**Comment by Svile30** [comment]
u mean this snapshot?? https://defi-snapshots-europe.s3.eu-central-1.amazonaws.com/snapshot-mainnet-1430890.zip

**Comment by Unicornlove87** [comment]
> u mean this snapshot?? https://defi-snapshots-europe.s3.eu-central-1.amazonaws.com/snapshot-mainnet-1430890.zip

solved!

take this Snapshot
https://defi-snapshots-europe.s3.eu-central-1.amazonaws.com/snapshot-mainnet-1430890.zip

and install it like here

https://defichain-wiki.com/wiki/Fullnode#Create_and_use_backup_for_blockchain_data

**Comment by Svile30** [comment]
i never did that, i will try later.  i m new in this,

**Comment by izzycsy** [comment]
Hi @JoergHoffmann @RainerBlessing @xXPaseoXx @MrB3x3F @Gilli1545 @Unicornlove87 @Svile30 @kmeans27 @chregg @NMF1812 , update [v2.8.1](https://github.com/DeFiCh/app/releases/tag/v2.8.1) is out, this is a **recommended update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by SKapi1985** [comment]
Hi @izzycsy unfortunately the problem still exists

**Comment by RainerBlessing** [comment]
Worked for me. Thanks!

**Comment by JoergHoffmann** [comment]
after struggling several days I am @100% Sync! HURRA! Downloaded the update 2.8.1 then  take a snapshot 1430890 and now it works. 
THANKS to everyone for support.
