### ISSUE TITLE
Problem swap dusd to dusdc

### ISSUE THREAD

**Issue by mastersly** [DeFiCh/app#1096]
hello .... the following problem occurred to me today. i carried out a swap over the dex from dusd to dusdc. I gave 1000 dusd in exchange and was supposed to receive 1278 dusdc. i took 1% slippage as an option. the order was also carried out. however, according to the app, I got 1000 dusdc credited. on dfi.tax it shows me a reasonably reasonable value of 1273. What went wrong? vg

**Comment by wmbst** [comment]
With this information no dev will be able to help you.
First, did you use the desktop app, or the mobile wallet? Right now you posted in the desktop full node part.
Can you provide the transaction ID or your DFI Address, so devs are able to check your transaction?
Did you check the transaction on defiscan.live? What is this showing you?

**Comment by izzycsy** [comment]
Hi @mastersly , update [v2.9.1](https://github.com/DeFiCh/app/releases/tag/v2.9.1) is out, this is a **mandatory update**. Kindly `backup wallet` and read through the release notes before updating. _This comment is to notify you about the update._

Regarding your issue, the team will need more information if you want it to be investigated. Also, there's no slippage tolerance on desktop app, so I'm guessing that you might be referring to [Light Wallet](https://github.com/DeFiCh/wallet). We can further discuss the issue there. This page is for desktop related issues. Thank you for your understanding.
