### ISSUE TITLE
Test PoolSwapTx execution failed: tx must have at least one input from account owner

### ISSUE THREAD

**Issue by cyrus1683** [DeFiCh/app#1098]
#### Actual behavior:

I can't swap DFI on the DEX to another coin.

#### Expected behavior:

I can swap from DFI to any coin :-)

#### How to reproduce it (as minimally and precisely as possible):

Want to swap 10 DFI to DUSD or USDC
- clicked on swap
- error message apears:

--> Test PoolSwapTx execution failed: tx must have at least one input from account owner

#### What are your environment parameters?

- DeFiCh/app Version: 2.8.1
- Operating System (OS): Elementary OS 5.1 (Ubuntu Base)
– RAM (GB): 16
– CPU (Intel Core i5): 4 Core

Debug Logfile entry:

2021-12-10T10:58:59Z [wallet.dat] Fee Calculation: Fee:262 Bytes:227 Needed:262 Tgt:6 (requested 6) Reason:"Half Target 60% Threshold" Decay 0.96200: Estimation: (1102.5 - 1157.62) 100.00% 352.4/(352.4 0 mem 0.0 out) Fail: (0 - 1102.5) 100.00% 0.4/(0.4 0 mem 0.0 out)

The other side, from DUSD to DFI worked!

**Comment by izzycsy** [comment]
Hi @cyrus1683 , may I check that you've more than 1 DFI (UTXO)? Do you have multiple addresses? 

Difference between DFI (UTXO) & DFI (Token) can be found here: https://github.com/DeFiCh/app/discussions/846

**Comment by cyrus1683** [comment]
@izzycsy 
Thanks, that was the problem. It's solved now!
