### ISSUE TITLE
Add liquidity dUSD-dXXX does not find any second token

### ISSUE THREAD

**Issue by wmbst** [DeFiCh/app#1099]
#### Actual behavior:
Since Version 2.7.3 (adjusting liquidity page), when I klick on add liquidity and choose dUSD on the left side, the right side doesn't fill up, so it is not possible to add the second token, to open a liquidity mining position.
It did work perfect till version 2.7.2. 
It is possible to add liquidity if you klick + directly at the pool pair, so this is a minor issue, but I guess it is easy to fix.

#### Expected behavior:
If you choose dUSD on the left side, you should find the different possibilities on the right side, to add liquidity to a pool pair.

#### How to reproduce it (as minimally and precisely as possible):

Just klick on add liquidity and choose dUSD as one token.

#### What are your environment parameters?

- DeFiCh/app Version: 2.7.3,2.8.0,2.8.1
- Operating System (OS): MAcOS

**Comment by izzycsy** [comment]
Hi @wmbst , thanks for your feedback, please give us time to investigate the issue.

**Comment by thedoublejay** [comment]
Fixed with https://github.com/DeFiCh/app/releases/tag/v2.8.2
