### ISSUE TITLE
Removal of vault collateral not possible if DFI <50%

### ISSUE THREAD

**Issue by derstrecker** [DeFiCh/app#1100]
**Actual behavior:**
While removing collateral in an active vault with a loan I receive the error message „Error Code 0 400“; in the official DeFiChain Light Wallet. If DFI amount is less than 50%, it is not possible to remove any other collateral, to change this. For example removing dBTC to balance the DFI part >51% is not possible. Only if I add DFI to be the vault >50%, then only I can remove any other collateral. Doesn't make sense.

**Expected behavior:**
Should remove Collateral.

**How to reproduce it (as minimally and precisely as possible):**
Remove Collateral in the official DeFiChain Light Wallet. Collateral 49% DFI and 51% dBTC.

**What are your environment parameters?**
DeFiCh/app Version: DFX Wallet v0.17.1
Operating System (OS): iOS mobile
– RAM (GB): -
– CPU (Intel Core i5/i7/etc.): iPhone 12 Pro Max
Current free storage capacity: enough

**Comment by wmbst** [comment]
I guess you are writing about the mobile wallet: https://github.com/DeFiCh/wallet
This part is the desktop full node app. 
Perhaps you can move it or copy it to the other branch.

**Comment by derstrecker** [comment]
Yes, did that, thanks :)
