### ISSUE TITLE
Tokens balances and transactions not showing

### ISSUE THREAD

**Issue by S555O** [DeFiCh/app#1101]
Hi,

A few days back, my Defichain wallet encountered a "node is disconnected error".

Since then I tried to 1. reindex (failed) and also 2. reinstall the latest wallet.

At present, after fully synchronized (100%), I still cannot see my token balances and transactions

Pls kindly advise further

Thanks 
[App Log -2021211.zip](https://github.com/DeFiCh/app/files/7701031/App.Log.-2021211.zip)

**Comment by izzycsy** [comment]
Hi @S555O , are you on [v2.8.1](https://github.com/DeFiCh/app/releases/tag/v2.8.1)? can you try `RESCAN` via settings.

<img width="782" alt="Rescan" src="https://user-images.githubusercontent.com/65014479/145876555-eed75ad1-8ab7-4588-8501-0555f46f8a48.png">

**Comment by S555O** [comment]
Yes, have tried this method before and just did it again. Not showing addresses still

**Comment by izzycsy** [comment]
Hi @S555O , can you try adding your address back manually? Toggle off the `Automatically generate new address` and paste your address in. 

<img width="791" alt="Do not auto create address" src="https://user-images.githubusercontent.com/65014479/146155954-6da1e7f7-222e-4c16-817c-b18d68b79060.png">

**Comment by S555O** [comment]
1. May I where can I access this page? Under settings?
2. Where can I find out my addresses?

**Comment by S555O** [comment]
I went on to restore my wallet on another laptop and it worked. Thanks for your help

**Comment by izzycsy** [comment]
Hi @S555O , thanks for the update. Glad your issue has been resolved. You may also switch to mobile [Light Wallet](https://github.com/DeFiCh/wallet), does not require running a full node wallet. You may ask the community on how to use / port over / etc. on [DeFiChain Telegram (EN)](https://t.me/defiblockchain). Thank you.
