### ISSUE TITLE
Configuraion error, no data found.

### ISSUE THREAD

**Issue by KouLiTo** [DeFiCh/app#1102]
Hello,
I cant launch the last 3.8.1 Update of DefiChain-Wallet on Windows 10! It is not possible to save logs. I just have screenshots. Ho to handle the issue?
I already deleted every folder and file concering DeFi-Wallet, reinstalled it thousand times, even launched defid.exe! Nothing helped. The app wont work.

**Comment by KouLiTo** [comment]
here is the lo
[main.log](https://github.com/DeFiCh/app/files/7719253/main.log)
g

**Comment by KouLiTo** [comment]
There are two errors in the log:
1. Error: ENOENT: no such file or directory, open 'C:\Users\Gena\.defi\defi.pid'
2. [IPC-RENDERER-error] [getConfig] "No data found"

**Comment by izzycsy** [comment]
Hi @KouLiTo , may I know the following: 
- DeFiCh/app Version:
- Operating System (OS): 
– RAM (GB): 
– CPU (Intel Core i5/i7/etc.): 
- Current free storage capacity:

Also, please ensure that your `wallet.dat` has been [backed up](https://github.com/DeFiCh/app/discussions/988).
