### ISSUE TITLE
BTC shows in my wallet but I can't use it on dex or adding to liquidity. I sent it to my wallet through the BTC beta address. I'm not sure if I screwed something up or its a bug in the system, any help would be appreciated. Thank You!

### ISSUE THREAD

**Issue by dexply** [DeFiCh/app#1105]
#### What are your environment parameters?

- DeFiCh/app Version:
- Operating System (OS): 
– RAM (GB): 
– CPU (Intel Core i5/i7/etc.): 
- Current free storage capacity:

**Comment by dexply** [comment]
Actual behavior: I transferred BTC on 12/22 (Total: $800.00, 0.0010073 for first test amount, 8:33am and final amount sent after test send, 0.015404 @ 8:48) from my ledger wallet to BTC beta wallet address.  

https://blockstream.info/tx/0884035aca375ba062e05cd8ff87d70c60f77cb50656db940e38d1e9054ddd1b 

https://blockstream.info/tx/5f3ec1bf7495fb5c596ffe976b1d027417d4f0d892e98d60d60e9e908884da70 

Expected behavior: transfer to wallet address and usable  

How to reproduce it (as minimally and precisely as possible): 

What are your environment parameters? 
DeFiCh/app Version:2.8.1 
Operating System (OS): Windows 11 Home, 21H2 
– RAM (GB): 32.0 GB (31.7 GB usable) 
– CPU (Intel Core i5/i7/etc.): 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz   3.00 GHz 
Current free storage capacity: 406GB free 

Anything else we need to know? 
My wallet shows 0.01639174 is available but no transaction listed for it being deposited and I can’t send it, swap it, or do anything with it

**Comment by dexply** [comment]
is there anyway to just return the funds if I can't use them? I guess I just lost 800 bucks or more now with the price of BTC going up. another lesson learned I guess, Merry Christmas to me

**Comment by dexply** [comment]
not sure if it even matters at this point but today the BTC doesn't show anymore in my account

**Comment by izzycsy** [comment]
Hi @dexply , at the moment for native BTC being sent to DeFiChain desktop app, it can only be for send (to and fro from your BTC address on BTC Network) & swapping of BTC to dBTC, and vice versa. This is also known as [Atomic Swap](https://github.com/DeFiCh/icx-makerbot). Users from the community have already open a discussion on this: https://github.com/DeFiCh/app/discussions/1083 

If you would like to use the other features, you'll have to send DFI instead. To send DFI, you may do so from exchanges which supports DFI via DeFiChain Network — KuCoin, Bittrex, Hotbit just to name a few. To wrap other tokens such as USDT to dUSDT, BTC to dBTC, or ETH to dETH, you can go through CakeDeFi to wrap and up-wrap. 

Kindly understand that DeFiChain app is not an exchange where you can trade BTC like on your exchanges. If you would like to do so, then DeFiChain app is not suitable.  Your tokens are your own responsibility. Please remember to [backup wallet](https://github.com/DeFiCh/app/discussions/988) if you're using the desktop app. Or simply use the [mobile Light Wallet](https://github.com/DeFiCh/wallet) to save the hassle of running a full node wallet. Thank you. For more enquiries, you can ask the community on how to use the features: [DeFiChain Telegram (EN)](https://t.me/defiblockchain)
