### ISSUE TITLE
Win10: Wallet "Unable to start blockchain"

### ISSUE THREAD

**Issue by raphbaph** [DeFiCh/app#1106]
#### What are your environment parameters?

- DeFiCh/app Version: 2.8.1
- Operating System (OS):  Windows 10
– RAM (GB):  16 GB
– CPU (Intel Core i5/i7/etc.):  i5 10th Gen
- Current free storage capacity: 138 GB

#### Anything else we need to know?

Complete deletion of all directories and reinstall didn't solve the issue.

**Comment by Stonygan** [comment]
Please check your debug.log, i think you can find there why the wallet are chrashed.
https://defichain-wiki.com/wiki/Debug.log

**Comment by raphbaph** [comment]
No. Debug. log stopped updating 12 days ago. 

—————————
Sent from the road

**Comment by raphbaph** [comment]
> Please check your debug.log, i think you can find there why the wallet are chrashed. https://defichain-wiki.com/wiki/Debug.log

Debug.log stopped updating 12 days ago. Deleting it doesn't result in a new file.

**Comment by izzycsy** [comment]
Hi @raphbaph , update [v2.8.2](https://github.com/DeFiCh/app/releases/tag/v2.8.2) is out, can you try updating?

**Comment by raphbaph** [comment]
This did the trick! Thanks a lot!
I've a hunch what caused the issue: I downloaded a snapshot but then somehow wound up re-synching from block 1... 
Apparently this deranged the process a bit...
Atm syncing from block 1. Malwarebytes reports a trojan, but I added an exception for defid.exe
