### ISSUE TITLE
Unable to create any wallet apart from DFI

### ISSUE THREAD

**Issue by Ausafari** [DeFiCh/app#111]
Hi,
I have been reading and re-reading the literature on your app regarding creating wallets for Liquidity Mining purposes.
As per the attached screenshot, I now have a test deposit of 700DFI sitting in that wallet - all good.
However, contrary to the information I have read on your app, there is no way to create wallets other than DFI. Each time I click on the "Wallets" tab (as shown), all that happens is I see my DFI wallet. There is no option for me to create a BTC / ETH wallet, etc.
Please advise what is going on with your app that is preventing me from opening other wallets and thus liquidity mining with you.
![dfi-wallet-option-only](https://user-images.githubusercontent.com/75756887/101955475-9bda8280-3c49-11eb-9006-bad191f97ef0.jpg)

**Comment by domedesign55** [comment]
Creates itself automatically at the DEX. You can convert DFI to BTC or ETH or other. 
After a few minutes you have an BTC wallet or other.

**Comment by izzycsy** [comment]
Hi @Ausafari , thanks for your feedback. @domedesign55 is right, it'll automatically appear once you receive / swap to other coins. For enquiries like this, you may also turn to the Telegram Channel for quick tips! 
<https://t.me/defiblockchain>
