### ISSUE TITLE
BTC is shown in wallet, but not in DEX

### ISSUE THREAD

**Issue by Kriskind** [DeFiCh/app#1112]
Hello, I see my BTC in the wallet. But I can't see the transaction in the BTC wallet.
I can't see it in DEX. And I can't send it to another wallet.

So what can I do with my BTC or to get it back to another wallet?

#### What are your environment parameters?

- DeFiCh/app Version: 2.8.2
- Operating System (OS):  win10
– RAM (GB): 
– CPU (Intel Core i5/i7/etc.): 
- Current free storage capacity:

**Comment by izzycsy** [comment]
Hi @Kriskind , , update [v2.8.3](https://github.com/DeFiCh/app/releases/tag/v2.8.3) is out, this is a **mandatory update**. Kindly `backup wallet` and read through the release notes before updating. After which, you can send your BTC to any BTC address via BTC network. 

At the moment for native BTC being sent to DeFiChain desktop app, it can only be for send (to and fro from your BTC address on BTC Network) & swapping of BTC to dBTC, and vice versa. This is also known as [Atomic Swap](https://github.com/DeFiCh/icx-makerbot). Users from the community have already open a discussion on this: https://github.com/DeFiCh/app/discussions/1083 

If you would like to use the other features, you'll have to send DFI instead. To send DFI, you may do so from exchanges which supports DFI via DeFiChain Network — KuCoin, Bittrex, Hotbit just to name a few. To wrap other tokens such as USDT to dUSDT, BTC to dBTC, or ETH to dETH, you can go through CakeDeFi to wrap and up-wrap.

**Comment by izzycsy** [comment]
Hi @Kriskind , update [v2.8.4](https://github.com/DeFiCh/app/releases/tag/v2.8.4) is out, this is a **recommended update**. Kindly `backup wallet` and read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Kriskind , update [v2.9.1](https://github.com/DeFiCh/app/releases/tag/v2.9.1) is out, this is a **mandatory update**. Kindly `backup wallet` and read through the release notes before updating. _This comment is to notify you about the update._
