### ISSUE TITLE
Incorrect version for latest 2.8.4

### ISSUE THREAD

**Issue by John-Gee** [DeFiCh/app#1115]
#### Actual behavior:
All assets with correct version in the filename.
#### Expected behavior:
Some assets are missing from the release and they have 2.8.3 in the filename instead.

@thedoublejay 

Thanks!

**Comment by thedoublejay** [comment]
Checking now

**Comment by John-Gee** [comment]
Thanks!

**Comment by John-Gee** [comment]
It looks good now, thank you.
