### ISSUE TITLE
BTC are no longer displayed in the DeFi Wallet

### ISSUE THREAD

**Issue by Braccus89** [DeFiCh/app#1116]
#### How to reproduce it (as minimally and precisely as possible):

1. Send previous app version btc to the wallet (they will be displayed)
2. Update app version 2.8.4
3. snapshot download and sync
4. the BTC are no longer displayed

#### What are your environment parameters?

- DeFiCh/app Version:2.8.4
- Operating System (OS): OS Windows 10 - 10.0.19043
– RAM (GB):  16 GB
– CPU (Intel Core i5/i7/etc.): Intel(R)Core(TM) i7 - 8550U CPU @1.80GHz, 1992MHz, 4 Kern(e), 8 loigsche(r)Prozessor(en)
- Current free storage capacity: 242 GB

**Comment by izzycsy** [comment]
Hi @Braccus89 , regarding the issue [`BTC not in the wallet #1093`](https://github.com/DeFiCh/app/issues/1093), we can further discuss the issue there. We would like to keep same issues in one thread. Thank you. 

Kindly refer to this comment and try this out: https://github.com/DeFiCh/app/issues/1093#issuecomment-992386228
