### ISSUE TITLE
CLI: Does not accept [option] key characters, i.e. {}

### ISSUE THREAD

**Issue by starman578** [DeFiCh/app#112]
Hello,
so far I didn't noticed due to copy&paste.
However I figured out now that you cannot type curly brackets {} in the console.
Running defi-app 2.1.3 on MacOS 10.15.7
[app_config.log](https://github.com/DeFiCh/app/files/5682825/app_config.log)
[app_log.log](https://github.com/DeFiCh/app/files/5682826/app_log.log)
[binary_log.log](https://github.com/DeFiCh/app/files/5682827/binary_log.log)

**Comment by izzycsy** [comment]
Hi @starman578 , thanks for your feedback, could you describe your user flow more? Screenshots / screen recordings would be helpful as well!

Do you mean you could not key this in the CLI? 
<img width="259" alt="Curly bracket in CLI" src="https://user-images.githubusercontent.com/65014479/102059008-4cec4300-3e2b-11eb-85cc-dba3e265e9bc.png">

**Comment by starman578** [comment]
Hi,
I can easily create those brackets everywhere else in the OS (alt+8 / alt+9)
However it does not recognize any keypresses of those when I'm in the CLI.
Normal brackets are working fine (shift+8 / shift+9).
I'm using a german keyboard layout which is also correctly recognized in the CLI.
I hope the attached screen recoding will help.
Since no-one else reported this issue so far I would assume its only happening in very strange circumstances....
Therefore I would assume it's not the highest prio on your list.

[no_curly_brackets.mov.zip](https://github.com/DeFiCh/app/files/5692098/no_curly_brackets.mov.zip)

**Comment by izzycsy** [comment]
Hi @starman578 , thanks for taking a screen recording, please give us time to investigate this issue.

**Comment by starman578** [comment]
Thanks for taking care.
Of course I understand that there are more important things right now.
Let me know if I can help with something.

**Comment by izzycsy** [comment]
Hi @starman578 , if this feature is not yet available in the current version, it might be pushed to the next as issues are dealt with accordingly to urgency. Rest assured that your feedback has been sent to the team. Thank you for your valued feedback.
