### ISSUE TITLE
Now tokens after wallet reset

### ISSUE THREAD

**Issue by r41ner** [DeFiCh/app#1121]
#### Actual behavior:

I lost my password so I could not access to my tokens. I wanted to reset.
after resetting I cant find my 124.8dfi (on dSBo9VfMKMvBYD2fPggsWoGG9zn95RaPLz)
What am I doint wrong?

#### Expected behavior:

finding my tokens

#### What are your environment parameters?

- DeFiCh/app Version:
- Operating System (OS): 
– RAM (GB): 
– CPU (Intel Core i5/i7/etc.): 
- Current free storage capacity:

#### Anything else we need to know?

[app logs.zip](https://github.com/DeFiCh/app/files/7862643/app.logs.zip)

**Comment by izzycsy** [comment]
Hi @r41ner , how did you reset it? What were the steps you took?

**Comment by r41ner** [comment]
Hi,

It is the German Version of the Desktop Wallet. I used the button beside
the lock and tried several things. Recover from the SEED phrase... but
didnt work... The last attempt was to recover from a recent .dat file.
Loading down a certain state of the Blockchain File and starting sync
procedure. When i watch in defiscan for my external adress i find the
Transaction but here it is unvisible.

Izzy ***@***.***> schrieb am Fr., 14. Jan. 2022, 10:39:

**Comment by izzycsy** [comment]
Hi @r41ner , unfortunately, there's no way to retrieve your passphrase if you lose it, likewise for your mnemonic seed, please try to remember. There’s no limit to trying. 

Alternatively, you can try to Restore via Wallet Backup, in the `wallets` folder there might be a backup that you made before you created your passphrase. Here's how to find the folder: 

For Windows it's located here:  
`C:\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\`
> In the wallets folder you'll likely see `wallet-bak-123456789` as well, these are additional wallet backups. 

Full guide on how to Restore Wallet from Backup: https://github.com/DeFiCh/app/discussions/988

**Comment by r41ner** [comment]
Yes, there are several Backup Files. But None of them recovers the dfi. And
thats Something i dont understand. In the Log File the external adress can
bei found but the transactions can not bei restored?

Izzy ***@***.***> schrieb am Mo., 17. Jan. 2022, 10:11:

**Comment by izzycsy** [comment]
@r41ner , for example, `wallet.dat1` has no passphrase, `wallet.dat2` has passphrase — because backups are created at different point in time, you can try to restore wallet using `wallet.dat1`. 

Are you on the latest version, [v2.8.4](https://github.com/DeFiCh/app/releases/tag/v2.8.4)?
Is your address displayed in Receive screen? 
<img width="1002" alt="DFI wallet   Receive   New Address" src="https://user-images.githubusercontent.com/65014479/149908541-77a594ae-beef-40b6-b255-d5cc1519ba5e.png">


If it's not, try to `Rescan` via settings, use snapshot to sync to 100%.

<img width="782" alt="Rescan" src="https://user-images.githubusercontent.com/65014479/149908604-afab59f2-81ee-4033-90ac-e2bd5aa7cd43.png">

**Comment by r41ner** [comment]
please find my answers below.

Am Di., 18. Jan. 2022 um 10:26 Uhr schrieb Izzy ***@***.***>:

> @r41ner <https://github.com/r41ner> , for example, wallet.dat1 has no
> passphrase, wallet.dat2 has passphrase — because backups are created at
> different point in time, you can try to restore wallet using wallet.dat1.
>
> Are you on the latest version, v2.8.4
> <https://github.com/DeFiCh/app/releases/tag/v2.8.4>?
>
Yes

> Is your address displayed in Receive screen?
>
No, it's completely empty. And if I try to add my previous external address
dSBo9VfMKMvBYD2fPggsWoGG9zn95RaPLz it is refused as invalid.
The corresponding Transaktions-ID is
17a7f8456de1c26f7713dc0b78a24fcb7486a1e103b05ef1bb420e62359fdb08


> [image: DFI wallet Receive New Address]
> <https://user-images.githubusercontent.com/65014479/149908541-77a594ae-beef-40b6-b255-d5cc1519ba5e.png>
>
> If it's not, try to Rescan via settings, use snapshot to sync to 100%.
>
Ok, I did. But I can't see any effect.

**Comment by r41ner** [comment]
what means Request failed with status code 500? Shown at transaction

Am Di., 18. Jan. 2022 um 10:26 Uhr schrieb Izzy ***@***.***>:

**Comment by izzycsy** [comment]
@r41ner means the app is trying to connect to synchronize. Is your app at 100%?

**Comment by r41ner** [comment]
Yes, was at 100%

Izzy ***@***.***> schrieb am Do., 20. Jan. 2022, 09:05:

**Comment by izzycsy** [comment]
Hi @r41ner , update [v2.9.1](https://github.com/DeFiCh/app/releases/tag/v2.9.1) is out, this is a **mandatory update**. Kindly `backup wallet` and read through the release notes before updating. 

As to your issue, it's best if you can try to recall your passphrase, there's no limit to trying.

**Comment by izzycsy** [comment]
Hi @r41ner , update [v2.13.0](https://github.com/DeFiCh/app/releases/tag/v2.13.0) is out, this is a **mandatory update**. Kindly `backup wallet` and read through the release notes before updating. I'll be closing this issue in the mean time. You may reopen this issue if there's new information (include screenshots) and your app logs. Thank you.
