### ISSUE TITLE
Export Data Dialog does not export Rewards & Commissions

### ISSUE THREAD

**Issue by microbiotic** [DeFiCh/app#1126]
#### What happened:

The export data dialog does not export rewards & commissions

#### What you expected to happen:

I expected to get a csv with 100 transactions including rewards & commissions. Instead I get all other txs like receive, sent, AddPoolLiquidity, PoolSwap etc.

#### How to reproduce it (as minimally and precisely as possible):

Version 2.8.4, Mac

1. Opened the app
2. Clicked "Transactions" on the LHS
3. Clicked "Export Data" on the RHS
4. Selected "Include rewards" in the export dialog
5. Clicked "Export"
6. Opened the exported csv but could not find any rewards

#### Anything else we need to know?:

This is currently critical to me as I need to create my tax reports.
Is there some other workaround to export the data from the app ?

**Comment by izzycsy** [comment]
Hi @microbiotic , regarding the issue [`Export Button is clickable to early #979`](https://github.com/DeFiCh/app/issues/979), we can further discuss the issue there. You may copy and paste your issue into the comment on the thread. We would like to keep same issues in one thread. Thank you. 

You can try other projects such as https://dfi.tax/ , done by the community or get your transaction history from https://defiscan.live/ — paste your address to generate the transactions.
