### ISSUE TITLE
dBTC missing

### ISSUE THREAD

**Issue by ChrisB44** [DeFiCh/app#1128]
I sent dBTC to DFX wallet, Laptop went into Standby. Transaction is not shown, dBTC is gone and not on DFX wallet.
Should I write the Wallet address here? Can you help please?
Kind regards, Chris
[DefI.Logs.27.01.2022.zip](https://github.com/DeFiCh/app/files/7950087/DefI.Logs.27.01.2022.zip)

- DeFiCh Version: 2.8.4
- Operating System (OS): Win10

**Comment by Stonygan** [comment]
https://defiscan.live/address/df1q2znydu675ryexd2r5yzeh2s8swch8fc2nkd6k5

Is this the Transaction with your dBTC?

**Comment by ChrisB44** [comment]
Hi there, 
I don’t think so. It should be dBtc from my laptop wallet. In the zip is a screenshot of balances from 25th and the transactions. 
No major dBtc transaction there, but they are gone. 
Kind regards, Chris 

Von meinem iPhone gesendet.

Dr. Christian Bechheim 
Franz-Rieder-Str. 11
85051 Ingolstadt 

Mail: ***@***.***
Phone: +49 177 210 8048

**Comment by Stonygan** [comment]
Can you post your address and some timestamps. And how much you send or missing. Maybe better when you contact private at telegram, when you dont want to post it public. @Stonygan

**Comment by izzycsy** [comment]
Hi @ChrisB44 , update [v2.13.0](https://github.com/DeFiCh/app/releases/tag/v2.13.0) is out, this is a **mandatory update**. Kindly `backup wallet` and read through the release notes before updating I'll be closing this issue in the mean time. You may reopen this issue if there's new information (include screenshots), app & node logs. Thank you.
