### ISSUE TITLE
No Sync with Full Node Wallet

### ISSUE THREAD

**Issue by ZUDW** [DeFiCh/app#1129]
#### What are your environment parameters?

- DeFiCh/app Version: 2.8.5
- Operating System (OS): Windows 10
– RAM (GB): 16
– CPU (Intel Core i5/i7/etc.): AMD Ryzen 5 4000H
- Current free storage capacity: 73GB

#### Anything else we need to know?

[logs.zip](https://github.com/DeFiCh/app/files/7953824/logs.zip)

**Comment by izzycsy** [comment]
Hi @ZUDW , can you try the latest update [v2.9.1](https://github.com/DeFiCh/app/releases/tag/v2.9.1). Closing some applications will help with the synchronization as well.

**Comment by izzycsy** [comment]
Hi @ZUDW , kindly update to [v2.12.0](https://github.com/DeFiCh/app/releases/tag/v2.12.0), if issue persists, kindly leave a comment [here](https://github.com/DeFiCh/app/issues/1197) so we can keep the same issue in one thread.
