### ISSUE TITLE
DFI disappeared after trying to add liquidity

### ISSUE THREAD

**Issue by Ronzen** [DeFiCh/app#113]
Mac osx 10.15.7, Defi-App Version 2.1.3 On the main network

please help. 

I already have an LM position open since a few days which was working as expected.
Today i transferred some DFI from Cake to my Defi-App Wallet.
Next i swapped a part of it into btc so i could add to my LM position.
Next i tried to add BTC and DFI to my already existing liquidity mining position.
After about one minute an error message appeared. I dont remember the exact words but it was very generic. saying it didnt work.
When i went back to my wallet, a part of the dfi that was supposed to go into the LM was gone. 
The btc wallet was still with the original amount. No btc disappeared.
i went into the console to check if there was an issue with token/coins as this seems to be a common problem. But the getbalance command showed exactly what the wallet showed. the wrong amount, missing part of my dfi stack.
gettokenbalances {} true true didnt show me the missing dfi too.
no liquidity has been added.

**Comment by Ronzen** [comment]
I'm using Defi-App Version 2.1.3

**Comment by izzycsy** [comment]
Hi @Ronzen , thanks for your feedback, do you have any screenshots that describes your situation? We need more details in order investigate how to reproduce this issue. 

In the mean time you may refer to the link attached, hope it helps!
<https://www.reddit.com/r/defiblockchain/comments/k92k2l/how_to_rescue_stuck_dfi/>

**Comment by Ronzen** [comment]
Unfortunately i didnt take any screenshots right before and after the issue happened. All i have are the logs. as desribed in my original post i already checked if there are any "stuck" dfi but there are none.

**Comment by Ronzen** [comment]
I think i've found the problem and it was on my side. I think the wallet hasn't fully synced before i did the transactions so i still had the dfi amount pre-swapping showing up. after the declined LM the wallet was synced correctly and therefore the amount of dfi was down. I'm sorry if i caused any trouble.
