### ISSUE TITLE
Swap preview calculation

### ISSUE THREAD

**Issue by yogsothoth123** [DeFiCh/app#1132]
#### Anything else we need to know?: Based on this i paid several hundreds of DFI although it told me the cost would be around 30 or 40 DFI. If this truly is a bug, I would at least want to know if there is a way to get my trashed DFI back. 

I attached some stuff. in pic1 you can see the amount it was showing me in the swap-window. in pic2 you see what really happened in the transaction. So while the pic1 told me I would get 499DFI, i only got 65. The actual loss for me happened of course when I did it the other way, changing DFI into dTokens. 

![dfi2](https://user-images.githubusercontent.com/98598476/151562330-4bd7a9b4-5dd8-4ac6-8eaf-c0ed4ec29081.png)
![dfi1](https://user-images.githubusercontent.com/98598476/151562336-02faa5db-9625-44a4-b28f-728269230481.png)

**Comment by izzycsy** [comment]
Hi @yogsothoth123 , may I know your tx id?

**Comment by yogsothoth123** [comment]
> ?

Hi @izzycsy, the txid for the picture dfi1and2 is https://defiscan.live/transactions/11b376870c49398e1d25aa97aa26d3622d26f77f3c5b01f48dbaaa5fa2bfeea3

That was the one where i tried to replicate the issue in the other way. The one where i actually paid a lot of DFI for a fraction of dTokens earlier although it was supposed to be much less was this ones here: 

https://defiscan.live/transactions/0106326bb6e5dca212939fe56cdbe88a302e0d8af173b294853582d480769011
(paid 299 DFI for 0.22940798 NVDA, although the swap screen told me it would only cost me ~20 or 30 dfi)

https://defiscan.live/transactions/f2118a8a50a89120e1c3ff3c6de301ba0aef176047cc3044e4735e8c463828b0
(paid 90 dfi for 0.40832237 NVDA although the swap screen told me it would only cost a fractino of that)

Let me know if you need anything else.

**Comment by yogsothoth123** [comment]
hi @izzycsy 
any update? i see that this issue is now fixed, correct? so was it a bug indeed?! some clarification would be nice.

**Comment by izzycsy** [comment]
Hi @yogsothoth123 , the team is investigating your case. Thank you for your patience.

**Comment by izzycsy** [comment]
Hi @yogsothoth123 , thank you for your patience. The team has investigated your issue, during the time when you added swap, the total liquidity was still very little. Currently it looks right because pools are normal.

**Comment by yogsothoth123** [comment]
Yes, as i mentioned now it looks right. So you are saying this was basically an extrem slippage? While it showed me the cost of a few dozen DFI it ultimately did cost a few hundred. Isnt there a safety net on the slippage, like 10 or 15% max?

**Comment by izzycsy** [comment]
Hi @yogsothoth123 , there's no slippage tolerance on the desktop app, however on the mobile Light Wallet there is this feature in place.

**Comment by yogsothoth123** [comment]
so in the desktop its basically possible that the DEX screen shows cost of 1 dfi as an example, but if liquidity is small it suddenly could be 100? do you intend to add slippage tolerance anytime soon, otherwise i would stop using the app immediately. 
once bitten, twice shy....

**Comment by izzycsy** [comment]
Hi @yogsothoth123 , there's no plans of adding slippage tolerance for desktop app at the moment, you can use the [Light Wallet](https://github.com/DeFiCh/wallet), there's slippage protection there. [App Store](https://apps.apple.com/us/app/defichain-wallet/id1572472820) / [Google Play Store](https://play.google.com/store/apps/details?id=com.defichain.app)

**Comment by izzycsy** [comment]
Hi @yogsothoth123 , update [v2.13.0](https://github.com/DeFiCh/app/releases/tag/v2.13.0) is out, this is a **mandatory update**. Kindly `backup wallet` and read through the release notes before updating. Slippage tolerance is now available on the Desktop App. I'll be closing this issue in the mean time. Thank you.
