### ISSUE TITLE
Lots of tx missing in CSV export

### ISSUE THREAD

**Issue by SpecialAgentX** [DeFiCh/app#1135]
Hi there,

im using the CSV export function with the well-known workaround (every single change in ui needs to be waiting that CPU load is going to 0% before change another setting). Otherwise I couldn't get the whole time horizon I need (Dec2020-Oct2021). I was using the desktop app the whole time and did not pause. I needed to start the export process twice, because 999999 in "Limit to last" was not enough.

When I set "Up to block height" to 971507 (01/07/2021 / 07:31 am) and "Limit to last" to 999999, activating "With rewards" button, wait approx. 5 minutes and then download the CSV. The CSV starts at block 966420 (29/06/2021 / 02:45 pm). So Im missing around 2 days.

When I put both CSV into "https://defichain-rewardhelper.com/" Version 5.3.0 it shows more blanks in the table (see red rectcangles in screenshot).

I tried to not use the snapshot and waited 27h to have a fresh copy of the blockchain, but it doesn't changed something. So I really do not know how to get a full list of my tx exported.

File 1: Transaktionen_2022-2-1_7-0-55.cvs (around 169,1 MB, Blocks 971507-1249324)
File 2: Transaktionen_2022-2-1_7-4-50.csv (around 34,1 MB, Blocks 480393-966420)

defi-wallet: 2.8.4
OS: MacOS

<img width="508" alt="Bildschirmfoto 2022-02-01 um 07 12 57" src="https://user-images.githubusercontent.com/24278992/151921618-a0cce37f-ac27-4f45-948a-a0dc0f1c32c0.png">
<img width="1121" alt="Bildschirmfoto 2022-02-01 um 07 13 25" src="https://user-images.githubusercontent.com/24278992/151921617-3d0dbc1d-ce9f-497a-ad52-1796f932e153.png">

**Comment by izzycsy** [comment]
Hi @SpecialAgentX , unfortunately [this issue](https://github.com/DeFiCh/app/issues/979) is still pending, you'll have to rely on other project such as https://dfi.tax/; done by the community or get your transaction history from https://defiscan.live/ — paste your address to generate the transactions. 

You may copy and paste your comment in the thread related. We would like to keep same issues in one thread.Thank you for your understanding.
