### ISSUE TITLE
2.9.0 includes a huge libvk_swiftshader.so

### ISSUE THREAD

**Issue by John-Gee** [DeFiCh/app#1136]
Hello!

#### Actual behavior:
libvk_swiftshader.so in 2.9.0 is 120Mb.
#### Expected behavior:
libvk_swiftshader.so in 2.8.4 is 4Mb.
#### How to reproduce it (as minimally and precisely as possible):
Look at the files.
I have not yet figured out why the difference, but I thought @thedoublejay you might know quickly. :)

#### Anything else we need to know?

Unrelated but is it acceptable to strip the binaries? I took over maintenance of this for my distro it and the previous maintainer prevented stripping, so I'm wondering if there's a reason.

Thanks!

**Comment by John-Gee** [comment]
Ok you fixed it in 2.9.1, thanks!

**Comment by thedoublejay** [comment]
Hey @John-Gee I'm not familiar with `libvk_swiftshader.so` but it might be from Electron library.

**Comment by John-Gee** [comment]
@thedoublejay 
Yeah it's from Chromium, but you fixed it with .1 anyway.
How about the stripping part for the whole build though?
