### ISSUE TITLE
Transactions are not in sync for the same wallet on different OS

### ISSUE THREAD

**Issue by PircolosJM** [DeFiCh/app#114]
> [Defi]([url](url)) app installed on windows and a linux vm, Both latest version 2.1.3 and synchronized.

The app shows different values on the liquidity tockens for both btc and etc.
Transactions are missing from app on linux vm.
BTC and ETH are always in synch.
Already tryed the usual stuff like restarting both the app and the vm for both OS.

Screenshots attached so you can see the diff.

**Comment by PircolosJM** [comment]
<img width="1919" alt="DFI_ISSUE" src="https://user-images.githubusercontent.com/33656229/102029901-4f598900-3da8-11eb-8f79-67c066d850ff.png">

**Comment by izzycsy** [comment]
Hi @PircolosJM , thanks for your feedback. Have you tried the **reindexing option** located in _Settings_?

You may also check your balances in the CLI by:
`getbalance` — utxo DFI 
`getokenbalances` — DFI  

The sum of utxo DFI & DFI would be what’s displayed in your wallet (i.e. 47.10009003). Hope this helps!

**Comment by PircolosJM** [comment]
1) **Restored the wallet using walet file**. I can see the correct balances on CLI but no wallets on the GUI.
2) **Restored thne wallet using 24 words**.  Balances are NOT in synch.

3) The only way that this can be resolved is by restoring the wallet using the 24 words and after that restore AGAIN ON TOP using the wallet file.
