### ISSUE TITLE
Maximum 7 LM Pools are showing

### ISSUE THREAD

**Issue by dzensik** [DeFiCh/app#1157]
#### Actual behavior:
The "Liquidity pools" view shows maximum 7 LM pools within the "Your liquidity" section

#### Expected behavior:
The "Liquidity pools" view shows **all** LM pools within the "Your liquidity" section

#### How to reproduce it (as minimally and precisely as possible):
To create at least 8 LM pools

To create at least 8 LM pools

#### What are your environment parameters?

- DeFiCh/app Version: 2.9.3
- Operating System (OS): macOS Monterey (12.2.1 (21D62))
– RAM (GB): 32GB
– CPU (Intel Core i5/i7/etc.): i9
- Current free storage capacity: 10GB

#### Anything else we need to know?
Nope. Just let me know if you need more info guys. Thank you!

**Comment by izzycsy** [comment]
Hi @dzensik , thanks for your feedback, team will investigate this.

**Comment by thedoublejay** [comment]
It should be fixed by this preview build - https://github.com/DeFiCh/app/releases/tag/v2.10.0-rc.1

**Comment by dzensik** [comment]
Thank you @thedoublejay !

**Comment by thedoublejay** [comment]
Will close this. Fixed with https://github.com/DeFiCh/app/releases/tag/v2.10.0
