### ISSUE TITLE
FB dToken not shown in UI "Liquidity" and "Add Liquidity"

### ISSUE THREAD

**Issue by rossi256** [DeFiCh/app#1161]
#### Actual behavior:
- creating LP does not show FB dToken even if in Balance
- existing LP in wallet shows as "undefined undefined" in Liquidity tab

#### Expected behavior:
- creating LP shows FB token when in wallet balance
- existing LP in wallet shows as FB-DUSD in Liquidity-tab

#### Reproduce:
1.
- get some FB token and DUSD in wallet balance
- go Liquidity
- ADD Liquidity -> no FB shown in list on the left

2.
- get some FB-DUSD LP token via CLI -> shown in Balances correctly.
- go check "Liquidity" -> LP token shown as "undefined undefined"
- click undefined LP and go ADD MORE -> App crashes
- NOTE: Remove -> ALL -> shows visually the correct values.

#### What are your environment parameters?

- DeFiCh/app Version: 2.9.3
- Operating System (OS): macOS 12.2.1
– RAM (GB): 
– CPU (Intel Core i5/i7/etc.): 
- Current free storage capacity:

**Comment by rossi256** [comment]
Screenshots
![image](https://user-images.githubusercontent.com/5187608/159112861-c5589790-efc5-4da6-aeaa-06c8f03ef98c.png)
![image](https://user-images.githubusercontent.com/5187608/159112871-eb3fb4c9-af22-4870-ae64-2f8d5f634e2d.png)
![image](https://user-images.githubusercontent.com/5187608/159112879-e023519b-8cab-4c28-9a23-3ecabb7d0158.png)

**Comment by izzycsy** [comment]
Hi @rossi256 , thanks for the feedback, please give us time to investigate this issue.

**Comment by thedoublejay** [comment]
Will be fixed with this preview build - https://github.com/DeFiCh/app/releases/tag/v2.10.0-alpha.2

**Comment by thedoublejay** [comment]
Will close this. Fixed with https://github.com/DeFiCh/app/releases/tag/v2.10.0
