### ISSUE TITLE
Mac Wallet does not Start after Update to 2.9.3

### ISSUE THREAD

**Issue by neuriGH** [DeFiCh/app#1163]
#### Actual behavior:
Using a intel Mac Book Pro 2015, loaded the Wallet Update to 2.9.3, after the Update the Program didn't start again.
After less than a second the Error message: "DeFI Wallet wurde unerwartet beendet" occurred - in english: "DeFI Wallet was unexpected terminated" (more or less)
Also making a clear install after deleting all Files (including Data and Wallet Files) dit not fix this error

#### Expected behavior:
Program should start

#### What are your environment parameters?

- DeFiCh/app Version:  2.9.3
- Operating System (OS):  MacOS Mojave 2.14.5
– RAM (GB):   8Gbyte
– CPU (Intel Core i5/i7/etc.):  2,9 GHz Intel Core i5
- Current free storage capacity: > 25 GByte free

#### Anything else we need to know?
Downgrading to 2.9.2 made no change, downgrading to 2.9.1 worked

**Comment by Mark76DefiChain** [comment]
I have the same issue, late 2012 intel-mac.... also in TG channels more reports of the same issue with intel macs

**Comment by goofy79** [comment]
Same issue - still reported at #1160

**Comment by stergios-gaidatzis** [comment]
Are there any suggestions for a fix?

i have the same issue..
macOS 12.3
2 GHz Quad-Core Intel Core i5 from 2020

Sync to peer is not possible

**Comment by izzycsy** [comment]
Hi @neuriGH @Mark76DefiChain @stergios-gaidatzis , regarding the issue #1160 , we can further discuss the issue there. Kindly copy and paste your comment there, also please save your app log & node log; and attach them together with your comment, so the team can investigate. We would like to keep same issues in one thread. Thank you! 

<img width="275" alt="1 App logs" src="https://user-images.githubusercontent.com/65014479/160771130-8ce01b09-a9d1-4ad4-bd48-8a7e64be9433.png">

<img width="547" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/160771159-474c2bb1-2e1e-46db-bb2f-13f806504cfb.png">

**Comment by Mark76DefiChain** [comment]
Hi, please find attached the crash report and the logs...

I closed 2.9.1. and than installed 2.9.3

[2022-03-30-mark76-wallet293.zip](https://github.com/DeFiCh/app/files/8378337/2022-03-30-mark76-wallet293.zip)

**Comment by thedoublejay** [comment]
HI @Mark76DefiChain, this is a preview build of the upcoming app release (with the new node). Can you try if this version is opening on your end? - https://github.com/DeFiCh/app/releases/tag/v2.10.0-alpha.1

Take note it's a dev build so only run it but don't do any transactions yet
