### ISSUE TITLE
Passphrase bug

### ISSUE THREAD

**Issue by finkels1** [DeFiCh/app#1168]
#### How to reproduce it (as minimally and precisely as possible): Uninstall DeFi Wallet Mac desktop app, reinstall newest version, log in, generate new wallet address, deposit, attempt swap/withdrawal

I downloaded and used DeFi Wallet desktop app in December, then uninstalled it. I reinstalled it on 03/25/2022, opened and signed in with passphrase. Sign in was successful, I saw all my previous transactions/balances etc. I then generated a new DFI address. I sent 153 DFI from Cake DeFi mobile app to new DFI address on desktop. Wallet address and transaction here: https://defiscan.live/address/dabZFCBciys5PGsE3M3qYQiYfMiky4Vd71.
 
After transaction was confirmed on the desktop platform, I attempted to swap DFI for dUSDT using the new wallet address. **I was prompted for passphrase again, which I entered. It now said my passphrase was incorrect. I tried several more times, still incorrect.**
 
**This is the same passphrase that had just worked minutes earlier, before generating new DFI address.** Now I am unable to move the 153 DFI I transferred into my wallet; the coins are essentially lost to me at this time. I can't afford this loss; I am a grad student with a wedding to pay for. Devs, please assist.

#### What are your environment parameters?

- DeFiCh/app Version: 2.9.3
- Operating System (OS): Mac OC Monterey 12.1
– RAM (GB): 8 GB
– CPU (Intel Core i5/i7/etc.): Apple M1
- Current free storage capacity: 116.27 GB
[Logs.zip](https://github.com/DeFiCh/app/files/8381430/Logs.zip)

**Comment by izzycsy** [comment]
Hi @finkels1 , we've no control over your passphrase. Please try to remember your passphrase, there's no limit to trying.

**Comment by finkels1** [comment]
Is there a minimum number of characters, are any special characters excluded, or any other criterion for it? One word or multiple?

**Comment by izzycsy** [comment]
Hi @finkels1 , it's one word with a minimum of 9 characters, special character is optional.

**Comment by izzycsy** [comment]
Hi @finkels1 , update [v2.13.0](https://github.com/DeFiCh/app/releases/tag/v2.13.0) is out, this is a **mandatory update**. Kindly `backup wallet` and read through the release notes before updating. I'll be closing this issue in the mean time. You may reopen this issue if there's new information. Thank you.
