### ISSUE TITLE
Exporting transactions including rewards not working over ~10,000 records

### ISSUE THREAD

**Issue by stevemccann** [DeFiCh/app#1171]
#### Actual behavior:

I'm trying to export my transactions to calculate taxes. Things appear to export okay when not including rewards. When I select including rewards, if changing the "Limit to last x transactions" to something like 10,000, the CSV only contains approx 1,200 rows.

When I check the "Include Rewards" box on the initial transactions screen, I can see there's over 3 million transactions. However, I can't seem to export this either in chunks or full at the moment.

Right away or a few seconds after when I click on export, I can see a CSV file generated. But it's only about 200KB and 1,200 rows.

I can see when I enter 1 million records to be exported, the defid service on my computer runs for around 10 minutes at 100% CPU and then stops. However, the CSV is not updated with the full result list.

#### Expected behavior:

I expect the full CSV to be generated. Given there's over 3M transactions, the number of transactions to export should be possible up to that amount. If over a certain amount is troublesome, the max export size could be limited, or a warning given.

#### How to reproduce it (as minimally and precisely as possible):

1. Load a wallet in the Mac desktop app with a large amount of transactions (including rewards). In my case it's 1,000 plus transactions, and over 3M including rewards.
2. Select the "Transactions" tab on the left side of the wallet
3. Click the checkbox "Include rewards" in the top right. Wait for the transaction count to reload
4. Select "EXPORT DATA" in the top right of the wallet
5. Click "Include reward transactions" 
6. Change the "limit to last" number to something like 10,000, or larger. Wait for the EXPORT button to turn from grey to pink again.
7. Click EXPORT, choose the CSV file name / location. Click Save
8. Observe the file output. Check if the CSV has the expected number of rows/transactions

#### What are your environment parameters?

- DeFiCh/app Version: 2.9.3
- Operating System (OS): Mac OS Monterey 12.3
– RAM (GB): 64 GB
– CPU (Intel Core i5/i7/etc.): Apple M1 Max
- Current free storage capacity: 1.17 TB

**Comment by izzycsy** [comment]
Hi @stevemccann , unfortunately [this issue](https://github.com/DeFiCh/app/issues/979) is still pending, you'll have to rely on other project such as https://dfi.tax/; done by the community or get your transaction history from https://defiscan.live/ — paste your address to generate the transactions. 

You may copy and paste your comment above in the thread related. We would like to keep same issues in one thread. Thank you for your understanding.
