### ISSUE TITLE
Missing UTXO after update to 2.10.0

### ISSUE THREAD

**Issue by Gilli1545** [DeFiCh/app#1173]
#### Actual behavior:
- Wallet 2.10.0 shows less UTXO than 2.9.3 (same Block)
- 2.10.0: "listaddressgroupings" shows only four addresses
- 2.9.3: "listaddressgroupings" shows dozens of addresses

#### What are your environment parameters?

- DeFiCh/app Version: 2.10.0
- Operating System (OS): Windows 10

#### Anything else we need to know?
After sending max defi to the same address both Wallet (2.9.3 an 2.10.0) show the same count of UTXO and Token.

**Comment by izzycsy** [comment]
Hi @Gilli1545 , can you attached a screenshot of your issue? Trying to understand how to reproduce your issue, when you updated to v2.10.0, your UTXO balance is missing? Can you attached your app & node logs please. Thank you. 

<img width="275" alt="1 App logs" src="https://user-images.githubusercontent.com/65014479/166900547-38c84c60-c50f-4bc7-b4c1-968169d12d49.png">

<img width="547" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/166900558-fd9b2590-4626-4b84-9681-05b2ce3b4748.png">

**Comment by izzycsy** [comment]
Hi @Gilli1545 , update [v2.13.0](https://github.com/DeFiCh/app/releases/tag/v2.13.0) is out, this is a **mandatory update**. Kindly `backup wallet` and read through the release notes before updating. If your issue persists, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
