### ISSUE TITLE
Windows Desktop Wallet v.2.10.0 - error occured - corrupted database block

### ISSUE THREAD

**Issue by gdouramanis** [DeFiCh/app#1175]
#### What happened:

After installing the new desktop wallet v2.10.0 by downloading the snapshot and restart the desktop wallet app in my windows PC, the desktop wallet sync and works good but after closing the desktop wallet app and starting this desktop wallet in the same day, some hours later then I get the error occured - corrupted database block - and then I do this again, 1. download snapshot , 2. start the desktop wallet app, 3. the wallet sych to 100% and works good but after closing the wallet (after 100% synch) and start the wallet some hours later, this error come again and again and ... never ending story...

#### What you expected to happen:
After downloading the snapshot and restart the desktop wallet app should be sync and working properly

#### How to reproduce it (as minimally and precisely as possible):
After 100% synch from desktop wallet app v.2.10.0 and closing the updated desktop wallet app with version v2.10.0 and opening again then is coming the same error message: error occured - corrupted database block , check attached files (screenshots)

#### Anything else we need to know?:
![error_dfi_desktop_wallet_01](https://user-images.githubusercontent.com/25442186/161697484-9db99133-59d6-477f-bcb3-46910de1ae37.JPG)
![error_dfi_desktop_wallet_02](https://user-images.githubusercontent.com/25442186/161697508-e6eead1e-3370-4c2b-8a01-a5958ffe97b6.JPG)

**Comment by RoflWolke7** [comment]
Same issue here.
Seems that the app does not gracefully stop the defid.
Happens also while closing wallet and try to open another wallet file.
defid is "killed" (no shutdown messages in debug.log) and restartet and then it complains about corrupted block database..

**Comment by gdouramanis** [comment]
The thing ist how to solve this please?

**Comment by RoflWolke7** [comment]
"Workaround" for normal usage (without switching wallets) would be to enter a "stop" in the CLI and wait for shutdown before closing the app.

**Comment by gdouramanis** [comment]
I do not understand how to solve this please.. .I am not a full stack developer and when I start the wallet I have this error. Also I have delete all files and installed the desktop wallet app in my windows as new one but I have again the same issues. I have thousand of dollars to my DEX Wallet and I want to have an access again, with a workarround or a bug fix issue or a user guide instruction how to solve this, or can you fix this with a app update? I will appreciate your help, so that I can start this desktop wallet app with my funds again.

**Comment by RoflWolke7** [comment]
I'm also a "user" and not a (DeFiCh) developer.
Again: When you start you have this error. OK.
Then download the snapshot and let the app sync.
If app is synced you have access to your funds and can interact with the blockchain.
But please do not close the app using the app itself.
In the app, open the "console" (button on the left bottom), enter "stop" and wait 1 minute.
After that you can close the app.
If you restart the app afterwards, all shoud be fine.
(But don't forget to use "stop" every time before closing the app.)

**Comment by gdouramanis** [comment]
Yeah but this is not a normal workarround and I need an info from the developer team how to fix this for ever. This is not fine every time to write in CLI stop, then closing the app and the next time again and again, it must be fixed from the software developer team and that is what I am asking for. I do not want a "recommendation" here from a user, but an expert how to solve this. (thanks for your help, I really appreciate, but I do not want as I told you a reccomendation from a user, that have the same problem ) but a help and a officially solution from the developer team to check and advise.

**Comment by gdouramanis** [comment]
Now I try to start the desktop wallet again and to make the snapshot synch and I get this error message
![error_dfi_desktop_wallet_05](https://user-images.githubusercontent.com/25442186/161774524-3f01395c-bcd8-4d32-89b7-30e9e3142839.JPG)

**Comment by Gilli1545** [comment]
Same Problem here
- "Corrupted block database..."
- "Verbindung mit dem Node ist getrennt"

**Comment by thedoublejay** [comment]
We're currently checking this issue. Thanks for the details

**Comment by thedoublejay** [comment]
Hi, please try out [v2.11.0](https://github.com/DeFiCh/app/releases/tag/v2.11.0) and see if it fixes your issue.

**Comment by Gilli1545** [comment]
No crashes anymore after v2.11.0 here

**Comment by gdouramanis** [comment]
Thank you for your help and your information! I have just downloaded and successfully installed the v2.11.0 without any problem! Best regards,
George from Austria
