### ISSUE TITLE
Initial rebuild wallet 2.10.0 from prev. backup on a new System (win) fails without after loading snapshot 1767923

### ISSUE THREAD

**Issue by BuckPi** [DeFiCh/app#1177]
#### Actual behavior:
I've done this on a win 10 after deinstallation and cleaning DFI-folders ind AppData\Roaming and AppData\Local (1) and on a new System win 7 in VBOX --- The Same behavior for both:
- Installation works fine and i can start the app
- I chose rebuild with an existing backup file
- The synchronization starts with 0 % ..., via i-Butten I choose snapshot Europe 1767923 (default)
- After loading until 100 % of the snapshot, the synchronizition can't be continued: 

"Snapshot wurde angewandt" and over this "Verbindung mit dem Node ist getrennt". 
The rebuild Process is unpossible with an unsynchronized wallet (?). After closing (waiting...) and retstart the wallet syncs, but it is not rebuild (no asking for wallet backup). There is no wallet recieve address and zero content.

#### Expected behavior:
complete synchronization and backup-file questioning. 

#### How to reproduce it (as minimally and precisely as possible):
- New install from the scratch

#### What are your environment parameters?

- DeFiCh/app Version: 2.10.0
- Operating System (OS): win 10 & win 7
– RAM (GB): 16 & 8
– CPU (Intel Core i5/i7/etc.):  i7
- Current free storage capacity: > 4 GB

#### Anything else we need to know?

[logs.zip](https://github.com/DeFiCh/app/files/8428326/logs.zip)

**Comment by thedoublejay** [comment]
Hi, please try out [v2.11.0](https://github.com/DeFiCh/app/releases/tag/v2.11.0) and see if it fixes your issue.
