### ISSUE TITLE
Unable to restore wallet

### ISSUE THREAD

**Issue by guiphil** [DeFiCh/app#118]
This has already been posted on [Reddit (Unable to restore wallet)](https://www.reddit.com/r/defiblockchain/comments/kamg5a/unable_to_restore_wallet/) but I thought it's handy to have the issue tracked in here as well: 

I've created a new wallet under DeFi App Version 2.1.1 and wrote down the **24-words mnemonic seed**. 

Now at DeFi-App version 2.1.3 when trying to restore my wallet with the 24-word I get the message "**Not a valid mnemonic**". I double-checked, each of my words is in the **BIP-0039 Word List**. I've tried several times now, double and triple checked + I'm 100% sure that the words are correct.

The error message "**Not a valid mnemonic**" comes in the instant when I press "**RESTORE**". So it seems like it just does not recognize those words as being correct BIP-0039 words?

I found out another thing: Shouldn't it be possible to randomly select 24 words from the BIP-0039 word list and restore a wallet from them? If so, this is not possible either. Would an example be helpful?

When I generate a new wallet in the DeFi-App via "Create a new wallet" I'm able to it with the 24-words after resetting the DeFi App, so this is working.

- I'm using Windows 10 (Build 19041.685). DeFi App Version 2.1.3.
- I've completely uninstalled DeFi App and deleted the blockchain files (/%appdata%/DeFi Blockchain).
- When opening the App, I wait until it's fully synchronized.
- After that, I click on "Restore wallet from mnemonic seed" and type in my 24-word seed (Every Word is in the BIP39 word list)
- I've made sure to only type **lowercase and no spaces** in the fields.
- When clicking "RESTORE", I instantly get the message "**Not a valid mnemonic**"

[DeFi-App Screenshot 1](https://imgur.com/CGnNvOE), [DeFi-App Screenhot 2](https://imgur.com/0CLcUIR)

If you need any further information, I'm happy to help.

Thanks a lot in advance!

Cheers,
Phil

**Comment by guiphil** [comment]
Update: I found out that my 24-word BIP0039 Words **do not have a valid Mnemonic code checksum**. I think this is why 
DeFi-App straight says "**Not a valid mnemonic**" when trying to restore the wallet. Still don't know why/how a 24-word Mnemonic seed with invalid checksum was generated by DeFi-App.

**Comment by izzycsy** [comment]
Hi @guiphil , thanks for your feedback here and on Reddit. Please give us some time to investigate the issue.

**Comment by guiphil** [comment]
Hi @izzycsy, 
unfortunately, all mnemonic 24-words are stored in plain text in the App Logs (not nice) after a wallet has been failed to restore, but this has already been fixed in commit 1773f07a597239ca1dbec4235761ebc0317ddfa9.

**I solved the issue by now.** The problem was one wrong letter in one of my words (So it was my fault.. sorry)

With the help of the checksum (last word) and lots of Python, I was able to brute force potentially wrong words and was so able to reduce the potential words to a minimum. (Good that there is a checksum)

For the ones who might run into the same issue that your checksum is wrong, or more precise, **that you have one wrong word in your 24-mnemonic words (maybe a typo, you can't read one word anymore, you lost one words etc.)**
This is what you can do:

1. The BIP-0039 List has 2048 words, you need 11 bit (2^11 = 2048) to display one word. 
2. So your 24 words is just a 24x11 Bit = 264 Bit long number
3. The checksum is the last 8-Bit (2 bytes) of your last words (11-bit).
    e.g. if the last word is = 'bullet' -> BIP-0039 index 241 -> to bin -> 00011110001 (11 Bit) ->
           last 8 bit: checksum_bin=11110001, checksum_hex-> F1
4. The checksum is calculated by calculating SHA256 hash over the first 256-Bit (32 byte) of your words
    That's the first 23 words (23x11Bit = 253 Bit + the first 3 bit of the last word = 256 Bit)
5. The Checksum is the first byte (8 bit) of the calculated SHA256 hash over the first 256-Bit of your words. 

Now, my assumption was that there is **only one wrong word** in my 24-word AND that the **checksum (last word) is correct.**
My idea was to replace each of my 24-words with each of the 2048 words from BIP-0039 and try them out to restore my wallet. 
That makes 23x2048 = 47104 potential combinations, that's quite a lots. 

To reduce the potential wallets to restore, I selected only 24-Word combinations that had a **valid checksum!**
_(So the starting point for here was that I had 47104 potential 24-word combinations (but not all of them had valid checksums))_

1. For each of the 47104 potential wallets, compute a SHA256 hash over the first 256 Bit. 
2. Compare the first 8 bit of the SHA256 (8-Bit checksum) with the checksum of your original 24-words ('bullet' -> 'F1' from the example above) 
3. Only if the calculated checksum is the same as the checksum of your 24 words, write down that combination. 
4. I ended up with 191 potential 24 mnemonic words, that also had the checksum 'bullet' (last 8-Bit of 'bullet')
5. Because I only changed one word at a time, I could then go through each of the potential correct words and compared the i-th word of my output to the i-th word of my 24 mnemonic words and look words that are similar. 

**Full example:**
BIP39 Mnemonic: `fashion staff across barrel dentist trophy vicious coconut wish income female multiply empower badge victory adult easy sock capable census boost steak find duty`
This Mnemonic is a randomly generated one and I misspelt one word on purpose, so it has a wrong checksum. 
But how do we fix this?
If you put those words into my tool, you get the following output: 
<pre><code>01010011010 11010100000 00000010010 00010010110...  
fashion     staff       across      barrel...    

Entropy hex: 535a80090963a9d1fce167fc8e5153c8b49022fce81e45d9c08792a19baa15aa
Last Word: bin 01000100100 | dec  548 | 'duty'
Checksum:  bin    00100100 | dec   36 | hex 0x24

Starting 24-word mnemonic that also have the checksum '00100100'...
FOUND! 24-word index:  1 | Word: blue     | 11-Bit chunk: 00011000010
FOUND! 24-word index:  1 | Word: cart     | 11-Bit chunk: 00100011000
FOUND! 24-word index:  1 | Word: cute     | 11-Bit chunk: 00110110101
FOUND! 24-word index:  1 | Word: elegant  | 11-Bit chunk: 01000111100
FOUND! 24-word index:  1 | Word: grab     | 11-Bit chunk: 01100101010
FOUND! 24-word index:  1 | Word: imitate  | 11-Bit chunk: 01110001011
FOUND! 24-word index:  1 | Word: notice   | 11-Bit chunk: 10010110111
FOUND! 24-word index:  1 | Word: sadness  | 11-Bit chunk: 10111101111

FOUND! 24-word index:  2 | Word: divide   | 11-Bit chunk: 00111111111
FOUND! 24-word index:  2 | Word: engine   | 11-Bit chunk: 01001010011
FOUND! 24-word index:  2 | Word: estate   | 11-Bit chunk: 01001101011
FOUND! 24-word index:  2 | Word: fat      | 11-Bit chunk: 01010011011
FOUND! 24-word index:  2 | Word: naive    | 11-Bit chunk: 10010010101
FOUND! 24-word index:  2 | Word: rain     | 11-Bit chunk: 10110001000
FOUND! 24-word index:  2 | Word: reduce   | 11-Bit chunk: 10110100000
FOUND! 24-word index:  2 | Word: renew    | 11-Bit chunk: 10110110001

FOUND! 24-word index:  3 | Word: artist   | 11-Bit chunk: 00001101000
FOUND! 24-word index:  3 | Word: bamboo   | 11-Bit chunk: 00010010000
FOUND! 24-word index:  3 | Word: cross    | 11-Bit chunk: 00110100000
FOUND! 24-word index:  3 | Word: depend   | 11-Bit chunk: 00111010111
FOUND! 24-word index:  3 | Word: giggle   | 11-Bit chunk: 01100001111
FOUND! 24-word index:  3 | Word: habit    | 11-Bit chunk: 01101000001
FOUND! 24-word index:  3 | Word: obtain   | 11-Bit chunk: 10011000100
FOUND! 24-word index:  3 | Word: sad      | 11-Bit chunk: 10111101101
....
</code></pre>

So you go through your 24 words and compare your 1st word with every word FOUND! word with index 1 an look for similarities. Then you do it for the 2nd word etc.

In this example: `FOUND! 24-word index:  3 | Word: cross ` **cross** is very similar to **across**. 
if we replace **across** in our 24-words with **cross** we will get: `fashion staff cross barrel dentist trophy vicious coconut wish income female multiply empower badge victory adult easy sock capable census boost steak find duty`. And that 24-word mnemonic has a valid checksum! So go and restore that wallet and check if it's yours.

If compare every one of your 24-words for similarities in the output you'll end up with maybe 2-3 words that are **very similar**, so those are the 24-word mnemonic wallets you should try. (Worst case you can try all of them)

That way I found a typo in one of my words, it was only one letter that was wrong but resulted in a new word that was also in the BIP-0039. 

If anyone whats to have my Python code feel free to contact me on Reddit: u/dothingsdo I might also upload it into a GitRepo.
