### ISSUE TITLE
BTC balance doesn't get updated after a successful transaction

### ISSUE THREAD

**Issue by Vargentum** [DeFiCh/app#1181]
Hello.
I issued a transaction in BTC network to top up my DeFI Wallet account. Tx got [confirmed](https://www.blockchain.com/btc/tx/d315a54a8293921d9fbed378cb6fca98cffdd5aa5a9b5ef70545129e0f0adf33), but my balance in a wallet doesn't get updated. I did a complete app reinstall, but nothing changed. 

I could see the address that received my satoshis in `spv_getalladdresses`

<img width="497" alt="image" src="https://user-images.githubusercontent.com/1523941/162578553-8fe2b495-b5a3-4a4c-a851-e43ca97953d5.png">

My DFI balance is 0. Could it be the reason?

DeFi Wallet OSX version 2.11.0

**Comment by Vargentum** [comment]
My BTC balance got updated on the main screen, but not in Liquidity or DEX panels. So I'm unable to use this functionality.

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/1523941/162590911-acf7258e-f348-4812-8492-3324d6053928.png">

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/1523941/162590922-223b3e7f-684e-44af-be19-7f98b240aa9c.png">

**Comment by izzycsy** [comment]
Hi @Vargentum , at the moment for native BTC being sent to DeFiChain desktop app, it can only be for send (to and fro from your BTC address on BTC Network) & swapping of BTC to dBTC, and vice versa. This is also known as [Atomic Swap](https://github.com/DeFiCh/icx-makerbot). Users from the community have already open a discussion on this: (further intregration of native BTC support #1083)[https://github.com/DeFiCh/app/discussions/1083]

If you would like to use the other features, you'll have to send DFI instead. To send DFI, you may do so from exchanges which supports DFI via DeFiChain Network — KuCoin, Bittrex, Hotbit just to name a few. To wrap other tokens such as USDT to dUSDT, BTC to dBTC, or ETH to dETH, you can go through CakeDeFi to wrap and up-wrap. Thank you.
