### ISSUE TITLE
Using BTC in DEFICHAIN APP

### ISSUE THREAD

**Issue by JoergHoffmann** [DeFiCh/app#1184]
I sent BTC from Cake to the DefiChain app. These have also arrived. Actually, I wanted to use it for liquidity mining with DFI. But I can't seem to use the BTC. I thought I have to swap these into dBTC on the DEX, but I can't. Now I wanted to send the BTC back to Cake, but that doesn't work either, "Insufficient fund to cover fee". I have 0.00428773 dBTC and 48.688 UTXO DFI, where is the error?
![insufficent](https://user-images.githubusercontent.com/18046932/163728547-dc80af43-51c7-4864-b684-57080382775c.JPG)

**Comment by izzycsy** [comment]
Hi @JoergHoffmann , if you're sending BTC out of the desktop wallet, fees are in BTC (0.000005 BTC). What is your BTC balance? dBTC and BTC are different tokens. 

Also, at the moment for native BTC being sent to DeFiChain desktop app, it can only be for send / receive (to and fro from your BTC address on BTC Network). If you would like to use the other features; on DeFiChain Network, you'll have to send DFI instead. To send DFI, you may do so from exchanges which supports DFI via DeFiChain Network — KuCoin, Bittrex, Hotbit just to name a few.

**Comment by JoergHoffmann** [comment]
Problem is solved. I got help from the Telegtram group. I have uses Electrum wallet to go trough.
