### ISSUE TITLE
Merging funds across different sub-addresses not possible

### ISSUE THREAD

**Issue by kjb92** [DeFiCh/app#1188]
#### Actual behavior:
I want to send out all my DFI from my desktop wallet app (running on windows) to another wallet, but have several "sub-addresses" where my DFI are scattered across - some in DFI_AccountToken, some in UTXO on my "main" address. I read about converting all the DFI_AccountTokens to UTXO first before sending them all out, which I already know to do by simply sending DFI to my own address, BUT this is when the problem comes in: I cannot select the "sending-FROM" sub-address where the DFI are supposed to be taken from. Why is that so? And how then do I achieve to merge all my scattered DFI to ONE address within my wallet? 

Add: I also have the same issue with dBTC scattered across several sub-addresses, but I guess that the solution to merge them will be the same as for DFI. 

#### Expected behavior:
A) I expect the app to pull the amount I want to send out of the wallet automatically from the sub-addresses where I have enough funds without me having to coordinate that manually.
OR B) It would be very helpful to being able to select the "sending-FROM" address as simple as the "sending-TO" address. 

#### How to reproduce it (as minimally and precisely as possible):
see above 

#### What are your environment parameters?

- DeFiCh/app Version: 2.11.0
- Operating System (OS): Windows 10
– RAM (GB): 
– CPU (Intel Core i5/i7/etc.): 
- Current free storage capacity:

**Comment by kjb92** [comment]
@izzycsy can you help here? You already solved one of my issues once so I was hoping that I can count on you again 🙏 Is my description of the issue accurate enough? Thanks in advance!

**Comment by izzycsy** [comment]
Hi @kjb92 , on the desktop app selecting the address is not possible at the moment; as you understood, it's automatically selected, however, what I would suggest is using the DeFiChain Light Wallet on mobile, you'll be able to better control multiple addresses on the mobile app. 

Do note that the DeFiChain [Light Wallet app](https://github.com/DeFiCh/wallet)'s & [Desktop app](https://github.com/DeFiCh/app)'s restoration methods are irrelevant; meaning to say you can't load the 24 words from mobile app on to the desktop app and neither can you load the `wallet.dat` from the desktop to mobile. If you would like to use the mobile app (saving the hassle of running a full node wallet), you'll have to create a new wallet and transfer your funds to the mobile app. 

The team is currently working on integrating the mobile & desktop app — so you can use the same 24 words account concurrently. As for now, these are 2 independent applications. Hope this resolves your issue.

**Comment by kjb92** [comment]
Hey @izzycsy, thanks for your lightning-fast reply! I understand everything you're saying and appreciate your response. 
However, I already have my funds stuck in the desktop app and now I'm trying to get them out of there :/ So, do you have an idea how I could step-by-step empty all the sub-address in my desktop wallet? I have 4 sub-addresses which all contain DFI & dBTC and I want to send everything to my Cake DeFi Wallet. How do I do that currently when the desktop app selects the source address automatically? Do I have to play around with the amounts I want to send so the app hopefully selects the right sub-address to send it from? :/

**Comment by izzycsy** [comment]
Hi @kjb92 , yes, you can:
1. Select dBTC > `MAX` > select `SEND` 
2. Select DFI > `MAX` -1 (as a balance of 1 DFI must remain in your desktop app) > select `SEND` 

Same steps apply if you're sending it to Light Wallet.

**Comment by kjb92** [comment]
Awesome @izzycsy, I made it work! Thanks!
