### ISSUE TITLE
I want to add Ukraine language to the desktop wallet

### ISSUE THREAD

**Issue by dzensik** [DeFiCh/app#1195]
Hi guys, I would like to add by myself the Ukraine language. How should I proceed? Just open a PR? Is there anybody who should make the decision first whether it is something valueble and therefor is worth to add it? Thank you in advance

**Comment by izzycsy** [comment]
Hi @dzensik , feel free to contribute a PR. Posting your suggestion here might have more responses from the community https://www.reddit.com/r/defiblockchain/new/. Closing this issue as it's not a bug. Thank you.
