### ISSUE TITLE
'Liqidity' screen causing app crash

### ISSUE THREAD

**Issue by Darkman-Q-Tester** [DeFiCh/app#1197]
Actual behavior: Windows Wallet App is crashing when clicking on 'Liqidity' tab.

Expected behavior: Liqidity screen should open without crashing/closing the app.

How to reproduce it (as minimally and precisely as possible): Open the Defi Wallet PC App, let system sync to 100%, click on 'Liqudity' button. 

What are your environment parameters?

    DeFiCh/app Version: 2.12.0
    Operating System (OS): Win 10 Pro 21H2 (Build19044, 1645)
    – RAM (GB): 32 GB
    – CPU: Intel i7-8700
    Current free storage capacity: 240GB

Anything else we need to know?
I'm running this DeFi Wallet on this PC since beginning and never had this issue. Now since about two weeks it more and  more frequently to crash when clicking on 'Liquidity' button (1 of 10) now today 9 of 10 times the app is crashing.
No changes on this PC except the regular windows updates.
The issue was also existing with version 2.11.0

--> For me it looks like a network timeout issue because my PC is running with VPN connection. It's more likely not to crash when VPN is off. But in any case the app should not crash/close.

Logs
[main log.zip](https://github.com/DeFiCh/app/files/8612038/main.log.zip)

Normally the liquidity tab looks like this in my Wallet:
![grafik](https://user-images.githubusercontent.com/77509687/166497230-5527b8fb-53fb-4f7f-96b1-c7b8a5b97fef.png)

but when the problem occurs appears first "Loading" for about 30 seconds
![grafik](https://user-images.githubusercontent.com/77509687/166497716-efebe761-c1e9-45c5-afb4-e90fdd4ea438.png)

then this screen
![grafik](https://user-images.githubusercontent.com/77509687/166497826-bb08af65-4744-4216-bbff-5b6cf0c269bc.png)

--> then the app is closed/gone.
It should not crash.

**Comment by thedoublejay** [comment]
@Darkman-Q-Tester per the logs, I think there was a network issue. Not sure if this is an isolated case or will happen when there's no internet

**Comment by Darkman-Q-Tester** [comment]
This happens all the time 9 out of 10 times, even while I'm working online. I have a fiber optic line with 100% availability, even my VPN works perfect.
![grafik](https://user-images.githubusercontent.com/77509687/167090303-b766f97f-4523-452e-8532-77e159075d8c.png)

**Comment by izzycsy** [comment]
Hi @Darkman-Q-Tester , update [v2.13.0](https://github.com/DeFiCh/app/releases/tag/v2.13.0) is out, this is a **mandatory update**. Kindly `backup wallet` and read through the release notes before updating. Can you try and see if it's fixed for you?

**Comment by Darkman-Q-Tester** [comment]
Hello Izzycsy,
issue is still happening with v2.13.0 but looks better/more stable. It is only crashing 3 of 10 times.
Workaround is to click on Liquidity and than on "ADD LIQUIDITY" before crashing to select the pair manually.
If you want you can close this issue.
Thank you

**Comment by izzycsy** [comment]
Hi @Darkman-Q-Tester , thanks for the update. If you're running other applications while DeFi app is running, try closing them. Alternatively, you could use the [Light Wallet](https://github.com/DeFiCh/wallet) — does not require running a full node, available on both App Store and Play Store. Thanks!
