### ISSUE TITLE
DefiChain Wallet: Snapshot is not working (on Windows)

### ISSUE THREAD

**Issue by jaliniki** [DeFiCh/app#1201]
#### Actual behavior:
When trying to use a Snapshot instead of the block synchronization, it's not working.

#### Expected behavior:
Snapshot downloading.

#### What are your environment parameters?

- DeFiCh/app Version: 2.12.0
- Operating System (OS): Windows 10
– RAM (GB): /
– CPU (Intel Core i5/i7/etc.): /
- Current free storage capacity: /

**Comment by thedoublejay** [comment]
@jaliniki do you still have this issue now?
