### ISSUE TITLE
Can't add any liquidity except DUSD - DFI - all others like BTC-DFI - It seems on the left pair side exists just DUSD - even I have BTC in the balance

### ISSUE THREAD

**Issue by Sigibret** [DeFiCh/app#1214]
#### What are your environment parameters?

- DeFiCh/app Version:
- Operating System (OS): 
– RAM (GB): 
– CPU (Intel Core i5/i7/etc.): 
- Current free storage capacity:

**Comment by Zettt** [comment]
I'm having the same issue.

**Comment by Zettt** [comment]
I'm having the same issue. More specifically, I'm getting stuck on the "Preparing UTXO" screen. It seems like there's nothing going on, but waiting (don't know for how long) still adds the liquidity at some point. No, it never finishes with "Adding liquidity".

**Comment by Sigibret** [comment]
The problem was / is, the system ignores the real BTCs - you just can use
wrapped BTC. (dBTC)

Am Fr., 19. Aug. 2022 um 00:40 Uhr schrieb Zettt ***@***.***>:
