### ISSUE TITLE
New Error: Test AccountToUtxosTx execution failed: tx must have at least one input from account owner

### ISSUE THREAD

**Issue by pmjlaw** [DeFiCh/app#1220]
![Screenshot 2022-09-05 at 10 55 12](https://user-images.githubusercontent.com/88074488/188409930-aa9b61ad-3995-451d-9344-03c588f86c66.png)

#### What are your environment parameters?

- DeFiCh/app Version: 2.19.0
- Operating System (OS): MaCOS
– RAM (GB): 8 GB
– CPU (Intel Core i5/i7/etc.): 
- Current free storage capacity: 2.42

#### Anything else we need to know?

[Archive.zip](https://github.com/DeFiCh/app/files/9487955/Archive.zip)

**Comment by pmjlaw** [comment]
Just to add a quick update, I did try to transfer 300 DFIs from cake to my browser wallet, which arrived but the same error continues to appear, additionally I did try also to send 1 DFI within the wallet to myself and it worked but then the error appeared again, please help. I am not able to send DFI from the wallet.

**Comment by izzycsy** [comment]
@pmjlaw do you have multiple addresses? May i know what's the output of 

`listaccounts {} false false true` and `getbalance` ? You can refer to [this as a guide](https://github.com/DeFiCh/app/discussions/846#discussioncomment-897090) to what's the expected output.

**Comment by pmjlaw** [comment]
Thanks @izzycsy, pls find below. I think I found a workaround - I went to the gear icon in the desktop wallet and selected the button PRE-FUND TXNS and it unblocked my issue so I could transfer the DFIs to KuCoin for example. Have not tried it today yet.

DeFi Wallet v2.19.0 
Node v2.10.0
listaccounts {} false false true
[
  {
    "key": "a914d0a766a666c398bce91c4d445e292236a97caeff87@0",
    "owner": "dYSYhu3iH5kWfup4KdgU9muTG1TwCJaz8x",
    "amount": "153.03242004@DFI"
  },
  {
    "key": "a914d0a766a666c398bce91c4d445e292236a97caeff87@2",
    "owner": "dYSYhu3iH5kWfup4KdgU9muTG1TwCJaz8x",
    "amount": "0.02616319@BTC"
  },
  {
    "key": "a914d0a766a666c398bce91c4d445e292236a97caeff87@5",
    "owner": "dYSYhu3iH5kWfup4KdgU9muTG1TwCJaz8x",
    "amount": "1160.78806402@BTC-DFI"
  }
]
getbalance
0.61812243

**Comment by izzycsy** [comment]
@pmjlaw edited your key & owner to `...`. Thanks for checking, your DFI (UTXO) balance is 0.6 (`getbalance`). Try converting 1 DFI (token) to DFI (UTXO) using `dYSYhu...`. 

1. Copy your address (dYSYhu...)
2. Go to `send DFI`
3. Input 1 DFI
4. Paste the address (step 1)
5. Send

Now go to CLI and input `getbalance`, see if it becomes 1.61812243. 
If not please send the output here. 

You should be able to send with a minimum balance of 1 DFI (UTXO).
