### ISSUE TITLE
Not able to see the amount of UTXO in the MAC OS desktop app. Amount displayed wrongly compared to the explorer

### ISSUE THREAD

**Issue by pmjlaw** [DeFiCh/app#1227]
#### What are your environment parameters?

- DeFiCh/app Version: 2.21.0
- Operating System (OS): Mac OS
– RAM (GB): 
– CPU (Intel Core i5/i7/etc.): 
- Current free storage capacity:

#### Anything else we need to know?

[Archive 2.zip](https://github.com/DeFiCh/app/files/9970856/Archive.2.zip)

**Comment by pmjlaw** [comment]
Thanks guys, I appreciate your help, also when I am trying to check the transaction in the app it takes ages, it shows the list is loading but there is nothing coming...

**Comment by pmjlaw** [comment]
DeFi Wallet v2.21.0 
Node v2.11.1
getbalance
0.26342355
getbalance
0.26342355
listaccounts {} false false true
[
  {
    "key": "a914d0a766a666c398bce91c4d445e292236a97caeff87@0",
    "owner": "dYSYhu3i",
    "amount": "54.33556867@DFI"
  },
  {
    "key": "a914d0a766a666c398bce91c4d445e292236a97caeff87@2",
    "owner": "dYSYhu3i",
    "amount": "0.00008606@BTC"
  },
  {
    "key": "a914d0a766a666c398bce91c4d445e292236a97caeff87@5",
    "owner": "dYSYhu3i",
    "amount": "1160.78806402@BTC-DFI"
  }

**Comment by pmjlaw** [comment]
the question is where is this UTXO and why the DFIs are sent to UTXO and not to the KuCoin account

**Comment by pmjlaw** [comment]
![Screenshot 2022-11-09 at 15 57 43](https://user-images.githubusercontent.com/88074488/200864063-1c351457-8681-4abb-ac64-db96d663b940.png)
Hope this helps, appreciate your kind support!

**Comment by pmjlaw** [comment]
In parallel I have also opened a support ticket with KuCoin, maybe the issue is on their end, however it looks more like the DFIs got sent to my UTXO but why then the desktop application does not show them..

**Comment by pmjlaw** [comment]
Just for your info, I was able to successfully send DFI from the app to my KuCoin DFI account (deposit), however no traces of my UTXOs/aka my previous transaction but in the explorer it shows that I do have that amount

**Comment by pmjlaw** [comment]
![Screenshot 2022-11-09 at 22 50 30](https://user-images.githubusercontent.com/88074488/200949274-c0583916-01ca-4ca7-8ca9-cbf12286321c.png)

**Comment by izzycsy** [comment]
Hi @pmjlaw , if I understand correctly, you sent DFI from app to KuCoin, but the transaction does not display on **Transactions** tab? or do you mean on the **Balances** tab, it does not display the correct remaining amount?

**Comment by pmjlaw** [comment]
Hi @izzycsy, I sent 2385 DFI from app to KuCoin, but this amount has not arrived to my KuCoin Deposit account, and from what I see in app, there was only the transaction from Account to UTXOs, pls see screenshot, but no Sent Transaction.

Now, in my app I do not see the UTXO with this amount, although in explorer it does show that I still have UTXO Balance
2385.12389499 DFI

**Comment by pmjlaw** [comment]
sure, 8a58de8b7fdf181df3ab68bd474b57c74646cb64dde01afdd4b0e8a44211eb1a

**Comment by izzycsy** [comment]
Thanks, can you provide the output of 

`getbalance`

`listaccounts {} false false true`

again please. You may XXX your key, owner, etc. as you did in [this comment](https://github.com/DeFiCh/app/issues/1227#issuecomment-1308875194)

**Comment by pmjlaw** [comment]
sure, sorry for the delay had to restart the app

**Comment by pmjlaw** [comment]
DeFi Wallet v2.21.0 
Node v2.11.1
getbalance
0.67892428
listaccounts {} false false true
[
  {
    "key": "a914d0a766a....97caeff87@0",
    "owner": "dYSYhu3i....Jaz8x",
    "amount": "81.34892445@DFI"
  },
  {
    "key": "a914d0a766a6.....caeff87@2",
    "owner": "dYSYhu3i....Jaz8x",
    "amount": "0.00023243@BTC"
  },
  {
    "key": "a914d0....caeff87@5",
    "owner": "dYSYhu....Jaz8x",
    "amount": "1160.78806402@BTC-DFI"
  }
]

**Comment by izzycsy** [comment]
Thanks. I think you might just have to wait for your DFI to reflect on your KuCoin, delays may occur due to congestion in the block chain. [Ku Coin's 3. FAQ](https://www.kucoin.com/support/900007079063-How-to-Deposit-Crypto-to-KuCoin). There's no in-between state in DeFiChain Network, either your tx gets through / gets rejected and goes back to your app. 

Just a suggestion, if you're not running a masternode, you could use the DeFiChain Light Wallet, available on [iOS](https://apps.apple.com/us/app/defichain-wallet/id1572472820) / [Android](https://play.google.com/store/apps/details?id=com.defichain.app&pli=1). Saves you the trouble of running a full node / cli.

**Comment by pmjlaw** [comment]
thanks @izzycsy I would of course wait and monitor the situation, but what worries me is that there was no SENT Transaction from my app with this amount as it usually happens and why in explorer those UTXOs still sit with my DeFI App account?
Nevertheless thanks a lot, I am of course also contacting KuCoin and hope for the quick resolution

**Comment by pmjlaw** [comment]
When I check in Explorer I do not see any OUT Transaction with that amount (2385.08330890 DFI), there is only IN 
![Screenshot 2022-11-10 at 06 23 06](https://user-images.githubusercontent.com/88074488/201007535-90a4b28e-d4c0-49d2-99f8-27aeda7b84c4.png)

**Comment by izzycsy** [comment]
Hi @pmjlaw , hmm another possibility is that might be the amount was converted to UTXO and not sent. In your screenshots, your app is not synced to 100% as well.  Can you try reindex, guide [here](https://github.com/DeFiCh/app/discussions/899). After syncing to 100%, take a screenshot of your **Balances** and outputs of `getbalance`, `listaccounts {} false false true`.

**Comment by pmjlaw** [comment]
![Screenshot 2022-11-10 at 06 34 14](https://user-images.githubusercontent.com/88074488/201008868-58195d18-ae5c-46d0-9869-8db01bd7acbe.png)

**Comment by pmjlaw** [comment]
it is synchronized now
getbalance
0.67892428
listaccounts {} false false true
[
  {
    "key": "a914d0a76.....caeff87@0",
    "owner": "dYSYhu3i.....Jaz8x",
    "amount": "88.46593402@DFI"
  },
  {
    "key": "a914d0a766.....caeff87@2",
    "owner": "dYSYhu3i....Jaz8x",
    "amount": "0.00024010@BTC"
  },
  {
    "key": "a914d0a7....caeff87@5",
    "owner": "dYSYhu3i....Jaz8x",
    "amount": "1160.78806402@BTC-DFI"
  }
]

**Comment by izzycsy** [comment]
Hi @pmjlaw , did you reindex?

**Comment by pmjlaw** [comment]
not yet, let me do that, would update once done, thanks!

**Comment by izzycsy** [comment]
@pmjlaw use snapshot, it's faster.

**Comment by pmjlaw** [comment]
yes, let me do that now, in fact I have already tried this even before after this situation happened, but just to be sure doing this now again.

**Comment by pmjlaw** [comment]
Issue closed by reindexing

**Comment by pmjlaw** [comment]
Issue closed by reindexing
