### ISSUE TITLE
Unable to send BTC

### ISSUE THREAD

**Issue by HEI1970** [DeFiCh/app#123]
I get an error when attempting to transfer DFI from desktop app

**Comment by izzycsy** [comment]
Hi @HEI1970 , thanks for your feedback. May I know the OS + version no. you're using? Could you describe your user flow more? Screenshots / screen recordings would be helpful as well! We need more details in order investigate how to reproduce this issue.

In the mean time, you may refer to the links attached, hope it addresses the issue you're facing.
<https://www.reddit.com/r/defiblockchain/comments/k92k2l/how_to_rescue_stuck_dfi/>
<https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/>

**Comment by HEI1970** [comment]
Hello, seems you are aware of this issue, as the second document sorted the issue with manual intervention. I would suggest you build the resolve into the code

**Comment by izzycsy** [comment]
Hi @HEI1970 , are you able to send DFI with the new update?
<https://github.com/DeFiCh/app/releases/tag/v2.1.4>

**Comment by kwamelaryea** [comment]
@izzycsy I m not sure the issue I am having is similar to this as for me I am trying to send BTC and the continue button stays deactivated. Anyway I have sent my logs and the screenshot is on my first issue. I look forward to your feedback.

**Comment by izzycsy** [comment]
Hi @kwamelaryea , thank you for your patience.

**Comment by izzycsy** [comment]
Hi @kwamelaryea @HEI1970 , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue w new information (include screenshots) and your app logs. Thank you.

**Comment by izzycsy** [comment]
Hi @kwamelaryea , may I check did you select DeFiChain address on <cakedefi.com> when trying to send BTC? 

<img width="375" alt="Click on DeFiChain" src="https://user-images.githubusercontent.com/65014479/104120495-53120880-5372-11eb-966d-0ee5f1908f85.png">

**Comment by kwamelaryea** [comment]
> Hi @kwamelaryea , may I check did you select DeFiChain address on <cakedefi.com> when trying to send BTC?
> 
> <img alt="Click on DeFiChain" width="375" src="https://user-images.githubusercontent.com/65014479/104120495-53120880-5372-11eb-966d-0ee5f1908f85.png">

Hi @izzycsy, I don't get the option of a Transfer Network when I click send it goes straight to the withdrawal fields and the greyed out continue button. 

![Screenshot 2021-01-11 at 14 50 40](https://user-images.githubusercontent.com/3295096/104191408-c4f35c00-541d-11eb-907b-90e2a6c9fbbf.png)
![Screenshot 2021-01-11 at 14 54 06](https://user-images.githubusercontent.com/3295096/104191434-cb81d380-541d-11eb-91b3-f9392f6e8f0b.png)

**Comment by izzycsy** [comment]
Hi @kwamelaryea , to retrieve the DeFiChain address and paste into your DeFi app is via <cakedefi.com>, try sending a small amount first to test. 

1. Click on `Balances` in <cakedefi.com>
2. In the BTC row, click on `Deposit` button
3. You'll see the Transfer Network options `BTC` `DeFi Blockchain`
4. Under the QR Code states your DeFi address, `copy` it
5. Go to DeFi app > BTC wallet > Send 
6. `paste` your DeFi address into `To address` field

Can you send your BTC?

**Comment by kwamelaryea** [comment]
> Hi @kwamelaryea , to retrieve the DeFiChain address and paste into your DeFi app is via <cakedefi.com>, try sending a small amount first to test.
> 
> 1. Click on `Balances` in <cakedefi.com>
> 2. In the BTC row, click on `Deposit` button
> 3. You'll see the Transfer Network options `BTC` `DeFi Blockchain`
> 4. Under the QR Code states your DeFi address, `copy` it
> 5. Go to DeFi app > BTC wallet > Send
> 6. `paste` your DeFi address into `To address` field
> 
> Can you send your BTC?

@izzycsy Thanks for the steps, I have tried them but I still have the same issue. 
![Screenshot 2021-01-11 at 18 02 04](https://user-images.githubusercontent.com/3295096/104214383-a4d09680-5437-11eb-8233-28a70174b8c5.png)

**Comment by izzycsy** [comment]
Hi @kwamelaryea , regarding the issue `unable to send BTC` could you send your logs to <https://github.com/DeFiCh/app/issues/195>. As I understand you're already in that thread. We will further discuss on the problem there. It seems like one of the use figured out a solution — may or may not work for you. Rest assured, the team is investigating this issue you're facing. Let’s keep this thread related to what the original author opened. Thank you for your understanding.

**Comment by izzycsy** [comment]
Hi @HEI1970 @kwamelaryea , regarding this issue I'll link you to <https://github.com/DeFiCh/app/issues/195> which we can further discuss on the problem. The team is investigating this issue. Thank you.
