### ISSUE TITLE
Project license clarification

### ISSUE THREAD

**Issue by prasannavl** [DeFiCh/app#124]
Hello wonderful team :)

The license section in the readme seemed a bit unclear on how the source code of repo is actually licensed. It has "Copyright 2020 DeFiChain Foundation" - just that without a permissive license to accompany usually indicates it's proprietary.

Whenever you can get around to this:

1. If this was indeed the intention - would be helpful if you could state it explicity - that this is how the source code on this repo is licensed.
2. If this wasn't, and the intention is to make it OSS friendly (like MIT or Apache 2.0, for instance which tends to be very friendly to enterprise contributions, etc) - would be great if you could add that and the LICENSE file.

Thanks! 

Cheers,
Prasanna

**Comment by izzycsy** [comment]
Hi @prasannavl , thanks for your feedback, well noted!
