### ISSUE TITLE
BTC lost while providing Liquidity to the BTC DFI Pool

### ISSUE THREAD

**Issue by AndErazor** [DeFiCh/app#125]
Hi Defi Team,

I transferred some BTC and DFI from Cake LM to my Wallet to start LM there. Unfortunately an error occurred when I wanted to provide Liquidity in the App. After this, my BTC balance in the DFI Wallet is around 0.05 BTC short. I tried analyzing using the Definition Blockchain explorer, but transaction is showing DFI only (no wrapped BTC).

Transaction ID according to the movement of BTC in my wallet is:
5690d907e85c81dea60969ecb9e1e8ac4a3f013fedd3e85d113b39d133474742

<img width="1042" alt="Bildschirmfoto 2020-12-15 um 21 03 04" src="https://user-images.githubusercontent.com/22431911/102266626-ffe69a80-3f18-11eb-9cb1-16d5cdf650cb.png">

[App Log.log](https://github.com/DeFiCh/app/files/5698275/App.Log.log)
[Binary Log.log](https://github.com/DeFiCh/app/files/5698277/Binary.Log.log)

**Comment by AndErazor** [comment]
Ok I found out by using command listaccounts that I seem to have more than one account, not sure how this happened and how to resolve but I see several accounts all assigned to my DFI address as owner as well as there more assigned to a different owner address. I assume both addresses are mine as they get listed by my wallet and seem to contain my missing funds. But how to resolve?

**Comment by PircolosJM** [comment]
I had exacltly the same issue today and i am trying to figure out whats going on.

**Comment by AndErazor** [comment]
Your Excel overview is great, did you add all the transactions by hand or is there an easy way to export all transactions? Will do the same as soon as I find time. In my case the amount is more significant :-(

**Comment by izzycsy** [comment]
Hi @AndErazor , thanks for your feedback and app log. May I know the OS + version no. you're using? Please give us time to investigate this. Thank you for your understanding.

**Comment by izzycsy** [comment]
Hi @PircolosJM , thanks for your feedback as well. May I know the OS + version no. you're using? Could you attach your app log as well? Thank you for your patience.

**Comment by AndErazor** [comment]
I use the latest MacOS ( Catalina ) and the current app version (2.1.3)

Thanks for your support!
Best regards
Andreas

**Comment by PircolosJM** [comment]
> Your Excel overview is great, did you add all the transactions by hand or is there an easy way to export all transactions? Will do the same as soon as I find time. In my case the amount is more significant :-(

Hi Andres
I did the whole thing manually since there were not many transactions.

**Comment by PircolosJM** [comment]
> Hi @PircolosJM , thanks for your feedback as well. May I know the OS + version no. you're using? Could you attach your app log as well? Thank you for your patience.



> Hi @PircolosJM , thanks for your feedback as well. May I know the OS + version no. you're using? Could you attach your app log as well? Thank you for your patience.

I Used Windows 10 - Ver 2004 - OS Build 21277.1000 for this transaction.
Logs have been atached on the main comment.

Thanks

**Comment by izzycsy** [comment]
Hi @AndErazor & @PircolosJM , well received. Please give us time to investigate this issue.

**Comment by PircolosJM** [comment]
Any update on this? This is not a usability issue it involves loss of funds!

**Comment by AndErazor** [comment]
I want to close my bug report. After analyzing all my transactions in detail everything seems to be alright. Not sure how one transaction was caused but no funds are missing in my case

**Comment by PircolosJM** [comment]
> I want to close my bug report. After analyzing all my transactions in detail everything seems to be alright. Not sure how one transaction was caused but no funds are missing in my case

Please Leave this issue open as this is not he case for me as you can see in the XLS i Provided. Thanks

**Comment by PircolosJM** [comment]
Any update on that? Is somebody looking into it? its been 2 weeks!

**Comment by izzycsy** [comment]
Hi @PircolosJM , the team is still investigating this issue along with other bugs as well. I apologise for the delay. The team will be releasing a new update soon, thank you for your patience.

**Comment by izzycsy** [comment]
Hi @PircolosJM , thank you for waiting. We looked at the excel spreadsheet and tracing the BTC-column, it seems like the numbers don't tally. At the end of 6 Dec 2020, the amount was `-0.00001927`. Could it be due your date-column is set to descending order and not ascending in the excel spreadsheet, which perhaps gave you an inaccurate number?  

```
0.36736263
(0.181)
(0.1816)
(0.00001927)
0.00001927
(0.0047819)
—————————————
- 0.00001927
—————————————
```

Could you expand the TR-HASH column and send it over? Thank you.

**Comment by izzycsy** [comment]
Hi @PircolosJM , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue w new information (include screenshots). Thank you.
