### ISSUE TITLE
insufficient funds

### ISSUE THREAD

**Issue by cnigischer** [DeFiCh/app#128]
Dear DeFiCh team,

after synching the blockchain and creating a wallet I've transferred some BTC and USDT to the DFI Wallet-Adress. When trying to swap either the BTC or the USDT to DFI to be able to start liquidity mining, I always receive the error message: "insufficient funds" 

Where have I gone wrong - I'm looking forward to your response.

[binary_log.log](https://github.com/DeFiCh/app/files/5700794/binary_log.log)
[app_log.log](https://github.com/DeFiCh/app/files/5700796/app_log.log)

[app_config.log](https://github.com/DeFiCh/app/files/5700802/app_config.log)

**Comment by izzycsy** [comment]
Hi @cnigischer , thanks for your feedback, you've not gone wrong. The team is currently investigating this issue, thank you for your understanding.

**Comment by cnigischer** [comment]
it seems to be working again, I could at least just swap usdt to dfi

**Comment by Tobias-hub** [comment]
I have the same problem. When trying to swap either the BTC or the USDT to DFI to be able to start liquidity mining, I always receive the error message: "insufficient funds"
I have restarted the app. 
What can I do? Are the coins safe?

![dex](https://user-images.githubusercontent.com/76232128/102672459-20b92500-4191-11eb-8950-344d1a4b2364.PNG)

**Comment by izzycsy** [comment]
Hi @Tobias-hub , thanks for your feedback. Could you send your app.log please? 

Your coins are safe, you can actually check balance via CLI: 
getbalance — utxo DFI 
getokenbalances — DFI  
The sum of utxo DFI & DFI would be what’s displayed in your wallet

The team is currently investigating this issue, thank you for your understanding.

**Comment by izzycsy** [comment]
Hi @cnigischer @Tobias-hub , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue w new information (include screenshots) and your app logs. Thank you.

**Comment by cnigischer** [comment]
thank you, looks good to me.
