### ISSUE TITLE
Can not send DFI from my wallet to Cake | Mac OSX

### ISSUE THREAD

**Issue by Retzor** [DeFiCh/app#132]
Hey Guys,
I have a problem, I can not send my DFI which i got from LM to my Cake account. 
Yesterday it was working. Now the whole day not.
I am in Mainnet and working with a Mac Book late 2012. OSX is 10.15.6 Wallet App version is 2.1.3

Thanks for help 😊 

<img width="1022" alt="Bildschirmfoto 2020-12-16 um 17 44 18" src="https://user-images.githubusercontent.com/76117771/102372025-780b9980-3fc7-11eb-9e72-399fb675b84d.png">

**Comment by starman578** [comment]
Hi @Retzor,
Have you already checked if you have enough coins (instead of tokens)?
Please have a look at the following guide so this potential problem can already be excluded.
If this is fine and you cannot send anyways your app log, binary log and app config would be useful for the developers.
You can easily collect those in the app and upload them here.

**Comment by Retzor** [comment]
Hi @starman578 ,
thanks for getting back to me. Yeah I already tried this solution. Everything fits till the last command when I will change 2 DFI sample Tokens to coins. The console said to me: "Expected type object, got string" and nothing happens. 

<img width="851" alt="Bildschirmfoto 2020-12-16 um 21 37 46" src="https://user-images.githubusercontent.com/76117771/102398382-e2cccd00-3fe7-11eb-8993-0ccf4fb9f7c8.png">

Attached please find my log datas 😊  Thanks very much for getting back again.

[app_config.txt](https://github.com/DeFiCh/app/files/5705159/app_config.txt)
[app_log.txt](https://github.com/DeFiCh/app/files/5705160/app_log.txt)
[binary_log.txt](https://github.com/DeFiCh/app/files/5705161/binary_log.txt)

**Comment by Retzor** [comment]
Got it fixed! Problem was that my text program changed the " in a cursiv one... So to anyone check out your syntax string if all is correct 😉
