### ISSUE TITLE
Sent my USDT/DFI Liquidity Token to my USDT Cake Adress - Assests seem to be lost

### ISSUE THREAD

**Issue by monday24** [DeFiCh/app#134]
I LM some USDT/DFI. As I wanted to change them into another LM-Pair I somehow thought that I need to send them from the DFI App to my USDT Cake Address and then change them into Bitcoin and DFI there. I sent my funds. In the App they now are no more visible. On cake neither. Are my funds lost?

**Comment by izzycsy** [comment]
Hi @monday24 , you could actually use DEX in DeFi app to swap to BTC / ETH / USDT. Have your funds appear on Cake? Withdrawals take around 24 hours to process (may take longer during weekends). <https://cake.zendesk.com/hc/en-us/articles/360035990572-How-can-i-withdraw-funds->. If not, you may want to contact Cake's support team <https://cake.zendesk.com/hc/en-us/requests/new>. 

For DeFi app, to check your balance you may use the following commands: 
Check balance:
getbalance — utxo DFI
 getokenbalances — DFI  
 The sum of utxo DFI & DFI would be your total DFI.

**Comment by izzycsy** [comment]
These links may help as well:
https://www.reddit.com/r/defiblockchain/comments/k92k2l/how_to_rescue_stuck_dfi/
https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/

**Comment by monday24** [comment]
Thank you very much for your support!! In the meantime I got the funds back. Cake support was helping alot!
Thanks for reaching out to me! Have a mery Christmas!
