### ISSUE TITLE
Maximum balance when adding liquidity to pool

### ISSUE THREAD

**Issue by thunderstorm99** [DeFiCh/app#135]
When adding liquidity to a pool clicking on MAX will enter your maximum available balance -1.
I think this should not be the case, as it is possible to enter the 'real' maximum available balance by hand.
If I'm not mistaken the line responsible for this is the following: [webapp/src/containers/SwapPage/index.tsx+226
](https://github.com/DeFiCh/app/blob/master/webapp/src/containers/SwapPage/index.tsx#L226)
it was added by cd6361f though i am not sure as to why

![image](https://user-images.githubusercontent.com/3219279/102563644-0708d680-40da-11eb-9fd9-11360101aa7c.png)

**Comment by izzycsy** [comment]
Hi @thunderstorm99 , thanks for your feedback, please give us time to investigate this issue.

**Comment by izzycsy** [comment]
Hi @thunderstorm99 , thank you for waiting. After some investigation, this seems like a visual bug. The team is in the midst of fixing this. In the mean time, you may try the temporary solution as stated, thank you. 

In input type `1` > click on `MAX`

**Comment by izzycsy** [comment]
Hi @thunderstorm99 , update v2.1.6 is out <https://defichain.com/downloads/>.
I've notified team of this visual bug. Proceeding to close this issue for now, you may reopen this issue if there's new information (include screenshots) and your app logs. Thank you.
