### ISSUE TITLE
Where are my USDT ?

### ISSUE THREAD

**Issue by TomBothe** [DeFiCh/app#142]
Hi support, 
I tried to transfer BTC from my Bybit wallet to my BTC wallet from Defichain. Unfortunately this was not possible because the BTC wallet address of Defichain is not valid. I then sent the BTC to Bittrex, exchanged it to DFI and then sent it to my DFI Wallet at Defichain.
Then I sent 500 USDT to my USDT wallet address at Defichain. These have not arrived to date. What can I do now? 
Where can I track the previous transactions / deposits on chronologically?
Is there any proof of DFI earnings? For example as an Excel download?
Yours sincerely, Thomas Bothe 

[DEFI App Logs.log](https://github.com/DeFiCh/app/files/5717937/DEFI.App.Logs.log)
[DEFI Binary Lgs.log](https://github.com/DeFiCh/app/files/5717938/DEFI.Binary.Lgs.log)

**Comment by KermitIsBack** [comment]
@TomBothe 
I think the is a misunderstanding how DEFICHAIN wallet works. You have to go via CAKE to change BTC and USDT to Tokens.

**Comment by TomBothe** [comment]
Ok, thanks for the answer.
However, I can use defichain.com without Cake. I have exchanged coins on Bittrex and sent DFI to Defichain DFI Wallet. This worked great. Since BTC, ETH and USDT wallets are also shown, I figured I can send USDT to the appropriate wallet as well. I guess that was a mistake. I guess the tokens are gone now?

**Comment by TomBothe** [comment]
> @TomBothe
> I think the is a misunderstanding how DEFICHAIN wallet works. You have to go via CAKE to change BTC and USDT to Tokens.

Ok, thanks for the answer.
However, I can use defichain.com without Cake. I have exchanged coins on Bittrex and sent DFI to Defichain DFI Wallet. This worked great. Since BTC, ETH and USDT wallets are also shown, I figured I can send USDT to the appropriate wallet as well. I guess that was a mistake. I guess the tokens are gone now?

**Comment by KermitIsBack** [comment]
The accounts you see in the DEFIWallet are the accumulated amount of BTC, ETC and USD "tokens" connected with your DEFIWallet addresses on the DEFIChain.
CAKE is the only token connector (Gateway) between other chains and the DEFIChains right now.
So you have send USTD to your DEFIWallet address ... , but on the wrong chain.
Maybe you can contact the other chains dev Team to try to recover the USDT.
If you are lucky the transfer will be cancelled because the address was not valid and the amount shows up again on you original source Wallet.

**Comment by TomBothe** [comment]
> The accounts you see in the DEFIWallet are the accumulated amount of BTC, ETC and USD "tokens" connected with your DEFIWallet addresses on the DEFIChain.
> CAKE is the only token connector (Gateway) between other chains and the DEFIChains right now.
> So you have send USTD to your DEFIWallet address ... , but on the wrong chain.
> Maybe you can contact the other chains dev Team to try to recover the USDT.
> If you are lucky the transfer will be cancelled because the address was not valid and the amount shows up again on you original source Wallet.

Hello Kermit, thank you very much for your support. The amount was in pending status at Bittrex because the wallet address was detected as invalid. I exchanged the amount at Bittrex to DFI Coin and transferred it to Defichain DFI Wallet. Now all is well.... Have a nice day and Merry Christmas.
