### ISSUE TITLE
Token lost

### ISSUE THREAD

**Issue by Tobias-hub** [DeFiCh/app#143]
Dear Team,
at all actions (LM add and remove, DEX, send) I get  the error: Insufficient funds.
So I checked https://mainnet.defichain.io/ and there are no funds on all my addresn.  Where are my tokens?
In the app the tokens are displayed and I also get the rewards. However, the address is missing from the transaction.
thanks for the help
Tobias

![image](https://user-images.githubusercontent.com/76232128/102686127-d746f500-41e5-11eb-9422-44743a9bc5f5.png)
![image](https://user-images.githubusercontent.com/76232128/102686148-f34a9680-41e5-11eb-8877-4355f0f29946.png)

**Comment by UserMaxL** [comment]
I guess you need to convert the tokens first:
https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/

**Comment by Tobias-hub** [comment]
thanks
