### ISSUE TITLE
DEFI Auszahlung von der DEFI Windows Wallet nicht möglich 

### ISSUE THREAD

**Issue by PoseidonXR** [DeFiCh/app#145]
Hallo Team DEFIChain
kann keine Auszahlung der DEFI machen - immer Fehler - zurück zur Wallet
Muß aber meine DEFI tauschen - mein anderes Konto ist leer .
Danke Micha aus Berlin
Super Projekt .

![image](https://user-images.githubusercontent.com/76259286/102694496-b4d2cd00-4221-11eb-8e6c-6417cbb2ada7.png)
<img width="538" alt="2020_12_19_17_44_36_Senden_DeFiChain_Client" src="https://user-images.githubusercontent.com/76259286/102694525-ee0b3d00-4221-11eb-8e58-5cea58cc0d00.png">

**Comment by habop73** [comment]
Habe genau das gleiche Problem.

**Comment by thunderstorm99** [comment]
For all with the same error, this is what helped me: https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/

**Comment by izzycsy** [comment]
Hallo @PoseidonXR , Vielen Dank für Ihr Feedback. Wir sind uns dieses Problems bewusst und untersuchen es derzeit. In der Zwischenzeit können diese Links helfen::
https://www.reddit.com/r/defiblockchain/comments/k92k2l/how_to_rescue_stuck_dfi/
https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/

Thanks @thunderstorm99 for the help!

**Comment by izzycsy** [comment]
Hi @PoseidonXR @habop73 @thunderstorm99 , update v2.1.7 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
