### ISSUE TITLE
Token transactions not transparent in Defi Blockchain Explorer

### ISSUE THREAD

**Issue by AndErazor** [DeFiCh/app#147]
I want to check some transaction in the DeFi Blockchain Explorer as I have issues with the display of some transactions (see issue #146 in the Defi App. Unfortunately the Blockchain explorer is not able to show Defi Token transaction in a transparent way.

This transaction below for example is a LM transfer involving BTC, DFI and BTC-DFI pool tokens. But in the Explorer I only see the corresponding DFI fees. Is there no way to see the underlying tokens? If not, what is the use of the Explorer at all and how should I check transactions?

Transaction ID: 72693ea0b3a23453a42dc1951136b489cdb710e13f48e992f705cbdb39b7468e
<img width="1145" alt="Bildschirmfoto 2020-12-19 um 18 17 30" src="https://user-images.githubusercontent.com/22431911/102695282-84416200-4226-11eb-9c35-142bfa5da6cd.png">

**Comment by izzycsy** [comment]
Hi @AndErazor , thanks for your feedback on this as well as <https://github.com/DeFiCh/app/issues/146>, the team is trying to improve the user experience on transaction history displayed. Thank you.

**Comment by izzycsy** [comment]
Hi @AndErazor , update v2.1.6 is out <https://defichain.com/downloads/>. 
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue w new information (include screenshots) and your app logs. Thank you.
