### ISSUE TITLE
DeFI not arrived

### ISSUE THREAD

**Issue by Kittylesen** [DeFiCh/app#148]
Hi,
I have sent few DeFi Coins from pool cake to my DeFi wallet (app). 
[binary_log.log](https://github.com/DeFiCh/app/files/5720276/binary_log.log)

The first time all coins arrived. The second and third time I am still waiting for the coins.

Could you please help me with my issue.

Best regards
Anna
[app config_app.log](https://github.com/DeFiCh/app/files/5720278/app.config_app.log)
[app_log.log](https://github.com/DeFiCh/app/files/5720279/app_log.log)
[binary_log.log](https://github.com/DeFiCh/app/files/5720280/binary_log.log)

**Comment by izzycsy** [comment]
Hi @Kittylesen , thanks for your feedback. There could be a delay in reflecting your coins, however you can check to see if your balances are there via the CLI: 

`getbalance` — utxo DFI 
`getokenbalances` — DFI  
The sum of utxo DFI & DFI would be your total DFI. 

Let me know if it's reflected. Screenshots would help us in the investigation as well!

**Comment by Kittylesen** [comment]
Hi,
Could you help me with my DeFi Chain wallet.

Every time when I sign in, my coins are on "0". How can I see the actual value and which steps do I have to follow?

Thank you!
Br
Anna

**Comment by Kittylesen** [comment]
Hi,
Could you help me with my DeFi Chain wallet.

Every time when I sign in, my coins are on "0". How can I see the actual value and which steps do I have to follow?

Thank you!
Br
Anna

**Comment by izzycsy** [comment]
@Kittylesen Please refer to the screenshot on how to check your balance in the CLI: 
`getbalance` — utxo DFI 
`getokenbalances` — DFI  
The sum of utxo DFI & DFI would be your total DFI.
<img width="1011" alt="CLI getbalance" src="https://user-images.githubusercontent.com/65014479/103212878-03314b80-4947-11eb-9988-e8cd33026f35.png">



Please give us time to investigate this issue.

**Comment by Kittylesen** [comment]
Perfect! Thanks a lot!

**Comment by izzycsy** [comment]
@Kittylesen i'll proceed to close this issue for now. Thank you.
