### ISSUE TITLE
Mac: Synchronization stuck at 0%

### ISSUE THREAD

**Issue by helmhue** [DeFiCh/app#155]
Hi everyone. I can never get defi-app to sync. It never get's past 0% / never gets past block 0

- I've deleted / redownloaded multiple times
- I'm running the latest (2.1.3)
- I've re-indexed and saved multiple times on multiple versions
- My firewall is off
- I was sure to follow the full mac instructions via the defi chain website 

Any ideas? Thanks for the help!

**Comment by izzycsy** [comment]
Hi @helmhue , thanks for your feedback. Please refer to screenshot on how to save app logs and attach it in your next comment. 

<img width="327" alt="app log" src="https://user-images.githubusercontent.com/65014479/102859027-361aa180-4466-11eb-9c99-9432590abf62.png">

May I know the version your mac (eg. v10.15.7)? How long did you wait while the block is stuck at 0%? Screenshots / screen recordings would be helpful as well! We need more details in order investigate how to reproduce this issue.

**Comment by helmhue** [comment]
Hi @izzycsy 

Yep! Both items attached here. Thanks so much. 

In terms of wait time - as mentioned, I've tried multiple times. Anywhere from a few minutes to multiple hours with the platform running in the background. In terms of screenshots - there's not much to show of the app itself. I open it, the sync never begins, and then sometimes I try to reindex via Settings and Save, but still it remains at zero. 

hope this helps!
[AppLogs_Dec21.log](https://github.com/DeFiCh/app/files/5731532/AppLogs_Dec21.log)
<img width="233" alt="Screen Shot 2020-12-22 at 1 45 03 PM" src="https://user-images.githubusercontent.com/76455062/102923053-0c10b180-445d-11eb-922b-2a1d2f35cfdf.png">
<img width="217" alt="Screen Shot 2020-12-22 at 1 46 35 PM" src="https://user-images.githubusercontent.com/76455062/102923055-0c10b180-445d-11eb-85dc-218e060d59aa.png">

**Comment by izzycsy** [comment]
Hi @helmhue , i understand, thank you. Please give us time to investigate this.

**Comment by izzycsy** [comment]
Hi @helmhue , are you able to sync with the new update v2.1.4? 
<https://github.com/DeFiCh/app/releases/tag/v2.1.4>

**Comment by helmhue** [comment]
Hi there. Yes, I was able to update to 2.1.4 - I just did it, and it was swift / had no connection issues. Unfortunately it seems I still can't sync on the app. Same issue as before. 
<img width="218" alt="Screen Shot 2020-12-27 at 8 51 24 PM" src="https://user-images.githubusercontent.com/76455062/103184374-e5e87880-4885-11eb-9679-4e56fe3e2b54.png">

**Comment by izzycsy** [comment]
Hi @helmhue , thanks for the screenshot. Could you try reindex option in `Settings` and send me your app log again please? Thank you. 

<img width="993" alt="Settings   Reindex option" src="https://user-images.githubusercontent.com/65014479/103212175-20fdb100-4945-11eb-997e-24d64498634f.png">

**Comment by helmhue** [comment]
Sure thing. I tried that again last night and just now - still the same issue. Here's my app log from this morning. Let me know if you need anything else, and thank you again :)
[AppLog_Dec28.log](https://github.com/DeFiCh/app/files/5747528/AppLog_Dec28.log)

**Comment by izzycsy** [comment]
Hi @helmhue , well received. Thank you for your understanding.

**Comment by helmhue** [comment]
Hey there. 

Just an FYI that I downloaded the newest release of the app (fully deleted the old) and still had / have the same sync issues.

**Comment by izzycsy** [comment]
Hi @helmhue , can I check if it's v2.1.6? You don't have to delete v2.1.5, simply replace the app with the latest version. 

Do give a thumbs up to this comment if your issue has been resolved, otherwise, could you attach screenshots & your logs please? Thank you.

**Comment by helmhue** [comment]
Yes it is / was. Same issues (no synching). Do you want the logs?

**Comment by izzycsy** [comment]
Hi @helmhue , could you send screenshots / screen recordings of what you're facing? Yes, do send your logs. Thank you.

**Comment by izzycsy** [comment]
hi @helmhue , update v2.1.7 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please provide new information (include screenshots) and app logs. Thank you.

**Comment by helmhue** [comment]
Still having issues. Just ran a brand new install on a brand new download from the DeFiChain website. Here's the log from just now. Thanks!
[AppLog_Jan13.log](https://github.com/DeFiCh/app/files/5809822/AppLog_Jan13.log)

**Comment by izzycsy** [comment]
Hi @helmhue , may I check what's your memory consumption on DeFi app in the Activity Monitor? 

<img width="733" alt="Activity Monitor" src="https://user-images.githubusercontent.com/65014479/104481406-b913bf80-5600-11eb-8e7e-c27e83c420ed.png">

**Comment by helmhue** [comment]
Sure! Similar to yours. attached screenshot.
![Screen Shot 2021-01-13 at 11 40 14 AM](https://user-images.githubusercontent.com/76455062/104481892-4bca4500-5594-11eb-9117-c9fff2097f9c.png)

**Comment by izzycsy** [comment]
Hi @helmhue , thank you. Please give us time to re-investigate this. Thank you! 

Hi @Grega-bot , are you also facing the same issue on v2.1.7 <https://defichain.com/downloads/>?

**Comment by izzycsy** [comment]
HI @helmhue @Grega-bot , update v2.1.10 is out <https://defichain.com/downloads/>. If your issue persist, please send new information (include screenshots) and app logs. Thank you.

**Comment by izzycsy** [comment]
Hi @helmhue , could you send resend your logs please — include binary & config? We need it to further investigate. Thank you. 

@Grega-bot , yours is all good, the team is investigating. Thank you for your patience. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/105311250-59b54100-5bf8-11eb-8749-38861ec5cb51.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/105311649-70f42e80-5bf8-11eb-9201-d0374c0b0331.png">

**Comment by izzycsy** [comment]
Hi @helmhue @Grega-bot , update v2.1.11 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.

**Comment by Babwenbiber** [comment]
I have the very same problem on Ubuntu 20.04, App Version 2.1.15.
Stuck at 0%.
I tried to set Reindex after saving to True, but when I click it, it reconnects to peer, but when I navigate to settings again, the option is not selected.
Here my complete app log.
[app.log](https://github.com/DeFiCh/app/files/5933945/app.log)

**Comment by yungmann** [comment]
Guys i found it, you just have to open the CLI, and manually add nodes for the blockchain to sync to them
just run these commands:

addnode 45.157.177.82:8555 add
addnode 24.134.79.25:8555 add
addnode 77.56.65.5:855 add
addnode 85.214.55.116:855 add

do not worry about the answer "null", if you type them twice it should answer "node already added"

then type getconnectioncount to see to how many nodes you are connected

here is a list of some public nodes you can connect to
http://cmk.mydeficha.in/mydefichain/check_mk/dashboard.py?name=dfi_fullnodes_public
