### ISSUE TITLE
DeFiCh / app, Insufficient funds

### ISSUE THREAD

**Issue by Franks-dotcom** [DeFiCh/app#157]
Hi,
swapping and adding liquidity does not work.
I get the message "Insufficient funds".
What to do? Please mention : I have no idea how to remove private information of log files
Thanks,
Frank

![Wallets 2020-12-22 um 06 51 30](https://user-images.githubusercontent.com/76466487/102855585-32b2f600-4425-11eb-82bc-2a552e1a529c.png)

![Dex_swapping 2020-12-22 um 06 51 38](https://user-images.githubusercontent.com/76466487/102855583-32b2f600-4425-11eb-9d26-69ad85254822.png)

![Dex_Insufficient funds 2020-12-22 um 06 51 59](https://user-images.githubusercontent.com/76466487/102855582-321a5f80-4425-11eb-8258-514113dd1b86.png)

**Comment by izzycsy** [comment]
Hi @Tobias-hub , thanks for your feedback. Please refer to screenshot on how to save app logs and attach them in your next comment. The team is currently investigating this issue, thank you for your understanding. 

<img width="327" alt="app log" src="https://user-images.githubusercontent.com/65014479/102858058-927cc180-4464-11eb-8812-8ffefc5afad4.png">

**Comment by Franks-dotcom** [comment]
[app_log.log](https://github.com/DeFiCh/app/files/5729117/app_log.log)

**Comment by izzycsy** [comment]
Hi @Franks-dotcom , thank you. Please give us time to investigate this issue.

**Comment by izzycsy** [comment]
Hi @Franks-dotcom , update v2.1.6 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue w new information (include screenshots) and your app logs. Thank you.
