### ISSUE TITLE
Transaction lost

### ISSUE THREAD

**Issue by hielscher92** [DeFiCh/app#158]
Hello friends

I sent a large amount of dfi to cake yesterday on my app. The transaction was displayed by the app al complete. No dfi arrived on cake. According to explorer there was no transaction and the coins are still on my address. But the balance is 0. I sent 4 dfi to this address as a test and withdrew again. It worked without any problems. Reindex, uninstall did not work. With the command send to address I could not send the coins to a new address either. Can you help me I am very worried.

**Comment by izzycsy** [comment]
Hi @hielscher92 , thanks for your feedback. Please refer to screenshot on how to save app logs and attach it in your next comment. 

<img width="327" alt="app log" src="https://user-images.githubusercontent.com/65014479/102865206-6bc48800-4470-11eb-9757-08985db35d29.png">

May I know what's the transaction ID & your address?

**Comment by hielscher92** [comment]
Yes I will do in the evening after work.
Thanks for helping👍

**Comment by hielscher92** [comment]
Adress from my app I should send you here? Tid I was not save and under transactions in app is nothing

**Comment by hielscher92** [comment]
dWZ5uFLNifNzRyNWHANhP6RFsei7Lj6UN4 my address from app. The coins still on this address

**Comment by hielscher92** [comment]
Here the logs

[logs 22.12.2020.log](https://github.com/DeFiCh/app/files/5731511/logs.22.12.2020.log)

**Comment by guiphil** [comment]
Can you type the following commands and post the results?

`getaccount dWZ5uFLNifNzRyNWHANhP6RFsei7Lj6UN4`
`getaddressinfo dWZ5uFLNifNzRyNWHANhP6RFsei7Lj6UN4`

**Comment by hielscher92** [comment]
![IMG_20201222_200801](https://user-images.githubusercontent.com/28611377/102924241-79d6d080-4491-11eb-8e46-f674bf4075f3.jpg)
![Uploading IMG_20201222_200749.jpg…]()

**Comment by hielscher92** [comment]
![Uploading IMG_20201222_200749.jpg…]()

**Comment by hielscher92** [comment]
![IMG_20201222_200749](https://user-images.githubusercontent.com/28611377/102924330-9ecb4380-4491-11eb-8bb7-c9753a82e3e0.jpg)

**Comment by guiphil** [comment]
I'm not a dev, just trying to help. 

Can you type this als post the result?
`listaccounts {} true true true`

**Comment by hielscher92** [comment]
Then I get only ()

**Comment by guiphil** [comment]
You said that you tried to send the funds manually afterwards but that didn't work, what command did you use for that? 
Did you get an error message?

**Comment by hielscher92** [comment]
Send to address xy

Insufficient funds


But when you check explorer I have my coins on this address

**Comment by guiphil** [comment]
What do you get if you type `getbalance` ?

**Comment by hielscher92** [comment]
0

**Comment by izzycsy** [comment]
> dWZ5uFLNifNzRyNWHANhP6RFsei7Lj6UN4 my address from app. The coins still on this address

Thank you may I have the transaction ID?

**Comment by hielscher92** [comment]
I did not save the transaction ID. And when I check history I can't see this transaction

**Comment by izzycsy** [comment]
Hi @hielscher92 , i see. Please give us time to investigate this issue. Thank you.

**Comment by hielscher92** [comment]
Hi problem is fixed with command clearmempool and restart after this the app
