### ISSUE TITLE
sending DFI from app wallet to CAKE doesn't work

### ISSUE THREAD

**Issue by cnigischer** [DeFiCh/app#159]
Dear DeFiChain team,

when trying to send DFI from my DeFi app wallet to my Cake wallet I get an error message in the app and the transaction is not processed. Could you please advise what I may have done wrong? Thanks & regards, Christopher
[app_log.log](https://github.com/DeFiCh/app/files/5728586/app_log.log)
[binary_log.log](https://github.com/DeFiCh/app/files/5728587/binary_log.log)
[app_config (2).log](https://github.com/DeFiCh/app/files/5728588/app_config.2.log)

**Comment by izzycsy** [comment]
Hi @cnigischer , thanks for your feed, do you have a screenshot of that error? We need to know what kind of error is it as it'll help with the investigation.

**Comment by rglass1** [comment]
I have the same problem
![error_withdrawl](https://user-images.githubusercontent.com/76663929/103178889-37ddce00-4887-11eb-8ee3-b1a5b8474171.PNG)

**Comment by cnigischer** [comment]
for me using the description here works: https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/

**Comment by izzycsy** [comment]
Thanks @cnigischer glad it worked for you. The team is still investigating this issue. 

@rglass1 did the tutorial on Reddit help you temporarily? 
<https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/>

**Comment by izzycsy** [comment]
@rglass1 , this issue may be of help as well: <https://github.com/DeFiCh/app/issues/81>

Please let me know if you manage to follow the tutorial attached in the previous comment.

**Comment by izzycsy** [comment]
Hi @rglass1 , update v2.1.6 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue w new information (include screenshots) and your app logs. Thank you.

**Comment by izzycsy** [comment]
Hi @cnigischer , the team is still investigating on the _unable to send DFI_ issue. I understand that the manual solution could be tedious, but I assure you that the team is trying to fix it. Thank you for your understanding. 

I'll be closing this issue in the mean time. You may reopen this issue if there's new information (include screenshots) and your app logs. Thank you.
