### ISSUE TITLE
Pay-out, pay-in, and swap don't working

### ISSUE THREAD

**Issue by Andyo911** [DeFiCh/app#162]
Hi! Form yesterday I can't pay out or pay in to liquidity pool. And swap don't working. 

I get always the error: Insufficient funds

I try to fix it with this tutorial, but this also not working:
https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/

[app_conifg.conf.log](https://github.com/DeFiCh/app/files/5730388/app_conifg.conf.log)
[binary_log.log](https://github.com/DeFiCh/app/files/5730389/binary_log.log)
[app_log.log](https://github.com/DeFiCh/app/files/5730408/app_log.log)

**Comment by izzycsy** [comment]
Hi @Andyo911 , thank you for the feedback, please give us time to investigate this issue.

**Comment by Andyo911** [comment]
OK Thanks, now I have install the wallet 2.1.4 and there's a new error displayed when I want swap DFI to BTC:

Insufficient UTXOS to perform swap

When I want add liquidity to the BTC/DFI pool, I get this error displayed:

Insufficient UTXOS to perform add liquidity

**Comment by izzycsy** [comment]
Hi @Andyo911 , thanks for your feedback. Please give us time to investigate this issue.

**Comment by izzycsy** [comment]
Hi @Andyo911 , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
