### ISSUE TITLE
Adressleiste -Versenden-

### ISSUE THREAD

**Issue by Bikefire1201** [DeFiCh/app#164]
Ich kann von meiner Defi Wallet nichts versenden (ETH BTC DeFi )   man kann auf der Adressleiste nichts eintragen, und auch die Höhe leiste funktioniert nur mit max.!

**Comment by izzycsy** [comment]
Hi @Bikefire1201 , thanks for your feedback, could you send your **app log** & **binary log** please? 

<img width="286" alt="App log" src="https://user-images.githubusercontent.com/65014479/102974538-aba37200-4539-11eb-9ae5-726394787838.png">

**Comment by izzycsy** [comment]
Hi @Bikefire1201 , v2.1.4 has released, kindly update and see if your issue still persist. 
<https://github.com/DeFiCh/app/releases/tag/v2.1.4> 
If yes, please follow the guide above and send your app logs. Thank you.

**Comment by izzycsy** [comment]
Hi @Bikefire1201 , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
