### ISSUE TITLE
Wallet: only DFI wallet displayed

### ISSUE THREAD

**Issue by ronvalo** [DeFiCh/app#166]
macOS Big Sur Version 11.1

After a restart of the defi-app the BTC Wallet and the liquidity pair Defi-BTC token/wallet were gone. I did an update and a reindex. Only the DFI Wallet is available. Last transaction was a receiveDec 23, 12:36 pm on the DFI wallet.

<img width="1136" alt="Bildschirmfoto 2020-12-23 um 19 42 24" src="https://user-images.githubusercontent.com/76536440/103035771-8f163280-4557-11eb-951c-3147a37bb058.png">
<img width="1136" alt="Bildschirmfoto 2020-12-23 um 19 42 30" src="https://user-images.githubusercontent.com/76536440/103035792-9ccbb800-4557-11eb-914a-c57a12fe31bb.png">

[app_log.log](https://github.com/DeFiCh/app/files/5737069/app_log.log)

- I can't send the binary_log because of size: 142.4 MB
- I can't send the app_config.conf because this file type is not supported

**Comment by izzycsy** [comment]
Hi @ronvalo , thanks for your feedback, you can actually `.zip` the files into one and you'll be able to send it. Please give us time to investigate this issue.

**Comment by ronvalo** [comment]
Thank you for your reply. Here are the zip files: 

[app_config.conf.zip](https://github.com/DeFiCh/app/files/5738877/app_config.conf.zip)

- the binary_log.zib is still too big (40MB)

**Comment by ronvalo** [comment]
[Uploading binary_log_1.rtf.zip…]()
[binary_log_2.rtf.zip](https://github.com/DeFiCh/app/files/5739051/binary_log_2.rtf.zip)
[Uploading binary_log_3.rtf.zip…]()
[binary_log_4.rtf.zip](https://github.com/DeFiCh/app/files/5739054/binary_log_4.rtf.zip)

**Comment by izzycsy** [comment]
@ronvalo Well received, thank you. Please give us time to investigate this.

**Comment by ronvalo** [comment]
Hi there. Here a little update:
- I sent 1.9 DFI from Bittrex to my original DFI Wallet adress: this worked fine
- I swapped DFI agains BTC: this worked fine
- I added liquidity to BTC-DFI: this worked fine
![Bildschirmfoto 2020-12-25 um 15 07 34](https://user-images.githubusercontent.com/76536440/103138537-1fbd5180-46c3-11eb-8364-544266f89272.png)

So what is missing is my original BTC-DFI Wallet where I put 6041.41 DFI and 0.22 BTC in the liquidity pool before I got the problems

[app_log_2.log](https://github.com/DeFiCh/app/files/5742197/app_log_2.log)

**Comment by izzycsy** [comment]
Hi @ronvalo , well received. Thanks for the update & app log. Please give us time to investigate this.

**Comment by ronvalo** [comment]
Hi @izzycsy 
Happy New Year to you!
I know you have a lot to do and there were also the holidays. I was just wondering if you have an estimate how long it will take to fix the problem? The thing is I have invested a lot of money in this project and I am a bit worried about the money being lost. Can you give me an update if the problem can be solved and my money is save? Thank you!

**Comment by izzycsy** [comment]
Hi @ronvalo , happy new year to you too. Apologies for the wait, I'm unable to provide a duration for you but I can assure that the team is investigating this. Thank you for your patience.

**Comment by izzycsy** [comment]
Hi @ronvalo , could you key the following in the CLI and let me know the output: 
`listaccounts {} true true true`

**Comment by ronvalo** [comment]
Hi @izzycsy 

listaccounts {} true true true
[
  {
    "key": "a91436d0c7a9aae9d337f07fb8fb152bb5b5083e744087@0",
    "owner": {
      "asm": "OP_HASH160 36d0c7a9aae9d337f07fb8fb152bb5b5083e7440 OP_EQUAL",
      "hex": "a91436d0c7a9aae9d337f07fb8fb152bb5b5083e744087",
      "reqSigs": 1,
      "type": "scripthash",
      "addresses": [
        "dJR8DR7ZvAUCdBE72hT2QJE6Dz72EaQnSH"
      ]
    },
    "amount": {
      "0": 0.00372545
    }
  },
  {
    "key": "a91436d0c7a9aae9d337f07fb8fb152bb5b5083e744087@5",
    "owner": {
      "asm": "OP_HASH160 36d0c7a9aae9d337f07fb8fb152bb5b5083e7440 OP_EQUAL",
      "hex": "a91436d0c7a9aae9d337f07fb8fb152bb5b5083e744087",
      "reqSigs": 1,
      "type": "scripthash",
      "addresses": [
        "dJR8DR7ZvAUCdBE72hT2QJE6Dz72EaQnSH"
      ]
    },
    "amount": {
      "5": 0.00015439
    }
  }
]

**Comment by ronvalo** [comment]
3872293771a810ba91c17421985e1b1545f8af7881b7d3d4fa31fc6041e810f3

> Hi @ronvalo , happy new year to you too. Apologies for the wait, I'm unable to provide a duration for you but I can assure that the team is investigating this. Do you by any chance have the transaction id for the BTC-DFI swaps? You can check if your transaction exist on Explorer https://mainnet.defichain.io/#/DFI/mainnet/home. Thank you for your patience.

do you mean this number?
<img width="1188" alt="Bildschirmfoto 2021-01-06 um 11 43 56" src="https://user-images.githubusercontent.com/76536440/103770002-cd5e2800-5014-11eb-9272-b80c67a8fc7d.png">

yes it exists. I just can't interpret it. If you like I can send you the number!

**Comment by SiriusVortex** [comment]
@ronvalo i have the same problem... after the wallet update my USDT liquidity pool and my USDT are gone :/

**Comment by SiriusVortex** [comment]
@ronvalo i found the solution. Go to your Wallet, then Settings and activate "ReIndex Option"....then restart your Wallet and it should be fine :)

**Comment by ronvalo** [comment]
> @ronvalo i found the solution. Open your Wallet, then go to Settings and activate "ReIndex Option"....then restart your Wallet and it should be fine :)

Hi @SiriusVortex 
I did this already before opening the issue. It's not working here. But thanks anyway!

**Comment by ronvalo** [comment]
Hi @izzycsy 
Can you please give me an update? it's been 15 days now since you put the fixing label on. Also should I update or wait until the issues are fixed?
thank you and best wishes!

**Comment by izzycsy** [comment]
Hi @ronvalo , the current update would be the release of v2.1.6 <https://defichain.com/downloads/>.

We're still investigating your issue however, can you try Refresh UTXOs? 

<img width="777" alt="Settings   Refresh utxos" src="https://user-images.githubusercontent.com/65014479/104303685-5b4e7d00-5505-11eb-9fe9-117aebeb6c72.png">

**Comment by ronvalo** [comment]
Hi @izzycsy 
Sure I understand that there are many bugs to fix. I just wanted to be assured that you got my output of the listaccounts as asked and the answer to the question of the BTC-DFI Swaps and I haven't got a reply from you. A short confirmation always helps.

I updated to v2.1.6 and did a UTXOs refresh as well as ReIndex. Result is all transactions before Dec. 21st are gone.
Please let me know if you need more information.
Beste wishes 
Ron

**Comment by izzycsy** [comment]
Hi @ronvalo thanks for your understanding. Could you send your logs please? Thank you.

**Comment by ronvalo** [comment]
Hi @izzycsy 

Here are the logs: 
[App_logs_1201.log](https://github.com/DeFiCh/app/files/5804920/App_logs_1201.log)
[app_config_1201.conf.zip](https://github.com/DeFiCh/app/files/5804926/app_config_1201.conf.zip)

the binary log is 167.5 MB. Even when I zip it, it is too big to upload. I tried to separate the log in different .txt files but my text edit program crashes every time when I try to divide it. Do you need the binary logs?

**Comment by izzycsy** [comment]
Hi @ronvalo , thank you, please give us time to investigate.

**Comment by izzycsy** [comment]
Hi @ronvalo @SiriusVortex , update v2.1.7 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please provide new information (include screenshots) and app logs. Thank you.

**Comment by ronvalo** [comment]
hi @izzycsy 

I did an update to v2.1.7. and and Reindex and a UTXOs refresh. Unfortunately the missing funds are still not there and the old transactions before December 21. as well.

There should be at least:
6029.15385751 DFI and
0.22306484 BTC

<img width="1638" alt="Bildschirmfoto 2021-01-13 um 19 13 15" src="https://user-images.githubusercontent.com/76536440/104506809-683aa180-55d5-11eb-83c3-96e9b0ce7a23.png">
<img width="1638" alt="Bildschirmfoto 2021-01-13 um 19 13 25" src="https://user-images.githubusercontent.com/76536440/104506840-71c40980-55d5-11eb-99b4-5f96d95e4e86.png">

[Config_log_01132021.conf.zip](https://github.com/DeFiCh/app/files/5810931/Config_log_01132021.conf.zip)
[app_log_01132021.log](https://github.com/DeFiCh/app/files/5810932/app_log_01132021.log)

**Comment by izzycsy** [comment]
Hi @ronvalo , thanks for your feedback and logs. Using the CLI could you send me the output for these commands please: 

`getbalance` — utxo DFI
`gettokenbalances` — DFI
`listaccounts {} true true true` — breakdown of your coin(s) / token(s)

**Comment by ronvalo** [comment]
Hi @izzycsy 

defi-app_v2.1.7

getbalance
2.206737
gettokenbalances
[
  "0.00562737@0",
  "0.00015439@5"
]
listaccounts {} true true true
[
  {
    "key": "a91436d0c7a9aae9d337f07fb8fb152bb5b5083e744087@0",
    "owner": {
      "asm": "OP_HASH160 36d0c7a9aae9d337f07fb8fb152bb5b5083e7440 OP_EQUAL",
      "hex": "a91436d0c7a9aae9d337f07fb8fb152bb5b5083e744087",
      "reqSigs": 1,
      "type": "scripthash",
      "addresses": [
        "dJR8DR7ZvAUCdBE72hT2QJE6Dz72EaQnSH"
      ]
    },
    "amount": {
      "0": 0.00562737
    }
  },
  {
    "key": "a91436d0c7a9aae9d337f07fb8fb152bb5b5083e744087@5",
    "owner": {
      "asm": "OP_HASH160 36d0c7a9aae9d337f07fb8fb152bb5b5083e7440 OP_EQUAL",
      "hex": "a91436d0c7a9aae9d337f07fb8fb152bb5b5083e744087",
      "reqSigs": 1,
      "type": "scripthash",
      "addresses": [
        "dJR8DR7ZvAUCdBE72hT2QJE6Dz72EaQnSH"
      ]
    },
    "amount": {
      "5": 0.00015439
    }
  }
]

**Comment by izzycsy** [comment]
Hi @ronvalo , thanks for checking. Do you have the transaction id (highlighted in blue) in the screenshot posted above? Please give us time to investigate this issue, thank you.

**Comment by ronvalo** [comment]
Hi @izzycsy 

I send you all the transaction id I have from my Bittrex account from where I sent the DFI to my wallet:

TxId	045ce1fdf03b237d2624dfd52341e479965dd73f0354e5dcb128816ff15ef163
Address	dRcEdQTNgTbs7NWqKHvCgUnCvFZLE5dKr1
Date	2020/12/21 14:23:02
Symbol	DFI
Quantity	212.85595324

TxId	1925b32d22ebe4ff5b0761c91e7e8e5e44146cc6183f0c3c435d0d12c50adfb7
Address	dRcEdQTNgTbs7NWqKHvCgUnCvFZLE5dKr1
Date	2020/12/22 07:00:57
Symbol	DFI
Quantity	6,174.86986964

TxId	43e0d65f06f99601da908fb748f31460a4fb2b28bebaab4ecd6c50eb12eff82acopy
Address	dRcEdQTNgTbs7NWqKHvCgUnCvFZLE5dKr1
Date	2020/12/22 18:06:31
Symbol	DFI
Quantity	3,032.95179715

TxId	2a551332d9abb1b34ae9fe2fd23d63d6aca7d8cfa209ef5f6fa0f126f8f13206copy
Address	dRcEdQTNgTbs7NWqKHvCgUnCvFZLE5dKr1
Date	2020/12/22 18:16:01
Symbol	DFI
Quantity	3,011.00070150

TxId	9ac6b1da79f6a8d016fbd7f7bbc71a073af0131aad5e65fe4308050561248c5ccopy
Address	dRcEdQTNgTbs7NWqKHvCgUnCvFZLE5dKr1
Date	2020/12/25 14:29:37
Symbol	DFI
Quantity	1.90000000

**Comment by ronvalo** [comment]
Hi @izzycsy 

Do you need any further information as there is still the label enquiring on?
Thank you and a good week to you!

**Comment by izzycsy** [comment]
Hi @ronvalo , not at the moment, please give us time to investigate this. Thank you!

**Comment by ronvalo** [comment]
Hi @izzycsy 
There is still the label enquiring on although you don't need any further information and no one is assigned to this issue. I am wondering if someone is working on this? And please don't tell me you need time to investigate this. It's been more than 30 days without any results. What is actually the problem? Thank you!

**Comment by izzycsy** [comment]
Hi @ronvalo , thank you for your patience. You’re right, this case was brought up during Christmas period and there was a slow down. We need to trace all your transaction history to see where the money went, and this takes time, but would appreciate your patience on this.

**Comment by uzyn** [comment]
@ronvalo Took at look at the supposed address: `dRcEdQTNgTbs7NWqKHvCgUnCvFZLE5dKr1`. It now has 1.9 DFI, the transactions can be clearly tracked on explorer: https://explorer.defichain.io/#/DFI/mainnet/address/dRcEdQTNgTbs7NWqKHvCgUnCvFZLE5dKr1

Also on top of that the address does not have any tokens. It's not an upgrade issue, it's not a reindex issue. It does not have any tokens now.

```bash
$ defi-cli getaccount dRcEdQTNgTbs7NWqKHvCgUnCvFZLE5dKr1
[
] # empty
```


Nor does it ever had any tokens ever.

```bash
$ defi-cli listaccounthistory dRcEdQTNgTbs7NWqKHvCgUnCvFZLE5dKr1 '{"depth":999999}'
[
]
```

I believe this case is closed. Firstly we can't track lost funds or lost keys. This issue is only for bug reports.

**Comment by monstrobishi** [comment]
Can you please try `getaddressinfo dRcEdQTNgTbs7NWqKHvCgUnCvFZLE5dKr1 `

**Comment by monstrobishi** [comment]
Can you check this address please `8FTtrzQQbSQ7pw1LAPpNebYFmLqSXFgMFA`, this seems to have some of your funds

**Comment by uzyn** [comment]
```bash
$ defi-cli getaccount 8FTtrzQQbSQ7pw1LAPpNebYFmLqSXFgMFA
[
  "2194.04766738@DFI",
  "0.00039857@BTC",
  "36.67355847@BTC-DFI"
]
```

Check if `8FTtrzQQbSQ7pw1LAPpNebYFmLqSXFgMFA` is in your wallet by typing `getaddressinfo 8FTtrzQQbSQ7pw1LAPpNebYFmLqSXFgMFA`. If it's not, try to recover from one of your backup wallet keys.

**Comment by ronvalo** [comment]
getaddressinfo dRcEdQTNgTbs7NWqKHvCgUnCvFZLE5dKr1
{
  "address": "dRcEdQTNgTbs7NWqKHvCgUnCvFZLE5dKr1",
  "scriptPubKey": "a91485b396fd26338ca07fe0ecd83a13c567e22a5c3487",
  "ismine": true,
  "solvable": true,
  "desc": "sh(wpkh([5be40ce9/0'/0'/0']0299700f1bf8f87ca991306407c675396a406ae79d16cc90013ab3dd1b2a132fac))#ellwwn04",
  "iswatchonly": false,
  "isscript": true,
  "iswitness": false,
  "script": "witness_v0_keyhash",
  "hex": "0014bd0a56c5594bcff3ae9dc063b2ab28d9a59b3c76",
  "pubkey": "0299700f1bf8f87ca991306407c675396a406ae79d16cc90013ab3dd1b2a132fac",
  "embedded": {
    "isscript": false,
    "iswitness": true,
    "witness_version": 0,
    "witness_program": "bd0a56c5594bcff3ae9dc063b2ab28d9a59b3c76",
    "pubkey": "0299700f1bf8f87ca991306407c675396a406ae79d16cc90013ab3dd1b2a132fac",
    "address": "df1qh599d32ef08l8t5acp3m92egmxjek0rkl36ls7",
    "scriptPubKey": "0014bd0a56c5594bcff3ae9dc063b2ab28d9a59b3c76"
  },
  "ischange": true,
  "timestamp": 1608797075,
  "hdkeypath": "m/0'/0'/0'",
  "hdseedid": "06fd81ef28d1a4bcb8042a7918846e593be77fd8",
  "hdmasterfingerprint": "5be40ce9",
  "labels": []
}

**Comment by ronvalo** [comment]
getaddressinfo 8FTtrzQQbSQ7pw1LAPpNebYFmLqSXFgMFA
{
  "address": "8FTtrzQQbSQ7pw1LAPpNebYFmLqSXFgMFA",
  "scriptPubKey": "76a914042aefb2acb1503cfdcfa376bcd046746086806588ac",
  "ismine": false,
  "solvable": false,
  "iswatchonly": false,
  "isscript": false,
  "iswitness": false,
  "ischange": false,
  "labels": []

**Comment by ronvalo** [comment]
> ```shell
> ```shell
> $ defi-cli getaccount 8FTtrzQQbSQ7pw1LAPpNebYFmLqSXFgMFA
> [
>   "2194.04766738@DFI",
>   "0.00039857@BTC",
>   "36.67355847@BTC-DFI"
> ]
> ```
> 
> 
> Check if 8FTtrzQQbSQ7pw1LAPpNebYFmLqSXFgMFA is in your wallet by typing getaddressinfo 8FTtrzQQbSQ7pw1LAPpNebYFmLqSXFgMFA. If it's not, try to recover from one of your backup wallet keys.
> ```

What I am supposed to do? Import Wallet and then the backup.txt?

**Comment by ronvalo** [comment]
Hi @uzyn 
How do I recover from my backup wallet keys. I have a backup.txt file and I have the mnemonic seed.
Thank you!

**Comment by izzycsy** [comment]
Hi @ronvalo , you may be able to recover your wallet by finding the backup wallet.dat in the wallets folder. On Mac it is located here: 
 
Mac — Go to Folder: 
` /Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat`
 
<img width="650" alt="201221 Rename wallet dat file" src="https://user-images.githubusercontent.com/65014479/105953961-0129ec00-60af-11eb-9fa6-d7f3c7c9d65e.png">


You may see several wallet.dat files named `wallet-bak-1234567890123.dat` — do not delete any of these, make a copy and move them to a safe location.   You may now do the following:   

1. Backup `wallet.dat`  file
2. Remove it from `DeFi/wallets` folder
3.  With the remaining _wallet.dat-bak-XXX_ , **rename** one of the files to `wallet.dat` 
 (in my case I’ll rename __7015196.dat__ to __wallet.dat__) 
 
Launch app and see if your balances are reflected. 

I'll be closing this issue. Should you face a bug-related issue, you may reopen this thread. Thank you.

**Comment by ronvalo** [comment]
Hi @izzycsy, @uzyn 

Please don't close the issue as it is still a bug. I didn't loose the keys and I didn't loose the funds. The transactions which were visible once on the wallet (as seen on the screenshot https://github.com/DeFiCh/app/issues/166#issuecomment-759752433) are not visible after the updates

- how is it possible that the transactions shown on the blockchain (https://explorer.defichain.io/#/DFI/mainnet/address/dRcEdQTNgTbs7NWqKHvCgUnCvFZLE5dKr1) are not visible anymore on the wallet? How can I retrieve it. I still have the original seed phrase
- why were the liquidity token suddenly not in my wallet anymore without my doing? This happened as you were doing some updates before christmas
- the transactions shown here (https://explorer.defichain.io/#/DFI/mainnet/address/dRcEdQTNgTbs7NWqKHvCgUnCvFZLE5dKr1) should show the DFI and BTC went to the liquidity pool. Is that correct? So why can't they be retrieved?

There is no DeFi folder on my Mac altough I have it installed:
<img width="814" alt="Bildschirmfoto 2021-01-27 um 07 10 21" src="https://user-images.githubusercontent.com/76536440/105962931-eb490680-606f-11eb-9ee7-8515b51161c4.png">

Please help me out there as I trusted you with my money. I did everything exactly as your chairman Julian described in his youtube videos and suddendly my investments are gone. How can this be?

I beg you to take your responsibility as a company and help me out to retrieve my investments!
Thank you and kind regards
Ron

**Comment by monstrobishi** [comment]
Hi @ronvalo,

That is the library in your Root drive, you must find the one under your username as Bella said:

/Users/<username>/Library/Application Support/DeFi

There are multiple Library folders on MacOS

**Comment by monstrobishi** [comment]
Hi @ronvalo ,

Some further investigation, the account that holds your funds `8FTtrzQQbSQ7pw1LAPpNebYFmLqSXFgMFA`  was last accessed on Dec 23, 2020, 9:36:33 PM, the funds are still sitting on there. Do you recall re-installing or resetting the wallet around that time? Maybe reloading seed phrase?

See if you can find older wallet.dat files as Bella suggested, one of those may hold the key to that address. The app always backups app wallet files before it resets the wallet so it's unlikely they are lost but we cannot make any promises.

**Comment by ronvalo** [comment]
> Hi @ronvalo,
> 
> That is the library in your Root drive, you must find the one under your username as Bella said:
> 
> /Users/(username)/Library/Application Support/DeFi
> 
> There are multiple Library folders on MacOS
> 
> Important: Don't delete anything

Hi @monstrobishi 
Thank you! I did, but I couldn't find a Library under my user name (Benutzer=User)
<img width="869" alt="Bildschirmfoto 2021-01-27 um 07 55 10" src="https://user-images.githubusercontent.com/76536440/105967257-2b5eb800-6075-11eb-8c7a-7d7ac048af7d.png">

**Comment by monstrobishi** [comment]
Library is hidden under user folder see this: [https://www.ionos.com/digitalguide/server/configuration/showing-hidden-files-on-a-mac/#:~:text=Open%20Macintosh%20HD%20or%20the,using%20the%20same%20keyboard%20shortcut.](url)

**Comment by ronvalo** [comment]
@monstrobishi 

You are my hero!!!! thank you so much!!!! 😊 

<img width="1414" alt="Bildschirmfoto 2021-01-27 um 08 19 12" src="https://user-images.githubusercontent.com/76536440/105970108-86de7500-6078-11eb-90b1-dbb4df68db38.png">

So what do I do next? Do I do a new Backup? Do I leave the wallet.dat as it is?

I am so grateful for your help!

**Comment by monstrobishi** [comment]
Sure I suggest you do another backup and also copy paste the wallet.dat somewhere secure. Keep in mind this address may not be saved by your seedphrase so do not rely on that instead rely on the wallet backup and wallet.dat.
