### ISSUE TITLE
Update while synchronizing the blockchain

### ISSUE THREAD

**Issue by willidh** [DeFiCh/app#168]
Heyho,
I clicked the update button and only later realized that the blockchain was being synchronized. After the update was finished, there was a synchronization error and the blockchain now has to be completely reloaded.

Proposed solution: Disable the Update Button while the blockchain is synchronizing?

Best regards

**Comment by izzycsy** [comment]
Hi @willidh , thanks for your feedback. If I understood your issue correctly — block synchronization is stuck (?), then you could possibly try the reindex option in `Settings`. If issue still persist, kindly send your app logs. We need more details in order investigate how to reproduce this issue.

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/103149389-e4df1a80-47a3-11eb-9bba-4bf729aa8f7a.png">
<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/103149391-e872a180-47a3-11eb-9416-7475ff8d412b.png">

**Comment by izzycsy** [comment]
Hi @willidh , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
