### ISSUE TITLE
Add LP: JSON value is not a string as expected

### ISSUE THREAD

**Issue by lennarthellmann** [DeFiCh/app#169]
Defi Wallet and App works mostly. Transferring Coins to the Liquidity Mining is not possible however. I get the fail message "JSON value is not a string as expected".

**Comment by izzycsy** [comment]
Hi @lennarthellmann , thanks for your feedback. May I know the OS + version no. you're using? Could you describe your user flow more (screenshots / screen recordings is encouraged). Also, could you send your app logs? We need more details in order investigate how to reproduce this issue.

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/103149340-7ef29300-47a3-11eb-962d-892156d8d8e0.png">
<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/103149344-82861a00-47a3-11eb-8396-0379e510d3ba.png">
<img width="671" alt="3 Drag and drop" src="https://user-images.githubusercontent.com/65014479/103149348-844fdd80-47a3-11eb-9a41-46ed0c4eeb34.png">

**Comment by lennarthellmann** [comment]
@izzycsy thanks for your reply. When I created the wallet I had OS 2.13 and then I updated to OS 2.14.
So far have found two Problems. 

1. JSON value is not a string as expected / Message when I try to add DFI/BTC to Liquidity Pool
2. It is not possible to transfer btc/defi token to be able to transfer. When I try to follow the tutorial on reddit (https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin) I cannot follow through because Step 2 is not possible. Owner is not displayed (I will a d picture)

Because of those Problems I cannot use the app basically but even worse I cannot send my coins to another platform. Im basically stuck ...

[DFI_Logs.zip](https://github.com/DeFiCh/app/files/5743049/DFI_Logs.zip)

**Comment by lennarthellmann** [comment]
![image](https://user-images.githubusercontent.com/62066027/103151081-198aac00-477b-11eb-8372-a836cebe7a30.png)

**Comment by izzycsy** [comment]
Hi @lennarthellmann , thanks for the app log & screenshot. Please give us time to investigate this.

**Comment by luckythai** [comment]
Have the same problem.
1.2 Dfi coin on getbalance
i cannot execute liquidity and no reseive address is displayed.


[app.zip](https://github.com/DeFiCh/app/files/5780396/app.zip)

**Comment by luckythai** [comment]
binary.log 3. 7zip files 
renamed to binary-log.7z.001
[binary-log.7z.001.zip](https://github.com/DeFiCh/app/files/5780465/binary-log.7z.001.zip)

**Comment by luckythai** [comment]
binary.log 3. 7zip files 
renamed to binary-log.7z.002

[binary-log.7z.002.zip](https://github.com/DeFiCh/app/files/5780472/binary-log.7z.002.zip)

**Comment by luckythai** [comment]
binary.log 3. 7zip files 
renamed to binary-log.7z.003

[binary-log.7z.003.zip](https://github.com/DeFiCh/app/files/5780474/binary-log.7z.003.zip)

**Comment by luckythai** [comment]
App restarted and sync.
execution of the page Step-by-Step: Changing DFI-Token to DFI-Coin done
0.01 dfi converted into a coin and 2.0 dfi converted into a coin.

start the Liquidity pool again and after confirmation the same error. JSON value is not a string as expected

Swap on the dex is not a problem.  only start the Liquidity pool.

ubuntu 18.04 on windows10 - ubunto 23gb swapfile - Windows10 16 gb swapfile 4gbRam


I am sending new logs.


[app.log](https://github.com/DeFiCh/app/files/5781202/app.log)

[App-config.conf.log](https://github.com/DeFiCh/app/files/5781214/App-config.conf.log)

**Comment by luckythai** [comment]
solved!
New address generated on the DFI token in the app.
I Add Liquidity and it worked immediately. No more the error ->    JSON value is not a string as expected.

On windows10 I increased the swapfile to 32GB. Ubuntu 18.04. on windows10 swapfile ubuntu 23GB.

The problem was the missing address generated.
sorry a user error

**Comment by izzycsy** [comment]
Hi @lennarthellmann @luckythai , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
