### ISSUE TITLE
Btc are not shwoing up in my wallet

### ISSUE THREAD

**Issue by 1942dirk** [DeFiCh/app#170]
Hallo

I made yesterday a transaction to pull out some btc/dfi out of the LM Pool.
The dfi showed up 2 minutes later in my dfi wallet.
The btc is still 15 hours later nit showing up in my btc wallet.

Could you help me to get my btc ?

My operating system is windows 10.
![Screenshot 2020-12-25 085211](https://user-images.githubusercontent.com/76582359/103127537-78282b00-4692-11eb-9ee1-29873e0b7010.png)

**Comment by izzycsy** [comment]
Hi @1942dirk , thanks for your feedback. Could you send your app logs please? 
<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/103149283-0b508600-47a3-11eb-9531-de0a28e88f27.png">
<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/103149286-0e4b7680-47a3-11eb-8b94-3718d7f7ca1b.png">
<img width="671" alt="3 Drag and drop" src="https://user-images.githubusercontent.com/65014479/103149290-13102a80-47a3-11eb-864f-bb4e158aeef7.png">

**Comment by izzycsy** [comment]
Hi @1942dirk , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
