### ISSUE TITLE
Es hat nichts gebracht, Coins auf die Adresse zu schicken um ihren Besitz zu beweisen.

### ISSUE THREAD

**Issue by dancingking83** [DeFiCh/app#171]
Hallo und Frohe Weihnachten,

MacBook Air MacOs High Sierra 10.13.6

ich habe mehrmals versucht Liquidät zum Pool hinzzufügen mit BTC/DFI. Jedesmal wenn ich ,,Supply" drücke, erscheint entweder

Can't find any UTXO's for owner. Are you an owner? If so, send some coins to address 8KjbjVrQP53irG4hozhJSWooBN2L8U2Mej and try again!(BTW: Das ist keine von den 2 Adressen, die ich mir generiert habe.)

oder

Can't find any UTXO's for owner. Are you an owner? If so, send some coins to address 
dQ4SmjVo7RM9rmnX3DxzdPomrhsZgofB42 and try again!(Eine meiner Adressen)

Ich habe 0.5 DFI zu dieser und bei den ganzen Versuchen zu allen drei Adressen geschickt. Es hat sich allerdings nichts verändert. 

Ich konnte außerdem nur 0.5 DFI schicken. Mit 1, 1.5 oder 2 DFI klappte es nicht.

[App Log1.log](https://github.com/DeFiCh/app/files/5741974/App.Log1.log)
[Binary Log1.log](https://github.com/DeFiCh/app/files/5741975/Binary.Log1.log)
![camphoto_1932422408](https://user-images.githubusercontent.com/76588162/103135283-82a8eb80-46b7-11eb-982a-f3c70afb9840.jpg)

Danke schön,

Gruß, Roman

**Comment by izzycsy** [comment]
Hi @dancingking83 , thanks for your feedback, please give us time to investigate this. Did you update to v2.1.4 <https://github.com/DeFiCh/app/releases/tag/v2.1.4>? 

Fröhliche Weihnachten!

**Comment by dancingking83** [comment]
Hello Bella,
yes, it’s up to date.
Roman

Gesendet von Yahoo Mail für iPhone


Am Samstag, Dezember 26, 2020, 10:45 AM schrieb Bella <notifications@github.com>:




Hi @dancingking83 , thanks for your feedback, please give us time to investigate this. Did you update to v2.1.4 https://github.com/DeFiCh/app/releases/tag/v2.1.4?

Fröhliche Weihnachten!

**Comment by izzycsy** [comment]
Hi @dancingking83 , understood. Please give us time to investigate this. Thank you for your understanding.

**Comment by GsonAn** [comment]
Help: no "owner" address is displayed to me. I can not continue to change my token into coins. does anyone have an idea? Thx

**Comment by izzycsy** [comment]
Hi @dancingking83 , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.

**Comment by izzycsy** [comment]
Hi @GsonAn , thanks for your feedback. Your issue seems unrelated to the original author's. Kindly create a new issue, state the OS + version no. you're using. Could you describe your user flow more (screenshots / screen recordings are encouraged). Also, kindly send your app logs. This will provide more insight for the investigation. Thank you.  In the mean time, kindly install the latest version v2.1.6 of the app <https://defichain.com/downloads/>
