### ISSUE TITLE
Linux AppImage 2.1.4: Error "Node is disconnected" during synchronizing

### ISSUE THREAD

**Issue by Okto8on** [DeFiCh/app#173]
When running DeFi App 2.1.4 from Linux AppImage, the app stops synchronizing and shows message "Node is disconnected".
There is no possibility to re-connect the app, and it does not re-connect by itself. The app needs to be closed and re-launched.
After re-starting the app, the synchronizations starts again at 0% and the app disconnects again.
This happens always around 99.7% of completeness of synchronization.

(Screenshots show 5 different occasions. Logs attached/linked)

![Screenshot from 2020-12-25 20-27-00](https://user-images.githubusercontent.com/76601018/103143312-fd075900-4713-11eb-80f0-38c05c4be833.png)
![Screenshot from 2020-12-25 21-28-19](https://user-images.githubusercontent.com/76601018/103143313-0395d080-4714-11eb-9264-20ef2a870ead.png)
![Screenshot from 2020-12-25 22-27-41](https://user-images.githubusercontent.com/76601018/103143314-04c6fd80-4714-11eb-9a00-f3a4607cc250.png)
![Screenshot from 2020-12-25 23-16-27](https://user-images.githubusercontent.com/76601018/103143315-05f82a80-4714-11eb-95f9-efe812d26a1e.png)
![Screenshot from 2020-12-26 00-28-38](https://user-images.githubusercontent.com/76601018/103143316-07295780-4714-11eb-9891-758ea8fce24a.png)

[app_251220202028.log](https://github.com/DeFiCh/app/files/5742507/app_251220202028.log)
[app_251220202119.log](https://github.com/DeFiCh/app/files/5742508/app_251220202119.log)
[app_251220202229.log](https://github.com/DeFiCh/app/files/5742509/app_251220202229.log)
[app_251220202316.log](https://github.com/DeFiCh/app/files/5742510/app_251220202316.log)
[app_261220200028.log](https://github.com/DeFiCh/app/files/5742511/app_261220200028.log)

[https://dgss.ch/download/binary_261220200028.zip](url)

**Comment by izzycsy** [comment]
Hi @Okto8on , did you try reindex option in `Settings`? Thanks for sending your app logs, please give us time to investigate this issue. 

<img width="993" alt="Settings   Reindex option" src="https://user-images.githubusercontent.com/65014479/103148819-a8f58680-479e-11eb-8f7b-dac9e4af1c4f.png">

**Comment by Okto8on** [comment]
Thank you. I will try the ReIndex Option.

Meanwhile here some additional input that might help:
The same behavior, as detailed above for 2.1.4., applies now to the **2.1.3** Linux AppImage. A version that worked well before.

(Tested on a separate user account - Screenshots show 2 different occasions. Logs attached/linked)


![Screenshot from 2020-12-26 03-22-31](https://user-images.githubusercontent.com/76601018/103149597-24d5db80-476b-11eb-8614-43c407bb0a58.png)

![Screenshot from 2020-12-26 10-51-54](https://user-images.githubusercontent.com/76601018/103149605-2d2e1680-476b-11eb-9855-62ba423be0f1.png)


[app261220200150.log](https://github.com/DeFiCh/app/files/5742930/app261220200150.log)
[app261220201055.log](https://github.com/DeFiCh/app/files/5742931/app261220201055.log)

https://dgss.ch/download/binary261220201055.zip

**Comment by Okto8on** [comment]
@izzycsy: Here the results of applying the ReIndex Option.

_Scenario A - ReIndex after interruption of synchronizing and disconnection_
After interruption of synchronizing and disconnection, the Settings are not accessible; the button is inactive.
The only left possibility it to close the app.

![_Screenshot from 2020-12-26 00-28-38](https://user-images.githubusercontent.com/76601018/103151657-645af280-4780-11eb-900c-a6776e1cddbf.png)



_Scenario B - ReIndex after re-launch_
When re-starting the app, and then activate and save the ReIndex Option, the app dis- and re-connects and initiates new synchronization. Once reached about 99,5% it behaves identical as detailed above: it disconnects and stops sync.

![Screenshot from 2020-12-26 13-23-02](https://user-images.githubusercontent.com/76601018/103151748-30cc9800-4781-11eb-8020-01582cf891b8.png)

![_Screenshot from 2020-12-26 13-19-00](https://user-images.githubusercontent.com/76601018/103151751-3924d300-4781-11eb-9ac3-21e760d97b80.png)

**Comment by izzycsy** [comment]
Thanks @Okto8on for the screenshots & explanation, please give us time to investigate this issue.

**Comment by Okto8on** [comment]
The root-cause of the issue was a very high usage of memory during synchronization (process "defi-init"). This led to interruption of the process.
The fix is to increase the memory swap file to at least 8 GB (on Linux Ubuntu).
[Here](https://bogdancornianu.com/change-swap-size-in-ubuntu/) a strait forward instructions on how to do that.

After that, the synchronization will complete.

**Comment by izzycsy** [comment]
Thanks @Okto8on , I'll keep this issue open for now, so Linux users may refer to your solution in the mean time. Thank you!

**Comment by kevarms2** [comment]
Same issue but in windows 10

**Comment by izzycsy** [comment]
@kevarms2 , seen your ticket <https://github.com/DeFiCh/app/issues/212>, and I've renamed it to Windows so that users can refer to it. Thanks for opening the issue.

**Comment by izzycsy** [comment]
Hi @Okto8on 	, update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
