### ISSUE TITLE
Too many decimal places in wallet display cause problems when sending with MAX Button

### ISSUE THREAD

**Issue by bernd-mack** [DeFiCh/app#176]
Hello all,

The decimal places in the wallet display are sometimes very high and lead to an error message "Invalid amount" when trying to send using the "MAX" button. If a number is entered manually there will be no error when sending.

**"Real wallet balance"**
`gettokenbalances
[
  "0.08483598@0",
  "0.00217305@1",
  "0.00060518@3",
  "0.06038489@4",
  "0.00278626@5",
  "1.90774681@6"
]
 `
**Walletbalance in GUI:**
![image](https://user-images.githubusercontent.com/76614620/103154809-819cba80-479a-11eb-962f-b9dbce927920.png)

**Error when trying to send with Button "MAX"**
![image](https://user-images.githubusercontent.com/76614620/103154853-e0faca80-479a-11eb-9ebf-3cc81339e147.png)

**Comment by izzycsy** [comment]
Hi @bernd-mack , thanks for your feedback, could you kindly attach your app logs please? Please give us time to investigate this. Thank you. 
<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/103208633-1db1f780-493c-11eb-805e-26c56c74aeb9.png">
<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/103208638-21457e80-493c-11eb-8c7e-c62413c7a300.png">
<img width="671" alt="3 Drag and drop" src="https://user-images.githubusercontent.com/65014479/103208644-23a7d880-493c-11eb-87f6-58e4cda77377.png">

**Comment by bernd-mack** [comment]
Hi Bella, Useful logs could be a problem. I played too much around to get rid of the problem and swapped on the DEX: ETH -> DFI and DFI -> ETH. And then the additional decimals were gone. But I will try to get them back :)

Testsystem and logs are the same like in https://github.com/DeFiCh/app/issues/177
(https://github.com/DeFiCh/app/files/5747174/app.logs.zip)

**Comment by izzycsy** [comment]
@bernd-mack Thank you, please give us time to investigate this issue.

**Comment by izzycsy** [comment]
Hi @bernd-mack 	, update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
