### ISSUE TITLE
DEX: [MAX] button error

### ISSUE THREAD

**Issue by bernd-mack** [DeFiCh/app#177]
Hello all,

When trying to exchange ETH into DFI on DEX, the maximum number of ETH is selected when pressing the MAX button, but the calculation of the resulting DFI does not take place. Only after manually changing the ETH the DFI window updates and you can perform the swap.

Here is a video recording:

https://user-images.githubusercontent.com/76614620/103155067-8cf0e580-479c-11eb-8c66-acb6373e6f3a.mp4

**Comment by izzycsy** [comment]
Hi @bernd-mack , thanks for your feedback! Could you kindly send your app logs please? Thank you!

**Comment by bernd-mack** [comment]
[app logs.zip](https://github.com/DeFiCh/app/files/5747174/app.logs.zip)

**Comment by izzycsy** [comment]
@bernd-mack Thank you, please give us time to investigate this issue.

**Comment by Woodrow1997** [comment]
I'm having the same issues. My app logs are attached. 
[Woodrow1997_app logs.log](https://github.com/DeFiCh/app/files/5768464/Woodrow1997_app.logs.log)
Thx.

**Comment by izzycsy** [comment]
Hi @bernd-mack @Woodrow1997 , the team is still investigating this. I think someone from the community manage to find a temporary solution: type `1` > click `MAX`, function should work from there.

**Comment by izzycsy** [comment]
Hi @bernd-mack @Woodrow1997 , update v2.1.7 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, this build may not consist of the [MAX] button issue, but rest assured it's pending to be fixed. Thank you for your patience.

**Comment by bernd-mack** [comment]
2.1.12 -> works fine
