### ISSUE TITLE
Pressing "include rewards" in DFI wallet leads to app error

### ISSUE THREAD

**Issue by oh-johnny** [DeFiCh/app#178]
Every time I try to activate the checkbox "include rewards" in my DFI-Wallet the app somehow seems to be overloaded. The task "defid" is working hard in my activity monitor but the wallet won't update anymore (also on other pages like "liquidity" …) and will eventually crash after some minutes after I already closed it. If it doesn't I have to force quit the task "defid" and restart the app.
<img width="1023" alt="screenshot_wallet" src="https://user-images.githubusercontent.com/76650269/103170844-c6caf600-4847-11eb-86da-f12385482336.png">

System: MacBook Pro (2019), MacOSX Version 10.15.7
defi-app: Version 2.1.4
 
[Logfiles.zip](https://github.com/DeFiCh/app/files/5744542/Logfiles.zip)
Logfiles can't be attached without zipping, therefore the help page should be updated.

**Comment by zipidude** [comment]
I have same problem. Now it's just loading Liquidity tab and nothing happens..
MacOSX: 10.15.7
defi-app: 2.1.4

**Comment by izzycsy** [comment]
Hi @oh-johnny , thank you for the feedback, please give us time to investigate this issue. Yes, the help page has been updated. 

@zipidude , thanks for your feedback, could you send your app logs please?

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/103274448-a55f3b00-49fc-11eb-9710-b50ba16b1eea.png">

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/103274442-a1cbb400-49fc-11eb-8b64-83bc04982f09.png">

**Comment by izzycsy** [comment]
Hi @oh-johnny @zipidude , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
