### ISSUE TITLE
App downloads entire blockchain everytime I open it

### ISSUE THREAD

**Issue by LukasGW** [DeFiCh/app#180]
Hi, I have a problem with the DeFi App. When I open the App I get this response:
![Screenshot](https://user-images.githubusercontent.com/71937669/103171933-3ba22e00-4850-11eb-80b4-e6ac8e091964.PNG)

I tried to download the app again but I still get this problem.
I have a Microsoft Surface with windows 10. I had no problems with the version 2.1.3, but since this update something doesn't work. Can you have a look at this?

**Comment by LukasGW** [comment]
I don't exactly know what happened, but everything works now again.

**Comment by izzycsy** [comment]
@LukasGW Thanks for your feedback, I'll close this issue for now that's working for you.
