### ISSUE TITLE
nachdem die app 100 % erreicht hat sehe ich das Wallet nicht mehr 

### ISSUE THREAD

**Issue by sanpau11** [DeFiCh/app#181]
nachdem die app 100 % erreicht hat sehe ich das Wallet nicht mehr 
https://share-your-photo.com/f279a1f47c
[https://share-your-photo.com/f279a1f47c](url)

![grafik](https://user-images.githubusercontent.com/76652739/103172498-3e068700-4854-11eb-9d23-5dfa77213ba4.png)

was kann ich tun

**Comment by sanpau11** [comment]
![grafik](https://user-images.githubusercontent.com/76652739/103172304-d13ebd00-4852-11eb-877c-4c3e81382ddd.png)

**Comment by madmehn** [comment]
That´s also my problem !!! i tryed also to importwallet "filename" with console , syntax importwallet "C:\Users\UserName\finan**\defichain2812txt" .. result is --> null ? please someone from the team can help ?

**Comment by DaBop** [comment]
Bei mir das gleiche. bin auch Ratlos...

**Comment by izzycsy** [comment]
Hi @sanpau11 @Grega-bot @madmehn @DaBop , thanks for your feedback. May i know are all of you on v2.1.4? 
<https://github.com/DeFiCh/app/releases/tag/v2.1.4>

Could you kindly send you app logs please? 
<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/103272562-2cf67b00-49f8-11eb-9108-1c3983110fac.png">

<img width="511" alt="2 Komprimiere" src="https://user-images.githubusercontent.com/65014479/103272567-2ec03e80-49f8-11eb-96fb-77a647e28447.png">

<img width="671" alt="3 Drag and drop" src="https://user-images.githubusercontent.com/65014479/103272572-3253c580-49f8-11eb-92f0-b1d046846583.png">

**Comment by DaBop** [comment]
Yes, Version 2.1.4

[DeFi Logs.zip](https://github.com/DeFiCh/app/files/5751012/DeFi.Logs.zip)

**Comment by madmehn** [comment]
[@madmehn.zip](https://github.com/DeFiCh/app/files/5751822/%40madmehn.zip)

**Comment by izzycsy** [comment]
@DaBop , @madmehn , thank you. Please give us time to investigate the issue.

**Comment by izzycsy** [comment]
@DaBop , could you resend your app logs please, file seems broken. 
<img width="390" alt="Screenshot 2020-12-30 at 3 32 20 AM" src="https://user-images.githubusercontent.com/65014479/103309311-c2712980-4a4f-11eb-8830-195d2e8c5f2d.png">

**Comment by DaBop** [comment]
[DFI Logs.zip](https://github.com/DeFiCh/app/files/5759531/DFI.Logs.zip)

**Comment by blnSilverBack** [comment]
Same problem, have anyone a solution?

**Comment by izzycsy** [comment]
Hi @sanpau11 @Grega-bot @madmehn @DaBop @blnSilverBack , update v2.1.5 is out <https://defichain.com/downloads/>. Please give a thumbs up to this comment if your issue has been resolved, if not, please send your app logs and we'll further investigate.

**Comment by izzycsy** [comment]
Hi @sanpau11 @Grega-bot @madmehn @DaBop @blnSilverBack , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
