### ISSUE TITLE
Sync stoped at 469818

### ISSUE THREAD

**Issue by defialex** [DeFiCh/app#182]
Hi, 

the syncronisation stopped at 469818 blocks. do you know how can I fix it?

here are the logs.

[app_logs.log](https://github.com/DeFiCh/app/files/5744797/app_logs.log)
[binary_logs.log](https://github.com/DeFiCh/app/files/5744798/binary_logs.log)

Thanks for your help

**Comment by izzycsy** [comment]
Hi @defialex , did you try `Reindex option` in **Settings**?

<img width="993" alt="Settings   Reindex option" src="https://user-images.githubusercontent.com/65014479/103275466-2f100800-49ff-11eb-81c2-c75b8d3fb96d.png">

**Comment by izzycsy** [comment]
Hi @defialex , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.

**Comment by defialex** [comment]
It worked. Sorry for not responding for so long!

Thanks for your help.
