### ISSUE TITLE
DFI lost in wallet

### ISSUE THREAD

**Issue by flotzke** [DeFiCh/app#185]
[logs.zip.001.zip](https://github.com/DeFiCh/app/files/5746214/logs.zip.001.zip)
[logs.zip.002.zip](https://github.com/DeFiCh/app/files/5746215/logs.zip.002.zip)
[logs.zip.003.zip](https://github.com/DeFiCh/app/files/5746216/logs.zip.003.zip)
[logs.zip.004.zip](https://github.com/DeFiCh/app/files/5746217/logs.zip.004.zip)

Hello,

i am using version 2.1.3 on Windows.

I recently tried the commands utxostoaccount and accounttoutxos in my wallet.

I had 1,426.0576832 DFI in my wallet showing up with getbalance.

Then i 'utxostoaccount' them in small charges to my wallet address dFHPGk3eiadpUgP6g7dk4oJbc7MfLnW4kc

They were shown as tokens with gettokenbalances  1,426.0576832@0 at this address.
 
Then i wanted to change them back to coins with accounttoutxos.

txid1: 1b0c078908b4818d6a9272618f56379f629990872f531d2707653f6c14d55cf5

txid2: 24e139bfb0ef05267036d0257585a26f9380f4cf2e2f270991e0a84b24d07aea
(this one i got as result, but it seems it has never made it to the blockchain!)

After that, only a balance of 0.000125 (getbalance) and nothing @0 (gettokenbalances) is shown in my wallet.

I then reidexed the app with settings->reindex

Node was restarted and reindexing begun. 

But nothing changed, still the DFIs are not shown in the wallet. (as before reindexing)

Please help me to recover them.
Thank you very much.
Florian

**Comment by izzycsy** [comment]
Hi @flotzke , thanks for your feedback, perhaps this may help 
<https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/?utm_medium=android_app&utm_source=share>.

**Comment by flotzke** [comment]
Hi izzycsy,

yes of course, as i wrote i am familiar with utxostoaccount and accounttoutxos.

Today i had the same issue again!

After performing this action: 

"21:19:08: accounttoutxos: ""dFHPGk3eiadpUgP6g7dk4oJbc7MfLnW4kc"", {""dFHPGk3eiadpUgP6g7dk4oJbc7MfLnW4kc"":""1361.18179431@DFI""} -> {""result"":""64705b41e12605328e9a99420fac75dca90a78935c1e2247134c7289e5460703"",""error"":null,""id"":null}

and seeing the coins in the wallet i did:

 "21:19:39: utxostoaccount: {""dFHPGk3eiadpUgP6g7dk4oJbc7MfLnW4kc"":""1361.17486551@DFI""} -> {""result"":""16d1d197c40504fa61f483b8665fd70c9cca5a83109499a4424a57f618780247"",""error"":null,""id"":null}

AGAIN THIS TXID is NOT VISIBLE IN THE BLOCKCHAIN EXPLORER,
and the DFIs are lost from the wallet.

getbalance: 
4.99944

gettokenbalances:
[
  "0.43309867@0",
  "0.00000007@2",
  "9150.53186172@3",
  "12.00806446@5"
]

Double quotes are only in my logfiles, they were sent as single quotes!

Please help me recover my initial 1,426.0576832 + today's 1361.17486551 DFI.

Thank you very much,
Florian

**Comment by izzycsy** [comment]
Hi @flotzke , thank you for the explanation, I checked on the explorer, it seems like your balance of 1,361.18 DFI is present. 

txid 1: `1b0c078908b4818d6a9272618f56379f629990872f531d2707653f6c14d55cf5`
<img width="970" alt="201228 1,426 DFI" src="https://user-images.githubusercontent.com/65014479/103878670-b6513000-5111-11eb-8a63-40e52efdeb63.png">

txid 2: `24e139bfb0ef05267036d0257585a26f9380f4cf2e2f270991e0a84b24d07aea`
<img width="972" alt="201229 1,426 DFI" src="https://user-images.githubusercontent.com/65014479/103878700-bea96b00-5111-11eb-9ec0-b06e705dcb67.png">

As for address `dFHPGk3eiadpUgP6g7dk4oJbc7MfLnW4kc`, 1,361 DFI, it's also reflected in the Explorer. 
<img width="971" alt="210107 1,361 DFI" src="https://user-images.githubusercontent.com/65014479/103878733-ca952d00-5111-11eb-92a6-451836c29fae.png">

May I know, what should be your actual balance shown in your wallet? Do you have any other addresses? Screenshots of the error you're facing in your app will help provide more insights.

**Comment by flotzke** [comment]
Ok, for the first lot (1,426.0576832 DFI) i can follow you.
The txid2 that was created by me on 28.12 has been mined one day later on 29.12.

Nevertheless the second lot (1,361 DFI) is still missing in my wallet,
and the corresponding txid 16d1d197c40504fa61f483b8665fd70c9cca5a83109499a4424a57f618780247
from the utxostoaccount transaction is still not visible in the block explorer.

from today:
gettokenbalances
[
  "35.37494942@0",
  "0.00064323@2",
  "4374.51264899@3",
  "33.38668659@5"
]
 
IMHO my tokenbalance should be + 1,361,18179431

**Comment by flotzke** [comment]
Today i could reclaim the lost DFI by installing the app from scratch on a different mac by doing the following:

1. restore from seed
2. import wallet

I found them as utxos's with getbalance.
On the first pc the getbalance was much less.
I then sent them to my own address, and then they appeared as well on the firs PC

It seems that on my first pc there are (sometimes for hours) not going any transactions in the chain,
but still influencing the balance in the wallet.
