### ISSUE TITLE
 does not refer to any valid address

### ISSUE THREAD

**Issue by didicorp** [DeFiCh/app#187]
problem: 

cant send my dfi or ustd i swapped back to any adress. 

dfi came from latoken. so i think that are coins and no token.   i didnt mine in the lp. it was only to check the app so there are no mined token.  

https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/?utm_medium=android_app&utm_source=share

step 3 doesnt work: 

getaccount address_from_command_before
recipient (address_from_command_before) does not refer to any valid address

**Comment by izzycsy** [comment]
Hi @didicorp , from the Reddit post by u/DanielZirkel, in the comments section there was a user that faced a similar issue, the `address_from_command_before` is a placeholder. You've to use the **address** which was determined in the **step before**. 

If your issue of not being able to swap persists, kindly send your app logs. If possible, do attach screenshots / screen recordings. This will provide more insight to for the investigation. Thank you.

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/103309807-0e709e00-4a51-11eb-93a9-1489544a123b.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/103309831-16c8d900-4a51-11eb-94bd-9b8f6b9964ef.png">

**Comment by izzycsy** [comment]
Hi @didicorp , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
