### ISSUE TITLE
Windows LM issue - can't add liquidity

### ISSUE THREAD

**Issue by jonjomatic** [DeFiCh/app#188]
Hi - I've already got a test run amount of DFI-BTC in LM but can't add more - No option to select or enter data for "Receive shares at"

Below screenshot is DFI-USDT but I get the same issue with DFI-BTC.  Windows version 2.1.4

![Screenshot 2020-12-28 172028](https://user-images.githubusercontent.com/75774679/103204584-a166e680-4932-11eb-933e-21b1df571d69.png)

If I try to proceed then I get the following

![image](https://user-images.githubusercontent.com/75774679/103204747-fe629c80-4932-11eb-85a6-6b886018829e.png)

Funds in wallet are recently transferred from Cake

Cheers, J.

**Comment by jonjomatic** [comment]
BTW I restored my wallet today from seed to trial the restore before committing to adding more funds to my defichain address

**Comment by SwissKerim** [comment]
I have the same problem.. I think the problem is because the "Receive address" is a empty string. I also can't choose a address..

**Comment by SwissKerim** [comment]
I have a solution. Create a new Wallet with a name and choose it in the list.
 The reason why you dont see your wallets in the list is, because in the old version there was no label for the wallets.

**Comment by jonjomatic** [comment]
> 
> 
> I have a solution. Create a new Wallet with a name and choose it in the list.
> The reason why you dont see your wallets in the list is, because in the old version there was no label for the wallets.

Do you mean the old version of defi-app?  I have only used 2.1.4

**Comment by SwissKerim** [comment]
I created my wallet in the old version. Just create a new Wallet and use it for the rewards

**Comment by izzycsy** [comment]
Hi @jonjomatic , thanks for your feedback. Did @SwissKerim suggestion worked? If the `JSON value is not a string as expected` still occurs, kindly send your app logs. Thank you.

And thank you @SwissKerim .

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/103310290-2e549180-4a52-11eb-9a6e-3274fb4f8765.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/103310295-30b6eb80-4a52-11eb-85cc-dc1a9f98464f.png">

<img width="671" alt="3 Drag and drop" src="https://user-images.githubusercontent.com/65014479/103310300-33194580-4a52-11eb-8d8a-dd3451f75cc2.png">

**Comment by jonjomatic** [comment]
Hi @izzycsy - I have my funds in my current wallet.  So, if I set up a new wallet then I won't be able to access them, therefore the workaround doesn't work for me.  Or have I missed something?

At the moment I can't add liquidity for the reason mentioned above. I do also have a test amount of DFI-BTC liquidity mining in defi-app, and I am not able to withdraw the funds from LM in defi-app - same issue, no wallet address to withdraw to.

I've uploaded my logs to my other issue in https://github.com/DeFiCh/app/issues/195

Cheers.

**Comment by amainz** [comment]
Hi @izzycsy 

I have the same issue with the windows wallet while adding liquidity. I see that jonjomatic added the logs already. Do you plan to fix it soon?

Cheers
Andre

**Comment by jonjomatic** [comment]
Since the above message I switched between versiosn 2.1.3, 2.1.4 and 2.1.5 but could not rectify.

I eventually understood the workaround mentioned above and created a new address and while I forget the exact sequence of events I was able to withdraw my liquidity to the address, and add liquidity again.

The main problem is if you have to recover your wallet from seed phrase the addresses will disappear from the menu and you will need to set up new defichain address

If it was possible to enter addresses manually for LM then this would not create such an issue, because it is possible to identify your addresses using the CLI

**Comment by izzycsy** [comment]
Hi @amainz , @jonjomatic is right, the issue for this could be that, your Receive Address is empty. Can you check if you've a `Receive Address` in your DFI wallet? 

If no, you need to create a `Receive Address` first, then it should appear in Add / Remove Liquidity's `Receive shares at` drop down menu. Let me know if this works out. 

<img width="1002" alt="DFI wallet   Receive   New Address" src="https://user-images.githubusercontent.com/65014479/103854043-804c8580-50ea-11eb-8396-ae81aaa8f4d4.png">

**Comment by amainz** [comment]
Hi @izzycsy 

Yes, this worked. 
I added a new receiving address. I did not pay attention to this since I did this already before. But due to several crashes of the wallet app and re-adding the wallet this seems to have disappeared.
May be it would be great to enhance the error message "JSON value is not a string.." to something more meaningful to give future users a little help.

Thank you for your support.

Andre

**Comment by izzycsy** [comment]
Hi @jonjomatic @SwissKerim @amainz , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.  
@amainz well noted on your feedback. Thank you.
