### ISSUE TITLE
Insufficient UTXOS to perform swap

### ISSUE THREAD

**Issue by mummelbar** [DeFiCh/app#192]
Tried to add liquidity to liquidity mining but did not work.
Updated the app and since then have the issue that I cannot convert or send DFI / BTC because it shows error message "Insufficient UTXOS to perform swap". Attached are the logs
[Archiv.zip](https://github.com/DeFiCh/app/files/5747765/Archiv.zip)

**Comment by izzycsy** [comment]
Hi @mummelbar , thanks for your feedback & app log. Please give us time to investigate this issue.

**Comment by booky84** [comment]
Same Problem here. 
[app logs.zip](https://github.com/DeFiCh/app/files/5755217/app.logs.zip)

**Comment by izzycsy** [comment]
Hi @booky84 , well received. Please give us time to investigate this issue. Thank you.

**Comment by izzycsy** [comment]
Hi @mummelbar @booky84 , in the mean time, there may be a solution to this, it could be that you've too little DFI UTXOs balance — which is required to perform swap and other functions. You could try convert a little DFI tokens to DFI UTXOs, and see if it works. Attached a link that might help you <https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/>.

**Comment by booky84** [comment]
@izzycsy thanks for your quick feedback. the workaround on the console fixed the problem in my case.
