### ISSUE TITLE
Windows: Synchronizing starts at each start / menu, "Wallet" not accessible

### ISSUE THREAD

**Issue by DeFiDirk** [DeFiCh/app#193]
2.1.4 asks at each start for synchronizing because of corrupted files although it was fully synchronized before.

There is no point in hte menu "Wallet" accessible - Import / Backup / Reset Wallet just in grey colour and cannot be clicked.

**Comment by jdavidhuebner** [comment]
Had the same Issue with 2.1.4

**Comment by madmehn** [comment]
That´s also my problem !!! i tryed also to importwallet "filename" with console , syntax importwallet "C:\Users\UserName\finan**\defichain2812txt" .. result is --> null ? please someone from the team can help ?

**Comment by izzycsy** [comment]
Hi @DeFiDirk , @jdavidhuebner , @madmehn , thanks for your feedback, could you kindly attach your app logs. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/103311654-e0418d00-4a55-11eb-8bea-079ac378dbe8.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/103311658-e5064100-4a55-11eb-8ab9-b3c5df4fca47.png">

**Comment by DeFiDirk** [comment]
Please find attached logs. - Sorry, the files seem too big for this chat...Please see attached screenshot.


![Screenshot 2020-12-30 103027](https://user-images.githubusercontent.com/74500775/103342554-139e0f00-4a8a-11eb-8c7a-2485b7a0a78d.jpg)

**Comment by izzycsy** [comment]
Hi @DeFiDirk , could you try to send them separately, or at least the `app_log.log`? On Github the maximum size for files is 25MB and the maximum size for images is 10MB.

**Comment by DeFiDirk** [comment]
Here we go....
[app_log_conf.zip](https://github.com/DeFiCh/app/files/5761550/app_log_conf.zip)

**Comment by izzycsy** [comment]
Hi @DeFiDirk @jdavidhuebner @madmehn , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
