### ISSUE TITLE
can not add liquidity

### ISSUE THREAD

**Issue by crypto-uli** [DeFiCh/app#194]
All,
After resolved Issue " #163 can not see my wallet".
I can not add or remove liquidity since there is no recieving address availible see picture below.
Installation on Windows 10 Rev. 2.1.4 
wallet restored by using mnemonic seed.
 Initial installation was the previous release. 2.1.3

My quesion is there a workaround to add or remove liquidity? probably by using the console?
Do I have to modify my Backup wallet?
Otherwise by when is a fix availible?
I will attache the log files as well
![grafik](https://user-images.githubusercontent.com/76495398/103245677-2d900280-4961-11eb-81b9-1e3cacc09f75.png)

Thanks for commets and Support

**Comment by jonjomatic** [comment]
I have the same issue in https://github.com/DeFiCh/app/issues/188

**Comment by crypto-uli** [comment]
I found a solution 
I erased the compete installation 
installed the initial version ( where I created my mnemonic seed)
restored my wallet
competing this I had my original state again, everyting works.

reagrds

**Comment by izzycsy** [comment]
Hi @crypto-uli , thanks for your feedback, glad that you manage to come up with a solution. 

Hi @jonjomatic , replied to your issue. Please give us time to investigate this issue.

**Comment by uzyn** [comment]
Closing as it's duplicate.
