### ISSUE TITLE
Cannot activate reindex option on the windows app

### ISSUE THREAD

**Issue by Popa11** [DeFiCh/app#199]
![Reindex option](https://user-images.githubusercontent.com/76740267/103293260-cb321300-49ef-11eb-9da3-6765f18fcf2b.png)
Hi, when I select the reindex option and click save it says Node restart all the time and the icon rotates but nothing happens. It has been running for an hour. Is it normal that it takes so long? Yesterday it just stopped after an hour with the error message that the blocks are corrupted. Then the app starts to resync but the reindex option is still not enabled. Can you help me? I would like to enable the reindex option.

**Comment by Popa11** [comment]
How i can send the log files to you? The zip folder is 37 MB.

**Comment by Popa11** [comment]
[app logs.log](https://github.com/DeFiCh/app/files/5752576/app.logs.log)

**Comment by izzycsy** [comment]
Hi @Popa11 , well received, please give the team time to investigate this issue. Thank you.

**Comment by izzycsy** [comment]
Hi @Popa11 , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
