### ISSUE TITLE
Connection with node is disconnected - Problem DefiApp

### ISSUE THREAD

**Issue by Goekan91** [DeFiCh/app#200]
Hello,

When opening my apps, I get the error message "Connection with node is disconnected". Was that a problem? And every time the app is accessed, the blocks are reloaded. Can someone help me?

Thank

**Comment by izzycsy** [comment]
Hi @Goekan91 , thanks for your feedback. Kindly send your app logs. If possible, do attach screenshots / screen recordings. This will provide more insight to for the investigation. Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/103312449-0c5e0d80-4a58-11eb-9a56-ee879b402b94.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/103312452-0ff19480-4a58-11eb-924e-6bb5f3dffce8.png">

**Comment by Goekan91** [comment]
Hello Bella,

thanks for your fast answer.

Here is the Screenshot and my app log in the attachment.

Thank you.


Von: Bella<mailto:notifications@github.com>
Gesendet: Dienstag, 29. Dezember 2020 21:33
An: DeFiCh/app<mailto:app@noreply.github.com>
Cc: Goekan91<mailto:goekhan.dasbacak@hotmail.de>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [DeFiCh/app] Connection with node is disconnected - Problem DefiApp (#200)


Hi @Goekan91<https://github.com/Goekan91> , thanks for your feedback. Kindly send your app logs. If possible, do attach screenshots / screen recordings. This will provide more insight to for the investigation. Thank you.

[1 App log]<https://user-images.githubusercontent.com/65014479/103312449-0c5e0d80-4a58-11eb-9a56-ee879b402b94.png>

[2 Compress]<https://user-images.githubusercontent.com/65014479/103312452-0ff19480-4a58-11eb-924e-6bb5f3dffce8.png>

**Comment by izzycsy** [comment]
Hi @Goekan91 , okay I've informed the team to look out for your email. Alternatively, you can drag and drop it here so I can escalate this. Thank you.

**Comment by izzycsy** [comment]
Hi @Goekan91 	, update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.

**Comment by Goekan91** [comment]
Hello,



i still get the same error message. But this time at 99.75%. What is the problem. I increased my laptop from 8 to 12 GB of RAM.

Thank you and best regards.


Von: Bella<mailto:notifications@github.com>
Gesendet: Dienstag, 12. Januar 2021 22:22
An: DeFiCh/app<mailto:app@noreply.github.com>
Cc: Goekan91<mailto:goekhan.dasbacak@hotmail.de>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [DeFiCh/app] Connection with node is disconnected - Problem DefiApp (#200)


Closed #200<https://github.com/DeFiCh/app/issues/200>.
