### ISSUE TITLE
DEX has error shown

### ISSUE THREAD

**Issue by OKnr66** [DeFiCh/app#201]
Error shown during DEX DFI to BTC.  Getbalance shows more DFI .
Execution test failed: PoolSwap creation: 
(76a914512ddc88981a5f102b70d8fbc0e6f3a23c79b15288ac:24500000000@0->76a9140959853538af80f76e0c007e9808599cb5c2f47788ac:?@2): 
PoolSwap creation: (76a914512ddc88981a5f102b70d8fbc0e6f3a23c79b15288ac:24500000000@0->76a9140959853538af80f76e0c007e9808599cb5c2f47788ac:?@2): 
amount 23861247206 is less than 24500000000

getbalance
255.03093499

**Comment by OKnr66** [comment]
10 Minutes later it worked. Maybe interesting for you. Cat 3 Call from my side :-).

**Comment by izzycsy** [comment]
Hi @OKnr66 , great. You may check your balance with the following commands: 
`getbalance` — utxo DFI 
`getokenbalances` — DFI  
The sum of utxo DFI & DFI would be your total DFI.
