### ISSUE TITLE
Cannot add to LM or Withdraw (BTC)

### ISSUE THREAD

**Issue by p3root** [DeFiCh/app#202]
Getting a strange error message (in this case, I tried to add BTC-DFI to LM).

Transfer AccountToAccount: from 76a9140ff210fe7be192db677431b613ea643e004c60eb88ac to (a91480b803f1d38dc4094615c129546651c57c3d4da487->0.16629351@2): amount 16629160 is less than 16629351 (code 16)

Withdraw was also not possible - see screenshot. Indeed I could swap it to DFI. 

![image](https://user-images.githubusercontent.com/4295914/103341132-4b0abc80-4a86-11eb-9d77-58b6838d0daa.png)

**Comment by p3root** [comment]
After swaping back via the DEX, it worked again. Seems like an invalid UTXO set?

**Comment by izzycsy** [comment]
Hi @p3root , thanks for your feedback. We do have an `Insufficient UTXOs` bug at the moment which the team is fixing <https://github.com/DeFiCh/app/issues/162>, however I need more information to determine if yours the same. 

Should you face the same issue again, kindly send your app logs. If possible, do attach screenshots / screen recordings. This will provide more insight to for the investigation. I'll be closing this comment in the mean time. Thank you.
