### ISSUE TITLE
DeFi chain lässt sich nicht öffnen

### ISSUE THREAD

**Issue by Sim-Cyber** [DeFiCh/app#203]
Hallo,
Ich habe die Defi Wallet App mit ´´X´´ geschlossen und den PC für 2 Tage ausgemacht. 
Nun mache ich ihn wieder an, möchte in die 2.1.4 DeFi Wallet App schauen (in Windows 10). Dies lässt sich leider nicht öffnen.  Es kommt immer die gleiche Meldung welche ich hier einfüge.
Ich kann nur auf ´´App Neustarten´´ klicken oder ich klicke auf ´´App Schliessen´´ . 

![20201230_120401](https://user-images.githubusercontent.com/76777781/103351485-b911ac80-4aa3-11eb-9ed1-e2af65c1f6f8.jpg)

Ich habe die DeFi Wallet App schon deinstalliert und neu installiert. 
Ich wäre sehr dankbar wenn mir jemand bei dem Problem helfen könnte.
Mit freundlichen Grüßen
Simon

**Comment by izzycsy** [comment]
Hi @Sim-Cyber , did you try restarting the app and waiting for it to sync to 100%? We're aware that there's a `corrupted block database detected` bug at the moment, and the team is fixing it. In the mean time, this is the only workaround — `restart app` + `wait till 100%`.

Current block is at 539,649, so it'll take awhile to sync. Thank you for your patience.

**Comment by Sim-Cyber** [comment]
Hallo izzycsy,
vielen dank für deine Antwort. 
Wie man auf dem Bild sieht laesst sich da leider nichts synchronisieren. 
Ich kann absolt nichts machen. Synchronisieren tut sich die App auch nicht.

Das heisst, dass der Fehler Ihnen bekannt ist. Nun warte ich also bis der Fehler behoben wird und in ein paar tagen/Wochen sollte sich die App normal wieder starten lassen?

**Comment by izzycsy** [comment]
Hallo @Sim-Cyber , yes the team is currently investigating the issue. Thank you for your understanding. Could you send your app logs please?

**Comment by izzycsy** [comment]
Hi @Sim-Cyber , update v2.1.7 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.

**Comment by Sim-Cyber** [comment]
Hallo liebe Bella,

es ist nun 2 Monate her das auf meiner DeFI Wallet ein Problem aufgetreten ist. Ich habe seit diesem Zeitpunkt keinen Zugriff mehr auf meien DeFi Wallet. Dort liegt für mich viel Geld und ich bin etwas verzweifelt.

Ich schicke hier nun meine Logs+ Screenshot.

Ich hoffe ihr könnt mir weiterhelfen.

 

Mit freundlichen Grüßen 

Simon Garz


 

Gesendet: Mittwoch, 13. Januar 2021 um 17:03 Uhr
Von: "Bella" <notifications@github.com>
An: "DeFiCh/app" <app@noreply.github.com>
Cc: "Sim-Cyber" <garz.simon@web.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [DeFiCh/app] DeFi chain lässt sich nicht öffnen (#203)


 

Hi @Sim-Cyber , update v2.1.7 is out https://defichain.com/downloads/.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
