### ISSUE TITLE
Transfer from BITTREX did not arrive

### ISSUE THREAD

**Issue by hjd48** [DeFiCh/app#207]
Hello dear service, yesterday at 12:27:07 p.m. from BITTREX I sent 0.00172452 BTC to my wallet (dcC3UVysyApqs7VZe2poEm17zLqqiwkVei) with the
Payment UUID ce115afa-1b5e-45b9-b201-77efae955046
transferred. Nothing arrived. Status: Invalid
I also received the following messages from the DEFI-APP:
Wallet Balance Error Network Error
Pending Balance Error Network Error

Please fix the problems (including the missing coins from BTC).
Best Regards
H-J.
[Bildschirmfoto 2020-12-30 um 14.27.37.pdf](https://github.com/DeFiCh/app/files/5757061/Bildschirmfoto.2020-12-30.um.14.27.37.pdf)
[Bildschirmfoto 2020-12-30 um 14.27.50.pdf](https://github.com/DeFiCh/app/files/5757063/Bildschirmfoto.2020-12-30.um.14.27.50.pdf)
[Bildschirmfoto 2020-12-30 um 14.49.48.pdf](https://github.com/DeFiCh/app/files/5757064/Bildschirmfoto.2020-12-30.um.14.49.48.pdf)

**Comment by Sim-Cyber** [comment]
Hallo hjd48.
Ich bin kein Spezialist, jedoch hatte ichvor ein paar tagen das gleiche Problem. 
Du kannst deine Bitcoin nicht von Bittrex direkt auf deine DeFi chain (wallet app) versenden.  
Du hast zwei verschiedene Möglichkeiten deine BTC von Bittrex zu deiner DeFichan zu versenden. 
1. Entweder du schickst von Bittrex deine Bitcoin auf Cake um sie dann von Cake auf deine Defi chain zu versenden.
2. Du tauscht deine BTC auf Bittrex zu DFI und schickst diese direkt zu deiner Defi chain Wallet

Schreibe den Bittrex Support an und schildere dein Problem. So hatte ich es letzte Woche getan und dann so meine BTC wieder bekommen. Binnen 3 tagen hatte ich meine BTC wieder.

Ich hoffe ich konnte dir weiterhelfen
Mit freundlichen Grüßen
Simon

**Comment by hjd48** [comment]
Hallo Simon,
ich danke Dir für diese gute Info. Alles Gute für Dich!

Mit freundlichen Grüßen 
Hans-Jürgen

**Comment by izzycsy** [comment]
Hallo @hjd48 , kindly update if you've manage to solve the issue. Thank you @Sim-Cyber for your help!

**Comment by izzycsy** [comment]
Hi @hjd48 , update v2.1.7 is out <https://defichain.com/downloads/>. 

I hope BITTREX has replied your enquiry. I'll be closing this Issue in the mean time, you may reopen if you've new information related to DeFi app (include screenshots) and your app logs. Thank you.
