### ISSUE TITLE
Linux AppImage 2.14 endless sync + insane memory usage + stuck when closing the app

### ISSUE THREAD

**Issue by niccoooo** [DeFiCh/app#209]
After 2 hours for the sync (without using other apps) and insane memory usage (4+14gb ram+swap) I could not close completely the app and end the process **defi-app** and **defi-shutoff** (this one still consuming memory).
I tryed with **kill**, but nothing.

These are the messages in the terminal on Linux 5.8.18-1-MANJARO x86_64 20.2 Nibia:
```

>>> ./defi-app-2.1.4.AppImage                                      
11:08:37.801 › Checking for update
11:08:38.908 › Node start initiated
Node start initiated
11:08:39.008 › Update for version 2.1.4 is not available (latest version: 2.1.4, downgrade is disallowed).
11:08:39.009 › checkForUpdatesAndNotify called, downloadPromise is null
11:08:39.203 › Node started
Node started
11:08:41.242 › Got error in isBlockchainStarted: Error: Request failed with status code 500
11:08:43.215 › Got error in isBlockchainStarted: Error: Request failed with status code 500
13:10:09.555 › {}
13:10:36.676 › Error: Request failed with status code 503
    at e.exports (file:///js/zchunk-2.1937e1f8.js:51:207430)
    at e.exports (file:///js/zchunk-2.1937e1f8.js:333:8126)
    at XMLHttpRequest.h.onreadystatechange (file:///js/zchunk-2.1937e1f8.js:51:206277)
13:10:46.438 › Error: Request failed with status code 503
    at e.exports (file:///js/zchunk-2.1937e1f8.js:51:207430)
    at e.exports (file:///js/zchunk-2.1937e1f8.js:333:8126)
    at XMLHttpRequest.h.onreadystatechange (file:///js/zchunk-2.1937e1f8.js:51:206277)
```

**Comment by izzycsy** [comment]
Hi @niccoooo , thanks for your feedback, could you send your app logs please? 

In the mean time, you may refer to <https://github.com/DeFiCh/app/issues/173>. The team is currently investigating this issue, thank you for your understanding.

**Comment by niccoooo** [comment]
Hi! Thanks for your reply!

[defi-app.log](https://github.com/DeFiCh/app/files/5762375/defi-app.log)

**Comment by izzycsy** [comment]
Hi @niccoooo , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
