### ISSUE TITLE
defi-app_v2.1.4 for MacOS: CLI does not accept characters typed via the option key

### ISSUE THREAD

**Issue by tame81** [DeFiCh/app#210]
On MacOS, when using the CLI, characters like curly braces do not work properly. I cannot enter them as usual, because OPTION+8 does not do anything. 

Note: I use a German keyboard layout, normally that's the way to type "{". My workaround for now is copy/paste of that character, which is very inconvenient. (Everywhere else, in the terminal or any GUI app, I can type the curly braces with OPTION+8/9.)

**Comment by izzycsy** [comment]
Hi @tame81 , thanks for your feedback. Yes, we're aware of this issue <https://github.com/DeFiCh/app/issues/112>. Please give us time to fix this. Thank you for your understanding.

**Comment by izzycsy** [comment]
Hi @tame81 , regarding the issue `CLI: Does not accept [option] key characters, i.e. {}`, I'll link you to <https://github.com/DeFiCh/app/issues/112> where I'll keep you updated, and we can further discuss on the problem. We would like to keep same issues in one thread. Thank you.

**Comment by tame81** [comment]
Sure Bella, I have the exact same problem, that <option> key combinations
are not supported by the CLI.

Am Mi., 13. Jan. 2021 um 08:32 Uhr schrieb Bella <notifications@github.com>:
