### ISSUE TITLE
Wallet: unable to send DFI

### ISSUE THREAD

**Issue by Ausafari** [DeFiCh/app#211]
Hi,
I have over 1,000DFI sitting in my DFI wallet in the app.
I have tried to send it to my DFI wallet address in both Cake and Bittrex.
No matter what wallet or how much DFI I try to send (I have tried up to 100 DFI), I receive the same error message on the final screen: "Error occurred while sending amount".
I can send you a screenshot of the relevant screen, but as it includes my Cake wallet address, I don't know if this is advisable.
Please help!
David

**Comment by Ausafari** [comment]
Hi,
To further assist, I have attached the app and binary logs, in case they are useful.
Thanks,
David
[defi-binary-log.log](https://github.com/DeFiCh/app/files/5759496/defi-binary-log.log)
[defi-app-log.log](https://github.com/DeFiCh/app/files/5759497/defi-app-log.log)

**Comment by izzycsy** [comment]
Hi @Ausafari , thanks for your feedback & app logs. In the mean time, there’s a temporary solution to this, it could be that you've too little DFI UTXOs balance — which is required to perform swap and other functions. You could try convert a little DFI tokens to DFI UTXOs, and see if it works. Attached a link that might help you.  <https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/> 

Currently you can only transfer to and fro via <cakedefi.com>. Let me know if it works for you.

**Comment by Ausafari** [comment]
Hi there,
Thanks for getting back to me. In the interim, one of the other users on the Telegram channel  pointed me in the direction of the above Reddit post. That worked, but obviously not a good UX. Two things I would suggest in terms of feedback as a result:
1: In the next iteration of the app, ensure this functionality can be completed by the user without resorting to CLI. Although I have experience in command line, it would be extremely daunting for those who don't to use this method.
2: The CLI needs to support CTRL+ functionality. Currently this is disabled. That means one has to laboriously and manually enter in the wallet addresses each time, which leads to regular errors. In the interim, this is even more important than (1) above and very simple to enable.
Thanks for taking this feedback on board.
David

**Comment by izzycsy** [comment]
Hi @Ausafari , well received on the app logs. Yes, the team is investigating and trying to fix this. Thank you for your understanding.

**Comment by izzycsy** [comment]
Hi @Ausafari , update v2.1.7 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
