### ISSUE TITLE
Windows10: high memory usage... 95% of 16gb

### ISSUE THREAD

**Issue by kevarms2** [DeFiCh/app#212]

**Comment by kevarms2** [comment]
The is the .14 update for app in windows 10

**Comment by kevarms2** [comment]
seems to be {defid (DeFi Blockchain node with a JSON-RPC server)} in taskmanager that is sucking up all the memory!

**Comment by kevarms2** [comment]
[log.log](https://github.com/DeFiCh/app/files/5761011/log.log)
[log defi.log](https://github.com/DeFiCh/app/files/5761013/log.defi.log)

**Comment by izzycsy** [comment]
Hi @kevarms2 , thanks for your feedback. The team is currently investigating this issue, please give us time to look into it. Thank you.

**Comment by kevarms2** [comment]
continued after 2.1.5   appears to happen when sync reaches around 90%

**Comment by izzycsy** [comment]
@kevarms2 noted, the team is still investing this issue. Thank you for the update.

**Comment by izzycsy** [comment]
Hi @kevarms2 	, update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
