### ISSUE TITLE
Private key lost after wallet restore

### ISSUE THREAD

**Issue by guiphil** [DeFiCh/app#214]
Hello, 

I re-installed my computer and now wanted to restore my DeFi wallet. 
- I installed DeFi App 2.1.4 and restored my wallet with my mnemonic seed (24 words) (working fine)
- I waited until the wallet was fully synchronized  (working fine)
- My ETH (-Token) are all there
- Now it shows only 13 DFI instead of ~1600. 
- The 1600 DFI are on this address `8F6jenzMBEsiogBmgB9AMDcQJ4EAvCRCns` 

If I type `getaddressinfo 8F6jenzMBEsiogBmgB9AMDcQJ4EAvCRCns` it shows: `"ismine": false`

The private key for the address  `8F6jenzMBEsiogBmgB9AMDcQJ4EAvCRCns` has not been generated while restoring the wallet. 

Any idea what I can do?

----------------
- I already re-installed DeFi App 2.1.4 and tried again, and also installed 2.1.3 and tried there, also no success. 
- I did not make any backup of the old DeFi wallet as only the mnemonic seed is needed to generate all private keys. 
Windows 10 Pro 2004
[app.log](https://github.com/DeFiCh/app/files/5761794/app.log)
[binary.log](https://github.com/DeFiCh/app/files/5761795/binary.log)

**Comment by izzycsy** [comment]
Hi @guiphil , thanks for your feedback. Could you check your balance using the following command via the CLI: 

`getbalance` — utxo DFI
 `getokenbalances` — DFI  
 The sum of utxo DFI & DFI would be total DFI
 
I would suggest that's it's a good habit to `backup wallet` often. Please let me know the result of getting your balance.

**Comment by guiphil** [comment]
Hello @izzycsy,

thanks for your reply! You are doing a great job replying to all comments and posts here and on reddit. 
Keep up the good work 💯 🥇 

For `getbalance` I get 8.07 DFI and for `gettokenbalances` I get 5.26 DFI which together is ~13 DFI.

Why is there a need to backup your `wallet.dat` file if you have the recovery words?  (mnemonic seed)
I thought that's what recovery word are there for. All child private keys should be generated via the master private key in the HD wallet. Please correct me if I'm wrong.

Thanks in advance 👍

**Comment by izzycsy** [comment]
@guiphil thank you for your kind words. Do you have the transaction id (txid) for the above mentioned 1600 DFI? You sent it to your DeFi app?

Well, `backup wallet` is not a requirement, but sometimes you'll never know what kind of bugs might happen, so I feel it's sort of a safety net to do backups every now and then. Personally, I do so before I updating the app (eg. to v2.1.5).

**Comment by guiphil** [comment]
Hi @izzycsy, 

doing regular backup actually makes sense then, you are right. 

I sent 139 DFI from CAKE to my wallet and converted 500 USDT via the DEX to ~1481 DFI. That was all working fine. I don't have any specific txid, only the txids which can be found at https://explorer.defichain.io for the address `8F6jenzMBEsiogBmgB9AMDcQJ4EAvCRCns`. 

I'm actually trying to find out which way addresses and private keys are generated in the DeFi HD wallet. I already checked out the wiki documentation but it's quite slim. 

To me it seems like the **hdkeypaths** which are used for DeFi is 
- `m/0'/0'/0'` to `m/0'/0'/999'` and 
-  `m/0'/1'/0'` to `m/0'/1'/999'`, 

Is this true? So the DeFi wallet only uses private keys / addresses generated from those hdkeypaths?

If I click "**New Address**" for my DeFi wallet, in which way is a address selected of those? Is there a specific order or is it a random address and private key from the hdkeypaths range mentioned above?

**Comment by izzycsy** [comment]
@guiphil  indeed, with the `wallet backup`, in the event when you `Restore Wallet` via mnemonic seed and your balance displayed is incorrect, you can `import` wallet backup and it should be displayed correctly. 

I'll need to get back to you in the hdkeypaths question. 

To answer the 2nd half, when you click on New Address, I believe it's a randomly generated address that's unique to you only.

**Comment by guiphil** [comment]
Thanks! 
Regarding the "**New Address**" button, but where is the address generated from? One random child private key from the extended privated key? (mnemonic seed)

In the new version 2.1.5 when I generate a new **legacy address** (just for fun) it shows "**Warning: Not secured by seed phrase**". This is new! So my address `8F6jenzMBEsiogBmgB9AMDcQJ4EAvCRCns` starts with 8, so it's a legacy address. I never generated a legacy address intentionally.

Also when generating a **standard address** is also shows a warning "**Warning: Not secured by seed phrase**" even though I can see the address in the wallet backup + private key. I even deleted the wallet again and the address which said "**Warning: Not secured by seed phrase**" was again in the backup.

**Comment by nappy** [comment]
I am having the same issue with a standard address, when I initially created it it showed the warning. After a while though the warning went away (maybe after version update). Now after restoring from seed and manually adding the address, the walled does not show balances from that address.

Can we please get more clarification on this matter, from what I read here the key should be restorable from seed. Is it possible that if I add the address manually, it uses a wrong key?

Also the warning in the UI does not indicate whether it only refers to the address / name or also the private key.

**Comment by izzycsy** [comment]
Hi @nappy , thanks for your feedback & update. Kindly send your app logs. If possible, do attach screenshots / screen recordings. This will provide more insight for the investigation. Thank you.

**Comment by salomonkarsten** [comment]
Hello all, 
after I restarted the app also it was already running, everything was stuck. Therefore I wnated to recreate the wallet, usung mnemoric key with the 24 words saved. After doing so, every asset was not displayed and instead of several ten thousand DFI, only 0,0005 something was displayed. Then I found an wallet-bax-xxxxx.dat file in C:\Users\User\AppData\Roaming\DeFi Blockchain\wallets . So I replaced this file with the wallet.dat . Now I see my balances but all  the previous receiving addresses are gone. Now I tried to go back to old version reinstalling etc. reputting the key again... Same issue. Main  problem now is, I seem to still see my assets but the master key / private key seems not be connected to the new generated addresses. Same problem as above. So I cannot move balances tokenized version to the coin version. Please help urgently as all my coins and not view are stuck now on the wallet. 
[08012021LogfileWallet.log](https://github.com/DeFiCh/app/files/5785414/08012021LogfileWallet.log)

**Comment by izzycsy** [comment]
Hi @salomonkarsten , thanks for your feedback, are you getting `Warning: address not saved by seed phrase`? Could you send a screenshot for your error please? 

If the above is true, it seems like the addresses is not secured by seed phrase, I would suggest:  
1. save the address externally (eg. copy & paste in Notes)
2. do backup wallet often
	
You should be able to continue using the features.

**Comment by salomonkarsten** [comment]
@izzycsy Thanks but this is not a good way as when it still was working, it was no linger possible to move the tokens to coin side to add to liquidity or transfer anywhere. Actually as stated in issue 235, I try to redcover all from scratch. unfortunately fully stuck at syncing. Nothing is moving... 0% since hours.

**Comment by guiphil** [comment]
What can help to increase the syncing process speed is to disable your Anti-Virus or add an exception to your Firewall. This prevents the **defid.exe** (Windows) process from being scanned. This increased my syncing speed from 3 hours+ to 20-30 min.

**Comment by salomonkarsten** [comment]
After 8.5 hours it is now synced. As the balance showed only 0.0005 DFI but no tokens and getbalances as well as listaccounts also showed virtually nothing. I found you can reload UTXO in the new Wallet 2.1.6 I started this now and it is already running for 9 hours day.  What exactly does it do? Rescan the whole blockchain and try if it fits with your private 24 keywords (private key)? Please help how to recover the wallet if you only have the 24 key words. I am lacking several thausand USD.

**Comment by guiphil** [comment]
Do you know the address on which your coins are on? 
If so, type `getaddressinfo <your-address>` in the CLI for each of your addresses and check if it says `"ismine": false` or `"ismine": true`.

- If it says `true`, you still do have access to the coins on that address, and it just doesn't display your funds correctly in the app
- If it says `false`, you do not have the private key to the address anymore, thus you are not able to access funds on that address
------
It is not 100% clear yet if you are able to restore all private keys in the `wallet.dat` file with your 24 word seed. 

Your 24 word seed is pretty much just one *large* private key, from which you are able to generate lots of child private keys (millions). For more info google Bitcoin HD-Wallet (BIP-32). 

24 words -> extended private key -> lots of child private keys -> public key -> address (legacy or standard format, see DeFi wiki)

To me it seems like that not all private keys (addresses used) are generated via the extended private key. 
Private keys which are not generated via the extended private key (24 words) are only stored locally in the `wallet.dat` file.  
That's why that file currently more important than the 24 words.

With the extended private key you are able to restore *some* private keys (access to addresses).
What the wallet restore progress does is, it generated ~2000 private keys + address (`m/0'/0'/0'` to `m/0'/0'/999'` and
`m/0'/1'/0'` to `m/0'/1'/999'`) from your extended private key (24 words), and stores them in your `wallet.dat` file. The wallet should then use only address from those that have been generated via the ext. priv. key. 

It currently *seems like*  that *some* addresses used by the app are not part of the 2000 generated ones from the ext. priv. key.
That means, once you lose the `wallet.dat` file you won't be able to restore the private keys for those addresses again.

**I have no proof that my claim is true! I'm still testing and trying to replicate the problem**

**Comment by salomonkarsten** [comment]
This explanation sounds like a nihhtmare but give some hope as I should have an old wallet.dat 
But actually before to try to just replace the wallet.dat with an old one, I would like to wait for UTXO reload. It is still processing something since more than 12 hour...
What does this UTXO actually do. My hope it crosscheck all transactions of all blocks if my mnemonic key fits????

In that way would be able to recover the wallet in full? 


Sorry this is totally nuts to tell it is needed to safe the 24 words and indeed you need to safe much more. 

So for future purpose would the backup file be sufficient or is the .dat file needed? 

I mean I still struggle to recover a lot of coins.

**Comment by guiphil** [comment]
I can't answer all your questions, but UTXO rescans/rebuilds the blockchain and searches for any transactions that contain addresses you own, so it can show you your full balance (Is this correct?).

As @izzycsy mentioned, it's good practice to backup the seed  + the do `backup wallet` as there could always be bugs in the code
> Well, `backup wallet` is not a requirement, but sometimes you'll never know what kind of bugs might happen, so I feel it's sort of a safety net to do backups every now and then. Personally, I do so before I updating the app (eg. to v2.1.5).

The 24 words should be enough to backup, if the wallet works correctly.

@salomonkarsten 
I still recommend to do the `getaddressinfo <your-address>` `"is mine": true/false` check. This can always be done, even with a not fully synced blockchain. If it says `true` for all addresses, just wait until it's fully synced and check with `listaccounts {} true true true` and `gettokenbalances {} true true` and `getbalance` your token/coin balances.

**Comment by salomonkarsten** [comment]
@guiphil update, The scan indeed found all my adresses also in one of the 2 computers, where i try to recover the chain, i stopped the scan before finish by restarting the app. Now all tokens show up. The public addresses originally created are no longer visible. Now I face the issue, i cannot transfer token to DFI anymore. The Address stated has enough funds and is stated as "is mine": true on the command you asked for. Please advice why accounttoutxos cannot be used anymore to shift token to coins. 
![Capture3](https://user-images.githubusercontent.com/77124114/104092910-698f6580-5287-11eb-9d26-431f85101d3f.JPG)

**Comment by salomonkarsten** [comment]
Attached the label, that the new address was generated without seed passphrase... To add before and after generation of a new address the accounttoutxos command does not work due to "insufficient funds" also at the adddress stated should be enough funds. 

![Capture4](https://user-images.githubusercontent.com/77124114/104093082-9132fd80-5288-11eb-8610-5744b30ad32c.JPG)

**Comment by guiphil** [comment]
Your issue might be related to issue "**Can't transfer BTC from defi-app on defichain**"#195
I recommend to remove the screenshot showing your funds.

**Comment by nappy** [comment]
@guiphil Just to get some more evidence here, the working hypothesis is that the rescan progress just found you the address, but the private key was already restored by the seed. Thus the warning only means that you have to store the address too.
Or did you restore the old wallet.dat, and by doing so also restored the private key and the scan progress only added the address?

Because in my case I added the address manually, and balances where not showing up still. Only I imported the seed into an older version I was able to restore my balance.

Additional things that are still in question here:
- Why does the "not saved by seed phrase" warning does disappear after a while
- When and why does that warning appear at all? is it true that there are private keys unrestorable from seed

**Comment by salomonkarsten** [comment]
@guiphil thanks for the reminder to not show balances. I erased the topic. The topic you state is not the same, as i do not want to move to another wallet, but stay in the same one. On top on both getbalance as well getbalances there are no sufficient funds but on the token side there are.  Further thanks for explaining why the old public addresses are no longer listed. Also it would be easy after an 12 hour search of the blockchain to also extract the public keys when a wallet is restored. Actually i am still stuck to move any funds. either to the Liquidity or to an external wallet. All worked soper smooth before the blockchain got corrupted. 
![Capture3](https://user-images.githubusercontent.com/77124114/104093424-bc1e5100-528a-11eb-9888-a0252c64530e.JPG)

**Comment by nappy** [comment]
@salomonkarsten For the latter issue maybe just fund an additional DFI from another wallet? I think under normal circumstances, the wallet should make sure you have always 1 or more DFI left

**Comment by guiphil** [comment]
If you are able to add the address manually in the DeFi app means that you **do have** the private key to address. The wallet prevents you from adding address which you **do not have** to private key to.

**Comment by nappy** [comment]
> If you are able to add the address manually in the DeFi app means that you **do have** the private key to address. The wallet prevents you from adding address which you **do not have** to private key to.

This confuses me even more, because as I described when I restored from seed all my balances showed up again but I was not able to add the address. Then after the blockchain had to be resynced I did the same during the synchronizing I could add my addresses back and everything worked fine.

Maybe there are other strange bugs in play here which makes every observation kind of fuzzy, but I am pretty certain that what I described is true.

**Comment by salomonkarsten** [comment]
@nappy Thanks add 1 DFI from external helped to move from token to coins. I agree with you it is very confusing. On top if you do a full scan of the chain, it should be easy to also recover all new addresses. On top Now I only see transactions that i put in liquidity in the history of the wallet itself, Swaps are no longer listed.  

For me if you do a full scan after syncing the blockchain, it should be easy to also save all transactions (they are listed) and also to recover all your addresses used. Fully linked. Now it is not clear as you stated, if in case one needs to recover again just from mnemoric key after a scan of UTXO one will be able to recover all funds. 

After a while the new addresses generated (for me these are public adresses and I do not understand, how and where a second layer of private keys comes into play) are no longer tagged as not generaed from seed. Might it be the case as soon as an mercke tree is stored on the BTC chain, they are connected properly?

For me also a book with 7 signs hihihi

**Comment by guiphil** [comment]
This is what I still get for my address. This pretty much just means `"is mine": false` for this address. 

![2021-01-09_17h41_36](https://user-images.githubusercontent.com/49029755/104103380-1676dc00-52a2-11eb-8dd4-7374d144328a.png)

**Comment by salomonkarsten** [comment]
For ne resync after plan reinstall (Meiningen also erase manual the blockchain as this is still presents in %appdata% folder after uninstall. 
And subsequent rescan UTXO I was able to add exusting addresses. 

But unfortunately I did not save the old ones used before...

Be aware it took 2 days to sync and Scanner UTXOs

**Comment by salomonkarsten** [comment]
For me resync after plain reinstall (Means also erase manual the blockchain as this is still presents in %appdata% folder after uninstall).
Then subsequent rescan UTXO I was able to add previously known addresses.

But unfortunately I did not save all the old ones used before...

Be aware it took 2 days to sync and Scan UTXOs ( where I cancelled the latter scan after waiting very long)

On top I had to move 1 DFI coin on a new generated address to be able to use the wallet again.

**Comment by izzycsy** [comment]
Hi @guiphil @salomonkarsten @nappy , update v2.1.7 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, may reopen this issue with new information (include screenshots) and your app logs. Thank you for your patience on this!
