### ISSUE TITLE
Unable to sync APP - Grey Screen-

### ISSUE THREAD

**Issue by Di-rt** [DeFiCh/app#220]
After getting to 99,6% the screen becomes grey and nothing can be done.
Please help
@izzycsy 
[APP_LOGS.log](https://github.com/DeFiCh/app/files/5766102/APP_LOGS.log)

**Comment by Di-rt** [comment]
where can i send the binary logs? file is too big

**Comment by izzycsy** [comment]
Hi @Di-rt , thanks for your feedback. App log well received. May I know the OS + version no. you're using? Could you describe your user flow more (screenshots / screen recordings are encouraged). Please give us time to investigate this issue.  If you haven't already, kindly install the latest version v2.15 of the app <https://defichain.com/downloads/>.

**Comment by Di-rt** [comment]
![BC5F454C-773A-4A25-9464-514BF847A8EC](https://user-images.githubusercontent.com/76961421/103590108-4b271400-4eed-11eb-8018-44c01a0233cf.jpeg)
![5934C446-BE0C-47DE-98B3-400EA1A7CEB7](https://user-images.githubusercontent.com/76961421/103590117-4febc800-4eed-11eb-8d70-74ac37306260.jpeg)
![D6971320-C8A6-4535-BDA7-F2FE802213CA](https://user-images.githubusercontent.com/76961421/103590120-50845e80-4eed-11eb-9073-8f144a36ec6d.jpeg)
![021D789F-081A-49F9-A782-E8C53964556A](https://user-images.githubusercontent.com/76961421/103590123-51b58b80-4eed-11eb-9503-1c25e6efd19e.jpeg)
![1CC6A532-BDB0-49DA-BF52-565F003242FA](https://user-images.githubusercontent.com/76961421/103590124-524e2200-4eed-11eb-9afd-8a9bf3db44ae.jpeg)
![93869D4A-2341-4A82-87A7-93E4999447FF](https://user-images.githubusercontent.com/76961421/103590126-52e6b880-4eed-11eb-9cfb-d8518db14edf.jpeg)
![9F7F4B8E-493E-4713-90B0-9091CDF8D46C](https://user-images.githubusercontent.com/76961421/103590127-5417e580-4eed-11eb-90ca-7200ed874c12.jpeg)
![1399594F-746B-484B-8AC7-31CE7EEC1C44](https://user-images.githubusercontent.com/76961421/103590129-54b07c00-4eed-11eb-9a27-ef6ca3e06d24.jpeg)
![59C9FF60-5600-4F09-97EC-7EC5EDE0F95D](https://user-images.githubusercontent.com/76961421/103590131-55491280-4eed-11eb-95d3-37f1237f72bc.jpeg)

**Comment by Di-rt** [comment]
It is loading until 99.5% reindexing is not working

**Comment by Di-rt** [comment]
Windows 10 64 bit

**Comment by izzycsy** [comment]
Hi @Di-rt , thank you for the details. Please give the team time to investigate this.

**Comment by Di-rt** [comment]
of course 
how can i send this the. config is not supported by github

**Comment by Di-rt** [comment]
[APP_CONFIG.zip](https://github.com/DeFiCh/app/files/5771948/APP_CONFIG.zip)

**Comment by Di-rt** [comment]
i restored the wallet on other device it is working and balances show up
but there is no wallet adress how can i import the old adress or have i to configure a new one?
i have no backup file

**Comment by izzycsy** [comment]
@Di-rt well received, thank you. Please give us time to investigate this issue.

**Comment by Di-rt** [comment]
![Uploading 103796502...]

**Comment by Di-rt** [comment]
![image](https://user-images.githubusercontent.com/76961421/103796544-a5d48300-5047-11eb-8474-4600040b8aab.jpeg)

I created a new Adresse but there is this warning can I progress?
I don't see all the message. What is the warning about?

**Comment by izzycsy** [comment]
Hi @Di-rt , feedback well received. I would think the warning states `Warning: Not secured by seed phrase`. The team is currently looking into the issue. I apologise for the delay, thank you for your patience.

**Comment by Di-rt** [comment]
ok i will wait and not generate an new adress

**Comment by izzycsy** [comment]
@Di-rt thank you for your understanding.

**Comment by izzycsy** [comment]
Hi @Di-rt , here's an update, the team is still investigating this issue. However, I would suggest you save the address `dKSFxFT...` externally (eg. write it down) — for temporary safe keeping. You should be able to continue using the features. Alternatively, please wait till this issue is fixed. Thank you for your understanding. 

Do you mind sending your logs again please?

**Comment by Di-rt** [comment]
[logs.log](https://github.com/DeFiCh/app/files/5783260/logs.log)
This is the log from second device wallet syncs but the adress is not there.
If you need the logs from white screen aplication i van send it to you.
This logs are from a working app (Only adress not schows up, and there is the warning you can see on the photo when i generate a new one)

**Comment by izzycsy** [comment]
Hi @Di-rt , ah the logs for the white screen has been well received, no need to send again. Logs for Address Issue also well received. 

Since the address is not secured by seed phrase. I would suggest that you save the addresses with `Warning: Not secured by seed phrase`, and do `backup wallet` often.

**Comment by Di-rt** [comment]
Will this ne fixed kn the next weeks?
Then I will wait.

**Comment by ph115** [comment]
Same situation on my side as @Di-rt described.

- Bug did not occure in V2.1.3, Update to 2.1.4 worked until beginning this week
- Suddenly this bug occured
- Update to 2.1.5 did not help, update to 2.1.6 did not help
- Roll-back (de-installation of 2.1.6) and installation to 2.1.3 did not help

During Bug occurs, Defi App uses
- 0% CPU
- approx. 300MB RAM

Environment:
- Windows 10 Home 64bit (v20H2, Build 19042.685)
- Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
- 8,00 GB RAM (virtual RAM 40GB)
- 500 GB SSD

**Comment by ph115** [comment]
![20210108_Bug_Report_Grey_Screen_Sync_running](https://user-images.githubusercontent.com/77172505/104064212-ccd4b580-51fd-11eb-8794-473670def31a.JPG)
________________________________________________

![20210108_Bug_Report_Grey_Screen_Sync_stopped_grey_screen](https://user-images.githubusercontent.com/77172505/104064206-cb0af200-51fd-11eb-96e2-7a07777ce211.JPG)

**Comment by Di-rt** [comment]
Hey with the update it works again great job. 
Wallet syncs and all my funds are visible. 
The only matter with the address.
I now my old address is it possible to import it?

**Comment by Di-rt** [comment]
@ph115 i did the update it synced util 99% then stopped but screen did not disappear this time. Then I did the reindex and everything is fine.

**Comment by Di-rt** [comment]
@izzycsy should I download the app on new device generate an new wallet with new keys and transfer the funds?
To solve the issue " not secured by seed phrase" ?

**Comment by izzycsy** [comment]
Hi @Di-rt , glad the new version worked for you. The `Warning: Address not saved by seed phrase` is still under investigation. 

What you suggested might be worth a shot, do understand that it’s your responsibility to keep yours funds safe. Following with what you mentioned, you could try it. 

Reminder to do `backup wallet` & save your mnemonic seed. In the event that you need to Restore Wallet via mnemonic seed and some random bug occurs, you could then `import` backup to get back to where you left off.

**Comment by izzycsy** [comment]
Hi @ph115 , thanks for your feedback, could you try `Reindex Option` in Settings?

**Comment by ph115** [comment]
> Hi @ph115 , thanks for your feedback, could you try `Reindex Option` in Settings?

Unfortunately not, as the settings symbol also disappeared. Only the main menu bar is visible (Wallet|Edit|Logs|Help). This afternoon i try to de-install the app and run a new installation from scratch. Maybe that help. I'll keep you in the loop.

**Comment by izzycsy** [comment]
Hi @Di-rt @ph115 	, update v2.1.7 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
