### ISSUE TITLE
insufficent UTXO

### ISSUE THREAD

**Issue by JoergHoffmann** [DeFiCh/app#222]
I cant transfer DFI to my Cake wallet?. Seems a big problem since mid December. How can I help?

**Comment by JoergHoffmann** [comment]
![image](https://user-images.githubusercontent.com/18046932/104094273-22f23900-5290-11eb-815b-c5a3609e359e.png)

**Comment by izzycsy** [comment]
Hi @JoergHoffmann , thanks for the screenshot. Please give us time to investigate this issue.
