### ISSUE TITLE
Sending Token not possible: not enough balance

### ISSUE THREAD

**Issue by DanielZirkel** [DeFiCh/app#227]
Hi, 

I am using the Defi-App version 2.1.5 and want to send DGT-Token from my wallet to another address.
After some attempts I am still facing the error message: 
**Not enough balance on wallet accounts, call utxostoaccount to increase it.**

![2021-01-05_12h41_05](https://user-images.githubusercontent.com/68841661/103642527-89571e80-4f53-11eb-94a7-1e570d70ab2f.jpg)

What I have done so far:
- I also did a complete new reindex of my wallet without any problem
- Sending DFI and USDT-Token on the address holding the DGT-Token: no problems, they arrived
![2021-01-05_12h44_52](https://user-images.githubusercontent.com/68841661/103642690-d1764100-4f53-11eb-9076-5c841eb13b27.jpg)
![2021-01-05_12h45_09](https://user-images.githubusercontent.com/68841661/103642702-da671280-4f53-11eb-977e-147c4affdd56.jpg)
- try to use utxostoaccount for DGT-Token
![2021-01-05_12h45_34](https://user-images.githubusercontent.com/68841661/103642746-e94dc500-4f53-11eb-8d9f-1a5bba02ac22.jpg)
- used utxostoaccount for 1 DFI (changing coin to token) on the address holding DGT
![2021-01-05_12h49_49](https://user-images.githubusercontent.com/68841661/103643179-87da2600-4f54-11eb-9a40-54f8085ba553.jpg)

Nothing changed the error message.
What should I do with the utxostoaccount-Command to solve the error message? I have no further idea.

here is also the App Log-File
[AppLog20210105.log](https://github.com/DeFiCh/app/files/5769959/AppLog20210105.log)

**Comment by bastiansc91** [comment]
Exactly the same problem happend to me with another token. I can not send this to another address.
The send button always is disabled. Dont make a difference whether I try to send 1 or 1000000 of that token.

**Comment by mikej289** [comment]
facing the same issue for ETH & USDT now when I want to withdraw it to Cake.

**Comment by RobinTorque** [comment]
I have exactly the same problem. I can no longer send BTC, DGT and JULE.

**Comment by Adrian-source-cmd** [comment]
I have the same problem it’s impossible to send ETH.

**Comment by izzycsy** [comment]
Hi @DanielZirkel , thanks for your detailed feedback and app logs.

Hi @bastiansc91 @mikej289 @RobinTorque @Adrian-source-cmd , thanks for your feedback as well. Kindly send your app log, binary log & app config if possible. This will provide more insight for the investigation.

The team is looking into the issue, please give us time to investigate this, thank you for your understanding.

**Comment by izzycsy** [comment]
Hi @DanielZirkel @bastiansc91 @mikej289 @RobinTorque @Adrian-source-cmd , there could be a temporary solution to this. It could be that you've too little DFI UTXOs balance (min. 0.05DFI) — which is required to perform swap and other functions. You could try to convert a little DFI tokens to DFI UTXOs, and see if it works. Attached a link that might help you.  <https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/>

**Comment by DanielZirkel** [comment]
Hi @izzycsy 
In my case there was enough DFI UTXOs.
I also tried to deposit 3 DFI UTXOs explicitly on the address holding the DGT-token (see my first screenshot with listunspent command). This also didn't solve the issue

**Comment by izzycsy** [comment]
Hi @DanielZirkel , could you type this in your CLI and let me know the output:

`getbalance` — utxo DFI `getokenbalances` — DFI  The sum of utxo DFI & DFI would be the total DFI.

**Comment by DanielZirkel** [comment]
Hi @izzycsy 

I still cannot send the DGT Token. Till Tuesday my account balance has changed a little bit. Here is the result of your posted commands.
![2021-01-07_07h20_29](https://user-images.githubusercontent.com/68841661/103858611-f3d59f00-50b8-11eb-8235-016c1d965a7f.jpg)
You see, I have more than 6 utxo DFI.

**Comment by izzycsy** [comment]
Hi @DanielZirkel , could you try` refreshing UTXOs` in Settings, and let me know the result, thank you.

<img width="775" alt="Settings   Refresh UTXOs" src="https://user-images.githubusercontent.com/65014479/103872839-e399e000-5109-11eb-8ee8-468a5e09da10.png">

**Comment by mikej289** [comment]
I am facing the same issue.
getbalance - 7+k
gettokenbalances - 100+

Yet I am also getting this error when trying to send out USDT / ETH. 

Trying now to Refresh UTXOS as well.

**Comment by mikej289** [comment]
In my case, the approach of Refreshing UTXOs did not work. I am still getting the same error.

**Comment by DanielZirkel** [comment]
Hi @izzycsy 

Sorry, I forgot to mentioned it in the issue description:
I also tried this and it didn't help.
I have done it now another time, but also with no effect. The error remains.

**Comment by izzycsy** [comment]
Hi @DanielZirkel , noted. Could you try the following: 

• send 1 DFI to `dJhAU8imrHpu2tHJ5xhUN7e7dfnASFTFcc`
• Is `dJhAU8imrHpu2tHJ5xhUN7e7dfnASFTFcc` listed in your **Receive Address**?

**Comment by izzycsy** [comment]
Hi @mikej289 , thanks for trying too. The team is addressing the issue.

**Comment by DanielZirkel** [comment]
Hi @izzycsy 

Now, I send 1 DFI to my address. Here is the Tx-Hash
7394f29e5ea7d385950b5743c73c565bcd21034dba0dbd67334aa871ac068e0f
And I checked it in the console
![image](https://user-images.githubusercontent.com/68841661/103990308-45e9f380-5191-11eb-859b-15c1a0fc9761.png)
But this also had no effect on sendig the token, still got the error.

Yes, the address is listed under received address. It was the first address of this wallet.
![image](https://user-images.githubusercontent.com/68841661/103989753-78dfb780-5190-11eb-9a0f-4fef5442603e.png)

**Comment by izzycsy** [comment]
Hi @DanielZirkel , thank you. Please give us time to investigate this.

**Comment by Workoholic-Jap** [comment]
Problem still not solved.
trying to send BTC to Cake, but still not enough balance, although there are enough DFI coins and BTC in getblances
any solution out there? any suggestions?

**Comment by maaze19** [comment]
Today I had the same problem when I called `defi-cli.exe sendtokenstoaddress '{}' '{"dXW...":"3@DFI"}'`. Before I moved all my tokens to one address (begins with 8...), so it worked just before.
Now I everytime get the error message:
```
error code: -32600
error message:
Not enough balance on wallet accounts, call utxostoaccount to increase it.
```

**What helped was to manually defining the inputs**
`defi-cli.exe sendtokenstoaddress '{"d3F...":"3@DFI"}' '{"dXW...":"3@DFI"}'`.

So I digged a little bit in the source code and found that defich/ain looks by themselves for valid inputs here: https://github.com/DeFiCh/ain/blob/4338a5c076fc8c7a1086a4cebe96ba4785289aa7/src/masternodes/mn_rpc.cpp#L3909

But only if I don't specifiy inputs by myself. For me it looks like the search for valid inputs has a bug. Maybe someone who is better in C++ can check the code which is autoselecting inputs https://github.com/DeFiCh/ain/blob/4338a5c076fc8c7a1086a4cebe96ba4785289aa7/src/masternodes/mn_rpc.cpp#L3903-L3915

In the meantime a workaround for the app could be to specify the inputs explicity.

**Comment by mikej289** [comment]
I am also not an expert, but it seems like you wanted to send DFI to another address. This error is already known and there is already a work around for that. We are having problems sending out BTC, USDT and other tokens other than DFI where the 'accounttoutxos' workaround is not working.

**Comment by maaze19** [comment]
> I am also not an expert, but it seems like you wanted to send DFI to another address. This error is already known and there is already a work around for that. We are having problems sending out BTC, USDT and other tokens other than DFI where the 'accounttoutxos' workaround is not working.

This behaviour is related to all tokens. I clearly showed that it's possible to send tokens, when you specify the inputs by yourself when using `sendtokenstoaddress`.
Maybe a little bit misleading that I used DFI in my example. Just replace it with any other token of your choice.

**Comment by DanielZirkel** [comment]
Sending the DGT token worked in my case, if you specify the source address explicitly.
I wrote a reddit article how to do it in the console
https://www.reddit.com/r/defiblockchain/comments/kvsw4l/stepbystep_workaround_sending_btc_eth_usdt_and/

**Comment by DanielZirkel** [comment]
@izzycsy please, have a look on the analysis of @maaze19 
In my reddit post I am showing the workaround for this issue.

**Comment by izzycsy** [comment]
Hi @DanielZirkel @bastiansc91 @mikej289 @RobinTorque @Adrian-source-cmd @Workoholic-Jap @maaze19 , update v2.1.7 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you!
