### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by lukefue** [DeFiCh/app#230]
app 2.1.5 works fine while syncronizing but inthe last 0.05% the screen turns white. Here are the app logs and a screen shot.
![image](https://user-images.githubusercontent.com/33607469/103746382-4e132900-5001-11eb-827c-3b2445269b24.png)
[app logs white screen.log](https://github.com/DeFiCh/app/files/5774632/app.logs.white.screen.log)

**Comment by izzycsy** [comment]
Hi @lukefue , thanks for the feedback, app logs are well received. Please give us time to investigate this issue.

**Comment by lukefue** [comment]
It works now ! Really fast solution, thanks to the team ! @izzycsy
