### ISSUE TITLE
Windows10: Unable to right-click

### ISSUE THREAD

**Issue by Fragharvester** [DeFiCh/app#237]
Hi,

at the Console (defiwallet 2.1.5) under Windows 10 (Build 20H2) I recognized following Problem.

I can use the Console by write directly but if it comes to copy paste commands or for example the dfi address there i cant right click for context menue so I use the keyboard (cmd +v command) but this also only works with these steps.

1. mouse right click in console (pink curser disappears)
2. cmd+v to paste
3. mouse left click (pink curser appears again)
4. enter to execute

I hope this helps

br Andi

**Comment by izzycsy** [comment]
Hi @Fragharvester , thanks for your feedback. Please give the team time to readjust this setting and enable `right-click`.

**Comment by luckythai** [comment]
Hi @Fragharvester , windows commants worked outside the app.
In the app to copy, paste, etc. use the functions for the console in the Edit menu.

![menue](https://user-images.githubusercontent.com/77095933/104040661-876ab500-520a-11eb-85fe-bab102577ea5.JPG)

**Comment by izzycsy** [comment]
Hi @Fragharvester , if this feature is not available in the current version, it might be pushed to the next as issues are dealt with accordingly to urgency. However rest assured that your feedback has been sent to the team. Thank you for your feedback.
