### ISSUE TITLE
Synchronizing stops

### ISSUE THREAD

**Issue by DeFiDirk** [DeFiCh/app#24]
DeFi wallet 2.0.0 stops synchronizing at block 423940.

[app_logs.zip](https://github.com/DeFiCh/app/files/5542625/app_logs.zip)

**Comment by bvbfan** [comment]
What happen afterwards? Did you able to continue when you restart the app or it stop work at all? Did you know where is located application directory called `defi` do you have space on that device?

**Comment by DeFiDirk** [comment]
All other functions work well, just no progress in synchronizing. Defi data path is in user path, 17 GB available.

**Comment by DeFiDirk** [comment]
I uninstalled the DeFi app, deleted all folder in the user path and reinstalled the app completely new.
Now it does not synchronize at all any more. It just stay at block 0. #

**Comment by DeFiDirk** [comment]
Which TCP and UDP ports have to be opened?

**Comment by izzycsy** [comment]
Hi @DeFiDirk , thanks for your feedback. The synchronising issue has been fixed, kindly install the latest version of the app.
<https://github.com/DeFiCh/app/releases/tag/v2.1.1>

**Comment by DeFiDirk** [comment]
Thank you!!!
