### ISSUE TITLE
txn-mempool-conflict (code 18)

### ISSUE THREAD

**Issue by lukefue** [DeFiCh/app#240]
When I try to add liquidity to the btc pool this error occurs. 
![image](https://user-images.githubusercontent.com/33607469/104004233-c87bae80-51a3-11eb-9c6b-7be7335feef0.png)

Ether pool works fine .

**Comment by lukefue** [comment]
already worked!

**Comment by rang3r72** [comment]
What was the solution? I have the same issue.

**Comment by Falkch** [comment]
I have the same problem. I need at least 2 attempts each time
