### ISSUE TITLE
Add Liquidity Error / txn-mempool-conflict (code 18)

### ISSUE THREAD

**Issue by booky84** [DeFiCh/app#241]
If i want to add Liquidity to a pool, i get this error message. Version 2.1.6 on Windows 10 64Bit.
![Unbenannt](https://user-images.githubusercontent.com/76788848/104010010-2b714380-51ac-11eb-8255-d05569ff9181.png)

[logs.zip](https://github.com/DeFiCh/app/files/5786889/logs.zip)

Bin_log is too big to provide here. Any other idea?

**Comment by booky84** [comment]
after i just tried it again, it worked and the error did not occur anymore.

**Comment by Falkch** [comment]
I have the same problem, for 2 days I have not been able to withdraw or add DFI to the LM. What should I do

**Comment by Falkch** [comment]
I was able to send small quantities a couple of times. In between, the error message came back. LM worked recently too - but I expect the error to reappear.

**Comment by booky84** [comment]
The problem occurs again with me now. I would open the issue again.

**Comment by izzycsy** [comment]
Hi @booky84 , thanks for your feedback, logs well received, please give the team time to investigate this issue. 

Hi @Falkch , thanks for your feedback. Kindly send your app logs. If possible, do attach screenshots / screen recordings. This will provide more insight for the investigation. Thank you.

**Comment by izzycsy** [comment]
Hi @booky84 @Falkch , it could be that you've too little DFI UTXOs balance (min. 0.05DFI) — which is required to perform swap and other functions. Try sending yourself 1 DFI and try the function again. If it still persist, please provide your app logs & screenshot.

**Comment by schollerbernhard** [comment]
got the exact same problem. using Version 2.1.7 (installed today).
If adding the funds would work I would still have 11 DFI in my wallet.
If I try to add less funds, still the same error message.
[app logs.zip](https://github.com/DeFiCh/app/files/5811113/app.logs.zip)

**Comment by champs2k** [comment]
Error CODE 18 
Here is the Help for you! 
Hi guys, it worked like this for me!!!!!! 
Got the same error message.  
1. send 1. DFi to Cake / Dfi address.  
2. Wait 5 minutes 
3. Now you can change your dfi-eth-btc in LM

:)

**Comment by izzycsy** [comment]
@schollerbernhard , thanks for your feedback. Could you check your balance via CLI using these commands: 

`getbalance` — utxo DFI
`gettokenbalances` — DFI 

 The sum of utxo DFI & DFI would be your total tokens.

**Comment by schollerbernhard** [comment]
> @schollerbernhard , thanks for your feedback. Could you check your balance via CLI using these commands:
> 
> `getbalance` — utxo DFI
> `gettokenbalances` — DFI 
> 
>  The sum of utxo DFI & DFI would be your total tokens.



> @schollerbernhard , thanks for your feedback. Could you check your balance via CLI using these commands:
> 
> `getbalance` — utxo DFI
> `gettokenbalances` — DFI 
> 
>  The sum of utxo DFI & DFI would be your total tokens.

OK, I can get the sum, but how do I solve my problem of the error message when I want to add liquidity? Version 2.1.8 does not solve my problem. What commands should I try in the command line?

**Comment by izzycsy** [comment]
Hi @schollerbernhard 	, update v2.1.9 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, please provide new information (include screenshots) and app logs. Thank you.

**Comment by booky84** [comment]
> 
> 
> Hi @booky84 @Falkch @schollerbernhard , update v2.1.9 is out https://defichain.com/downloads/.
> Do give a thumbs up to this comment if your issue has been resolved, otherwise, please provide new information (include screenshots) and app logs. Thank you.

It did not occur again and can be closed from my side. Thank you!

**Comment by schollerbernhard** [comment]
After installing the new version and refreshing the UTXO in the settings of the defi-app, adding liquidy worked.
The "old" wallets are still not there, but all the funds are on the new address, so should be OK.

**Comment by izzycsy** [comment]
Hi @schollerbernhard , you could try to convert a little DFI tokens to DFI UTXOs, and see if it works. Attached a link that might help you.  <https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/>

**Comment by izzycsy** [comment]
Hi @booky84 , great! I'll _close with comment_ in the mean time. If there's new information that occurred for error: txn-memepool-conflict (code 18), you may reopen this issue.

**Comment by schollerbernhard** [comment]
Perfect. Thank you for you help!!!

**Comment by RomanShumkov** [comment]
@izzycsy, I'm getting the same error when trying to add liquidity, while tokenA and tokenB are on different addresses.
After sending tokenA to the tokenB address, adding liquidity works fine.

macOS app 2.1.10
