### ISSUE TITLE
No Wallet ( missing address ? )

### ISSUE THREAD

**Issue by Kampflama** [DeFiCh/app#242]
Because i had some previous problems with the defi app i reinstalled the new version 2.1.6 and typed in my previous mnemonic seed so far so good. But i cannot access my wallet. I get the same window : New Wallet or Mnemonic Seed and if i click on the liquidity button i see my share and if i want to withdraw liquidity i can see how much i collected but no address to send i shown... 

[defi.zip](https://github.com/DeFiCh/app/files/5787917/defi.zip)

**Comment by Kampflama** [comment]
![liquid](https://user-images.githubusercontent.com/77161613/104032755-e6123d80-51ce-11eb-8f42-7a5ec461f94d.PNG)
![wallet](https://user-images.githubusercontent.com/77161613/104032771-eb6f8800-51ce-11eb-8168-c30fc80fe207.PNG)
![Unbenannt](https://user-images.githubusercontent.com/77161613/104032776-ee6a7880-51ce-11eb-887f-8e9f2e6b7b15.PNG)

**Comment by amainz** [comment]
Hi @Kampflama,

Try to go to "Wallet" and add a new address ("erhalten"). Those addresses are not re-created after you put your wallet in again. Then the empty address problem should be gone.

I had the same on another issue.

Kind regards,
Andre

**Comment by Kampflama** [comment]
I dont have the option to add a new address

**Comment by amainz** [comment]
On DFI wallet top right corner

![image](https://user-images.githubusercontent.com/29411467/104088945-d3e5dd00-526a-11eb-8e20-e19f248ca789.png)

**Comment by Kampflama** [comment]
Yes but im stuck as you can see in the pictures above. I already restored the wallet ´, i can see how much liquidity i added put i cant see my wallet and if i click on new wallet or restore seed i get the message that i have to restart, over and over again

**Comment by Kampflama** [comment]
This is the message i get in the wallet window when i want to restore.

Already have this key (either as an HD seed or as a loose private key)

**Comment by Kampflama** [comment]
Now it works somehow ??? 

But when i want to withdraw i get this message : 
Got error in sendToAddress: Not enough balance on wallet accounts, call utxostoaccount to increase it.
