### ISSUE TITLE
Wallet empty after complete 2.1.6 re-install

### ISSUE THREAD

**Issue by sushihater** [DeFiCh/app#243]
Problem:
I opened the App today and saw the update. Clicked on the botton and my PC crashed. After trying several times to sync the App, I went to install the App from scratch. 

After the installation of 2.1.6 was complete, I wnt to restore the wallet. 

Final result: App synced, wallet restored, but the wallet shows only a friction of what I had there before. Only a few DFI left, no active liquidity pools :(

Need help if there is a chance

**Comment by jonho79** [comment]
This just happened to me as well.  I literally have 0.05 DFI in my wallet and nothing else.  I had much more DFI as well as ETH, BTC and USDT in addition 3 liquidity pools I was participating in.

**Comment by jonho79** [comment]
Additionally, the wallet is no longer encrypted but not sure after a seed restore if it losses it's encryption.    What's interesting is when I click on DFI wallet it has some of my transactions from a few days back so seems as if there's still some connection to what the wallet should be.

**Comment by jonho79** [comment]
I reset again and restarted the app, and looks like everything is back to normal.   Can't say I wasn't a little worried but relieved the everything is still there.  I'm relatively new to the Defi space so maybe this is normal and I'll get used to it.

**Comment by salomonkarsten** [comment]
I had the same issue only after a UTXO rescan was able to see my coins. But the previous adresses got lost as well as the Transaction history not properly updating. In future it is better to do a wallet backup and not only recover from the 24 words seed.

**Comment by izzycsy** [comment]
Hi @sushihater , thanks for your feedback. Could you describe your user flow more (screenshots / screen recordings are encouraged). Do you by any chance `backup wallet` before you deleted v2.1.5 and installed v2.1.6?

Thanks for the help @jonho79 @salomonkarsten . As they mentioned, it would be good habit to do regular `backup wallet` between each update. In the event that you need to Restore Wallet via mnemonic seed and some random bug occurs, you could then `import` backup to get back to where you left off. 

Did you try `Refresh UTXOs` in Settings?

**Comment by izzycsy** [comment]
Hi @sushihater @jonho79 @salomonkarsten , update v2.1.9 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
