### ISSUE TITLE
I lost my DFI address after upgrade to ver 2.1.6

### ISSUE THREAD

**Issue by kenang68** [DeFiCh/app#244]
Dear Sir /Madam,

When I upgrade to version 2.1.6, I have use my seed phrase and backup wallet to recover my account. My DFI token and my liquidity is still there. However I realize that my DFI address is done.

I also realize that the receiving address is not there when I try to add liquidity.

Can you advise how I can get it back? I have a record of my previous DFI address and the receiving address for the liquidity pool reward.

![Receive address blank for adding liquidity](https://user-images.githubusercontent.com/72757945/104084451-0818c800-5282-11eb-994a-919156bcd313.jpg)

![Receive address blank for adding liquidity](https://user-images.githubusercontent.com/72757945/104084550-fb48a400-5282-11eb-861d-d809677d3a8e.jpg)

Thanks.

Regards,
Ken

**Comment by kenang68** [comment]
![DFI address disappear](https://user-images.githubusercontent.com/72757945/104084564-2206da80-5283-11eb-9323-8f90f77d48eb.jpg)

Above the wallet address disappear. Thanks.

**Comment by uzyn** [comment]
@kenang68 From Telegram, it seems that you have managed to solve this issue by closing and restarting the wallet. I'm closing this issue, if it still remains an issue, please re-open with more details
