### ISSUE TITLE
Error when adding to liquidity pool

### ISSUE THREAD

**Issue by kenang68** [DeFiCh/app#247]
Dear Sir / Madam,

I just upgrade to version 2.1.6 and has recovered account by using seed phrase and backup wallet.

As the old DFI address is gone so I create a new address. However I got an error when adding liquiding of the BTC/DFI pair, the error code is "txn-mempool-conflict (code 18).

Please see error code below:

![210110 Add Liquidity Error](https://user-images.githubusercontent.com/72757945/104105301-14377080-52e8-11eb-9ada-4d12be55d6ed.jpg)
[Binary Apps.zip](https://github.com/DeFiCh/app/files/5791549/Binary.Apps.zip)

**Comment by kenang68** [comment]
Dear Sir / Madam,

You can close the issue.

I try adding liquidity for both ETH / DFI pair and USDT / DFI pair. They are successful. After that I try again on BTC / DFI pair and it works. Thanks.

**Comment by lraphael** [comment]
I have the same issue with the same program version. If I try it several times with a smaller number, it works. I activated the option "UTXo reload after save" and after that it worked again.

**Comment by izzycsy** [comment]
Hi @kenang68 , glad you managed to figure it out. Thanks for your feedback, I'll proceed to close this issue as mentioned.
