### ISSUE TITLE
Wallet does not show Liquidity Pool, i cant remove liquidity. 

### ISSUE THREAD

**Issue by Jugeen23** [DeFiCh/app#248]
After reinstall DeFi-Chain wallet on another PC and entering 24 words of backup phrase my liquidity pool stake shown under "Liquidity.". So a cannot remove liquidity. No used adresses are shown Also i had more than 8.x DFI in my wallet before reinstall.. Now i have 4.x.

**Comment by mrblueSG** [comment]
Same here.. I did a re-install and restore using "Import Wallet"... Not able to see my liquidty pool stake... Any help will be greatly appreciated.

**Comment by izzycsy** [comment]
Hi @Jugeen23 @mrblueSG 	, thanks for your feedback. Could you describe your user flow more (screenshots / screen recordings are encouraged). Also, kindly send your app logs. This will provide more insight for the investigation. Thank you.  In the mean time, kindly install the latest version v2.1.6 of the app <https://defichain.com/downloads/>.

**Comment by izzycsy** [comment]
HI @Jugeen23 @mrblueSG 	, update v2.1.10 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
