### ISSUE TITLE
withdrawl error with bitcoin

### ISSUE THREAD

**Issue by kryssylynn** [DeFiCh/app#249]
hello-

very very new to defi and dex

sold some shares of defi and sent to dex. I was able to swap them for bitcoin. and now they show in my wallet. however when amount and address is inputted the continue stays gray.

**Comment by kryssylynn** [comment]
for some reason i cannot move any of my assets from my wallet.  when i put in the ammount and the proper address the continue  button does not light up to send   can anyone help with this? . please

**Comment by izzycsy** [comment]
Hi @kryssylynn , thanks for your feedback, regarding this issue, I'll link you to <https://github.com/DeFiCh/app/issues/195> which we can further discuss on the problem. We would like to keep same issues in one thread. 

In <<https://github.com/DeFiCh/app/issues/195>, could you describe your user flow more (screenshots / screen recordings are encouraged). Also, kindly send your app logs. This will provide more insight for the investigation. Thank you.
