### ISSUE TITLE
Synchronizing stops at 99-99.6%

### ISSUE THREAD

**Issue by Landi01** [DeFiCh/app#25]
Always while opening the Defi-App, the synchronisation stopps at approximately 99 to 99.6 %. I already did close the app and opened again, but it didn't work. See screenshot attached. Should I delete the Defi-App complitely and instal again or do you have any other solutions for this issue?
Thanks a lot!

<img width="1020" alt="Bildschirmfoto 2020-11-16 um 00 29 48" src="https://user-images.githubusercontent.com/74515031/99199950-d7954000-27a2-11eb-9991-519280671961.png">

**Comment by izzycsy** [comment]
Hi @Landi01 , the synchronising issue has been fixed, kindly install the latest version of the app. 
<https://github.com/DeFiCh/app/releases/tag/v2.1.1>

**Comment by wolfpirker** [comment]
Hello,
I had the same issue two times in a row with version 2.1.3. But there was also a popup in my case, I already closed it, but I think it said "Node not connected". Might try it again tomorrow.

I started the app under Linux from command line, here parts of the output:

> 22:22:50.597 › Node started
> Node started
> 23:22:56.599 › Error occurred while running binary with code: null
> Error occurred while running binary with code: null
> 23:24:01.544 › Error: Network Error
>     at e.exports (file:///js/zchunk-2.4c5e40ac.js:51:207430)
>     at XMLHttpRequest.h.onerror (file:///js/zchunk-2.4c5e40ac.js:51:206395)
> 23:24:01.557 › Error: Network Error
>     at e.exports (file:///js/zchunk-2.4c5e40ac.js:51:207430)
>     at XMLHttpRequest.h.onerror (file:///js/zchunk-2.4c5e40ac.js:51:206395)
> ...
> (defi-app:25664): libnotify-WARNING **: 23:32:03.518: Failed to connect to proxy
> 
> (defi-app:25664): libnotify-WARNING **: 23:32:03.522: Failed to connect to proxy
> 23:33:18.053 › {}

Is my issue a different one, should I start a new issue?

**Comment by izzycsy** [comment]
Hi @wolfpirker , could you attach you app log & binary log please? This would help the team in investigating the issue. Thank you.

<img width="286" alt="App log" src="https://user-images.githubusercontent.com/65014479/102980400-7b140600-4542-11eb-82e0-bab9fe308c7d.png">

**Comment by wolfpirker** [comment]
Hallo izzycsy, 
sure, here are logs files and also the output of the top command: [https://file.io/7ZOjMOhBZqOI](url)
When the synchronization was nearly complete - at around 99.5% - there is a process related to the app which uses much more than 90% at the end (defi-init). I tried it two times today. The first time, I had to reset my linux system, it was frozen. The second time I closed the process, before it was too unresponsive.

**Comment by izzycsy** [comment]
Hallo @wolfpirker , please refer to the screen shot on how to upload your app logs. The link that you provided is empty. 
<img width="511" alt="Compress" src="https://user-images.githubusercontent.com/65014479/103078269-761b8900-460c-11eb-869a-d83879f0eb4b.png">
<img width="671" alt="Drag and drop" src="https://user-images.githubusercontent.com/65014479/103078285-7ddb2d80-460c-11eb-8430-a31a39751618.png">

Also, we've released a new update v2.1.4. Hope this helps! 
<https://github.com/DeFiCh/app/releases/tag/v2.1.4>

**Comment by wolfpirker** [comment]
Hallo @izzycsy ,
the binary log is quite big, even zipped it is bigger than 10 MB, so I upload it to file.io again. 
Just now I tested in the version of 2.1.4 DeFi App. It synchronized until around 99.97%. After this percentage was reached and it almost froze my system, after some more minutes it brought a popup "Node disconnected" (actually "Verbindung mit Node ist getrennt", German). When the popup appeared, the linux system was not slowed down dramatically anymore.

The link above - it would work if you copy and paste it in the url field. I inserted it not correctly.
[File.io](https://file.io/ax4C3eyTDrsA)

**Comment by izzycsy** [comment]
Hi @wolfpirker , well received, thank you. Please give us time to investigate this.

**Comment by izzycsy** [comment]
Hi @wolfpirker , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue w new information (include screenshots) and your app logs, and we’ll investigate. Thank you.
