### ISSUE TITLE
automatically swap from token to coin

### ISSUE THREAD

**Issue by krishna-83** [DeFiCh/app#250]
Hello, I got an error message in the DFI-APP all day today, which I haven't had since the installation. Despite restarting the computer and neustadt the app, the error could not be resolved. I was then helped in the Telegram group. I had to convert coins into tokens via the console. Actually, it should work independently by now, but obviously it didn't work for me - you can now get my log files here to fix the error. Many Thanks
[app logs.zip](https://github.com/DeFiCh/app/files/5791958/app.logs.zip)
[app logs.zip](https://github.com/DeFiCh/app/files/5791961/app.logs.zip)

**Comment by izzycsy** [comment]
Hi @krishna-83 , thanks for your feedback & logs. May I know the OS + version no. you're using? Could you describe your user flow more (screenshots / screen recordings are encouraged). This will provide more insight for the investigation. Thank you.  In the mean time, kindly install the latest version v2.1.6 of the app <https://defichain.com/downloads/>

**Comment by izzycsy** [comment]
Hi @krishna-83 , update v2.1.7 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may go to this link <https://github.com/DeFiCh/app/issues/211> and state your new information (include screenshots) and app logs. Thank you.
