### ISSUE TITLE
Can't exchange or add liquidity error message "Insufficient UTXOS to perform add liquidity"

### ISSUE THREAD

**Issue by MarsaXod** [DeFiCh/app#251]
Good day Defichain,

Having an issue as per subject, since last night. Can you please have a look at this?

**Comment by MarsaXod** [comment]
[defi_log_3.log](https://github.com/DeFiCh/app/files/5792497/defi_log_3.log)

**Comment by MarsaXod** [comment]
found the way to transfer tokens to coins following steps posted here.

**Comment by izzycsy** [comment]
Hi @MarsaXod , thanks for your feedback. Glad that you managed to fix it. Should you face the same issue, you may refer to this link <https://github.com/DeFiCh/app/issues/195>. I'll close this issue for now.
