### ISSUE TITLE
can not swap tokens to coins because no owner address is shown in the console. 

### ISSUE THREAD

**Issue by GsonAn** [DeFiCh/app#252]
via the command -listaccounts- the accounts are displayed, but without the owner address, which I need according to the instructions for the exchange to coins. please help. many thanks in advance

DeFi-App v2.1.6
On Windows 10 Pro

![no_owner_adress](https://user-images.githubusercontent.com/77214205/104123710-1384f580-534d-11eb-9d6a-f32ef4cdf9b1.JPG)

[Logs.zip](https://github.com/DeFiCh/app/files/5797690/Logs.zip)

**Comment by izzycsy** [comment]
Hi @GsonAn , thanks for your feedback & logs. May I know if you've a screenshot of the error you're facing?

**Comment by GsonAn** [comment]
it seems that my problem is solved by the new version. Thanks for the effort. Can be closed :-)
