### ISSUE TITLE
Wallet DFI: missing tx history 

### ISSUE THREAD

**Issue by luckythai** [DeFiCh/app#257]
Hi,
App version 2.1.6
With DFI, only the last three transactions are displayed for rewards. 
The amount is displayed correctly in the balance. The rewards also arrive. In the case of a transaction, it only shows the last 3 transactions and is overwritten with a new transaction.

At ETH it is displayed normally with no missing transactions.

[App-log-12012021.log](https://github.com/DeFiCh/app/files/5798220/App-log-12012021.log)
![dfi](https://user-images.githubusercontent.com/77095933/104235942-4f70a580-5488-11eb-851f-c0c23e19004c.PNG)
![eth](https://user-images.githubusercontent.com/77095933/104235966-58fa0d80-5488-11eb-852e-325a57a092a7.PNG)

**Comment by salomonkarsten** [comment]
I have a similar issue. I cannot see al transactions after restoring the wallet from 24 mnemoric key. further using the command: istaccounthistory mine {"maxBlockHeight":560002,"depth":0}    (evtl. other blockheights.... ) there seem to be different types available. Is there a explanation of the different types as e.g. external received DFI (that not belong to my addresses are shown as AccountToAccount which is confusing) there are several receive but this should be a reward I guess. the transaction fee should be commission but also seems to show up sometimes as sent sometimes as receive. Can someone clarify about the different types:

Rewards
sent
receive
AccountToAccount
Commission

**Comment by izzycsy** [comment]
Hi @luckythai , thanks for your feedback and logs. Please give us time to investigate this issue. Thank you.  Have you tried `Refresh UTXOs` in Settings? 

<img width="777" alt="Settings   Refresh UTXOs" src="https://user-images.githubusercontent.com/65014479/104470720-fbcf9a80-55f4-11eb-9a08-c2eed1a5a9c7.png">

**Comment by izzycsy** [comment]
Hi @salomonkarsten , thanks for your feedback. Regarding your transaction history not being displayed completely, you can try the `Refresh UTXOs` in Settings — as mentioned above. 

If your issue persist, kindly send your app logs. If possible, do attach screenshots / screen recordings. Thank you. 

Regarding your question on definition of different type of command, you could type `help` in the app's CLI or turn to Telegram and seek answers from the community. 

Telegram (EN): <https://t.me/defiblockchain> DeFiChain 
Telegram (DE): <https://t.me/defiblockchain_DE>

**Comment by Sunnyville1234** [comment]
I have exactly the same issue: no transactions are shown in the Transaction list since 27.12.2020, although there have been plenty! And another thing: I have two wallets. When I switch from one to the other (via 24 Words) I still see the same transactions! That can't be. I have tried clicking "Refresh UTXO" - after 16 hours it was still spinning (I have gigabit Internet).

My question: where are the program files stored for the MacOS Version of the app? Maybe I could delete all caches manually in the library and force the app to get all data again. Maybe then I could get access to my Transaction history (which I need soon for my taxes). Thanks!

A thought: will there be a way to export a CSV / excel file straight from the app at some time? Once that exists, I could really do LM & Staking from the app.

**Comment by salomonkarsten** [comment]
Hello sunny ville,

I also need transaction history for tax. 

@Sunnyville1234 do you know how to transfer the blocktime in listaccounthistory command to UTC date and time. Further lot of transaction types are strange. I made a excel script to transform the structure after copied in a textile to excel. But some state AccountToAccount transaction from cake also  type should be receive.....

I guess I will need to add a check if address belongs to me. I also need it for tax.

**Comment by Sunnyville1234** [comment]
Hey Salomon,

sadly, I have no idea how to convert the block time. 
The first issue that needs to be solved, in my opinion, is that all the data (all transactions) are shown within the app. 
Next, there should be a way to export these as CSV. Even if they are not perfectly formatted, that would be a start! Maybe the CSV can be formatted so that it can be identical to the new export worked on currently by the CAKE Team.

**Comment by luckythai** [comment]
hi izzycsy,
Unfortunately nothing has changed through refreshUTXO

But I think it can only be solved by deleting a specific file. Or by deleting the entire app and the folder by reinstalling it?
Now that the app works particularly well. The only mistake is the view of the rewards on DFI.

<img width="601" alt="DFI" src="https://user-images.githubusercontent.com/77095933/104654512-cc04bd80-56ee-11eb-85f4-0a4e15399623.PNG">
<img width="600" alt="dfi1 2 3" src="https://user-images.githubusercontent.com/77095933/104654684-184ffd80-56ef-11eb-902b-932523c91f2b.png">
<img width="574" alt="seite1" src="https://user-images.githubusercontent.com/77095933/104654822-564d2180-56ef-11eb-889d-39a9cf6d96d7.PNG">
<img width="553" alt="seite2" src="https://user-images.githubusercontent.com/77095933/104654784-446b7e80-56ef-11eb-90aa-54458c26d56d.PNG">
<img width="553" alt="seite2" src="https://user-images.githubusercontent.com/77095933/104654862-66fd9780-56ef-11eb-98c9-a71388c24994.PNG">
<img width="190" alt="Seite513" src="https://user-images.githubusercontent.com/77095933/104655097-be036c80-56ef-11eb-90c6-99387d410879.PNG">
<img width="602" alt="ETH" src="https://user-images.githubusercontent.com/77095933/104655113-c5c31100-56ef-11eb-84da-74619d737a92.PNG">
[App-log-12012021_2.log](https://github.com/DeFiCh/app/files/5817229/App-log-12012021_2.log)
[binary-log-12012021_2.log](https://github.com/DeFiCh/app/files/5817231/binary-log-12012021_2.log)

**Comment by luckythai** [comment]
hi izzycsy,
today update to 2.1.9
again refresh UTXO, nothing changed.

<img width="594" alt="Seite1-0" src="https://user-images.githubusercontent.com/77095933/104655641-919c2000-56f0-11eb-8149-6acc15e4622b.PNG">
<img width="588" alt="Seite1-1" src="https://user-images.githubusercontent.com/77095933/104655646-9365e380-56f0-11eb-87fa-0aacd4515adc.PNG">
[App-log.zip](https://github.com/DeFiCh/app/files/5817258/App-log.zip)
[App-log-15012021.log](https://github.com/DeFiCh/app/files/5817261/App-log-15012021.log)

**Comment by luckythai** [comment]
10 entries per page.
no new page will be created.
Made a new liquidity on the 12th and it only remains with three rewards since the 10th.

the display in the wallet is only incorrect for include rewards. And only at DFI.

**Comment by Sunnyville1234** [comment]
[applogs.log](https://github.com/DeFiCh/app/files/5819233/applogs.log)
attached you can find my app Log file. I tried the update UTXO - it ran for 1,5 days without finishing (I have very fast internet). Today, the transactions in both wallets end on the 27.12.2020. And, very interesting: both wallets show the exact same transaction history, which is impossible, as I never sent anything between the two! I really think that somewhere there is a cache that needs to be cleared. Where can I find this on OS X? Simply deleting and reinstalling the app does not solve the issue.

**Comment by izzycsy** [comment]
Hi @luckythai , thanks for the screenshots, can you send your logs again please, it looks like it's broken. Please give us time to investigate this. Thank you. 

<img width="462" alt="Screenshot 2021-01-15 at 5 37 26 PM" src="https://user-images.githubusercontent.com/65014479/104708221-60573a80-5758-11eb-94c0-0413b4ad68ee.png">

**Comment by izzycsy** [comment]
Hi @Sunnyville1234 , thanks for your feedback. I understand your issue. Please give us time to investigate, I advice you not to delete folders that you're unfamiliar with. Thank you for your patience.

**Comment by luckythai** [comment]
hi izzycsy, 
app.log from 12th and app.log from 15th
thank you for the effort

[App-log-12012021_2.log](https://github.com/DeFiCh/app/files/5819769/App-log-12012021_2.log)
[App-log-15012021.log](https://github.com/DeFiCh/app/files/5819774/App-log-15012021.log)

**Comment by izzycsy** [comment]
Hi @luckythai , well received, please give us time to investigate, it's not advisable to delete the app and not to install older version for your safety and security, our team is constantly working on improving the app and solving its issues. We regularly do releases, so if you are not in a big hurry I would suggest staying on the latest version and wait for a fix. Thank you for your patience.

**Comment by salomonkarsten** [comment]
Can you clarify the Difference in commission and rewards. Further for transactions how to see the fee in the history. All this info is needed for tax...

**Comment by izzycsy** [comment]
Hi @luckythai @salomonkarsten @Sunnyville1234 , update v2.1.10 is out <https://defichain.com/downloads/>. DFI missing transaction history is still under investigation, thank you for your patience. 

@salomonkarsten could you send me your logs again please? It redirects me to an error page. 

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/104808543-fc994400-5821-11eb-9375-87ede35663d0.png">

<img width="671" alt="3 Drag and drop" src="https://user-images.githubusercontent.com/65014479/104808545-002ccb00-5822-11eb-8ea2-12b56ef8a9ea.png">

Also here are the definitions to your question: 
**Sent:** tokens sent out of DeFi app
**Receive:** tokens received to DeFi app
**Account to account:** when you send a token to another address
**Commission:** the reward you receive when people swap on the pool that you’ve invested in
**Rewards:** DFI received from Liquidity Pool

**Comment by salomonkarsten** [comment]
@izzycsy THanks for your reply and the intention to work on this issue! I just had a look, I cannot see a swap just made. It appeard about 7 blocks later in the chain and is also visible using the command: listaccounthistory mine {"maxBlockHeight":576788,"depth":0} 

Nevertheless the app does not show this poolSwap type of transaction (by the way a type not stated above!) .

Further how to distinguish a AccountToAccount type from a receive. One needs to crosscheck if the address owner belongs to me?

Thanks in advance

**Comment by salomonkarsten** [comment]
@izzycsy 
[AppLog.log](https://github.com/DeFiCh/app/files/5824314/AppLog.log)
Attached the requested Applog

**Comment by izzycsy** [comment]
Hi @salomonkarsten , logs well received. Please give us time to investigate this issue.

You can further understand your account details using the command `listaccounts {} true true true`. To access all types of commands, type `help` in the CLI.

**Comment by salomonkarsten** [comment]
@izzycsy Hello dear Izzy,

I am using the listaccounts command already intensively. Thanks.  
As I understand USDT Transfers from an Extertal account will be displayed with the history command as AccountToAccount type and not as receive. So one alo needs to crosscheck if the address belongs to oneself . The actual history in the graphics interface definitively does not display everything.

Can you give advise how to transfer blocktime to UTC? I mean it should be given in the code already. Evtl. You can paste the code snipped here?

**Comment by izzycsy** [comment]
Hi @salomonkarsten , I see. Well, if I understand correctly, you're unable to transfer USDT as well? If so, there’s a temporary workaround for this, attached is the link that might help you <https://www.reddit.com/r/defiblockchain/comments/kvsw4l/stepbystep_workaround_sending_btc_eth_usdt_and/>.

For missing transaction history, the team is still investigating the issue. Thank you for your patience.

**Comment by salomonkarsten** [comment]
@izzycsy hello Bella,

is there a way to see the amount transaction fee from any specific transaction on command line? It would be great to add it to the history. As mentioned the main purpose of fiddling with history is tax reports for me!.

Thanks in advance.

**Comment by izzycsy** [comment]
Hi @salomonkarsten , I don't think that's available in the app at the moment, will feedback to the team.

**Comment by salomonkarsten** [comment]
@izzycsy Hello Izzy,
I tried to use the command in the apps command line interface:
listaccounthistory mine {"maxBlockHeight":535339,"depth":498,"limit":10000}

it will list if the depth and limit are not taken too high. The above stated is already on its limit  on a windows 10 with 20GB internal memoy. 
Afterwards I copy from the result to clipboard. just to highlight it needs 1 minute. after Copy it, I want to bring the curser back to enter the Clear command. and get the next set of approx 500 blocks.....
It needs another two minute just to be able to enter the command. To display "just" 10.000 entries it really is a long time. 
Also the instance seems to run 7 times. right after opening the app. 
screenshot of cpu usage to just bring the cursor back as well as applog. included.
![image](https://user-images.githubusercontent.com/77124114/104997130-5b7cda00-5a29-11eb-8a98-bdeac4cfac49.png)
[AppLog.log](https://github.com/DeFiCh/app/files/5834113/AppLog.log)

**Comment by izzycsy** [comment]
Hi @salomonkarsten , from your comment above, you may be facing the issue `Corrupted block database`, I'll link you to <https://github.com/DeFiCh/app/issues/138>, please copy and paste what your comment to the link provided. which we can further discuss on the problem. Logs well received. 

Let’s keep this thread related to what the original author opened. Thank you for your understanding.

**Comment by izzycsy** [comment]
Hi @luckythai @salomonkarsten @Sunnyville1234 @MrWild1412 , update v2.1.12 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send your app logs. Thank you. 

@Sunnyville1234 , after you've installed v2.1.12, and if transactions history that does not belong to you appear, try the `Reindex Option` in Settings. 

<img width="776" alt="Reindex option" src="https://user-images.githubusercontent.com/65014479/105637166-06b4e580-5ea7-11eb-9986-b64e3b2e38da.png">

**Comment by MrWild1412** [comment]
@izzycsy  Did the update and the reindex. Problem is still there [AppLog.zip](https://github.com/DeFiCh/app/files/5863103/AppLog.zip)

**Comment by luckythai** [comment]
Hi izzycsy, no, even with this app v2.1.12, no other page for rewards. Still limited to 3 rewards. Also reidex executed with no success.
I will install a new version on a VM to test whether the error occurs there. If so, it is not due to the database.
Is it possible to install the same wallet address on two machines?
is there a parameter for reindex when starting the app, or does it only work in the app with the switch?
<img width="597" alt="dfi" src="https://user-images.githubusercontent.com/77095933/105643309-af703e80-5ec1-11eb-8c72-55faf5ba2784.PNG">
[logs.zip](https://github.com/DeFiCh/app/files/5863161/logs.zip)

**Comment by izzycsy** [comment]
Hi @luckythai @MrWild1412 , thanks for the update, will continue to investigate, thank you.

**Comment by izzycsy** [comment]
Hi @luckythai @salomonkarsten @Sunnyville1234 @MrWild1412 , update v2.1.13 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.

**Comment by loric723** [comment]
Hi, why is the issue closed? I have the same problem since January with the rewards transaction history. Is this problem solved?

**Comment by luckythai** [comment]
My problem is still there. Only the last 3 rewards are displayed in the app under transactions. They are available when the data is exported. both in the app 2.1.17 / 2.3.0 / 2.3.1 / Wallet - 2.3.2

**Comment by izzycsy** [comment]
Hi @loric723 	, regarding the issue [`Missing tx history`](https://github.com/DeFiCh/app/issues/529), we can further discuss on the problem there. We would like to keep same issues in one thread. For your case, try to check the Include Rewards box. Thank you.

<img width="776" alt="Include reward tx" src="https://user-images.githubusercontent.com/65014479/112811193-6483ca80-90ae-11eb-9306-0a92148d3bf6.png">

**Comment by loric723** [comment]
Hi @izzycsy, yes I have checked the "Include reward transactions box" in the past and also reindex and Refresh Utxos. I follow now the issue https://github.com/DeFiCh/app/issues/529. Intersting is that the defichain portfolio App showing me all rewards.
