### ISSUE TITLE
Remove Liquidity error: Add-on auth TX failed: Insufficient funds

### ISSUE THREAD

**Issue by ideolog** [DeFiCh/app#258]
**The problem**
I am trying to remove 50% of liquidity from defichain. When I confirm the transaction I get "Add-on auth TX failed: Insufficient funds"

***How to reproduce***
1. Open defi-app_v2.1.6 on macOs Catalina 10.15.7
2. Click Liquidity in the left menu  
3. Click the minus icon to remove the selected liquidity pair
4. Select 50% and click Continue
5. Confirm the transaction
6. The green icon flashes for less than a second followed by a red icon with "Add-on auth TX failed: Insufficient funds"
But I have a lot of funds. 

****Other problems that might be related to the issue****

1. In DEX section I permanently see "Insufficient UTXOs to swap"
2. When I try to perform accounttoutxos X to {"X"} I get the same "Add-on auth TX failed: Insufficient funds" error

[app logs.zip](https://github.com/DeFiCh/app/files/5798496/app.logs.zip)

.....
Feel free to contact me for product management positions in #DEFI

**Comment by izzycsy** [comment]
Hi @ideolog , thanks for your feedback & app logs. Please give us time to investigate this issue.

**Comment by izzycsy** [comment]
Hi @JoergHoffmann , could you send your app logs and screenshot here please? Thank you. 

![image](https://user-images.githubusercontent.com/65014479/104382337-e57bfd00-5568-11eb-935c-8894f135fdd6.png)

![image](https://user-images.githubusercontent.com/65014479/104382361-ed3ba180-5568-11eb-9d70-c0be0e8460a8.png)

**Comment by ideolog** [comment]
I solved this problem by sending myself DFI from Cake. I could not even perform accounttoutxos command -my balance was something like 0.0001231 coins - very low.

**Comment by izzycsy** [comment]
Hi @ideolog , thanks for the update. Yes, the minimum DFI UTXOs balance is **0.05 DFI** — which is required to perform swap and other functions.

**Comment by izzycsy** [comment]
Hi @ideolog , update v2.1.7 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
