### ISSUE TITLE
[fetchBlockSyncInfo] Error: Invalid configuration (running dev mode)

### ISSUE THREAD

**Issue by hershkoy** [DeFiCh/app#259]
I am trying to run the app in dev according to instructions (for windows 10)

```
npm run init
npm run start:dev
```
It opened the react on localhost:5000 in the browser, and the electron app. Both seem to be stuck. 

The react is waiting to sync and there is `fetchBlockSyncInfo` error in the console (also there is an error about invalid configuration):

![image](https://user-images.githubusercontent.com/13259380/104243815-dbbfa000-5469-11eb-8b3a-e18c1aff9109.png)

The electron is stuck on loading screen, also with some error on blockchain issue:

![image](https://user-images.githubusercontent.com/13259380/104244329-dca50180-546a-11eb-9617-d0b745648765.png)

Any idea how to fix?

**Comment by hershkoy** [comment]
The invalid configuration is triggered because `rpcauth`, `rpcconnect`, `rpcport` are all empty in `webapp\src\utils\rpc-client.ts`. How do I configure these variables, and what should be their values?

**Comment by izzycsy** [comment]
Hi @hershkoy , you could be missing the setup of the required binary. You'll need to run `npm run pre:build:win` first, kindly refer to the README on DeFiChain's repo <https://github.com/DeFiCh/app>. Also, please get the latest code from master, some changes have been merged recently. 

<img width="381" alt="Screenshot 2021-01-20 at 10 34 00 PM" src="https://user-images.githubusercontent.com/65014479/105189344-d7813a00-5b6f-11eb-9401-972819b0da72.png">
