### ISSUE TITLE
I cannot send bitcoin "Not enough balance on wallet accounts, call utxostoaccount to increase it"

### ISSUE THREAD

**Issue by nordi6000** [DeFiCh/app#260]
I cannot send bitcoin to Cake from my DEX Wallet.

I exchanged USDT for DFI and then exchanged DFI for Bitcoin and then I want to send it to Cake for withdrawal. Now I get the error "Not enough balance on wallet accounts, call utxostoaccount to increase it"
![image](https://user-images.githubusercontent.com/49670309/104249357-8f755f80-546b-11eb-8121-8ae92228f711.png)

But I have enough credit on my wallet
![image](https://user-images.githubusercontent.com/49670309/104249466-c2b7ee80-546b-11eb-97e0-c5707bd83d1e.png)

**Comment by DanielZirkel** [comment]
The following workaround via console worked in my case
https://www.reddit.com/r/defiblockchain/comments/kvsw4l/stepbystep_workaround_sending_btc_eth_usdt_and/

**Comment by izzycsy** [comment]
Hi @nordi6000 , thanks for your feedback. Did @DanielZirkel 's tutorial work for you? For further discussion, kindly refer to <https://github.com/DeFiCh/app/issues/195>. I'll be closing in issue for now. Thank you.

**Comment by nordi6000** [comment]
@izzycsy , yes it works for me... Thanks Daniel for your quick help :-)
