### ISSUE TITLE
Unable to enter special characters in defi console - { and }

### ISSUE THREAD

**Issue by MartinSeeler** [DeFiCh/app#262]
I ran into the issue not having enough UTXO, so I was about to convert some DFI to real tokens by following the [Step by step guide](https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/).

However, when trying to enter `accounttoutxos address_from_above {"adress_from_above":"DFI_amount_to_convert@DFI"}` I noticed the bug that the `{` and `}` don't get rendered, which makes it impossible to convert it. Neither pasting nor entering the key is working.

I was able to work around this problem by running `defid` and using the cli, but I'm not sure if you can expect that every defichain user will be able to figure this out. As long as this problem with UTXOs is still ongoing and affecting this many people, you should at least assure that the users will be able to use the console.

**Comment by izzycsy** [comment]
Hi @MartinSeeler , thanks for your feedback. Regarding the issue `CLI: Does not accept [option] key characters, i.e. {}`, I'll link you to <https://github.com/DeFiCh/app/issues/112> which we can further discuss on the problem. We would like to keep same issues in one thread. Thank you.
