### ISSUE TITLE
BTC-DFI Liquidity Pool Balance Disappeared

### ISSUE THREAD

**Issue by KHecker0801** [DeFiCh/app#266]
Dear Support Team,

I am in big trouble because since yesterday evening at about 9.45 pm Western Europe Time I dont see any value in my BTC-DFI Liquidity Mining Pool in the DeFi App 2.16 anymore. There were more than 2 BTC and the equivalent part in DFI tokens in the pool – since that time I dont get any rewards of my BTC-DFI Pool Share either. I did not withdraw any BTC nor did I try to remove any liquidity of the pool, in the BTC wallet I dont see any withdraw transactions, only the deposits into the pool in December 2020. My DFI Addrees where I sended the BTC, DFI and Ether for Luqiudity Mining to is: dMQVYnRhRXfUBLeWJvwa1xqaqw5Z1gdz8L
Because we talk about a value of approximately 150000$ I am of course very concerned and hope for a postive solution soon. I also have an ETH-DFI Liquidity Mining Pool Share of 14.18 ETH and 7.564 DFI, this is shown correctly and is earning yield.  

What I did so far to solve the issue: I restored the folders DeFiBlockchain and def-app under appdata\roaming from a 4 day old backup, during the restore the BTC-Pool showed up but during the resync phase at 99.xx % the Pool disappeard again. 

I am very desperate, because the amount is about a 2 year salary and thougt for my retirement. Please let me know if I you need further information of me, beause the Binary Logfile was too large to upload, at the moment I send only the Applog. 

[AppLog.zip](https://github.com/DeFiCh/app/files/5801582/AppLog.zip)

**Comment by monstrobishi** [comment]
Hi @KHecker0801 thanks for reporting the issue. We are currently investigating and will update you our findings.

**Comment by uzyn** [comment]
@KHecker0801 Try going to console and type `getaddressinfo dMQVYnRhRXfUBLeWJvwa1xqaqw5Z1gdz8L`. Check that `isMine` is `true`, if it is, you're safe. Likely UI issues.

Replace the address with any addresses of your concern.

Also key thing is to ensure that your wallet.dat is available.

**Comment by KHecker0801** [comment]
Hi uzyn, thank you very much for your fast reply and your support, ismine shows true, this let me feel much better. Nevertheless I have some questions, first do I get rewards for the staked amount at the moment? Second, what are the next steps we can do so I have access to my funds again? I am so glad to read that noone has get access to my private key and moved the funds anywhere else - beliefe me, I had some really terrible hours. Your work made my day :-) and I hope we solve the rest soon.

**Comment by monstrobishi** [comment]
Hi @KHecker0801 ,

We've tracked down your BTC-DFI to this transaction:

https://explorer.defichain.io/#/DFI/mainnet/tx/394070a788391fdb152abca6ffb8cfcc3731a57d02e83293ec59be651d67fbde

Note that 289.6217991 BTC-DFI was transferred out yesterday. I decoded the information from the above transaction and was able to find the account that they were sent to.

They are currently sitting in this address: dLwamYmeQcZ2ER2gDsGcGLSaWp5t9sVoas

Here is the token listing for this address: https://dex.defichain.com/mainnet/address/dLwamYmeQcZ2ER2gDsGcGLSaWp5t9sVoas

Let us know if you have access to this address, you can do the same check as above with the new address.

**Comment by KHecker0801** [comment]
Der nonstrobishi, this sounds not very good. The Address dLwamYmeQcZ2ER2gDsGcGLSaWp5t9sVoas is my Bittrex Account where I send my daily rewards to change them to USDT. Because Bittrex does not support Liquidity Pools I cannot access the funds. I send you an image of my recent Bittrex Holdings, Withdraws and Deposits of this address. What can we do?

With this mail I send you my recent Bittrex DFI Deposit Address, Withdraws, Deposits and Balance
[SnippingTool.zip](https://github.com/DeFiCh/app/files/5803538/SnippingTool.zip)

**Comment by izzycsy** [comment]
Hi @KHecker0801 , if your funds are sent to your Bittrex; it's beyond our control, you'll have to contact Bittrex support and request them to send it back to you. In the future, when you perform swap / remove liquidity, do it on DeFi app before transferring out to other exchanges, also they need to support the token in order for the transfer to be successful. A good rule of thumb would be to transfer to and from the platform you started with. Thank you for your understanding.
