### ISSUE TITLE
Error after starting the defi App

### ISSUE THREAD

**Issue by bauxl** [DeFiCh/app#268]
Hi, since the update to version 2.1.6 I get the error "Unable to start blockchain" after starting the app. 

I hope someone can help me 

[log.log](https://github.com/DeFiCh/app/files/5803409/log.log)

**Comment by izzycsy** [comment]
Hi @bauxl , the team checked your log, it seems that your disk space is too low, could you check the Activity Monitor? Personally, mine shows this. 

<img width="733" alt="Activity Monitor" src="https://user-images.githubusercontent.com/65014479/104424971-0cfbb580-55bb-11eb-8340-bf92fea952e3.png">

If your error persist, please refer to this Issue <https://github.com/DeFiCh/app/issues/213>, as we would like to keep same issues in one thread. Thank you!
