### ISSUE TITLE
DFI funds disappeared after restoring

### ISSUE THREAD

**Issue by floxcgncgn** [DeFiCh/app#270]
Hello,..yestarday after restoring my wallet, 316 DFI are not displayed on my wallet, only 1,019. What could have happened?
i restored wallet over and over again, but my DFi are away. Who can help me?

thank u very much

**Comment by izzycsy** [comment]
Hi @floxcgncgn , thanks for your feedback, are you on v2.1.6? Did you try `Refresh UTXOs` option in Settings? 

![image](https://user-images.githubusercontent.com/65014479/104375917-1e16d900-555f-11eb-968f-1bc3b8064fb1.png)

To check your balance via the CLI, type the following commands:

`getbalance` — utxo DFI
`getokenbalances` — DFI  The sum of utxo DFI & DFI would be your total.

**Comment by izzycsy** [comment]
Hi @floxcgncgn , update v2.1.7 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
