### ISSUE TITLE
Beschädigte Block-Datenbank entdeckt!

### ISSUE THREAD

**Issue by Fabio129** [DeFiCh/app#276]
Seit einiger Zeit bekomme ich die Meldung "beschädigte Blockdatenbank" in meiner App angezeigt￼￼. Wenn ich die App neu starte kommt die selbe Meldung wieder ich habe nur zwei Möglichkeiten entweder die App zuschließen oder die App neu zu starten das bringt aber beides nichts. 
Leider sehr ärgerlich da ich auf nichts zugreifen kann. 

Anbei ein Bild von dem Problem. 

Ich hoffe Sie können mir helfen und das Problem lösen!

![image](https://user-images.githubusercontent.com/77388401/104444292-e0827200-5597-11eb-9dd2-99979658ad3c.jpeg)￼￼￼

**Comment by izzycsy** [comment]
Hallo @Fabio129 , thanks for your feedback. I'm unable to see your screenshot, could you send it again? ay I know the OS + version no. you're using? Also, kindly send your app logs. This will provide more insight for the investigation. Thank you.

**Comment by Fabio129** [comment]
Hello Bella, 

In advance thanks for your help. Under the text you will find the screenshot. 

I use my Computer with Windows 10 + currently the version 2.1.7

I hope you can help 😊

![image](https://user-images.githubusercontent.com/77388401/104478777-fbb6a700-55c2-11eb-986b-ec32f8a1cbcb.jpeg)

**Comment by Fabio129** [comment]
> Hallo @Fabio129 , thanks for your feedback. I'm unable to see your screenshot, could you send it again? ay I know the OS + version no. you're using? Also, kindly send your app logs. This will provide more insight for the investigation. Thank you.
-----------------------------------------

Hello Bella,

In advance thanks for your help. Under the text you will find the screenshot.

I use my Computer with Windows 10 + currently the version 2.1.7


What do zu mean with: App Logs?

I hope you can help 😊

![image](https://user-images.githubusercontent.com/77388401/104478984-328cbd00-55c3-11eb-93fb-2b4a21826730.jpeg)

**Comment by Fabio129** [comment]
> Hi @Fabio129 , thanks for the screenshot. Below is a guide on sending app logs.
> 
> <img alt="1 App log" width="339" src="https://user-images.githubusercontent.com/65014479/104482971-8a96e400-5602-11eb-8ac5-c098157a1aac.png">
> 
> <img alt="2 Komprimiere" width="511" src="https://user-images.githubusercontent.com/65014479/104482982-8ec30180-5602-11eb-8b08-82e732c7d665.png">
> 
> <img alt="3 Drag and drop" width="671" src="https://user-images.githubusercontent.com/65014479/104483009-94b8e280-5602-11eb-86c4-3be162adbe87.png">

Good Morning, 

here you get the App Logs. I hope it will help.

[App Logs.zip](https://github.com/DeFiCh/app/files/5812686/App.Logs.zip)

**Comment by izzycsy** [comment]
Hi @Fabio129 , well received. Please give us time to investigate this, thank you.

**Comment by RoyDD87** [comment]
hello, i have the same problem. Is there already a solution

**Comment by Fabio129** [comment]
> hello, i have the same problem. Is there already a solution

No not yet, but I am looking forward to hearing from the support as soon as possible!

**Comment by izzycsy** [comment]
Hi @RoyDD87 , could you send your app logs please? 

Hi @Fabio129 , the team is still investigating, thank you for your patience.

**Comment by RoyDD87** [comment]
hello, I'll send you the logs app in a moment. in the meantime the synchronization has worked. but! now there are two new bugs. I have fewer tokens than before and the error add-on auth tx failed: insufficent funds appears.
![Uploading 20210118_104904.jpg…]()

**Comment by RoyDD87** [comment]
[app logs.zip](https://github.com/DeFiCh/app/files/5829469/app.logs.zip)

**Comment by RoyDD87** [comment]
![20210118_104904](https://user-images.githubusercontent.com/77566284/104902116-95dd6d00-597e-11eb-8f49-bc01cd740006.jpg)

**Comment by RoyDD87** [comment]
hello, is there already a solution

**Comment by Fabio129** [comment]
> Hi @RoyDD87 , could you send your app logs please? 
> 
> 
> 
> Hi @Fabio129 , the team is still investigating, thank you for your patience. 

Thank you I am looking forward to hearing an solution for my problem.

**Comment by RoyDD87** [comment]
hello, is there already a solution

**Comment by RoyDD87** [comment]
Yesterday, i send my app logs

**Comment by izzycsy** [comment]
Hi @RoyDD87 , no the team is still investigating, logs well received. Thank you.

**Comment by izzycsy** [comment]
hi @RoyDD87 , the team is still investigating. Regarding the issue `Add LP: Add-on auth TX failed: Insufficient funds`, I'll link you to <https://github.com/DeFiCh/app/issues/312> where we can further discuss on the problem. Let’s keep this thread related to what the original author opened. Thank you for your understanding.

**Comment by izzycsy** [comment]
Hi @Fabio129 , you seem to be on v2.1.7, update v2.1.10 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please provide new information (include screenshots) and app logs. Thank you.

**Comment by izzycsy** [comment]
Hi @Fabio129 , update v2.1.12 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
