### ISSUE TITLE
Menu: Unable to click Import / Backup / Reset wallet

### ISSUE THREAD

**Issue by jdavidhuebner** [DeFiCh/app#278]
Dear DefiApp-Team, dear @izzycsy 
as requested, my problems in a new issue. I just put in some quotes from the old article. [https://github.com/DeFiCh/app/issues/183]

Do I need to provide logs and all that again @izzycsy or do you guys have everything you need?

Hope this gets resolved swiftly. Not a good feeling at all to not be able to access your funds.

From the old/closed issue:

"Sadly, I still have the same problem on 2.16. My wallets are gone and I can't select any of the wallet dropdown menu options. "Import Wallet" "BackUp Wallet" and "Reset Wallet" are not available/clickable. I'm still afraid of clicking "Import Wallet via Mnemonic Seed" since I have a lot of farmed DFI currently shown as balance on the DEX. But no wallets to be seen. What do I do? Import via Mnemonic Seed? Reinstall? Help would greatly be appreciated."...

"The problem is - I can't select any of the dropdown options under "wallet". They are all greyed/whited out. So I can't even import my backups, since I can't select "Import Wallet". Right now I can't do backups anymore either, since, as I said, I can't select anything under the "Wallet"-Dropdown Menu"...

**Comment by izzycsy** [comment]
Hi @jdavidhuebner , thanks for your feedback. I'll upload your screenshot here as well for you. The team is investigating this issue, thank you for your patience. 

![210113 v2 1 6 - Wallet - Unable to click Import, backup, reset wallet](https://user-images.githubusercontent.com/65014479/104466980-c32dc200-55f0-11eb-8535-ff25a55a058e.png)

**Comment by jdavidhuebner** [comment]
Thanks @izzycsy . Just a quick question - 2.17 came out, should I install it or wait with it?

**Comment by izzycsy** [comment]
Hi @jdavidhuebner , if you're still able to use all other functions, you may stay on your current version, we're still investigating. Howwever, if you do think of it, I do not recommend installing older version for your safety and security, our team is constantly working on improving the app and solving its issues.

**Comment by jdavidhuebner** [comment]
Meanwhile 2.1.10 is out - any News? @izzycsy

**Comment by izzycsy** [comment]
Hi @jdavidhuebner , thank you for your patience on this. After investigating your case, it seems that app, somehow "thinks" you don't have a wallet, hence you were unable to click on the `Import / Backup / Reset Wallet`. 

You can move forward to install v2.1.10 <https://defichain.com/downloads/>. Once you've installed, `restore wallet` via your mnemonic seed, wait for blockchain to sync to 100%. Your wallet should appear then.

**Comment by rxandr** [comment]
Its an update solve, I had that & restarted with update

**Comment by izzycsy** [comment]
Hi @jdavidhuebner @rxandr , update v2.1.12 is out <https://defichain.com/downloads/>.

@rxandr if you're facing the same error, install v2.1.12, `restore wallet` via your mnemonic seed, wait for blockchain to sync to 100%. Your wallet should appear then. Following which, if your balances are incorrect, import the latest wallet backup you have.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
