### ISSUE TITLE
2.1.7 txn-mempool-conflict (code 18)

### ISSUE THREAD

**Issue by schollerbernhard** [DeFiCh/app#282]
I tried to add some BTC / DFI funds to LM and got the following error:
txn-mempool-conflict (code 18)
[app logs.zip](https://github.com/DeFiCh/app/files/5811105/app.logs.zip)

**Comment by lraphael** [comment]
I have the same issue with 2.1.8

**Comment by izzycsy** [comment]
Hi @schollerbernhard @lraphael , regarding the issue `txn-mempool-conflict (code 18)`, I'll link you to <https://github.com/DeFiCh/app/issues/241> which we can further discuss on the problem. We would like to keep same issues in one thread. 

Please send your app logs & screenshots (if possible).Thank you.
