### ISSUE TITLE
2.1.7 Wallet: DFI balance not displayed

### ISSUE THREAD

**Issue by Yannick1712** [DeFiCh/app#284]
In Version 2.1.7 the DFI balance in the wallet is not displayed. I checked my balance in the console, where it was right. 
The token balance seems to show right

**Comment by PrinzBG13** [comment]
I have the exact same issue on Mac! I tried a Test-Deposit, under "get balance" in the console the amount rightfully increased but still does not show up in the balance and is not possible to withdraw

**Comment by sany89** [comment]
The same, and also not possible to swipe on DEX any coin. What can I do?

**Comment by izzycsy** [comment]
Hi @Yannick1712 thanks for your feedback, do you have a screenshot of the error? Kindly send your app logs. This will provide more insight for the investigation. Thank you.

Hi @PrinzBG13 , logs well received. Please give us time to investigate, thank you.

**Comment by izzycsy** [comment]
Hi @sany89 , I think what you describe could be regarding this issue `DEX: something went wrong`, I'll link you to <https://github.com/DeFiCh/app/issues/280> which we can further discuss on the problem. Please send your app logs and provide screenshots of the error if possible. 

Let’s keep this thread related to what the original author opened. Thank you for your understanding.

**Comment by Yannick1712** [comment]
> 
> 
> Hi @Yannick1712 thanks for your feedback, kindly send your app logs. This will provide more insight for the investigation. Thank you.
> 
> Hi @PrinzBG13 , logs well received. Thank you.
> 
> Do any of you have a screenshot of the error? Is it only DFI that is not displayed?

<img width="566" alt="No Balance" src="https://user-images.githubusercontent.com/52333989/104601710-d8e7c980-567a-11eb-85e0-e79823f2213b.PNG">

**Comment by pegasus2003** [comment]
> Hi @Yannick1712 thanks for your feedback, kindly send your app logs. This will provide more insight for the investigation. Thank you.
> 
> Hi @PrinzBG13 , logs well received. Thank you.
> 
> Do any of you have a screenshot of the error? Is it only DFI that is not displayed?

Hi @izzycsy, I have the same issue. Please see the screenshot attached. getbalance brings 0.9999484 DFI. The other wallets are empty.
![Ohne Titel](https://user-images.githubusercontent.com/77398160/104601915-1c423800-567b-11eb-9b62-e5ff5a9e38c4.png)

**Comment by Yannick1712** [comment]
> 
> 
> > Hi @Yannick1712 thanks for your feedback, kindly send your app logs. This will provide more insight for the investigation. Thank you.

Yeah sure. My Wallet currently has a whitescreen. So I don't know if you can use my Log files ^^
I will open an other issue for the whitescreen issue.
[App.log](https://github.com/DeFiCh/app/files/5815320/App.log)
[Binary.log](https://github.com/DeFiCh/app/files/5815321/Binary.log)

**Comment by Yannick1712** [comment]
@izzycsy 
Still not showing my Balance with Version 2.1.9. But the whitescreen is fixed. So I will send you the logs with the 2.1.9 running Wallet:
[2.1.9 Logs.zip](https://github.com/DeFiCh/app/files/5816117/2.1.9.Logs.zip)

**Comment by PrinzBG13** [comment]
@izzycsy 
Same problem here. After the update to 2.1.9. the whitescreen is fixed but still no Balance

[2.1.9. Applog.log](https://github.com/DeFiCh/app/files/5816264/2.1.9.Applog.log)

**Comment by pegasus2003** [comment]
> > Hi @Yannick1712 thanks for your feedback, kindly send your app logs. This will provide more insight for the investigation. Thank you.
> > Hi @PrinzBG13 , logs well received. Thank you.
> > Do any of you have a screenshot of the error? Is it only DFI that is not displayed?
> 
> Hi @izzycsy, I have the same issue. Please see the screenshot attached. getbalance brings 0.9999484 DFI. The other wallets are empty.
> ![Ohne Titel](https://user-images.githubusercontent.com/77398160/104601915-1c423800-567b-11eb-9b62-e5ff5a9e38c4.png)

Now the same with 2.1.9. Up to 2.1.6 my Wallt worked perfect on MAC OS Catalina. The problem started with the update to 2.1.7.

**Comment by Yannick1712** [comment]
@izzycsy Issue solved with Version 2.1.10

**Comment by izzycsy** [comment]
Hi @Yannick1712 @PrinzBG13 @sany89 @pegasus2003  , update v2.1.10 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
