### ISSUE TITLE
"Invalid address. Please check this belongs to you..." when adding an address that has already been added

### ISSUE THREAD

**Issue by guiphil** [DeFiCh/app#285]
Hi, I found a minor bug when manually adding an receive address. 

When you try to manually add an address that has already been added you get the error message
"**Invalid address. Please check if this belongs to your, the current address has been used**"

The error message should be changed to "address has already been added" or something. 
This issue is not majorly important to me. Please close this issue at our own discretion. 

![2021-01-14_08h20_41](https://user-images.githubusercontent.com/49029755/104557869-3d3a6700-5642-11eb-84c3-d4bbcc77d716.png)
![2021-01-14_08h20_55](https://user-images.githubusercontent.com/49029755/104557874-3e6b9400-5642-11eb-88f7-5f0bc997f7b5.png)

**Comment by izzycsy** [comment]
Hi @guiphil , thanks for the feedback. Will forward it to the team!

**Comment by izzycsy** [comment]
Hi @guiphil  , update v2.1.12 is out <https://defichain.com/downloads/>. We've updated the feature you mentioned in the app. Thank you.
