### ISSUE TITLE
2.1.7 Wallet Whitescreen

### ISSUE THREAD

**Issue by Yannick1712** [DeFiCh/app#297]
### Preflight Checklist

- [ x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [ x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  - 2.1.7
- **Previous DeFi App Version:**
  - 2.1.6
- **Operating System (OS):**
  - Windows 10 Home (2004)

### Screenshot(s) / screen recording(s) of issue

<img width="960" alt="whitescreen" src="https://user-images.githubusercontent.com/52333989/104613482-8fea4200-5687-11eb-9526-62e299b0e9dd.PNG">

### Actual Behavior

1. Open the app
2. Whitescreen - nothing happens; no start screen etc.

### Expected Behavior
App should start normally

### App log / binary log / app config
[Logs.zip](https://github.com/DeFiCh/app/files/5815405/Logs.zip)

**Comment by OKnr66** [comment]
I have now the firdt time the same behaviour with version 2.1.8. It worked before, but after closing the app and starting after 2 hours I have now a white app and a reduced pull down menu, only with Wallet, Edit, Logs and Help.

With kind regards Olaf Knauber

**Comment by Yannick1712** [comment]
Fixed with Version 2.1.9 in my case

**Comment by izzycsy** [comment]
Hi @OKnr66 @Yannick1712  , update v2.1.10 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
