### ISSUE TITLE
DFI Balance is not shown in App but in console

### ISSUE THREAD

**Issue by MJDefi** [DeFiCh/app#299]
[logs.zip](https://github.com/DeFiCh/app/files/5816948/logs.zip)
Hi,

my balance is not shown in the dfi app gui. It says 0 DFI.
I have updated the app to 2.1.9 but still nothing is shown.
When i type "getbalance" in the console, i do see the correct amount of DFI.
I have restored the wallet and even restored it via seed, nothing helped so far.
Can somebody help me ?

**Comment by UserMaxL** [comment]
Hi,

I have the same issue. DFI are available for the DEX, LM and on the console, but not in the wallet.

**Comment by UserMaxL** [comment]
Seems solved after 2.1.10 update
