### ISSUE TITLE
Can

### ISSUE THREAD

**Issue by salomonkarsten** [DeFiCh/app#300]
Cannot transfer from DFI token to USDT token after update to 2.1.9

![Unbenannt](https://user-images.githubusercontent.com/77124114/104649714-6a742d00-56b5-11eb-84ca-42cd3c8af868.PNG)

**Comment by salomonkarsten** [comment]
I transferred 1 USDT from an external account and then the swap was possible again. I do not want to try to empty fully again.  I guess I just leave some USDT in the wallet. There seems to be something wrong with the referencing. Might be also connected with similar problems, that not all history is showing up properly.

**Comment by izzycsy** [comment]
Hi @salomonkarsten , thanks for your feedback. I've replied to you & the other users having this issue in <https://github.com/DeFiCh/app/issues/305>. Thank you.
