### ISSUE TITLE
Wallet: All balances displayed 0

### ISSUE THREAD

**Issue by MAKEchelon** [DeFiCh/app#301]
When checking my folder, my DFI doesn’t show in my wallet but when I go to the DEX, the amount I transferred over shows up as a swappable. Also, I have USDT and when I try to swap it and the DFI (when it shows my balance in the DEX) the currency pair in which Im trying to swap into remains at ‘0’. When I try to transfer out my USDT it the application won’t let me. Need help asap. Thanks.
[App_log.zip](https://github.com/DeFiCh/app/files/5817574/App_log.zip)

**Comment by thedoublejay** [comment]
Hi @MAKEchelon, can you try to update the app with the latest version? v2.1.9. https://github.com/DeFiCh/app/releases/tag/v2.1.9.

**Comment by MAKEchelon** [comment]
I did. Before with the earlier version, i only saw the DFI wallet there but now i see a few wallets but now I don’t see my DFI balance.

**Comment by MAKEchelon** [comment]
I tried to update it again, but same issue. Is there any update on options for me. Its time sensitive.

**Comment by lraphael** [comment]
Similiar Issue with 2.1.10: https://transfer.sh/cwcqr/Kapture%202021-01-15%20at%2011.38.50.webm

**Comment by lraphael** [comment]
If the destination wallet contains some coins the DEX seems working as expected: https://transfer.sh/dPLUr/Kapture%202021-01-15%20at%2012.46.36.webm

**Comment by MAKEchelon** [comment]
That’s awesome. Which version is that?

**Comment by Katakom88** [comment]
Hi all,
I am having the same issue. I dont see any coins in my wallet but I can see them in the DEX view.
Sadly I am not able to swap as I am getting an error message every time saying something went wrong.

I tried updating the app via the appinternal update function but the app only crashed. (tried several times).
Updated now via the link sent by thedoublejay  

Current DeFi App Version:
2.1.9
Previous DeFi App Version:
2.1.7
Operating System (OS):
windows 10

[Uploading app logs.zip…]()

**Comment by izzycsy** [comment]
Hi @MAKEchelon @Katakom88 @lraphael 	, regarding the issue `DEX: something went wrong`, I'll link you to <https://github.com/DeFiCh/app/issues/280> which we can further discuss on the problem, please send your logs and / or screenshots there if it's new information. Let’s keep this thread related to what the original author opened. Thank you for your understanding.

**Comment by izzycsy** [comment]
Hi @MAKEchelon , update v2.1.10 is out <https://defichain.com/downloads/>. May I have a screenshot of your wallet screen with regards to "DFI doesn’t show in my wallet". 

Can you check you balance via CLI using the following commands: 
`getbalance` — utxo DFI
`gettokenbalances` — DFI  

The sum of utxo DFI & DFI would be your total tokens.

**Comment by izzycsy** [comment]
![App_BTC_shown_No_DFIs](https://user-images.githubusercontent.com/65014479/104836979-99281880-58ec-11eb-8238-086c20056615.JPG)

Hi @Mabarkubus , tagging you _here_ regarding the issue you're facing. Thank you.

**Comment by Katakom88** [comment]
@izzycsy thank you for linking me to issue #280.
However this is onlyone part of my issue. I still can not see my Defi balance in the wallet. 

any chance the issues can befixed short therm? I am sure you areawareof the daily loss as long as we can not join the lequidity mining.

thanks and best wishes.

**Comment by izzycsy** [comment]
Hi @Katakom88 , the team is investigating. I understand your concern, thank you for your patience.

**Comment by izzycsy** [comment]
Hi @MAKEchelon @monnyfx @adrian-schnell @Mabarkubus @Katakom88 	, update v2.1.11 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
