### ISSUE TITLE
My Balance is not showing in Wallet PC only for 1 Second then disappear. Everything is 0.00000

### ISSUE THREAD

**Issue by monnyfx** [DeFiCh/app#303]
Hello,
Can you Please fix this app.
I am using Version 2.1.9 Pc windows
I deposited to Wallet and it took 2 hours to show balance for 1 Second then everything is 0 again.
Restored Wallet and still same issue.

[applogs.zip](https://github.com/DeFiCh/app/files/5818622/applogs.zip)
[screenshot.zip](https://github.com/DeFiCh/app/files/5818623/screenshot.zip)

**Comment by adrian-schnell** [comment]
same on mac with 2.1.9

**Comment by izzycsy** [comment]
Hi @monnyfx , screenshots & logs well received.

@monnyfx @adrian-schnell , regarding the issue `DFI: Balance not displayed`, I'll link you to <https://github.com/DeFiCh/app/issues/301> which we can further discuss on the problem. We would like to keep same issues in one thread. Thank you.
