### ISSUE TITLE
DEX: recipient () does not refer to any valid address

### ISSUE THREAD

**Issue by jonjomatic** [DeFiCh/app#305]
Hi there,

I am swapping some USDT to ETH via defi-app v 2.1.9

1. USDT to DFI - ok

2. DFI to ETH - error, see screenshot below. The message is `recipient () does not refer to any valid address`

Is there a workaround?

Also the DEX does not tell you how much of the token you will get when you swap, but I think this has been reported already.

Thanks,
Jonathan

![image](https://user-images.githubusercontent.com/75774679/104697309-870e7480-574a-11eb-857e-b5a994d97453.png)

### Preflight Checklist

- [ X] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [ X] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  - 
- **Previous DeFi App Version:**
  - 
- **Operating System (OS):**
  -

**Comment by salomonkarsten** [comment]
HEllo My workaround for USDT was to send to my address a small amount of USDT from an external address. Then everything was back to normal. Actually unfortunately the only way to send from an external address is either to open another wallet or to use Cake. Cheers

I hope it works for you as well with ETH coin. See issue #300

**Comment by UserMaxL** [comment]
Have the same issue DFI to ETH (or adding ETH/DFI LM shows the error). Version 1.1.10 wallet was set up new (three days ago). Tried to transfer some ETH from an older wallet (all works fine here on version 1.1.10) and also with some ETH DEX or LM still doesn't work. AppLog attached 
[AppLogsJan15.log](https://github.com/DeFiCh/app/files/5821479/AppLogsJan15.log)

**Comment by izzycsy** [comment]
Hi @jonjomatic , @salomonkarsten , thanks for your feedback, kindly send your app logs. This will provide more insight for the investigation. Thank you.

Hi @UserMaxL , thanks for your feedback, logs well received. Please give us time to investigate this issue.

**Comment by izzycsy** [comment]
Hi @jonjomatic @salomonkarsten @UserMaxL , may I check that you're on v2.1.10? <https://defichain.com/downloads/> It was officially released yesterday.

**Comment by UserMaxL** [comment]
Hi @izzycsy
My App version is 2.1.10 (as described in the first comment) and I have the same issue on all swaps: 
✕ Swap DFI to BTC
✕ Swap DFI to ETH
✕ Swap DFI to USDT

**Comment by izzycsy** [comment]
Hi @jonjomatic @salomonkarsten @UserMaxL , may I check when you use DEX,  did you select a `receive address`?

**Comment by salomonkarsten** [comment]
@izzycsy yes receive address was chosen. But I solved the issue as mentioned by transfer from an external account. So I can no longer verify the issue.

**Comment by izzycsy** [comment]
Hi @salomonkarsten , noted thanks for the update.

**Comment by UserMaxL** [comment]
@izzycsy yes, chose both receive addresses I have. And as described already I transferred some ETH from an older wallet I have (all works fine here on version 1.1.10) and also with some ETH the DEX or adding LM still doesn't work.

**Comment by izzycsy** [comment]
Hi @UserMaxL , thanks for the confirmation, please give us time to investigate this issue.

**Comment by 1230-1** [comment]
@izzycsy hey there. May i know how i can complete the swap then? Posted my issue here previously as requested https://github.com/DeFiCh/app/issues/195 from reddit https://www.reddit.com/r/defiblockchain/comments/kzq1o1/need_help_here_i_am_unable_to_swap_the_dfi_for/

**Comment by izzycsy** [comment]
@1230-1 , thanks for your feedback. After analysing from the screenshot you provided, it could be a different issue `DEX: [MAX] button error` <https://github.com/DeFiCh/app/issues/177>. The team is aware of this minor visual bug, there's a temporary solution: type `1` > click `MAX`, function should work from there. Let me know if it works, if you face an error please take a screenshot. Thank you.

**Comment by 1230-1** [comment]
@izzycsy Hmm not working 
![image](https://user-images.githubusercontent.com/77612073/105005401-3d869800-5a70-11eb-8ce5-404819fac288.png)

**Comment by UserMaxL** [comment]
@izzycsy I tried the instructions from the issue #177 and multiple other combinations of [Max] and typing numbers.
I get a "something went wrong" massage. See Screenshot attached.
![SomethingwentWrong](https://user-images.githubusercontent.com/75398355/105089810-e3043080-5a9d-11eb-9d6c-1d38accb6b94.JPG)

**Comment by UserMaxL** [comment]
@izzycsy Not sure if this is partly causing this issue, but as I said I created a new wallet on my PC by resetting the wallet. I created a new one (with new seed). When I go to the Transaction list I still see the transactions from the old Wallet. Probably this is worth a new issue.

**Comment by izzycsy** [comment]
Hi @1230-1 , thanks for trying and for the screenshot, we're investigating. 

Hi @UserMaxL ,well noted on the update, thanks for trying. Regarding your 2nd comment, yes I think it deserves a new issue, could you elaborate further in the new issue? I'll keep a look out. Thank you!

**Comment by UserMaxL** [comment]
@izzycsy Hi, I saw this issue was mentioned in the recent update 2.1.11 to be fixed, but I still have the „something went wrong issue“ in DEX on version 2.1.11 (have amounts on both ends) and still „recipient () does not refer to any valid address“ in LM.

**Comment by rxandr** [comment]
iHave the same problem even via console

**Comment by izzycsy** [comment]
Hi @jonjomatic @salomonkarsten @UserMaxL @1230-1 @rxandr  , update v2.1.12 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send your logs after updating to v2.1.12. Thank you. 

@UserMaxL , if in v2.1.12, you still face the issue `DEX: Something went wrong`, refer to this link <https://github.com/DeFiCh/app/issues/280> where we can further discuss on the problem. Let’s keep this thread related to what the original author opened. Thank you for your understanding.

**Comment by INQB1** [comment]
Hi @izzycsy . I first had the issue "insufficient funds" in v2.1.1, but it got resolved after I transferred 20 DFI to my wallet (it only had BTC and ETH but no DFI). 
But now I have the same issue as the guys above: 
"recipient () does not refer to any valid address"
I upgraded to v2.1.12 but the issue persists.

**Comment by izzycsy** [comment]
Hi @INQB1 , thanks for your feedback, could you send you logs please? Please give us time to investigate this, thank you.

**Comment by INQB1** [comment]
Thx @izzycsy izzycsy. Btw, I meanwhile tried a UTXO rescan and it got stuck at 99.98% with the error: 
Node is disconnected. 
Plus I receive alerts every 10 sec: Network failure. Wallet balance failure. Pending balance failure. 

To your question. I've not tried any of the below.
✓ / ✕ Swap DFI to BTC
✓ / ✕ Swap DFI to ETH
✓ / ✕ Swap DFI to USDT
My issues happened when I tried to add to BTC-DFI liquidity. 
I'll fetch the log file now and send it to you.

**Comment by INQB1** [comment]
[DeFiChain App log 24.1.2021.log](https://github.com/DeFiCh/app/files/5862976/DeFiChain.App.log.24.1.2021.log)

**Comment by izzycsy** [comment]
Hi @INQB1 noted, I've replied you.

**Comment by PrinzBG13** [comment]
Hi I get the same issue while using the DEX for all 3 pairs:

"recipient () does not refer to any valid address"

I'm not using the "MAX" Button

[defi-app.log](https://github.com/DeFiCh/app/files/5874036/defi-app.log)

**Comment by izzycsy** [comment]
Hi @INQB1 @PrinzBG13 , can I check that you're on [v2.1.13](https://defichain.com/downloads/)?

**Comment by PrinzBG13** [comment]
> Hi @INQB1 @PrinzBG13 , can I check that you're on [v2.1.13](https://defichain.com/downloads/)?

Yes I am! To make sure, I deleted the app and reinstalled. Now I had to recover with my seed phrase. I made a backup of my wallet first, too. Now that I imported the wallet back in over 2000 DFI are missing... what can I do? I'm a little bit freaked out right now...

[defi-app.log](https://github.com/DeFiCh/app/files/5879983/defi-app.log)

**Comment by eagleel** [comment]
I still have the issue, I have 2.1.13.

Unfortunately I cannot get my danish keyboard to write the correct code in the console. Pretty frustrating.

**Comment by PinkiNoBrain** [comment]
Archiv.zip

same here with 2.1.13

**Comment by salomonkarsten** [comment]
Did you reload the UTXO???

**Comment by eagleel** [comment]
Broke the danish keyboard code..... crazy......so managed to get the utxostoaccount code into the console and after a few failed attempts it now works between btc and dfi ..... back and forth. Thanks for all the help

**Comment by izzycsy** [comment]
Hi @PinkiNoBrain ,	the error occurs because you've too little utxoDFI balance (min. 1DFI) — which is required to perform swap and other functions. The UI does not differentiate between coin and token. 

Please try the following via `CLI`.   Check balances:  `getbalance` — utxoDFI
`gettokenbalances` — accountDFI  `utxostoaccount {“your_address”:”1.0@DFI"}`  — you’re sending 1 DFI to your own address

Check balances again: `getbalance` — utxoDFI
`gettokenbalances` — accountDFI

Try your function again.

**Comment by izzycsy** [comment]
Hi @jonjomatic @salomonkarsten @UserMaxL @1230-1 @rxandr  @INQB1 @PrinzBG13 @eagleel @PinkiNoBrain , 	update [v2.1.13](https://defichain.com/downloads/) is out.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thanks for your feedback, the team will improve the ux. Thank you.
