### ISSUE TITLE
Add Liquidity: recipient () does not refer to any valid address

### ISSUE THREAD

**Issue by Mabarkubus** [DeFiCh/app#311]
System Win10:
I'm havin the same troubles as a lot of other users: 
- Transfered DFI coins were not shown in the wallet, 
- BTCs were shown
- couldn't add luiquidity BTC/DFI: Error-message shows "recipient () does not refer to any valid address"

After update to 2.1.9 complete Wallets empty
- had to reset wallet
- then both wallets BTC and DFI are empty
- DFI are shown, when trying to add liquidity BTC/DFI but no BTCs.

[Pictures_15012021.zip](https://github.com/DeFiCh/app/files/5820391/Pictures_15012021.zip)

**Comment by Mabarkubus** [comment]
Now with the update to 2.10.0 coins are shown in the wallets, i'm still not able to add liquidity BTC/DFI:
Error-message shows "recipient () does not refer to any valid address"

**Comment by izzycsy** [comment]
Hi @Mabarkubus , thanks for your feedback & screenshots!

Issue 1: Add Liquidity > error: `recipient () does not refer to any valid address`
• Did you select a `receive address`?

Issue 2: Wallet > All balances displayed 0
• Regarding the issue `https://github.com/DeFiCh/app/issues/301`, I'll link you to <Wallet: All balances displayed 0> which we can further discuss on the problem. We would like to keep same issues in one thread. I'll tag you there. Thank you.

**Comment by izzycsy** [comment]
Hi @Mabarkubus , I'll proceed to close this thread first. Thank you.
