### ISSUE TITLE
SHA256 Hash is not correct for downloadfiles v1.2.10

### ISSUE THREAD

**Issue by bernd-mack** [DeFiCh/app#313]
Hello devteam,
A Telegram user noticed that the SHA256 hashes do not match the hashes of the download files. I tried to recreate this (see screenshot) and it looks like all hash files are identical "bc05de5af37736c91abe3cbe4a2b57e5571c7dd1cef86a8b3ac88ccd45714068" -> can't be. And none matches the hash the files generate.
Please have a look at it when you get a chance. Thanks

![image](https://user-images.githubusercontent.com/76614620/104746263-541aaf80-574f-11eb-82cc-dfa0622e6c44.png)

**Comment by bernd-mack** [comment]
Thanks for the quick correction. The now downloadable SHA hashes match the installation files.
![image](https://user-images.githubusercontent.com/76614620/104753793-c479fe80-5758-11eb-9088-90124215d25f.png)

**Comment by izzycsy** [comment]
Hi @bernd-mack , thanks for the feedback!
