### ISSUE TITLE
DEX with 0 balance

### ISSUE THREAD

**Issue by MrStryker** [DeFiCh/app#315]
### Preflight Checklist

- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  2.1.10
- **Previous DeFi App Version:**
2.1.9
- **Operating System (OS):**
 Windows 10 (19042) 

### Actual Behavior

1. Go to DEX,  in DEX select (from) DFI.  
2. If (to) USDT/ETH/BTC has a zero balance receive the error message "something went wrong."  
3. DEX works when the wallet has a small amount of USDT/ETH/BTC works.

-->

### Expected Behavior
The DEX should swap regardless if you have a wallet balance.
![DFI app dex issue](https://user-images.githubusercontent.com/77477221/104780155-57fa0200-574e-11eb-9fa4-3bf31bc52d16.jpg)

**Comment by izzycsy** [comment]
Hi @MrStryker , thanks for your feedback, may I check, did you select a `receive address`? 

Regarding the issue `DEX: Something went wrong`, I'll link you to <https://github.com/DeFiCh/app/issues/280> which we can further discuss on the problem. We would like to keep same issues in one thread. Please send me your logs there. Thank you.
