### ISSUE TITLE
Update Button > Corrupted Blockchain file

### ISSUE THREAD

**Issue by Yannick1712** [DeFiCh/app#316]
### Preflight Checklist

- [x ] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x ] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Operating System (OS):**
  - Windows 10

### Actual Behavior

1. Open the app
2. Update the wallet with Update Button
3. Caused an error when starting the wallet after installation
4. Corrupted Blckchain file

Unfortunalty I cannot give any log Data. I got the problem some days ago and forgot to write an issue. I have read some other guys had the same issue

**Comment by marathom** [comment]
I have the same issue on linux Ubuntu. It's still a problem of consuming a lot of ram memory. My pc with 12GB RAM is not enough for re-synching blockchain. Please provide an update as soon as possible.

**Comment by izzycsy** [comment]
Hi @Yannick1712 @marathom , thanks for your feedback, I understand please give us time to investigate this issue.

**Comment by izzycsy** [comment]
![210120 v2 1 10 MN - Wallet - high memory consumption (salomonkarsten)](https://user-images.githubusercontent.com/65014479/105142239-560cb600-5b35-11eb-998d-11b836915518.png)

Hi @salomonkarsten , as I understood you're facing a similar issue of high RAM consumption, will keep you updated there. If possible send your app config & binary log, it'll help with the investigation. Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/105142372-7ccaec80-5b35-11eb-84ba-233784f9e63a.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/105142391-83596400-5b35-11eb-93c6-f77a4daa417d.png">

**Comment by Leon2023** [comment]
[1.log](https://github.com/DeFiCh/app/files/5855003/1.log)

There seems so be something fundamentally wrong with the update button. Im just gonna hop in and give a classic me too. The last version i took directly from github - no reindex needed. Today i used the update button to upgrade from 2.1.10 to 2.1.11 and the blockchain is corrupted again and needs to sync from . All three logs are attached.
[Neuer ZIP-komprimierter Ordner.zip](https://github.com/DeFiCh/app/files/5855022/Neuer.ZIP-komprimierter.Ordner.zip)

**Comment by izzycsy** [comment]
Hi @Leon2023 , thanks for your feedback, logs well received. Please give us time to investigate this issue. In the mean time there's another way to update the app: 

1. Download update from <https://defichain.com/downloads/>
2. Open `defi-app-2.1.12.dmg` file
3. Drag and replace your cureent app 

<img width="535" alt="Replace app2" src="https://user-images.githubusercontent.com/65014479/105638834-edfcfd80-5eaf-11eb-818c-37f0d6d1e254.png">

<img width="539" alt="Replace app1" src="https://user-images.githubusercontent.com/65014479/105638831-e9d0e000-5eaf-11eb-99e4-215ab4e1d339.png">

**Comment by izzycsy** [comment]
Hi @Yannick1712 @Leon2023 , it seems like there are a few other users facing the same issue [`v2.1.13 Error: Corrupted block database detected`](https://github.com/DeFiCh/app/issues/390), we can further discuss on the problem there. We would like to keep same issues in one thread. The team is investigating this issue Thank you for your patience.
