### ISSUE TITLE
[BUG] Coins are stuck on the blockchain

### ISSUE THREAD

**Issue by gutenmorgen2** [DeFiCh/app#317]
Hello everybody,

it's about this topic:
https://www.reddit.com/r/defiblockchain/comments/ky4qz2/bug_coins_are_stuck_on_the_blockchain/

I've tried the reindex option before. Additionally on another PC. The 64 DFI are no longer displayed.
Can someone help me there? If log files are required, I will be happy to provide them.

Version 2.1.10 (But I also tried older versions.)

Thank you!

**Comment by gutenmorgen2** [comment]
I have now deducted everything from the address, but the 64 dfi cannot be moved. I can't move it. There are several more with the problem, according to Reddit. Blockchain bug or app bug?

Please check it out.

Address: https://explorer.defichain.io/#/DFI/mainnet/address/dZaotNHvsJhwcUdvsHdg1q4Xfee1cSnCQP
Tansaction: https://explorer.defichain.io/#/DFI/mainnet/tx/7e6efe9cc0bed864e89df737d9b00de5d556a6777a22c3a75ff684f4fb3eeb6e

**Comment by izzycsy** [comment]
Hi @gutenmorgen2 , thanks for your feedback. Could you type the following via the CLI: 

`getbalance` — utxo DFI
`gettokenbalances` — DFI

  The sum of utxo DFI & DFI would be your total tokens.

Next, please provide the output of: 
`listaccounts {} true true true` — breakdown of your coin(s) / token(s)

Thank you.

**Comment by gutenmorgen2** [comment]
Thanks for answer.

just do this transaction: I can only move the 0.1 dfi. The 64 dfi frozen on blockchain.
https://explorer.defichain.io/#/DFI/mainnet/tx/ba76e3b1f54f6887dc97862872f2a848b47dddb24ffdf5b058051309520a9c80

I can no longer reach the 64!
https://explorer.defichain.io/#/DFI/mainnet/tx/7e6efe9cc0bed864e89df737d9b00de5d556a6777a22c3a75ff684f4fb3eeb6e

The 64 are not displayed in the defi app. If I send 5 dfi to the address now, I can also use these 5 dfi, but the 64 dfi are stuck. (See first transaction with the 64 dfi).

Tokens are no longer on the address.

gettokenbalances
[
  "1.67388290@0",
  "0.00012457@2",
  "0.01862148@3",
  "7.07296830@5",
  "1309.34849962@6"
]

getbalance
0.99932357


And this balance is from this Address:
https://explorer.defichain.io/#/DFI/mainnet/address/dXU7fg5nk2t4hRGd3c6XM86FdPJAXaCUJk

See this transaction from just:
https://explorer.defichain.io/#/DFI/mainnet/tx/ba76e3b1f54f6887dc97862872f2a848b47dddb24ffdf5b058051309520a9c80

**Comment by gutenmorgen2** [comment]
Now I will explain it in a little more detail.

So, after the incident I created a new address and all coins / tokens / liquidy mining to this address:
https://explorer.defichain.io/#/DFI/mainnet/address/dXU7fg5nk2t4hRGd3c6XM86FdPJAXaCUJk

I have now prepared a little for clarification. Now ALL DFI Coins are on my old address. Look:
https://explorer.defichain.io/#/DFI/mainnet/address/dZaotNHvsJhwcUdvsHdg1q4Xfee1cSnCQP

Blockchain says: 65.34034314 DFI

As a result of the transaction, a small residue came to this address:
https://explorer.defichain.io/#/DFI/mainnet/address/dTVknCTeFrSiSaUVmNQQQwRKSY2WJDDAvk

Blockchain says: 65.34034314 DFI

0.02005788 DFI

Now I type in "getbalance":
getbalance
1.37999963

Address 1 + Address 2 = 65,37999963 DFI Subtract the 64 = 1.37999963

The DFI are NOT recognized. I've also completely reloaded the blockchain. Tried on another PC. I hope you understand better what I mean now. Either there is a bug in the blockchain or the Defi app has a bug.

I hope you will have a look at it soon, as the values are constantly changing (use DeFi liquidity mining productively). I won't move anything today so that you can understand it better.

**Comment by gutenmorgen2** [comment]
After this transaction (conversion of tokens to coins 2 days ago) the 64 dfi "disappeared".
https://explorer.defichain.io/#/DFI/mainnet/tx/7e6efe9cc0bed864e89df737d9b00de5d556a6777a22c3a75ff684f4fb3eeb6e

**Comment by gutenmorgen2** [comment]
Solved. I imported an old wallet backup. Then it worked. But that's risky when you think about it. The seed alone is apparently not enough. A wallet backup is essential.

**Comment by izzycsy** [comment]
Hi @gutenmorgen2 , thanks for your feedback. I'll forward this to the team for improvement. Agreed, however the mnemonic seed & wallet backup is store in your own local PC. Therefore not accessible but external parties unless you send / lose it. Please keep it safe. Thank you.
