### ISSUE TITLE
Connection to node breaks

### ISSUE THREAD

**Issue by RoyDD87** [DeFiCh/app#320]
![20210116_202138](https://user-images.githubusercontent.com/77566284/104834620-f26a5a80-58a0-11eb-8fc1-89c906e5ade6.jpg)
![20210116_202112](https://user-images.githubusercontent.com/77566284/104834624-f8603b80-58a0-11eb-9876-833d507a0392.jpg)
![20210116_202110](https://user-images.githubusercontent.com/77566284/104834625-fa29ff00-58a0-11eb-9330-295e035923ed.jpg)

Hi, I have the following problem. the synchronization breaks off after 99.6 percent. then comes the message connection to the node disconnected. I have to restart the app and then the blockchain broken error occurs.

I have the latest version

### Preflight Checklist

- [ ] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [ ] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  - 
- **Previous DeFi App Version:**
  - 
- **Operating System (OS):**
  -

**Comment by izzycsy** [comment]
Hallo @RoyDD87 , thanks for your feedback. Regarding the issue `Wallet: Corrupted blockchain detected`, I'll link you to <https://github.com/DeFiCh/app/issues/276> which we can further discuss on the problem. We would like to keep same issues in one thread. Please send your logs there. Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/104838190-3f2b5100-58f4-11eb-8cf9-d9a5d47d3dc1.png">

<img width="511" alt="2 Komprimiere" src="https://user-images.githubusercontent.com/65014479/104838193-418dab00-58f4-11eb-9bdb-c735663eda03.png">
