### ISSUE TITLE
Wallet BTC: Missing tx history

### ISSUE THREAD

**Issue by maaze19** [DeFiCh/app#322]
### Preflight Checklist

- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app)

### Issue Details

- **Current DeFi App Version:** 
  - 2.1.10
- **Previous DeFi App Version:** 
  - 2.1.4
- **Operating System (OS):** 
  - Microsoft Windows [Version 10.0.18363.1316]

### Screenshot(s) / screen recording(s) of issue

Wrong paginator (DFI):
![image](https://user-images.githubusercontent.com/23696030/104839211-e9d54c80-58bf-11eb-8ea3-affba1c4e206.png)

Last page is missing (BTC):
![image](https://user-images.githubusercontent.com/23696030/104839293-5b14ff80-58c0-11eb-8c57-9a2689e2d362.png)
![image](https://user-images.githubusercontent.com/23696030/104839324-87308080-58c0-11eb-8d40-7d0efc96222b.png)

### Actual Behavior
```
1. Open the app
2. Go to wallet page
3. Click on DFI
4. Look at the paginator of the transaction history:
- The paginator shows only 1 page, forward (>) and back to page 1 (|<)
- When clicking on page 1, the app redirects to page 1
- When clicking on forward, the app redirects to the next page. It's possible until no more entries can be found. 
For BTC: The paginator disappears even there should be one more page and the text "No entries..." appears. You have to start from step 2 again. (See image 2 and 3)
- When clicking on 'back to page 1' (|<), it redirects to page 1. There is no possibility to go only one page back.
```

**Comment by izzycsy** [comment]
Hi @maaze19 , thanks for your feedback. 

1) Pagination jumps back to page 1: Will feedback this to the team to improve the user experience. 

2) Missing BTC page: Can you try `Reindex option` in Settings , and see if your missing page of BTC tx history appears. 

<img width="776" alt="Reindex option" src="https://user-images.githubusercontent.com/65014479/104901281-284e3280-59b8-11eb-8f24-012a70586b1d.png">

**Comment by maaze19** [comment]
> Hi @maaze19 , thanks for your feedback, can you send your app logs please?
> 
> <img alt="1 App log" width="339" src="https://user-images.githubusercontent.com/65014479/104902209-67c94e80-59b9-11eb-8d35-c6b238bbb049.png">
> 
> <img alt="2 Compress" width="511" src="https://user-images.githubusercontent.com/65014479/104902216-69931200-59b9-11eb-9794-fcde40e0bf5f.png">
> 
> 1. Pagination jumps back to page 1: Will feedback this to the team to improve the user experience.
> 2. Missing BTC page: Can you try `Reindex option` in Settings , and see if your missing page of BTC tx history appears.
> 
> <img alt="Reindex option" width="776" src="https://user-images.githubusercontent.com/65014479/104901281-284e3280-59b8-11eb-8f24-012a70586b1d.png">

I will post the App logs later. I made a reindex right before I posted this issue because I made the update to the latest version.

**Comment by izzycsy** [comment]
Hi @maaze19 	, update [v2.1.13](https://defichain.com/downloads/) is out.

Do give a thumbs up to this comment if your issue (missing tx history) has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
