### ISSUE TITLE
Add LP: Insufficient UTXOs

### ISSUE THREAD

**Issue by miromiro321** [DeFiCh/app#323]
Dear Support Team

As I want to perform a swap or to add liquidity to my Liquidity to my pools there is always a errror at the bottom of the Page written in red "insufficent UTXOs to perform swap" 

I tried to change the settings into refresh UTXOs each time after saving but it is stuck in an Page saying " UTXOs will be reloaded, it can take a while" 

Tanks for ur Help 

cheers 

[app logs.zip.zip](https://github.com/DeFiCh/app/files/5826002/app.logs.zip.zip)
### Preflight Checklist

- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  -  2.1.7
- **Previous DeFi App Version:**
  - 
- **Operating System (OS):**
  -  Windows 10 home

### Actual Behavior

1. Open the app
2. Go to liquidity Mining
3. Click on Pool
4. Add liquidity
5. Insufficient UTXOs to perform add liquidity

### Expected Behavior
 to perform add liquidity

### App log / binary log / app config
 
[app logs.zip.zip](https://github.com/DeFiCh/app/files/5826016/app.logs.zip.zip)

**Comment by izzycsy** [comment]
Hi @miromiro321 , thanks for your feedback. Please give us time to investigate this. In the mean time, there’s a temporary solution to this, it could be that you've too little DFI UTXOs balance (min. 0.05DFI) — which is required to perform swap and other functions. 

You could send yourself some DFI **or** try to convert a little DFI tokens to DFI UTXOs, and see if it works. Attached a link that might help you.  <https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/>

**Comment by miromiro321** [comment]
Thank u help a lot.

The problem might have resultet out of the reason that i transferd all DFI to another Platform. leaving me with 0 DFI. After a few days of LQM i had agin DFI wich where not sutibale for performing a swap or refill

**Comment by izzycsy** [comment]
Hi @miromiro321 , yes then it's definitely lack of DFI UTXOs balance. I'll proceed to close this issue. Thank you.
