### ISSUE TITLE
recipient () does not refer to any valid address => adding liquidity mining

### ISSUE THREAD

**Issue by Zhenja90** [DeFiCh/app#324]
I got also the same issue! At "DEX" where you  from DFI to BTC for liquidity mining it shows that my valid adress doesn't fit.
Would be nice getting any help!

![LM](https://user-images.githubusercontent.com/77582466/104849894-89103900-58ec-11eb-9bad-939d06597d53.png)

**Comment by maaze19** [comment]
Can you please provide a full screenshot of the app? Have you selected an address in the process before?
![image](https://user-images.githubusercontent.com/23696030/104886391-f1e9c680-5969-11eb-91dc-9efa1351d5cc.png)

If you can't select any address, create a new one:
1. Go to Wallets
2. Click DFI
3. Click "Receive" on the upper right corner
4. Click "New Address" on the upper right corner
5. Give your address a describing name like "Liquidity Mining RCV"
6. Click "Create" on the lower right corner
![image](https://user-images.githubusercontent.com/23696030/104886617-57d64e00-596a-11eb-89fb-7669a3b4a8dc.png)

**Comment by izzycsy** [comment]
Hi @Zhenja90 , thanks for your feedback, regarding the issue `Add LP: recipient () does not refer to any valid address`, if what @maaze19 suggested did not work, please proceed to <https://github.com/DeFiCh/app/issues/314> which we can further discuss on the problem. We would like to keep same issues in one thread. Thank you.

**Comment by Zhenja90** [comment]
Thanks a lot for your Suggestion managing the issue. ASAP I’ll go through the points to solve the problem. Cheers !
