### ISSUE TITLE
Pagination on token page wrong when searching

### ISSUE THREAD

**Issue by maaze19** [DeFiCh/app#327]
### Preflight Checklist

- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app)

### Issue Details

- **Current DeFi App Version:** 
  - 2.1.10
- **Previous DeFi App Version:** 
  - 2.1.4
- **Operating System (OS):** 
  - Microsoft Windows [Version 10.0.18363.1316]

### Screenshot(s) / screen recording(s) of issue

![image](https://user-images.githubusercontent.com/23696030/104883515-2b6c0300-5965-11eb-9523-f3dbe9e3f1a7.png)
![image](https://user-images.githubusercontent.com/23696030/104883539-36bf2e80-5965-11eb-8880-84cb7f25013a.png)

### Actual Behavior

```
1. Open the app
2. Go to Tokens page
3. Search for DGT
 - The pagination shows 1-10 of 60 tokens
 - The paginator shows pages like I would not have used the search bar
```

### Expected Behavior

I would expect, that the paginator is responding to the search filter from the search bar and is only showing 1 page.

**Comment by izzycsy** [comment]
Hi @maaze19 , thanks for your feedback. Will feedback this to the team.

**Comment by izzycsy** [comment]
This issue will be address in the upcoming release. Thank you.
