### ISSUE TITLE
Can't send anything 

### ISSUE THREAD

**Issue by class95** [DeFiCh/app#332]
### Preflight Checklist

- [x ] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [ x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:2.1.10 - have tried out on many versions, but none work.
  - 
- **Previous DeFi App Version:**
  - 
- **Operating System (OS):**windows 10 1909
  - 

### Screenshot(s) / screen recording(s) of issue
[sending eth](https://user-images.githubusercontent.com/77646732/104970352-72044080-59eb-11eb-97a3-142bf1f3ecf0.PNG)

### Actual Behavior
1. Open the app
2. Go to wallet page
3. Click on ETH
4. Send ETH
5. Unable to send ETH
6. The Send Button is greyed out

### App log / binary log / app config
[app logs.log](https://github.com/DeFiCh/app/files/5832723/app.logs.log)

**Comment by UserMaxL** [comment]
This is a ETH Address. You can't send the Defichain ETH to an ETH address from the App at the moment, because it's not real ETH. There will be an option to do an atomic swap in the Q1'21 releases, so you can swap to real ETH. At the moment you can only send the ETH to a DeFi Chain address (to Cake for example). At Cake to can send to another ETH address.

**Comment by class95** [comment]
didn't know that, thank you. it worked now.

**Comment by class95** [comment]
why is the withdrawal fee of eth so high though in cake. its at 0.028 eth. thats like 40 dollars.

**Comment by UserMaxL** [comment]
That’s a cake topic, but here is the answer:

https://cake.zendesk.com/hc/en-us/articles/360035886591-What-is-the-withdrawal-fee-for-Cake-

 I recommend the cake telegram group for cake issues:
 https://t.me/CakeDeFi_DE

**Comment by izzycsy** [comment]
Hi @class95 , thanks for your feedback. As @UserMaxL mentioned, the address you're using is not a DeFi-friendly address. You can retrieve the DeFiChain address via <cakedefi.com>, try sending a small amount first to test.

1. Click on Balances in <cakedefi.com>
2. In the ETH row, click on Deposit button
3. You'll see the Transfer Network options `ETH` / `DeFi Blockchain`
4. Under the QR Code states your DeFi address, copy it
5. Go to DeFi app > ETH wallet > Send
6. Paste your DeFi address into `To address` field
