### ISSUE TITLE
Plans for ARM release?

### ISSUE THREAD

**Issue by sandrich** [DeFiCh/app#335]
Hi

Is there any plans to release an M1 compatible version? The app is working fine using Rosetta 2 but wonder how long Rosetta 2 will be around.

**Comment by BenThrottle85** [comment]
+1

**Comment by izzycsy** [comment]
Hi @sandrich @BenThrottle85 , there's no plans at the moment but if M1 platform improves and the usage increases, we could look at doing something. Our team is focused on delivering value on the blockchain and we prioritise what the majority of the user base sees; as the direction we want to go.

**Comment by prasannavl** [comment]
Referencing for context: https://github.com/DeFiCh/app/issues/1030#issuecomment-905561464
