### ISSUE TITLE
Direct transfer of Nicehash BTC to DEFIChain possible?

### ISSUE THREAD

**Issue by Anlien75** [DeFiCh/app#340]
Hello,

can I send my BTC mined in Nicehash directly to DEFIChain, or does this have to go through a third party account?
I can't add my DFI wallet address to Nicehash. 

Greetings Andy

**Comment by MrStryker** [comment]
No only through cake.  Or buy DFI on an exchange, send to DEX then convert to WBTC, WETH, WUSDT.

**Comment by Anlien75** [comment]
Thank you

Greetings Andy
