### ISSUE TITLE
Restored Wallet shows tokens but no address -> can't convert or access them

### ISSUE THREAD

**Issue by Sunnyville1234** [DeFiCh/app#343]
### Issue Details

- **Current DeFi App Version: 2.1.10
- **Operating System (OS):Linux, Windows & MacOS (tried all three)

I restored my second Wallet using the Seed Phrase. The balance was zero. I then typed in the command for listing the tokens, followed by the command to get the associated address. No address appears (I removed the balances in the text below):

}
gettokenbalances {} true true
{
  "DFI": _xxxx_,
  "BTC": _xxxx_
}
listaccounts {} false false true
[]

There are always the two brackets at the end, where there should be an address. I don't really know what to do...

**Comment by izzycsy** [comment]
Hi @Sunnyville1234 , you're trying to restore wallet #2 on which OS? Are you trying to change computer for your wallet #2? If so, have you tried saving `backup wallet` from old PC and `import wallet` new PC for wallet #2?

**Comment by rxandr** [comment]
I have and I am completely missing the recognition of wallet coin & cannot send it out from where it is visable. So wierd=/

**Comment by iceman999sod** [comment]
I have the same issue. I reinstalled the the new app version 2.1.11 (I had to reinstall my complete windows system). I restored my wallet with the Seed Phrase and tried it with my backup file, but everytime the receiving adress is missing. Therefore I cant perform LM and the DEX. 

System. Windows 10.
Defi App Version 2.1.11

[applog.log](https://github.com/DeFiCh/app/files/5860947/applog.log)

**Comment by izzycsy** [comment]
Hi @Sunnyville1234 , regarding the issue `Restored wallet > addresses missing`, I'll link you to <https://github.com/DeFiCh/app/issues/370> which we can further discuss on the problem. We would like to keep same issues in one thread. Thank you. 

Hi @rxandr , could you describe your issue more. Check if there's an existing issue and you may drop your comment there or if it's completely new you can create a new issue.
