### ISSUE TITLE
New Wallet: > tx history from old wallet displayed

### ISSUE THREAD

**Issue by UserMaxL** [DeFiCh/app#344]
### Preflight Checklist

- [X] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [X] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:** 2.1.10
 
- **Previous DeFi App Version:** 2.1.9

- **Operating System (OS):** Windows 10 Pro (19042)

1. Open the app
2. Go to wallet page
3. Click on DFI
4. See Transaction list 

I created a new wallet on my PC by resetting the wallet (->Wallet->Reset Wallet). I created a new wallet with a new seed. After several restarts and for days now, when I go to the transactions list I still see the transactions from the old wallet (including very old transactions). The wallet in use also has issues described in issue #305 

![TransactionsIssue](https://user-images.githubusercontent.com/75398355/105410403-2c858480-5c32-11eb-99a3-6b721c9f6519.JPG)

**Comment by izzycsy** [comment]
Hi @UserMaxL , thanks for your feedback. I'd like to understand your issue more. When you `reset` > `create new wallet`, did you import a previous `backup wallet`?

**Comment by UserMaxL** [comment]
Hi @izzycsy , no as mentioned, I created a new wallet with a new seed. No backup was used or imported. Completely new seed.

**Comment by izzycsy** [comment]
Hi @UserMaxL , understood. Please give us time to investigate this. In the mean time, kindly install the latest version v2.1.11 of the app <https://defichain.com/downloads/>. And ensure that you're not running 2 apps on one PC. Thank you.

**Comment by UserMaxL** [comment]
Thanks @izzycsy I updated to version 2.1.11 just an hour ago (no change to the issue) and to my knowledge I'm not running two apps on the PC (is this even possible)?

**Comment by izzycsy** [comment]
Hi @UserMaxL , my hunch is the cache is storing your old transactions, but I will not advise you to remove anything as of now. Please give us time to investigate. Thank you.

**Comment by RobinTorque** [comment]
I also have this problem and found the following. The wallet is not deleted properly. 

![image](https://user-images.githubusercontent.com/65536965/105575599-16c8aa00-5d6d-11eb-9093-3978ef4f0fe2.png)

**Comment by UserMaxL** [comment]
Hi @izzycsy my issue I had here is solved now. 
On my old PC I had issues to get the new versions 2.1.4 and 2.1.15 running so I deleted all the app data (not only Blockchain data as this didn't help) and after restoring with the seed the old transactions are gone now. I know that's probably not the ideal solution for that problem, but I still wanted to keep you updated.

**Comment by izzycsy** [comment]
Hi @UserMaxL , update [v2.1.17](https://defichain.com/downloads/) is out.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
