### ISSUE TITLE
Wallet: Missing receive addresses

### ISSUE THREAD

**Issue by TTSIP** [DeFiCh/app#345]
### Issue Details

- **Current DeFi App Version:**
  -  2.1
- **Previous DeFi App Version:**
  - . 2.1.6 --> 2.1.0
- **Operating System (OS):**
  - Windows 10
4 -->
### Screenshot(s) / screen recording(s) of issue
![image](https://user-images.githubusercontent.com/76814941/105422071-6743e880-5c43-11eb-832e-a38af47e38a1.png)

![image](https://user-images.githubusercontent.com/76814941/105422102-7460d780-5c43-11eb-8696-c52c3a57efba.png)

![image](https://user-images.githubusercontent.com/76814941/105422139-86427a80-5c43-11eb-9904-bb997c198b44.png)

### Actual Behavior

```
1. Open the app
2. Go to wallet page
3. Click on DFI
4. Click Receive
5. Dont see my own wallet adress

```
-->

### Expected Behavior

i would like to se my wallet adress to copy

### App log / binary log / app config

[Apploggs.log](https://github.com/DeFiCh/app/files/5852533/Apploggs.log)
[Binary.log](https://github.com/DeFiCh/app/files/5852534/Binary.log)

**Comment by UserMaxL** [comment]
You need to click "+Neue Adresse" to get/create a new address to send to.

**Comment by TTSIP** [comment]
but why new adress ? i already have DFI @ the wallet so i should be have an adress already ?

**Comment by Capswiss** [comment]
Bei mir ist der gleiche Fehler. Weil die App 2.1.4 Probleme machte habe ich mit dem Seed neu installiert. Balances stimmen aber ich kann meine 3 Adressen nicht mehr sehen. Auch kann ich sie nicht manuell hinzufügen, Button ist grau. Aber ismine ist für alle true.

**Comment by UserMaxL** [comment]
Well, DeFi chain is built like Bitcoin and also here you usually create multiple receive addresses for a good reason:
https://support.blockchain.com/hc/en-us/articles/210353663-Why-are-my-bitcoin-and-bitcoin-cash-addresses-changing-

**Comment by izzycsy** [comment]
Hi @TTSIP  @Capswiss , update v2.1.11 is out <https://defichain.com/downloads/>.
Are your addresses back? Please send you app logs (include screenshots) again after upgrading. Thank you. 

@UserMaxL appreciate the help!

**Comment by TTSIP** [comment]
@izzycsy 

still the same issue with 2.1.11

here u can find the current logs

[Apploggs.log](https://github.com/DeFiCh/app/files/5856040/Apploggs.log)
[Binary.log](https://github.com/DeFiCh/app/files/5856041/Binary.log)

**Comment by Capswiss** [comment]
> Hi @TTSIP  @Capswiss , update v2.1.11 is out https://defichain.com/downloads/.
> Are your addresses back? Please send you app logs (include screenshots) again after upgrading. Thank you.
> 
> @UserMaxL appreciate the help!

@izzycsy Hi, thank you. 
I installed 2.1.11 but have problems starting the app. 
See issue: Update 2.1.11 - stop at 99.88% and slows down my Mac extremely without error message.
https://github.com/DeFiCh/app/issues/352
You can also see my log files there.

**Comment by TTSIP** [comment]
@Capswiss make sure u have enough disk space (C:) > 50 GB i had the same issue with more disc space it worked

**Comment by Capswiss** [comment]
> @Capswiss make sure u have enough disk space (C:) > 50 GB i had the same issue with more disc space it worked

Yes, I have 360 GB free space. I think this should be enough...

**Comment by izzycsy** [comment]
Hi @TTSIP @Capswiss logs well received, please give us time to investigate.

**Comment by TTSIP** [comment]
Same issue with 2.1.3
[Apploggs.zip](https://github.com/DeFiCh/app/files/5875955/Apploggs.zip)

**Comment by izzycsy** [comment]
Hi @TTSIP , thanks for the updated, please give us time to investigate this. Thank you. 

Hi @Capswiss , if you haven't updated your app, [v2.1.13](https://defichain.com/downloads/) is out.

**Comment by TTSIP** [comment]
@izzycsy yes 2.1.13 (newest version)

**Comment by TTSIP** [comment]
in the end the issue is always if u deninstall the defi app and delete all folders and afterwards u install the app completly new u have to create a new adress. This is very confusing for users which are not familiar with the bitcoin logic and is definitly not userfriendly imo this should be changed that i if i reinstall the wallet and right in my private key ... it should be possible that i can choose the adresses i would like to have to (Inclusive all adresses i created in the past)

**Comment by izzycsy** [comment]
Hi @TTSIP , you're right, that logic is already in place when you `restore wallet` as the _mnemonic seed_ + _backup wallet_ should save you addresses. Unless you `create new wallet` then addresses won't be present. Is your issue resolved on [v2.1.15](https://defichain.com/downloads/)?

**Comment by Capswiss** [comment]
> Hi @TTSIP , you're right, that logic is already in place when you `restore wallet` as the _mnemonic seed_ + _backup wallet_ should save you addresses. Unless you `create new wallet` then addresses won't be present. Is your issue resolved on [v2.1.15](https://defichain.com/downloads/)?

For me with the version v.2.1.15 on a Mac everything is going to my satisfaction. I was able to add the missing addresses manually.

**Comment by UserMaxL** [comment]
Hi @Capswiss, how did you add the addresses manually? Via mnemonic seed + backup wallet or is there a different approach?

**Comment by Capswiss** [comment]
> Hi @Capswiss, how did you add the addresses manually? Via mnemonic seed + backup wallet or is there a different approach?

Go in the App to the DFI Wallet, click on „receive“, click on „+ new Adresse“ and then unlock „create automatic new Adress“ now you can write your Adress. When the Write adress is your own, you now can click on something like „make“ i dont now the exact word of the button, i use the app in German

**Comment by izzycsy** [comment]
Hi all, for users who are facing this `Missing receive address`, rest assured you can manually add the addresses it back. In the future, you could make a copy of your wallet.dat folder — the wallet.dat is key to secure your wallet's information, we're introducing more security to it soon. In the mean time, providing the following steps for your reference:

1. **Save** the address externally (eg. copy & paste in Notes)
2. Make a copy of your **wallet.dat** folder

Location of wallet.dat: 
Windows — C: 
` \Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat`

Mac — Go to Folder: 
` /Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat`


<img width="626" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/108045239-2ee6cd00-707e-11eb-89e1-0fdd3aeb32ab.png">
