### ISSUE TITLE
Unable to send from wallet- Transitioned Eth

### ISSUE THREAD

**Issue by rxandr** [DeFiCh/app#349]
![ice_screen
[Archive.zip](https://github.com/DeFiCh/app/files/5853659/Archive.zip)
shot_20210121-205052](https://user-images.githubusercontent.com/25475060/105448181-aade2880-5c2a-11eb-9e2f-16343d0d1b5c.png)
![ice_screenshot_20210121-205052](https://user-images.githubusercontent.com/25475060/105448198-b0d40980-5c2a-11eb-8807-fb5367ed069a.png)

### Preflight Checklist

- [ ] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [ ] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  - 
- **Previous DeFi App Version:**
  - 
- **Operating System (OS):**
  -

**Comment by rxandr** [comment]
Sorry having a hard time reading post/edit
Not sure how or why I am unable to send.

I dont get the option to continue, may need some help please

**Comment by izzycsy** [comment]
Hi @rxandr , thanks for your feedback. The address you’re using is not a DeFiChain-friendly address. You can retrieve the DeFiChain address via <cakedefi.com>, try sending a small amount first to test.

1. Click on Balances in <cakedefi.com>
2. In the BTC row, click on Deposit button
3. You'll see the Transfer Network options `BTC` / `DeFi Blockchain`
4. Under the QR Code states your DeFi address, copy it
5. Go to DeFi app > BTC wallet > Send
6. Paste your DeFi address into `To address` field

<img width="375" alt="Click DeFiChain   BTC" src="https://user-images.githubusercontent.com/65014479/105479018-eb977980-5cde-11eb-836f-408251420c70.png">

 You may also turn to Cake’s telegram for Cake-related issues: 
[CakeDeFi Telegram (EN)](https://t.me/CakeDeFi_EN )
[CakeDeFi Telegram (DE)](https://t.me/CakeDeFi_DE)
