### ISSUE TITLE
Transaction history is not deleted with Reset Wallet.

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#351]
Hi

I ran the "Reset Wallet" function in my DeFi app. Then I created a new wallet and restarted the app. However, the past transactions of the deleted app are still displayed. 

![photo_2021-01-22_17-50-55](https://user-images.githubusercontent.com/65536965/105521744-95293b80-5cdc-11eb-9ac7-bdd84fbec822.jpg)

I have refrained from attaching a log file. I think this problem is easy to track. 

Windows 10
Version: 2.1.11
16GB RAM

**Comment by RobinTorque** [comment]
I have seen this error has already been reported:

https://github.com/DeFiCh/app/issues/344

**Comment by izzycsy** [comment]
Hi @RobinTorque , please send your app logs to <https://github.com/DeFiCh/app/issues/344>, thank you.
