### ISSUE TITLE
JS Errors occurs on token create page

### ISSUE THREAD

**Issue by sergejmueller** [DeFiCh/app#354]
### JS Errors
```
Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a child of <table>. Make sure you don't have any extra whitespace between tags on each line of your source code.
Warning: validateDOMNesting(...): <div> cannot appear as a child of <table>.
```

### Preflight Checklist
- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details
- **Current DeFi App Version:**
  - 2.1.12
- **Previous DeFi App Version:**
  - 2.1.11
- **Operating System (OS):**
  - MacOS

### Screenshot(s) / screen recording(s) of issue
Video: https://siasky.net/_BkszXZ5WJFCqplSJnnY3Yf0GhVR2v0Xd-MWIuLQ87b1cA
Screenshot: https://siasky.net/fAWw92x8708QyUfq10qvT3Z-J-7oW3JveDhvvAuw-66Llw

### Actual Behavior
1. Start the app
2. Open Developer Tools
3. Go to `Tokens`
4. Click `Create token` button
5. See console output

### Expected Behavior
No errors occurs

### Logs
https://github.com/DeFiCh/app/files/5859924/Archiv.zip

**Comment by izzycsy** [comment]
Hi @sergejmueller , thanks for the feedback. Kindly send your app logs. This will provide more insight for the investigation. Thank you.

**Comment by sergejmueller** [comment]
> Hi @sergejmueller , thanks for the feedback. Kindly send your app logs. This will provide more insight for the investigation. Thank you.

I saw you collect app logs, I thought you didn't need one for JS errors.
Logs attached now: [Archiv.zip](https://github.com/DeFiCh/app/files/5859924/Archiv.zip)

**Comment by izzycsy** [comment]
Hi @sergejmueller , thank you, well received.
