### ISSUE TITLE
JS Error on the "verify mnemonic seed" page

### ISSUE THREAD

**Issue by sergejmueller** [DeFiCh/app#355]
### JS Error
```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `VerifyMnemonic`.
```

### Preflight Checklist
- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  - 2.1.12
- **Previous DeFi App Version:**
  - 2.1.11
- **Operating System (OS):**
  - MacOS

### Screenshot(s) / screen recording(s) of issue
Video: https://siasky.net/_BFD91wGT8ZynRvuhgyc9yCyVK95k4E8OLKOw1bAKjGDKA
Screenshot: https://siasky.net/fAI1xFjLjzPo7a66zeZKOyrwrGHiqDtQOl8ndNiBzBBcwQ

### Actual Behavior
```
1. Start and open the app
2. Open Developer Tools
2. Go to wallet page
3. Click `create a new wallet`

4. Click on `I’ve copied down the 24 words in the exact order`
5. See the console
```

### Expected Behavior
No JS error occurs

### Logs
[Archiv.zip](https://github.com/DeFiCh/app/files/5860543/Archiv.zip)

**Comment by sergejmueller** [comment]
@izzycsy If you can tell me how to delete my wallet to create a new one, I can create a app log for this issue ;)

**Comment by izzycsy** [comment]
Hi @sergejmueller , I highly recommend that you wait for the team to investigate this. If you proceed, it's at your own risk and we'll not be responsible for any lost. You may refer to the steps below: 

In app directory: 
1. Windows — C:  \Users\<username>\AppData\Roaming\DeFi Blockchain\wallets 
2.  **Make a copy** the wallets folder, store it safe somewhere else on your PC
3. Delete `DeFi` folder
4. Delete `defi-app` folder

<img width="621" alt="DeFi folder - delete all except walletdat" src="https://user-images.githubusercontent.com/65014479/105574457-a6874c00-5d9f-11eb-9c7a-dfb26f976641.png">

<img width="624" alt="defi-app folder - delete all" src="https://user-images.githubusercontent.com/65014479/105574459-a8510f80-5d9f-11eb-88ad-fb9ccefe6bcb.png">

Also, kindly note that you **should not** have 2 apps in one PC.

**Comment by sergejmueller** [comment]
@izzycsy Thanks for your support. Logs are attached.

**Comment by izzycsy** [comment]
Hi @sergejmueller , update [v2.1.15](https://defichain.com/downloads/) is out.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, provide new information (include screenshots) and app logs. Thank you.

**Comment by sergejmueller** [comment]
Solved & Closed.
