### ISSUE TITLE
DEXd coin cannot be transferred or recognized from one backed-up wallet to the next

### ISSUE THREAD

**Issue by rxandr** [DeFiCh/app#358]
transaction sitting in limbo, un-movable
![MAC DFI2](https://user-images.githubusercontent.com/25475060/105564400-ca328f80-5cd6-11eb-8faf-927e30aa1553.png)
![ice_screenshot_20210122-171354](https://user-images.githubusercontent.com/25475060/105564404-d0287080-5cd6-11eb-888f-2a215fa951a4.png)
![Eth wallet](https://user-images.githubusercontent.com/25475060/105564409-d4ed2480-5cd6-11eb-8ff7-1ac90da41a4e.png)
![ice_screenshot_20210122-065923](https://user-images.githubusercontent.com/25475060/105564416-da4a6f00-5cd6-11eb-925f-df5002492a98.png)
 Why the last screen, same wallet doesn't show ETH balance?

Anyone study my logs
[Archive.zip](https://github.com/DeFiCh/app/files/5859406/Archive.zip)

**Comment by izzycsy** [comment]
Hi @rxandr , update v2.1.11 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, please leave a comment on <https://github.com/DeFiCh/app/issues/301> with your new information (include screenshots) and app logs. Thank you.
