### ISSUE TITLE
V 2.1.12 does not show tokens

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#360]
I have installed version 2.1.12. My tokens have disappeared. 

![photo_2021-01-23_10-52-50](https://user-images.githubusercontent.com/65536965/105575112-673e0880-5d69-11eb-9455-099ca45af58f.jpg)
![photo_2021-01-23_10-52-13](https://user-images.githubusercontent.com/65536965/105575113-6907cc00-5d69-11eb-9016-c4fbef1589d3.jpg)

A reboot did not fix the problem.

Windows 10
16GB RAM

**Comment by RobinTorque** [comment]
Access via the console does not work either. 
![image](https://user-images.githubusercontent.com/65536965/105575306-fbf53600-5d6a-11eb-911f-b56ef15da563.png)

**Comment by RobinTorque** [comment]
Problem solved. These tokens are not from the same wallet. They are from another wallet which I had installed before. The reset wallet command does not seem to delete everything. So that would be a different problem with the reset function.

**Comment by monstrobishi** [comment]
@izzycsy even though this is closed we should investigate as we do not want to show balance of old wallet

**Comment by izzycsy** [comment]
@monstrobishi  kindly refer to issue `New Wallet: > tx history from old wallet displayed
` <https://github.com/DeFiCh/app/issues/344>.
