### ISSUE TITLE
Error: Got error in handleFallbackSendToken: Insufficient token in account 

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#363]
Hello

I get this error message for over 4 weeks. Even the latest version 2.1.12 does not fix this problem. 

I own a few tokens. DGT, JULE, GOLD and others. I can not send these tokens 100%. A partial quantity is possible, but not the whole quantity. 

So, for example, I own one DGT. I cannot send this DGT. A subset like 0.5 DGT is possible, but not the whole DGT. 

In this example, I own 48 GOLD. I am trying to send these.

![photo_2021-01-23_13-02-00](https://user-images.githubusercontent.com/65536965/105578188-9f037b00-5d7e-11eb-8dc6-97235ffa86f2.jpg)

![photo_2021-01-23_13-02-30](https://user-images.githubusercontent.com/65536965/105578222-cfe3b000-5d7e-11eb-9cc4-0b2c7f8d883c.jpg)

And then I get an error message. 

![photo_2021-01-23_13-02-48](https://user-images.githubusercontent.com/65536965/105578237-e0942600-5d7e-11eb-9546-820e8ef21679.jpg)

Sending via the Console is possible without any problems. 

![photo_2021-01-23_13-17-21](https://user-images.githubusercontent.com/65536965/105578248-f570b980-5d7e-11eb-97b4-5725cd6ea437.jpg)

This problem exists on Windows and on Mac. 

The log files are attached.
[210123 App Confic V2.zip](https://github.com/DeFiCh/app/files/5860319/210123.App.Confic.V2.zip)

**Comment by RobinTorque** [comment]
I have entered the seed on another device and there the problem is exactly the same. 

I would be happy to share my seed with you so that you can understand the problem. Send me a message on Telegram @RobinTorque

**Comment by izzycsy** [comment]
Hi @RobinTorque , thanks for your feedback. Could you send your logs please? The team will investigate. We would never ask for your mnemonic seed phrase, please keep it safe, I suggest that you remove your Telegram username in the previous comment. Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/105669706-c0996980-5f1a-11eb-93a3-875e69bcb07e.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/105669713-c3945a00-5f1a-11eb-9e1f-04cb96ca8c1f.png">

**Comment by RobinTorque** [comment]
I installed the new version 2.1.13 and checked the problem on my computer several times. It seems to be fixed and everything works.
