### ISSUE TITLE
Restored wallet > addresses missing

### ISSUE THREAD

**Issue by iceman999sod** [DeFiCh/app#370]
- **Current DeFi App Version:** 2.1.12
- **Previous DeFi App Version:** 2.1.11
- **Operating System (OS):** Windows 10

I had to reinstall my Windows System. Afterwards I installed DeFi app 2.1.11 and updated it to 2.1.12.

Loaded my backup file (I have overwritten it with every new update). Coins are there, but I cannot see my receiving adress. Therefore I cant perform LM and the DEX. 

![missing receiving adress](https://user-images.githubusercontent.com/77898625/105614966-2bd52580-5dcd-11eb-98ba-7b7d216285b6.jpg)

I typed in the commands for listing the tokens, followed by the command to get the associated address:

gettokenbalances {} true true
  "DFI": xxxxxx
  "BTC": xxxxx
  "BTC-DFI": xxxxx

listaccounts {} false false true
  {
    "key": "xxxxxxxxxxx",
    "owner": "xxxxxxxxxxxxx",
    "amount": "xxxxxxx@DFI"
  },
  {
    "key": "xxxxxxxxx",
    "owner": "xxxxxxxxx",
    "amount": "xxxxxxxx@BTC"
  },
  {
    "key": "xxxxxxx",
    "owner": "xxxxxxxxxx",
    "amount": "xxxxxxxx@BTC-DFI"
  }
]

There i see my adress. But it doesnt show me the receiving adress to receive DFI, to use Liquid Mining or the DEX  (as shown in the pic above). 

### App log / binary log / app config
[applog.log](https://github.com/DeFiCh/app/files/5861155/applog.log)
[binarylog.log](https://github.com/DeFiCh/app/files/5861156/binarylog.log)

**Comment by izzycsy** [comment]
Hi @iceman999sod , thanks for your feedback, screenshots and logs. Please give us time to investigate this.

**Comment by izzycsy** [comment]
Hi @iceman999sod , update [v2.1.15](https://defichain.com/downloads/) is out.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, provide new information (include screenshots) and app logs. Thank you.

**Comment by izzycsy** [comment]
Hi @iceman999sod , the team investigated your issue, solution to your issue is that you've to manually add your addresses again.
