### ISSUE TITLE
Terminate called without an active exception 

### ISSUE THREAD

**Issue by henryb694** [DeFiCh/app#371]
### Preflight Checklist

- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  -  2.1.12
- **Previous DeFi App Version:** 
  -  2.1.6/2.1.10/2.1.11
- **Operating System (OS):**
  -  Windows 7

**Comment by henryb694** [comment]
Is there the problem "terminate called without an active exception"? If I then let the app continue to load, the old problem "unable to start blockchain" comes up ... Both to version 2.1.6, as well as 2.1.10, 2.1.11, 2.1.12. 

Had the paging file at 32000. 

Then I changed it back, but the app still doesn't load.

Also reinstalled all 4 versions. 

Before i made the paging file at 32000, 2.1.6 worked. 
But now since i swapped it back, no of the versions even start.
![Screenshot_20210124-120455_Video Player](https://user-images.githubusercontent.com/77920440/105628305-6b872600-5e3c-11eb-8723-f8e05b5d557c.jpg)

**Comment by izzycsy** [comment]
Hi @henryb694 , thanks for your feedback, could you send your app logs please?

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/105827611-2a8a3f80-5ffd-11eb-9935-fe2a5d29563c.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/105827618-2cec9980-5ffd-11eb-917a-7a85136d483f.png">

**Comment by izzycsy** [comment]
Hi @henryb694 , update [v2.1.13](https://defichain.com/downloads/) is out.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
