### ISSUE TITLE
Linux: sync stops at 99%+ > increases memory usage

### ISSUE THREAD

**Issue by BenThrottle85** [DeFiCh/app#372]
### Preflight Checklist

- [X ] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [X ] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  - 2.1.12
- **Previous DeFi App Version:**
  - 2.1.11
- **Operating System (OS):**
  - Lubuntu 20.04 LTS (VirtualBox), 12GB RAM, 8GB Swap File

### Screenshot(s) / screen recording(s) of issue

![unable to start blockchain](https://user-images.githubusercontent.com/68747114/105628612-35e33c80-5e3e-11eb-97f3-6e42cb142b0a.JPG)
![unable to start blockchain_2](https://user-images.githubusercontent.com/68747114/105629408-1dc1ec00-5e43-11eb-9321-2f930f64d784.JPG)

- RAM usage is increasing
- HDD is working
- Thread time (Zeit) stands still most of the time?

### Actual Behavior

I started syncing yesterday evening.
It was pretty fast but at about 90%-95% it became very slow and the RAM usage increased dramatically.
Then I closed the app without shuting down the OS. The next morning I started the app again. The RAM usage increased dramatically again. After a while I got the message "unable to start blockchain".

### App log / binary log / app config

I will try it again and post all the logs if possible.

[app logs.zip](https://github.com/DeFiCh/app/files/5862112/app.logs.zip)

### Video
I made a little video. Maybe it helps
https://drive.google.com/file/d/1yR0ltcgabaZjbuNNqwZhXgbGFFjPZjYz/view?usp=sharing

**Comment by nick-preda** [comment]
App version 2.1.14
mine isn't even synching to the blockchain

<img width="224" alt="Schermata 2021-01-24 alle 13 25 37" src="https://user-images.githubusercontent.com/4056857/105630156-ad699980-5e47-11eb-8bac-98864217d105.png">


have been trying to "reindex", tried different versions of the app
still won't start

macOS Big Sur, on macbook air m1

logs from the app:
[binary_logs.log](https://github.com/DeFiCh/app/files/5862187/binary_logs.log)
[app_logs.log](https://github.com/DeFiCh/app/files/5862188/app_logs.log)

**Comment by BenThrottle85** [comment]
After increasing the swap file to 16GB it worked.
Seems that we still have memory issues?! Thought it was fixed.

**Comment by BenThrottle85** [comment]
> App version 2.1.14
> mine isn't even synching to the blockchain
> 
> <img alt="Schermata 2021-01-24 alle 13 25 37" width="224" src="https://user-images.githubusercontent.com/4056857/105630156-ad699980-5e47-11eb-8bac-98864217d105.png">
> 
> have been trying to "reindex", tried different versions of the app
> still won't start
> 
> macOS Big Sur, on macbook air m1
> 
> logs from the app:
> [binary_logs.log](https://github.com/DeFiCh/app/files/5862187/binary_logs.log)
> [app_logs.log](https://github.com/DeFiCh/app/files/5862188/app_logs.log)

I'm not sure if the app is working with the new M1 chipset.

**Comment by nick-preda** [comment]
> > App version 2.1.14
> > mine isn't even synching to the blockchain
> > <img alt="Schermata 2021-01-24 alle 13 25 37" width="224" src="https://user-images.githubusercontent.com/4056857/105630156-ad699980-5e47-11eb-8bac-98864217d105.png">
> > have been trying to "reindex", tried different versions of the app
> > still won't start
> > macOS Big Sur, on macbook air m1
> > logs from the app:
> > [binary_logs.log](https://github.com/DeFiCh/app/files/5862187/binary_logs.log)
> > [app_logs.log](https://github.com/DeFiCh/app/files/5862188/app_logs.log)
> 
> I'm not sure if the app is working with the new M1 chipset.
> There is no version 2.1.14 I think. Scam?

![image](https://user-images.githubusercontent.com/4056857/105634809-34c30700-5e60-11eb-889a-b31fd8146102.png)

wrote it badly, 2.1.12

**Comment by amkbra123** [comment]
> After increasing the swap file to 16GB it worked.
> Seems that we still have memory issues?! Thought it was fixed.

Hey I have the same problem. Can you tell me how increased it and which file exactly?

**Comment by BenThrottle85** [comment]
> > After increasing the swap file to 16GB it worked.
> > Seems that we still have memory issues?! Thought it was fixed.
> 
> Hey I have the same problem. Can you tell me how increased it and which file exactly?

In my case (Lubuntu Linux) this tutorial worked for me --> https://bogdancornianu.com/change-swap-size-in-ubuntu/

**Comment by nick-preda** [comment]
finally synchronized, on M1. now having other troubles 😄

**Comment by izzycsy** [comment]
Hi @BenThrottle85 @amkbra123 , thanks for your feedback, please give us time to investigate the issue. 

Hi @nick-preda , there are other Mac users facing a the same issue <https://github.com/DeFiCh/app/issues/352>. 

I'll keep this thread open for Linux users in the mean time.

**Comment by dieterich-m** [comment]
If not already mentioned somewhere, the same issue also applies to the Win App (Win 10).

**Comment by izzycsy** [comment]
Hi @dieterich-m , not mentioned yet for Windows at the moment, but well noted on your feedback.

Hi @nick-preda @BenThrottle85 @amkbra123 , update [v2.1.13](https://defichain.com/downloads/) is out.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, provide new information (include screenshots) and app logs. Thank you.

**Comment by dieterich-m** [comment]
I've already downloaded  v2.1.13 yesterday, but the issue is atill there. This issue prevents from adding new liquidity to the pool: "Cannot create transactions while still in Initial Block Download"
Should a separate thread be created for Win?

**Comment by izzycsy** [comment]
Hi @dieterich-m , do you mean this <https://github.com/DeFiCh/app/issues/325>? If yours is different, you may open a new issues.

**Comment by dieterich-m** [comment]
Hi, I assume, that #325 describes the root issue.
If that one (related to the mem leak) is solved, the rest might work again.
I am waiting for a resolution to #325.

**Comment by izzycsy** [comment]
Hi @dieterich-m , okay do leave a comment there so Github will notify you when I tag you in the comment.

**Comment by Anlien75** [comment]
Same problem.

Windows: sync stops at 99.95%,> node is disconnected #Network Error 500

![image](https://user-images.githubusercontent.com/76808716/106051739-23406000-60e9-11eb-8add-c4f4d8c167e2.png)

**Comment by izzycsy** [comment]
Hi @Anlien75 , could you send your screenshot & logs to [`Windows: sync stops at 99%+ > node is disconnected`](https://github.com/DeFiCh/app/issues/325) please. Thank you.

**Comment by izzycsy** [comment]
Hi @nick-preda @BenThrottle85 @amkbra123 , the team reviewed your logs, it seems that the issue you're facing could be due to the block being stalled at block 597924 yesterday, which can cause the node to disconnect, hence not a ram issue. The solution to this is wait for the block to sync to 100% or try `Reindex Option` in Settings. If `Reindex option` does not work, you may reopen this issue, kindly send screenshots / app logs.

Hi @dieterich-m @arnaudom , currently it seems that some windows-users are facing the issue [Windows: sync stops at 99%+ > node is disconnected](https://github.com/DeFiCh/app/issues/325). Take a screenshot of your activity monitor and send it in that thread — attached is an example.

<img width="734" alt="Activity Monitor" src="https://user-images.githubusercontent.com/65014479/106120048-d7e18c80-6190-11eb-9cdf-36e6448bdebf.png">

**Comment by dieterich-m** [comment]
Hi, I found the following comment in #352
+++++
Hi Bella
The root cause of the issue might be here: https://www.reddit.com/r/defiblockchain/comments/l765tb/fix_for_ram_bug_and_corrupt_blockchain/
Great troubleshoot from Kracht (Sp0nde on reddit).
Please share with developers.
Thx
Goran
+++++
This solves the issue in Win10 for me.
