### ISSUE TITLE
Can't swap any DFI to other token

### ISSUE THREAD

**Issue by pspiess** [DeFiCh/app#373]
After installation a fresh new installation of the DeFi app, I want to swap my DFI token with another Token ETH, BTC, USDT
I'm always getting that error "Etwas lief schief"

### Preflight Checklist
- [X] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [X] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details
- **Current DeFi App Version:**
2.1.12

- **Operating System (OS):**
Windows 10

### Screenshot(s) / screen recording(s) of issue
![swap-error](https://user-images.githubusercontent.com/6769565/105630190-f0c40800-5e47-11eb-9d32-26c5ac59654a.JPG)

### Actual Behavior
```
1. Open the app
2. Go to DEX
3. Select DFI (Von)
4. Select BTC (In)
5. Click on Max in "Von" Token
5. Unable to Swap "Etwas lief schief"
```

### Expected Behavior
I expect to see the information for swapping my tokens.

### App log / binary log / app config
[app.log](https://github.com/DeFiCh/app/files/5862202/app.log)

**Comment by izzycsy** [comment]
Hi @pspiess , thanks for your feedback, regarding the issue `DEX: Something went wrong`, I'll link you to <https://github.com/DeFiCh/app/issues/280> which we can further discuss on the problem. We would like to keep same issues in one thread. Logs well received. Thank you.
