### ISSUE TITLE
Changing the display settings "Display amounts in unit" to "fi" does not change the unit, also changes the currency

### ISSUE THREAD

**Issue by thunderstorm99** [DeFiCh/app#374]
### Preflight Checklist

- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  - Version 2.1.12 (2.1.12)
- **Operating System (OS):**
  - macOS 11.1 (20C69)

### Screenshot(s) / screen recording(s) of issue
![Screen Shot 2021-01-24 at 20 41 27](https://user-images.githubusercontent.com/3219279/105641899-bc237100-5e86-11eb-9ab8-930b37c6f6a1.png)
![Screen Shot 2021-01-24 at 20 41 35](https://user-images.githubusercontent.com/3219279/105641904-c04f8e80-5e86-11eb-8faf-b60501bb748f.png)

### Actual Behavior

1. Open the app
1. Go to settings
1. Click on Display
1. Change `Display amounts in unit` `DFI` to `fi`
1. Click on Wallet
1. The currency symbol changed to fi and the amount is not displayed in fi

### Expected Behavior
When switching from DFI to fi, the amount in your wallet should be multiplied by 100,000,000 (as mentioned in the subtext `1 DFI = 100,000,000 fi`

### App log / binary log / app config
No logs provided. This most probably wasn't programmed yet.

**Comment by izzycsy** [comment]
Hi @thunderstorm99 , update [v2.1.17](https://defichain.com/downloads/) is out. 
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.

**Comment by thunderstorm99** [comment]
This did indeed not fix the problem. We need to re open it again

**Comment by izzycsy** [comment]
Hi @thunderstorm99 , I just checked with the team, they are planning to remove the option of changing to `fi`, it's currently not released yet on v2.1.17.

**Comment by thunderstorm99** [comment]
Okay, then this would "solve" this issue. I guess we can leave the issue closed.
