### ISSUE TITLE
Update policy

### ISSUE THREAD

**Issue by spacie2136** [DeFiCh/app#376]
Almost every morning i wake up i get the message Update available. Thats usually a great thing!

BUT... every day something stops working in that new version! Today in 2.1.12 on my Mac i was not able to add liquidity. Switched over to 2.1.11 an woops... worked!

Actually i have the 4 different versions installed to be able to use everything :-/

Please introduce some testing of the whole APP before publishing as final version. Publishing an untested APP is just not right and puts some nasty shadow on this nice project!

**Comment by izzycsy** [comment]
Hi @spacie2136 , thanks for your feedback. Do you have a screenshot of your error? We do test the entire app before announcing its official. However due to different circumstances, a minority of users might face new issues — hence the purpose of this Github page. 

Kindly send a screenshot on your issue, and I'll redirect if its an existing issue or if it's a new one we can continue to use this thread.

**Comment by BenThrottle85** [comment]
+1

**Comment by spacie2136** [comment]
> Hi @spacie2136 , thanks for your feedback. Do you have a screenshot of your error? We do test the entire app before announcing its official. However due to different circumstances, a minority of users might face new issues — hence the purpose of this Github page.
> 
> Kindly send a screenshot on your issue, and I'll redirect if its an existing issue or if it's a new one we can continue to use this thread.

I was not able to reproduce the error from this morning. But something new just happened.

<img width="2006" alt="Bildschirmfoto 2021-01-25 um 16 09 26" src="https://user-images.githubusercontent.com/19873137/105732153-11638f00-5f28-11eb-9bb4-45634fe1c2fc.png">

**Comment by izzycsy** [comment]
Hi @spacie2136 , you mentioned that you've 4 different versions installed to run everything, are your 4 version all in one PC? 

Thanks for the above screenshot, I've inform the team.

**Comment by RobinTorque** [comment]
I see it the same way as @spacie2136 . New versions are insufficiently tested. You don't need a screenshot to see that.

**Comment by izzycsy** [comment]
Hi @RobinTorque , you're right and I agree, the reason for my question to @spacie2136 is because there have been cases where 1 user installs >1 defi app on their PC and it led to many issues, so if that were the case, the user simply has to stick to only 1 app per PC.

Hi @Leon2023 agreed as well, we did think of setting up a Telegram group with some windows users, I'll coordinate with the Telegram community manager and he'll contact some of you who are interested to help and can commit. More details will be shared then.

**Comment by spacie2136** [comment]
> Hi @RobinTorque , you're right and I agree, the reason for my question to @spacie2136 is because there have been cases where 1 user installs >1 defi app on their PC and it led to many issues, so if that were the case, the user simply has to stick to only 1 app per PC.
> 
> Hi @Leon2023 agreed as well, we did think of setting up a Telegram group with some windows users, I'll coordinate with the Telegram community manager and he'll contact some of you who are interested to help and can commit. More details will be shared then.

Hi again,
so right now i only have 2.1.15 installed. My Problem startet with 2.1.14. I'm on OsX.

Today a new problem appeared! I'm scared as hell right now! This morning i was able to gather some Doge token and do some Arbitrage using DEX in the app. Right now im not able to send any coin or token from my wallet anywhere!

Everytime i try, it says "Transaction completed" and gives me a Transaction ID... for example this one... b9aa31644a11cb8a639c595f423deccc35dc6013dd76b6ca9ae5b79d6be81397

This ID was generated trying to convert 10 DFI into BTC with DEX.
<img width="1009" alt="Bildschirmfoto 2021-01-30 um 17 51 28" src="https://user-images.githubusercontent.com/19873137/106363990-cb416d80-6323-11eb-97b6-4054037af6ec.png">

But it will never get any confirmation!
<img width="1013" alt="Bildschirmfoto 2021-01-30 um 17 52 22" src="https://user-images.githubusercontent.com/19873137/106364014-e90ed280-6323-11eb-84b7-1c026991ef80.png">

app.log:
[2021-01-30 17:44:34.595] [IPC-RENDERER-info] [handlePoolSwap] "Starting"
[2021-01-30 17:44:34.685] [IPC-RENDERER-info] [handlePoolSwap] "1. Address dHp2D9geAbCtrKtcyCQJ7AXiHpskQ6XoaR Amount 225.24254478"
[2021-01-30 17:44:34.687] [IPC-RENDERER-info] [handlePoolSwap] "Refresh Pool Swap"
[2021-01-30 17:44:34.692] [IPC-RENDERER-info] [handlePoolSwap] "Starting Pool Swap RPC"
[2021-01-30 17:44:34.864] [IPC-RENDERER-info] [handlePoolSwap] "b9aa31644a11cb8a639c595f423deccc35dc6013dd76b6ca9ae5b79d6be81397"

bin.log:
2021-01-30T17:44:34Z [default wallet] keypool added 1 keys (1 internal), size=2000 (1000 internal)
2021-01-30T17:44:34Z [default wallet] keypool reserve 3120
2021-01-30T17:44:34Z [default wallet] keypool keep 3120
2021-01-30T17:44:34Z [default wallet] Fee Calculation: Fee:25208 Bytes:185 Needed:25208 Tgt:6 (requested 6) Reason:"Conservative Double Target longer horizon" Decay 0.99520: Estimation: (131501 - 159841) 100.00% 21.7/(21.7 0 mem 0.0 out) Fail: (0 - 131501) 100.00% 12.3/(12.3 0 mem 0.0 out)
2021-01-30T17:44:34Z [default wallet] Fee Calculation: Fee:30931 Bytes:227 Needed:30931 Tgt:6 (requested 6) Reason:"Conservative Double Target longer horizon" Decay 0.99520: Estimation: (131501 - 159841) 100.00% 21.7/(21.7 0 mem 0.0 out) Fail: (0 - 131501) 100.00% 12.3/(12.3 0 mem 0.0 out)
2021-01-30T17:44:34Z [default wallet] AddToWallet bce7608de49451f7d3dd5305e880329c8352b462ec33f2815298c11538f020ea  new
2021-01-30T17:44:34Z [default wallet] AddToWallet b9aa31644a11cb8a639c595f423deccc35dc6013dd76b6ca9ae5b79d6be81397  new


I can not swap my money, i can not add my money to liquidity pools and i can not transfer my money... Did i lose my money???

**Comment by spacie2136** [comment]
Now i am scared as hell... i installed wallet on another system (Ubuntu) and introduced my seed. And voila... not my wallet :-/

**Comment by monstrobishi** [comment]
Hi @spacie2136 ,

The transactions not appearing on the explorer does not mean you lost funds. It simply means the transactions were not processed. Transactions are either processed or not processed, there's no "halfway" state where it gets stuck in the middle. It just means the state of your wallet is the same as before you made the transactions.

The node on the PC you made the transactions simply thinks the transactions took place, this is common on blockchain it's a distributed system.

What differences do you see on the ubuntu system? it's probably just showing the correct state before the transactions were applied.

**Comment by izzycsy** [comment]
Hi @spacie2136 , update [v2.3.0](https://github.com/DeFiCh/app/releases/tag/v2.3.0) is out, this is a mandatory update due to node Dakota Upgrade 1.5.0.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
