### ISSUE TITLE
Max Button in Liquidity mining

### ISSUE THREAD

**Issue by spacie2136** [DeFiCh/app#379]
Usuing OSX with version 2.1.12

The two MAX buttons in liquidity mining give different results! That makes no sense because we are providing a equal pair.

I see two options... Make them work equal or remove one of the MAX buttons.

**Comment by izzycsy** [comment]
Hi @spacie2136 it's actually designed that way bec each token is of a different value. eg. 1 BTC = USD 30,000 and 1 DFI = 0.00007881 BTC. Hence the `MAX` represents the what you want to max-out when pairing / swapping. For future enquiries on functions you may ask the community on [DeFiChain Telegram (EN)](https://t.me/defiblockchain).
