### ISSUE TITLE
Invalid block 597925

### ISSUE THREAD

**Issue by Anlien75** [DeFiCh/app#381]
Hello,

have today made the update to the latest version 2.1.12. 

Unfortunately, the synchronization always breaks at 99.91%. But the blocks themselves are synchronized (598463 at 20:05).
Have deleted the DeFi app and reloaded again.

What else can I do to access my wallet?

Greetings Andy

**Comment by cRuuZaR** [comment]
Same issue here with Mac

**Comment by domo88** [comment]
same here with windows 10 and app version 2.1.12. stops at block 597924: 
![image](https://user-images.githubusercontent.com/77995293/105767580-797f9880-5f5b-11eb-89a3-86d97385fb56.png)

**Comment by Jacobsieler8888** [comment]
I have the same problem with windows 10.  Except mine will not sync after block 597952.  Can anyone help?

**Comment by madeinusmate** [comment]
same, stuck at block 597924. tried multiple releases they get all stuck at the same block.
The behavior appeared first after 9:30 PM SG Time on Jan 25th.

**Comment by DanielZirkel** [comment]
Same issue on my side.
It seems that the synchronization is stucked at the block of the triggered blockchain update.
![image](https://user-images.githubusercontent.com/68841661/105803516-f5023980-5f9d-11eb-9db7-b81b16469874.png)
I also tried to use the CLI and here it shows me an invalid block 597925
![image](https://user-images.githubusercontent.com/68841661/105803587-195e1600-5f9e-11eb-9fb4-e9e4026652c7.png)
Here is also my Log-File from the App
[AppLog20210126.log](https://github.com/DeFiCh/app/files/5871313/AppLog20210126.log)

**Comment by uzyn** [comment]
Can you post the output of `defi-cli getblockchaininfo` please?

**Comment by DanielZirkel** [comment]
> Can you post the output of `defi-cli getblockchaininfo` please?

Here are the wanted results 
![image](https://user-images.githubusercontent.com/68841661/105806834-fdaa3e00-5fa4-11eb-9444-9df7f7710629.png)
![image](https://user-images.githubusercontent.com/68841661/105806847-0438b580-5fa5-11eb-9b12-51b58e0a9191.png)
The node was running the whole time. If the second command should be executed without running it, please let me know.

**Comment by Jacobsieler8888** [comment]
DOES ANYONE KNOW OF A FIX FOR THIS PROBLEM YET??

**Comment by monstrobishi** [comment]
Hi @DanielZirkel I'm adding a checkpoint for this block to the next build it may help with this issue

**Comment by madeinusmate** [comment]
@uzyn 

`defi-app_v2.1.6
defi-cli getblockchaininfo
{
  "chain": "main",
  "blocks": 597924,
  "headers": 597924,
  "bestblockhash": "e229dfaec32944b3f476da1f1981a3ccc650619e4ff7f38823d5ed68477564d2",
  "difficulty": 216379423.5508064,
  "mediantime": 1611581057,
  "verificationprogress": 1,
  "initialblockdownload": false,
  "chainwork": "00000000000000000000000000000000000000000000ab3aab5e823f18120bcd",
  "size_on_disk": 574744815,
  "pruned": false,
  "softforks": {
    "bip34": {
      "type": "buried",
      "active": true,
      "height": 0
    },
    "bip66": {
      "type": "buried",
      "active": true,
      "height": 0
    },
    "bip65": {
      "type": "buried",
      "active": true,
      "height": 0
    },
    "csv": {
      "type": "buried",
      "active": true,
      "height": 1
    },
    "segwit": {
      "type": "buried",
      "active": true,
      "height": 0
    },
    "amk": {
      "type": "buried",
      "active": true,
      "height": 356500
    },
    "bayfront": {
      "type": "buried",
      "active": true,
      "height": 405000
    }
  },
  "warnings": ""
}`

**Comment by Jacobsieler8888** [comment]
WHAT DOES THAT MEAN?

**Comment by monstrobishi** [comment]
@madeinusmate you must be on app version minimum 2.1.9 to sync with blockchain, that's unrelated to this issue thanks

**Comment by Jacobsieler8888** [comment]
Does anyone know how to fix this problem yet?

**Comment by madeinusmate** [comment]
> @madeinusmate you must be on app version minimum 2.1.9 to sync with blockchain, that's unrelated to this issue thanks

tested on multiple releases. 
2.1.6 was the most recent release that allowed to provide liquidity without "() recipient address..." error.

here you go with  2.1.12


> defi-app_v2.1.12
> defi-cli getblockchaininfo
> {
>   "chain": "main",
>   "blocks": 597924,
>   "headers": 597924,
>   "bestblockhash": "e229dfaec32944b3f476da1f1981a3ccc650619e4ff7f38823d5ed68477564d2",
>   "difficulty": 216379423.5508064,
>   "mediantime": 1611581057,
>   "verificationprogress": 0.9901780275247484,
>   "initialblockdownload": false,
>   "chainwork": "00000000000000000000000000000000000000000000ab3aab5e823f18120bcd",
>   "size_on_disk": 574744815,
>   "pruned": false,
>   "softforks": {
>     "bip34": {
>       "type": "buried",
>       "active": true,
>       "height": 0
>     },
>     "bip66": {
>       "type": "buried",
>       "active": true,
>       "height": 0
>     },
>     "bip65": {
>       "type": "buried",
>       "active": true,
>       "height": 0
>     },
>     "csv": {
>       "type": "buried",
>       "active": true,
>       "height": 1
>     },
>     "segwit": {
>       "type": "buried",
>       "active": true,
>       "height": 0
>     },
>     "amk": {
>       "type": "buried",
>       "active": true,
>       "height": 356500
>     },
>     "bayfront": {
>       "type": "buried",
>       "active": true,
>       "height": 405000
>     },
>     "clarkequay": {
>       "type": "buried",
>       "active": true,
>       "height": 595738
>     }
>   },
>   "warnings": ""
> }

**Comment by Jacobsieler8888** [comment]
@madeinusmate what do you mean when you said "here you go with 2.1.12"?  Is that a fix to the issue?

**Comment by monstrobishi** [comment]
@Jacobsieler8888 he's saying he's also stuck on 2.1.12, he is a user like you, we will be releasing 2.1.13 today which should hopefully fix this issue.

**Comment by Jacobsieler8888** [comment]
okay.  Do you know what time today 2.1.13 will be released?

**Comment by monstrobishi** [comment]
Within the next 3-4 hours

**Comment by Jacobsieler8888** [comment]
Okay.  Thank you very much for your help.

**Comment by domo88** [comment]
worked for me after: Settings -> Reindex-Option. Now fully synced with 2.1.12 on W10.

**Comment by monstrobishi** [comment]
For those facing the issue, are you able to try with this pre-release build? we would like to confirm before making the release official: [Download v2.1.13 here](https://github.com/DeFiCh/app/releases/tag/v2.1.13)

Note that our testers and developers are not facing the issue hence we cannot 100% test if it is resolved ourselves., so would like users that are facing the issue to try it.

**Comment by izzycsy** [comment]
Hi @Anlien75 @cRuuZaR @domo88 @Jacobsieler8888 @DanielZirkel @madeinusmate do give a thumbs up to this comment if your issue has been resolved, otherwise, provide new information (include screenshots) and app logs. Thank you.

**Comment by cRuuZaR** [comment]
I have downloaded and install this version and it works fine... but before
I have done a resync under Settings with the 2.1.12 version ;-)

Am Di., 26. Jan. 2021 um 14:29 Uhr schrieb Bella <notifications@github.com>:

**Comment by DanielZirkel** [comment]
Version 2.1.13 was working in my case, but I need a complete new reindex.
Just installing could not solve the issue

**Comment by Jacobsieler8888** [comment]
How do you reindex DanielZirkel?

**Comment by Jacobsieler8888** [comment]
https://github.com/DanielZirkel, how do you reindex?

**Comment by monstrobishi** [comment]
@Jacobsieler8888 you can go to Settings -> Reindex after saving -> Save

**Comment by Jacobsieler8888** [comment]
Thank you!

**Comment by Anlien75** [comment]
My system is dead. Nothing works anymore. 

Reindex is not possible. Uninstalling and reinstalling from .12 to .13 does nothing. 


![image](https://user-images.githubusercontent.com/76808716/105883111-c2405b80-6006-11eb-8464-537067dcc568.png)

**Comment by Jacobsieler8888** [comment]
I installed version 2.1.13 and it stopped syncing at block 597952 again so I reindexed after saving and it froze as well.  It says "restarting node. this may take a few minutes". but it's been about 30 minutes and it's still trying to restart node.  Please help!
![DEFI APP SCREEN SHOT](https://user-images.githubusercontent.com/78001800/105888058-4ff95800-5fc1-11eb-8f3e-6080e693dbec.png)

**Comment by monstrobishi** [comment]
Yes this can happen you can restart your computer to clear any stuck process and then try reindex again

**Comment by Jacobsieler8888** [comment]
Okay, but now I tried to close the app to restart my computer and it says "Quitting
![TRYING TO CLOSE DEFI CHAIN APP](https://user-images.githubusercontent.com/78001800/105888737-34db1800-5fc2-11eb-8148-22dd7e7201e3.png)
 Defi chain app. do not turn off computer while this window is open".  What should I do????

**Comment by monstrobishi** [comment]
Under normal circumstances you should not but because it seems stuck for a long time go ahead and restart. Don't worry this warning is just to save you the trouble of having to reindex but in this case you want to reindex anyway so you can ignore it and restart.

**Comment by Jacobsieler8888** [comment]
okay.  will do. thank you

**Comment by Jacobsieler8888** [comment]
Now I got this message when trying to open defi app after restarting my computer.

![error when restarting defi app](https://user-images.githubusercontent.com/78001800/105891027-fb57dc00-5fc4-11eb-8306-1f19fc80c813.png)

**Comment by Jacobsieler8888** [comment]
and it still will not reindex.  It says it is restarting node again and it will not restart, just like the last picture

**Comment by cherryactiveo2** [comment]
Got also the same problem @monstrobishi

**Comment by Jacobsieler8888** [comment]
IT'S WORKING NOW!  THANK YOU EVERYONE!

**Comment by Christian-vfx** [comment]
I had exactly the same issues. 
After the same steps as Jacobsieler8888, it worked for me as well.
Now I can sleep again. Thanks for your support!

**Comment by madeinusmate** [comment]
> Hi @Anlien75 @cRuuZaR @domo88 @Jacobsieler8888 @DanielZirkel @madeinusmate do give a thumbs up to this comment if your issue has been resolved, otherwise, provide new information (include screenshots) and app logs. Thank you.

Different error for me "node disconnected" + notification saying: "Pending Balance Failure - network error"  
Tried both updating the existing installation and with a fresh one.

<img width="711" alt="Screenshot 2021-01-27 at 9 02 47 AM" src="https://user-images.githubusercontent.com/25027502/105927359-cad47880-607e-11eb-847d-2c697f059b12.png">

**Comment by madeinusmate** [comment]
problem solved with a restart and fresh install.
the issue "node is disconnected" was due to no more free space on my hard drive to store the blocks.

**Comment by izzycsy** [comment]
Hi @madeinusmate , for hard disk space yes. 

Thanks all for your reply, should the the same error occur, you may reopen this issue with new information (include screenshots) and app logs. Thank you.

**Comment by Christian-vfx** [comment]
After closing and restarting the app I had again damaged blocks. 
Now the app is syncronizing again.
![2021-01-27-1 damaged block](https://user-images.githubusercontent.com/78051131/105962402-0f144880-6080-11eb-9b32-1aa0047178f8.jpg)

**Comment by uzyn** [comment]
Block corruption is an unrelated issue.

That happens locally when your memory is filled up and it doesn't have the buffer to dump to disk before OS kills the process. Try to increase the memory/swap allocation.

**Comment by Christian-vfx** [comment]
I have 32GB RAM. When syncing DeFi app goes up to 10GB. 
After sync, right now only 177MB.
I used the workaround to “stop” via console and then kill the process via Task Manger. Then I can start the app without error message and full sync.
