### ISSUE TITLE
Problem with defi-app 2.1.12

### ISSUE THREAD

**Issue by GitHubRea** [DeFiCh/app#382]
### Preflight Checklist

- [ x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [ x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  - 2.1.12
- **Previous DeFi App Version:**
  - 
- **Operating System (OS):**
  - macOS 11.1

### Screenshot(s) / screen recording(s) of issue

[DEX DFI BTC error.pdf](https://github.com/DeFiCh/app/files/5868967/DEX.DFI.BTC.error.pdf)
[Send_DFI_error.pdf](https://github.com/DeFiCh/app/files/5868973/Send_DFI_error.pdf)

### Actual Behavior

It is not possible to send DFI´s or Adding liquidity to pools.
But I get rewards from liquidity mining. 

### App log / binary log / app config

[Logs.zip](https://github.com/DeFiCh/app/files/5869002/Logs.zip)

**Comment by izzycsy** [comment]
Hi @GitHubRea thanks for your feedback, screenshots and logs, regarding the issue `Add LP / Add-on auth TX failed: Insufficient funds`, I'll link you to <https://github.com/DeFiCh/app/issues/312> which we can further discuss on the problem. We would like to keep same issues in one thread. Thank you.
