### ISSUE TITLE
DFI and BTC Wallets Missing

### ISSUE THREAD

**Issue by OreoDave71** [DeFiCh/app#383]
### Preflight Checklist

- [x ] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x ] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
2.1.4
- **Previous DeFi App Version:**
None
- **Operating System (OS):**
Windows 10

### Screenshot(s) / screen recording(s) of issue

[Cake DFI Withdrawal Jan 25 2021.zip](https://github.com/DeFiCh/app/files/5869858/Cake.DFI.Withdrawal.Jan.25.2021.zip)

### Actual Behavior
DeFi App crashed when I was sending funds from Cake to my DFI wallet in the DeFi app. I'm worried that my funds might be lost. Neither my DFI wallet nor my BTC wallet appear in the DeFi app. 

Please provide steps on how to reproduce the issue:
```
1. Open the app
2. Go to wallet page
3. Click on DFI
4. Send DFI
5. Unable to send DFI
6. Error: Insufficient UTXOs
```
-->

### Expected Behavior
Open app. See my DFI wallet and my BTC wallet. See funds deposited from Cake to DFI wallet in the app.

### App log / binary log / app config

[app_log.log](https://github.com/DeFiCh/app/files/5869866/app_log.log)

**Comment by OreoDave71** [comment]
![Confirmed DFI Balance Jan 25 2021](https://user-images.githubusercontent.com/76673895/105824234-b2336800-5f83-11eb-9d4f-5ae9c50f2cdf.png)
![Screenshot 2021-01-26 020341](https://user-images.githubusercontent.com/76673895/105824243-b52e5880-5f83-11eb-8c2a-f95dd7c0c752.png)

**Comment by OreoDave71** [comment]
![Screenshot 2021-01-26 020341](https://user-images.githubusercontent.com/76673895/105824287-c2e3de00-5f83-11eb-91e4-60ba3017fe47.png)

**Comment by adrian-schnell** [comment]
take a look:

> Clarke Quay upgrade transition is successful and live on mainnet. 
> 
> App users, please ensure that you are running app version 2.1.9 and up. 
> If you run a node, ensure that it is version 1.4.x and up.

(https://t.me/defichain_announcements)

did upgrading solve your issue @OreoDave71 ?

**Comment by OreoDave71** [comment]
Hi Adrian. Yes, upgrading to the newest version of the software did help
quite a bit. We can call the issue resolve. That said, I won't be
using even the newest version of the software on a regular basis until some
improvements are made. The software is "buggy" and takes quite a long time
to sync even when run on a new computer with lots of RAM and a good
graphics card.

OreoDave

**Comment by izzycsy** [comment]
Hi @OreoDave71 , thanks for your feedback, I understand your hesitation, our team is constantly working on improving the app and solving its issues. We regularly do releases, so if you are not in a big hurry I would suggest staying on the latest version and wait for a fix.  Thank you for your understanding.

Hi @adrian-schnell thank you for the help!
