### ISSUE TITLE
DEFI CHAIN APP STOPS SYNCING AT BLOCK #597952.  I AM UNABLE TO USE THE APP.

### ISSUE THREAD

**Issue by Jacobsieler8888** [DeFiCh/app#386]
### Preflight Checklist

- [x ]--> I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x ]--> I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
                                        VERSION 2.1.12
- **Operating System (OS):**
                                        WINDOWS 10

### Screenshot(s) / screen recording(s) of issue
![DEFI APP SNIPP](https://user-images.githubusercontent.com/78001800/105803322-10475780-5f52-11eb-9f18-e68de3957188.PNG)

### Actual Behavior
When I open my desktop DEFI App, it stops syncing at block #597952 every time I open the app.  It has been syncing all day but hasn't got past block #597952.  I first noticed the problem this morning at about 8:00 AM Pacific Standard Time.
Please provide steps on how to reproduce the issue:
```
1. Open the app
2. wait for the app to sync
3. App doesn't finish syncing. 
4. App has been syncing for about 13 hours and hasn't made any progress past block #597952
```
-->

### Expected Behavior
I expected the DEFI App to finish syncing like it has done every day I have had it, except today.

### App log / binary log / app config
[BINARY LOGS.log](https://github.com/DeFiCh/app/files/5871329/BINARY.LOGS.log)

[APP LOGS.log](https://github.com/DeFiCh/app/files/5871332/APP.LOGS.log)

**Comment by izzycsy** [comment]
Hi @Jacobsieler8888 , thanks for your feedback and logs, regarding the issue `v2.1.12 block stuck at 99.91%`, I'll link you to <https://github.com/DeFiCh/app/issues/381> which we can further discuss on the problem. We would like to keep same issues in one thread. Thank you.
