### ISSUE TITLE
Button for scrolling through transactions still missing

### ISSUE THREAD

**Issue by marksiam** [DeFiCh/app#391]
### Preflight Checklist

- [X] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [X] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
App version 2.1.13
- **Previous DeFi App Version:**
App version 2.1.12 etc
- **Operating System (OS):**
  MAcOS Big Sur 11.1

### Screenshot(s) / screen recording(s) of issue
![Screenshot 2021-01-26 at 22 55 58](https://user-images.githubusercontent.com/35368018/105861502-c0d45a80-6029-11eb-8860-124974008762.png)

### Actual Behavior
The buttons to scroll through the transactions are missing (see screenshot attached)
Forward is a page per page hop possible, backward only all at once. 
Once you overshoot the last/first page you can have to start scrolling from the beginning that takes forever it should stop at the first transaction not rotate through.

Please fix that. THX
Lord Mark

### Expected Behavior
Add buttons (2 per side, page by page, and all) and avoid rotating over the first entry. In that style.

![Screenshot 2021-01-26 at 23 20 16](https://user-images.githubusercontent.com/35368018/105864711-2ece5100-602d-11eb-8b6c-d4f1ad75c1f7.png)

**Comment by izzycsy** [comment]
Hi @marksiam , thanks for your feedback, a user previously mentioned this as well. The team is aware and will improve the UI/UX for this. Thank you!
