### ISSUE TITLE
Wallet encryption, unlocking with walletpassphrase does not work

### ISSUE THREAD

**Issue by jung-eto** [DeFiCh/app#392]
Hi all,
Issue Details: after installing V 2.1.13, unlocking the app with "walletpassphrase" in concole is not possible any more
Error Message: JSON value is not an integer as expected
Please see attached screen picture

Current Defi Version: 2.1.13
Previous Defi Version: 2.1.12
Operating System: macOS 10.15.7

Bahaviour: after using the "walletpassphrase" function many times without problems, it will not work after the update to 2.1.13 with the error code JSON value is not an integer as expected

Log files: my log files are miles long and I am not a computer specialist. Please tell me how to find and delete all private information, then I can send them over to you :)

![IMG_0593](https://user-images.githubusercontent.com/78017139/105866571-6b318b00-5ff4-11eb-86cc-45f0884dbf56.JPG)

**Comment by RadioSteve-dev** [comment]
Same issue with Windows wallet. Went back to version 2.1.12 to be able to use my funds and add liquidity.

**Comment by FrankN75** [comment]
Same issue on my Windows system.
Did a downgrade to 2.1.12 as workaround to access the wallet.

**Comment by izzycsy** [comment]
Hi @jung-eto @RadioSteve-dev @FrankN75 , regarding the issue [`walletpassphrase: JSON value is not an integer as expected`](https://github.com/DeFiCh/app/issues/397), we can further discuss on the problem there. Kindly send your screenshot & logs there. We would like to keep same issues in one thread. Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/106252019-b47e1680-6250-11eb-93ec-770a2f5e097f.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/106252025-b647da00-6250-11eb-8a05-ec34c472da9c.png">
