### ISSUE TITLE
V2.1.13 Error: recipient () does not refer to any valid address 

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#393]
I have tried to use the DEX:

<img width="1440" alt="Bildschirmfoto 2021-01-26 um 17 29 41" src="https://user-images.githubusercontent.com/65536965/105875159-bef4a200-5ffd-11eb-969a-b2432a4127f3.png">

<img width="1440" alt="Bildschirmfoto 2021-01-26 um 17 28 34" src="https://user-images.githubusercontent.com/65536965/105875150-bb611b00-5ffd-11eb-855b-90ad8764440f.png">

Mac 
16 GB Ram
M1 Chip

[210126 Logfiles.zip](https://github.com/DeFiCh/app/files/5874692/210126.Logfiles.zip)

**Comment by Kracht** [comment]
Try 

>utxostoaccount {"YOUR_ADDRESS":"1.0@DFI"}

on the console, then go back to DEX and try swapping again.

Possibly same issue as https://github.com/DeFiCh/app/issues/314#issuecomment-767536792

**Comment by RobinTorque** [comment]
> Try
> > utxostoaccount {"YOUR_ADDRESS":"1.0@DFI"}
> on the console, then go back to DEX and try swapping again.

Yes, this solution works

**Comment by yant0r** [comment]
It works for me too

**Comment by PrinzBG13** [comment]
> Try
> 
> > utxostoaccount {"YOUR_ADDRESS":"1.0@DFI"}
> 
> on the console, then go back to DEX and try swapping again.
> 
> Possibly same issue as [#314 (comment)](https://github.com/DeFiCh/app/issues/314#issuecomment-767536792)

This solves the issue for me too! Thank you

**Comment by izzycsy** [comment]
Hi @RobinTorque @Kracht @yant0r @PrinzBG13 , thanks for the feedback, the team is currently investigating this issue. Regarding the issue [`DEX: recipient () does not refer to any valid address`](https://github.com/DeFiCh/app/issues/305), we can further discuss on the problem there. We would like to keep same issues in one thread. Thank you.
