### ISSUE TITLE
Tokens: Missing tx history

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#394]
The DeFi app does not show me a trak action history on the tokens. 

<img width="1440" alt="Bildschirmfoto 2021-01-26 um 17 26 05" src="https://user-images.githubusercontent.com/65536965/105876124-ec8e1b00-5ffe-11eb-9e06-dcdbe93ed046.png">

[210126 Logfiles.zip](https://github.com/DeFiCh/app/files/5874735/210126.Logfiles.zip)

**Comment by izzycsy** [comment]
Hi @RobinTorque , thanks for your feedback, please give us time to investigate this.

**Comment by salomonkarsten** [comment]
I worte a script on excel Windows users. You need to take care to download the CLI version and not the desktop app. If you already installed the desktop app, it is ok but you need to close the app as the synchronisation deamon is not the same as for the CLI. Then you need to open a command shell and run defid.exe which is the synchronisation tool and it will automatically use your existing wallet no matter where defid.exe  is stored. Basically from another command shell you can now run defichain commands e.g. test if following works

defi-cli.exe gettokenbalances {} true true 

You need to be careful with jason commands in ein shell as all double quotes need a backslash forehand.

Once started I call the shell command using VBA in Excel. In the following script you should modify the path to your downloaded app defi-cli.exe and eventually alter the amount of blocks. I parsed blockwise as I had issues with more blocks in the desktop app already. Unfortunately this might need quite some time depending on the amount of blocks.

Sub Makro1()
'
' Makro1 Makro
'
Dim i_block As LongLong
Dim rowNbr As LongLong
i_block = 515339 ' erste Übrweisung
If Range("a2").Value = "" Then rowNbr = 2 Else rowNbr = CInt(Range("C1").End(xlDown).Row + 1)

For i_block = 515339 To 541339 ' Block 515339 erste Übrweisung

HistoryWriteLines i_block, rowNbr
Next i_block

'MsgBox ShellRun("C:\Users\User\Desktop\DEFI-Wallet\CLI\defichain-1.4.5\bin\defi-cli.exe listaccounthistory mine {\""maxBlockHeight\"":616134,\""depth\"":0,\""limit\"":100}")

End Sub


Function HistoryWriteLines(i_block As LongLong, rowNbr As LongLong)
'filetext = ReadTextFile("C:\Users\User\Desktop\DEFI-Wallet\HistoryTEMPDEFI-Wallet.txt")

filetext = ShellRun("C:\Users\User\Desktop\DEFI-Wallet\CLI\defichain-1.4.5\bin\defi-cli.exe listaccounthistory mine {\""maxBlockHeight\"":" & i_block & ",\""depth\"":0,\""limit\"":500}")
'ReadTextFile("C:\Users\User\Desktop\DEFI-Wallet\History2020DEFI-Wallet.txt")

arrlines = Split(filetext, vbLf)

   Cells(1, 1).Value = "owner"
    Cells(1, 2).Value = "blockHeight"
    Cells(1, 3).Value = "blockHash"
    Cells(1, 4).Value = "blockTime"
    Cells(1, 5).Value = "type"
    Cells(1, 6).Value = "poolID"
    Cells(1, 7).Value = "txn"
    Cells(1, 8).Value = "txid"
    Cells(1, 9).Value = "amounts"




For i = 0 To UBound(arrlines) - LBound(arrlines) - 1
temp = Split(arrlines(i), """")
If UBound(temp) - LBound(temp) > 0 Then ' Not IsEmpty(temp) Then
'MsgBox (temp(1))
Select Case temp(1)
Case "owner"
    Cells(rowNbr, 1).Value = temp(3)
Case "blockHeight"
    Cells(rowNbr, 2).Value = Split(Split(temp(2), ",")(0), ":")(1)
Case "blockHash"
    Cells(rowNbr, 3).Value = temp(3)
Case "blockTime"
    Cells(rowNbr, 4).Value = CDate(DateAdd("s", CDbl(Split(Split(temp(2), ",")(0), ":")(1)), "Jan 1 1970 1:00:00"))
Case "type"
    Cells(rowNbr, 5).Value = temp(3)
Case "poolID"
    Cells(rowNbr, 6).Value = temp(3)
Case "txn"
    Cells(rowNbr, 7).Value = Split(Split(temp(2), ",")(0), ":")(1)
Case "txid"
    Cells(rowNbr, 8).Value = temp(3)
Case "amounts"
    colAmount = 9
    While UBound(temp) - LBound(temp) > 0
    i = i + 1
    temp = Split(arrlines(i), """")
    If UBound(temp) - LBound(temp) > 0 Then
        Cells(rowNbr, colAmount).Value = Split(temp(1), "@")(0)
        Cells(rowNbr, colAmount + 1).Value = Split(temp(1), "@")(1)
        colAmount = colAmount + 2
    Else: rowNbr = rowNbr + 1
    End If
    Wend
Case Else: MsgBox ("uncovered case at" & i & ":" & temp(1))
End Select
End If

Next i

End Function






Public Function ShellRun(sCmd As String) As String

    'Run a shell command, returning the output as a string

    Dim oShell As Object
    Set oShell = CreateObject("WScript.Shell")

    'run command
    Dim oExec As Object
    Dim oOutput As Object
    Set oExec = oShell.Exec(sCmd)
    Set oOutput = oExec.StdOut

    'handle the results as they are written to and read from the StdOut object
    Dim s As String
    Dim sLine As String
    While Not oOutput.AtEndOfStream
        sLine = oOutput.ReadLine
        If sLine <> "" Then s = s & sLine & vbCrLf
    Wend

    ShellRun = s

End Function

**Comment by izzycsy** [comment]
Hi @RobinTorque , update [v2.3.0](https://github.com/DeFiCh/app/releases/tag/v2.3.0) is out, this is a mandatory update due to node Dakota Upgrade 1.5.0.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
