### ISSUE TITLE
V2.1.13 QR Code Scanner does not work

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#395]
I tried using the QR code scanner to avoid having to transcribe the address.  No error message was displayed.

<img width="1440" alt="Bildschirmfoto 2021-01-26 um 17 54 19" src="https://user-images.githubusercontent.com/65536965/105877662-83a7a280-6000-11eb-9838-b5c48c7b8561.png">

Apple MacBook Air – Late 2020
M1 Chip

[210126 Logfiles.zip](https://github.com/DeFiCh/app/files/5874811/210126.Logfiles.zip)

**Comment by izzycsy** [comment]
Hi @RobinTorque , thanks for your feedback. Please give us time to fix this. Thank you.

**Comment by izzycsy** [comment]
Hi @RobinTorque , just an update, this issue is not yet fixed. Thank you for your patience.
