### ISSUE TITLE
walletpassphrase: JSON value is not an integer as expected

### ISSUE THREAD

**Issue by salomonkarsten** [DeFiCh/app#397]
the command
walletpassphrase "my pass" 120

does not longer work and end up with:

"JSON value is not an integer as expected"

I will recover my seed using the mnemoric key. But wanted to state this problem before. Attached the log file
[Applog.txt.log](https://github.com/DeFiCh/app/files/5875642/Applog.txt.log)

**Comment by dell1503** [comment]
Exactly the same Problem here. I notice after command entring and switch back with the Arrow Keys to move the cursor back, that it Jumps. Like there is a special character between the lines. This normal indicates a Copy Past issue, bit the issue allso appear when type the command in. I try to create a GIF to illustrate that more.
https://imgflip.com/gif/4veteg
Also add the Pictures.
<img width="107" alt="Bildschirmfoto 2021-01-26 um 20 47 32" src="https://user-images.githubusercontent.com/20696826/105897066-f5d7b180-6017-11eb-92b6-4218a8733d99.png">
<img width="108" alt="Bildschirmfoto 2021-01-26 um 20 47 05" src="https://user-images.githubusercontent.com/20696826/105897070-f6704800-6017-11eb-96ac-7b95c6da691f.png">

I'm 100% shure that there is a space between the pass and the digit.

**Comment by salomonkarsten** [comment]
Did you succeed to open the wallet? 

Anyways too late about to recover it in full...":(

**Comment by kyoungrok0517** [comment]
Same here. More bugs are coming after updates :(

**Comment by Surfer88** [comment]
Had the same problem, deleted the app version 2.1.13 on my Mac. Downloaded app release 2.1.12 (from official GitHub) again and now I can send the rewards back to cake.

**Comment by dell1503** [comment]
> Had the same problem, deleted the app version 2.1.13 on my Mac. Downloaded app release 2.1.12 (from official GitHub) again and now I can send the rewards back to cake.

Thanks, worked for me as well.

**Comment by tame81** [comment]
Same here, running the wallet on MacOS Catalina. The wallet suggests to back up before the update, however no such backup is created that could be restored.

**Comment by izzycsy** [comment]
Hi @salomonkarsten , thanks for your feedback, please give us time to investigate this issue. Thank you. 

Hi @kyoungrok0517 @tame81 @Surfer88 could you send your logs please? Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/106133581-6f9aa700-61a0-11eb-9f2b-3c9307142e48.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/106133589-71fd0100-61a0-11eb-8cf7-fdd7df4b72d1.png">


Hi @dell1503 , thanks for your feedback on the `jump`, the team is aware of this, it's irrelevant to the original issue. Rest assured that your feedback has been sent to the team. Thank you for your valued feedback.

**Comment by salomonkarsten** [comment]
@tame81 @izzycsy 

Yes another issue. If any passwortgeschützt is set the walletbackup file is empty. But I guess is another issue.

Cheers

**Comment by izzycsy** [comment]
Hi @salomonkarsten @kyoungrok0517 @dell1503 @Surfer88 @tame81 , update [v2.1.15](https://defichain.com/downloads/) is out.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
