### ISSUE TITLE
No sending / no swapping of USDT to DFI possible

### ISSUE THREAD

**Issue by flotzke** [DeFiCh/app#398]
Version 2.1.13
![1](https://user-images.githubusercontent.com/9954463/105897081-fb34fc00-6017-11eb-925a-0bf0ae46590e.png)
![2](https://user-images.githubusercontent.com/9954463/105897083-fbcd9280-6017-11eb-8431-8012ab2f8ec3.png)
![3](https://user-images.githubusercontent.com/9954463/105897084-fc662900-6017-11eb-834f-4be7f3dc008c.png)
![4](https://user-images.githubusercontent.com/9954463/105897085-fc662900-6017-11eb-8b92-8760ae5b4d5a.png)

[logs.zip](https://github.com/DeFiCh/app/files/5875823/logs.zip)

**Comment by flotzke** [comment]
[logs.zip](https://github.com/DeFiCh/app/files/5875817/logs.zip)

**Comment by flotzke** [comment]
After reindexing i got a different usdt balance and the problem did no more occur, nevertheless it ocurred in this situation.

**Comment by izzycsy** [comment]
Hi @flotzke , another user reported a similar issue, it should be fixed in the upcoming release. Thank you for your feedback.
