### ISSUE TITLE
Node is disconnected

### ISSUE THREAD

**Issue by wyssen** [DeFiCh/app#399]
Dear team / community.
I had no issues so far and was still using version 2.1.6. Since yesterday, I had problems, so I updated today to the latest 2.1.13.
However, at 99.51% of sync, the following message appears: "Node is disconnected".

I already rebooted (after waiting until the program exited correctly and the process was shut down). Still the same problem. Do you have any ideas?

I run on Win10, latest 2.1.13

![image](https://user-images.githubusercontent.com/9450822/105900992-0d656900-601d-11eb-8e33-9c930e730e02.png)

**Comment by thbestforyourbizdeployment** [comment]
me too 
![Uploading image.png…]()

**Comment by wyssen** [comment]
I just did a downgrade and tried with the version 2.1.12. Same error with 99.43%...

**Comment by izzycsy** [comment]
Hi @wyssen @thbestforyourbizdeployment , thanks for the feedback. Regarding the issue [`Windows: sync stops at 99%+ > node is disconnected`](https://github.com/DeFiCh/app/issues/325), we can further discuss on the problem there. We would like to keep same issues in one thread. Thank you.
