### ISSUE TITLE
DEX problem

### ISSUE THREAD

**Issue by eagleel** [DeFiCh/app#401]
### Preflight Checklist

- [ x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [ x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:2.1.13
  - 
- **Previous DeFi App Version:**
  - 
- **Operating System (OS):Mojave
  - 

### Expected Behavior
 I expect the dpi to change to BTC

**Comment by eagleel** [comment]
It left out some details.......

When I try to change dfi to btc in DEX. it asks me to choose a Receive token at address. I choose one hit swap and it tells me recipient () does not refer to any valid address.

I can only choose from the address' I created in the drop down bar?

can anyone shed light on this? 

thanks

**Comment by Kracht** [comment]
Open console and try:

>utxostoaccount {"ADDRESS":"AMOUNT@DFI"}

e.g.

>utxostoaccount {"yFgrUd8RdL39Yrsqnv9B3yFXnaThGqQ2bm":"1.0@DFI"}

Then go back to DEX and try again.

Same issue as https://github.com/DeFiCh/app/issues/314#issuecomment-767743662

**Comment by izzycsy** [comment]
Hi @eagleel @Kracht thanks for the feedback, the team is currently investigating this issue. Regarding the issue [`DEX: recipient () does not refer to any valid address`](https://github.com/DeFiCh/app/issues/305), we can further discuss on the problem there. We would like to keep same issues in one thread. Do send your logs & screenshot as well. Thank you.
