### ISSUE TITLE
unable to send usdt

### ISSUE THREAD

**Issue by wattafot** [DeFiCh/app#408]
Dear DeFiChain team,
im trying to send USDT to an external wallet.
but the "next" button is greyed out in the SENDING TAB

![dfi_send](https://user-images.githubusercontent.com/4711679/106019167-a1d5d700-60c2-11eb-8728-6c771b7efe74.png)

what am i doing wrong?

**Comment by RobinTorque** [comment]
You cannot send ETH to an Ethereum address. Only to a DFI address. Starting with a "d" or an "8".

You can exchange these ETH tokens for real ETH coins at CAKE DEFI.
