### ISSUE TITLE
DFI swapped to BTC - BTC didn't arrive

### ISSUE THREAD

**Issue by jussy67** [DeFiCh/app#409]
### Preflight Checklist

- [x ] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

App Version 2.1.13

Hi
I swapped 2024 DFI to BTC. The DFI were gone but the BTC didn't arrive!
On the tix was remarked under "Custom transaction" at to: "false"...

Here is the tix: https://mainnet.defichain.io/#/DFI/mainnet/tx/fe7f88fa179d5d42845a72ac8058a389f6f32c8f416ae27e807757ced15dfa0e

Cincerly Marius

**Comment by izzycsy** [comment]
Hi @jussy67 , kindly check your tokens via CLI: 

`listaccounts {} true true true` — breakdown of your coin(s) / token(s) 

<img width="1011" alt="CLI" src="https://user-images.githubusercontent.com/65014479/106381866-b681da00-63f6-11eb-85a3-ca1e0a5ca2d0.png">

**Comment by jussy67** [comment]
Thanks for your reply. When I just type "listaccounts {} true true true", I get this feedback: []

If I copy the whole expression (listaccounts {} true true true - breakdown of your coin(s) / token(s)) comes a long text. Is this a tutorial then?

**Comment by jussy67** [comment]
<img width="1036" alt="Bildschirmfoto 2021-02-02 um 08 06 38" src="https://user-images.githubusercontent.com/78120052/106564654-ce0fae80-652d-11eb-9283-5b4462c7116b.png">


What does it mean? It the lower BTC amount is exactly the equivalent of the amount that did not come back. Can you help me with this?

**Comment by izzycsy** [comment]
Hi @jussy67 , this means that `0.15736621 BTC` is still in your account, it seems like you've no `receive address`. Can you check? 

<img width="1002" alt="DFI wallet   Receive   New Address" src="https://user-images.githubusercontent.com/65014479/106604111-27152c00-659a-11eb-8703-48c0497ac03a.png">

**Comment by jussy67** [comment]
Yes I do, I even have two addresses. Can I somehow assign them via the console so that these two amounts appear again in my wallet?

**Comment by izzycsy** [comment]
Hi @jussy67 , can you create a new address, take a screenshot of the list of addresses. 

Then type in CLI: `listaccounts {} true true true`, and send the output.

**Comment by izzycsy** [comment]
Hi @jussy67 , has your issue been resolved? It could be that you're on an older version of the app. The team won't be able to address bugs on the older version. Update [v2.3.0](https://github.com/DeFiCh/app/releases/tag/v2.3.0) is out, this is a mandatory update due to node Dakota Upgrade 1.5.0.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
