### ISSUE TITLE
Window 10 DFI ver 2.1.13 Add LP : Add-on auth TX failed: Can't sign TX - Input not found or already spent

### ISSUE THREAD

**Issue by kenang68** [DeFiCh/app#412]
Hi,

I try to add liquidity pool but I receive error
 "Add-on auth TX failed: Can't sign TX: [{"txid":"3d0d1afe3f7df02753e8b0c9a472a22197d74ad922567c016b7e70c890a0b7d8","vout":0,"witness":[],"scriptSig":"","sequence":4294967294,"error":"Input not found or already spent"}] "

Can you help to take a look?

I am running Window 10 with App Ver 2.1.13.

Log attached.

Thanks.
![210128 Add Liquidity erroe](https://user-images.githubusercontent.com/72757945/106099453-a909ed00-6175-11eb-8dac-c7d47d2ae77d.jpg)
[Binary Logs.zip](https://github.com/DeFiCh/app/files/5885279/Binary.Logs.zip)

**Comment by izzycsy** [comment]
Hi @kenang68 , the issue could be you've too little DFI UTXOs balance (min. 1DFI) — which is required to perform swap and other functions. Basically DFI exist in 2 forms; **utxoDFI** and **accountDFI**. utxoDFI is used to pay for transactions fees while Rewards received are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. To convert accountDFI to utxoDFI, the simplest way is to send DFI from your `receive address A` to your `receive address A`, the app will automatically convert for you. 

Try sending 1 DFI, you can do it from an exchange or get a friend to send you some, and try the function again. 

If the error persist, send you logs again to [`Add LP / Add-on auth TX failed: Insufficient funds`](https://github.com/DeFiCh/app/issues/312). We can further discuss on the problem there. We would like to keep same issues in one thread. Thank you.
