### ISSUE TITLE
Unable to Synchronize Blocks 

### ISSUE THREAD

**Issue by ashtonpaulsingh** [DeFiCh/app#413]
Hi Guys,

I updated a new version yesterday and all was fine. Today I tried to open my app and while it was synchronizing I accidentally closed the window while trying to minimize it before its completion. I reopened the app and now it seems that the blocks wont sync. Could use some help with this. Thank you :)

![Synchronizing 11 57%](https://user-images.githubusercontent.com/78137732/106106964-4585bc80-6181-11eb-83ad-aaaa325bc8af.PNG)

[App config.zip.zip](https://github.com/DeFiCh/app/files/5885626/App.config.zip.zip)

**Comment by izzycsy** [comment]
Hi @ashtonpaulsingh , try using the `Reindex option` via Settings.

<img width="776" alt="Reindex option" src="https://user-images.githubusercontent.com/65014479/106122848-247a9700-6194-11eb-9a38-1971a450b460.png">

**Comment by ashtonpaulsingh** [comment]
HI Bella,

Thanks for this. Everything seems to be running fine now. Thank you for the
fast response,

Best,
