### ISSUE TITLE
Trying to help with debugging...

### ISSUE THREAD

**Issue by Kracht** [DeFiCh/app#414]
So yesterday I build the app from source and run it via npm in Devmode.

Everything is running fine until 99.91% sync, then Memory usage spikes and hardfaults rise, at one point performance monitor showed over 33GB commited memory. My system freezes completely (16GB DDR4, Ryzen 9 3900X) for a while and console becomes red.

![Screenshot 2021-01-27 205237](https://user-images.githubusercontent.com/59254851/106125582-a058ed00-615c-11eb-9f8e-72b3c1346406.png)
![Screenshot 2021-01-27 205500](https://user-images.githubusercontent.com/59254851/106125587-a0f18380-615c-11eb-9a8c-086265502c34.png)
![Screenshot 2021-01-27 205602](https://user-images.githubusercontent.com/59254851/106125591-a18a1a00-615c-11eb-8785-bac825954e4f.png)
 
I created a Lighthouse Report in which vendor.js and the unreliable "unload" event listener raises attention, since I see vendor.js in all the app logs uploaded here.

[DeFI_Lighthouse.zip](https://github.com/DeFiCh/app/files/5886498/DeFI_Lighthouse.zip)

I hope it contributes to debugging in someway.

**Comment by izzycsy** [comment]
Hi @Kracht , thanks for your insightful feedback & logs, could you send this to [`Windows: sync stops at 99%+ > node is disconnected `](https://github.com/DeFiCh/app/issues/325), we would like to keep same issues in one thread. Thank you.
