### ISSUE TITLE
Add-on auth TX failed: Insufficient funds

### ISSUE THREAD

**Issue by SKiener** [DeFiCh/app#417]
I transferred BTC from CakeDefi to my DeFi app and I can see them there. When I want to swap it gives me an error Add-on auth TX failed: Insufficient funds 

[Logs.zip](https://github.com/DeFiCh/app/files/5889339/Logs.zip)

**Comment by izzycsy** [comment]
Hi @SKiener , thanks for your feedback. It could be that you've too little utxoDFI balance (min. 1DFI) — which is required to perform swap and other functions. Try sending yourself 1 DFI and try the function again. If it still persist, please send screenshot of the error and re-send your logs. Thank you.

**Comment by SKiener** [comment]
That is true I have no DFI at the moment, only BTC. So I have to transfer at least one DFI that I can change?
