### ISSUE TITLE
Node disconnected

### ISSUE THREAD

**Issue by jibesmaster** [DeFiCh/app#418]
Hello 
I update to version number 13 and it is loading the blockchain. Then at around 99% it stops and says node disconnected. 
I had version 12 running without any problems. Now when I downgrade again it tells me the same error. 
I have attached the log files. If there is anything else you need please let me know. 

Thank you 
Jim 
[App logs error.log](https://github.com/DeFiCh/app/files/5889430/App.logs.error.log)

**Comment by Speedy2003trs** [comment]
Hello
I have exactly the same issue. Downgrading back to version 12 did also not help. Hope to get support.

**Comment by thbestforyourbizdeployment** [comment]
same on version x.x.13

**Comment by izzycsy** [comment]
Hi @jibesmaster @Speedy2003trs @thbestforyourbizdeployment , regarding the issue [`Windows: sync stops at 99%+ > node is disconnected
`](https://github.com/DeFiCh/app/issues/325), we can further discuss on the problem there. We would like to keep same issues in one thread. Kindly send screenshots of your Activity Monitor / the error, as it provides better insight and to ensure that you're directed to the right thread. Thank you.
