### ISSUE TITLE
Warning: Address not saved by seed phrase

### ISSUE THREAD

**Issue by jung-eto** [DeFiCh/app#419]
App Version 2.1.13
macOS 10.15.7

Hi,
yesterday I created a complete new seed and transferred all my funds to the new address because the old wallet addresses all said "Warning: Address not saved by seed phrase".
Yesterday, my new created wallet address was save.
**Today the "Warning: Address not saved by seed phrase" shows up again also in the new wallet.**
I know issue #267 and commented in it but no one answered.
As you know from issue #392 and #397 , it is impossible to unlock the wallet.
**Therefore it is impossible to create any backup!**
This combination is very risky and I really sincerely ask you to fix these errors, because at the moment no safe recovery is possible.

Thanks in advance!

**Comment by izzycsy** [comment]
Hi @jung-eto , thanks for your feedback. I've reopened the issue [Warning: Address not saved by seed phrase](https://github.com/DeFiCh/app/issues/267) I'll follow up with you there and in <https://github.com/DeFiCh/app/issues/392>. Please give us time to investgate the issue.
