### ISSUE TITLE
Mac | Unable to start blockchain

### ISSUE THREAD

**Issue by thbestforyourbizdeployment** [DeFiCh/app#420]
v2.1.13 Unable to start blockchain  | Mac 
[v2.1.13 Unable to start blockchain  | Mac .conf.zip](https://github.com/DeFiCh/app/files/5890035/v2.1.13.Unable.to.start.blockchain.Mac.conf.zip)

**Comment by izzycsy** [comment]
Hi @thbestforyourbizdeployment , thanks for your feedback & logs, have you tried `Reindex Option` via Settings? Do you have a screenshot of the error?

**Comment by izzycsy** [comment]
Hi @thbestforyourbizdeployment , could you further describe your issue, the issue I redirected the users in <https://github.com/DeFiCh/app/issues/418> are mostly windows-users. You might be facing another bug, hence I would like to confirm that.

**Comment by thbestforyourbizdeployment** [comment]
my issue was solved with the help of a Reddit https://www.reddit.com/r/defiblockchain/comments/l765tb/fix_for_ram_bug_and_corrupt_blockchain/
