### ISSUE TITLE
txn-mempool-conflict (Code 18)

### ISSUE THREAD

**Issue by TTSIP** [DeFiCh/app#426]
Previous Version : 2.1.13
Current Version: 2.1.14

1. Open the app
2. Go to Liquidity
3. Click on BTC/DFI pool
4. Click on + (add liqudity)
5. Use Max Button for BTC
6. Error: txn-mempool-conflict (Code 18)

Expexcted Behaviour

Add Liqduitdy to pool

![image](https://user-images.githubusercontent.com/76814941/106289976-33bc1c00-624a-11eb-8e5b-4c0299ef62a1.png)

[Config.zip](https://github.com/DeFiCh/app/files/5894484/Config.zip)

**Comment by Darkman-Q-Tester** [comment]
For me the same. Was working fine two hours before.

[2021-01-29 11:48:47.918] [IPC-RENDERER-error] [getBlockSyncInfo] Error: Network Error
[2021-01-29 15:11:59.341] [IPC-RENDERER-error]  Request failed with status code 500
[2021-01-29 16:38:50.368] [IPC-RENDERER-error] [getBlockSyncInfo] Error: Network Error
[2021-01-29 16:48:16.769] [IPC-RENDERER-error]  Request failed with status code 500
[2021-01-29 16:48:44.461] [IPC-RENDERER-error]  Request failed with status code 500

![grafik](https://user-images.githubusercontent.com/77509687/106297286-d4163e80-6252-11eb-9a2a-92e640c0fcf9.png)

**Comment by TTSIP** [comment]
@Darkman-Q-Tester if u dont use max button it works... but i let the ticket open because it should also work with max button

**Comment by Darkman-Q-Tester** [comment]
@TTSIP Thank you, yes if I enter an specific amount then it works. Strange because till now I always used MAX and it was working without issues.

**Comment by theduchess16** [comment]
Same issue here... I've tried the manual method (not using the max button) and it doesn't work either.

**Comment by Darkman-Q-Tester** [comment]
For me it works like this. I click on MAX (for DFI) I then copy the BTC value. I go back to Wallets view then again back to Lqiditiy Mining for BTC-DFI, click add and enter the copied BTC amount from before. Then it works for me.

**Comment by theduchess16** [comment]
@Darkman-Q-Tester Strange, now it worked for me, too... thanks!

**Comment by izzycsy** [comment]
Hi @TTSIP @Darkman-Q-Tester , it could be that you've too little utxoDFI balance (min. 1DFI) — which is required to perform swap and other functions. Try sending yourself 1 DFI and try the function again. Also, update [v2.1.15](https://defichain.com/downloads/) is out. Kindly update to the latest version, if your error persists, kindly send your logs again. Thank you.

**Comment by Darkman-Q-Tester** [comment]
Yes, sending 1 DFI to same address fixed the issue for me. Now it works again with "MAX" DFI button.
Please add this to a "Help" section or Wiki. Normal user would not know this and will not check open bugs here.
Thank you

**Comment by booky84** [comment]
I also have this problem from time to time. I have also changing DFI-Token to DFI-Coin from time to time, but this only helps for a short time.

**Comment by Darkwinde** [comment]
Had this issue yesterday as well. Full synced, walletpassphrase was entered, issue popping up until I restarted the app. After restart all worked fine again. May this info helps.

**Comment by izzycsy** [comment]
Hi @booky84 , the error [`txn-mempool-conflict (code 18)`](https://github.com/DeFiCh/app/issues/378) stems from the lack of accountDFI. 

Basically DFI exist in 2 forms; utxoDFI and accountDFI. utxoDFI is used to pay for transactions fees while Rewards received are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio, and in order to convert accountDFI to utxoDFI. The simplest way is to **send DFI** from your receive address A to your receive address A, the app will automatically convert for you.

To check your balances via CLI: 
`getbalance` — utxoDFI
`gettokenbalances` — accountDFI

  The sum of utxo DFI & DFI would be your total tokens.

**Comment by izzycsy** [comment]
Hi @Darkwinde , good to know, some users manage to solve it by refreshing UTXO via Settings.

**Comment by izzycsy** [comment]
Hi @booky84 , sending DFi to yourself should solve the issue. Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
