### ISSUE TITLE
can't start blockchain errror 

### ISSUE THREAD

**Issue by kevarms2** [DeFiCh/app#429]
massive memory usage ... 2.1.4 ..... can't even get to the point where the syncing starts and my memory is stuck at 99% again with 12gb  ram......   can you please get this bloody thing to work for once ....ive have been locked out now for a month.

**Comment by kevarms2** [comment]
[IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"

**Comment by izzycsy** [comment]
Hi @kevarms2 , can you try to update to [v2.1.15](https://defichain.com/downloads/)? If issue still persists, kindly send your logs & screenshot to [`Node disconnected`](https://github.com/DeFiCh/app/issues/428), we can further discuss on the problem there. We would like to keep same issues in one thread. Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/106366338-2ac86900-6376-11eb-970b-3edd4bd3673c.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/106366339-2d2ac300-6376-11eb-9588-58179492da4f.png">
