### ISSUE TITLE
[Proposal / Feature Request] Allow user to choose data directory

### ISSUE THREAD

**Issue by Darkwinde** [DeFiCh/app#436]
### Preflight Checklist
- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### User Details
- **Current DeFi App Version:**
  - 2.1.15
- **Operating System (OS):**
  - Windows 10.0.19042

### Proposal
As today, the blockchain data directory already consumes 10GB and not all useres have 1TB SSD for Windows default partition installed. Would be great to get the possibility to define the data directory of the DeFi app. 
Currently it is hardcoded to:
`
%appdata%\Roaming\DeFi Blockchain
`

Other crypto coins have the possibility to give on wallet / app start a parameter with:
`
-datadir=F:\Cryptopia\Bitcoin\Data
`

This would allow the user to:
1. Have the blockchain in a separate directory and not in the user ones. Having multiple wallets would lead to an massive decrease of available space in Windows partition.
2. App is splitted from data and lead to flexibility and maintainability in case of backup and resync of wallet and application

**Comment by izzycsy** [comment]
Hi @Darkwinde , you can post your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner some support from the community, and the team can decide whether to implement the feature in the future. Thank you!
