### ISSUE TITLE
Development // "npm run start:electron" don't start the Electron app

### ISSUE THREAD

**Issue by sergejmueller** [DeFiCh/app#438]
### Preflight Checklist
- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details
- **Current DeFi App Version:**
  - 2.1.15
- **Previous DeFi App Version:**
  - 2.1.11
- **Operating System (OS):**
  - MacOS

### Actual Behavior
Please provide steps on how to reproduce the issue:
1. Fresh forked repo
2. Open the terminal
3. `npm run init`
4. `npm run pre:build:mac`
5. `npm run start:electron`
6. Error: `(node:5750) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit`

`npm run start:dev` starts React and Electron app correctly.

### Expected Behavior
Electron app starts after running `npm run start:electron`

**Comment by thedoublejay** [comment]
Hi @sergejmueller, the command `npm run start:electron` is used to run the electron app only. You can use it to test a production or dev build of React then running the electron app locally. It needs to have the react app to work. If you need to run both at the same time, you can use `npm run start:dev`.

**Comment by sergejmueller** [comment]
@thedoublejay The information in the readme file https://github.com/DeFiCh/app#running-apps-electron-and-webapp suggests to me that I can start the single Electron app. It doesn't say the React app has to be running.

Maybe we should add a one-liner to the readme and point out that the React app must be running for the successful start of the Electron app.

**Comment by thedoublejay** [comment]
> @thedoublejay The information in the readme file https://github.com/DeFiCh/app#running-apps-electron-and-webapp suggests to me that I can start the single Electron app. It doesn't say the React app has to be running.
> 
> Maybe we should add a one-liner to the readme and point out that the React app must be running for the successful start of the Electron app.

@sergejmueller  Oh understood. Thanks for your point. I'll try to update the readme files in a while. Actually React app doesn't need to be running, but it should be compiled. Anyway, great suggestion. Will create a PR for this.
