### ISSUE TITLE
UI: Wallet import not possible without existing wallet

### ISSUE THREAD

**Issue by eMDi101** [DeFiCh/app#439]
Hi Team,

I noticed that you can't import a wallet when you start the app for the first time. Import Button is greyed out.
I suspect it is because of this code line, here instead of 
`"enabled: !!isWalletLoaded," -> "enabled: true," `
should be written here.

https://github.com/DeFiCh/app/blob/9c70c16e94f044827d19088974cc179698b57eab/electron-app/src/menus/index.ts#L22

Many greetings 
eMDi101

**Comment by izzycsy** [comment]
Hi @eMDi101 , thanks for your feedback, please give us time to investigate the issue. Thank you.

**Comment by thedoublejay** [comment]
Hi @eMDi101, we have updated the backup/restore process in 2.1.17. You can now backup with wallet.dat and restore it as well. Please have a look. Thanks!
