### ISSUE TITLE
Development // GitHub Workflow for Mac Build is broken

### ISSUE THREAD

**Issue by sergejmueller** [DeFiCh/app#442]
### Preflight Checklist

- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  - 2.1.15
- **Previous DeFi App Version:**
  - 2.1.11
- **Operating System (OS):**
  - MacOS

### Actual Behavior
Mac Version Build aborts with an error:
https://github.com/DeFiCh/app/runs/1797625074

### Expected Behavior
No errors on build process.

**Comment by thedoublejay** [comment]
I think it's failing because you don't have access to our Github secrets. I'll try to run your changes on my branch to see if it works. Thanks for reporting @sergejmueller

**Comment by sergejmueller** [comment]
@thedoublejay My changes? Please take a look on the PR behind the failed workflow: https://github.com/DeFiCh/app/runs/1797625074

P.S. Please let the issue creator to close his issue requests. Once an issue is cleared, the author will close the ticket.

**Comment by thedoublejay** [comment]
@sergejmueller The PR you specified was cancelled by the Author. Your PRs on the other hand were breaking in Mac build due to not having access to the Git secrets. 

P.S @sergejmueller sure, will let you do it next time
