### ISSUE TITLE
Withdrawal error

### ISSUE THREAD

**Issue by JoergHoffmann** [DeFiCh/app#451]
I thought that the error Insufficient amount was cleared meanwhile. I transferdd 3,8 DFI form Cake to the App. Then  I tried to withdrawal the new amount from the App to Cake. Doesnt work. Is it still the Token problem? When you will fix that?
![error-withdrawal](https://user-images.githubusercontent.com/18046932/106465714-a28fb400-649a-11eb-8910-2dedbddf10d1.JPG)

**Comment by thedoublejay** [comment]
Hi @JoergHoffmann, can you try it on the latest version? We have addressed this issue of selecting token from address on the latest version. https://github.com/DeFiCh/app/releases/tag/v2.1.15

**Comment by JoergHoffmann** [comment]
Doesnt work, with any  earlierer versions. I had have adress that issue more than 4 weeks ago. So, how can I transfer my DFI to Cake?

**Comment by thedoublejay** [comment]
You can download the latest version manually and install them @JoergHoffmann.

**Comment by JoergHoffmann** [comment]
Problem solved! Version 2.1.15 works
