### ISSUE TITLE
2.1.15 Version for Windows. Can't login to Wallet - Error *Node Disconnected*

### ISSUE THREAD

**Issue by monnyfx** [DeFiCh/app#455]
### Preflight Checklist

- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  - 
- **Previous DeFi App Version:**
  - 
- **Operating System (OS):**
  - 

### App log / binary log / app config

**2.1.15 Version for Windows after update Can't login to Wallet - Error *Node Disconnected*** after load.
Also Adding Liquidity still doesn't work or convert on Dex.
I have so much errors haven't been able to do anything with this.
[Error Nod Disconnected.zip](https://github.com/DeFiCh/app/files/5908036/Error.Nod.Disconnected.zip)

**Comment by izzycsy** [comment]
Hi @monnyfx , thanks for your feedback. The team is currently investigating this issue, logs are well receive. Regarding the issue [`Windows: sync stops at 99%+ > node is disconnected`](https://github.com/DeFiCh/app/issues/325), we can further discuss on the problem there. We would like to keep same issues in one thread. Thank you.
