### ISSUE TITLE
Gets to 97% then gives me error and disconnects node

### ISSUE THREAD

**Issue by rarce037** [DeFiCh/app#456]
### Preflight Checklist

- [x ] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x ] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  -  v2.1.15
- **Previous DeFi App Version:**
  - 
- **Operating System (OS):**
  - Windows 10

### App log / binary log / app config

[applogs2121.log](https://github.com/DeFiCh/app/files/5908218/applogs2121.log)

**Comment by izzycsy** [comment]
Hi @rarce037 ,  thanks for your feedback. The team is currently investigating this issue, logs are well receive. Regarding the issue [`Windows: sync stops at 99%+ > node is disconnected`](https://github.com/DeFiCh/app/issues/325), we can further discuss on the problem there. We would like to keep same issues in one thread. Thank you.
