### ISSUE TITLE
Add LP: ApplyAddPoolLiquidityTX: amount X is less then XXX (code 16)

### ISSUE THREAD

**Issue by salomonkarsten** [DeFiCh/app#458]
I just moved token to coins as I had a mempool conflict before and wanted to add liquidity:
![image](https://user-images.githubusercontent.com/77124114/106564738-f4354e80-652d-11eb-9884-c08735f98c9e.png)
[Applog.txt.log](https://github.com/DeFiCh/app/files/5909294/Applog.txt.log)

**Comment by gsi2help** [comment]
@salomonkarsten 
It looks like you have done some actions before ... that the balance of DFI is now 0 instead of the needed 75.21.... DFI. 
Go back to DFI-Wallet, Press the actualize-button and have a look.
When you then go back to the Add Liquidity, the amounts should be correct

**Comment by izzycsy** [comment]
Hi @salomonkarsten , thanks for your feedback, are you on v2.1.15? Could you send your _binary_ & _app config_ if possible? App log well received. Please give us time to investigate this issue. 

Hi @gsi2help , thank you for your help! 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/106601690-e9fb6a80-6596-11eb-99bf-366598a65e5f.png">

**Comment by salomonkarsten** [comment]
[AppBinaryLogs.log](https://github.com/DeFiCh/app/files/5916866/AppBinaryLogs.log)

I have another problem now. The LTC coins no longer show up...

**Comment by izzycsy** [comment]
Hi @salomonkarsten , thanks for your logs, well received. Please give us time to investigate. Regarding the issue [`ApplyRemovePoolLiquidityTx: amount X is less than XXX (code 16)`](https://github.com/DeFiCh/app/issues/468), we can further discuss on the problem there. We would like to keep same issues in one thread. Thank you.

**Comment by salomonkarsten** [comment]
@gsi2help no crosschecked with "gettokenbalnaces {} true true" and with "balances" even after waiting for some blocks.  I did a UTXO rescan which got stuck. But i closed it after 1 day running with an computer with sufficient resources. Then it worked. Unfortunately the same issue again with the next transaction. 

@izzycsy  Waiting for your investigation.

**Comment by izzycsy** [comment]
Hi @salomonkarsten the team's investigation discovered an issue on the node side. The workaround is to restart the app, can you try? Thank you.

**Comment by izzycsy** [comment]
Hi @salomonkarsten , update [v2.1.17](https://defichain.com/downloads/) is out.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
