### ISSUE TITLE
Hi @Alkarz, thanks for the screen record. Please give us time to investigate the possibly missing 15 DFI. Next, regarding the DEX issue you're facing, a fix will be included in the next app update. Here's a link to the issue in the mean time. <https://github.com/DeFiCh/app/issues/280>

### ISSUE THREAD

**Issue by Alkarz** [DeFiCh/app#462]
Hi @Alkarz, thanks for the screen record. Please give us time to investigate the possibly missing 15 DFI. Next, regarding the DEX issue you're facing, a fix will be included in the next app update. Here's a link to the issue in the mean time. <https://github.com/DeFiCh/app/issues/280>

_Originally posted by @izzycsy in https://github.com/DeFiCh/app/issues/318#issuecomment-765159310_

**Comment by izzycsy** [comment]
Hi @Alkarz , we're trying to investigate your issue, will get back to you sometime today. Thank you.
