### ISSUE TITLE
DEFI App won't synchronise the blockchain

### ISSUE THREAD

**Issue by gabriello79** [DeFiCh/app#464]
Hello guys,
I'm trying to use the defi chain app on my Pc (surface pro with 16G RAM)...I’m having trouble on synchronization of the blockchain, it stays stucked to 0 blocks synchronised...No firewall...I left the app running overnight but still no result...is there any of you might help?
The strange thing is that the total numbers of blocks are slowly increasing...but the sync is sucked to 0...

**Comment by izzycsy** [comment]
Hi @gabriello79 , may I know if you're on the [v2.1.15](https://defichain.com/downloads/)? Regarding the issue [`Error: Corrupted block database detected`](https://github.com/DeFiCh/app/issues/390), we can further discuss on the problem there. Kindly send your app logs, screenshot of the **error** & **task manager** if possible, as this will provide insights to your issue. Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/106740220-12e23500-6655-11eb-8f4c-5cfccb1fdfb6.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/106740230-15448f00-6655-11eb-920e-0f0605bc979b.png">

<img width="734" alt="Activity Monitor" src="https://user-images.githubusercontent.com/65014479/106740258-1ecdf700-6655-11eb-8352-bebb842ef22c.png">

**Comment by gabriello79** [comment]
Hello,
actually I'm not getting any error...only the sync is stuck into 0.00%
Find some screenshot and the log file.

Thanks for your precious help!
![Immagine](https://user-images.githubusercontent.com/78435161/106743211-5e2d2100-661e-11eb-88fc-0613affc3255.jpg)
![Immagine 1](https://user-images.githubusercontent.com/78435161/106743252-6be2a680-661e-11eb-88ed-eb376a5c96a3.jpg)
[App log.zip](https://github.com/DeFiCh/app/files/5918174/App.log.zip)

**Comment by Darkwinde** [comment]
Had this today as well. Was wondering but figured out that this is caused by not well synced peers. 
Solutionfor me: After app start directly add a peer / node that is synced. As I am running a node to create these blockchain snapshots you can just add my by the following console command:

> addnode "62.75.139.29:8555" add

**Comment by gabriello79** [comment]
> Had this today as well. Was wondering but figured out that this is caused by not well synced peers.
> Solutionfor me: After app start directly add a peer / node that is synced. As I am running a node to create these blockchain snapshots you can just add my by the following console command:
> 
> > addnode "62.75.139.29:8555" add

Thanks Darkwinde...that worked for me!!!
