### ISSUE TITLE
transfer liquidity 

### ISSUE THREAD

**Issue by helhimm** [DeFiCh/app#467]
cannot transfer anything from liquidity pools , no receiving address can be entered when telling how much to take out the button on the boom does not open to confirm

helgehimmeroder@gmail.com

**Comment by izzycsy** [comment]
Hi @helhimm, thanks for your feedback. May I know the OS & app version you're using? Could you describe your user flow more (screenshots / screen recordings are encouraged). Also, kindly send your app logs. This will provide more insight for the investigation. Thank you.

**Comment by helhimm** [comment]
Hi,
in the meantime the system regenerated or what and I was able to access and
remove my funds.
I am just very concerned that the DX programming is not to
professional standart and need
lot of improvements. Furthermore there is ne explanations anywhere on how
to work inside the system and what to do
and how to solve problems when they occur.

regards
HH

**Comment by izzycsy** [comment]
Hi @helhimm , thanks for your feedback. Good to know that you're able to remove liquidity. I do empathise with you as a user myself, furthermore I appreciate that you're open to using the app. At the same time, having a team that is responsive and willing to resolve issues as they come up immediately, that makes me feel safe and secure in my funds even when problems arise. 

You can feel free to contribute to the DeFi App — find out more [here](https://defichain.com/developers/). The purpose of this GitHub Issue page is to address bugs that users face. Although we do test before official release, sometimes new bugs may occur. 

I can try to link you to the PR if you'd like in the future, should you face another issue. Thank you for your feedback.
