### ISSUE TITLE
Remove LP: ApplyRemovePoolLiquidityTx: amount X is less than XXX (code 16)

### ISSUE THREAD

**Issue by Fabialfonso** [DeFiCh/app#468]
### Preflight Checklist

- [x ] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [ x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version: 2.1.15
  - 
- **Previous DeFi App Version:2.1.13
  - 
- **Operating System (OS): MacOS 11.1
  - 

### Screenshot(s) / screen recording(s) of issue
<img width="230" alt="image" src="https://user-images.githubusercontent.com/78506939/106805638-3f06b180-6667-11eb-9772-e6f89f94ab43.png">

<img width="798" alt="image" src="https://user-images.githubusercontent.com/78506939/106805717-547bdb80-6667-11eb-8f7f-71400670ca40.png">

### Actual Behavior
I did some LTC DFI trading two days ago and experience as some other here some serious bugs. The major issue I experience is probably, and this is my assumption, that one of the transaction got on an orphan block or something. The transaction on blockchain (https://mainnet.defichain.io) has been iditcated as "skipped". So some transaction never updated on the Defi app.
A restart also didn't help. After some googling and searching I decided to try some of the command in the CLI. after a clearmempool statement quite some result came up. The app also therefore crashed. It took quite some time until the app was useable again (facing the issue that at 99% the node wasn't found) After I solved this issue and having the newest version of the blockchain on the Mac (deleting the .dat files) and also adding additional UTXO DFI to it,  I am still facing an issue:

I can't remove the Liquidity of the pair DFI - LTC. As shown in the screenshot my balances is indicated as kind of zero, even though the app and also the "Gettokenbalances" shows another result.

Error message in the app says:  ApplyRemovePoolLiquidityTx: amount X is less than 393318466 (code 16)

Note: I tried to remove that liquidity several times in the past and never managed. but as it seemed something got stuck. I also never received the provided DFI or LTC amounts.

Please for help- Thanks in advance!

**Comment by izzycsy** [comment]
Hi @Fabialfonso , thanks for your feedback. Can you try `remove liquidity` at a lower %? Also, I suggest that you do not remove files that you're not familiar with — as we won't be responsible for it. The team regularly do releases, so if you are not in a big hurry I would suggest staying on the latest version and wait for a fix. Thank you for your understanding.

**Comment by Fabialfonso** [comment]
hi @izzycsy , yes I tried to remove lower amounts which wasn't possible. And I only removed those files since it was one of the solutions described here. I still have them and could therefore enter them again. But then again- the blockchain scan stopped 3 times before and a new scan helped. 
When is the new version coming? I am not in a complete hurry but also dont feel super comfortable with the different bugs and weird behavior that I am facing. :/ But what kind of fix is in the pipeline? Did you have similar issues before?

**Comment by izzycsy** [comment]
Hi @Fabialfonso , okay, please keep your files safe. Our team will investigate. There's another user facing a [similar issue](https://github.com/DeFiCh/app/issues/458) recently, yes there's a fix coming but I'm not sure if it'll be included in this upcoming release as this is a new issue. New versions will be announced on [DeFiChain Announcements (EN)](https://t.me/defichain_announcements) . I'll keep this thread open, and will update you when it's ready.

**Comment by Fabialfonso** [comment]
Hi @izzycsy, this morning suddenly the missing transaction has been executed. Dont really know why but everything is in order again. Thanks for the support.

**Comment by izzycsy** [comment]
Hi @Fabialfonso , could be a lag in processing. Thanks for the update.
