### ISSUE TITLE
Settings: Refresh UTXOs > loading loop

### ISSUE THREAD

**Issue by salomonkarsten** [DeFiCh/app#470]
I waited now 24 hours to reload the UTXO and it is still thinking:
![image](https://user-images.githubusercontent.com/77124114/106895524-9dc43d80-66f0-11eb-8d25-9221d925eb94.png)
Attached the binary. which shows the blockchain is synced. All functzions of the app except the upper menu

wallet, Edit, logs, Help  are stuck. 

I will wait until late evening anouther view hours before to stop....
[AppBinaryLogs.log](https://github.com/DeFiCh/app/files/5925806/AppBinaryLogs.log)

**Comment by izzycsy** [comment]
Hi @salomonkarsten , thanks for your feedback. May I know what was the issue that made you want to refresh UTXOs? Thanks for the logs, please give us time to investigate.

**Comment by salomonkarsten** [comment]
@izzycsy first issue not all transactions visible.
So eventually it could solve the mempool issue. 
Also on cli there was enough dfi, I transferred using send 1 DFI to the address for the pool,  I was able to put liquidity in...

**Comment by izzycsy** [comment]
Hi @salomonkarsten , well noted. So I suppose your app is working fine now? I'll be closing this issue in the mean time, you may reopen this thread if the issue persist. The team will look continue to look into the issue.

**Comment by salomonkarsten** [comment]
@izzycsy well the issue remain on Windows...

**Comment by izzycsy** [comment]
@salomonkarsten well noted.

**Comment by izzycsy** [comment]
Hi @salomonkarsten , update [v2.3.0](https://github.com/DeFiCh/app/releases/tag/v2.3.0) is out.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
