### ISSUE TITLE
wallets empty after crash

### ISSUE THREAD

**Issue by joergrossow63** [DeFiCh/app#471]
app unstable, could see values in wallet but not access anymore, no transfer, no DEX or other functions
after re-install app the initial sync stops always at 99,...%, does not finish sync, correct values already shown
I try many times, sync never finishes
installed app on different computer, recover wallet with phrase - all wallets are empty

any idea on what I should do? how to recover the wallets?

**Comment by joergrossow63** [comment]
here a screen shot of the situation

![Screenshot 2021-02-03 at 17 15 41](https://user-images.githubusercontent.com/78553612/106921160-08cf3d80-670c-11eb-9338-572adf7ca818.png)

**Comment by izzycsy** [comment]
Hi @joergrossow63 , thanks for your feedback, was there an error when it was at 99.92% or it was still trying to sync and you closed the app? The values will definitely be showing, as it collects information from the relevant blocks till 100%. You won't be able to use the functions till it reaches 100%. 

If there's no error, and it's taking too long to load beyond 99.92%, try `Reindex Option` via Settings. 

<img width="776" alt="Reindex option" src="https://user-images.githubusercontent.com/65014479/106999508-49d55980-67c1-11eb-9e4e-ad07dbcb0888.png">

**Comment by salomonkarsten** [comment]
@izzycsy From where do ppl. get the GOLD token from ? Just a question. Was there an airdrop?

**Comment by izzycsy** [comment]
Hi @salomonkarsten , no airdrop that I'm aware of, and I've no idea who issued the #GOLD.

**Comment by joergrossow63** [comment]
I don't know why I have this in the wallet, it just appeared when the wallet became unstable

I restarted again, now it stopped @ 99.46%, "node is disconnected" and "pending balance failure" errors

unfortunately now no more balance shown now

any further ideas how i can get back those coins as it is a very substantial amount ? 

<img width="1019" alt="Screenshot 2021-02-05 at 13 38 11" src="https://user-images.githubusercontent.com/78553612/107035117-f4487f00-67b7-11eb-8f39-07b1991c8a71.png">

**Comment by salomonkarsten** [comment]
Look if your swapfile or pagefile is large enough. For unknown reasons the app needs a lot of memory

**Comment by joergrossow63** [comment]
I cleaned up my computer, 114GB free space, app started, disk space reduced to 74GB within 9 minutes, app stopped with error as attached

<img width="1024" alt="Screenshot 2021-02-05 at 15 26 31" src="https://user-images.githubusercontent.com/78553612/107046455-ee0dcf00-67c6-11eb-9e8e-08a6da6ad62c.png">

**Comment by joergrossow63** [comment]
now I am restarting the app with re-index

would it make sense to install the app on a different computer, recover the wallet with 24 word phrase and the coins will be back ?

**Comment by salomonkarsten** [comment]
You can recover your wallet on another computer. 

On your actual one make sure the swap file is large enough

**Comment by joergrossow63** [comment]
this time the sync went through, disk space needed at peak time was 29GB, which is far more then I would ever have expected

thanks a lot for all the help!!!

I could send out the BTC to another wallet already and stop liquidity mining for USDT, but still cannot send out the DFI and USDT

should I re-index or refresh UTXO or even both ?

**Comment by salomonkarsten** [comment]
You need at least 1 DFI as coin not token to be able to send

**Comment by joergrossow63** [comment]
all the re-indexing last night did not work, so this morning I created a new address and send "new" DFI to the already existing 6.032 DFI
after that I was able to send out all funds, just left the 44 GOLD#167 coins behind, no idea what it is or where it came from

again, thanks a lot for all the help!!!
![Screenshot 2021-02-06 at 10 25 43](https://user-images.githubusercontent.com/78553612/107115322-22879680-686c-11eb-8ca6-cdecb96fae66.png)

**Comment by joergrossow63** [comment]
so the solution was re-indexing, providing 30GB disk space for the app to work and creating a new address/sending new DFI
still no idea what GOLD#167 is
