### ISSUE TITLE
Mac: sync stops at 99% workaround

### ISSUE THREAD

**Issue by lraphael** [DeFiCh/app#473]
### Preflight Checklist

- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  - 2.1.15
- **Previous DeFi App Version:**
  - 2.1.14
- **Operating System (OS):**
  - macOS 10.15.7

### Actual Behavior
The syncronization gets stuck. 
I see new blocks, but the current block remains in the same position.
A ReIndex solves the problem only for a short time.

```
1. Open the app
2. Wait
```

### Workarround
When I run the following command, the syncronization works without any problems.
```
addnode "62.75.139.29:8555" add
```
![Bildschirmfoto 2021-02-06 um 08 02 10](https://user-images.githubusercontent.com/2973257/107111600-aa13dc00-6851-11eb-9043-dbde792eeb2f.png)

### App log / binary log / app config
[logs.zip](https://github.com/DeFiCh/app/files/5936417/logs.zip)

**Comment by dell1503** [comment]
Same here, on Mac OS, Wallet 2.1.15.
Workaround 
`addnode "62.75.139.29:8555" add`
works for me as well, thank you @lraphael

**Comment by Okto8on** [comment]
How did you come up with this node address?

**Comment by lraphael** [comment]
From [here](https://github.com/DeFiCh/app/issues/464)  and [here](https://github.com/DeFiCh/app/issues/434)

**Comment by DanielHirsbrunner** [comment]
Thanks alot for the Workarround @lraphael 

I have the same problem on Windows 10, Wallet version 2.1.15.
I tried reindexing -> got stucked
Delete App and all Folders in AppData -> got Stucked
I allwais had 8 node connections active (checked with getconnectioncount command) but it just didn't load any new blocks.

Now with adding the provided node ip it works fine.

**Comment by Jaafa10** [comment]
Doesn't work for me. Even after adding the new node, the sync will continue up to 99.X% and then fail. Node disconnects.

**Comment by izzycsy** [comment]
Hi @Jaafa10 , regarding the issue [`Windows: sync stops at 99%+ > node is disconnected`](https://github.com/DeFiCh/app/issues/325), we can further discuss on the problem there. Kindly send your app logs. We would like to keep same issues in one thread. Thank you.

**Comment by joergrossow63** [comment]
I had the same problem last week, sync always stopped at 99.xx%, node disconnected

cleaned up 30GB disc space, restarted and it worked

the app needed that much of space (at least in my case)

**Comment by Darkwinde** [comment]
> I had the same problem last week, sync always stopped at 99.xx%, node disconnected
> 
> cleaned up 30GB disc space, restarted and it worked
> 
> the app needed that much of space (at least in my case)

Wallet is already at 13GB and rapidly increasing.
@izzycsy: Do you support / plan support pruning feature only to keep the last X blocks?

**Comment by izzycsy** [comment]
Hi @lraphael @dell1503 @Okto8on @DanielHirsbrunner @Jaafa10 @joergrossow63 , update [v2.3.0](https://github.com/DeFiCh/app/releases/tag/v2.3.0) is out.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.

**Comment by Faith04Brave18** [comment]
So I’m very new to the space and very interested in Defichain. I followed instructions and started downloading the snapshot. Several attempts later the synchronization stop at the very end and it’s been stuck for awhile. 
![image](https://user-images.githubusercontent.com/84364091/118584583-a261bd00-b7da-11eb-8ddf-6d63e182eacd.jpg)
  Not sure what do next. I have enough space. TIA
