### ISSUE TITLE
Mac: Sync stuck at 0%

### ISSUE THREAD

**Issue by inyo** [DeFiCh/app#474]
DeFi app version: 2.1.15

1) New install 
2) Sync stuck at 0%
3) Tried to set Reindex after saving to True, but when I click it, it reconnects to peer, but when I navigate to settings again, the option is not selected.
4) App log attached.

### Preflight Checklist

- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  - 
- **Previous DeFi App Version:**
  - 
- **Operating System (OS):**
  -

**Comment by inyo** [comment]
[app.log](https://github.com/DeFiCh/app/files/5936432/app.log)

**Comment by Babwenbiber** [comment]
confirmed on linux and windows a well

**Comment by Darkwinde** [comment]
looks some nodes currently have issues. You can add a synced one by console command. You can use my, if you like:
> addnode "62.75.139.29:8555" add

![DeFiChain_Console](https://user-images.githubusercontent.com/7759961/107117510-03443580-687b-11eb-977c-acd3dff319ac.png)

**Comment by izzycsy** [comment]
Hi @inyo 	, regarding the issue [`Mac: sync stops at 99% workaround`](https://github.com/DeFiCh/app/issues/473), if your problem still persist we can further discuss on the problem there. We would like to keep same issues in one thread. Thank you. 

Hi @Darkwinde appreciate the help!
