### ISSUE TITLE
Lost coins after swapping, getaddressinfo ismine: false

### ISSUE THREAD

**Issue by HeinrichvLangen** [DeFiCh/app#476]
### Preflight Checklist

- [X] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version: 2.1.15**
- **Previous DeFi App Version: 2.1.14**
- **Operating System (OS): MacOS 11.1**

Yesterday i tried to swap ETH into DFI. The defi-app confirm the swap - so I thought it works fine. But the DFI didn’t come and the swapped ETH were not usable anymore. No transfer and no swap again were possible because of insufficient funds. The ETH’s stayed in the app.
That happened during a sync problem. To solve the problem I restart the app. The sync worked fine, but the unusable ETH’s stayed in the app.
I tried a reindex. Worked fine but no change with the ETH’s. So I deleted all of the defi-files on my computer and did a reinstall of the app and the wallet with my keywords. During this process I looked into the same wallet on an another computer. After syncing with all the new blocks the ETH’s were missing. Later on the reinstalled wallet the same problem. Zero ETH’s.
I checked the old address (copied out of the transactions at cake or Bittrex) in the dex-Explorer. The missing ETH’s are still there.

<img width="1575" alt="Bildschirmfoto 2021-02-07 um 07 12 03" src="https://user-images.githubusercontent.com/78666809/107138693-1eb04e80-6916-11eb-9f25-0fe95048436a.png">

So I tried to reactivate the address in the app. It wasn’t possible because the address belongs not to me anymore.
<img width="1015" alt="Bildschirmfoto 2021-02-07 um 07 15 34" src="https://user-images.githubusercontent.com/78666809/107138708-37206900-6916-11eb-82b2-1ea9e58b5097.png">

After checking getaddressinfo it displayed the same problem. ismine=false.
<img width="1015" alt="Bildschirmfoto 2021-02-07 um 07 10 57" src="https://user-images.githubusercontent.com/78666809/107138734-5c14dc00-6916-11eb-9fe0-5c58e46772fa.png">

All former addresses that I deleted in the past worked fine - except of this one. I have no access to this address and with it to the ETH’s.

Please help!

Best regards
Marcus

**Comment by HeinrichvLangen** [comment]
I sent 1 DFI to the crashed address. It worked fine. But no access to this address.
<img width="1186" alt="Bildschirmfoto 2021-02-07 um 08 33 38" src="https://user-images.githubusercontent.com/78666809/107139998-73a49280-691f-11eb-9091-4e237255e1db.png">
<img width="1343" alt="Bildschirmfoto 2021-02-07 um 08 37 58" src="https://user-images.githubusercontent.com/78666809/107140049-db5add80-691f-11eb-831c-c5c15ab23e5f.png">

**Comment by Adrian-source-cmd** [comment]
I have the same problem with adresse dbPyCJidc5mSe3Lys56XCSs1vYxhZigLCs

**Comment by HeinrichvLangen** [comment]
I could reproduce the problem with the not accessible address. I encrypt the wallet first and delete the wallet after that to restore the wallet. After restoring with the 24 keywords the wallet is not encrypted anymore. By adding the old addresses from the former encrypted wallet-version come the same error message like my issue: "Invalid address. Please check this belongs to you". A new encryption with the same passphrase didn't help. Obviously the addresses from a former encrypted wallet are not usable in a restored wallet. So this would be no problem when the balances are there. In my case I afraid, that the lost coins are somehow connected with the address from the former encrypted wallet.
So I hope for help getting the lost coins or solving this problem with the next app-version.

**Comment by szene23** [comment]
I have a similar problem. After reinstalling the DeFi app, only 2 of 3 wallet addresses were displayed. When trying to enter the missing address by hand, the following error occurs: Invalid address. Please make sure this address is yours. (Ungültige Adresse. Bitte versichere dich, dass diese Adresse dir gehört.) Need help very soon ='(

**Comment by HeinrichvLangen** [comment]
I tried the unusable address again in 2.1.17. There happened something strange. Again I could not add the old address, but after set on automatically adding, there was suddenly the old address displayed.
<img width="777" alt="Bildschirmfoto 2021-02-12 um 02 42 13" src="https://user-images.githubusercontent.com/78666809/107722148-9992b400-6cde-11eb-82a7-aec437fd1b68.png">
<img width="772" alt="Bildschirmfoto 2021-02-12 um 02 42 45" src="https://user-images.githubusercontent.com/78666809/107722157-9e576800-6cde-11eb-8534-b602e9ca9ff2.png">
<img width="766" alt="Bildschirmfoto 2021-02-12 um 02 43 46" src="https://user-images.githubusercontent.com/78666809/107722167-a1eaef00-6cde-11eb-8d9c-0bbe57f52441.png">

But this address didn't work correct. There were not the missing token displayed and by using the dex, it told me, that this address is not my own.

<img width="826" alt="Bildschirmfoto 2021-02-12 um 02 44 39" src="https://user-images.githubusercontent.com/78666809/107722340-0017d200-6cdf-11eb-9c23-15f303e3d8bd.png">
<img width="241" alt="Bildschirmfoto 2021-02-12 um 02 45 05" src="https://user-images.githubusercontent.com/78666809/107722348-04dc8600-6cdf-11eb-9baa-9b4446050ba6.png">
<img width="828" alt="Bildschirmfoto 2021-02-12 um 02 45 32" src="https://user-images.githubusercontent.com/78666809/107722352-073ee000-6cdf-11eb-8057-dd43037551c8.png">

after closing and restart the app, the address was missing.

<img width="1013" alt="Bildschirmfoto 2021-02-12 um 02 46 59" src="https://user-images.githubusercontent.com/78666809/107722410-263d7200-6cdf-11eb-8880-63a966ffd9e6.png">

hoping for the next app version
Marcus

**Comment by izzycsy** [comment]
Hi @szene23 @Adrian-source-cmd , regarding the issue [`Warning: Address not saved by seed phrase`](https://github.com/DeFiCh/app/issues/267), we can further discuss on the problem there. Let’s keep this thread related to what the original author opened. Thank you for your understanding.

**Comment by izzycsy** [comment]
Hi @HeinrichvLangen , thanks for your feedback. As I understand, one of the tech team devs replied you on [reddit](https://www.reddit.com/r/defiblockchain/comments/lh52rg/restoring_of_an_encrypted_wallet_with_the_seeds/). Please understand that we’re not here to recover if you’ve lost your funds due to your own misinterpretation / misunderstanding — or whether impermanent loss etc, but what we can do is try to help investigate where the funds went.

After investigating your situation, in summary: 

• User swapped ETH to DFI. 
 • Transaction did not get through because of insufficient utxoDFI.   
 • User then restarted the app because there was a sync problem, synced to 100%, ETH still reflected in app. This confirms that your ETH did not leave the address.   
 • But it seems like user misunderstood the issue and went to reindex and deleted deli-files on PC A, did a reinstall of app with mnemonic seed
 
It is possible that your ETH did not leave your address `dWbNJYqsZeLg8baQbb3mYoxtkT8rAktJLU` as shown [here](https://dex.defichain.com/mainnet/address/dWbNJYqsZeLg8baQbb3mYoxtkT8rAktJLU). Meaning to say that there was not an issue and you may have complicated it. 
What you could do is try and recover your wallet using your wallet.dat, on Mac it is located here: 

Mac — Go to Folder:  
`/Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat`
 
you will see several wallet.dat files named `wallet-bak-1234567890123.dat` — do not delete any of these, make a copy and move them to a safe location.   Proceed with the following:  
1. Ensure app is not running
 2. Backup the `wallet.dat` file 
 3. Remove `wallet.dat` from `DeFi/wallets` folder 
 4. With the remaining _wallet.dat_, **rename** one of the files to `wallet.dat` 
  (in my case I’ll rename _1605637015196.dat__to _wallet.dat_) 

Launch app and see if your balances are reflected. 

<img width="626" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/107754726-d8674f00-6d5c-11eb-84bb-56e4a06ce052.png">

**Comment by HeinrichvLangen** [comment]
Hello izzycsy,
thanks for your response. Unfortunately i deleted these folders and cleared my trash since that. So i don`t have any backup from the encrypted version of my wallet.

**Comment by yacrazyone** [comment]
maybe there is a way you can recover the files. I did a quick [google search](https://www.easeus.com/mac/mac-data-recovery-resource/recover-mac-deleted-file-from-trash.htm) and there seem to be some options to recover after trash clearing.

**Comment by HeinrichvLangen** [comment]
Thanks, yacrazyone. You are so nice, but i already tried easeus as well as some other software the whole week. I think i tried all of them on the market. Without success. They found nothing.

**Comment by HeinrichvLangen** [comment]
Hello izzycsy,
i tested the encryption-fuction a little bit more under 2.1.15 and there are some things the team should know. The problems appeared with NEW addresses after encryption and AFTER doing a backup. By restoring the wallet with the seeds OR a backup before adding a new adress, the new Addresses were not accepted. So i think the only way in an encrypted wallet to avoid this problem is to backup everytime after creating a new address. But this should be mentioned in your advice https://github.com/DeFiCh/app/wiki/Wallet-Encryption

There some other things i want to address:

1. The only note that the seeds are gone appear directly AFTER encryption. Then it's too late. Is has to be appear before. Everyones seeds are holy. If someone don't realize or forget this information, they have lost.
2. During the wallet is locked, there is no note, that the backup wasn't created. You got a note that transfers or swaps are not possible, but no note, that the backup was not created. Users maybe wonder about, that there is no backup, when it's needed.
3. By resetting the wallet in 2.1.15 there was no warning, that in future the seeds are useless and a backup or the old wallet.dat with all new added addresses are nessesary to keep the funds.
4. After resetting the wallet in 2.1.15, there was no option to load a backup in the UI - only restore from the (useless) seeds. It seems that then is no need to import the backup, but it only works with it.

I can't believe that i am the first one who realize this and i can't believe that the seeds are useless. Hope there is a missunderstanding on my side but maybe it helps you to improve the app and the encryption guide.
I know you are doing your best.

Marcus

**Comment by HeinrichvLangen** [comment]
Hello izzycsy,
thanks to Ahmed Hilali for changing the Encryption-guide. I wish I could have read this before. I would never have encrypted the wallet. Anyway. Do you have any ideas, what to to with the funds? They have a rising value and they are still in nirvana. Will an update solve the problem?
Marcus

**Comment by izzycsy** [comment]
Hi @HeinrichvLangen you can see if you can add your address back to your wallet and self transfer to your new address. If you've deleted your `wallet.dat` files then we're unable to help guide you on how to retrieve it either. 

Please do understand that DeFiChain an open source project and that your funds are your own responsibility, what we can do is try to help investigate where the funds went. Transactions are either processed or not processed, there's no "halfway" state where it gets stuck in the middle. Thank you for your understanding and patience once again. 

Regarding `Warning: address not saved by seed phrase` , there's currently no fix for this error yet as the mnemonic seed somehow does not register the existing addresses, a few users faced the same [issue](https://github.com/DeFiCh/app/issues/267) as well. However, moving forward in update [v2.3.0](https://github.com/DeFiCh/app/releases/tag/v2.3.0), we'll be introducing _wallet passphrase_ (optional), and the utilisation of `wallet.dat`. Please keep your `wallet.dat` file safe. Hence, this error should not occur anymore. Apart from safe-keeping `wallet.dat`, personally, I keep a copy of my addresses in my Notes too. With this, I'll be closing this issue. Thank you for your understanding and patience on this issue!
