### ISSUE TITLE
Unable to send BTC to another wallet address.

### ISSUE THREAD

**Issue by jimmytscotia** [DeFiCh/app#477]
I am unable to send BTC from the Defi App to another BTC wallet address. The confirm buttton is greyed out.

[app_config.log](https://github.com/DeFiCh/app/files/5938988/app_config.log)
[app_log.log](https://github.com/DeFiCh/app/files/5938989/app_log.log)
[binary_log.log](https://github.com/DeFiCh/app/files/5938990/binary_log.log)
<img width="1034" alt="Screenshot 2021-02-07 at 12 42 16" src="https://user-images.githubusercontent.com/67348200/107146891-c80d3980-6942-11eb-83d1-19f6a414e067.png">

**Comment by OtenMoten** [comment]
> I am unable to send BTC from the Defi App to another BTC wallet address. The confirm buttton is greyed out.
> 
> [app_config.log](https://github.com/DeFiCh/app/files/5938988/app_config.log)
> [app_log.log](https://github.com/DeFiCh/app/files/5938989/app_log.log)
> [binary_log.log](https://github.com/DeFiCh/app/files/5938990/binary_log.log)
> <img alt="Screenshot 2021-02-07 at 12 42 16" width="1034" src="https://user-images.githubusercontent.com/67348200/107146891-c80d3980-6942-11eb-83d1-19f6a414e067.png">

Hey bro,

technical there is no error. Let me explain this:

The BTC you hold on the DEFI wallet is stored in the DEFIchain. It's kind of wrapped BTC Token. This is a great advantage for the developers and the whole DEFI ecosystem. Therefore, currently you need to send the BTC from DEFI app wallet via DEFIchain protocol to Cake and from Cake you can send the wrapped BTC Token via normal BTCchain to any address.

Greetz

**Comment by jimmytscotia** [comment]
Thanks for the response. I'm still new this so I'm afraid I need more information on how exactly to go about doing that. What website, wallet or exchange do I need to transfer the wrapper BTC token to in the first instance? Are you referring to https://www.cakedefi.com/ or the Cake Wallete or something else? I think the product needs clearer instructions for those of us that are not defi blockchain experts.

**Comment by jimmytscotia** [comment]
Same for Ethereum?

<img width="1022" alt="Screenshot 2021-02-07 at 17 10 36" src="https://user-images.githubusercontent.com/67348200/107153853-9bb7e400-6967-11eb-90e7-339c23c54b16.png">

**Comment by jimmytscotia** [comment]
Same for Ethereum?

<img width="1022" alt="Screenshot 2021-02-07 at 17 10 36" src="https://user-images.githubusercontent.com/67348200/107153928-fd784e00-6967-11eb-8f7d-0077eef6254f.png">

**Comment by izzycsy** [comment]
Hi @jimmytscotia , it's likely that the the address you’re using is not a DeFiChain-friendly address. You can retrieve the DeFiChain address via <cakedefi.com>, try sending a small amount first to test. Same goes for ETH and other tokens. 

1. Click on Balances in <cakedefi.com>
2. In the BTC row, click on Deposit button
3. You'll see the Transfer Network options `BTC` / `DeFiChain`
4. Under the QR Code states your DeFiChain address, copy it
5. Go to DeFi app > BTC wallet > Send
6. Paste your DeFiChain address into `To address` field

<img width="375" alt="Click DeFiChain   BTC" src="https://user-images.githubusercontent.com/65014479/107192097-24965480-6a28-11eb-89c3-47c52db74e87.png">

<img width="362" alt="Click DeFiChain   ETH" src="https://user-images.githubusercontent.com/65014479/107192105-27914500-6a28-11eb-9ae4-4a046bbd1b94.png">

Attaching some links that may help you with these kind of enquiries: 
[DeFiChain Telegram (EN)](https://t.me/defiblockchain)
[DeFiChain Telegram (DE)](https://t.me/defiblockchain_DE) 
[DeFiChain Announcements (EN)](https://t.me/defichain_announcements) 

Hi @OtenMoten , thanks for the help!

**Comment by jimmytscotia** [comment]
Can this issue be placed into an open state again please? I have opened an account on cafedefi.con and I still get the same issue of the "Continue" button being greyed out. I am now worried about losing my investment in your project and not being able to transfer my funds out of the walltet. 
<img width="1041" alt="Screenshot 2021-02-13 at 01 17 23" src="https://user-images.githubusercontent.com/67348200/107837556-534e5b00-6d99-11eb-8ca1-a18332d249be.png">
