### ISSUE TITLE
Can't send ETH

### ISSUE THREAD

**Issue by Folderguion** [DeFiCh/app#484]
Hello,

I've installed the Wallet in Linux, Network is sync and received some DFI founds. I swapped to ETH but now I can't SEND the ETH ammount. I can't tap "continue" because is not highlighted. 

Any ideas? 

Thank you.

**Comment by UserMaxL** [comment]
Probably you are trying to send to a ETH Address. You can't send the Defichain ETH to an ETH address from the App at the moment, because it's not real ETH. There will be an option to do an atomic swap in the Q1'21 releases, so you can swap to real ETH. At the moment you can only send the ETH to a DeFi Chain address (to Cake for example). At Cake you can send to another ETH address.

**Comment by Folderguion** [comment]
Thanks for the help. Yes I had the DFI and swapped to ETH thinking it was real ETH :/ So the solution should be to switch back to DFI and send the DFI to Cake right? In Cake will be possible to exchange DFI to ETH again correct?

**Comment by UserMaxL** [comment]
Hi, no. You can send this non-real ETH (let's call it D-ETH) to CAKE using you DFI address from there (Choose DeFi Chain in the deposit section). No need to change ETH back to DFI. At Cake the D-ETH is automatically ETH and D-ETH, depending which network you choose for a deposit (ETH or DeFi Chain).

**Comment by izzycsy** [comment]
Hi @Folderguion , the address you’re using is not a DeFiChain-friendly address. You can retrieve the DeFiChain address via <cakedefi.com>, try sending a small amount first to test.

1. Click on Balances in <cakedefi.com>
2. In the ETH row, click on Deposit button
3. You'll see the Transfer Network options `ETH` / `DeFiChain`
4. Under the QR Code states your DeFiChain address, copy it
5. Go to DeFi app > ETH wallet > Send
6. Paste your DeFiChain address into `To address` field

<img width="362" alt="Click DeFiChain   ETH" src="https://user-images.githubusercontent.com/65014479/107361140-dd848e00-6b11-11eb-9435-d909ce6f724f.png">


 You may turn to Cake’s telegram for Cake-related issues: 
(CakeDeFi Telegram (EN))[https://t.me/CakeDeFi_EN]
 (CakeDeFi Telegram (DE))[https://t.me/CakeDeFi_DE]
 
 Hi @UserMaxL , appreciate the help!

**Comment by Folderguion** [comment]
Thank you guys. How can I be informed whether will be possible to send real ETH?

**Comment by UserMaxL** [comment]
Are you on Telegram? https://t.me/defichain_announcements

**Comment by Folderguion** [comment]
Joined, tnx!
