### ISSUE TITLE
Restore wallet > balances not reflected

### ISSUE THREAD

**Issue by kyoungrok0517** [DeFiCh/app#485]
### Issue Details
I see "Create a new wallet" button even if I recovered and completed syncing. I downgraded from 2.1.16 to 2.1.15 because the balances aren't displaying at all. Now the sync is complete, liquidity balance is showing normal. But I can't see the balance in the Wallet (screenshot#1). Also I can't see any address attached to me in DEX menu (screenshot#2)

- **Current DeFi App Version: 2.1.15**
- **Previous DeFi App Version: 2.1.16**
- **Operating System (OS): Mac 11.2**

### Screenshot(s) / screen recording(s) of issue
<img width="620" alt="image" src="https://user-images.githubusercontent.com/1051900/107332355-69d58780-6af7-11eb-8fce-c2dffbb47f80.png">

<img width="803" alt="image" src="https://user-images.githubusercontent.com/1051900/107331766-aa80d100-6af6-11eb-8c17-c3a2aace4f62.png">

<img width="749" alt="image" src="https://user-images.githubusercontent.com/1051900/107332776-f41deb80-6af7-11eb-9de3-5e9d7fdff8a1.png">

### App log / binary log / app config
[binary-log.log](https://github.com/DeFiCh/app/files/5949688/binary-log.log)
[app-log.log](https://github.com/DeFiCh/app/files/5949690/app-log.log)
[app-config.conf.txt](https://github.com/DeFiCh/app/files/5949692/app-config.conf.txt)

**Comment by izzycsy** [comment]
Hi @kyoungrok0517 , thanks for your feedback. Sometimes it's a lag that causes the balances to not be displayed. However, to check your balances please type the following the CLI: 

`getbalance` — utxoDFI
`gettokenbalances` — accountDFI
  The sum of utxoDFI & accountDFI would be your total tokens.

`listaccounts {} true true true` — breakdown of your coin(s) / token(s)

What is the output there? 

Following which, what I would do is _copy & paste_ the addresses into Notes or somewhere — this is in case your Receive Address remains empty, you still have a backup of it.  

I do not recommend installing older version for your safety and security, the team is constantly working on improving the app and solving its issues. We regularly do releases, so if you are not in a big hurry I would suggest staying on the latest version and wait for a fix.

**Comment by izzycsy** [comment]
If the output in the CLI is not your token value before the display went blank, you can try recover your wallet by finding the backup wallet.dat in the wallets folder. On Mac it is located here: 
 
Mac — Go to Folder: 
` /Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat`
 
you will see several wallet.dat files named `wallet-bak-1234567890123.dat` — do not delete any of these, make a copy and move them to a safe location.   Proceed with the following: 

1. Ensure app is not running
2 . Backup the `wallet.dat` file 
  3. Remove `wallet.dat` from `DeFi/wallets` folder
    4.  With the remaining _wallet.dat_, **rename** one of the files to `wallet.dat`  
  (in my case I’ll rename _1605637015196.dat__to _wallet.dat_) 

Launch app and see if your balances are reflected. 

<img width="650" alt="Rename wallet dat file" src="https://user-images.githubusercontent.com/65014479/107363000-7fa57580-6b14-11eb-8477-6724b509d896.png">

**Comment by eagleel** [comment]
I cannot even open the app, it will not load at all just tells me 'cannot start blockchain'

I am running 2.1.15 and have tried downloading 2.1.17 app it does exactly the same thing. 
Trying to use the recover your wallet by finding back up wallet but I cannot even find that folder.

**Comment by izzycsy** [comment]
Hi @eagleel , I've replied your message, as I understood you're using MacOS, and regarding your [`issue`](https://github.com/DeFiCh/app/issues/473), we can further discuss on the problem there. Let’s keep this thread related to what the original author opened. Thank you for your understanding.

**Comment by izzycsy** [comment]
Hi @elxlee , following up from [#500](https://github.com/DeFiCh/app/issues/500), similar t to the comment above, you may be able to recover your wallet by finding the backup wallet.dat in the wallets folder. On Windows it is located here: 

Windows — C: 
 \Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat
 
you will see several wallet.dat files named `wallet-bak-1234567890123.dat` — do not delete any of these, make a copy and move them to a safe location.   Proceed with the following:  

1. Ensure app is not running
 2. Backup the `wallet.dat` file
  3. Remove `wallet.dat` from `DeFi/wallets` folder
   4. With the remaining _wallet.dat_, **rename** one of the files to `wallet.dat` 
    (in my case I’ll rename _1605637015196.dat__to _wallet.dat_) 
    
Launch app and see if your balances are reflected. 

<img width="650" alt="Rename wallet dat file" src="https://user-images.githubusercontent.com/65014479/107943543-d2c17180-6fc7-11eb-88c6-88a8b864a614.png">

**Comment by izzycsy** [comment]
Hi @kyoungrok0517 , update v2.3.0 is out <https://github.com/DeFiCh/app/releases/tag/v2.3.0>.
	
Do give a thumbs up to this comment if your issue has been resolved, otherwise, please provide new information (include screenshots) and app logs. Thank you.
