### ISSUE TITLE
Unable to start blockchain

### ISSUE THREAD

**Issue by eagleel** [DeFiCh/app#487]
When I try to open the app I am getting 'uable to start blockchain'

I have no other options to try other than close the app. I am running 2.1.15

Do I need to delete the app and reinstall with my seed words

**Comment by eagleel** [comment]
Unable to start blockchain

**Comment by eagleel** [comment]
I cannot get around the Security the Way I did with the first install.

**Comment by Darkwinde** [comment]
Hi @eagleel,
2.1.17 is out, worth to check with this version. 
Are you using Windows or Mac or Linux?
Have you checked for enough space as blockchain already required 13 GB....

**Comment by eagleel** [comment]
Hi Darkwinde 

Thanks for replying 

Yeah I tried that.....  does exactly the same thing, doesn't open at all just the same message.
 I am using Mac with 233GB spare

I have received some things to try from tech  but cannot even get to those files.

Have you tried deleting the app completely and starting again with the seed words?

**Comment by Darkwinde** [comment]
Hi @eagleel,
I am a Windows or Linuy kiddi, so my ability to help will be limited...but lets try 😄  
Would it possible to share the app and binary log? How-To: https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app

Do you know, if the installation directory requires certain rights to write, e.g. special user rights etc.?
Did you try to add a node manually? DeFi app console command: addnode "62.75.139.29:8555" add

![Node add](https://user-images.githubusercontent.com/2973257/107111600-aa13dc00-6851-11eb-9043-dbde792eeb2f.png)

**Comment by eagleel** [comment]
Hi Darkwinde, The app does not even go past just trying to start. I have no access to the console. It never opens just after a few mins it says unable to start blockchain. 😔

**Comment by Darkwinde** [comment]
Hi @eagleel,
ok hmmm then I am out, and @izzycsy can may help to find the log location.

As an example for Windows they are located:
> %appdata%\Roaming\defi-app\logs\main.log
> %appdata%\Roaming\DeFi Blockchain\debug.log

**Comment by Mihalis1312** [comment]
Hi Everbody, I just have the same trouble. App v. 2.1.7 doesn't start at all

Some ideas anybody?

**Comment by eagleel** [comment]
Thanks a lot Darkwinde for trying to help👍.
 Miraculously after trying restarts of 2.1.15 app and the 2.1.17 app all of sudden the 2.1.15 started to load and has shown everything as it should.
But when I try to update it comes with an error and tells me to download from the website. So I guess this means I need to start from scratch if I want the new 2.1.17?

**Comment by Mihalis1312** [comment]
HI eagleel, there did you get the 2.1.15 app? I would try it also

**Comment by eagleel** [comment]
Hi Mihalis, 2.1.15 is the app I have been running. It all of a sudden decided to work. But I cannot upgrade to 2.1.17. 

I am starting to realise I probably do not know enough yet to be using DeFiChain. I will end up losing my money to float around the universe for eternity😂

**Comment by izzycsy** [comment]
Hi @eagleel , are you running 2 DeFi apps on 1 device?

Hi @Mihalis1312 , I do not recommend installing older version for your safety and security, our team is constantly working on improving the app and solving its issues. We regularly do releases, so if you are not in a big hurry I would suggest staying on the latest version and wait for a fix. Thank you for your understanding. May I know if you're facing the same issue — `unable to start blockchain`?

**Comment by eagleel** [comment]
Hi, thanks for following up, no I only have the 2.1.17 and it will not even install due to the security. 
I simply cannot get around it as of now. Just keeps telling me to contact the developers. 

Tony

**Comment by izzycsy** [comment]
Hi @eagleel , can you send a screenshot of the security prompt?

**Comment by eagleel** [comment]
<img width="446" alt="Screenshot 2021-02-17 at 10 56 57" src="https://user-images.githubusercontent.com/78055383/108187766-1b377700-710f-11eb-8fe2-2d258052f973.png">
I have completly deleted the app and trying to install a new version. But I get this message and cannot see how to get around it. Just don't get the option in system preferences to get around the security.

**Comment by izzycsy** [comment]
Hi @eagleel , as discussed on Reddit, this issue is resolved for now, I suggest that you check your Mac firewall settings etc, maybe it has to do with that that's preventing you from allowing to use the app. Thank you, I wish you the best.

**Comment by Babwenbiber** [comment]
I have the same problem when I start the App on upgrading to 2.30
Im on Windows
