### ISSUE TITLE
No receive addresses available

### ISSUE THREAD

**Issue by jung-eto** [DeFiCh/app#489]
Hello Team,
there is a new behavior which might be a bug?

### Issue Details

- **Current DeFi App Version:**
  - v2.1.17
- **Previous DeFi App Version:**
  - v2.1.16
- **Operating System (OS):**
  - macOS Big Sur 11.2

### Screenshot(s) / screen recording(s) of issue
<img width="1023" alt="Bildschirmfoto 2021-02-09 um 12 43 06" src="https://user-images.githubusercontent.com/78017139/107472651-9d53f880-6b6f-11eb-8567-acc02b6649f8.png">

### Actual Behavior

1. Open the app
2. Go to wallet page
3. Click on DFI
4. Click on Receive
5. see Message "No receive addresses available"

### Expected Behavior
1. Open the app
2. Go to wallet page
3. Click on DFI
4. Click on Receive
5. see my receive address(es) 

### App log / binary log / app config
[App_Logs.zip](https://github.com/DeFiCh/app/files/5956206/App_Logs.zip)

This behavior first occured in v2.1.16 and still persists in v2.1.17
Thank you, as always, for investigating :)

**Comment by Darkwinde** [comment]
A really stupid question, but you already created one before and have send some DFI to it, or?

**Comment by jung-eto** [comment]
Hi @Darkwinde , 
i do not think your question is stupid!
Yes, my wallet works well, I am into LM, listaccounts {} false false true shows my address and getaddressinfo "myaddress" shows "ismine" : true.
I am facing this issue here since the update to v2.1.16. Before that I was facing another issue with my address which is written in issue #267

**Comment by izzycsy** [comment]
Hi @jung-eto , thanks for your feedback, regarding the issue [Warning: Address not saved by seed phrase](https://github.com/DeFiCh/app/issues/267), the workaround has been mentioned there. For this issue that you're facing, my take is that it's a carry forward from what you were facing. That the seed did not save your address somehow. 

You can try the following — it's a workaround to restore wallet but it might resolve your issue. On ________ it is located here: 
 
Mac — Go to Folder: 
` /Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat`
 
you will see several wallet.dat files named `wallet-bak-1234567890123.dat` — do not delete any of these, make a copy and move them to a safe location.   Proceed with the following:  

1. Ensure app is not running
 2. Backup the `wallet.dat` file
  3. Remove `wallet.dat` from `DeFi/wallets` folder 
  4. With the remaining _wallet.dat_, **rename** one of the files to `wallet.dat` 
   (in my case I’ll rename _1605637015196.dat__to _wallet.dat_) 

Launch app and see if your balances are reflected. 

<img width="650" alt="Rename wallet dat file" src="https://user-images.githubusercontent.com/65014479/107625012-ac819600-6c96-11eb-9488-98c4b1eba281.png">

**Comment by jung-eto** [comment]
Hi @izzycsy ,
thank you for your detailed workaround instruction. Unfortunately there are no such files that I could rename...
Please see screenshot. Any ideas?
<img width="433" alt="Bildschirmfoto 2021-02-11 um 19 20 43" src="https://user-images.githubusercontent.com/78017139/107680699-82cc6d00-6c9e-11eb-8fa3-1b4ae3a6c734.png">

**Comment by izzycsy** [comment]
Hi @jung-eto , regarding the issue [`Warning: Address not saved by seed phrase`](https://github.com/DeFiCh/app/issues/267), we can further discuss on the problem there. We would like to keep same issues in one thread. Thank you.
