### ISSUE TITLE
DEFI-cli-exe and desktop wallet 

### ISSUE THREAD

**Issue by salomonkarsten** [DeFiCh/app#491]
Hello,

I want to setup the the shell based defi-cli.exe to interact with the defi desktop wallet. Where should i put it. If i run it, it states defid not running. but it must be running somewhere as the desktop wallet is permanently syncing and running.  Intention is to be able to write script batch files using the defi-cli.exe  on command shell. 

Thanks in advance

**Comment by monstrobishi** [comment]
Hi, the app uses some specific settings for interacting with the daemon including RPC authentication. I suggest you run defid separately without the app open, it will still connect to your default wallet and have access to your funds. Thanks

**Comment by salomonkarsten** [comment]
Is there a specific folder to run the defid from on Windows?
Usually i found folder created from the Desktop App under %appdata%

Please advise

**Comment by salomonkarsten** [comment]
@monstrobishi sorry the above message Was for you...

**Comment by monstrobishi** [comment]
you can run defid from any folder. it will look for your wallet inside the AppData/Roaming/Defi Blockchain directory

**Comment by salomonkarsten** [comment]
@monstrobishi perfect thanks. I guess the Desktop App needs to be closed to not get into conflict right?

**Comment by monstrobishi** [comment]
yes correct

**Comment by salomonkarsten** [comment]
@monstrobishi lovely works like a charm.

Thanks a lot!

**Comment by salomonkarsten** [comment]
@monstrobishi Hello sorry to ask again. within the desktop app as well as in linux following command works nice:

listaccounthistory mine {"maxBlockHeight":515339,"depth":0,"limit":1000}

but calling: 
defi-cli.exe listaccounthistory mine {"maxBlockHeight":515339,"depth":0,"limit":1000}

from the shell when defid is running returns 

error: Error parsing JSON:{maxBlockHeight:515339,depth:0,limit:1000}

Any idea? Thanks in advance

**Comment by salomonkarsten** [comment]
@monstrobishi might there a Problem with quotation Marks? IT seems other commands with quotation marks also do not work?

The command 
defi-cli.exe listaccounthisrory mine {} 

does work. But it is not what I would need.

In principle I like to parse through all blocks to extract my transactions directly in VBA to include in excel. All setup call shell command from Excel and write the Jason output in spreadsheet but the command should work. 

Please advise

Thanks for your help in advance.

**Comment by monstrobishi** [comment]
Hi when running through CLI you can put single quotes e.g. ' around the json object

**Comment by salomonkarsten** [comment]
@monstrobishi Hello thanks for the hint, but none of the following helps:
![image](https://user-images.githubusercontent.com/77124114/107829701-9228e480-6d8a-11eb-8124-f8f2ad1250d0.png)

on linux it works with the single quotes not on win command shell cmd. please advise.

**Comment by salomonkarsten** [comment]
I should mention, i am running Windows 10.

Did you succeed to run this cimmand in Windows?

**Comment by monstrobishi** [comment]
Since you are wrapping the inside with double quotes e.g. ", you want to wrap the outside with single e.g. '

So for example '{"depth":100}'

**Comment by salomonkarsten** [comment]
@monstrobishi As you can see wrapping the outside is not sucessful and leeds to a jason parsing error. 

In Desktop app the single quotes are also not accepted. But anyways I will not be able to use the desktop app for what I want to set up. I just tried. I also tried on Linux on my Raspberry pi. There the single quotes seem to work.

so once again any idea. Or better have you ever succeeded to run a command with Jason structures on the windows command shell?

![image](https://user-images.githubusercontent.com/77124114/107853441-6bb08b00-6e16-11eb-9c72-ad58f741ad31.png)

**Comment by monstrobishi** [comment]
Single quote is only needed in command shell, app doesn't need single quote

**Comment by monstrobishi** [comment]
For windows maybe you have to escape all the double quotes inside by doing "{\"key\":100}"

**Comment by salomonkarsten** [comment]
@monstrobishi Amazing the bachslash did the Trick. Should be added to a readme somewhere.

Thank you so much!

Kind regards

**Comment by salomonkarsten** [comment]
Thanks
