### ISSUE TITLE
Can not remove liquidity from pool

### ISSUE THREAD

**Issue by Mihalis1312** [DeFiCh/app#493]
### Preflight Checklist

- [ ] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  - 
- **Previous DeFi App Version:**
  - 
- **Operating System (OS):**
  -

**Comment by Mihalis1312** [comment]
I am unable to remove the liquidity from pool. I get the following failure: 
ApplyRemovePoolLiquidityTx: amount 9884 is less than 370474005 (code 16)

That does it Mean and how I can remove the liquidity? Is there a minimum amount, it isn't mentioned anywhere…

Please comment…

Thx
[Logs.zip](https://github.com/DeFiCh/app/files/5963705/Logs.zip)

**Comment by izzycsy** [comment]
Hi @Mihalis1312 , thanks for your feedback, the error shown is probably due to some pending transactions that you have — could you made too many transactions in the same block. Wait for next block and your issue should be resolved. We will update the error message to improve the UX in the next build. Thank you.

**Comment by Mihalis1312** [comment]
Hallo Bella, thank you. That worked after restart and wait.  But now I can't start the app at all. the UX says "can't start the blockchain" and the app does not start. So I even can't provide some logs… I reinstalled the app on my Mac. It didn't help.

Do you have some ideas?

Thx
