### ISSUE TITLE
Keinen Zugriff auf Defi Chain

### ISSUE THREAD

**Issue by Sim-Cyber** [DeFiCh/app#495]
Hallo liebe Community und Entwickler,
ich habe keinen Zugriff mehr auf meine Wallet. Das seit ende Dezember 2020!
Ich moechte die DeFI Chain öffnen und es erscheint leider nur dieses Fenster.
Keine Synchronisierung.

**Screenshoot**
![2021-02-11](https://user-images.githubusercontent.com/76777781/107690490-76e6a800-6caa-11eb-8e1b-1afc7eb64be8.png)

Bitte helfen Sie mir ich sorge mich wie gesagt schon seit 2 Monaten um das Problem.

**Aktuelle Version**
2.1.17

**Betriebssystem**
Windows 10

**Hier sind die Logs, es waere klasse, wenn mir jemand bei dem Problem helfen koennte**

[App Logs.log](https://github.com/DeFiCh/app/files/5968054/App.Logs.log)
[Binary Logs.log](https://github.com/DeFiCh/app/files/5968055/Binary.Logs.log)

Freundliche Grüße,
Simon

**Comment by Darkwinde** [comment]
Hi @Sim-Cyber ,
besteht das Problem weiterhin, wenn du den re-index machst oder hast du immer an der Stelle abgebrochen?

Die Meldung sagt aus, dass deine Blockchain korrupt ist und neu geladen werden muss. Das ist mir häufig passiert im Zusammenhang der alten Wallets, da diese zu schnell geschlossen haben bevor alle Zugriffen beendet waren und in Kombination mit meinem Virenscanner. Hab den Blockchain Ordner als Ausnahme definiert und dann nicht mehr das Problem beobachtet. Vielleicht hilft dir das.

Da du ja den Seed hast, kannst du auch nochmal alles unter "C:\Users\%username%\AppData\Roaming\DeFi Blockchain" in ein Archiv-Ordner verschieben und die App starten. Dann sollte alles neu angelegt werden. Falls dann Probleme sind, kannst die alten Daten aus dem Archiv auch immer wieder zurück kopieren.

**Comment by Sim-Cyber** [comment]
Hallo Darkwinde, 
vielen danke für deine ausfuehrliche Antwort. 

Du recht, das Problem taucht seit Version 2.3 auf und ich vermute auch das es daran liegt, dass die App geschlossen wurde obwohl noch nicht alle Zugriffe beendet waren. 
Das Problem mit dem Virenscanner habe ich bereits beseitigt. 

Ich bin Crypto ´´neuling´´ und weiß leider nicht wie man einen re-index ausführt.
Ich habe ´´delete peers and blocks´´ aktiviert und  ´´ App neustarten´´ ausgeführt. Leider hat das nichts gebracht.
War das ein re-index oder muss ich das manuell irgendwie starten?
Für eine weitere Antwort wäre ich sehr sehr dankbar.

**Comment by Darkwinde** [comment]
Hi @Sim-Cyber ,
kein Problem bekommen wir schon hin 👍 Nächstes Ticket sollte vielleicht besser auf Englisch sein 😄 

Wir machen mal die forced Variante :)

1. Erstmal die App komplett schließen.
2. Hol dir die aktuelle App hier aus dem GIT und installiere sie: https://github.com/DeFiCh/app/releases/tag/v2.1.17
3. App nicht starten :) falls doch wieder schließen
4. Wenn du in Windows ein neues Explorer Fenster öffnest (über Computer, beliebiger Ordner , Windows-Tatee + E) hast du ja oben die Pfadangabe wo du bist. Nun kopierst du `C:\Users\%username%\AppData\Roaming\DeFi Blockchain` und packst es in die Pfadangabe und drückst enter. Damit wechselst du direkt für den aktuellen Nutzer in das Blockchain-Verzeichnis.
5. Dort legst du einen neuen Ordner an und nennst ihn zum Beispiel `_Archiv` und packst da alle Dateien aus dem DeFi Blockchain Ordner rein.
6. Starte die App
7. Jetzt sollte der Sync starten. Warte bis der durch ist und recover dein Wallet via Seed


Falls das immer mal wieder auftritt, hier kannst du auch ein Snapshot der Blockchain runterziehen und speichern. Damit geht das Syncen schneller: https://62.75.139.29/
Aber erst den oberen Weg probieren. Wen alles nix hilft einfach die Dateien aus dem Archiv zurück kopieren und du hast den alten Stand wieder.

Probleme hatte ich wie gesagt hatte ich seit 2.1.17 und deaktivierten Virenscanner nicht mehr.

Achso noch als Hinweis zu einem bekannten Problem....
Du solltest in der App oben rechts nicht auf Update klicken...auch wenn es angeboten wird und sehr verlockend ist. Sondern gehe aktuell immer manuell hier über den GIT downloaden für neue Versionen und installiere diese manuell. 
Es gibt ein bekannten Fehler bei dem Update Prozess wobei die App nicht sauber heruntergefahren wird und es ebenfalls zu den korrupten Blöcken kommt.

**Comment by Sim-Cyber** [comment]
Hallo Darkwinde,
nochmals vielen dank für deine Geduld und Zeit du hilfst mir damit enorm. Das mir dem englisch, ja da hast du wohl recht mein Fehler ;)
Nun ich bin bei Punkt 5.
Alles ist sehr gut erklärt und ich habe nun in dem Blockchain-Verzeichnis einen Ordner mit _Archiv erstellt. 
Nun weiß ich jedoch nicht genau welche Dateien aus dem DeFi Ordner ich da rein legen soll. Ich habe ein paar Varianten versucht, jedoch hat nichts geklappt. Kannst du das evtl noch etwas genauer erklären?

Hier ist ein Screen der aktuellen Lage, der _Archiv Ordner ist bisher leer.

![2021-02-13](https://user-images.githubusercontent.com/76777781/107857408-93abe880-6e2e-11eb-94a3-f067cbe56598.png)



Freundliche Grüße 
Simon

**Comment by Darkwinde** [comment]
Hi @Sim-Cyber ,
Einfach alles 😄 Sprich alle Ordner und Dateien ab ins Archiv...

**Comment by Sim-Cyber** [comment]
Hallo Darkwinde,
so ich hab es nun geschafft :D alles hat super funktioniert. 
Ich danke dir vielmals du hast mir wirklich sehr weitergeholfen. 
Wirklich vielen viel danke,

We are ready here, it can be closed.

**Comment by Darkwinde** [comment]
sehr gerne :)
