### ISSUE TITLE
Unable to start blockchain error on v2.1.15 and v2.1.17

### ISSUE THREAD

**Issue by elxlee** [DeFiCh/app#497]
Hi, I was using v.2.1.15 app few days ago. After updating the app to v.2.1.17, there was a data base re-index issue. I closed the app and restarted the app. When DeFi App v.2.1.17 was relaunched, it stopped at the splash screen with error message "Unable to start blockchain".

I decided to reinstall v.2.1.15 app. When I launch the app, the same error now applies to v.2.1.15 with "Unable to start blockchain". See screenshot. 

My system is a Windows 10 on a Windows book 2 laptop, and 50 GB of harddisk space available. 

I am not sure what to do next and would appreciate some guidance. App's log file attached. 

[app logs.zip](https://github.com/DeFiCh/app/files/5970938/app.logs.zip)
![App error message](https://user-images.githubusercontent.com/70930938/107754465-7b6b9900-6d5c-11eb-966d-b6b96546b902.jpg)

**Comment by Darkwinde** [comment]
Hi @elxlee,
from the logs I would assume that you have a blockchain init issue. Can you put everything in C:\Users\%username%\AppData\Roaming\DeFi Blockchain to an archive directory and check if start is working now for you?

If not you can check out https://62.75.139.29/ if the blockchain snapshots helps you.

**Comment by elxlee** [comment]
This solution works! 

put everything in C:\Users%username%\AppData\Roaming\DeFi Blockchain to an archive directory and restart the app. It works. Currently syncing, waiting to see if i am able to restore the wallets

**Comment by Darkwinde** [comment]
Happy to help you out of the stuck situation

**Comment by elxlee** [comment]
@Darkwinde  While this method works in allowing me to restart the app, after I recreated by wallet from mnemonics keywords, the app does not show the investment that I made from the wallet. When I click on liquidity pool, there no records that I can recall the funds from. How do I reconnect with the investments made from my wallet to the liquidity pool? 

![missing liquidity investment](https://user-images.githubusercontent.com/70930938/107866144-7287de00-6ea8-11eb-8a29-97cc1dad01f9.jpg)

**Comment by Darkwinde** [comment]
Hi @elxlee,
good question was not in that situation hmmmm, first I would try would be:

1. Closing app
2. Going to `C:\Users\%username%\AppData\Roaming\DeFi Blockchain` and save the directory `wallets` to a new Archive directory.
3. Put the wallets directory from the previous archive, e.g. `C:\Users\%username%\AppData\Roaming\DeFi Blockchain\_Archive\wallets` as a copy back to the blockchain directory: `C:\Users\%username%\AppData\Roaming\DeFi Blockchain`. Just only work with copies so that you do not loose anything from the original state.
4. Start App again and checking for the results

**Comment by izzycsy** [comment]
Hi @elxlee , regarding the issue [`Unable to start blockchain`](https://github.com/DeFiCh/app/issues/487), we can further discuss on the problem there. We would like to keep same issues in one thread. Thank you. 

Hi @Darkwinde , much appreciated for the help!
