### ISSUE TITLE
Wallet and Liquidity Mining Investments are Missing after Mnemonic keywords recovery

### ISSUE THREAD

**Issue by elxlee** [DeFiCh/app#500]
I had an issue with the app previously, had to reinstall and recover the wallets from mnemonic 24 keywords.
While the recovery seems to have worked, 1) the receiving wallet address is missing and 2) the liquidity pool investments are missing. 

Need advice on how to recover the deposit wallet and the liquidity investments linked to it. 

I am sticking with v.2.1.15 app working on a Win 10 laptop.  See attached pdf for screenshots

[postrecoverylog.zip](https://github.com/DeFiCh/app/files/5976880/postrecoverylog.zip)
[recovery issue.pdf](https://github.com/DeFiCh/app/files/5976881/recovery.issue.pdf)

**Comment by elxlee** [comment]
Unable to recover access to the wallet address - dYE8Fr3EyjF3ec1Y8SjtW8BkUyniXE8mvL
But I am able to see all transactions interacting with wallet address - dYE8Fr3EyjF3ec1Y8SjtW8BkUyniXE8mvL
This is so strange, I should have access to the wallet address after recovery.

See attached 
[Issues with wallet address - dYE8Fr3EyjF3ec1Y8SjtW8BkUyniXE8mvL.pdf](https://github.com/DeFiCh/app/files/5976926/Issues.with.wallet.address.-.dYE8Fr3EyjF3ec1Y8SjtW8BkUyniXE8mvL.pdf)

**Comment by Darkwinde** [comment]
Hi @elxlee,
sounds partially like #485. May worth to check conversation.

**Comment by scope-li** [comment]
Hi

I read about this problem in the telegram group, on reddit and also on github.
I can reproduce this on my Macbook and i play a little bit with this.

My seed (24 words) was generate in the defi-app 2.1.16.

When I restore the wallet on the MacBook with the 24 words, the balance for all wallet is 0 (GUI and CLI).
After the first try, I remove all under `/User/[Username]/Library/Application\ Support/[Defi|defi-app] ` and start from new.
Try again (after download the hole blockchain) with the 24 words and the same, no balance on all wallets, no address and no other information.
3th try, I close the wrong wallet from the 24 words and restore a second time with the wallet backup `*.dat` from the iMac and all is fine.

At the moment, I believe that not all seed's work correct or the app has a bug.

**Comment by izzycsy** [comment]
Hi @elxlee , thanks for your feedback, regarding the issue [`Restore wallet > balances not reflected`](https://github.com/DeFiCh/app/issues/485), we can further discuss on the problem there. We would like to keep same issues in one thread. I'll tag you there. Thank you. 

Hi @scope-li , I do not suggest removing any files, but should you decide please ensure you make a copy, we will not be responsible for your trial and error losses. Thank you for your feedback. We're improving the app as we go along. 

Hi @Darkwinde , appreciate the help!
