### ISSUE TITLE
Cant send ballance in my wallet to other wallets

### ISSUE THREAD

**Issue by xesly** [DeFiCh/app#502]
### Preflight Checklist

- [ x
[App logs.log](https://github.com/DeFiCh/app/files/5979836/App.logs.log)
[Binary logs.log](https://github.com/DeFiCh/app/files/5979837/Binary.logs.log)

] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x ] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  - 
- **Previous DeFi App Version:**
  - 
- **Operatin
[App logs.log](https://github.com/DeFiCh/app/files/5979842/App.logs.log)
[Binary logs.log](https://github.com/DeFiCh/app/files/5979844/Binary.logs.log)
![issue](https://user-images.githubusercontent.com/79075413/107912920-10b98980-6f25-11eb-8fc2-a46086128532.png)

g System (OS):**
  -

**Comment by izzycsy** [comment]
Hi @xesly , it appears that you are attempting to send BTC to a Bitcoin network address. BTC on DeFiChain is a DeFi Standard Token (DST) — in other words D-ETH,  that is only transmittable to other DeFiChain addresses (usually starting with `8` or `d`). Try sending it through sites such as <cakedefi.com>, then to your own preferred exchange.

**Comment by izzycsy** [comment]
Hi @xesly , attaching a workaround for you should you decide to use CakeDeFi. You can retrieve the DeFiChain address via <cakedefi.com>, try sending a small amount first to test.

1. Click on Balances in <cakedefi.com>
2. In the ETH row, click on Deposit button
3. You'll see the Transfer Network options `ETH` / `DeFiChain`
4. Under the QR Code states your DeFiChain address, copy it
5. Go to DeFi app > ETH wallet > Send
6. Paste your DeFiChain address into `To address` field

<img width="362" alt="Click DeFiChain   ETH" src="https://user-images.githubusercontent.com/65014479/107949453-423b5f00-6fd0-11eb-91c0-46c4ba84b0c8.png">

 You may turn to Cake’s telegram for Cake-related issues: 
[CakeDeFi Telegram (EN)](https://t.me/CakeDeFi_EN) 
[CakeDeFi Telegram (DE)](https://t.me/CakeDeFi_DE)
