### ISSUE TITLE
DeFi App stops working because McAfee is deleting defid.exe and defi-app.exe files

### ISSUE THREAD

**Issue by contraelviento** [DeFiCh/app#505]
Hello,

for several days I experience following issue. 
I install DeFi App, let it syncronise, put my mnemonic words and is working fine for several hours. 
Then McAfee Antivirus is doing Real-time scan and is deleting/putting in a quaratine two .exe files: defid.exe and defi-app.exe.

It says:
**Virus or threat found**
Status: Quarantined

Process: C:/Users/username/AppData/Local/Programs/defi-app/resources/binary/win/defid.exe
Process: C:/Users/username/AppData/Local/Programs/defi-app/defi-app.exe

Current DeFi App Version: 2.1.17
OS: Windows 10 Home
McAfee Total Protection, Version 16.0, Release Name 16.0 R30

Is it a known/common issue? Is it related to DeFi App or do I have to allow these 2 files to be treated as safe by the antivirus?

I don't want to install DeFi App every single day.

Many thanks.

**Comment by thedoublejay** [comment]
@contraelviento I think you can mark these files as safe. `defid.exe` is the binary to connect to the blockchain. `defi-app.exe` is the app itself. Please make sure that you're downloading from our official releases https://github.com/DeFiCh/app/releases

**Comment by Darkwinde** [comment]
You should also put the Blockchain directory to the exception list as well (`C:\Users\%username%\AppData\Roaming\DeFi Blockchain`), because my Virus Scanner (GDATA) was also mess up day by day and leading to corrupted blockchain. After adding to exceptions, nos issues anymore :)
