### ISSUE TITLE
PC unlock / woken > Node is disconnected > app starts from 0%

### ISSUE THREAD

**Issue by LuisAsano** [DeFiCh/app#508]
Hi, I was previously facing this error when leaving DeFi App open in the background when my computer goes to sleep automatically when idle. After coming back it will present me with the corrupted block database error message.

Of course the solution is to Resync the app again but it takes so long(Up to a few hours sometimes) and is annoying because it happened again right after I had Synced the app but let my computer go to sleep again.

Currently my workaround is to either close DeFi App before leaving my computer idle or to change the settings on my computer so it never goes to sleep.

DeFi App Version: 2.1.17
OS: Windows 10 Home

My settings on DeFi app are Default and have not touched them since initial installation.
![Defi](https://user-images.githubusercontent.com/79193414/108220926-35ef0780-7172-11eb-91bc-d106e1568dc6.JPG)

**Comment by izzycsy** [comment]
Hi @LuisAsano , thanks for your feedback. The app creates new block every 37 seconds, and it stacks up if your app is not running. If your PC goes to sleep, the app will try to sync and hence `node is disconnected`. You don't have to leave it running though, rewards will still appear when you sync to 100% the next time you launch the app. 

When you launch the app, does it sync at where you left off or 0%? In the mean time, maybe increase your PC display settings to a longer timeout before it goes to sleep.

**Comment by LuisAsano** [comment]
Hi @izzycsy thanks for helping me understand. I guess its more of a QOL issue. 

When I launch the app under a normal circumstance e.g. After turning on my computer. It will sync from where I left off previously(normally done within a few minutes.)

Only in this case when my computer goes to sleep when the app is still running. Then the corrupted block error msg occurs and the sync starts from 0%.

**Comment by izzycsy** [comment]
Hi @LuisAsano , the team will investigate this, for now, I advice that you do not let your PC sleep when the app is running, so you can avoid syncing from 0%. Can you send me your app logs please? 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/108344306-f11dac00-7217-11eb-852d-123780dc1a0a.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/108344319-f4b13300-7217-11eb-8413-f618d7bb64fa.png">

**Comment by LuisAsano** [comment]
Hi @izzycsy Attached is log from the day the issue last happened for me.
[150221.zip](https://github.com/DeFiCh/app/files/6002983/150221.zip)

**Comment by izzycsy** [comment]
Hi @LuisAsano , just checking with you, did you combine all 3 files into 1 `.txt` file? Because the app logs are `.log` / `.conf` format respectively.

**Comment by LuisAsano** [comment]
@izzycsy ah I only provided 1 app log file not the other 2 let me attach them later on when I have access to my pc.

**Comment by LuisAsano** [comment]
@izzycsy Ok this should be the 1s you requested for. As attached logs on the date error last occurred.
[150221.zip](https://github.com/DeFiCh/app/files/6009785/150221.zip)

**Comment by Darkwinde** [comment]
Hi @LuisAsano,
to reduce your sync time, you could perform a backup (close app beforehand) of the blockchain directory and in case of corruption you just can remove the faulty one and copy the backup one in...or you can use a snapshot of the blockchain itself: https://62.75.139.29/

**Comment by izzycsy** [comment]
Hi @LuisAsano , update v2.3.1 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, please leave a comment with your new information (include screenshots) and app logs. Thank you. 

I would suggest that if the app is in the midst of syncing, do not let your computer go to sleep. If you're not using the app you can close it and let your computer go to sleep.
