### ISSUE TITLE
Import backup > Node is disconnected

### ISSUE THREAD

**Issue by SpecialAgentX** [DeFiCh/app#515]
Exported backup OS: MAC OS 11.2.1
Imported backup OS: Windows 10 PRO 20H2, 5GB RAM
defi-app: 2.1.17

What I did:
1. Exported with 2.1.17 on Mac, stored wallet.dat
2. Fresh install of defi-app 2.1.17 of windows computer
3. waited HOURS till 100% blockchain is downloaded
5. imported wallet.dat... and "Connection to Node is lost" (in german) error occurred.
<img width="973" alt="Bildschirmfoto 2021-02-18 um 14 02 45" src="https://user-images.githubusercontent.com/24278992/108366365-932d9c00-71f8-11eb-8fdc-5a1eaeff91a6.png">

4. Then I need to quit the defi-app (waited till it is closed)
5. After open it again, Im getting the message "Unable to start blockchain)
<img width="381" alt="Bildschirmfoto 2021-02-18 um 14 14 38" src="https://user-images.githubusercontent.com/24278992/108366399-9de83100-71f8-11eb-85c5-7060052b7239.png">

6. Quitted defi-app, checked that I have 3.3 GB of RAM free
7. Can not start app anymore. It is broken.

[defi-app-logs.zip](https://github.com/DeFiCh/app/files/6003332/defi-app-logs.zip)

**Comment by izzycsy** [comment]
Hi @SpecialAgentX , thanks for the feedback, please give us time to investigate this issue.

**Comment by Darkwinde** [comment]
Hi @SpecialAgentX ,
from the logs I see network errors and loading issues of the wallet directory.

Based on the config it is placed on a network share, right? Can you change you config back to a local directory and try again?
[main]
wallet=defi-app2117.dat
walletdir=\\NAS-Zuhause\Dokumente\defi-app


```
[2021-02-18 14:36:42.943] [IPC-RENDERER-error] [startBinary] "Error:"
[2021-02-18 14:36:43.095] [IPC-RENDERER-info] [Blockchain Status] "Error:"
[2021-02-18 14:36:43.173] [IPC-RENDERER-error] [blockChainNotStarted - Not Running] "Error:"
[2021-02-18 14:36:43.227] [IPC-RENDERER-info] DefiProcessManager close with code 1
[2021-02-18 14:36:43.256] [IPC-RENDERER-info] Error occurred while running binary with code: 1
[2021-02-18 14:36:43.337] [IPC-RENDERER-error] [startBinary] "Specified -walletdir \"\\\\NAS-Zuhause\\Dokumente\\defi-app\" does not exist"
[2021-02-18 14:36:43.395] [IPC-RENDERER-info] [Blockchain Status] "Specified -walletdir \"\\\\NAS-Zuhause\\Dokumente\\defi-app\" does not exist"
[2021-02-18 14:36:43.460] [IPC-RENDERER-error] [blockChainNotStarted - Not Running] "Specified -walletdir \"\\\\NAS-Zuhause\\Dokumente\\defi-app\" does not exist"
[2021-02-18 14:36:43.551] [IPC-RENDERER-error] [startBinary] {"success":false}
[2021-02-18 14:36:43.613] [IPC-RENDERER-info] [Blockchain Status] {"success":false}
[2021-02-18 14:36:43.665] [IPC-RENDERER-error] [blockChainNotStarted - Not Running] ""
[2021-02-18 14:36:46.909] [IPC-RENDERER-error] [isBlockchainStarted] "Network Error"
[2021-02-18 14:36:47.140] [IPC-RENDERER-error] [isBlockchainStarted] "Network Error"
[2021-02-18 14:36:48.886] [IPC-RENDERER-error] [isBlockchainStarted] "Network Error"
[2021-02-18 14:36:50.859] [IPC-RENDERER-error] [isBlockchainStarted] "Network Error"
[2021-02-18 14:
```

**Comment by SpecialAgentX** [comment]
Hi Darkwinde,

**thanks for your immediate support.** I really appreciate this.

Ok, I've copied the backup wallet file "defi-app2117.dat" from my NAS to local directory to "C:\Users\%username%\.defi\wallet" and changed variable "walletdir" in "defi.conf" to this. Now the defi-app started normally and I can see my wallets. Sync is also working. No more "Node is disconnected" message occured. I did not added some other Node IPs.

Im wondering about this:

1. I used my NAS to have a central location to put und load my backup file. After I opened it on my windows machine, Im wondering why defi-app is dependend on this file. In my understanding it should only import information and use its own local stuff. **Here Im seeing a bug.**
2. The backup file is not complete, I do not have all my transaction for example in my LTC-DFI wallet. It only shows "No transaction found", whereas the original defi-app shows my transactions. I have also tried to restore wallets through my seed, but also there the transactions are lost. So, this I see als a **major bug**, because some one, who lost its original wallet will loose his tx history and will get problems, for example with financial institutes. I will raise a seperate bug for this, later.

But for this: Thanks for your help again.

**Comment by Darkwinde** [comment]
Hi @SpecialAgentX,
you are welcome. I am just a user like you, but sometimes go through reported bugs and try to support the project :)

Based on your description, it comes into my mind, did you maybe encrypted your wallet.dat?

**Comment by SpecialAgentX** [comment]
Hi Darkwinde,

thx. Cool, you helped a lot :-)

Well, I don't know actually... I used just the export function from 2.1.17 and in the file resulting file there are binary data. I don't think it is encrypted, because I did not provide a password or a private key.

Thx

**Comment by Darkwinde** [comment]
Hi @SpecialAgentX,
ok in case of setting a password to your wallet, this would lead to a new random seed to be created. Was thinking about, that this could have impact. But as you stated you have not.

I played around a bit with the blockchain directory and always the transactions were fine.

To import the wallet, have you used the App build in function or did you copy over an backupped one manually into `C:\Users\%username%\AppData\Roaming\DeFi Blockchain\wallets`?

**Comment by SpecialAgentX** [comment]
Used App build in function, nothing special. I waited until 100% sync was complete.

**Comment by Darkwinde** [comment]
Ok, maybe this could be the dif...I always replaced it manually:
> Started App
> Waited until peers connected and block sync started
> Close App
> Replace created wallet.dat in `C:\Users\%username%\AppData\Roaming\DeFi Blockchain\wallet` with my backupped one
> Started App and let sync...

Also Snapshot worked always fine for me: https://62.75.139.29/

**Comment by izzycsy** [comment]
Hi @SpecialAgentX , update [v2.3.0](https://github.com/DeFiCh/app/releases/tag/v2.3.0) is out, this is a mandatory update due to node Dakota Upgrade 1.5.0.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
