### ISSUE TITLE
App not generating backup file

### ISSUE THREAD

**Issue by Folderguion** [DeFiCh/app#517]
Hello,

I'm running the DeFi wallet on Linux, but the founds doesn't show up. Seems lost after your fork update. 
Please could you advise?

**Comment by Folderguion** [comment]
the above is solved. But the App is not generating a backuf file when I want to backup. Any ideas?

**Comment by izzycsy** [comment]
Hi @Folderguion , thanks for your feedback, may I know which version are you on? Do you have a screenshot on how you try to save backup?

**Comment by Folderguion** [comment]
Hello! Tnx for your help. 
I'm on the version: 2.1.17 . 
I just click on Wallet menu > Backup wallet > the folders explorer open up but there's no file to save. The only option is to press on Cancel on the explorer window. 
The same happen when I go to Logs > any menu the same, no files generated. 

I've gone through the post you linked but I don't understand just the very first step :" unlock the wallet with 'walletpassphrase PASSPHRASE 60' " > How to do this? 

Thanks

**Comment by Folderguion** [comment]
Ok, as per your indication I've posted on this thread > https://github.com/DeFiCh/app/issues/461
