### ISSUE TITLE
[Proposal / Feature Request] UI/UX improvement ideas

### ISSUE THREAD

**Issue by BenThrottle85** [DeFiCh/app#519]
### Preflight Checklist

- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

Hello everyone,

I had same thoughts on how to improve the UI/UX a little bit.
Maybe you like some of them.

### Screenshot(s) / screen recording(s) of issue

![IMG_0055](https://user-images.githubusercontent.com/68747114/108488686-f70b9f80-72a0-11eb-933a-9bcf2f155be8.jpeg)
![IMG_0056](https://user-images.githubusercontent.com/68747114/108488695-f96df980-72a0-11eb-9ba0-b62af2e5780f.jpeg)
![IMG_0057](https://user-images.githubusercontent.com/68747114/108488697-f96df980-72a0-11eb-80f1-9cc12d18fca6.jpeg)
![IMG_0058](https://user-images.githubusercontent.com/68747114/108488698-fa069000-72a0-11eb-9bee-fbaba3729655.jpeg)
![IMG_0060](https://user-images.githubusercontent.com/68747114/108488702-fb37bd00-72a0-11eb-9703-7d873bee1b05.jpeg)

**Comment by izzycsy** [comment]
Hi @BenThrottle85 , thanks for your feedback, will forward this to the team!

**Comment by izzycsy** [comment]
Hi @BenThrottle85 , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

The above feature / issue is not included in this update yet, this comment is to notify you about the update.

**Comment by izzycsy** [comment]
Hi @BenThrottle85 , you can post your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner some support from the community, and the team can decide whether to implement the feature in the future. Thank you!
