### ISSUE TITLE
Win8: Unable to start blockchain

### ISSUE THREAD

**Issue by vsduq** [DeFiCh/app#521]
Hi there,

So i have the v2.1.17 version of the app in a pc with Windows 8.1 Pro and for a week everything worked smothly, today when i tried to start the app i got this error, "Unable to start blockchain".

I already checked the other closed issues here with the same name but could not find a solution to my problem.

What should i do? unistall and reinstall the app? other?

Other questions:

- in case that i need to reinstall, all i need is the wallet.dat file, and the 24 words, or i need some more files? note too that my wallet is encrypted with a passphrase this makes the process of recovery any different?

- I have a second computer can i install the app in it and with my wallet.dat file try get access again temporaly or this is a bad idea?

when u can give me some help thx.

[applogs.log](https://github.com/DeFiCh/app/files/6017984/applogs.log)
[binarylogs.log](https://github.com/DeFiCh/app/files/6017985/binarylogs.log)

![defi app error](https://user-images.githubusercontent.com/79408021/108630019-af307800-745a-11eb-9700-4e0592e1e275.png)

**Comment by izzycsy** [comment]
Hi @vsduq , thanks for your feedback, the team is currently investigating this issue. I would suggest that you keep a copy of your `wallet.dat` files. I suggest that you don't delete files that you're unfamiliar with. Moving forward in the upcoming release, we'll be focusing on the utilisation of `wallet.dat` and securing it. So to answer your question, the `wallet.dat` files are important.

I do not recommend installing older version for your safety and security, our team is constantly working on improving the app and solving its issues. We regularly do releases, so if you are not in a big hurry I would suggest staying on the latest version and wait for a fix. In the mean time, you can find the files here: 

Windows — C:  
\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat

Mac — Go to Folder:  
/Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat

<img width="626" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/108752887-ffa0f600-757e-11eb-9357-7b7b71277bb5.png">

**Comment by vsduq** [comment]
Thx for the awser izzy, i guess i will wait a bit then.

About that second question can u elaborate a bit? If there is any problem or not to install in a different computer the app and use my wallet.dat files to try have access until this issue is fixed.

thx for your time.

**Comment by izzycsy** [comment]
Hi @vsduq , yes you can try to install the app on another PC and `restore wallet` via `wallet.dat`. I would not suggest restore via mnemonic seed as you balances may not appear and you still have to import the `wallet.dat`. 

The team realised after awhile with the mnemonic seed it causes some errors. Hence, we’ll be implementing a new encryption enabler. The files that you should keep safe would be your `wallet.dat` — which the UI in the app will guide you to on how to save it as well. Personally, I save my addresses in my Notes as well. We're working on the release and it's not ready yet however. Hope the above mentioned workaround would suffice for now.

**Comment by izzycsy** [comment]
It also seems like your PC does not meet the minimum requirement though <https://defichain.com/learn/defi-app-how-to/>.

**Comment by thbestforyourbizdeployment** [comment]
same issue on the Mac. same version and it happens on 2.3 on the Mac.
Really frustrating! 👎.  Never had a build that works constantly. 
In addition, I don't find any documentation that the wallets are more important than the seed phrase!

**Comment by izzycsy** [comment]
Hi @thbestforyourbizdeployment , I understand your frustration, I would suggest that you wait for the next build then replace the app when it's ready for download. I'll update this this thread when the team is ready to deploy the next update. 

<img width="539" alt="Replace app1" src="https://user-images.githubusercontent.com/65014479/109382508-d0daa500-791b-11eb-99e7-2b605f3f82d2.png">
<img width="535" alt="Replace app2" src="https://user-images.githubusercontent.com/65014479/109382509-d2a46880-791b-11eb-9e6c-9ff48ef4fedf.png">

**Comment by izzycsy** [comment]
Hi @vsduq , it seems like your PC does not meet the [minimum requirement](https://defichain.com/learn/defi-app-how-to/) for DeFi app.

**Comment by felixwithonex** [comment]
[bin log.log](https://github.com/DeFiCh/app/files/6063868/bin.log.log)
[app log.log](https://github.com/DeFiCh/app/files/6063875/app.log.log)
the app config. file is not supported

**Comment by izzycsy** [comment]
Hi @felixwithonex , following up from your [reddit post](https://www.reddit.com/r/defiblockchain/comments/lvfd2y/recover_wallet_just_with_seed_phrase/), thanks for sending your logs. Please give us time to investigate the issue.

**Comment by izzycsy** [comment]
Hi @vsduq @thbestforyourbizdeployment @felixwithonex , update [v2.3.1](https://github.com/DeFiCh/app/releases/tag/v2.3.1) is out. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please leave a comment on with new information (include screenshots) and app logs. Thank you.

**Comment by izzycsy** [comment]
Hi @thbestforyourbizdeployment @vsduq @felixwithonex , we've halting v2.3.1 at the moment due to some issues. I'll update you again when the team fixes it and is ready for release.

**Comment by izzycsy** [comment]
Hi @thbestforyourbizdeployment @vsduq @felixwithonex , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out.  Please read through the release notes before updating. 

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
