### ISSUE TITLE
Missing tx history

### ISSUE THREAD

**Issue by SpecialAgentX** [DeFiCh/app#529]
_defi-app: 2.1.17_

As I wrote in bug #515, the backup export in version 2.1.17 (MacOS client) does not contain transaction history (I restored it on an Windows 10 PC). Furthermore: Restore (on Windows PC) with a seed does not contain tx history as well.

So, in my eyes there is **NO possibility to backup or restore TX history**. This is critical, because if one lost his original defi-app installation, there is NO WAY to provide exact tx data for financial institures e.g.

So, this needs to be fixed as high priority bug (in my eyes).

**Absolutely a risk for the whole defichain project.**

**Comment by izzycsy** [comment]
Hi @SpecialAgentX , thanks for the feedback, please give us time to investigate this issue. Have you tried to restore wallet using your `wallet.dat` file? 

Windows — C: 
 \Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat

Mac — Go to Folder: 
 /Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat
 
 
<img width="626" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/108752600-a1741300-757e-11eb-8f50-4909f7fa197d.png">

**Comment by SpecialAgentX** [comment]
Hi izzycsy,

so, you mean just copy the wallet.dat form mac to windows without the built in backup functionality? I'll try this in a couple of days.

Thx.

**Comment by izzycsy** [comment]
Hi @SpecialAgentX , you didn't state which kind of operating system you're using, hence I'm providing the respective routes for you to find your wallet.dat files. However, you should also be able to restore wallet using wallet.dat **if** in the event you're using 2 PCs.

**Comment by salomonkarsten** [comment]
@izzycsy In Version 2.3.0 the Transactions are not visible. Therefore all data missing for the .csv export. .csv only shows a header. I wonder why it is not possiblt what another project like https://github.com/DeFi-PortfolioManagement/defi-portfolio/blob/master/README.md

can do. Would it not great to fuse both projects?

**Comment by izzycsy** [comment]
Hi @salomonkarsten , may I have your app logs and a screenshot of the issue you're facing please? 

Thanks for sharing the project, we appreciate users creating their own community project. The original creators could perhaps share it on [DeFiChain Telegram (EN)](https://t.me/defiblockchain) to stir some interest in the mean time 😉

**Comment by salomonkarsten** [comment]
@izzycsy 
![image](https://user-images.githubusercontent.com/77124114/109976371-fd1b6a80-7cfb-11eb-8c11-93576e1e16c5.png)
[AppBinaryLogs.log](https://github.com/DeFiCh/app/files/6084230/AppBinaryLogs.log)
[Applog.txt.log](https://github.com/DeFiCh/app/files/6084232/Applog.txt.log)

**Comment by salomonkarsten** [comment]
@izzycsy no history is displayed correctly none of the latest transactions are displayed.
But i can see them in the history commands.

**Comment by izzycsy** [comment]
Hi @salomonkarsten , can you send your logs please? The team is investigating the issue, thank you.

**Comment by salomonkarsten** [comment]
@izzycsy habe a look, they are send already

**Comment by izzycsy** [comment]
Hi @salomonkarsten , does the issue persist in [v2.3.1](https://github.com/DeFiCh/app/releases/tag/v2.3.1)? When you've updated and the issue persists, please send the latest app log, bin log & app config, thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/110759190-4cc3de00-8288-11eb-9648-f14b72158c07.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/110759203-4fbece80-8288-11eb-8ff3-576cb16df76e.png">

**Comment by salomonkarsten** [comment]
[AppBinaryLogs.log](https://github.com/DeFiCh/app/files/6125508/AppBinaryLogs.log)
[Applog.txt.log](https://github.com/DeFiCh/app/files/6125509/Applog.txt.log)
@izzycsy problem remains, i see only transactions older than 13.1.2021 also i do some daily.

**Comment by SpecialAgentX** [comment]
Hey,

yes problem persists in 2.3.1:

I have backuped my wallet on my Mac OS client (v2.3.1) (this is the original with tx history). Installed 2.3.1 on an Windows 10 PC, reindexed everything and then imported the wallet.dat from MacOS by first copying it local to Windows PC and then used the UI restore button.

Im seeing on Windows PC no transactions for every wallet except of my DFI wallet. All or some (did not check for completeness) tx are there for DFI wallet. Nothing for LTC, BTC, USDT. The amount of all wallets are correct displayed.

I attached app logs from Windows PC.

Regards

[applogs.zip](https://github.com/DeFiCh/app/files/6127946/applogs.zip)

**Comment by SpecialAgentX** [comment]
> Hi @SpecialAgentX , you didn't state which kind of operating system you're using, 

I've updated my bug description. Sorry.

**Comment by izzycsy** [comment]
Hi @SpecialAgentX , okay so you've manage to restore wallet, just that you have missing tx history. Can you try Reindex Option via Settings? After that, if issue persists, please send your app log, binary log & app config again. 

<img width="778" alt="Reindex   saving + delete peers and blocks" src="https://user-images.githubusercontent.com/65014479/110913541-45680780-8350-11eb-8076-86684c7273a8.png">

**Comment by SpecialAgentX** [comment]
@izzycsy : This did it! I do have some tx data within other wallets as DFI. Thank you!

But it seems, that some tx are missing:

In my ETH wallet, when Im scrolling through tx pages, Im seeing that there must be 48 tx but on page 3 defi-app tells me that there are no tx. See screenshot 1 and 2

![ETH-TxPages1](https://user-images.githubusercontent.com/24278992/110959629-2ec0b100-834e-11eb-8cf2-ca17322d0bdf.png)

Pressing the arrow button shows this:

![ETH-TxPages2](https://user-images.githubusercontent.com/24278992/110959705-44ce7180-834e-11eb-878e-8db7a87bb8a5.png)

**Comment by izzycsy** [comment]
Hi @SpecialAgentX , the team has halted v2.3.1 at the moment due to some issues, your issue is not related to it, but I suggest you wait for v2.3.2 and try Reindex again. I'll update you again when the team fixes it and is ready for release.

**Comment by luckythai** [comment]
Das ist ein aehnliches problem wie meines.

My problem is still there. Only the last 3 rewards are displayed in the app under transactions. They are available when the data is exported. both in the app 2.1.17 / 2.3.0 / 2.3.1 / Wallet - 2.3.2

https://github.com/DeFiCh/app/issues/257

**Comment by izzycsy** [comment]
Hi @luckythai , v2.3.2 is not officially release yet, please refrain from downloading it until official announcement on [DeFiChain Announcements (EN)](https://t.me/defichain_announcements). If you've already installed, please wait till we officially release it and see if your issue still persists. Thank you.

**Comment by izzycsy** [comment]
Hi @SpecialAgentX @luckythai , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out. .  Please read through the release notes before updating.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.

**Comment by salomonkarsten** [comment]
Update and reindex didn't solve the problem.  I wonder why the portfoliomanager app can Retriever the data but the app cannot

**Comment by izzycsy** [comment]
Hi @salomonkarsten , thanks for your feedback, may I know which tx history are you missing? Can you send your app logs please? Thank you.

**Comment by luckythai** [comment]
Hi izzycsy,
with dfi only the last 3 rewards in the history are shown. On the inventory and when exporting the files everything is ok.
Screenshots are in issues # 257, are the same, only the date changes. Everything is ok, only the dfi reward is not shown except for the last 3. https://github.com/DeFiCh/app/issues/257

[Logs.zip](https://github.com/DeFiCh/app/files/6219933/Logs.zip)

**Comment by izzycsy** [comment]
Hi @luckythai , thanks for your feedback. When you export the CSV files your tx history is displayed, only in the app UI it is not? Logs well received.

**Comment by luckythai** [comment]
Hi izzycsy,

yes exactly, only with dfi and only the reward is a problem, but only the display of the transactions. I only ever see the latest 3.
with refresch the latest rewards again (if one is paid out in the meantime). The credit is displayed correctly.
It's not a problem for me now, because the export works.

refresh utxo does not bring any improvement

<img width="436" alt="Screenshot 2021-03-29-1" src="https://user-images.githubusercontent.com/77095933/112819604-f4c20f80-90ae-11eb-9547-29ba019d0fb5.png">
<img width="425" alt="Screenshot 2021-03-29-2" src="https://user-images.githubusercontent.com/77095933/112819611-f5f33c80-90ae-11eb-967a-bc53986124d4.png">
<img width="422" alt="Screenshot 2021-03-29-3" src="https://user-images.githubusercontent.com/77095933/112819613-f68bd300-90ae-11eb-89bc-0ac24206dab5.png">

**Comment by luckythai** [comment]
Here is the screenshot after refresh utxo

Everything is displayed correctly, every transaction, but the rewards are only ever limited to the last 3 that I have received.
But I should normally see "hundreds".


<img width="434" alt="Screenshot 2021-03-29 171513" src="https://user-images.githubusercontent.com/77095933/112823245-3e145e00-90b3-11eb-9067-dce5fb9b55f3.png">

**Comment by izzycsy** [comment]
Hi @luckythai , thanks for the screenshots. Please give us time to investigate this. Thank you.

**Comment by dnamurphy** [comment]
@izzycsy - this issue is also found in 2.3.3 (MacOS). 

I have a Windows 10 machine running 2.3.2 and MacOS 2.3.3. The latter was freshly (re)-installed (I wiped 2.3.2), and synced yesterday, accelerated with the snapshot. Swap and LM records are missing as before under Mac (Windows is OK). 

I also note that when I add liquidity in Windows, the transaction **does** appear in the Mac client once the block height increases. 

Hope this helps.

**Comment by izzycsy** [comment]
Hi @dnamurphy , thanks for your feedback, please give us time to investigate this issue.

**Comment by luckythai** [comment]
@izzycsy 
now with the 2.3.3 the rewards work again in the view, but now all the transactions in the wallet are gone.
have not yet assigned a password and every backup of my wallet shows different transaction sizes when importing. But you only see a maximum of 30 transactions. With some wallet backups even only 10. The rewards are now displayed normally again.

**Comment by izzycsy** [comment]
Hi @luckythai , I'm not sure how you manage your wallet.dat backups, but personally I label them before I save the backup. I understand that it's a bit late to do that now, but in the future maybe you can practice this so you don't lose track of your own file versions. Maybe you can try using the latest wallet.dat and just continue using it from there. During every upgrade, the app is trying to find past transactions amongst other transactions in the each block. Are your addresses and balances are reflected correctly?

**Comment by luckythai** [comment]
Hi @izzycsy
yes my addresses and balances is displayed correctly everywhere.
Except for restore with the 24 word seed. There is no address there, only the balances is right here.
It is not a problem of the organization of my wallet (see picture) and also not a user error. By fixing the previous problem (only 3 rewards are displayed) a new error has arisen.

With every backup that I import, the correct balances and addresses appear. The reward appears correctly with every import wallet. The only difference is the amount of transactions in the hystery. Only the very first transaction is shown everywhere. Any subsequent transactions will no longer appear.
The transactions do not appear in the CSV export either.

For a wallet, the amount of transactions is 3
With the other 60, with the other 220 .... all different values.
The database is the same with every import.
But the error is also when using 2 or 3 computers and different wallets.
---
An import with the old txt backup always breaks off with the error of a missing dump file. Only the import with the dat file and the 24 words seed was possible for me. My wallet doesn't have a password yet.

<img width="854" alt="wallets txt" src="https://user-images.githubusercontent.com/77095933/114746477-03304c80-9d7a-11eb-8817-6fd9f7b19f80.png">

**Comment by luckythai** [comment]
There are 2 different errors in the display in the wallet 2.3.3 and the export of the cvs. And 1 error with the restore of the txt file.

#1. Restore temporally different backup dat files from the same wallet. 
Error -> Different amount of transactions with and without reward. The CSV export adapts to the displayed amount and not to the actual transactions.
Backups from Wallet 2.3.0 show the same amount of transactions, but a new restore with the 24 words seed has a different amount of transactions.

# 2. A restore of a wallet dat and a restore of 24 words seed. Every restore.
Errors -> e.g. 210 transactions displayed, but only the first 10 can be seen. when scrolling to the 2nd page there are no transactions. The transaction overview with reward works without any errors. But not all that were actually received with the wallet. The new ones are all there.

# 3. a restore of the txt file is not possible with the interface.
He breaks with the error> missing dup file

![Wallets](https://user-images.githubusercontent.com/77095933/114761689-08e25e00-9d8b-11eb-8748-7a9839fcae56.png)

**Comment by luckythai** [comment]
#1. Restore zeitlich unterschiedliche Backup dat Dateien vom selben Wallet. Fehler -> 

Bevore 2.3.0

![Screenshot 2021-04-14 234718](https://user-images.githubusercontent.com/77095933/114762929-73e06480-9d8c-11eb-8163-e604617dc008.png)

From wallet 2.3.0 and more

![Screenshot 2021-04-15 000236](https://user-images.githubusercontent.com/77095933/114763142-ac803e00-9d8c-11eb-9330-ba6f3c2277f1.png)

![Screenshot 2021-04-15 015405](https://user-images.githubusercontent.com/77095933/114763963-98890c00-9d8d-11eb-9bbc-e2815aa18168.png)


From 24 words seed

<img width="865" alt="Screenshot 2021-04-15 000730" src="https://user-images.githubusercontent.com/77095933/114763321-dcc7dc80-9d8c-11eb-9a46-41142fae01dc.png">

<img width="510" alt="Screenshot 2021-04-15 010222" src="https://user-images.githubusercontent.com/77095933/114763448-fff28c00-9d8c-11eb-9168-b53f09b05d5c.png">

**Comment by luckythai** [comment]
# 2. A restore of a wallet dat and a restore of 24 words seed. every restore.
Errors ->

![InkedScreenshot 0_LI](https://user-images.githubusercontent.com/77095933/114765076-ea7e6180-9d8e-11eb-942d-f39db3830d14.jpg)

<img width="529" alt="Screenshot 2021-04-15 010009" src="https://user-images.githubusercontent.com/77095933/114765157-05e96c80-9d8f-11eb-994e-38e026a69950.png">

**Comment by luckythai** [comment]
Support of the database for the wallets

<img width="851" alt="Fullnode" src="https://user-images.githubusercontent.com/77095933/114767127-772a1f00-9d91-11eb-88c1-9e22b9a49f88.PNG">

**Comment by izzycsy** [comment]
Hi @luckythai , thanks for the elaboration. Let's away the `Restore via mnemonic seed` & `any.txt` file. What should matter are the `wallet.dat` and your passphrase from v2.3.0. The team has disable mnemonic seed generation for security purposes. We'll look into the missing tx history issue for `wallet.dat`. Thank you for your understanding.

**Comment by luckythai** [comment]
Hi @izzycsy 
the Restore via mnemonic seed & any.txt file, was just an attempt to further isolate the error.
so the dat file is not the cause, but the app. if the dat file were the cause, the import with the 24word mnemonic seed should have had the correct transaction display, but it made the same display errors of the transactions, although the dat file created by the app.
Somewhere the database is no longer queried, but only the content of the dat file and/or the ./config/defi-wallet folder, which is just not complete. Otherwise the export would be complete. So the dat file has too little information or it is only queried from the cache and not from the database. When the wallet is restored, not all information from the database is restored, but rather the current status of the computer and fragments of database information.
However, no inventory or value is lost from the wallet; it only affects the display of transactions and the csv export.
But I am firmly convinced you and the others of the team will find a solution with the information.

**Comment by salomonkarsten** [comment]
On top even New transactions are not listed in the tx history. It seems not all ismine addresses are taken into account for tax history. Did you ever look at the dfip. You should include this Grat apps as these can evaluate in a correct manner the history. I wonder why the wallet cannot do the same and just use the history command!!!

**Comment by luckythai** [comment]
Hi @izzycsy
Ok, proceed differently and let's focus on the dat file.
#Starting position
1 computer with ubuntu 18.04 and cli 1.6.3 - full node.
Database of node 1.6.3. Was created without a snapshot and after Defichain.
2 computers with windows 10 and 2x Ubuntu 18.04 as WSL for the Defichain app 2.3.3 Appimage.
Fullnode's cloned database. 41.6 GB (I call the database node.1.6.3)
1 computer (I call it original now) with windows 10 and ubuntu 18.04 WSL Defichain App 2.3.3 Appimage. Database created with reindex and was 80 GB in size. (I call the database node.1.6.2)
#
Only 1 dat file was used. No mixing of backups and with the same cloned "~ / .config / defi-Wallet" folder. from the original PC with the 80 GB database - node 1.6.2 reindex. The defi.conf is the same and also the first 3 entries on every computer.
This datfile showed 5 transactions. No receiving addresses.

2 computers with the cloned database - node 1.6.3 only showed 3 transactions. No receiving addresses.

Why? is completely cloned.
The difference is the database. OK. Clone the 80GB node.1.6.2 database and see there 1 computer now also shows 5 transactions and the 2nd with the database node.1.6.3 only 3 transactions.

On the computer with the three transactions (node ​​1.2.3) I manually entered every address with credit that I found with "listadressgroupings". 17 addresses which I have not generated before.
Transactions were added with each address, until after the last address it increased from 3 transactions to 210.

So now I have 2 databases node.1.6.2 and node 1.6.3 and 2 Wallet.dat. an original one (I call it wallet.dat-5adress) and one where the receiving addresses were entered (I call them wallet.dat-3adress)

I send the result with pictures and log files of every procedure and computer in zip format.



![config defi-wallet](https://user-images.githubusercontent.com/77095933/115122618-08dc9b00-9fe3-11eb-978e-f76629abd968.png)
![wallet dat from 11 02 2021](https://user-images.githubusercontent.com/77095933/115122671-59ec8f00-9fe3-11eb-8e96-57b4a60e0ae9.png)

Node.1.6.2
![Defi conf Node 1 6 2](https://user-images.githubusercontent.com/77095933/115122701-86081000-9fe3-11eb-81f5-97f134729326.png)

Node.1.6.3
![Defi conf Node 1 6 3](https://user-images.githubusercontent.com/77095933/115122722-a0da8480-9fe3-11eb-89b5-bec9036f2959.png)

no receiving addresses
![no adress](https://user-images.githubusercontent.com/77095933/115122765-da12f480-9fe3-11eb-9225-a3e3948484ed.png)

the receiving addresses were entered
![Adress](https://user-images.githubusercontent.com/77095933/115122790-fb73e080-9fe3-11eb-8342-041ae1581ebb.png)

**Comment by luckythai** [comment]
Original PC. Node 1.6.2 reindex - all clone from this PC.
Everything was created on this PC and the 2nd wallet and the 2nd database were not used. The evaluation of this pc was made at the end. 3 new transactions have been added that I have made in the meantime.

[Node.1.6.2.original.zip](https://github.com/DeFiCh/app/files/6329802/Node.1.6.2.original.zip)

**Comment by luckythai** [comment]
PC no1. Evaluation of Node 1.6.2 and Node 1.6.3 and the 2 wallet.dat 3 + 5 addresses.

[Node.1.6.3.Adress3.zip](https://github.com/DeFiCh/app/files/6329811/Node.1.6.3.Adress3.zip)
[Node.1.6.3.Adress5.zip](https://github.com/DeFiCh/app/files/6329812/Node.1.6.3.Adress5.zip)
[Node.1.6.2.Adress3.zip](https://github.com/DeFiCh/app/files/6329814/Node.1.6.2.Adress3.zip)
[Node.1.6.2.Adress5.zip](https://github.com/DeFiCh/app/files/6329815/Node.1.6.2.Adress5.zip)

**Comment by luckythai** [comment]
PC no2. Node 1.6.3 and the wallet.dat 3 addresses. chance Hardware

[Node.1.6.3-chance.HW.zip](https://github.com/DeFiCh/app/files/6329821/Node.1.6.3-chance.HW.zip)

**Comment by izzycsy** [comment]
Hi @luckythai , thank for the updates and feedbacks, please give us time to investigate.

**Comment by izzycsy** [comment]
HI @memzila , the team is still investigating the missing tx history issue. May I know when you export the data, are the tx history reflected? 

<img width="1003" alt="TX   Export Data" src="https://user-images.githubusercontent.com/65014479/117785415-25cd5c80-b277-11eb-8800-b4994d5df02a.png">

Could you save your app logs, .zip it and send them please? Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/117785486-37aeff80-b277-11eb-80c5-1c35870c3598.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/117785495-3a115980-b277-11eb-89bd-89d968abf38a.png">

**Comment by gamsterx** [comment]
You can add me to the list of affected users. 

It happened after the following interaction:
Remove liquidity from USDT-DFI pool (100%)

Notes:
- Since removing the liquidity from one pools no rewards are shown in the tx list.
- Other types of tx are also missing (swap, addToPool, ...)
- I have the app running on two machines (win + mac) both apps show same behavior
- I can see all tx with the "defi-portfolio" app

**Comment by izzycsy** [comment]
Hi @memzila , no need. 

Hi @gamsterx , thanks for your feedback, yes in the mean time you may use [DeFiChain Portfolio](https://defichain-wiki.com/wiki/DeFiChain-Portfolio) to view your tx.

**Comment by memzila** [comment]
Here the logs
[Logs.zip](https://github.com/DeFiCh/app/files/6517414/Logs.zip)

**Comment by izzycsy** [comment]
Hi @memzila @nippur72 , yes the team is investigating. In the mean time you can use , in the mean time you may use [DeFiChain Portfolio](https://defichain-wiki.com/wiki/DeFiChain-Portfolio) to monitor your tx history.

**Comment by gamsterx** [comment]
Upgraded to 2.4.0. 
- I synced with a snapshot --> even more txns and rewards missing
- I did a full reindex (took about 30h)--> same effect. Midway through the reindex I was seeing all the txns and rewards, but when the reindex was complete they were gone again.

**Comment by memzila** [comment]
> Hi @memzila @nippur72 , yes the team is investigating. In the mean time you can use , in the mean time you may use [DeFiChain Portfolio](https://defichain-wiki.com/wiki/DeFiChain-Portfolio) to monitor your tx history.

Hi @izzycsy bella. I don‘t think the portfolio app is still working, when all the rewards transactions are no longer in the blockchain.

**Comment by izzycsy** [comment]
Hi @gamsterx @memzila , thanks for the update, [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**.  Please read through the release notes before updating. _The above issue is not included in this update yet, this comment is to notify you about the update._ 

Our team is investigating on the missing tx history, will keep you updated here or you may refer to [DeFiChain Announcements (EN)](https://t.me/defichain_announcements) for a quicker notification update. Thank you for your patience.

**Comment by chrsch** [comment]
I'm also missing TX in the wallet. If you need input from another wallet installation just let me know @izzycsy

**Comment by izzycsy** [comment]
Hi @SpecialAgentX @salomonkarsten @luckythai @dnamurphy @gamsterx @memzila @chrsch , [v2.4.3](https://github.com/DeFiCh/app/releases/tag/v2.4.3) is out. Please read through the release notes before updating. 

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs to this issue [`v2.4.0: Missing past tx history #891`](https://github.com/DeFiCh/app/issues/891). we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.

**Comment by nippur72** [comment]
@izzycsy I upgraded to 2.4.3 but the history is still missing. 

![image](https://user-images.githubusercontent.com/2598443/120695380-9e58bf00-c4ab-11eb-9a57-47aa400a2066.png)

Here are my logs: [logs.zip](https://github.com/DeFiCh/app/files/6593642/logs.zip)

**Comment by chrsch** [comment]
For me with 2.4.5 TX are still missing.

Hint: Seems to apply only for wallets that are imported.
