### ISSUE TITLE
Minimize personal debug information in app logs

### ISSUE THREAD

**Issue by AltCoiFish** [DeFiCh/app#532]
### Preflight Checklist
`want to proceed  (y)`

### Issue Details
After going through a few submitted debug logs by users seeking help, I needed to open this issue. 
For debugging purposes it's needed to have relevant debug information. 
It would be helpful to protect the users privacy but at the same time get enough information from the application to do debugging. 

- Is it really needed to expose so much user data for debugging logs?

- Can you please minimize the exposure of personal data in debug logs?

### Actual Behavior
`# getting api credentials`
file: 068ebfb138ac0a31e5ef62f23c00a27e35bf71208ddbbfb47a730a4572bd7ccf  applogs.log
"http://XXXXX:ac41b8fc46b8XXXXXXXXXXXXXXXXb17874840c20f87348e1d0145149a@127.0.0.1:8555\"
 
#### usernames 
`# get to know the user`
112cb46bc0ff83bfd7bb65e0ac2852461cc4946895d652d1cdf0d30d32fff666  binary_log.log
"app_log.log:[20XXXXXXX] [IPC-RENDERER-info] New version 2.1.13 has been downloaded to /Users/$CLEAR_USERNAME/Library/Application Support/Caches/defi-app-updater/pending/defi-app-2.1.13-mac.zip"
 
 
#### AddToWallet TX_IDs
28b26d7651223491271fb04949219de89203390d25fae74da997a7efc2cca747  binary-log.log
"binary-log.log:202XXXXXXXX [default wallet] AddToWallet d6f9feb84e84a3aeab2177cf2cab8889bd78a1b1add131c8433fb1d065a10867  update"
 
 
#### handleAddPoolLiquidity 
`# personal preferences in investing? `
068ebfb138ac0a31e5ef62f23c00a27e35bf71208ddbbfb47a730a4572bd7ccf  applogs.log
"applogs.log:[2021-XXXXXXXXX] [IPC-RENDERER-info] [handleAddPoolLiquidity] 1. Address dbnQMqPTvpxoEAtDGFZ34DYuCm9TqptJ2scv Amount 0.213"
 
 
#### additional possible needed debug information:
068ebfb138ac0a31e5ef62f23c00a27e35bf71208ddbbfb47a730a4572bd7ccf  applogs.log
"applogs.log:[2XXXXXXX] [IPC-MAIN-info] [Starting Electron App] OS Windows 8.1 - 6.XXXXX"
 
 
I did try to anonymize the user data here, in order to protect users privacy. 

### Expected Behavior
no user data should be included in the `debug` information log's.
Users should have the possibility to choose `with` or `without` personal information. 

### App log / binary log / app config
`(not needed)`

**Comment by izzycsy** [comment]
Hi @AltCoiFish , thanks for your feedback, will forward it to the team!
