### ISSUE TITLE
Send DFI: "handleFallbackSendToken: Got error in accountToAccount"

### ISSUE THREAD

**Issue by sbisig** [DeFiCh/app#541]
#### What happened:
I cannot transfer anymore any DFI to another address. Error: "handleFallbackSendToken: Got error in accountToAccount, The address (...) is not your own address"

#### What you expected to happen:
Successful transfer as before on same 2.1.17 sw version

#### How to reproduce it (as minimally and precisely as possible):

Send DFI operation

#### What are your environment parameters?

- DeFi App Version: 2.1.17
- Operating System (OS): Win10
[Logs.zip](https://github.com/DeFiCh/app/files/6028893/Logs.zip)

**Comment by izzycsy** [comment]
Hi @sbisig , thanks for your feedback. It could be that you've too little utxoDFI balance (min. 1DFI) — which is required to perform swap and other functions. Try sending yourself 1 DFI and try the function again.

**Comment by sbisig** [comment]
utxoDFI to accountDFI is not working according to https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/
(was using both CLI commands, cf. https://defichain-wiki.com/wiki/Cli_commands wout success, still "Insufficient funds" :
- **sendtoaddress** "address" amount ( "comment" "comment_to" subtractfeefromamount replaceable conf_target "estimate_mode"avoid_reuse )
- **accounttoutxos** "from" {"address":"str"} ( [{"txid":"hex","vout":n},...] )

**Comment by izzycsy** [comment]
Hi @sbisig , to convert accountDFI to utxoDFI, the simplest way is to send DFI from your `receive address B` to your `receive address A`, the app will automatically convert for you. Can you send a screenshot if you face the error again.

**Comment by Deuf97** [comment]
![Image 01-03-2021 at 10 42](https://user-images.githubusercontent.com/52449462/109486760-34c7af80-7a7b-11eb-8d79-789a5a68ee80.jpg)

**Comment by Deuf97** [comment]
i can't swap and I can't transfer into another wallet

**Comment by izzycsy** [comment]
Hi @Deuf97 , you need to send 1 DFI to your _dK2f4..._ address. Your utxoDFI balance is **0** — which is required to perform swap and other functions. Try sending yourself 1 DFI and try the function again.

**Comment by Deuf97** [comment]
![image](https://user-images.githubusercontent.com/52449462/110216553-9aff6880-7ea7-11eb-86e1-78a22ed4f380.png)

**Comment by Deuf97** [comment]
now I can't synchronizing .. I Just update this app look to be a little complicated to use. what I need to do

**Comment by Deuf97** [comment]
I can't withdraw in my coinbase so I TRANSFER in my Deficake wallet btc  but now they say it's not enough

**Comment by Deuf97** [comment]
![image](https://user-images.githubusercontent.com/52449462/110244200-7c57ab00-7f55-11eb-90b4-89b5ba823ec6.png)

**Comment by Deuf97** [comment]
but I transfer all my btc if I Send it on my defi cake wallet it's for do my withdraw on my bank . but I'm just paying fee for every tranfert I DO and ask me again to do a deposit

**Comment by Deuf97** [comment]
how can I transfer my fuckin btc or DfI in GBP and put it my bank ? they don't even say the amount of the fee when they ask to do the deposit

**Comment by Deuf97** [comment]
someone know how much is this fee or if we got way to withdraw without do a new deposit or transfert ?

**Comment by izzycsy** [comment]
Hi @Deuf97 , this is DeFiChain, not Cake. You can enquire on [CakeDeFi Telegram (EN)](https://t.me/CakeDeFi_EN) about your issue or seek Cake's support via their website. I'm not sure about the fees charged on Cake so I do not have an answer for you.

**Comment by izzycsy** [comment]
Hi @sbisig , update [v2.3.1](https://github.com/DeFiCh/app/releases/tag/v2.3.1) is out.   Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
