### ISSUE TITLE
MacOS: App CLI does not accept <option> key combinations

### ISSUE THREAD

**Issue by tame81** [DeFiCh/app#543]
This is a very old issue, however, it has not been solved and it's not open anymore. 

#### What happened:
When using the app on MacOS, entering characters that are typed using the `<option>` key are not accepted. That applies for example to the curly braces and the square brackets on a German keyboard layout.

#### What you expected to happen:
The CLI should print the characters as every other app on MacOS.

#### How to reproduce it (as minimally and precisely as possible):
Click the CLI symbol in the app. Now try to enter a character using `<option>+<something>`.

#### What are your environment parameters?

- DeFi App Version: 2.1.17 (happened ever since the first version I downloaded months ago)
- Operating System (OS): MacOS

**Comment by izzycsy** [comment]
Hi @tame81 , thanks for your feedback. Yes the team is aware of this and will get it fixed in due time. Thank you.

**Comment by izzycsy** [comment]
Hi @tame81 , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

The above feature / issue is not included in this update yet, this comment is to notify you about the update.
