### ISSUE TITLE
Passphrase should be starred out

### ISSUE THREAD

**Issue by tame81** [DeFiCh/app#544]
#### What would you like to be added:
When entering the passphrase in the CLI, it should be starred out (stars displayed instead of the clear text password). This could be done by redesigning the `walletpassphrase` command such that it will query for the password and display stars instead of the individual characters.

#### Why is this needed:
For security reasons, obviously.

**Comment by thedoublejay** [comment]
@tame81 On the upcoming app release, we will be a releasing a wallet encryption feature. You can use the UI for this and not rely on CLI anymore.

**Comment by thedoublejay** [comment]
@tame81 New app v2.3.0 is available for download now - https://github.com/DeFiCh/app/releases/tag/v2.3.0 The passphrase feature is now available in the app.

**Comment by tame81** [comment]
@thedoublejay, will this version be pushed to the app so we can update from there?

**Comment by thedoublejay** [comment]
Yes @tame81, but you can also download the binary here and install it. It will overwrite your current app. Depends on your preference. Btw, for this release you need to re-index from 0% because it's using the new hardfork v1.5.0.
