### ISSUE TITLE
Add-on auth TX failed: Insufficient funds

### ISSUE THREAD

**Issue by tava6655** [DeFiCh/app#545]
#### How to reproduce it (as minimally and precisely as possible): Try swapping or adding or removing liquidity. 

I tried adding liquidity to several trading pairs; such as DOGE/DFI or USDT /DFI and keep getting the error: _Add-on auth TX failed: Insufficient funds._ This also occurs and when swapping coins for another; doesn't work. 

#### What are your environment parameters?

- DeFi App Version:2.1.17
- Operating System (OS): Windows 10

#### Anything else we need to know?:

[DefiChainLogs.zip](https://github.com/DeFiCh/app/files/6031196/DefiChainLogs.zip)

**Comment by izzycsy** [comment]
Hi @tava6655 , it could be that you've too little utxoDFI balance (min. 1DFI) — which is required to perform swap and other functions. Try sending yourself 1 DFI and try the function again. 

To check your balance via CLI:
`getbalance` — utxoDFI
`gettokenbalances` — accountDFI  

The sum of utxoDFI & accountDFI would be your total tokens.

**Comment by tava6655** [comment]
Thanks for your response.  It was helpful!

**Comment by izzycsy** [comment]
Hi @tava6655 glad to know your issue has been resolved, I'll be closing this issue. Thank you.
