### ISSUE TITLE
Win: sync 95% > Node is disconnected

### ISSUE THREAD

**Issue by jwmcdonnell** [DeFiCh/app#546]
HI, I have been using the DeFi app for several months on my work laptop with little to no issues.  I am now trying to load the app on my personal laptop but I cannot get it to load.  It syncs for about 2 hours and gets to about 95% then I get a Node Error message.  I've tried this on several of my personal computers all with the same results.  I'm using the latest app from the website (2.1.17).  I  have windows 10 and the required memory.  Does anyone else have this issue or does anyone have any suggestions?  thanks.
John
mcdonnelljohn13@yahoo.com

[app_config.zip](https://github.com/DeFiCh/app/files/6033396/app_config.zip)
[System Information 2.23.21.xlsx](https://github.com/DeFiCh/app/files/6033397/System.Information.2.23.21.xlsx)

**Comment by thedoublejay** [comment]
@jwmcdonnell Have you tried the solution here https://defichain-wiki.com/wiki/Wallet_Bugs? You can go to Settings page -> Enable Reindex after savings -> Enable Delete peers and blocks -> Save. It should re-index the app but might resolve this node is disconnected issue.

**Comment by izzycsy** [comment]
Hi @jwmcdonnell , as mentioned in the above comment, try to Reindex via Settings. 

<img width="778" alt="Reindex   saving + delete peers and blocks" src="https://user-images.githubusercontent.com/65014479/108977698-c625d300-76c3-11eb-89a6-936f96ff49f7.png">

**Comment by jwmcdonnell** [comment]
Hi,
I just got an email about the Dakota upgrade and it says that I need to use the new app by March 1.  Is the new app available now?  Should I start using it now?
Thanks.
    On Wednesday, February 24, 2021, 04:15:09 AM EST, Bella <notifications@github.com> wrote:  
 
 


Hi @jwmcdonnell , as mentioned in the above comment, try to Reindex via Settings.

**Comment by thedoublejay** [comment]
@jwmcdonnell Yes, the new app is available now. You can download it from our release page - https://github.com/DeFiCh/app/releases/tag/v2.3.0

**Comment by izzycsy** [comment]
Hi @jwmcdonnell , update [v2.3.1](https://github.com/DeFiCh/app/releases/tag/v2.3.1) is out.   Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
