### ISSUE TITLE
Feat | Save send address

### ISSUE THREAD

**Issue by Brownie89** [DeFiCh/app#551]
#### What would you like to be added:
I'd like to have a feature that offers the possibility to save common address I often use for sending DFI or something.
#### Why is this needed:
Currently I use a document for keeping the addresses and I don't want to have an external document for stuff like this.

**Comment by izzycsy** [comment]
Hi @Brownie89 you can manually add your address in the app. Turn off the `Automatically generate a new address`. 

<img width="869" alt="Manually add address" src="https://user-images.githubusercontent.com/65014479/109153470-eaf37680-77a7-11eb-8405-4c46778e0279.png">

**Comment by Brownie89** [comment]
I'm pretty sure my English is not that bad you could misunderstand my concern in this way.
I know how to insert my (old) receive addresses into the app.

Maybe it get's clearer by giving an example:
By LM I receive DFI and I want to send them to cake. Now I need to login into cake and copy my receive address there or I open up my local document and copy it. At this point I'd like to have the possibility to choose from something like an address book inside the app.

**Comment by tame81** [comment]
Excellent suggestion @Brownie89, just wanted to create that feature request!

**Comment by tame81** [comment]
BTW @izzycsy, that button most likely should be an address book launcher is apparently malfunctioning, it just displays an empty box...
<img width="1011" alt="Screenshot 2021-02-26 at 21 44 33" src="https://user-images.githubusercontent.com/34913516/109353300-776f6900-787c-11eb-97db-78ccf297ff5c.png">

**Comment by izzycsy** [comment]
Hi @Brownie89 , thanks for you feedback. Will forward it to the team. 

Hi @tame81 , thanks for the feedback, the team is aware of the blank QR code issue.

**Comment by izzycsy** [comment]
Hi @Brownie89 , team has accepted your feature request to be considered in future builds, I can’t give you a timeline on it right now as we’re prioritising other issues at the moment, thank you for your understanding and patience.

**Comment by izzycsy** [comment]
Hi @tame81 @Brownie89 , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

The above feature is no included in this update yet, this is comment to notify you about the update.

**Comment by izzycsy** [comment]
Hi @tame81 @Brownie89 , your feedback has been conveyed to the team, however I do not have a timeline on whether and when this would be implemented. Just wanted to update you before this thread becomes stale. Rest assured that it'll be considered by the team. For future enhancement related ideas, you can post it on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner some support from the community, and the team can decide whether to implement the feature in the future. Thank you!
