### ISSUE TITLE
Linux: app not generating a backup file

### ISSUE THREAD

**Issue by Folderguion** [DeFiCh/app#553]
#### What happened: 

The Defi App is not generating a backup file, but neither log files. 

#### 

- DeFi App Version: 2.1.17 
- Operating System (OS): Linux

**Comment by izzycsy** [comment]
Hi @Folderguion , thanks for your feedback, for Linux you can get access to your `wallet.dat` files through: 

Linux: ` /home/<username>/.defi/wallets/wallet.dat`

Moving forward in the latest release v2.3.0, we've be introducing _wallet passphrase_ (optional), and the utilisation of `wallet.dat`. Essentially, tour `wallet.dat` is replacing the current v2.1.17 `backup wallet`. Please keep your `wallet.dat` file safe. This workaround should solve your issue. 

<img width="626" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/109126096-d99a7200-7787-11eb-83e0-9d40a4878737.png">

/need docs

**Comment by Folderguion** [comment]
Hello, tnx for the answer. Actually I can't find that directory. Just running the DeFi wallet through the .AppImage file and cannot find any other folder named DeFi as your image.

**Comment by izzycsy** [comment]
Hi @Folderguion it's a hidden folder in your PC. You probably have to type the route out. I'm not a Linux user, but hopefully this might [help](https://www.linode.com/docs/guides/find-files-in-linux-using-the-command-line/). 

<img width="888" alt="Find Linux file by extension" src="https://user-images.githubusercontent.com/65014479/109383272-68da8d80-7920-11eb-85a9-1199031f429a.png">

**Comment by Folderguion** [comment]
Ok, thank you very much, I found "wallet.dat" . So in case I need to recover my wallet, this is the file to backup, right? 
Do you suggest to update from 2.1.17 version by the way? 

Thank you

**Comment by izzycsy** [comment]
Hi @Folderguion , yes you'll use this backup to Restore your wallet when you upgrade to [v2.3.0](https://github.com/DeFiCh/app/releases/tag/v2.3.0). Please keep your `wallet.dat` safe. And yes, you'll have to update to v2.3.0 eventually due to the Dakota upgrade. More details in the link provided.

**Comment by Folderguion** [comment]
Ok thank you very much!

**Comment by izzycsy** [comment]
Hi @Folderguion , did you manage to upgrade to v2.3.0 and restore with wallet.dat?

**Comment by Folderguion** [comment]
Hey  @izzycsy , thanks for asking. I've updated and I'm still in Sync so I can't still backup the wallet.dat file. 
Will report back to you later on, once the Sync is complete.

**Comment by Folderguion** [comment]
Hello @izzycsy , I've sync and imported wallet.dat. All is perfect!

However the only uncomfortable process is the "manual" backup. I have to open the .defi directory, find the the wallet.dat file and copy it to another location in order to backup the wallet. 

If I can be of help testing any other automated process for Linux that you might develop later, just let me know. Will be glad to contribute!

**Comment by izzycsy** [comment]
Hi @Folderguion , I'll keep you in mind if we do set up a Linux team, can you dm me on Telegram @imnotabell? I'll remove this message when I receive your dm.

**Comment by izzycsy** [comment]
Hi @Folderguion , perfect, I'll be closing this issue in the mean time. You may reopen this issue if there's new information (include screenshots) and your app logs. Thank you.

**Comment by Folderguion** [comment]
Thank you for the help!
