### ISSUE TITLE
Backup Wallet locked or unlocked does not change

### ISSUE THREAD

**Issue by wyssen** [DeFiCh/app#555]
Hello dear community
I have the following problem and I need to be sure that my funds are save before I update to the latest version 2.3.0

I have encrypted my wallet and want to make a backup of it, before updating.
I remember that in older versions prior my current version 2.1.17, I needed to first use "walletpassphrase" in order to decrypt and only then use the Menu "Wallet->Backup Wallet". If I used the Wallet backup function without prior decryption, nothing happened.

However, in the current version 2.1.17 I use, it does not change anymore, if I have the wallet locked or unlocked. The export of the "Wallet->Backup Wallet" gives my the very same encrypted *.dat File.
Should there not be a difference, when I decrypt the wallet before?
Am I save with my encrypted wallet.dat file or do I need anything else appart from the seed to be able to restore everything in case of a problem during the update?
It confuses me that before, the export was different and in plain text, do you know what I mean?

I send DFI's to Cake daily and always need to decrypt it before (makes sense to me).

- DeFi App Version: 2.1.17
- Operating System (OS): Win10

Thank you so much for giving me the security that the encrypted wallet.dat (and the passphrase) is what I need to be able to restore everything in case of a problem.

**Comment by thedoublejay** [comment]
Hi @wyssen, both will give same backup. I believe your wallet is already "encrypted". Using passphrase command doesn't remove the encryption, but only unlocks your wallet for a certain time. So technically, both should have same wallet.dat. But of course, keep your old backups as usual. 

By the way, the new app release is out - https://github.com/DeFiCh/app/releases/tag/v2.3.0 You can now do wallet encryption on the app and not on the CLI.

**Comment by wyssen** [comment]
Hi @thedoublejay 
Thank you for your response. I was just confused because in the previous versions, the backup was not possible when wallet was locked. I needed to unlock, then backup. And then, the backup file was an unencrypted txt file.
With the version 2.1.7, I don't need to unlock prior backing up and the backup file is an encrypted dat, not an unencrypted txt anymore. For me, this is perfect, because I prefer having an encrypted file instead of the plain text obvisouly.
As long as I am able to restore in the case of an emergency. Was just confused about this different behaviour in previous versions and want to make sure that this is correct now.

**Comment by thedoublejay** [comment]
Hi @wyssen, yes it was an iterative process for us for the overhaul of wallet encryption. We started with removing the "txt" backup and moving to a proper .dat backup where you can use to restore. Now with new version, you can do encryption in the app including locking and unlocking your wallet. Please have a look. You might need to re-index from 0% because it's using the new hard fork v1.5.0. 

I hope I helped you solve your issue. Please close the issue if it's ok with you. Thanks!
