### ISSUE TITLE
Synchronizing still at 0.00%

### ISSUE THREAD

**Issue by rampo12** [DeFiCh/app#556]
Hello everybody,

I'm new on defi-app, I start to use this from software version 2.1.7 and from the beginning I was not able to synchronize blocks. I solved it manually adding the node "62.75.139.29:8555" and till updating to version 2.3.0 everything works fine. After updated to software version 2.3.0 I'm not able to synchronize blocks again, so I tried to manually add again the previous node, but nothing changed. So I try to uninstall and install again the app, also adding again the node, but I'm still not able to synchronize blocks. 
I made a backup of my wallet before updating the app, but now I'm not able also to recover my wallet because it gave me the message "You will be able to create or restore a wallet when sync is complete". So I have to wait for a synchronization that never happen. 
I'm using defi-app on MacOS 11.2.1

Hope someone can help me, thanks in advance best regards. 

Davide

**Comment by izzycsy** [comment]
Hi @rampo12 , thanks for your feedback, may I know how long did you wait while the app was stuck at 0% then you proceed to close it?

**Comment by rampo12** [comment]
Hi @izzycsy, I've open the app 2 hours ago, the app is still open and now synchronizing is still at 0.00%. I notice that sometimes it appear the green check next to synchronize (bottom left of the app), but it restart from 0.00% every time and stay still at 0.00% every time. 
Please see attached log file. 
Hope you can help me..
[Archivio.zip](https://github.com/DeFiCh/app/files/6044916/Archivio.zip)

**Comment by izzycsy** [comment]
Hi @rampo12 , thanks for the update, it'll take a while for the team to investigate this issue. But maybe you can try this, backup your wallet.dat and replace the app with v.2.3.0 again. 

Ensure your app is not running. You may be able to recover your wallet by finding the backup wallet.dat in the wallets folder. On Mac it is located here: 
 
Mac — Go to Folder: ` /Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat`
 
you will see several wallet.dat files named `wallet-bak-1234567890123.dat` — do not delete any of these, make a copy and move them to a safe location.   

<img width="626" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/109383752-80674580-7923-11eb-80bc-8a89d485bfd5.png">

Then go to [v2.3.0](https://github.com/DeFiCh/app/releases/tag/v2.3.0), download **defi-app-2.3.0.dmg**.

<img width="629" alt="defi-app-2 3 0" src="https://user-images.githubusercontent.com/65014479/109383824-0edbc700-7924-11eb-8d57-e64032b3cacc.png">

Replace your app with the recently downloaded **defi-app-2.3.0.dmg**.

<img width="539" alt="Replace app1" src="https://user-images.githubusercontent.com/65014479/109383839-2f0b8600-7924-11eb-9654-d3ca8522ee4d.png">

<img width="535" alt="Replace app2" src="https://user-images.githubusercontent.com/65014479/109383847-3af74800-7924-11eb-9768-fcb8ca383f7d.png">

See if the app syncs to 100%. If it doesn't, I advice that you wait for a fix — the next update.

**Comment by rampo12** [comment]
Hi @izzycsy and thanks for your answer, I solved uninstalling and reinstalling the version 2.3.0. The sync process was very long to be taken (approx one night) and it was necessary also to add the node "62.75.139.29:8555", but now it works. 
Thanks for your support! May I close this issue now, I suppose..

**Comment by izzycsy** [comment]
Hi @rampo12 , thanks for the update. I'll close this issue on your behalf, I'll let the team know of this, might help in the investigation. Thank you!
