### ISSUE TITLE
Win8: Wallet balances not displayed

### ISSUE THREAD

**Issue by arnaudom** [DeFiCh/app#559]
After updating to latest version v2.3.0 from inside desktop application, the wallet request a restart. Clicking on restart lead to application freeze. Impossible to close or do anything else.

1 -> next step: delete all chain DB and files
2 -> launch app : resync
3 -> next step after full sync : restore wallet from seed
4 -> app freeze
5 -> restart from step 1 + 2
6 -> next step after full sync : restore wallet from backup
7 -> app freeze
8 -> restart from step 1 + 2
9 -> close app and restart : splash screen running indefinitely

- DeFi App Version: 2.3.0
- Operating System (OS): Windows 8, 16G

Attached:
logs after step 8 above;
app screenshots
running tasks 
[logs-after-sync-and-restart.zip](https://github.com/DeFiCh/app/files/6042091/logs-after-sync-and-restart.zip)

**Comment by thedoublejay** [comment]
Hi @arnaudom,

Based on your logs, I believe you might have deleted one configuration file that we're using. I'll be investigating this issue so we can prevent this even if users will be deleting their files. For the mean time, can you add the attached file in your `C:\Users\your username\AppData\Roaming\DeFi Blockchain\wallets` folder? It's an empty configuration file. 

1. Close the app
2. Extract the file
3. Paste the file on the folder
4. Re-open the app.

As a precaution, please avoid deleting files in the future especially without proper backup. Let me know if this workaround will work for you. Thanks.

[wallet_map.zip](https://github.com/DeFiCh/app/files/6042424/wallet_map.zip)

**Comment by arnaudom** [comment]
Hi,

I follow your procedure, 
The app closed after clicking X and quite some time closing;
Copied your file. 
Get the screen asking for restart with "delete peers" (see attachment);
Click "restart", so far nothing happen...
From task manager all seems running.
[DeFiBlockchain.zip](https://github.com/DeFiCh/app/files/6042674/DeFiBlockchain.zip)

"_As a precaution, please avoid deleting files in the future especially without proper backu_p" :  actually my procedure is like a full re-installation. In this case you should not have need for backup.
Note: in previous version I had similar problems and I always managed to do full re-installation after deleting DB folder.
Like: https://github.com/DeFiCh/app/issues/352#issuecomment-768360525

**Comment by izzycsy** [comment]
Hi @arnaudom it seems like your PC does not meet the [minimum requirement](https://defichain.com/learn/defi-app-how-to/) for DeFi app.

**Comment by arnaudom** [comment]
> Hi @arnaudom it seems like your PC does not meet the [minimum requirement](https://defichain.com/learn/defi-app-how-to/) for DeFi app.

Hi izzycsy

I did not have this problem until last version.
Have requirement changed specifically for that version ?

**Comment by arnaudom** [comment]
I see a lot of comments about the fact that many other users have similar problems with the new version and that also master nodes are upgraded at the same time
Thus, I am still trying to launch the wallet with new sync. 
But now I am having a new error: Node is disconnected
![node disconnect](https://user-images.githubusercontent.com/1535627/109236506-acdb6e80-780a-11eb-8600-91108dc29a60.jpg)

**Comment by arnaudom** [comment]
> But now I am having a new error: Node is disconnected
> ![node disconnect](https://user-images.githubusercontent.com/1535627/109236506-acdb6e80-780a-11eb-8600-91108dc29a60.jpg)

I tried to revert to the previous version **2.1.17** that was working perfectly on my system, but now, It does not sync anymore as well.
Something is broken.

![v2117](https://user-images.githubusercontent.com/1535627/109252902-8b3daf80-7829-11eb-9237-46b2b14e5630.jpg)

**Comment by thedoublejay** [comment]
Hi @arnaudom, 2.1.17 won't work because it's using an old node. For the node is disconnected issue, when you reindexed, have you enabled delete peers and blocks?

**Comment by arnaudom** [comment]
Hi @thedoublejay,
Yes, but "restart" button does not seems to work. I close with "X" icon and relaunched
It starts resync. I managed to sync 100% on third attempt but then can't restore my wallet. Tried seed and backup. Seed procedure tells me that there is an error, "the key exist or is loose" (something like that and backup does not do anything.
Then after close again and restart, sync start again from 0.
(I am talking about 2.1.17 here)

**Comment by thedoublejay** [comment]
@arnaudom Have you tried to use v2.3.0 and successfully synced to 100%?

**Comment by izzycsy** [comment]
Hi @arnaudom the specifications for minimum requirements has not changed, I understand that perhaps your PC has a strong RAM, but the OS version matters as well. It could be that your PC is becoming incompatible with the app as we move forward with the upgrades. 

As for users with the same issues, their reason for facing the issue might be different from yours. We do not make assumptions and review everything on a case by case basis. And for yours, it's likely OS version. What I can suggest is to keep your wallet.dat safe. For Windows it's located here: 

Windows — C: ` \Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat`

**Comment by arnaudom** [comment]
@thedoublejay On windows 8, I did not managed.
I have another install in a computer with windows 10 and I did it. I downloaded and install instead of using update button.
But it sync 2 times before it restored my data.

@izzycsy , 2.1.17 was working perfectly with my config of 16MB in windows 8. too bad you can't maintain for older windows versions.
Yes I am keeping backups of wallet.dat files. Thanks

**Comment by thedoublejay** [comment]
Hi @arnaudom, regarding the double sync issue. Thanks for reporting it. We have a fix for it and will be coming on next update. Sorry for the inconvenience. 

On the OS support, I think it was always set to Windows 10 as minimum requirement. We are using mostly Windows 10 machines for development and testing. Just always have a copy of your wallet.dat and you're good.

**Comment by flotzke** [comment]
Hi, same issue here. When i try executing defid.exe after the 'Node is disconnected' i get the following output:
![defid-error](https://user-images.githubusercontent.com/9954463/109383269-b8e82e80-78e5-11eb-89fd-b47734211958.jpg)

**Comment by arnaudom** [comment]
Hello,
I am still trying to update the latest version on W8 system.
I have followed this procedure:

1. re-install previous v2.1.17
2. sync 100%
3. update to v2.3.0 from within previous version 
4. once sync 100%, tried to load backup file from cli -> failed
5. closed and restart
6. do backup
7. try to restore wallet from seed -> getting error message "Already have this key (either as an HD seed or as a loose private key)"

Looks the wallet is already installed ...
But token accounts are not displayed.
And CLI gettokenbalances gives me correct result.

So isn't only a interface design issue ?

See attachments.

[2-3-0.zip](https://github.com/DeFiCh/app/files/6058755/2-3-0.zip)

**Comment by izzycsy** [comment]
Hi @arnaudom , thanks for the update. Possibly UI issue, we'll need time to investigate. You can try to Restore from wallet backup (wallet.dat) instead and see if balance in UI appears, or wait for a fix since you're already synced to 100%.  

<img width="1019" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/109544092-18228a80-7b02-11eb-8783-b4f119e8e7d1.png">

**Comment by arnaudom** [comment]
Good morning @izzycsy,
when I click the "Restore wallet from backup" button the application freezes.
I tried a CLI import but I am not sure of the exact script.
What is exact CLI import script ?

**Comment by izzycsy** [comment]
Hi @arnaudom , no we do not have a script for that, you'll have to do it through the app UI. Do you have screenshot of when the application freezes? 

Windows — C:  `\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat`

**Comment by arnaudom** [comment]
@izzycsy 

I found another way to have backup import choices on the interface.
I edited the wallet_map.json manually with paths of backups which gave me the list in the application:

![walletmap](https://user-images.githubusercontent.com/1535627/109788117-e87e9a00-7c49-11eb-9c64-18468708195f.jpg)

I selected the 1st one

![walletmap-restore](https://user-images.githubusercontent.com/1535627/109788231-0c41e000-7c4a-11eb-84f0-49797a494b3f.jpg)

Importing

![walletmap-import](https://user-images.githubusercontent.com/1535627/109788309-24b1fa80-7c4a-11eb-8562-089c0359b06f.jpg)
...

Result :

![walletmap-disconnect](https://user-images.githubusercontent.com/1535627/109788376-37c4ca80-7c4a-11eb-8b6a-e56dec16ffb4.jpg)


Now the application is not starting or freeze at splash screen with log stating:

_Error: Specified -walletdir "C:\Users\Dominique\AppData\Roaming\Defi Blockchain" does not exist_

The folder exist, no doubt.

So now I am trying to re-install the whole app and restart a synchronization.

Ialso noticed something: when uninstalling and re-installing the application (and delete blocks DB), the folder "wallets" is not created but the logs show that the application is looking for that folder and the wallet_map.json file.

**Comment by izzycsy** [comment]
Did you try to include C:\Users\Dominique\AppData\Roaming\Defi Blockchain`\wallet\wallet.dat` in your search bar? Do note that you should not rename / move wallet.dat file when the app is running. It should be left with it's original name, if you want to rename / move the file, create a new wallet.dat backup and specify the file in the app when you exit the wallet. Only in v2.3.0 onwards users can name / move their wallet.dat to their preference. 

<img width="403" alt="Exit wallet" src="https://user-images.githubusercontent.com/65014479/109790719-a7d45000-7c4c-11eb-9c30-9b292b9b4ebb.png">

**Comment by arnaudom** [comment]
@izzycsy 

I don't understand this question:
Did you try to include C:\Users\username\AppData\Roaming\Defi Blockchain\wallet\wallet.dat in your search bar?

What search bar is it ?

I don't have the exit button available. You can see from previous screenshots, it appears only once I get the wallet imported but then the error message "node disconnected" prevent use of the exit button.

I did not rename while running and these are various backups that where made from the application.

**Comment by arnaudom** [comment]
@izzycsy

Ok, finally managed to do it !

1 - re-install full application from scratch on my windows 8
2 - synchronized 100%
3 - create wallet folder under C:\Users\***\AppData\Roaming\Defi Blockchain **manually**
4 - create wallet_map.json file **manually**
5 - edited the file with a backup path (I changed the path that logs were telling me it does not exist previously)
6 - closed and restart the application
7 - now having a choice to **import wallet from path**

![wallet-choose-backup](https://user-images.githubusercontent.com/1535627/109828600-c0a62b00-7c77-11eb-9f4a-02ea6f704586.jpg)

 
![wallet-confirm-backup](https://user-images.githubusercontent.com/1535627/109828656-cbf95680-7c77-11eb-9f9c-3dbe46df07a1.jpg)

![wallet-import-backup](https://user-images.githubusercontent.com/1535627/109828701-d61b5500-7c77-11eb-979c-3f8578355520.jpg)

Now everything is recovered.

![wallet-tokens](https://user-images.githubusercontent.com/1535627/109829187-40cc9080-7c78-11eb-9076-5f57e765c1e2.jpg)

**Comment by izzycsy** [comment]
Hi @arnaudom , glad to hear! Please keep your wallet.dat & passphrase (write it down somewhere) safe. 

Hi @flotzke , may I have your app logs please? Are you having the same issue where you've trouble linking your app to the wallet.dat? Did you wait for the app to sync to 100%?

**Comment by izzycsy** [comment]
Hi @flotzke , update [v2.3.1](https://github.com/DeFiCh/app/releases/tag/v2.3.1) is out. Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may leave a comment & tag @izzycsy, please provide new information (include screenshots) and app logs. Thank you.
