### ISSUE TITLE
Test transaction is not displayed in Explorer

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#562]
Respected developers

I have made a transaction in the testnet. The transaction worked, but it is not displayed in Explorer. 

Error message: 
The requested txid c4034a8b28705a06de38dfa1062b5a7978f0afcbc6efb53007557080d3411d35v could not be found, it is most likely still being confirmed, please try again in a few minutes.

https://testnet.defichain.io/#/DFI/testnet/tx/c4034a8b28705a06de38dfa1062b5a7978f0afcbc6efb53007557080d3411d35v

**Comment by izzycsy** [comment]
Hi @RobinTorque , thanks for your feedback, please give us time to investigate this.

**Comment by izzycsy** [comment]
Hi @RobinTorque , update [v2.3.1](https://github.com/DeFiCh/app/releases/tag/v2.3.1) is out, I'll be closing this issue for now, if the issue occurs again please take note of the error & send logs. Thank you!
