### ISSUE TITLE
Insufficent uxtoDFI

### ISSUE THREAD

**Issue by bmagierski** [DeFiCh/app#563]
I have 77+ DFI Tokens and tried to stake them on the ETH-DFI pool. Many times this fails with an 'insufficient UTXO' error. To solve it in the past (daily), I would go to Settings->Refresh UTXOs->Save, and then stake and it would work fine. Since I upgrade to v2.3 and added a passphrase to my wallet, I cannot stake my DFI to my existing pools. When I try, I get 'insufficient UTXO' error. When I try to "Refresh UTXOs", the app hangs up with a spinner. I've let it go as long at 30+ minutes without resolution. 

If I check 'getbalance' I only have 0.97 DFI coins. If I check 'gettokenbalances', I show 77+ DFI Tokens. 

I expected to refresh UTXOs like I have in the past and then successfully stake my new DFI tokens to the ETH pool.

- DeFi App Version: 2.3
- Operating System (OS): Mac OSX 10.15.7 Catalina

**Comment by izzycsy** [comment]
Hi @bmagierski , thanks for your feedback, and for checking `getbalance` & `gettokenbalances`. It could be that you've insufficient utxoDFI balance (min. 1 DFI) — which is required to perform swap and other functions. You could try to convert a little accountDFI tokens to utxoDFI, and see if it works.

DFI exist in 2 forms; **utxoDFI** and **accountDFI**. utxoDFI is used to pay for transactions fees while rewards received are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. To convert accountDFI to utxoDFI, the simplest way is to send DFI from your `receive address B` to your `receive address A`, the app will automatically convert for you.

**Comment by bmagierski** [comment]
Thanks. I understand the difference between the utxoDFI and the accountDFI. Can you be more specific about what you refer to as 'receive address B' and 'receive address A'? I'm staked in three pools: ETH, BTC and USDT. I also accumulate DFI rewards from these pools and hold a little BTC and ETH on-chain. Are you suggesting that I just send 1 DFI to myself in the DFI wallet on-chain? Or is there a CLI command for converting accountDFI to utxoDFI which I can use when the balance goes below 1 utxoDFI?

**Comment by bmagierski** [comment]
Quick follow-up. I have two addresses in my app for DFI, so I sent 1.0 DFI from one of my addresses to the other. The results are below: 

`getbalance` before was 0.97. After is now 144.39
`gettokenbalances` for DFI Token before was 171. After is 26.09.

When I go to my app though, I have properly 170 DFI tokens in my wallet. 

I see this solved the issues by creating utxoDFIs and enabled me to post more liquidity to the ETH-DFI pool, however, I must say I am pretty confused as to how the utxoDFI and accountDFI work. Wouldn't my `getbalance` command just incremented the utxtDFI from 0.97 to 1.97 rather than up to 144.39. Seems random. 

Anyway the solution worked, but it still leaves me confused as to how to manage the utxos.

**Comment by bmagierski** [comment]
One last question on this topic. When I post new liquidity to a pool, I have been adding the max DFI to the pool less 1.0 DFI. Would it be better to short the amount by more than 1.0? I noticed that when I completed adding the new liquidity to the pool, my `getbalance` went back down below 1.0 to about 0.99. 

Thanks.

**Comment by izzycsy** [comment]
Hi @bmagierski , for example, you want to send BTC to an external address, utxoDFI will be deducted as fees. Another example, you paired DFI-BTC using Add Liquidity, the rewards you received are in accountDFI. Hence, the two balances `getbalance` & `gettokenbalances` for your DFI. 

Regarding you last question, when your `getbalance` went down to 0.99 it's probably due to transaction fees. I hope this answers your question. Glad that your issue is resolved, I'll be closing this in the mean time. Should you face the same issue again, you may reopen this issue with new information (include screenshots) and app logs. Thank you.

**Comment by bmagierski** [comment]
Thanks. I hope that this will be obfuscated from the user in the future as it is a barrier to usability for those not technical enough. 

For clarity - if this issue arises for a user, they have two options: 

1. Send 1.0 DFI from one of the user addresses to another (i.e. send to oneself). I guess this means that a user needs two DFI wallet addresses minimum.
2. Use CLI with this command `accounttoutxos "from" {"address":"str"} ( [{"txid":"hex","vout":n},...] )` where "from" is one DFI address and {"address"} is the second one (same addresses in #1 above). 

Just leaving a trail for future users that face this issue. The lack of UTXOs seems to come up a lot on the Telegram channel.
