### ISSUE TITLE
Feat: add tx history of pool-pair to wallets

### ISSUE THREAD

**Issue by gsi2help** [DeFiCh/app#565]
app V2.3.0
no transactions in the poolpair-wallets (BTC-DFI, ETH-DFI, DOGE-DFI, LTC-DFI, USDT-DFI) in the new wallet
LM add/remove transactions are now only showed in the DFI/ETH/BTC/DOGE/LTC Wallet

please show the LM transaction on all 3 wallets - eg.. LM BTC-DFI should be showed at BTC-DFI, BTC and DFI wallet, because all accounts are changed at the same time in one tx

**Comment by izzycsy** [comment]
Hi @gsi2help , thanks for your feedback, will forward it to the team.

**Comment by izzycsy** [comment]
Hi @gsi2help , this feature has been feedback to the team. The team are trying to resolve some major blockers in v2.3.1, so it may be released in v2.3.2. Thanks for your feedback.
