### ISSUE TITLE
The CSV Export is missing some necessary data

### ISSUE THREAD

**Issue by jleidinger** [DeFiCh/app#569]
#### What would you like to be added:

I miss a date and time (or one together) column in the generated CSV. The amount and the coin are actually shown as 0.34@DFI. This should be two columns. There should also be an opportunity to export the whole account data for each coin in one step. 

#### Why is this needed:

The data export is needed for an export to CoinTracking or other similar platforms.

**Comment by izzycsy** [comment]
Hi @jleidinger , thanks for your feedback, will forward this to the team.

**Comment by izzycsy** [comment]
Hi @jleidinger , update [v2.3.1](https://github.com/DeFiCh/app/releases/tag/v2.3.1) is out. Date / Time has been added.
