### ISSUE TITLE
Please wait until your transaction has been added to the next block before proceeding with a new transaction.

### ISSUE THREAD

**Issue by NatetheGit** [DeFiCh/app#571]
I'm using DFI App version 2.3.0.

I have DFI and ETH that I'm trying to add to liquidity pool.
When I attempt to add, I get this error message: "please wait for your transaction to be reflected in the next block before proceeding with a new transaction"

I get the same error if I try to add to DFI/BTC liquidity.
I've used different machines, and get the same error on each machine.

I've waited for days on separate days, and still get the same error.

I've attached my logs as Archive.zip.
[Archive.zip](https://github.com/DeFiCh/app/files/6052005/Archive.zip)

**Comment by NatetheGit** [comment]
An additional note. I tried to fix this by removing everything from liquidity to sort of start over with liquidity by re-adding it all. But it wouldn't let me remove anything from liquidity either with the same error message about waiting for my previous transaction to be reflected in the next block.

**Comment by NatetheGit** [comment]
I temporarily re-installed version 2.1.17 and tried adding liquidity with that. And it worked! I know I can't stay on 2.1.17 for long because of the Dakota update will be necessary. But I'm hoping that version 2.3.0 will work now that I've gotten at least one transaction through using the old app. I will try adding liquidity again with 2.3.0 tomorrow when I have more DFI to work with.

**Comment by izzycsy** [comment]
Hi @NatetheGit , thanks for the feedback. It could be that there's too many transactions stuck in the same block, the solution for this would be to leave your app running for about 1–2 hours and let the app process your pending transactions.

You can check pending tx via CLI by typing:
`listtransactions`

**Comment by bmagierski** [comment]
I had the same issue earlier today. I think I solved it by ensuring that I had over 1.0 utxoDFI and then it worked. Try `getbalance` on the CLI and see if you have more than 1.0. Not sure why ... but I was able to stake to my ETH-DFI pool after that on v2.3 on the Mac.

**Comment by Capswiss** [comment]
I had the same issue since my update on 2.3.0 before 3 Days, when I try to add Liquidity. I can send tokens or Change in DEX whiteout Problems. Only Add Liquidity show this error message.
Also since the update, my Wallet BTC-DFI can't show transactions... it show the text, no transactions available. On my other Computer with the app 2.1.7, there it shows the transactions. Also there I can add Liquidity without problems.

**Comment by helhimm** [comment]
tried to remove which is ok, qdding does not work after, same error message

**Comment by NatetheGit** [comment]
I got the same error again today. Sending DFI to wallet to a second address to the same wallet worked. It seems that it's really a problem with needing to convert DFI Token to DFI coin before adding to liquidity.

I still look at this as a bug as I shouldn't have to send DFI to myself to force a conversion from token to coin just to do any transactions. But I'm going to just accept that that's what I have to do for now.
