### ISSUE TITLE
Many Problems after install DeFi App 2.3.0 WIN 10, sync OK, but after backup setback every time

### ISSUE THREAD

**Issue by Geldmax** [DeFiCh/app#573]
[logs.zip](https://github.com/DeFiCh/app/files/6053951/logs.zip)

Problems after app installation 2.3.0 (from 2.1.17). System: WIN 10 (20H2, Build 19042.844). Two attempts behind me, once installed via the old app over it, once completely deleted and uninstalled everything and yet the problem remains the same! After starting the app and synchronizing and then importing the backup, the wallets will probably be displayed correctly for a few seconds, then all go to "0", except for the DFI wallet. The app then reverts to the state it was in after a new installation and expects me to upload the process again with NEW wallet, SEED or backup! The way via the SEED also brought exactly the same result and I am therefore going in circles. With the command "gettokenbalances" in the CLI, the wallet values   are shown to me, which was not the case with some backups. I tried about 7 backups, including one that I was able to create shortly after installing and starting version 2.3.0. Unfortunately the same result at the end, except that the tokens are displayed as described. Wallets were never encrypted, ALL blocks were synchronized at that point! Who of the programmers can please help me? What I noticed is that the backup files are of different sizes from before the installation to after the installation (backup approx. 1/3) I just keep coming back to this screen ......

**Comment by izzycsy** [comment]
Hi @Geldmax , thanks for your feedback. Did you try using restore via `wallet.dat`? For Windows, the file is located here: 

Windows — C:`  \Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat`

<img width="626" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/109381459-8e15ce80-7915-11eb-8b89-3e4715bdec78.png">

**Comment by Geldmax** [comment]
JJ help me wonderful, many thanks!

**Comment by Geldmax** [comment]
Thank you very much, JJ and izzycsy
