### ISSUE TITLE
Not enough UTXO DFI to cover transaction fees

### ISSUE THREAD

**Issue by nordi6000** [DeFiCh/app#574]
Not enough UTXO DFI to cover transaction fees. Please send a few DFIs from an exchange or other wallet to this address and try again.
![image](https://user-images.githubusercontent.com/49670309/109385141-efc44180-78f1-11eb-8743-85b15b30b1ef.png)

I have enough DFI to send.
![image](https://user-images.githubusercontent.com/49670309/109385001-e8506880-78f0-11eb-9a18-bd1626485f02.png)

I tried the error description for changing DFI-Token to DFI-Coin. But that doesn't work.
![image](https://user-images.githubusercontent.com/49670309/109385083-7cbacb00-78f1-11eb-8cd5-f2ef59a182f1.png)

#### What are your environment parameters?

- DeFi App Version: 2.3.0
- Operating System (OS): Windows

**Comment by bmagierski** [comment]
This might help. https://github.com/DeFiCh/app/issues/563

Perhaps try only 1.0@DFI in the `accounttoutxos` command. It seems you need a minimum of 1.0 utxoDFI to do a transaction. You only have 0.012 per the `getbalance` command above.

**Comment by nordi6000** [comment]
@bmagierski  I have send DFI from Cake. Now I have 4.8 DFI In my getbalance
![image](https://user-images.githubusercontent.com/49670309/109399068-ca125900-7940-11eb-9a21-d5e21b9d8e35.png)

But it is still not sending my DFI

**Comment by nordi6000** [comment]
When I shut down the wallet and restart. My transaction is in progress.
If I then want to do another transaction, the same error occurs again.
![image](https://user-images.githubusercontent.com/49670309/109531225-eb498580-7ab7-11eb-8abe-780f87d26973.png)

**Comment by izzycsy** [comment]
Hi @nordi6000 , thanks for your feedback, please give us time to investigate this issue. In the 2nd screenshot, was your `getbalance` at least 1 DFI?

**Comment by nordi6000** [comment]
[AppLog.log](https://github.com/DeFiCh/app/files/6066431/AppLog.log)
[BinaryLog.log](https://github.com/DeFiCh/app/files/6066432/BinaryLog.log)

**Comment by izzycsy** [comment]
Hi @nordi6000 , may I have the output of `listaccounts {} false false true`, this list accounts that belongs to you. I would like to understand how many address & DFI on that address you've. You may mark X for the unrequested information, or only include the addresses with DFI.

```
listaccounts {} false false true
[
  {
    "key": "X@2",
    "owner": "SDAELFRUMvBFcVhAMBnUEV4rCa2dzQ5y1",
    "amount": "X@BTC"
  },
  {
    "key": "X@0",
    "owner": "dTmhZjsYgZL1ayLwrgGkaGXoSccXc8zRGM",
    "amount": "123.456@DFI"
  },
  {
    "key": "X@1",
    "owner": "dTmhZLASHs8kaGXoSccXc8zRGM",
    "amount": "X@ETH"
  },
```

**Comment by nordi6000** [comment]
Hi @izzycsy here my listaccounts...
![image](https://user-images.githubusercontent.com/49670309/109994116-49bb7180-7d0d-11eb-95ad-e19e21cf077f.png)

**Comment by izzycsy** [comment]
Hi @nordi6000 , thank you. It looks like you've 2 addresses with DFI. 
Address 1: `dKpa...`
Contains: DFI, ETH, ETH-DFI, BTC, BTC-DFI

Address 2: `dYH5...`
Contains: DFI, LTC, LTC-DFI

You can send 1DFI to either addresses when making your related tx. This action will convert your accountDFI to utxoDFI, uxtoDFI is required for fees when performing any actions on the app.

**Comment by nordi6000** [comment]
@izzycsy Hi Bella, at the moment I have no problem with converting the DFI in the Wallet automaticly. 
All transaction are going out. 
If you like I can make Log file to evaluate the error.

Thanks for your help :-)

**Comment by izzycsy** [comment]
Hi @nordi6000 , thanks for the update, I'll close this issue in the mean time.
