### ISSUE TITLE
How to import backup or password phrases on 2.3.0?

### ISSUE THREAD

**Issue by thbestforyourbizdeployment** [DeFiCh/app#575]
How to import backup or password phrases on 2.3.0?
I create the new 1 password and I would like to import a backup wallet or enter the original list of phrases.
How can I do this on 2.3.0? @izzycsy

**Comment by izzycsy** [comment]
Hi @thbestforyourbizdeployment , attached is a screenshot on how to Restore from wallet backup (wallet.dat). Your wallet.dat would be located here: 

Windows — C: ` \Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat`

Mac — Go to Folder:  `/Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat`

<img width="1019" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/109541938-5a969800-7aff-11eb-839e-3fe1415022d7.png">

**Comment by thbestforyourbizdeployment** [comment]
> Hi @thbestforyourbizdeployment , attached is a screenshot on how to Restore from wallet backup (wallet.dat). Your wallet.dat would be located here:
> 
> Windows — C: ` \Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat`
> 
> Mac — Go to Folder:  `/Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat`
> 
> <img alt="Restore wallet from backup" width="1019" src="https://user-images.githubusercontent.com/65014479/109541938-5a969800-7aff-11eb-839e-3fe1415022d7.png">

You can close the case.  I was able to set up 2.3.0 on a Windows 10 PC. 
thanks for your help
