### ISSUE TITLE
Transactions are Missing: Problem with communication CLI, Defid.exe V2.3.0

### ISSUE THREAD

**Issue by jleidinger** [DeFiCh/app#576]
#### What happened:

1.  I  tried to run the "defid.exe" after I updated to version 2.3.0. During this time the DeFi App was closed. For the time this is running there are no rewards shown in the DeFi App. It seems that when the DeFi-App is running something is getting saved differently to when running the "defid.exe" in CLI.

2. Running in CLI listaccounthistory all {\"limit"\":1000000} some transactions only refering to DFI are missing in the CLI. As I can see, it occurs with the transactions types sent and receive. Might be the reason why it's only with DFI because the transactions of the other coins are token based.

#### What you expected to happen:
A fix that the two defid.exe and the DeFi-App are doing the same work without missing some transactions.

#### How to reproduce it (as minimally and precisely as possible):
I run the DeFi-App and close ist for 10 minutes then I start "defid.exe" from CLI. After the sync is up to date I close the CLI and open the DeFi-App again. Now during the 10 minutes there are no rewards are shown but newer ones are shown. You can see the data gap.

#### What are your environment parameters?

- DeFi App Version: 2.3.0
- Operating System (OS): Windows 10 Home

**Comment by izzycsy** [comment]
Hi @jleidinger , thanks for your feedback, please give us time to investigate this issue. 

/triage accepted

**Comment by jleidinger** [comment]
We just found the problem. My wallet.dat was not in the standard path. The DeFiApp uses this but the "defid.exe" opens a new wallet.dat in the standard path. So some data is in the one and same in the other wallet.dat.

The "defid.exe" should use the path that is defined in the "defi.conf"

**Comment by izzycsy** [comment]
Hi @jleidinger , thanks for your feedback, yes with the latest version v2.3.0, users can gain access to their wallet.dat files easier because we included optional encryption. Will convey your feedback to the team. Are you tx history appearing now that you've found your wallet.dat? The file routes for wallet.dat as follow: 

Windows — C:  `\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat`

**Comment by jleidinger** [comment]
Hi @izzycsy ,
I renamed and copied "wallet.dat" to the standard path. Then I changed it in "defi.conf" as well. It worked and after reindexing everything was fine ;)
