### ISSUE TITLE
Error on fresh macOS Catalina 10.15.7 older MacBook Pro "St13runtime_error DeriveNewChildKey: Writing HD chain model failed in AppInit()"

### ISSUE THREAD

**Issue by Geldmax** [DeFiCh/app#582]
![20210301_090445 1](https://user-images.githubusercontent.com/78381957/109619713-6606b500-7b39-11eb-9089-9701be67909a.jpg)
DeFiApp Version 2.3.0
Fresh MacOS 10.15.7 System on older MacBook Pro (end 2008). 

After Installation DeFi App on fresh system the blockchain load on evening over 85%, after night the display shows only 70% an I see at any time "corrupt blocks", I mean. After restart system and App the error
"St13runtime_error DeriveNewChildKey: Writing HD chain model failed in AppInit()"

picture follows.

Is this a HDD error, but system was checked no error.

[Archiv.zip](https://github.com/DeFiCh/app/files/6067118/Archiv.zip)

**Comment by thedoublejay** [comment]
@Geldmax This error might be happening if you don't have enough disk space. Can you check if your machine has enough disk space?

**Comment by Geldmax** [comment]
Is more then enough disk space! 214,77 GB free.... But after start the Mac, I have mistake on display yet. I will post this

**Comment by Geldmax** [comment]
hard disk test ok. But error from restart here.
[Fehler Mac.zip](https://github.com/DeFiCh/app/files/6074142/Fehler.Mac.zip)

**Comment by Geldmax** [comment]
After systemcheck and HDD check, delete the Folders (anchors, blocks, recovered files and file wallet_map.json), restart an new install DeFi App 2.3.0 and load the blockchain (third time) the DeFi App is functuionally! Blockchain load mor then 20 hours, this is not ok!
