### ISSUE TITLE
Remove Liquidity: Insufficient funds

### ISSUE THREAD

**Issue by Bomaestro** [DeFiCh/app#586]
#### What are your environment parameters?

- DeFi App Version:
- Operating System (OS):

**Comment by Bomaestro** [comment]
[Uploading defi-app.zip…]()

**Comment by Bomaestro** [comment]
[defi-app.zip](https://github.com/DeFiCh/app/files/6068844/defi-app.zip)

**Comment by Bomaestro** [comment]
@defichain-bot I hope if i upload this you can help me

**Comment by Bomaestro** [comment]
@defichain-bot 
![Képernyőfelvétel (1)](https://user-images.githubusercontent.com/79913956/109693164-a4c45b80-7b89-11eb-9775-e39ee5940ff8.png)

**Comment by thedoublejay** [comment]
@Bomaestro your wallet looks locked. Can you try to unlock it first then do the transaction?

**Comment by izzycsy** [comment]
Hi @Bomaestro , it could be that you've insufficient utxoDFI balance (min. 1DFI) — which is required to perform swap and other functions. 

utxoDFI is used to pay for transactions fees while rewards received are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. To convert accountDFI to utxoDFI, the simplest way is to send DFI from your `receive address B` to your `receive address A`, the app will automatically convert for you. Try sending yourself 1 DFI and try the function again.

You can check your DFI balance with the following commands via CLI:
`getbalance` — utxoDFI
`gettokenbalances` — accountDFI

The sum of utxoDFI & accountDFI would be your total tokens.

**Comment by Bomaestro** [comment]
Thank you for your help! My problem is solved
