### ISSUE TITLE
send DFI from app to cake, still pending

### ISSUE THREAD

**Issue by suelbph** [DeFiCh/app#589]
#### How to reproduce it (as minimally and precisely as possible):
sent yesterday DFI from app to cake. it is still pending.
Did i sth wrong? why does it take so long?
fe2bcbd28b13b4aefd3afbec2c50ae82fe9b215ce6433511e4c6c554ee69cef0
thx for your support

#### What are your environment parameters?

- DeFi App Version: 2.3.0
- Operating System (OS): Win10

**Comment by izzycsy** [comment]
Hi @suelbph , it seems that your tx [got through](https://mainnet.defichain.io/#/DFI/mainnet/tx/fe2bcbd28b13b4aefd3afbec2c50ae82fe9b215ce6433511e4c6c554ee69cef0). I'm not sure how long does it take for your balance to be reflected on Cake, you might want to enquire in[ CakeDeFi Telegram (EN)](https://t.me/CakeDeFi_EN).

**Comment by suelbph** [comment]
ok thanks :)

**Comment by suelbph** [comment]
i was going automatically in the staking ;)
