### ISSUE TITLE
Forgotten passphrase

### ISSUE THREAD

**Issue by rickcys** [DeFiCh/app#591]
#### How to reproduce it (as minimally and precisely as possible):

1. I open my DefiChain wallet app
2. I want to perform a conversion in DEX from my BTC to USDT
3. The error message said insufficient DFI token.
4. I buy DFI token at cake and withdraw to DefiChain app wallet which makes it my DFI wallet total value is equivalent of 2.6 DFI.
5. I tried to perform conversion in DEX from BTC to USDT again. 
6. I failed again due to insufficient DFI token.
7. I exited the Defichain app wallet and wait until it closed itself automatically. I didn't perform any force close.
8. I entered Defichain app wallet again
9. I login to Defichain app wallet by inserting my passphrase. Sadly, it failed to login. It mentioned, "Wrong Passphrase."

#### What are your environment parameters?

- DeFi App Version:
- Operating System (OS): 2.3.0.

#### Anything else we need to know?:

[app log.zip](https://github.com/DeFiCh/app/files/6076817/app.log.zip)

**Comment by izzycsy** [comment]
Hi @rickcys , thanks for your feedback, please give us time to investigate this issue.

**Comment by rickcys** [comment]
![image_2021-03-04_113558](https://user-images.githubusercontent.com/78590540/109907695-c9c9e300-7cdd-11eb-977d-52e1bcf9ed7c.png)

Here you go

**Comment by izzycsy** [comment]
Hi @rickcys , the team has investigated and it's highly likely that you have forgotten your passphrase, can you try again? There's no limit to trying. Unfortunately, there's no way to retrieve your passphrase if you lose it, likewise for your mnemonic seed. 

Alternatively you can try to `Restore from mnemonic seed`, so your unencrypted wallet will be loaded and encrypt again — but if you did anything when your encryption was active, then you might lose those transactions.

**Comment by rickcys** [comment]
what do you mean by losing those transaction if I perform mnemonic seed restoration? Will the BTC inside still be there?

**Comment by izzycsy** [comment]
Hi @rickcys , if you did any transactions between when you start your passphrase and then when it became locked, those transaction are contained in between that period, and is saved in your wallet.dat. Hence, we suggest that you try and remember your passphrase. Could it be that you mis-typed 1 alphabet or capitalised one letter? Please try to remember.

**Comment by rickcys** [comment]
Alright. Thank you.

**Comment by izzycsy** [comment]
Hi @rickcys , update [v2.3.1](https://github.com/DeFiCh/app/releases/tag/v2.3.1) is out.   I'll be closing this issue in the mean time, thank you.
