### ISSUE TITLE
[Proposal / Api Feature Request] Add totalLiquidityLpToken attribute to listyieldfarming response

### ISSUE THREAD

**Issue by Shelkovenkov** [DeFiCh/app#596]
#### What would you like to be added:
API
Please add totalLiquidityLpToken attribute to listyieldfarming response actual only in getpoolpair response
#### Why is this needed:
I use the getpoolpair and listyieldfarming endpoints for my site defichain-income and so for each pool to calculate the pool share I need to make a separate request for each pool to get the totalLiquidityLpToken attribute. If it was in the listyieldfarming response, I would save the separate calls and get all the info with one listyieldfarming call.

**Comment by izzycsy** [comment]
Hi @Shelkovenkov 	, update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

The above feature is not included in this update, this is comment to notify you about the update. 

By the way, you can post your passion projects on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/show-and-tell), to gain more awareness and share with the community!
