### ISSUE TITLE
Beschädigte Block-Datenbank entdeckt!

### ISSUE THREAD

**Issue by Fabio129** [DeFiCh/app#597]
Seit enormer Zeit versuche ich mit Neuinstallation und immer wieder einem Neustart meine App zum laufen zu bringen. Leider komme ich in die App durch beschädigte Blog-Datenbank (siehe Bild) nicht rein. ￼￼￼

Da ich aber gerne über meinen Computer arbeiten möchte mit dieser App wäre es super wenn Sie mir dabei helfen können, dass diese wieder funktioniert. ￼ auf einem anderen Endgerät funktioniert meine Wallet nur möchte ich es lieber auf meinem eigenen Computer haben. 

Ich hoffe Sie können mir dabei helfen.

Mit freundlichen Grüßen 

Fabio Kuhn

 ![image](https://user-images.githubusercontent.com/77388401/109986394-fb56a480-7d05-11eb-9f46-2ef5bc18b0cb.jpeg)￼￼

**Comment by supervolot** [comment]
Ich hatte die Fehlermeldung auch schon. Ich habe "delete peers an blocks" deaktiviert und dann die Wallet neu gestartet. Sicherheitshalber solltest du vorher noch die wallet.dat sichern. Wenns über die App nicht mehr geht dann manuell. 
Hast du -reindex schon probiert ?

**Comment by izzycsy** [comment]
Hi @Fabio129 , thanks for your feedback, please give us time to investigate this. If you click on the `Restart app` button, and it appears again, please refer to this issue [`Loop: Corrupted block database detected. Please restart with -reindex or -reindex-chainstate to recover. Do you want to restart?`](https://github.com/DeFiCh/app/issues/560), we can further discuss on the problem there. We would like to keep same issues in one thread. Kindly send your app logs there. Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/110236676-204f4f80-7f72-11eb-8a06-0a99e4f9c7d8.png">

<img width="511" alt="2 Komprimiere" src="https://user-images.githubusercontent.com/65014479/110236677-247b6d00-7f72-11eb-894c-ebb085656769.png">


In the mean time, please make a backup of your wallet.dat and keep it safe. You may find the files here: 
Windows — C:  \Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat

Mac — Go to Folder:  /Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat
