### ISSUE TITLE
creation masternode doesn´t work

### ISSUE THREAD

**Issue by supervolot** [DeFiCh/app#599]
#### What are your environment parameters?

- DeFi App Version: 2.3
- Operating System (OS): WIN10

**Comment by thedoublejay** [comment]
@supervolot Hi, we disabled it for v2.3.0 due to some issues that are still existing on the app. It will be enabled again on the upcoming v2.3.1 version. We have added this note on the release notes for v2.3.0 - https://github.com/DeFiCh/app/releases/tag/v2.3.0

**Comment by supervolot** [comment]
@thedoublejay Hi, ok then please modifi your release notes because _"Masternode management through the app is still in development, masternode creation has been disabled and will be re-enabled in a coming release on **Monday**"_ is confusing.

**Comment by thedoublejay** [comment]
Hi @supervolot, thanks for pointing out. I updated it already. We're still testing the next app release but it will be out soon.
