### ISSUE TITLE
Win10: Masternode is missing

### ISSUE THREAD

**Issue by supervolot** [DeFiCh/app#602]
#### How to reproduce it (as minimally and precisely as possible):
TX = e4335c1f31695d5f4676db6b34017943c5f4698dda335a3189384ab4f7dedaaf
![defi_bug_v2 3 1_05 03 2021](https://user-images.githubusercontent.com/59117793/110105580-d9fac480-7da8-11eb-8082-b3026fed976f.JPG)
![defi_bug_v2 3 1_05 03 2021](https://user-images.githubusercontent.com/59117793/110105616-e67f1d00-7da8-11eb-82a0-95a5003d3d65.JPG)

#### What are your environment parameters?

- DeFi App Version: 2.3.1
- Operating System (OS): WIN 10

**Comment by supervolot** [comment]
The "masternode will have an auto-lock timeout of 3 years (max timeout available) until you close the app or lock it" don´t work at my v2.3.1 WIN10, or the wallet don´t check that the masternode is enable !? Is there a way to deactivate the auto-lock manuel ?

**Comment by supervolot** [comment]
i just check "getmintinginfo" and the note in enable. the masternode_operator id = 8YSNU3ukCS5pGDQQUjsj4ppzb9onuM3iCB is also in the masternode list. But the wallet dont show the masternode. It look like when i klick "mine" a mili second are all nodes shown and then all masternods be filtert out?

**Comment by supervolot** [comment]
I also checked the Log defi.conf file. Here is somthing weard the logfile shows masternode_operator[]=8YSNU3ukCS5pGDQQUjsj4ppzb9onuM3iCB
but the defi.conf is correct !

**Comment by supervolot** [comment]
My Masternode just mined a block, so the bug belongs only the vierwing of the active masternode on the masternode frame.

**Comment by Martin8617** [comment]
I have the same issue at self-generated AppImage 2.3.1 (defid 1.5.1).
I made the MN in the console instead using the create buttom. --> How to get the MN shown in the App at Masternode "mine"?

**Comment by izzycsy** [comment]
Hi @supervolot @Martin8617 , thanks for your feedback. Can you send your app logs and current screenshot of your Masternode screen? I assume it's still blank. Please refrain from deleting any files that are you're unfamiliar with for your safety and security, our team is constantly working on improving the app and solving its issues.

**Comment by izzycsy** [comment]
Hi @supervolot @Martin8617 , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

The above feature / issue is not included in this update yet, this is comment to notify you about the update.
