### ISSUE TITLE
Wallet Transactions are not up to date

### ISSUE THREAD

**Issue by supervolot** [DeFiCh/app#605]
#### How to reproduce it (as minimally and precisely as possible): 

 After install the app v2.3.1 i make a masternode, after restart the app the node dont work,. a compleat rescan did not help.

#### What are your environment parameters?

- DeFi App Version: 2.3.1
- Operating System (OS): WIN10

**Comment by Kittylesen** [comment]
Hi,
I have the same problem. I cannot proceed with an update.
I stopps by 98,35% of synchronisation.

![Bildschirmfoto 2021-03-06 um 14 46 40](https://user-images.githubusercontent.com/76268493/110209198-61b8ff80-7e8b-11eb-898a-5514aa01a37d.png)


Which files should I provide?:
- app_config
- binary_log
- - app_log?


Thank you in advance

**Comment by izzycsy** [comment]
Hi @Kittylesen , thanks for your feedback, regarding the issue [`Win: sync 95% > Node is disconnected`](https://github.com/DeFiCh/app/issues/546), if your issue persist, we can further discuss on the problem there. Let’s keep this thread related to what the original author opened. From your screenshot it seems you just have to leave the app running and it should sync to 100%. It took me about 2 hours to sync as well. The team is preparing a better sync solution in the later releases, but for now we seek your patience in waiting for the blocks to sync. Thank you for your understanding.

**Comment by izzycsy** [comment]
Hi @Kittylesen , thanks for your feedback, regarding the issue [`Win: sync 95% > Node is disconnected`](https://github.com/DeFiCh/app/issues/546), if your issue persist, we can further discuss on the problem there. Let’s keep this thread related to what the original author opened. From your screenshot it seems you just have to leave the app running and it should sync to 100%. It took me about 2 hours to sync as well. The team is preparing a better sync solution in the later releases, but for now we seek your patience in waiting for the blocks to sync. Thank you for your understanding.

**Comment by izzycsy** [comment]
Hi @supervolot , update [v2.3.1](https://github.com/DeFiCh/app/releases/tag/v2.3.1) is out. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please leave a comment with new information (include screenshots) and app logs. Thank you.

**Comment by Kittylesen** [comment]
Hi @izzycsy,
unfortunately the app still doesn´t work and the sync is lasting for more than 24h... without any progress. The second problem is that I cannot even transfer the DFIs from the app to Cake.

I am waiting for the update v2.3.1 as described by _**supervolot._**

Best regards and have a nice day

**Comment by izzycsy** [comment]
Hi @supervolot @Kittylesen 	, update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating. 

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
