### ISSUE TITLE
App 2.3.1 freeze at first start 

### ISSUE THREAD

**Issue by supervolot** [DeFiCh/app#606]
#### What are your environment parameters?

- DeFi App Version: 2.3.1
- Operating System (OS): WIN10

#### Anything else we need to know?:

Seems like an bug at the checkupdates IPC renderer
[2021-03-06 17:43:14.811] [IPC-RENDERER-error] [startBinary] "Cannot set property 'nodeVersion' of undefined"
[2021-03-06 17:43:14.825] [IPC-RENDERER-info]  [Blockchain Status] {"success":false,"data":{}}
[2021-03-06 17:43:14.836] [IPC-RENDERER-error] [blockChainNotStarted - Not Running] ""
[2021-03-06 17:43:17.833] [IPC-RENDERER-info]  Update for version 2.3.1 is not available (latest version: 2.3.0, downgrade is disallowed).
[2021-03-06 17:43:17.845] [IPC-RENDERER-debug] checkForUpdatesAndNotify called, downloadPromise is null

**Comment by supervolot** [comment]
[defilog.log](https://github.com/DeFiCh/app/files/6095711/defilog.log)

**Comment by izzycsy** [comment]
Hi @supervolot , thanks for your feedback. v2.3.1 is not officially released yet, please wait for the official announcement on [DeFiChain Announcements (EN)](https://t.me/defichain_announcements).

**Comment by supervolot** [comment]
Hi @izzycsy i have the same problem at v2.3.0

**Comment by supervolot** [comment]
@izzycsy i have a soloution = just run one time the the defid.exe (v.1.5.1) then the app v2.3.1 is running again.

**Comment by thedoublejay** [comment]
@supervolot  I have added some fix with v2.3.1 for the error in your logs. I'll let you know once we have released v2.3.1 and you can retry.

**Comment by Stonygan** [comment]
I have the same problem with 2.3.1, nothing happens after start. Te solution to start first defid.exe 1.5.1 helps. Following error occur when start the APP on a new system:

[2021-03-10 14:01:54.531] [IPC-MAIN-error] Error: ENOENT: no such file or directory, open 'C:\Users\xxx\AppData\Roaming\DeFi Blockchain\wallets\wallet_map.json'

When i start 1.5.1 first, some files and folders are created and with the start of the APP, the APP creates a new wallet_map.json without error and start.

Maybe it helps.

**Comment by RobinTorque** [comment]
There is a problem with version 2.3.1

If the app is not installed as an update, but the first time on a new system, then the blockchain folder is not created and the app cannot start. 

The problem and the fix is documented here.
https://defichain-wiki.com/wiki/V2.3.1#Known_bugs_with_this_version

**Comment by izzycsy** [comment]
Hi @supervolot @Stonygan @RobinTorque , the team has halted v2.3.1 at the moment due to some issues. I'll update you again when the team fixes it and is ready for release.

**Comment by RobinTorque** [comment]
hi @izzycsy , this problem also exists in V2.3.0

**Comment by Mabarkubus** [comment]
I'm having the same problem, de-installed the v2.3.1, deleted the files and installed v2.3.0, but it's the same behavior. What do we have to do? Still wait???

**Comment by izzycsy** [comment]
Hi @Mabarkubus , yes wait. The issue may exist on v2.3.0. Please keep your passphrase & wallet.dat safe in the mean time.

**Comment by izzycsy** [comment]
Hi @supervolot @Mabarkubus , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
