### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#607]
I received an error message that is not correct. 

![210306 1812](https://user-images.githubusercontent.com/65536965/110215099-4d373000-7ea8-11eb-9f3a-94d010445e22.PNG)
Error message in English: Not enough UTXO DFI available for transaction fees. Please send some DFI from an exchange or another wallet to this address and try again. 

I waited only a few seconds and after that the transaction worked. So it is not possible that there were too few UTXO. 

[210306 Robin Logs.zip](https://github.com/DeFiCh/app/files/6095764/210306.Robin.Logs.zip)

**Comment by Fabialfonso** [comment]
Hi, I get the same error even though the holding amount should be fine:

getbalance
2.28684901
gettokenbalances
[
  "16.67900911@0",

I also tried the https://defichain-wiki.com/wiki/How_to_%22rescue%22_stuck_DFI recommanded soltution but it seems it doesn't work anymore with the passphrase activated. Please help

**Comment by Fabialfonso** [comment]
> Hi, I get the same error even though the holding amount should be fine:
> 
> getbalance
> 2.28684901
> gettokenbalances
> [
> "16.67900911@0",
> 
> I also tried the https://defichain-wiki.com/wiki/How_to_%22rescue%22_stuck_DFI recommanded soltution but it seems it doesn't work anymore with the passphrase activated. Please help

 OK Now after several restarts of the app it worked.... very strange

**Comment by izzycsy** [comment]
Hi @Fabialfonso , it’s likely that you've insufficient utxoDFI balance (min. 1 DFI) — which is required to perform swap and other functions. DFI exist in 2 forms; **utxoDFI** and **accountDFI**. utxoDFI is used to pay for transactions fees while rewards received are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. To convert accountDFI to utxoDFI, the simplest way is to send DFI from your `receive address A` to your `receive address A`, the app will automatically convert for you.

**Comment by izzycsy** [comment]
Hi @Fabialfonso , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

The above feature / issue is not included in this update yet, this is comment to notify you about the update.

**Comment by izzycsy** [comment]
Hi @RobinTorque , the team is aware of this issue and are in discussion to improve the UX of utxoDFI. I'll be closing this issue in the mean time. Thank you.
