### ISSUE TITLE
Can't Exchange DFI for other coins

### ISSUE THREAD

**Issue by jonho79** [DeFiCh/app#608]
Hi,

I'm using the DEX to try to transfer DFI to USDT, BTC and ETH and I keep on getting this error:

"Insufficient UTXO DFI for transaction fees. Please send some DFI from an exchange or another wallet and try again"

Is this because I have insufficient DFI coin?  I remember that there is a way to exchange coin to token but i can't seem to locate the post any more?  Thanks

**Comment by supervolot** [comment]
Hi @jonho79 perhaps this link help: https://defichain-wiki.com/wiki/How_to_%22rescue%22_stuck_DFI  but it seems that the wallet 2.3.1 has some bugs, i had the same problem, but at the second try it worked. Just take a look at #607

**Comment by izzycsy** [comment]
Hi @jonho79 , DFI exist in 2 forms; **utxoDFI** and **accountDFI**. utxoDFI is used to pay for transactions fees while rewards received are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. To convert accountDFI to utxoDFI, the simplest way is to send DFI from your `receive address B` to your `receive address A`, the app will automatically convert for you.

**Comment by jonho79** [comment]
Thanks for the solution.  I ended up closing and restarting the app, and
all transactions started working again.

**Comment by izzycsy** [comment]
Hi @jonho79 , thanks for the update! I'll close this issue in the mean time.
