### ISSUE TITLE
No Inbound connections to 8555

### ISSUE THREAD

**Issue by Martin8617** [DeFiCh/app#609]
#### What happened:
I'm not able to allow inbound connection.
If I check at https://bitnodes.io/nodes/77.56.65.5-8555/  connection is down

#### What you expected to happen:
After opening port 8555 in the router I expected to have inbound connections.

#### How to reproduce it (as minimally and precisely as possible):
1. opened port 8555 in router
2. deactivated firewall at PC (anyway port 8555 is opened in firewall)
3. started / restarted node with automatic defined defi.conf
4. only 8 outbound connections
4. found errors in debug.log
5. checked if DeFi Blockchain is running somewhere - nothing found
6. checked who is using port 8555 (lsof -i TCP / sudo netstat -apv) - nothing found

#### What are your environment parameters?
- DeFi App Version:            AppImage 2.3.1
- Operating System (OS):   MX Linux 18.3 (based on Debian Stretch)
- Kernel:                              Linux 4.19.0-5-amd64 (x86_64)
- RAM usage:                      3.8GB of 7.7GB
- HD Storage size:               Root: 112GB of 245GB

#### Anything else we need to know?:
1. port forwarding is made the same way for 8555 as for 8333, however 8333 works fine
2. error messages from debug.log. Writing just in the first line the "...Ignoring configuration...":
    2021-03-06T07:34:59Z Ignoring unknown configuration value rpcconnect
    ...
    2021-03-06T07:35:06Z  block index            7180ms
    2021-03-06T07:35:06Z ERROR: CBlockPolicyEstimator::Read(): up-version (149900) fee estimate file
    2021-03-06T07:35:06Z init message: Loading wallet...
    ...
    2021-03-06T07:35:06Z torcontrol thread start
    2021-03-06T07:35:06Z Bound to [::]:8555
    2021-03-06T07:35:06Z Unable to bind to 0.0.0.0:8555 on this computer. DeFi Blockchain is probably already running.
    2021-03-06T07:35:06Z init message: Loading P2P addresses...
    ...

3. configuration of defi.conf:
    maxconnections=32
    rpcauth=w...........................
    rpcuser=w............
    rpcpassword=a.........................
    testnet=0
    regtest=0
    masternode_owner=8............
    rpcconnect=127.0.0.1

    [main]
    wallet=wallet.dat
    walletdir=/root/.defi
    rpcbind=127.0.0.1
    rpcport=8555
    gen=1
    spv=1
    masternode_operator=8.....................

    [test]
    rpcbind=127.0.0.1
    rpcport=8555

**Comment by Martin8617** [comment]
Attached the port 8555 find by 'sudo lsof -i TCP'
[Ports 8555.zip](https://github.com/DeFiCh/app/files/6097512/Ports.8555.zip)

**Comment by izzycsy** [comment]
Hi @Martin8617 , thanks for your feedback. Please give us time to investigate this.

**Comment by izzycsy** [comment]
Hi @Martin8617 , the issue might be with your connection. The team's feedback is that their connection is working fine. I'll be closing this issue in the mean time, thank you for your patience.
