### ISSUE TITLE
Masternode Count wrong

### ISSUE THREAD

**Issue by Stonygan** [DeFiCh/app#610]
Open Issue in APP, closed in AIN. #### What happened: Tab Masternodes shows only 898 enabled Masternodes. Maybe the default value from listmasternodes of 1000 is used to display.

#### How to reproduce it (as minimally and precisely as possible):
Open Wallet, click Tab Masternodes

#### What are your environment parameters:
Windows, APP-Version 2.3.0

#### Anything else we need to know?:
It seems same behaviour in MAC APP, some Users reported in Telegram.

![mn_count](https://user-images.githubusercontent.com/44975826/109874005-d105d800-7c6e-11eb-8da5-d572783907bf.jpg)

__Originally posted by @Stonygan in https://github.com/DeFiCh/ain/issues/260__

**Comment by monstrobishi** [comment]
Yes you are correct, we are limiting to 1000, thanks for reporting this
