### ISSUE TITLE
Conflicting information at MN

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#611]
I have installed a masternode in the testnet. Everything looks good on the graphical interface. 

![image](https://user-images.githubusercontent.com/65536965/110254413-53540c00-7f8f-11eb-9150-d522a6d3d4b8.png)

![image](https://user-images.githubusercontent.com/65536965/110254424-61099180-7f8f-11eb-9a61-2c8377e74ba9.png)

![image](https://user-images.githubusercontent.com/65536965/110254433-6bc42680-7f8f-11eb-91a2-4e12db5e4469.png)

The information in the console, however, shows a different result. 
I have not found a block yet. 

[210307 Robin Logs.zip](https://github.com/DeFiCh/app/files/6097946/210307.Robin.Logs.zip)

**Comment by thedoublejay** [comment]
Hi @RobinTorque, in your config I cannot see the masternode configs existing. After you created the masternode in the app, have you modified the defi.conf somehow?

**Comment by RobinTorque** [comment]
Hi @thedoublejay , no, I have not changed anything. My error message refers less to the fact that the MN does not work. I wanted to point out that the MN does not work, but the user interface tells the user that everything is fine. This is a problem from my point of view, because the user must be able to rely on the information in the user interface. 

Bella has the access data to my Windows test computer.

**Comment by thedoublejay** [comment]
@RobinTorque  Yes, we have added a fix for this. Will be included in 1.3.1. I think we're missing a feature to enable/disable masternode in case it is created but not on config. Thanks for raising this issue.

**Comment by RobinTorque** [comment]
I think this problem is solved with the new version and the issue can be closed. 

Thanks a lot @izzycsy 

<img width="742" alt="Bildschirmfoto 2021-03-11 um 10 34 17" src="https://user-images.githubusercontent.com/65536965/110766362-5d0e9580-8255-11eb-9299-83b47244ef77.png">
