### ISSUE TITLE
AppImage running as root without --no-sandbox is not supported

### ISSUE THREAD

**Issue by Martin8617** [DeFiCh/app#614]
#### What happened:
I'd like to start the AppImage (defi-app-2.3.1.AppImage)
However this is not easy. May be their is a fault on the Image or I have missing information.

#### What you expected to happen:
I expected to start the defi-app-2.3.1.AppImage just by clicking it as user without error messages.

#### How to reproduce it (as minimally and precisely as possible):
[AppImage.zip](https://github.com/DeFiCh/app/files/6101707/AppImage.zip)

#### What are your environment parameters?
- DeFi App Version: AppImage 2.3.1
- Operating System (OS): MX Linux 18.3 (based on Debian Stretch)
- Kernel: Linux 4.19.0-5-amd64 (x86_64)
- RAM usage: 1.2GB of 7.7GB
- HD Storage size: Root: 431GB of 914GB

#### Anything else we need to know?:
What I see is, sandbox needs root access for tmp/.mount_defi..., however sandbox is not allowed under root access. This is the point where the cat bits itselfs in the tail.

I have an AppImage running on the other Linux-PC with the same behaviour, but maybe error ((defi-app:10627): libnotify-WARNING **: 13:30:17.697: Failed to connect to proxy) I get on that terminal has to do with the missing sandbox. See my other issue #609.

**Comment by izzycsy** [comment]
Hi @Martin8617 , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you

**Comment by Martin8617** [comment]
Hi Bella, the problem isn't related to 2.3.1. 
I had it with 2.3.0 too. Please find the logs from the DeFi-Wallet-2.3.2.AppImage - it's the same.

Additional information: The libnotify-warning: Failed to connect to proxy occurs when I open the wallet with the password (wallet works even with this warning...)

Remark to the closed issue #609:
I just use the DeFi-Wallet for the MN-Owner now. MN-Operator runs with defid 1.6.1 without change of firewall or network settings with inbound connection. I believe the use of "no-sandbox" has influence of the rpc configuration (see debug-app.log) as well as of the blocking of inbound connection.
[200402.zip](https://github.com/DeFiCh/app/files/6248341/200402.zip)

**Comment by bvbfan** [comment]
I see blockchain works, libnotify is engine for showing desktop notifications it does not have anything related to the blockchain, it's a part of Electron. `--no-sandblox` is required when you run as root, why you want to do that?

**Comment by izzycsy** [comment]
Hi @Martin8617 , the team as investigated your logs, the [error](https://github.com/DeFiCh/app/issues/609) you faced `2021-04-02T06:53:58Z Unable to bind to 0.0.0.0:8555 on this computer. DeFi Blockchain is probably already running` did your app start?

**Comment by bvbfan** [comment]
The normal permissions of /tmp are drwxrwxrwt so that's mean 1777 changing them makes you a responder. So you should take this personally and solve it for you.

**Comment by Martin8617** [comment]
@bvbfan, I have an idea what you mean, however I don't know who to solve this permission issue...

**Comment by izzycsy** [comment]
Hi @Martin8617 , [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a **mandatory update**. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Martin8617  [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**. Please read through the release notes before updating. _This comment is to notify you about the update._ 

Posting non-bug related issues here will eventually turn stale. For future Linux related post (if it's not a suspected bug) you can post your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), share your findings with the community. In the mean time, I'll provide a link to [Linux: Running the app as a webapp #736](https://github.com/DeFiCh/app/discussions/736) , there are other community members in discussion on an idea that might be related.
