### ISSUE TITLE
Feat | Add liquidity: Show how many liquidity tokens will be added

### ISSUE THREAD

**Issue by tame81** [DeFiCh/app#616]
#### What would you like to be added:
When adding liquidity to a pool, it would be very nice to see beforehand how many liquidity tokens one will receive in exchange.

#### Why is this needed:
This is needed for proper tax calculation.

**Comment by RobinTorque** [comment]
Hi @tame81 
You can easily work it out yourself. Square root(Coin1xCoin2)=Number of liquidity tokens.

**Comment by tame81** [comment]
I know @RobinTorque, but that's not very convenient to do every time. I suggest displaying it in the summary page before the confirmation.

**Comment by izzycsy** [comment]
Hi @tame81 , the team has added a CSV export feature in the app to assist in your tax calculation. When you add liquidity, the app displays how much is your pool-pair tokens before you add liquidity. I'll let the team know of your feedback for it to be considered. Can you elaborate more on what kind of enhanced feature you're referring to?
