### ISSUE TITLE
DFI transaction from 1 adress to another in same wallet

### ISSUE THREAD

**Issue by johnnyknoxville1337** [DeFiCh/app#620]
#### What happened:

The usecase is to have a backup app working seamlessly doing the same good job as the main system.

After the transfer from the wallet.dat to from linux ubuntu to linux mint system I transferred 1 DFI from cake to a new address in the application. 
In general, the adresses displayed in the app should be visible when restoring it via wallet.dat + passphrase, it would add a lot of usability to the app it without having to add addresses in the background that are already attached to the wallet.dat but not visible in the application to trade/swap/LM management.

#### What you expected to happen:

The Wallet.dat should be restored in a new synched app, the balances and adresses should be seen as in the original system, without having to add the adresses manually being able to do operative transactions without interference.
Following Error Messages occured: 
1. _Execution test failed: ApplyAccountToAccountTx: tx must have at least one input from account owner_
2. _not enought UTXO's in account_
3.  The error described in: https://defichain-wiki.com/wiki/210226-Block-Error 

DFI had to be transferred from cake to the "new" address to have enough UTXO's to swap and add liquidity to the liquidity mining pool. 
The 2nd try it worked. The first try i had following transaction that is in pending state until now while transferring 1 dfi to the new adress in the application itself without cake
https://mainnet.defichain.io/#/DFI/mainnet/tx/df69c4ccb370cd36382fec52205ea982d0b205091ef22a63016aa58b9ffb9afc 

#### What are your environment parameters?

- DeFi App Version: 2.3.1
- Operating System (OS): 
Original: Linux Ubuntu 20.042 LTS
transferred machine: Linux Mint 19.1 | Cinnamon

**Comment by izzycsy** [comment]
Hi @johnnyknoxville1337 , thanks for your feedback, are you addresses missing? Do you have a screenshot of the 3 errors you mentioned? Kindly send your app logs. If possible, do attach screenshots / screen recordings. This will provide more insight for the investigation. Thank you.

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/110533469-fdcb5b00-8158-11eb-8cef-0a0ff52ef7fc.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/110533478-002db500-8159-11eb-8869-13a181988f25.png">

**Comment by izzycsy** [comment]
Hi @johnnyknoxville1337 , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you
