### ISSUE TITLE
Feat | CSV Export: missing transaction for legacy address

### ISSUE THREAD

**Issue by Yannick1712** [DeFiCh/app#624]
#### What happened:
The incoming transaction on legacy addresses are not shown in the csv export.
No matter if incoming or outgoing transactions with legacy addresses will not shown in the last transaction list. 
#### What you expected to happen:
Showing the transaction
#### How to reproduce it (as minimally and precisely as possible):
Open wallet with a legacy address and export the csv file 

#### What are your environment parameters?

- DeFi App Version: 2.3.0
- Operating System (OS): Windows 10

**Comment by izzycsy** [comment]
Hi @Yannick1712 , thanks for your feedback, update [v2.3.1](https://github.com/DeFiCh/app/releases/tag/v2.3.1) is out. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please leave a comment describing your issue further (include screenshots) and app logs. Thank you.

**Comment by RobinTorque** [comment]
The following problems still exist:

1. The transaction is not displayed in the history. Not on the interface, and not in the CSV file. There seems to be a connection with this problem: https://github.com/DeFiCh/app/issues/624

2. The information in the Wallet interface does not match the information on https://dex.defichain.com/testnet/address/7DjqbxQ6FDeTn2dHujc4ir5baQnQqJVMe3. This is confusing.

**Comment by Yannick1712** [comment]
> 
> 
> Hi @Yannick1712 , thanks for your feedback, update [v2.3.1](https://github.com/DeFiCh/app/releases/tag/v2.3.1) is out. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please leave a comment describing your issue further (include screenshots) and app logs. Thank you.

Hey Bella, now the outgoing transaction is shown in the csv file but not on the transaction list in the app. The incoming Transaction is not shown neither in the csv file or the transaction list

**Comment by izzycsy** [comment]
Hi @Yannick1712 , could you kindly elaborate more on what you meant by incoming / outgoing transaction, you mean to displace the addresses related to that transaction?

**Comment by Yannick1712** [comment]
> 
> 
> Hi @Yannick1712 , could you kindly elaborate more on what you meant by incoming / outgoing transaction, you mean to displace the addresses related to that transaction?

I got DFI send on a legacy address. This transaction (e.g. +100 DFI) is neither shown in the wallet transaction list nor in the exportet csv. After I send some of the DFI from this legacy address it is not shown in the wallet transaction list, too. In the exported csv file these send DFI are shown.


Summarized:

-Incoming DFI on legacy address will not shown in wallet transaction list and exported csv file
-Outgoing DFI from legacy address will not shown in wallet transaction list but in the csv file

**Comment by izzycsy** [comment]
Hi @Yannick1712 , thank you for elaborating, will notify the team on this.

**Comment by izzycsy** [comment]
Hi @Yannick1712 , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you

**Comment by Yannick1712** [comment]
> 
> 
> Hi @Yannick1712 , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.
> 
> Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you

Unfortunately nothin changed in new version for this issue

**Comment by izzycsy** [comment]
Hi @Yannick1712 , noted, thank you for updating, the team will continue to investigate.

**Comment by izzycsy** [comment]
Hi @Yannick1712 , may I know what's the output of `getaddressinfo`?

**Comment by izzycsy** [comment]
Hi @Yannick1712 , I tried using a Legacy address and the tx does appear in the CSV export on v2.3.3, can you check on yours please? Thank you. Are the issues still persisting on your end? 

• Incoming DFI on legacy address will not shown in wallet transaction list and exported csv file

• Outgoing DFI from legacy address will not shown in wallet transaction list but in the csv file

<img width="1021" alt="usdt csv" src="https://user-images.githubusercontent.com/65014479/113869962-e88f2e00-97e3-11eb-8989-547c786473bb.png">

**Comment by Yannick1712** [comment]
> 
> 
> Hi @Yannick1712 , I tried using a Legacy address and the tx does appear in the CSV export on v2.3.3, can you check on yours please? Thank you. Are the issues still persisting on your end?
> 
> • Incoming DFI on legacy address will not shown in wallet transaction list and exported csv file
> 
> • Outgoing DFI from legacy address will not shown in wallet transaction list but in the csv file
> 
> <img alt="usdt csv" width="1021" src="https://user-images.githubusercontent.com/65014479/113869962-e88f2e00-97e3-11eb-8989-547c786473bb.png">

Hey Bella,

yes the csv-export is now right. Perfect! 
But the wallet transaction list is still not right. Neitheir the incoming nor the outgoing transaction are shown in the transaction list. 

Annotation: I saw the transaction list should include 38 transaction (showed by number below the transaction list), but if I try to switch to the 2. page it only shows me a blank page. Also interesting the last transaction showed in the list is from January the missing transactions are from march, so it should appear above the last transaction from January. I made a transaction to my own address to checkif the number of transaction will increase. The number increased to 40 (looks right) but the transaction is not shown in the transaction list, too

**Comment by izzycsy** [comment]
Hi @Yannick1712 , great then this issue is resolved! Regarding the issue [`DFI: Missing tx history on UI`](https://github.com/DeFiCh/app/issues/734), we can further discuss on the problem there. The team is looking into it. Thank you for your understanding!
