### ISSUE TITLE
DeFiChain App Not Working

### ISSUE THREAD

**Issue by pastorjim31** [DeFiCh/app#626]
Today was my first day of using the app. I downloaded it. It took several hours to sync. It allowed me to create a wallet. After which it said something was corrupted. I shut it down and restarted the system. Now, I am only getting a message saying blockchain unable to start. 

I found a reddit thread with this problem. 

I tried to delete and reinstall the app, but nothing has worked.

Log is attached 

[March92021.log](https://github.com/DeFiCh/app/files/6112721/March92021.log)

**Comment by thedoublejay** [comment]
Hey @pastorjim31, it seems that your wallet folder is not existing. Can you check if you have this folder? The app is breaking because this path does not exist

`/Users/your username/Documents/Wallet`

**Comment by pastorjim31** [comment]
Thank you for the reply @thedoublejay  - I do have a wallet folder - however, As I mentioned I uninstalled it and reinstalled it and I am not sure if the reinstall created a new wallet or linked to the old. But one is there

**Comment by thedoublejay** [comment]
The reinstall will create the new wallet if this folder exist. But in this case, your wallet directory is not seen by the app. Can you double check if it's there? or Mmaybe check if it's hidden @pastorjim31

**Comment by pastorjim31** [comment]
There is one there and there is not one hidden @thedoublejay

**Comment by thedoublejay** [comment]
Ok, in this folder. Do you see any `.dat` files?

**Comment by pastorjim31** [comment]
There is 1 .dat file and 1 .log file

**Comment by pastorjim31** [comment]
Yes I can. I will contact you in a few mins then

**Comment by pastorjim31** [comment]
[030921log2.log](https://github.com/DeFiCh/app/files/6112817/030921log2.log)

**Comment by pastorjim31** [comment]
Trying to locate it, but having trouble on the Mac. Still looking

**Comment by pastorjim31** [comment]
I found it. What can I open it with? I want to change the code you mentioned @thedoublejay  but it is looking for a program to open the file with

**Comment by pastorjim31** [comment]
This is what it looks like currently 

wallet=wallet.dat
walletdir="/users/jamesburgoon/documents/Wallet 

and I will change it to what you posted

wallet=my_wallet.dat
walletdir=/Users/your username/Documents/Wallet

**Comment by pastorjim31** [comment]
It opened!!!!! 

Now, I have to restore the pathway. 

There are two options 

/Users/jamesburgoon/Documents/Wallet /wallet.dat
/Users/jamesburgoon/Library/Application Support/Defi/wallets/wallet.dat

The first one (documents) is where the wallet folder it. Do I pick that one to restore?

**Comment by thedoublejay** [comment]
@pastorjim31 oh I see. In your previous config, it's "users" but the correct one should be "Users". that's why the old directory was not visible. Glad it's working now. Please close the issue once your ok with it. Thanks!

**Comment by pastorjim31** [comment]
Good Morning @thedoublejay 

I did all the above and it opened. Then when I went back to restore path like you mentioned it crashed again

Now it says this:

Corrupted block database detected. Please restart with -reindex or -reindex-chainstate to recover. Do you want to restart?

I did just restart the app and redid the .conf file ...

With that being said, I am nervous about hitting restore and then using the wallet. 

here is the log post reopen and restarted 

[log 3.log](https://github.com/DeFiCh/app/files/6117725/log.3.log)

**Comment by pastorjim31** [comment]
Update 

I have it working @thedoublejay but as long as I don't hit the restore button it won't crash, but that makes me nervous that if I link my crypto to the wallet it will crash again

**Comment by thedoublejay** [comment]
@pastorjim31, I think there's some name casing issue in your folders. The app uses "Users" but in your machine it is "users". I suggest using a different folder to avoid this issue.

The other issue "re-index" error is caused when the app is not closed properly. When you close the app, it opens a shutdown screen that waits until the node is closed properly. Don't close/shutdown your machine until the app comes to a full close.

**Comment by pastorjim31** [comment]
Oh ok! So, how do I create a different file? does that mean create a new wallet?

**Comment by thedoublejay** [comment]
@pastorjim31, you can use the default blockchain folder to avoid any issues. Do you have your wallet created already?

**Comment by pastorjim31** [comment]
Before the crash there was a wallet I created, then it crashed ... so I don't know if there is one or if the one created was corrupted

**Comment by thedoublejay** [comment]
The wallet will not be corrupted. Only the blocks because it's not terminated properly.

What I suggest on your end is:
1. Create wallet on default folder
2. Wait app to be fully closed

**Comment by pastorjim31** [comment]
How do I create a wallet on the default folder?

Thank you sooooooo much for all your help you have been amazing

**Comment by thedoublejay** [comment]
@pastorjim31 oh yeah I forgot you need to select a wallet upon creating. I suggest you store it somewhere other than the "Users" folder.

**Comment by pastorjim31** [comment]
Help me understand :) 

Do I create wallet and then link it to a different folder? Do I restore a wallet from a backup?

**Comment by thedoublejay** [comment]
You can do both. As long as you select a different folder than "Users".

**Comment by DirkRiesi** [comment]
I don't know if I am correct here, but I also downloaded the Defi completly new. I can install it but it never synchronize. I am also not able to create a wallet. What can I do? re-installed it also several times already.

**Comment by thedoublejay** [comment]
@DirkRiesi  what is the display of your app?

**Comment by DirkRiesi** [comment]
Thanks @thedoublejay . Found the problem with not created folders.
