### ISSUE TITLE
Feat | Add LP: Direction of arrow icon

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#633]
<img width="825" alt="Bildschirmfoto 2021-03-11 um 10 53 52" src="https://user-images.githubusercontent.com/65536965/110769218-3aca4700-8258-11eb-88fa-b6700bdcceb2.png">

In the DFI Wallet, an icon with an arrow pointing upwards is used to sell the asset. The icon with the arrow pointing down, is used for adding. 

According to this logic, the arrows must be exchanged in the Liquidity Wallet. Add liquidity decreases the asset balance in the DFI Wallet and increases the asset balance in the Liquidity Wallet. So, the symbols in the Liquidity Wallet should be rotated.

**Comment by izzycsy** [comment]
Hi @RobinTorque , thanks for your feedback. As I understood, for eg:
• User has BTC wallet, a DFI wallet and a DFI-BTC wallet
• When add liquidity, DFI wallet & BTC wallet should display outgoing symbol 
• And DFI-BTC wallet should display incoming symbol 

Currently, app displays outgoing symbol for for all add liquidity tx. 

Feedback well noted, will convey to team.
