### ISSUE TITLE
Testnet: Masternode Rewards are not displayed in the wallet

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#636]
I set up a masternode in the testnet and after a few hours I already found 2 blocks. But the rewards are not displayed in the wallet. 

<img width="843" alt="Bildschirmfoto 2021-03-11 um 12 59 10" src="https://user-images.githubusercontent.com/65536965/110784211-b4b6fc00-8269-11eb-8712-482b38842440.png">

Mining Rewards are displayed correctly in the Explorer. 
https://testnet.defichain.io/#/DFI/testnet/address/7DjqbxQ6FDeTn2dHujc4ir5baQnQqJVMe3

<img width="966" alt="Bildschirmfoto 2021-03-11 um 13 02 19" src="https://user-images.githubusercontent.com/65536965/110784485-0b243a80-826a-11eb-8aaa-5b4cf52fb686.png">

<img width="536" alt="Bildschirmfoto 2021-03-11 um 13 04 39" src="https://user-images.githubusercontent.com/65536965/110785982-e0d37c80-826b-11eb-878d-10a06810f152.png">

The balance in the Wallet is smaller than the distributed rewards. 

<img width="307" alt="Bildschirmfoto 2021-03-11 um 13 09 13" src="https://user-images.githubusercontent.com/65536965/110785238-014f0700-826b-11eb-94c2-e00b4bb71370.png">

I am aware that there is a lock-in period for Mining Rewards. However, I assumed that the display in the Explorer must always match the display in the Wallet. 

I have exported the transaction history as CSV. I have not found any Mining Rewards in this file. 
The logs and the CSV document are in the zip file. 

[210311 Robin Logs.zip](https://github.com/DeFiCh/app/files/6122917/210311.Robin.Logs.zip)

**Comment by RobinTorque** [comment]
Update:
The coins that are not displayed can be displayed in the console using the getbalances command. I have documented this situation in the wiki to share the knowledge about it.

https://defichain-wiki.com/wiki/Masternode#I_have_found_a_block.2C_but_the_rewards_are_not_apparent

**Comment by RobinTorque** [comment]
The following problems still exist:

The transaction is not displayed in the history. Not on the interface, and not in the CSV file. There seems to be a connection with this problem: #624

The information in the Wallet interface does not match the information on https://dex.defichain.com/testnet/address/7DjqbxQ6FDeTn2dHujc4ir5baQnQqJVMe3. This is confusing.

**Comment by izzycsy** [comment]
Hi @RobinTorque , well noted, thanks for your feedback.
