### ISSUE TITLE
Testnet: It is possible to operate one masternode on 2 devices at the same time

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#639]
<img width="1440" alt="Bildschirmfoto 2021-03-11 um 17 01 29" src="https://user-images.githubusercontent.com/65536965/110817864-045aef00-828d-11eb-9b1f-a1a90ae0bfc2.png">
<img width="1440" alt="Bildschirmfoto 2021-03-11 um 17 01 43" src="https://user-images.githubusercontent.com/65536965/110817874-06bd4900-828d-11eb-90bf-3b46b2089048.png">
<img width="1440" alt="Bildschirmfoto 2021-03-11 um 17 02 19" src="https://user-images.githubusercontent.com/65536965/110817888-0ae96680-828d-11eb-91e0-47d28434011c.png">

I have a masternode installed on my MacBook. Then I created a BackUp and restored the BackUp on a Windows computer. On the Windows computer, the masternode was initially deactivated. I then activated it, and after that I had exactly the same picture on both computers. 

Is it ok that a masternode can run on 2 devices at the same time? There was no indication and no error message. 

Bella has the RemoteDesktop access information for my Windows computer to better investigate this. 

[210311 Robin MacBook Logs.zip](https://github.com/DeFiCh/app/files/6124391/210311.Robin.MacBook.Logs.zip)
[210311 Robin Windows Logs.zip](https://github.com/DeFiCh/app/files/6124394/210311.Robin.Windows.Logs.zip)

**Comment by izzycsy** [comment]
Hi @RobinTorque , thank you for your feedback, please give us time to investigate this.

**Comment by monstrobishi** [comment]
Hi @RobinTorque , it's not a problem to run the same masternode on different machines, it's just a waste of RAM and electricity :)

The consensus will enforce that you can only submit the maximum amount of hashes for that operator.
