### ISSUE TITLE
Feat| Optimization of CSV export

### ISSUE THREAD

**Issue by jleidinger** [DeFiCh/app#640]
#### What would you like to be added:

I have several points that would improve the CSV export:

- Inserts an option to export all transactions (as with Cake)

- Summarizes Rewards and Commissions on a daily basis. Best grouped by type, pool ID, and coin. I tried this and in this way the amount of data can be reduced by a factor of 1400-1700.

- Some lines contain multiple coins or tokens, such as this line:
   "701348","daca3e...d78c7b","11/Mar/2021, 03:24 pm","Commission","4","0.00000022@DFI,0.00000063@ETH"
   To improve further processing, it would make sense to split the sample line into two lines:
   "701348","daca3e...d78c7b","11/Mar/2021, 03:24 pm","Commission","4","0.00000022@DFI"
   "701348","daca3e...d78c7b","11/Mar/2021, 03:24 pm","Commission","4","0.00000063@ETH"

- I found AddPoolLiquidity transactions that are incomplete. For example:
  
The pool pair and the second coin are missing: 
 "533560","94522ed64bf70c4fe6b409954339e14874930880900fb332167bc560c282656f","28/Dec/2020, 04:29 pm","AddPoolLiquidity","","-49.90035871@DFI"

The second coin are missing  
 "534165","1e3404e7303c97fae1fca9b88ffda78a814aa7078a7eb2cb83275b50dfb1059d","28/Dec/2020, 10:35 pm","AddPoolLiquidity","","-49.90939535@DFI,0.36593409@BTC-DFI"
 
The second coin are missing 
 "537945","acaf8fe7282fbcfa0838ed19944ca98a68493783ca3bc6039450205d2a53177c","30/Dec/2020, 02:43 pm","AddPoolLiquidity","","-0.99924129@DFI,0.04483244@ETH-DFI"

#### Why is this needed:

The proposed changes are necessary to increase user experience, reduce data volumes and make exporting data more usable for exports to other platforms such as CoinTracking.

**Comment by izzycsy** [comment]
Hi @jleidinger , thanks for your feedback, will let the team review your suggestions.

**Comment by izzycsy** [comment]
Hi @jleidinger , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.

**Comment by johnnyknoxville1337** [comment]
Could this request be integrated in one of the next sprints please?

**Comment by izzycsy** [comment]
Hi @johnnyknoxville1337 , thanks for your interest. The team has to prioritise issues that are more pressing to majority of the users, for feature improvements I cannot guarantee that it'll be implemented in the next update. Thank you for your understanding.

**Comment by AndErazor** [comment]
I would also highly support this issue being solved sooner than later! I would not even call it a new feature or optimization, this is the very basic display of transaction that is not correct.

**Comment by MaReCoding** [comment]
I would suggest to separate the different points mentioned by @jleidinger as independent issues. Maybe then it is easier to plan the realization. From my point of view, I would like to see the following priority:
1.) Inserts an option to export all transactions (as with Cake)
2.) Summarize Rewards and Commissions on a daily basis. Best grouped by type, pool ID, and coin.
3.) Some lines contain multiple coins or tokens. To improve further processing, it would make sense to split these into two lines

The following point: "I found AddPoolLiquidity transactions that are incomplete." is not really an error. All transactions are complete. They can be found, when all Balances are exported (the transactions are distributed over several files)

**Comment by jleidinger** [comment]
There are transactions with missing parts which has nothing to do with a distribution over different files. You can check it with the posted examples. We discussed it also on telegram. This is not only my issue.

**Comment by izzycsy** [comment]
Hi @jleidinger @johnnyknoxville1337 @AndErazor @MaReCoding , thanks for your feedbacks. The team has taken them and will be improving on the feature, should be out in the upcoming release. I'll let you know when it's ready.

**Comment by izzycsy** [comment]
Hi @jleidinger @johnnyknoxville1337 @AndErazor @MaReCoding , [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a **mandatory update**. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @jleidinger @johnnyknoxville1337 @AndErazor @MaReCoding , [v2.5.0](https://github.com/DeFiCh/app/releases/tag/v2.5.0) is out. Please read through the release notes before updating. 

@jleidinger , posting non-bug related issues here will eventually turn stale. The team is in the midst of working on the Light Wallet, I'd suggest that you copy & paste your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner more support from the community. Thank you.
