### ISSUE TITLE
App v2.3.1_v2 is blocking the network connection

### ISSUE THREAD

**Issue by supervolot** [DeFiCh/app#644]
#### What are your environment parameters?

- DeFi App Version: 2.3.1_v2
- Operating System (OS): WIN10, WIN Server 2019, WIN Server 2009

**Comment by RobinTorque** [comment]
Hello @supervolot 

Please send us some more screenshots and your log data so that we can better understand the problem. 

https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-Defi-App

**Comment by izzycsy** [comment]
Hi @supervolot , the team has halted v2.3.1 at the moment due to some issues. I'll update you again when the team fixes it and is ready for release. In the mean time, could you send your app logs please? 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/111070106-1053e480-850b-11eb-9052-f095a7e3c221.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/111070113-12b63e80-850b-11eb-9e03-7aaa4b297c0f.png">

**Comment by supervolot** [comment]
[defi_v2.3.1_log_14.03.2021.log](https://github.com/DeFiCh/app/files/6137053/defi_v2.3.1_log_14.03.2021.log)

**Comment by supervolot** [comment]
There are also "network errors" seems like the app have a lot ob bugs, perhaps you should update as fast as possible to 2.3.2

**Comment by thedoublejay** [comment]
@supervolot Do you know if your machine has network connection? Maybe there's some firewall/anti virus that's blocking the network connection on your machine. The network errors on the logs are just warnings that the app cannot connect to the network

**Comment by Stonygan** [comment]
Sometimes i have the same error, i make a video.
HTTP over Browser failed
Wallet Balance failed
Ping ok
Sync ok

Close Wallet: All fine again.

http://mydeficha.in/video/lost_internet_http.mp4

**Comment by uzyn** [comment]
Do you have a low bandwidth cap on your network? It seems that app is only synced to block 270k and not fully synced. During syncing state it would consume quite significant bandwidth, this might limit your other apps from using the same bandwidth.

Regardless, I don't think this is an issue on the node or defi app but more of an issue of the network. I can't really be sure. Alternatively you might want to try the Bitcoin Core (QT) client to see if the same network issues occur. https://bitcoin.org/en/download

**Comment by bernd-mack** [comment]
I have the same problem, about 5 hours after opening the wallet (same effect when only the defid is running without wallet) the internet connection on Win10 drops.
From that moment on no RPC connections are possible neither to a bitcoin fullnode on the computer nor to the defi node.
Immediately after the definode was shut down everything works normally again.
In the logfiles there is nothing to find at the time, I will try to record the next interruption.

**Comment by Stonygan** [comment]
> Do you have a low bandwidth cap on your network? It seems that app is only synced to block 270k and not fully synced. During syncing state it would consume quite significant bandwidth, this might limit your other apps from using the same bandwidth.
No, my Wallet is on testnet, Blockheight is correct.
I check the connections from defid.exe when the wallet and internet works:

![image](https://user-images.githubusercontent.com/44975826/111136416-04553a80-857e-11eb-80e3-b055546cf1e5.png)

Bitcoin Testnet or not? After connection is lost, all this Ports are closed, only 18555 visible.

![image](https://user-images.githubusercontent.com/44975826/111136639-3ff00480-857e-11eb-8953-13281552a433.png)

when the error occurs, the ports above opened from defid.exe.

**Comment by Stonygan** [comment]
This error occurs only with enabled spv-support (spv=1 in defi.conf) Is this switch necessary to run a Masternode inside the Wallet?
Maybe its not a problem from the APP, its a problem of defid.exe (AIN/Node-Version)

**Comment by izzycsy** [comment]
Hi @supervolot , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

The above feature / issue is not included in this update yet, this comment is to notify you about the update.

**Comment by supervolot** [comment]
Hi i have still the bug after the mandatory update (and no SPV=1) in the defi.conf
![app_bug_29 03 2021](https://user-images.githubusercontent.com/59117793/112893173-d6b5d880-90c9-11eb-9ce7-bf9f43410cf0.PNG)
[App_log_29.02.2021.log](https://github.com/DeFiCh/app/files/6224236/App_log_29.02.2021.log)
[Bin logs_29.03.2021.log](https://github.com/DeFiCh/app/files/6224237/Bin.logs_29.03.2021.log)

**Comment by supervolot** [comment]
After the bug when i stopp the app and restart i get the message "corrupted block database detected" !!! 
![app_bug_29 03 2021_2](https://user-images.githubusercontent.com/59117793/112893560-5cd21f00-90ca-11eb-9392-a8ae058645ee.PNG)

**Comment by izzycsy** [comment]
Hi @supervolot , thanks for the update, it's likely did not close the app properly. 
<img width="1012" alt="Wait for app to quit itself" src="https://user-images.githubusercontent.com/65014479/112981567-f8789380-918d-11eb-95e4-4503499dc347.png">


The team is working on the Snapshot fix — to speed up synchronisation. Logs well received, please give us time to investigate.

**Comment by izzycsy** [comment]
Hi @supervolot , [v2.3.3](https://github.com/DeFiCh/app/releases/tag/v2.3.3) is out. Please read through the release notes before updating. If you have not sync to 100%, there was a node issue on 05/04/2021 that may have cause the `network error`, everything is back online now, you may try the following: 

**Option 1 — Reset & Reindex (sync from 0%)**
1. Settings > `Reset & Reindex` 

<img width="790" alt="Settings   Reset   Reindex" src="https://user-images.githubusercontent.com/65014479/113691297-ddae9d80-96fe-11eb-85e8-a888f16a8df3.png">

 
**Option 2 — Snapshot (sync from 90%+)**
1. Settings > `Reset & Reindex` 
2. Wait for app to start syncing
3. Ensure you’ve at least 27GB of extra space
2.  Click on `i` located at bottom-left corner of app screen 
3. Download Snapshot

<img width="244" alt="`i` to trigger Snapshot download" src="https://user-images.githubusercontent.com/65014479/113691572-2403fc80-96ff-11eb-94c9-1e7ebafd697f.png">

Let me now your results, thank you for your patience.

**Comment by izzycsy** [comment]
If your issue persist, we can further discuss on the problem here [`Unable to start blockchain`](https://github.com/DeFiCh/app/issues/733). We would like to keep same issues in one thread. Thank you for your patience.
