### ISSUE TITLE
Feature in GUI to automate transfer utxoDFI to accountDFI

### ISSUE THREAD

**Issue by sbisig** [DeFiCh/app#646]
#### What would you like to be added:
Feature in GUI to **automate transfer utxoDFI to accountDFI** (within single wallet)

#### Why is this needed:
Cumbersome current implementation (need 2 wallets)

**Comment by RobinTorque** [comment]
Hi @sbisig 

Maybe it's just me. But I don't understand why this function is needed. Can you explain what it is needed for?

**Comment by sbisig** [comment]
> Hi @sbisig
> 
> Maybe it's just me. But I don't understand why this function is needed. Can you explain what it is needed for?
Hi @RobinTorque 
Thank you for your fast response.
Yes, sure I can give more info. I want to stake the DFI coins (at the moment only possible via CakeDEFI, right?) - earned from LM -  and I am not able to send these DFI to that account (because I only have the DFI coins as account coins and not utxo).

**Comment by RobinTorque** [comment]
I suspect there is a problem of understanding here. The app manages the UTXO very well. I have no problems or restrictions with it. You are not allowed to send all DFIs, otherwise you will not have any DFIs to make transactions. That is actually logical.

Maybe this article will help. 

https://defichain-wiki.com/wiki/App_error_messages#Insufficient_Fund

**Comment by RobinTorque** [comment]
I suspect there is a problem of understanding here. The app manages the UTXO very well. I have no problems or restrictions with it. You are not allowed to send all DFIs, otherwise you will not have any DFIs to make transactions. That is actually logical.

**Comment by sbisig** [comment]
I also read this: https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/

**Comment by RobinTorque** [comment]
In the current version, this is done automatically. There is no longer any reason to do this manually. The texts and the video are out of date.

From my point of view, this issue can be marked as done.

**Comment by izzycsy** [comment]
Hi @sbisig , thanks for your feedback, utxoDFI is used to pay for transactions fees while rewards received are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. To convert accountDFI to utxoDFI, the simplest way is to send DFI from your `receive address A` to your `receive address A`, the app will automatically convert for you. This feature has already been implemented, I'll be closing this issue in the mean time.
