### ISSUE TITLE
The DFI Explorer no longer works

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#648]
<img width="850" alt="Bildschirmfoto 2021-03-12 um 13 13 56" src="https://user-images.githubusercontent.com/65536965/110939050-155f3b00-8335-11eb-8bd2-bf34038aba5f.png">

The display with the DFI Explorer does not currently work.
<img width="984" alt="Bildschirmfoto 2021-03-12 um 13 17 22" src="https://user-images.githubusercontent.com/65536965/110939223-6111e480-8335-11eb-8784-db5628e7a0b0.png">
The display of the pools does not work either. 

https://dex.defichain.com/mainnet/pool

@izzycsy

**Comment by RobinTorque** [comment]
it works again

**Comment by izzycsy** [comment]
Hi @RobinTorque , thanks for your feedback. I'll close this issue.
