### ISSUE TITLE
Exiting Wallet creates misleading message on mnemonic phrase

### ISSUE THREAD

**Issue by nico89-exp** [DeFiCh/app#649]
#### What happened: 
Wanted to restore the wallet, clicked the "exit" button in the app. A message occured, indicating that "You will need your mnemonic phrase if you want..."

#### What you expected to happen: 

Since 2.3.0 the creation of mnemonic phrases is discouraged by the app. While creating a new wallet, no mnemonic phrase is created. So the message is misleading and should be indicate that a .dat backup file is needed.

#### What are your environment parameters?

- DeFi App Version: 2.3.0
- Operating System (OS): Linux

#### Anything else we need to know?:

![Wallet Exit_phrase](https://user-images.githubusercontent.com/80567701/111023395-1f3a7a00-83d9-11eb-92ee-3b408173251a.jpg)

**Comment by RobinTorque** [comment]
Yes, you are right. Thank you very much for this message. I have immediately submitted a proposal. 

https://github.com/DeFiCh/app/pull/651

**Comment by izzycsy** [comment]
Hi @nico89-exp @RobinTorque , thanks for you feedback and PR. The team will update this, including the German translation.
