### ISSUE TITLE
Misleading wallet management

### ISSUE THREAD

**Issue by bebosudo** [DeFiCh/app#655]
#### What would you like to be added:

This may possibly be a request for removal of a "feature", because I'm freaking out at how the app manages wallets.

Every time I log out of a wallet it asks me to make a backup, which I do every time.  
I don't understand why should I make a backup, though; isn't the wallet that I used up until that moment being saved back to disk at any change? If so, then why should I make a backup? Just tell the user to be sure to have a backup of the wallet which was used up until that moment.  
So far I save a new separate wallet each time I log out, but I don't understand what changes between the different backups. If I create e.g. a new address, is that "visible" and "reachable" from an old backup?

I did some tests: I made a backup and quit, then reloaded it, created a new address and saved a new backup; then I loaded the old backup and it had the new address as well and was able to see some DFI that I sent to the address (I didn't try moving them, though). This is why I don't get why should I make a backup at all, if I got any previous backup.  
I remember reading from the bitcoin book that bitcoin wallets contain an internal seed, which is used to create a deterministic sequence of private key + public address, so an old "backup" of a wallet should be able to gain access to any new addresses; is that the same also for defichain?

Moreover the exit panel talks about a mnemonic seed, which is not part of the wallet anymore, right?

The app also creates a "default" wallet in `~/.defi/wallet.dat` on linux, and many other files like `~/.defi/wallet-bak-TIMESTAMP.dat`. Is that just a "safety measure" to have copies of wallets around, in case a user deletes the one they had? Are these copies created every time the app is closed?

#### Why is this needed:

Don't ask to make a backup every time the user wants to log out of a wallet, it's misleading. Just recommend the user to make a copy of *any* wallet.

If you add new data to the wallet (e.g. new addresses? transactions for which the addresses on the wallet are involved? temporary amounts?) just overwrite the previous wallet file automatically. I'd let the user managing copies of the wallet, if they want so.

- DeFi App Version: 2.3.0

**Comment by Stonygan** [comment]
Hi, one question, maybe u use this button to "logout" of Wallet?

![image](https://user-images.githubusercontent.com/44975826/111117548-f4caf700-8567-11eb-808d-b414cf3b1605.png)

Thats no logout, that is the Button to "Reset" your wallet and delete all. Many users are confused, because this ICON is often used to exit programs, not reset. Close the APP with the X in the corner, thats enough. Maybe this help?

**Comment by Stonygan** [comment]
@thedoublejay Please consider using a different ICON for the reset/"Exit Wallet" button.

![image](https://user-images.githubusercontent.com/44975826/111119807-dc101080-856a-11eb-8624-921c887619a4.png)

**Comment by bebosudo** [comment]
Oh, that's definitely a great example of bad UI. I didn't know that, and there seems to be no "text" when hovering that icon.
Thank you @Stonygan!

So how should I manage different wallets? Should I continue "resetting" before loading the other?

Anyway, I still don't know if there's any difference between the different wallet backups. Or any copy of a wallet is fine?

**Comment by Stonygan** [comment]
> So how should I manage different wallets? Should I continue "resetting" before loading the other?
> 
I can't recommend using the APP with multiple wallets. I think thats not the focus of the current APP. Maybe use different Workstations or virtual machines to do this. I think sooner or later you have trouble with such a setup.

**Comment by bebosudo** [comment]
Mmm doesn't really sound like a "portable" solution.

Any suggestion on how the "wallets" work? Is a backup of a wallet any different from a previous backup?

**Comment by thedoublejay** [comment]
@bebosudo Hi, thanks for your comments. It's very valuable for us to get some feedback from the community. To explain the reasoning behind it, we're asking for a backup every time is to have better security of wallets. If you only have one backup and it gets corrupted for some reason, or it gets deleted, you will lose all your funds. I don't see the issue on having lots of backups. Some users might be more tech savvy but we also need to cater on others users. Our suggestion is to have multiple copies of the wallet.dat file. One in your desktop and one in another storage (like external drive).

Regarding the change with "mnemonic seed" on exit wallet, we have already addressed it and it will be updated on next release.

**Comment by thedoublejay** [comment]
@Stonygan thanks for raising it. I will raise it to our designer. However, I disagree with using a "trash bin" icon for it since it's widely used for "deletion". Exiting your loaded wallet is not the same as deleting it.

**Comment by bebosudo** [comment]
> Our suggestion is to have multiple copies of the wallet.dat file. One in your desktop and one in another storage (like external drive).

I still don't understand how these copies "work". Is any copy of wallet.dat enough to get back access to the funds?


> I disagree with using a "trash bin" icon for it since it's widely used for "deletion".

What about an X symbol?
❌ | ✖️
That's associated with "closing" an application, and some more detailed text in the popup dialog could explain what @Stonygan told me above.

**Comment by thedoublejay** [comment]
@bebosudo Yes any copy can get back access to your funds. 

For the exit wallet, I will communicate it to our designer and will update you on it.

**Comment by bebosudo** [comment]
> Yes any copy can get back access to your funds.

That's great to hear! So I don't need to sweat it, and can keep any copy of the wallet as a backup. Good!
I'd suggest explaining also this in the popup.

Thank you!

**Comment by aentan** [comment]
It is kind of a "logout" feature but because the way wallets are managed, for security, exiting a wallet essentially unloads it. To be able to get back to it again, you'd need to back it up to a file name and location that you know.

It's definitely a more involved process because there's no centralized server to handle all that for you, for it to feel like the logout/login experience of Facebook.

Regarding the UI. It is what it is – an exit button. It does what it does – exiting. I don't think a change of icon solves the misunderstanding you had. The fundamental problem I believe is that a decentralized single wallet paradigm is at odds with the centralized multi-account UX that most people are used to. So much of crypto UX is cumbersome because we give up convenience for control.

To your issue, my response would be that the app currently does not offer a convenient way to quickly switch between wallets. It is meant to be used with a single wallet. There is a certain gravity to exiting a wallet thus we don't recommend doing so to switch wallets. You can but it's a lot of trouble.

As a heavy user myself, I want to be able to switch wallets too. I'm definitely exploring with the team how this can be achieved technically.

**Comment by bebosudo** [comment]
Cryptos exist to empower decentralization, at the expense of possible money loss if the user doesn't take the necessary precautions.

Fine with me keeping the same icon, but the explanation given when clicking on the button sounds like if the user doesn't make a copy *RIGHT THERE* they will lose access to their funds, as if the recent operations are saved only in that backup.
For future reference, the current exit message that appears is:
> Exiting your wallet now will remove your wallet from the app. You will need your mnemonic seed phrase if you want to add this wallet later. Do you wish to backup your wallet before exiting?

But if the user already archived copies somewhere else, they don't need to worry about it anymore.

Thank you for your work!

**Comment by izzycsy** [comment]
Hi @bebosudo , thanks for your valued feedback, we'll be updating the message as well in the upcoming release. With that I'll be closing this issue. Thank you!
