### ISSUE TITLE
Defi-App doesn´t synchronise

### ISSUE THREAD

**Issue by franz1612** [DeFiCh/app#656]
Dear community,

my defi-App doesn't synchronize any more. It always stops at the same percentage. already deleted it and tried to reinstall but always the same error.. My logs are attached!
Thanks for your help

[Archiv.zip](https://github.com/DeFiCh/app/files/6140068/Archiv.zip)

**Comment by izzycsy** [comment]
Hi @franz1612 , thanks for your feedback, regarding the issue [`v2.3.1 corrupted blockchain / app not syncing`](https://github.com/DeFiCh/app/issues/657), we can further discuss on the problem there. We would like to keep same issues in one thread. Can you send a screenshot of your issue & your logs there please? Thank you!
