### ISSUE TITLE
Synchroize stuck on Block 469818

### ISSUE THREAD

**Issue by Stonygan** [DeFiCh/app#67]
Sync with Blockchain stuck at Block 469818.

[app_log.log](https://github.com/DeFiCh/app/files/5617961/app_log.log)
[binary_logs.log](https://github.com/DeFiCh/app/files/5617962/binary_logs.log)
[app_config.log](https://github.com/DeFiCh/app/files/5617982/app_config.log)

**Comment by starman578** [comment]
[binary_log.log](https://github.com/DeFiCh/app/files/5618014/binary_log.log)
[app_config.log](https://github.com/DeFiCh/app/files/5618015/app_config.log)
[app_log.log](https://github.com/DeFiCh/app/files/5618016/app_log.log)

Same issue here, also stuck on the same block height.
singet without a problem after the update from 2.0.1 to 2.1.0 after some idle time I noticed it was a few blocks behind and synced. Then it got stuck at 469818. Now for more then 30 min.

**Comment by izzycsy** [comment]
Hi @Stonygan & @starman578  , thanks for your feedback. The synchronising issue has been fixed, kindly install the v2.1.1 of the app <https://github.com/DeFiCh/app/releases/tag/v2.1.1>.

**Comment by starman578** [comment]
Thanks @izzycsy,
Update went smooth and solved the problem for me.
Great work!
