### ISSUE TITLE
Cant restore my Wallet with Seed

### ISSUE THREAD

**Issue by RussellReibold** [DeFiCh/app#670]
#### What happened:
1.) Synchronizing of Blockchain stoped at 86% for hours. 
2.) Update could not be done. Only a white screen appeared after restart
3.) I downloaded the 2.3 Version and installed it manuel. Then i wanted to restore my wallet with my seed, but there was a message telling me that their is a blockproblem. When entering the seed a second time it says "Already have this key (either as an HD seed or as a loose private key)"

#### What you expected to happen:
I just wanted to update the wallet 

#### How to reproduce it (as minimally and precisely as possible):
Enter my Seed. 

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.0
- Operating System (OS): Mac OS Big Sure (M1)
[app logs.zip](https://github.com/DeFiCh/app/files/6158098/app.logs.zip)

[app logs.zip](https://github.com/DeFiCh/app/files/6158092/app.logs.zip)

**Comment by izzycsy** [comment]
Hi @RussellReibold , thanks for your feedback, regarding the issue [`v2.3.1 corrupted blockchain / app not syncing`](https://github.com/DeFiCh/app/issues/657), we can further discuss on the problem there. We would like to keep same issues in one thread. Can you send a screenshot of your issue & your logs there please? Thank you!
