### ISSUE TITLE
I can't input my "Receive Address" on the "Decentralized Exchange" tab

### ISSUE THREAD

**Issue by jwmcdonnell** [DeFiCh/app#671]
On the Decentralized Exchange tab, I am not able to insert my address in the "Receive Address" box.  It is not accepting anything I input.  I tried typing and copying and pasting and nothing works.  I didn't have this issue before with my old computer (a Dell).  Now I am using a MacBook Pro.  Thank you.
<img width="1080" alt="Screen Shot 2021-03-17 at 5 15 57 PM" src="https://user-images.githubusercontent.com/79559218/111541160-82fcd400-8746-11eb-865c-6b30985d92df.png">

**Comment by thedoublejay** [comment]
@jwmcdonnell You need to go to Wallets -> Click on any tokens -> Receive -> Input your address there. Then it will be visible on this dropdown.

**Comment by RobinTorque** [comment]
https://github.com/DeFiCh/app/issues/669

**Comment by izzycsy** [comment]
Hi @jwmcdonnell , regarding the issue [`Restore: show old addresses after wallet import`](https://github.com/DeFiCh/app/issues/669), we can further discuss on the problem there. We would like to keep same issues in one thread. In the mean time you can manually add back your address. Thank you. 

<img width="769" alt="Turn off auto generate new address" src="https://user-images.githubusercontent.com/65014479/111597190-e7806780-8808-11eb-9efc-c6ed6ac87757.png">
