### ISSUE TITLE
Feat | Adjustment of the DFI MAX calculation

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#686]
<img width="1001" alt="Bildschirmfoto 2021-03-19 um 11 03 07" src="https://user-images.githubusercontent.com/65536965/111763929-f287d600-88a2-11eb-8421-6a9c9fb7b393.png">

Suggested improvement:

Problem: Many users run LM with DeFi Wallet and send all DFI Rewards to CAKE for staking. In doing so, they go into DFI Wallet and click MAX on the amount. A few days later they come to our Telegram group and complain about the error message "Insufficient DFI UTXO". Of course it is possible to explain to these users what they did wrong, but there are always new people coming into the DeFiChain system and so there are still always new people who don't understand and make this mistake. 

<img width="754" alt="Bildschirmfoto 2021-03-19 um 11 15 24" src="https://user-images.githubusercontent.com/65536965/111765253-72627000-88a4-11eb-9e56-ea272c773a83.png">

Short term solution proposal:
When pressing the MAX key, 0.1 DFI less should be transferred to the quantities field. With this simple solution everyone should be happy. The error described above no longer happens, and who still wants to send everything has the option to send the full amount, in which he enters the amount manual. 

Long term proposed solution:
Implementation according to above. In addition, the Mechaniusmus should automatically take over 100% if the wallet has no other tokens.

**Comment by izzycsy** [comment]
Hi @RobinTorque , thanks for the feedback, please give us time to address this issue.

**Comment by bebosudo** [comment]
I would +1000 if I could.
I had to ask a friend to "borrow" me a couple of DFI to unlock the DFI I had in my wallet which were "locked" because were in token form.

I think there's no need to add complex computations for different cases, but a warning may be enough, similarly to the warning you show when a user tries to send a liquidity pool share:
![photo_2021-03-23_14-07-15](https://user-images.githubusercontent.com/1922124/112218691-41a27380-8be1-11eb-8246-34216974b432.jpg)

e.g.
```
This transaction will leave less than X DFI on your wallet.
Please note that some DFI coins are required to perform operations on the DeFiChain blockchain, including further withdrawals.
Note that DFI in token form (those gained through liquidity mining) need to be converted to DFI in coin form, and this also requires DFI coins.
Please refer to this article on the DeFiChain knowledge base for more details:
https://defichain-wiki.com/index.php?title=App_error_messages&redirect=no#Insufficient_Fund
```

(I couldn't find a link to the current article in the wiki, it seems it was removed, which is not great for such an important procedure, and relying on the post of a random user on reddit doesn't sound great)

**Comment by diegorodriguezv** [comment]
I'm having the same problem and a search for:
> Insufficient UTXO DFI for transaction fees. Please send some DFI from an exchange or another wallet and try again.
doesn't give meaningful results. This is very frustrating for newcomers.

**Comment by izzycsy** [comment]
Hi @diegorodriguezv , we're working on improving the feature. Just make sure you've some DFI in your address and you should never have to face the issue. 

`getbalance` — utxoDFI
`gettokenbalances` — accountDFI

The sum of utxoDFI & accountDFI would be your total DFI tokens.

**Comment by izzycsy** [comment]
Hi @RobinTorque @diegorodriguezv , your feedback has been conveyed to the team, however I do not have a timeline on when this would be implemented. Just wanted to update you before this thread becomes stale. Rest assured that the team has accepted this enhancement and will be implemented in due time. 

For future enhancement related ideas, you can publish it on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner some support from the community, and the team can decide whether to implement the feature in the future. Thank you!
