### ISSUE TITLE
Incorrect display Masternode status

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#688]
This problem has a connection to the following issue: https://github.com/DeFiCh/app/issues/644

<img width="1440" alt="Bildschirmfoto 2021-03-19 um 11 46 47" src="https://user-images.githubusercontent.com/65536965/111769608-b9069900-88a9-11eb-96bf-154c6db6a7b2.png">
Problem: Some users report that with the operation of a masternode the Internet fails. This is known as far as it goes. I would like to point out with this issue that the display of the masternode is faulty. Although the internet is down and no account balances can be displayed, a green dot appears next to the masternode. This suggests that the masternode is online. But this is wrong. 

[210319 Robin Logs Network Error.zip](https://github.com/DeFiCh/app/files/6170604/210319.Robin.Logs.Network.Error.zip)

**Comment by izzycsy** [comment]
Hi @RobinTorque , thanks for your feedback, please give us time to investigate this.

**Comment by supervolot** [comment]
I have still the bug (v.2.3.2) that i run a masternode, but the app dont show the masternode ?

**Comment by izzycsy** [comment]
Hi @supervolot , thanks for updating. The above feature / issue is not included in this update yet, as I understand your issue relates to [App v2.3.1_v2 is blocking the network connection](https://github.com/DeFiCh/app/issues/644) & [Win10: Masternode is missing](https://github.com/DeFiCh/app/issues/602), which the team is still investigating. Thank you for your patience.
