### ISSUE TITLE
Defi guthaben wird trotz bestätigter Transaktion nicht angezeigt

### ISSUE THREAD

**Issue by klauwein** [DeFiCh/app#690]
Hallo, ich weis leider nicht wie ich diese Art von hilfe richtig in Anspruch nehmen soll daher versuche ich es mal mit schreiben.

Ich habe eine Transaktion von Cake zur Defi APP gesendet diese Transaktion so wurde mir bestätigt auch abgeschlossen!

  | Fabrizio (CAKE)                                                                                      18.03.2021, 21:40 GMT+8                                                Hey,danke für deine nette Nachricht und hoffe dir gehts gut.Laut Explorer sind dein DFI angekommen, kannst du dies bitte nochmals Prüfen:https://explorer.defichain.com/#/DFI/mainnet/tx/17d38aa1c919c175e3a83df28fa64cc409e3938d5a0cc598a90cf41edb4e9220Best regards & stay happy Fabrizio

Aber ich sehe die transferierten Defis nicht in/auf meiner Wallet!

Was läuft da falsch?
Bitte um Aufklärung.
Danke
lG Klaus
-- | --

**Comment by klauwein** [comment]
Was schreibt der da??? sorry ich habe ganz was anderes geschrieben!

Hallo, ich weis leider nicht wie ich diese Art von Hilfe richtig in Anspruch nehmen soll daher versuche ich es mit schreiben.

Ich habe eine Transaktion von Cake zur Defi APP gesendet, wie mir bestätigt wurde ist diese auch abgeschlossen!

  | Fabrizio (CAKE) 18.03.2021, 21:40 GMT + 8 Hey, danke für deine nette Nachricht und dein dir gehts gut.Laut Explorer sind dein DFI erforderlich, kannst du sterben noch nochmals Prüfen: https://explorer.defichain.com / # / DFI / mainnet / tx / 17d38aa1c919c175e3a83df28fa64cc409e3938d5a0cc598a90cf41edb4e9220Beste Grüße & bleib glücklich Fabrizio

Aber ich sehe die transferierten Defis nicht in / auf meiner Wallet.
Was lauft da falsch?
Bitte um Aufklärung.
Danke
lG Klaus

**Comment by RobinTorque** [comment]
Hallo Klaus, es wäre hilfreich von deiner Wallet einen Screenshot zu haben.

**Comment by izzycsy** [comment]
Hi @klauwein , from the link you provided, it seems like your transaction has not been confirmed yet. On Cake side has it shown that it has been transferred?
