### ISSUE TITLE
DeFi Wallet v2.3.2 does not import addresses.

### ISSUE THREAD

**Issue by luckythai** [DeFiCh/app#691]
#### What happened:
The addresses are not imported.
#### What you expected to happen:
The error only occurs with wallet 2.3.2.
#### How to reproduce it (as minimally and precisely as possible):
The error does not occur with the app 2.3.0 and 2.3.1.
also
With dual operation of the app 2.3.1 and wallet 2.3.2, the error occurs with 2.3.2 but not with 2.3.1.

1. When reinstalling the app and resetting the wallet.
On all tried ways and different systems.
2.  the wallet.dat has not yet been assigned a password.
but are backups of version 2.3.0 & 2.3.1. That can't be the problem with the backups.
3. Only the addresses created in 2.3.2 are no longer imported and can therefore no longer be used for additional actions in the app because they no longer appear and you have to generate new addresses.
#### What are your environment parameters?
- DeFi Wallet Version: 2.3.2
- Operating System (OS): ubuntu 18.04 & Windows10 with Ubuntu 18.04 WSL & ubuntu 18.04 Vm
#### Anything else we need to know?:
I would like to thank you for your commitment.

**Comment by izzycsy** [comment]
Hi @luckythai , please wait for the release to become official. Refer to [DeFiChain Announcements (EN)](https://t.me/defichain_announcements) and read the release notes before updating. In the mean time, keep your wallet.dat & passphrase safe. I'll update you again when we've officially released it.

**Comment by luckythai** [comment]
I already know that it is not an official app.
But I have now found a solution for myself. If you copy the contents of defi-app to the defi-wallet folder in the .config folder, the addresses in the 2.3.2 Wallet app also appear again.
This defi-app folder in the .config folder is particularly important for a backup in order to completely restore the wallet.

Thanks this issue can be closed.

**Comment by RobinTorque** [comment]
more information: https://defichain-wiki.com/wiki/V2.3.2#Wrong_addresses_are_displayed

**Comment by izzycsy** [comment]
Hi @luckythai , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

  Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
