### ISSUE TITLE
failed: A socket operation could not be performed because the system lacked buffer memory or a queue was full. (10055)

### ISSUE THREAD

**Issue by supervolot** [DeFiCh/app#695]
#### What are your environment parameters?

- DeFi Wallet Version: v.2.3.2
- Operating System (OS):WIN server 2009

**Comment by izzycsy** [comment]
Hi @supervolot , thanks for your feedback. Kindly send your app logs. If possible, do attach screenshots / screen recordings. This will provide more insight for the investigation. Thank you.
