### ISSUE TITLE
Error in CSV Export

### ISSUE THREAD

**Issue by MaReCoding** [DeFiCh/app#698]
#### What happened:
Exporting the Data from the Wallet to CSV file leads to inconsistent information in the CSV-Export. 
PoolSwap: Sometimes the second coin is missing
AddPoolLiquidity: Sometimes the LM-Token is missing. And sometimes the second coin and the LM-Token is missing

#### What you expected to happen:
All exported data should be consistent otherwise the CSV-Export is useless.
Poolswap: 2 Coins should be exported (In and Out Coin)
AddLiquidityMining: 3 Coins should be exported (Coin1 out / Coin2 out / LM-Token in)
RemoveLiquidityMining: 3 Coins should be exported (Coin1 in / Coin2 in / LM-Token out)

#### How to reproduce it (as minimally and precisely as possible):
Use a Wallet which has done some PoolSwaps and uses LiquidityMining. Than export the CSV-File and check it via TextEditor

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.2 (also happens on version 2.3.0 and 2.3.1)
- Operating System (OS): Win10

#### Anything else we need to know?:
Because of privacy I don't want to offer the original CSV-Export.

**Comment by izzycsy** [comment]
Hi @MaReCoding , thanks for your feedback, regarding the issue [Feat| Optimization of CSV export](https://github.com/DeFiCh/app/issues/640), we can further discuss on the problem there. Can you copy and paste your comment there please? We would like to keep same issues in one thread. Thank you.!
