### ISSUE TITLE
App does not load - now wallet gone

### ISSUE THREAD

**Issue by Dfichain-user** [DeFiCh/app#700]
My DFI-Chain app stopped working. It kept loosing connection to the nodes and then started downloading again the entire chain. After unistalling and reinstalling the app as well as trying >10x times downloading it now worked again but my backup wallet is gone. I have searched on my entire laptop but the file is not to be found.

#### What you expected to happen: Explanation why I cannot access my walltet anymore.

- DeFi Wallet Version: 2.3.0
- Operating System (OS): Windows 10

#### Anything else we need to know?:

 
[Uploading app logs.log…](
[app logs.log](https://github.com/DeFiCh/app/files/6188850/app.logs.log)
)
[binary logs.log](https://github.com/DeFiCh/app/files/6188855/binary.logs.log)

[binary logs.log](https://github.com/DeFiCh/app/files/6188867/binary.logs.log)

**Comment by izzycsy** [comment]
Hi @Dfichain-user , thanks for your feedback. update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

To find your wallet.dat files, it's in a hidden folder for security purposes. Please refer to the following route: 
Windows — `C: \Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat`

<img width="626" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/112138706-ce165b80-8c0c-11eb-9404-32b537e7af40.png">

Make a backup of your wallet folder before updating to v2.3.2.

**Comment by izzycsy** [comment]
Hi @Dfichain-user , regarding the issue [`Unable to start app`](https://github.com/DeFiCh/app/issues/703), we can further discuss on the problem there. We would like to keep same issues in one thread. Thank you.

**Comment by peteinvests** [comment]
how did this get solved, sounds similar to mine

**Comment by Dfichain-user** [comment]
> how did this get solved, sounds similar to mine

Hey @peteinvests ,
unfortunately my issue did not get resolved. I was really passionate about the DFI-Chain project and performed Liquidity Mining almost every day. However due to this incident I lost all my money stored in the wallet! It might have been irresponsible that I trusted the backup file and did not note down the seed. Yet it is still very frustrating to see all my money lost, so I would you advise you to be very careful with the app. I hope you get a more valuable support from the DFI Team than they provided for me and find a solution to get your money back. All the best
