### ISSUE TITLE
Copy and Paste is not working insinde CLI

### ISSUE THREAD

**Issue by Mafiat0m** [DeFiCh/app#701]
#### What happened:
Copy a Console syntax an tyred to paste the syntax with STRG-V in the CLI Console - nothing happend.

#### What you expected to happen:
Te Copied syntax to be pasted into the CLI Command Line.

#### How to reproduce it (as minimally and precisely as possible):
Try STRG-C and STRG-V in the CLI Console - will not work.
Try the same when hitting the Copy and Paste in the Edit menue - will work.

Try to copy this syntax `getbalance`  by mark the syntax and hit STRG-C.
Open the CLI Console in the DeFiCh App, open the CLI Console and hit STRG-V. (nothing will happen)
Instead of using STRG-V now click on Menu Edit and Paste. (Will work, the copied syntax will be pasted)

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.2
- Operating System (OS): Windows

#### Anything else we need to know?:
Is it possible to write in Germen?

**Comment by Stonygan** [comment]
Try Shift+INS (Shift+Einfg)

**Comment by Mafiat0m** [comment]
Tryed Shift+INS - Worked. 

But then the Edit Menu is wrong.
![image](https://user-images.githubusercontent.com/81232361/112151097-1fa8f100-8be1-11eb-9875-32906914d2c6.png)

**Comment by supervolot** [comment]
It worked for me to click the right mouse button in the command line and then the STRG-V workes

**Comment by memzila** [comment]
The same for me. CTRL+V not working. I can only paste command via the menu. CTRL+V should work in the CLI like in any other windows program

**Comment by izzycsy** [comment]
Hi @Mafiat0m @memzila , [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a **mandatory update**. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by memzila** [comment]
It is still the same behavior in actual version

**Comment by izzycsy** [comment]
Hi @memzila , did you try `Shift+INS`?

**Comment by memzila** [comment]
Hi @izzycsy Shift+Ins works, but it should work like in every other available windows programm out there. At least it should be reflected in the menu with the copy commands.
![grafik](https://user-images.githubusercontent.com/48082176/122399475-20041e80-cf7b-11eb-8330-8dd3ca34e792.png)
