### ISSUE TITLE
Almost all Receive addresses disappeared after update to 2.3.2

### ISSUE THREAD

**Issue by bebosudo** [DeFiCh/app#702]
#### What happened:

I've made a backup of my wallet and updated the app to 2.3.2, as suggested; I was able to read the previous wallet fine, but when I now go to Balances > DFI > Receive I only see the first address I ever created.
In the previous version of the app I used other addresses as receiving addresses for liquidity mining shares, but then I changed the allocations on my wallet, so I don't know whether I'm currently sending rewards from the liquidity mining to a black hole (this would also be useful to see in the wallet).

#### What you expected to happen:

See all receive address I created with 2.3.0.

#### How to reproduce it (as minimally and precisely as possible):

- Create multiple addresses in a 2.3.0 wallet
- Open the wallet with 2.3.2 and only the first address is visible
- 
#### What are your environment parameters?

- DeFi Wallet Version: 2.3.2
- Operating System (OS): Fedora Linux 30 (via AppImage)

**Comment by thedoublejay** [comment]
Hi @bebosudo, the addresses are stored locally on the old app. We have made a change to store it on the blockchain folder for v2.3.2 for better safekeeping. These addreses are still yours, you can just re-add them on your app.

**Comment by bebosudo** [comment]
Ok, good to know, thanks @thedoublejay.
I would have appreciated this to be part of the release notes, though.

Is there a way to extract the older addresses from the old local config/wallet? I'm on linux and the 2.3.0 release doesn't like the 2.3.2 data in `~/.defi/` probably because it's not backward compatible (a popup appears titled "Configuration failure" and with text "No data found"). I'd prefer to avoid deleting the .defi dir and resync the blockchain on the 2.3.0 app, which takes hours even when using a snapshot.

**Comment by bebosudo** [comment]
I exported the last 1M transactions in DFI as a csv and extracted all the most recent addresses with:
```
$ cut -d, -f4 Transactions_XXX.csv |sort |uniq
```

And then I manually readded those addresses back into the wallet of the 2.3.2 app.

How can I be sure that I also have the private key for those addresses? Is it stored inside the wallet.dat file?
Or is it automatically calculated based from a common generator seed?

**Comment by Darkman-Q-Tester** [comment]
> 
> 
> Hi @bebosudo, the addresses are stored locally on the old app. We have made a change to store it on the blockchain folder for v2.3.2 for better safekeeping. The missing addresses are still yours, you can just re-add them on your app.

Hi @thedoublejay ,
I'm also missing my main address but funds are still displayed in version 2.3.2.
How to "just re-add them on your app" ?

**Comment by bebosudo** [comment]
To add them back I did as you did @Darkman-Q-Tester; Balances > DFI > Receive > New address > Toggle the button that creates a new random address, and entered the previous addresses.
I noticed that if I try adding an address that's not mine it says to double check if I really control that address, so I guess it uses some kind of "generator" to create and control public and private addresses.

**Comment by Darkman-Q-Tester** [comment]
> 
> 
> > Hi @bebosudo, the addresses are stored locally on the old app. We have made a change to store it on the blockchain folder for v2.3.2 for better safekeeping. The missing addresses are still yours, you can just re-add them on your app.
> 
> Hi @thedoublejay ,
> I'm also missing my main address but funds are still displayed in version 2.3.2.
> How to "just re-add them on your app" ?



> 
> 
> To add them back I did as you did @Darkman-Q-Tester; Balances > DFI > Receive > New address > Toggle the button that creates a new random address, and entered the previous addresses.
> I noticed that if I try adding an address that's not mine it says to double check if I really control that address, so I guess it uses some kind of "generator" to create and control public and private addresses.

Hi @bebosudo,
yes worked for me. Address is back and working.
Thank you

**Comment by izzycsy** [comment]
Hi @bebosudo @Darkman-Q-Tester I'll be closing this issue in the mean time, if your issues persists, please send new information (include screenshots) and app logs. Thank you
