### ISSUE TITLE
Unable to start app

### ISSUE THREAD

**Issue by monkeyman19112** [DeFiCh/app#703]
#### What are your environment parameters?

- DeFi Wallet Version: 2.3.2
- Operating System (OS): windows 10

**Comment by monkeyman19112** [comment]
i cant even open the app no one else has this problem.

**Comment by MarsaXod** [comment]
I have the same issue after installation v.2.32 app doesn't start. Freeze on logo page. 
![Capture](https://user-images.githubusercontent.com/77227016/112342456-84884800-8cc2-11eb-9ec7-c0d26a0827d9.JPG)

**Comment by monkeyman19112** [comment]
How do I fix this issue?

**Comment by thedoublejay** [comment]
@monkeyman19112  Can you generate your logs and attach them here?

**Comment by monkeyman19112** [comment]
I can not. The app stopped opening up completely

**Comment by thedoublejay** [comment]
@monkeyman19112 You can click on the menu bar -> Logs -> App & Binary Logs.
![image](https://user-images.githubusercontent.com/25013382/112422976-bce46080-8d6c-11eb-8d71-78daecb68471.png)

**Comment by monkeyman19112** [comment]
I know that. The problem is the app won’t open at all.

**Comment by thedoublejay** [comment]
Hi @monkeyman19112, ok sorry I mislook @MarsaXod screenshot. For your issue, what happens when you open the app? Do you have any anti-virus or firewall that might prevent the app from opening?

**Comment by monkeyman19112** [comment]
I haven’t checked the firewalls or antivirus yet.

**Comment by MarsaXod** [comment]
Good day Support,

I have uninstalled complete app, prior saved wallet backup dat file in another place. Reinstall defi app. The same issue. Firewall is off and antivirus AVG also off. pls see applog attached below.

[applog 2.3.2.log](https://github.com/DeFiCh/app/files/6203547/applog.2.3.2.log)

**Comment by izzycsy** [comment]
Hi @monkeyman19112  @MarsaXod , thanks for your feedback, a few questions to understand what may be the cause: 
• May I know you have new folders named `defi-wallet` & `DeFi Blockchain` respectively? (you can take a screenshot so it's easier to refer to)
To find the files on Windows: 
`C:\Users\<username>\AppData\Roaming\DeFi Blockchain\`

• where did you specify to install the DeFi Wallet?

**Comment by MarsaXod** [comment]
Hi @izzycsy,

pls see attached screenshot. I have installed app in C:\Program Files\DeFi Wallet

![Capture1](https://user-images.githubusercontent.com/77227016/112455315-e5af2a80-8d59-11eb-98cc-86679a6b726f.JPG)

**Comment by thedoublejay** [comment]
@MarsaXod There's an error on your wallet_map.json. Can you help me check your DeFi Blockchain > wallets > wallet_map.json file? Try to delete it and run the app again. Thanks!

**Comment by izzycsy** [comment]
Hi @MarsaXod , before you delete anything, please keep a copy of your `wallet.dat`.

**Comment by MarsaXod** [comment]
Hello @izzycsy  @thedoublejay ,

All works now, I have saved walet.dat and then deletee wallet_map.json file. 
Thanks for your great support

**Comment by izzycsy** [comment]
Hi @monkeyman19112 , [v2.3.3](https://github.com/DeFiCh/app/releases/tag/v2.3.3) is out. Please read through the release notes before updating. If you have not sync to 100%, there was a node issue on 05/04/2021 that may have cause the `network error`, everything is back online now, you may try the following: 

**Option 1 — Reset & Reindex (sync from 0%)**
1. Settings > `Reset & Reindex` 

<img width="790" alt="Settings   Reset   Reindex" src="https://user-images.githubusercontent.com/65014479/113691297-ddae9d80-96fe-11eb-85e8-a888f16a8df3.png">

 
**Option 2 — Snapshot (sync from 90%+)**
1. Settings > `Reset & Reindex` 
2. Wait for app to start syncing
3. Ensure you’ve at least 27GB of extra space
2.  Click on `i` located at bottom-left corner of app screen 
3. Download Snapshot

<img width="244" alt="`i` to trigger Snapshot download" src="https://user-images.githubusercontent.com/65014479/113691572-2403fc80-96ff-11eb-94c9-1e7ebafd697f.png">

Let me know your results, thank you for your patience.
