### ISSUE TITLE
Stuck on blockHeight 733229 / 733230 

### ISSUE THREAD

**Issue by supervolot** [DeFiCh/app#706]
#### What happened: the chain start getting corrupt see debug file 
2021-03-25T15:06:59Z UpdateTip: new best=48664522bf6408560f80fa153a8e1cbe5485e33b04f15776ae6fd634a94eee3d height=733230 version=0x20000000 log2_work=79.646165 tx=2039000 date='2021-03-25T11:34:51Z' progress=0.998852 cache=0.0MiB(0txo)
2021-03-25T15:06:59Z UpdateTip: new best=2b4d4a765707b6543956a8619b7fa418b5cd5eee5311a2ee0afa77285fd07a1c height=733229 version=0x20000000 log2_

#### What are your environment parameters?

- DeFi Wallet Version: v.2.3.2
- Operating System (OS):WINdows server 2009

**Comment by izzycsy** [comment]
Hi @supervolot , thanks for your feedback, there might not anything wrong with the binary log portion you sent. Please send full app log, binary log and app config so it'll help us investigate. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/112624723-eda9c000-8e68-11eb-8f87-ccf032cef305.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/112624737-f13d4700-8e68-11eb-9ef9-bd796634971b.png">

If you're stuck on block 733229 / 733230 you can try to reindex and see if it syncs to 100%. 

![Reindex   saving + delete peers and blocks](https://user-images.githubusercontent.com/65014479/112624659-e1256780-8e68-11eb-9e3f-03a4dfaa1bff.gif)


<img width="778" alt="Reindex   saving + delete peers and blocks" src="https://user-images.githubusercontent.com/65014479/112624646-dec30d80-8e68-11eb-99e5-5b547589e3b1.png">

**Comment by izzycsy** [comment]
Hi @supervolot , regarding the issue [`Sync stuck at 98%+ / blockHeight 733594`](https://github.com/DeFiCh/app/issues/673), we can further discuss on the problem there. We would like to keep same issues in one thread. Thank you.
