### ISSUE TITLE
Adding Liquidity not possible (LTC/DFI Pool) and LTC are gone

### ISSUE THREAD

**Issue by jokerty1** [DeFiCh/app#707]
Hey Defi Team,

Since yerterday i have a Problem with my Defi APP ... i send LTC from Cake do Defi-Wallet und DFI from Bittrex to DFI Wallet and than i wanted to add it into the LTC/DFI Liquidity Pool .... got always an Error (Screenshot)
after that i tried almost everything ... updated the Wallet from Version 2.3.0 to 2.3.2 ... did not work... reindexing dident work...
i installed the app on an other pc und recoverd with the seed ( than my LTC are gone ) the transaktions i made aren not right in the wallet ... can not unterstand that ... and also my Liquidity witch is already added is not working anymore ?? 
please help me out with that ... realy lot of LTC and DFI i have in the wallet ....
[defilogs.zip](https://github.com/DeFiCh/app/files/6210765/defilogs.zip)
![IMG_4277](https://user-images.githubusercontent.com/81413779/112613352-4b65ea00-8e20-11eb-9e5e-b08a4ecbc70c.JPG)

**Comment by izzycsy** [comment]
Hi @jokerty1 , thanks for your feedback. Can you try Restore Wallet from Backup (wallet.dat). 

<img width="1019" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/112625126-745e9d00-8e69-11eb-9197-64951c81a883.png">

To find your wallet.dat files: 
Windows — C: 
`\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat`

So long as you've your wallet.dat & passphrase your funds are safe.

**Comment by izzycsy** [comment]
Hi @jokerty1 , if your app is not synced to 100% yet — it needs reach 100% before you can `Restore wallet from backup`. There was a node issue on 05/04/2021 that may have cause the `network error`, everything is back online now, you may try the following: 

**Option 1 — Reset & Reindex (sync from 0%)**
1. Settings > `Reset & Reindex` 

<img width="790" alt="Settings   Reset   Reindex" src="https://user-images.githubusercontent.com/65014479/113691297-ddae9d80-96fe-11eb-85e8-a888f16a8df3.png">

 
**Option 2 — Snapshot (sync from 90%+)**

1. Ensure you’ve at least 27GB of extra space
2.  Click on `i` located at bottom-left corner of app screen 
3. Download Snapshot

<img width="244" alt="`i` to trigger Snapshot download" src="https://user-images.githubusercontent.com/65014479/113691572-2403fc80-96ff-11eb-94c9-1e7ebafd697f.png">

Thank you for your patience.

**Comment by jokerty1** [comment]
hey

the problem is that my Harddisk c:\ is to small ... is it possible to 
move it on a other Drive ?

i know the defichain-wiki for it - but it dont work with version 2.3.3 ?


Greeds Chris


Am 07.04.2021 um 14:02 schrieb Bella:

**Comment by izzycsy** [comment]
Hi @jokerty1 , you can try, just ensure that you `wallet.dat` & `passphrase` is backup-ed and safe. Our team is working on reducing the storage size, which might be released in future versions.

**Comment by John-Gee** [comment]
Even when an app does not support relocation, you can do it yourself with links. I don't use Windows, but I believe it is called a junction there cf: https://docs.microsoft.com/en-us/windows/win32/fileio/hard-links-and-junctions

so you'd see a folder like c:\defi but it's really just some link to the real folder in d:\defi .

**Comment by izzycsy** [comment]
Hi @jokerty1 , [v2.3.4](https://github.com/DeFiCh/app/releases/tag/v2.3.4) is out. Please read through the release notes before updating. Kindly save your wallet.dat and proceed to update, see if your issue has been resolved, if it's not, please send new information (include screenshots) and app logs. Thank you. 

@John-Gee for Windows there's a guide here https://defichain-wiki.com/wiki/Blockchain_folder

**Comment by izzycsy** [comment]
Hi @jokerty1 , update [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
