### ISSUE TITLE
Suggestion for improvement in the symbols

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#708]
I noticed that CAKE DEFI and DeFi Wallet use conflicting symbols. 

<img width="888" alt="Bildschirmfoto 2021-03-27 um 13 57 42" src="https://user-images.githubusercontent.com/65536965/112721519-7f1a4000-8f04-11eb-88df-c3480cab07ad.png">

Inflowing capital is marked on CAKE with an arrow pointing upwards. Outflowing capital with an arrow pointing downwards. 

<img width="520" alt="Bildschirmfoto 2021-03-27 um 14 00 11" src="https://user-images.githubusercontent.com/65536965/112721560-c4d70880-8f04-11eb-8330-d23095d0bf41.png">

In DeFi Wallet it is the other way around. Inflowing capital is marked with an arrow pointing down. Outflowing capital is marked with an arrow pointing upwards. 

Even though CAKE and the DeFi app are two different things, I would recommend using a consistent standard. 

Further, I would refrain from showing send and receive separately if it was just a wallet internal transaction. 

<img width="724" alt="Bildschirmfoto 2021-03-27 um 14 02 33" src="https://user-images.githubusercontent.com/65536965/112721844-63179e00-8f06-11eb-8ad6-a430438a770c.png">

My suggestion how this transaction could be displayed:

<img width="783" alt="Bildschirmfoto 2021-03-27 um 14 18 35" src="https://user-images.githubusercontent.com/65536965/112722023-69f2e080-8f07-11eb-8837-90dcaa4f8c6e.png">

**Comment by izzycsy** [comment]
Hi @RobinTorque , thanks for your feedback.
