### ISSUE TITLE
Execution test failed: ApplyAddPoolLiquidityTx: tx must have at least one input from account owner

### ISSUE THREAD

**Issue by rene-sch** [DeFiCh/app#709]
Hello everybody.
I updated to version 2.3.2 a few days ago. Since then I have had problems swapping in DEX and adding liquidity to mining. Sometimes I manage to add a small amount after starting the app several times.
The error message that appears is: "Execution test failed: ApplyAddPoolLiquidityTx: tx must have at least one input from account owner"

**Comment by rene-sch** [comment]
I also checked getbalance and gettokenbalances in my CLI and sent DFI to myself. Unfortunately, this has not resulted in any improvement.
I am using Windows 10

**Comment by izzycsy** [comment]
Hi @rene-sch , was the output of your `getbalance` more than 1 DFI? Are your address / addresses present in your wallet? Kindly send your app logs please. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/112804560-246d1980-90a7-11eb-9273-929c4a35feca.png">
<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/112804578-29ca6400-90a7-11eb-8ece-6245a012d6ec.png">

**Comment by rene-sch** [comment]
hi @izzycsy  thanks for your quick reply. My addresses are present in my wallet. When I type getbalance into the console, I get 98 DFI
[App Config.zip](https://github.com/DeFiCh/app/files/6226688/App.Config.zip)

**Comment by izzycsy** [comment]
Hi @rene-sch , well received, please give us time to investigate this issue.

**Comment by rene-sch** [comment]
Hello @izzycsy 
Sorry for my late answer. When I enter the command in the CLI, will my private key also be displayed? or can I just copy the values ​​"Key, Owner and Amount" into here?

The only thing that is currently possible is that I can swap small amounts (max. 25 DFI) in the DEX. If I want to add liquidity, the above message appears

Thanks for your time

**Comment by izzycsy** [comment]
Hi @rene-sch , no I do not need your private key, and yes you can just copy and paste the values here, you can change the `key` & `owner` to _xxx_. I need to understand how your tokens are broken down so I can advice on the issue. I'll provide an example below. 

```
  {
    "key": "76a9xxx@0",
    "owner": "dTsOxxx",
    "amount": "0.00008024@DFI"
  },
  {
    "key": "76a9xxx@6",
    "owner": "8JaZxxx",
    "amount": "0.00000180@USDT-DFI"
  },
    {
    "key": "76a9xxx@2",
    "owner": "dTsOxxx",
    "amount": "0.000001234@BTC"
  },
```

**Comment by rene-sch** [comment]
Hello @izzycsy 
  Okay :) sorry for my stupid question. Below is the breakdown:)

{
    "key": "a914xxx@0",
    "owner": "dGAKxxx",
    "amount": "113.07613066@DFI"
  },
  {
    "key": "a914xxx@1",
    "owner": "dGAKxxx",
    "amount": "0.00000259@ETH"
  },
  {
    "key": "a9141xxx@2",
    "owner": "dGAKxxx",
    "amount": "0.00004990@BTC"
  },
  {
    "key": "a914xxx@3",
    "owner": "dGAKxxx",
    "amount": "7.00420025@USDT"
  },
  {
    "key": "a914xxx@4",
    "owner": "dGAKxxx",
    "amount": "0.30764518@ETH-DFI"
  },
  {
    "key": "a914xxx@5",
    "owner": "dGAKxxx",
    "amount": "91.07174998@BTC-DFI"
  },
  {
    "key": "a914xxx@6",
    "owner": "dGAKxxx",
    "amount": "3842.01697993@USDT-DFI"
  },
  {
    "key": "a914xxx@9",
    "owner": "dGAKxxx",
    "amount": "0.00042822@LTC"
  },
  {
    "key": "a9141xxx@10",
    "owner": "dGAKxxx",
    "amount": "19.50598843@LTC-DFI"
  },
  {
    "key": "a914xxx@11",
    "owner": "dGAKxxx",
    "amount": "0.00032111@BCH"
  },
  {
    "key": "a914xxx@12",
    "owner": "dGAKxxx",
    "amount": "12.43187336@BCH-DFI"
  },
  {
    "key": "a914xxx@0",
    "owner": "dJYQxxx",
    "amount": "8.60166084@DFI"
  },
  {
    "key": "a914xxx@2",
    "owner": "dJYQxxx",
    "amount": "0.02855106@BTC"
  },
  {
    "key": "a914xxx@3",
    "owner": "dJYQxxx",
    "amount": "0.00612143@USDT"
  },
  {
    "key": "a914xxx@5",
    "owner": "dJYQxxx",
    "amount": "3.87686564@BTC-DFI"
  },
  {
    "key": "a914xxx@6",
    "owner": "dJYQxxx",
    "amount": "8.04094672@USDT-DFI"
  },
  {
    "key": "a914xxx@0",
    "owner": "dJgTxxx",
    "amount": "105.40398639@DFI"
  },
  {
    "key": "a914xxx@2",
    "owner": "dJgTxxx",
    "amount": "0.00000171@BTC"
  },
  {
    "key": "a914dxxx@2",
    "owner": "dZWWxxx",
    "amount": "0.00012015@BTC"
  },
  {
    "key": "a914dxxx@9",
    "owner": "dZWWxxx",
    "amount": "0.00193282@LTC"
  },
  {
    "key": "a914dxxx@11",
    "owner": "dZWWxxx",
    "amount": "0.00547770@BCH"
  },
  {
    "key": "76a9xxx@0",
    "owner": "8F8Qxxx",
    "amount": "2.21856240@DFI"
  },
  {
    "key": "76a9xxx@1",
    "owner": "8F8Qxxx",
    "amount": "0.00000236@ETH"
  },
  {
    "key": "76a9xxx@2",
    "owner": "8F8Qxxx",
    "amount": "0.00000342@BTC"
  },
  {
    "key": "76a9xxx@3",
    "owner": "8F8Qxxx",
    "amount": "0.14240031@USDT"

**Comment by izzycsy** [comment]
Hi @rene-sch , I'm here to help. Ok these are the addresses that contain DFI, which of it do you want to use for DEX and add liquidity?

```
{
"key": "a914xxx@0",
"owner": "dGAKxxx",
"amount": "113.07613066@DFI"
},
{
"key": "a914xxx@0",
"owner": "dJYQxxx",
"amount": "8.60166084@DFI"
},
{
"key": "a914xxx@0",
"owner": "dJgTxxx",
"amount": "105.40398639@DFI"
},
{
"key": "76a9xxx@0",
"owner": "8F8Qxxx",
"amount": "2.21856240@DFI"
},
```

**Comment by rene-sch** [comment]
@izzycsy until now I've used mostly the second (dJYQxxx)

**Comment by rene-sch** [comment]
> @izzycsy until now I've used mostly the second (dJYQxxx)

but it dosent matter which one

**Comment by izzycsy** [comment]
@rene-sch ok, when you use DEX and `dJYQxxx`, try to leave at least 3 DFI in the address, reason being, when you DEX — DFI fee is take, when you add liquidity — DFI fee is taken again, when you remove liquidity — DFI fee is taken again, and when you send out which token under `dJYQxxx` — DFI fee is taken. If you've insufficient utxoDFI you'll need to

Send 1 DFI to yourself:
1. copy your address (`dJYQxxx`)
2. Go to send DFI
3. 1 DFI
4. Paste the address `dJYQxxx`
5. Try the function again

The app should automatically find DFI in your various addresses but this method should work as well. The team is in the midst of improving the UX.

**Comment by rene-sch** [comment]
@izzycsy 
sending DFI to myself works without problems. I still can't add any liquidity though. The message "Execution test failed: ApplyAccountToAccountTx: tx must have at least one input from account owner" always appears.
Sometimes it works to add small parts to DFI (max. 25) but not always.

I have sent myself DFI several times (sometimes 1, sometimes 10) unfortunately without success

**Comment by izzycsy** [comment]
@rene-sch what's the liquidity ratio that you're trying to add? I'll try to reproduce it on my end.

**Comment by rene-sch** [comment]
@izzycsy Usually it works 3 - 5 times to add small amounts. (BTC - DFI) Now 25 and 50 worked out. Any others not

**Comment by rene-sch** [comment]
@izzycsy even if I send myself DFI again, it doesn't work

**Comment by izzycsy** [comment]
Hi @rene-sch , ok can you send me your app log, binary log & app config? .zip it and send here. Please give me time to investigate, thank you.

**Comment by rene-sch** [comment]
[App Config.zip](https://github.com/DeFiCh/app/files/6296958/App.Config.zip)

**Comment by rene-sch** [comment]
Hi @izzycsy, now i can't add any more liquidity at all.
Do you think it would help to uninstall and reinstall the entire wallet?

**Comment by izzycsy** [comment]
Hi @rene-sch , unlikely reinstalling will solve the issue, and if you reinstall you'll have to sync from 0% — which is going to be a pain. What's your `getbalance` at the moment?

**Comment by rene-sch** [comment]
@izzycsy thanks for your quick response.

98.58886876

**Comment by rene-sch** [comment]
@izzycsy but it´s also painful not to be able to reinvest :D 
are you sure that a new installation would help?

**Comment by izzycsy** [comment]
Hi @rene-sch , you can try to reinstall the app, if you do decide to I've a guide here: https://github.com/DeFiCh/app/issues/733 

Please keep a copy of your `wallet.dat`, the routes as stated: 
Windows — C:
`\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\`

Mac — Go To Folder: 
`/Users/<username>/Library/Application Support/Defi/wallets/`

Actually, if you're still on v2.3.2, the issue might be resolved if you updated to v2.3.3.
To update: https://github.com/DeFiCh/app/releases/tag/v2.3.3

**Comment by xavschw** [comment]
Hello, 

I am faced to the same issue with version 2.3.3 of App DeFi on WIndows 10.
I just re-download the blocks from the snapshot. Before I did have this trouble.

![image](https://user-images.githubusercontent.com/74258325/115712059-b08efb80-a34a-11eb-818d-faff0c10d780.png)

In attachment, you will have the App logs.zip.

Also, is it normal that I do not have the same amount of DFI shown in the DFI wallet and shown by the CLI command "getbalance"? It is about 10 times less displayed with the command comparing to the value displayed in the DFI wallet.

Thank you !

Regards,

[app logs.zip](https://github.com/DeFiCh/app/files/6358320/app.logs.zip)

**Comment by izzycsy** [comment]
Hi @xavschw , can you try this via CLI: 

`getbalance` — utxoDFI
`gettokenbalances` — accountDFI

The sum of utxoDFI & accountDFI would be your total DFI tokens.

**Comment by izzycsy** [comment]
Hi @rene-sch , may I have your output of the following please:

`getbalance` — utxoDFI
`gettokenbalances` — accountDFI

**Comment by marathom** [comment]
Same issue here. When will the Light Wallet be released?

**Comment by xavschw** [comment]
Hi @izzycsy, thank you for your answer !

Finally it seems to me that the problem is solved.
I used the function "Reset and Reindex" to delete peers/block data and rebuild the database from the last snapshot.

OK I tried the cammand "gettokenbalances", all my values correspond to the values displayed on the wallet (BTC, LTC, USDT, pool DFI-BTC, DFI-LTC, DFI-USDT) except for DFI where there is a difference about 16 DFI less seen on the console.
For you what should be the right value ? The one displayed on the console or on the wallet ?

Thank you !

**Comment by xavschw** [comment]
Also, I am not sure it is the right post but I have an issue when I want to add liquidity.

![image](https://user-images.githubusercontent.com/74258325/115885808-ad693d80-a426-11eb-8260-332078b00769.png)

Do you have any idea to solve it ?

Thank you !

**Comment by izzycsy** [comment]
Hi @xavschw , can you send the follow output to the link provided below: 
Type in CLI: 
`getbalance` — utxoDFI
`gettokenbalances` — accountDFI

The sum of utxoDFI & accountDFI would be your total DFI tokens.
[`v2.3.3 Unable to add liquidity`](https://github.com/DeFiCh/app/issues/704) 

We can further discuss on the issue there. Let’s keep this thread related to what the original author opened. Thank you for your understanding.

**Comment by xavschw** [comment]
OK thanks for your answer @izzycsy !
Yes sure.

**Comment by izzycsy** [comment]
Hi @marathom , apologies missed out on your message. I do not have a expected date for you, but when it's ready it'll be announced on [DeFiChain Announcements (EN)](https://t.me/defichain_announcements).

**Comment by cyrus1683** [comment]
Hello,

I have nearly the same problem. I can't get out of my Liquidity Mining and got this similar error:

**Execution test failed: ApplyRemovePoolLiquidityTx: tx must have at least one input from account owner**

I tried it with every address I have and also with small amounts, but no chance.

Please help me with this problem.

Thanks a lot!
Daniel

**Comment by izzycsy** [comment]
Hi @cyrus1683 , can you check your balances via CLI: 
`getbalance` — utxoDFI
`gettokenbalances` — accountDFI

If your `getbalance` is < 1,  you've insufficient utxoDFI balance (min. 1 DFI) — which is required to perform swap and all other functions. DFI exist in 2 forms; `utxoDFI` and `accountDFI`. utxoDFI is used to pay for transactions fees while rewards received from liquidity mining (for example) are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. To convert accountDFI to utxoDFI, the simplest way would be via DeFi Wallet app. I'll guide you how after your reply.

**Comment by cyrus1683** [comment]
Hi @izzycsy 

I know and I have enough, so this could not be the problem:

getbalance
34.93466705
gettokenbalances
[
  "152.71732610@0",
  "0.06156399@9",
  "178.21506061@10",
  "118.00000000@167"
]

I attach my log files, maybe that helps.
It's really frustraiting to no be able to get the coins under my control :-(
 
[applog.log](https://github.com/DeFiCh/app/files/6448366/applog.log)

[binarylog.log](https://github.com/DeFiCh/app/files/6448365/binarylog.log)

Thanks a lot

kind regards
Daniel

**Comment by izzycsy** [comment]
Hi @cyrus1683 , thanks the logs, please give us time to investigate. Try adding / remove liquidity with a smaller amount, it's the current workaround. Do you have multiple addresses or just one?

**Comment by cyrus1683** [comment]
Hi @izzycsy 

I tried it again and looked in the debug.log and when the error message in the app appears, this is the output from debug log. Maybe that helps:

2021-05-10T15:43:36Z [wallet.dat] Fee Calculation: Fee:13320 Bytes:185 Needed:13320 Tgt:0 (requested 6) Reason:"Fallback fee" Decay 0.00000: Estimation: (-1 - -1) -nan% 0.0/(0.0 0 mem 0.0 out) Fail: (-1 - -1) -nan% 0.0/(0.0 0 mem 0.0 out)

**Comment by izzycsy** [comment]
Hi @cyrus1683 , can you provide the output of `listaccounts {} false false true` — breakdown of your token(s). I would like to understand whether there's sufficient DFI in your addresses.

**Comment by cyrus1683** [comment]
Hi @izzycsy 

sorry, I had another problem, the blockchain was broken and I hat to sync again.
But now with the release of 2.3.4 it worked with a little amount :-)

here the output of the accounts:

[
  {
    "key": "a9141b0d001b54ed991487058761e09bd02ea8e66c1a87@0",
    "owner": "dFtKSEkcSaKKs8ich4bEGZWfKFfo9C7ZfS",
    "amount": "22.52602740@DFI"
  },
  {
    "key": "a9141b0d001b54ed991487058761e09bd02ea8e66c1a87@9",
    "owner": "dFtKSEkcSaKKs8ich4bEGZWfKFfo9C7ZfS",
    "amount": "0.06553298@LTC"
  },
  {
    "key": "a9144f76294934e34cbd9a7a7346e26a9ba3a456470b87@167",
    "owner": "dLfSYvAgUTuj3j16WhdVhX68hKfBAn3hxE",
    "amount": "59.00000000@GOLD#167"
  },
  {
    "key": "a914716483a540650a45a6b9f702fc9827c6c1803f3587@0",
    "owner": "dPkrPJVSEfzZGfnyVpDNpsvwj8EiXPa16S",
    "amount": "188.04086655@DFI"
  },
  {
    "key": "a914716483a540650a45a6b9f702fc9827c6c1803f3587@9",
    "owner": "dPkrPJVSEfzZGfnyVpDNpsvwj8EiXPa16S",
    "amount": "0.28809589@LTC"
  },
  {
    "key": "a914716483a540650a45a6b9f702fc9827c6c1803f3587@10",
    "owner": "dPkrPJVSEfzZGfnyVpDNpsvwj8EiXPa16S",
    "amount": "175.72004976@LTC-DFI"
  },
  {
    "key": "a914716483a540650a45a6b9f702fc9827c6c1803f3587@167",
    "owner": "dPkrPJVSEfzZGfnyVpDNpsvwj8EiXPa16S",
    "amount": "59.00000000@GOLD#167"
  }
]

thanks
Daniel

**Comment by izzycsy** [comment]
Hi @rene-sch @xavschw @marathom @cyrus1683, [v2.3.5](https://github.com/DeFiCh/app/releases/tag/v2.3.5) is out. Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.

**Comment by izzycsy** [comment]
Hi @cyrus1683 , based on your output,

```
{
"key": "a914xxx@0",
"owner": "dFtKxxx",
"amount": "22.52602740@DFI"
},
{
"key": "a914xxx@0",
"owner": "dPkrxxx",
"amount": "188.04086655@DFI"
}
```
I'm assuming you're trying to add liquidity for DFI-LTC, it could be LTC price that's high so it's insufficient to add liquidity. You can try to convert more / max of your `tokenDFI` to `utxoDFI`. In v2.3.5, you'll be able to see the the breakdown. 

<img width="987" alt="utxoDFI   tokenDFI" src="https://user-images.githubusercontent.com/65014479/118403550-86a6cb80-b6a1-11eb-978b-eea4e53c915e.png">

Try convert tokenDFI to utxoDFI again:

From your output:
```
gettokenbalances
[
  "152.71732610@0", — tokenDFI
  "XXXXXXXXXX@2",
  "XXXXXXXXXX@5"
]
```
To send more/max tokenDFI to yourself:

1. Copy your address (`dPkrxxx`)
2. Click send DFI
3. Input 1 DFI
4. Paste the address `dPkrxxx`
5. Try the function again

By sending to yourself, you're converting your tokenDFI to utxoDFI. utxoDFI is used for transaction fees.

**Comment by rene-sch** [comment]
> Hi @rene-sch @xavschw @marathom @cyrus1683, [v2.3.5](https://github.com/DeFiCh/app/releases/tag/v2.3.5) is out. Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.

Hi @izzycsy After updating to version 2.3.5, It was shown a corrupt blockchain. A new synchronization stopped at 95.99%. Now I'm in the process of downgrading to 2.3.3 again

**Comment by izzycsy** [comment]
Hi @rene-sch , the last few nodes will take time to sync — took me an hour. You can try to add node. In [DeFiChain-Wiki](https://defichain-wiki.com/wiki/Addnode) the article guides you on how to do this, or simply try via the CLI:
`addnode "seed.mydeficha.in:8555" add`

**Comment by izzycsy** [comment]
Hi @rene-sch @xavschw @marathom @cyrus1683 , update [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.

**Comment by rene-sch** [comment]
Hey @izzycsy, i have updated to 2.4.0. Everything works fine. the one thing is that it feels like the app is running slower than usual. 
You did a great job! Thank you

**Comment by izzycsy** [comment]
Hi @rene-sch @xavschw @marathom @cyrus1683 , [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**. Please read through the release notes before updating. Speed should be improved in this update. Thank you.
