### ISSUE TITLE
Mac 2.3.2: Stuck at 0% synchronization

### ISSUE THREAD

**Issue by saurin13** [DeFiCh/app#710]
#### What are your environment parameters?

- DeFi Wallet Version:  app version 2.3.2 for mac
- Operating System (OS):  macos 11.2.3

#### Anything else we need to know?:  using macbook pro m1

[app_log.log](https://github.com/DeFiCh/app/files/6230427/app_log.log)
[binary_log.log](https://github.com/DeFiCh/app/files/6230428/binary_log.log)
<img width="274" alt="Screen Shot 2021-03-30 at 12 07 26 PM" src="https://user-images.githubusercontent.com/54778696/113020344-833a9d80-9150-11eb-9910-3350ded5f310.png">

**Comment by izzycsy** [comment]
Hi @saurin13 , you might want to try using the Snapshot download, just a heads up the file is quite large, the team is working on a faster sync process coming in future releases. In the mean time, you can try the following option if you’re more technical:

_Reminder: Keep a copy of `wallet.dat` & `passphrase` safe before proceeding_
**Snapshot (sync from 90%+)** 
 1. Download the snapshot  
 2. In app, Reindex via Settings  
 3. Wait for 1%, close the app  
 4. Go to Defi (Mac) / DeFi Blockchain (Windows) folder  
 Mac — Go to Folder: 
 `/Users/<username>/Library/Application Support/Defi` 
 
Windows — C: 
`C:\Users\<username>\AppData\Roaming\DeFi Blockchain` 
5. Unzip the downloaded Snapshot, replace the **individual files** in the Defi (Mac) / DeFi Blockchain (Windows) folder  
6. Open your app, and it should start syncing from 90%+ 


[Snapshot download](https://snapshots.defichain.com/snapshot-mainnet-682097.tar.gz)

**Comment by saurin13** [comment]
I did try the setting changes you suggested, and it did not work.  I tried the download on my PC and it works - though I would prefer to use my mac.  I will give the snapshot a try. Where can i download it?

**Comment by saurin13** [comment]
Using the snapshot seems to have helped. will keep you posted after I give it a try

**Comment by saurin13** [comment]
Its been stuck here for the last two hours:
Synchronizing 98.74%
Block 738701 of 748097
[app_log.log](https://github.com/DeFiCh/app/files/6239581/app_log.log)

**Comment by saurin13** [comment]
unfortunately now my PC is stuck too, it will not synchronize either

**Comment by izzycsy** [comment]
Hi @saurin13 , you've already passed the blockHeight 733594 where users who updated after the Dakota Crescent Upgrade were stuck at, I think you just have to ensure good internet connection and wait for it to reach 100%. 

Hi @dell1503 , did you update [manually](https://github.com/DeFiCh/app/releases/tag/v2.3.2)?

**Comment by dell1503** [comment]
Yes did the update as described.
Sync hangs still on  733594 von 749737 as before. Yes, I did a ReIndex with delete blocks and peers already twice.

**Comment by saurin13** [comment]
I have a wired/ethernet gigabit connection. I do not think my internet connection is the issue.  

My mac is stuck at 239044 of 749748. (31.88%)

**Comment by saurin13** [comment]
I used the snapshot on my PC and it is also stuck at 738701 out of 749814 (98.52%) - the mac was stuck at the same block when I used the snapshot. 

I cannot seem to move on from this.

**Comment by sash2007** [comment]
I have the same that it is stuck at Block 733594 out of 753961 (97.30%) on my Mac. Is there any new solution?

**Comment by izzycsy** [comment]
Hi @dell1503 @saurin13 @sash2007 , can you check that you Mac have sufficient storage? There's not other methods apart from 
1. Reindex via Settings (Sync from 0%)
2. Snapshot download (Sync from 90%)

The snapshot is rather big — approx 27GB. I would suggest staying on the latest version and wait for a fix. Our team is working on an automatic snapshot where you do not have to step 4–5 manually. Thank you for your patience. Kindly refer to the official channels for announcement updates: 
[DeFiChain Telegram (EN)](https://t.me/defiblockchain)
[DeFiChain Announcements (EN)](https://t.me/defichain_announcements)

**Comment by dell1503** [comment]
I updated now the app to 2.3.3, did a other time re-sync, and it works for me. Re-sync with the Snapshot.

**Comment by izzycsy** [comment]
Hi @saurabh391 @sash2007 , if you haven't sync to 100%, there was a node issue on 05/04/2021 that may have cause the `network error`, everything is back online now, you may try the following: 

**Option 1 — Reset & Reindex (sync from 0%)**
1. Settings > `Reset & Reindex` 

<img width="790" alt="Settings   Reset   Reindex" src="https://user-images.githubusercontent.com/65014479/113691297-ddae9d80-96fe-11eb-85e8-a888f16a8df3.png">

 
**Option 2 — Snapshot (sync from 90%+)**

1. Ensure you’ve at least 27GB of extra space
2.  Click on `i` located at bottom-left corner of app screen 
3. Download Snapshot

<img width="244" alt="`i` to trigger Snapshot download" src="https://user-images.githubusercontent.com/65014479/113691572-2403fc80-96ff-11eb-94c9-1e7ebafd697f.png">

Let me know your results, thank you for your patience.

**Comment by sash2007** [comment]
Thanks for your help. Its working again.
Regards

**Comment by izzycsy** [comment]
Hi @saurin13 , perhaps [adding node](https://defichain-wiki.com/wiki/Addnode) might help you get unstuck. Reach out to the community on [DeFiChain Telegram (EN)](https://t.me/defiblockchain), there will definately be people to help you! With that I'll be closing this issue.
