### ISSUE TITLE
Lost wallet backups in the process of updating from defi-app 2.3.0 to DeFi Wallet 2.3.2

### ISSUE THREAD

**Issue by UglyJo** [DeFiCh/app#711]
Hello everybody,

During the transition from v2.3.0 to v2.3.2 on Win 10, I lost my wallet, my backups and probably all my coins. 
Before the transition, I copied the wallet folder with all my wallet backups from DEFI Blockchain folder under defi-app onto my OneDrive, at least that was what I though I did. Then I installed the DeFi Wallet and tied to load my previously saved wallets. And I deinstalled defi-app 2.3.0.

It turned out every one of these wallets in the wallet folder were only the automatic created wallets, and when I tried to open them one by one they were all empty! So where were the wallet-backups?! I reached out to the Telegram DeFiChain community, and JJ and Bella tried to help me to recover the wallet or the key. But we were unable to do so, and we did not find them. 
Thanks so much JJ and Bella!

So, over night I pulled all the previously deleted files out of the Recycle Bin. And I thought, it would be a great idea to try to re-install the defi-app 2.3.0 in order to recreate the key or to retrace where the backup wallets would have gone. And with that I overwrote the wallet backs in C:\\Users\\Joachims_Dell_XPS15\\AppData\\Local\\Programs\\defi-app\\resources\\binary\\win\\wallet\\wallet_backup_20210327.dat ! 🤦‍♂️

I am running right now the 3rd or 4th recovery software, and I found the links to the wallet_backups, but the actual wallet_backups are gone.

Any idea what I can do now? You guys are my last hope!

Cheers,

Jo

**Comment by UglyJo** [comment]
Done, thanks!
Jo

 
--

 

    Am Mittwoch, 31. März 2021, 04:03:21 GMT-5 hat Bella ***@***.***> Folgendes geschrieben:  
 
 


Hi @UglyJo , thanks for your feedback, you could post your enquiry on DeFiChain Discussions, maybe the community can help recommend a recovery software. Issues posted are bug related and will become stale in a few weeks. On DeFiChain Discussions at least it'll remain visible.

**Comment by peteinvests** [comment]
Did you get it solved?

**Comment by UglyJo** [comment]
> Did you get it solved?

No, unfortunately not.

**Comment by izzycsy** [comment]
Hi @UglyJo , I'm closing this issue and leaving the https://github.com/DeFiCh/app/discussions/717 open. Thank you.
