### ISSUE TITLE
Make the wallet app more secure and easy to use with Yubikeys from Yubico

### ISSUE THREAD

**Issue by rocketeer76** [DeFiCh/app#723]
#### What would you like to be added:
When creating a new wallet, the only way to protect it thus far seems to be by adding a passphrase and keep track of the backup.dat file so that it's not overwritten or lost. Let's make this wallet more easy to use.

#### Why is this needed:
I would ask to implement the option to use Yubikeys from Yubico to be used instead of passphrase and any other security measures you can think of. A minimum of 5 keys should be able to add to the wallet app (similar to Binance).

https://developers.yubico.com

Many CEX's such as Binance and Kraken already implemented this option. Let's implement it on the DeFi wallet as well. I see that Evercoin also has this implemented: https://www.yubico.com/se/works-with-yubikey/catalog/evercoin/

**Comment by izzycsy** [comment]
Hi @rocketeer76 , thanks for your feedback, you can post your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner some support from the community, and we can decide whether to implement the feature in the future. Thank you!
