### ISSUE TITLE
No rewards received via BTC-DFI LM

### ISSUE THREAD

**Issue by stefanowitschdev** [DeFiCh/app#73]
In the DEX I had swapped 5 DFI to BTC. After successful swap I had deposited the DFI (4,99) and BTC (0,00011303) to the BTC-DFI pool on Nov. 30 20:00 UTC. Today, about 24h later I can still not see any received rewards in my BTC-DFI wallet. Pool share with this token amount of course is very small (currently 0,0004%).

Blockchain shows up as fully sychronized. App version is 2.1 on Windows 10 Pro with latest OS updates.

Note: The app had not been freshly installed but rather updated from previous version 2.0.1. Prior to the above mentioned DEX transaction and pool deposit the blockchain had also been fully synced.

Note: While writing this bug entry the blockchain synchronization status suddenly changed from "fully synced" back to 71,63% (Block 472451) and then again jumped back to "fully synced".

![defichain_wallet_2 1_bug02_img1](https://user-images.githubusercontent.com/49589027/100788364-41555100-3415-11eb-8924-cf04ac93f547.png)
![defichain_wallet_2 1_bug02_img2](https://user-images.githubusercontent.com/49589027/100788373-43b7ab00-3415-11eb-88cc-768e0d0761d1.png)
[defichain_app_2.1_applogs.log](https://github.com/DeFiCh/app/files/5625018/defichain_app_2.1_applogs.log)
[defichain_app_2.1_binlogs.log](https://github.com/DeFiCh/app/files/5625063/defichain_app_2.1_binlogs.log)

**Comment by izzycsy** [comment]
Hi @stefanowitschdev , thanks for your feedback. The team is currently addressing the "no rewards received" issue, more details will be stated in the upcoming update. Regarding the synchronising NaN% issue, it has been fixed in release v2.1.1 <https://github.com/DeFiCh/app/releases/tag/v2.1.1>.
