### ISSUE TITLE
v2.3.3 Cannot add liquidity

### ISSUE THREAD

**Issue by mat42x** [DeFiCh/app#731]
Error message:

**Please wait for your transaction to be reflected in the next block before proceeding with a new transaction.**

**Comment by izzycsy** [comment]
Hi @mat42x , may I know what's your `getbalance` output? Regarding the issue [`v2.3.2 Unable to add liquidity`](https://github.com/DeFiCh/app/issues/704), we can further discuss on the problem there. We would like to keep same issues in one thread. Thank you.

**Comment by mat42x** [comment]
getbalances
{
  "mine": {
    "trusted": 0.99938935,
    "untrusted_pending": 0,
    "immature": 0
  }
}

**Comment by izzycsy** [comment]
Hi @mat42x , not `getbalances` but `getbalance`.
