### ISSUE TITLE
Show DFI in Token and coins separately

### ISSUE THREAD

**Issue by wmbst** [DeFiCh/app#737]
#### What would you like to be added:
Please list DFI in the wallet as Tokens and Coins separately, and perhaps make a button to change Token into coins.
Also it would be great if amount of coins cannot get below 1 DFI (turn this feature on and off in the configuration if you think somebody should be able to send all its DFI)

#### Why is this needed:
There are soo many support questions from people who do not know that there are different types of DFI. They get Error messages and cannot use the app without support. This is very bad for user experience.
And using the command line is good for tech people but not for the normal users.
It generates a lot of frustration if the app doesn't work as a normal user would expect it. Even if it is from the blockchain view business as it should be. 
So I think these little enhancements will increase the usability for normal users by a lot and help the general acceptance for DFI.

**Comment by izzycsy** [comment]
Hi @wmbst , thanks for your feedback, the team is aware and working on improving what you mentioned.

**Comment by thedoublejay** [comment]
Hi @wmbst, we have added a split of display for UTXO and Token in >v2.3.5. Please take a look. Thanks!
