### ISSUE TITLE
$1000 DOLLARS LOST DUE TO WALLET BUG!!!

### ISSUE THREAD

**Issue by peteinvests** [DeFiCh/app#739]
#### How to reproduce it (as minimally and precisely as possible):

If this means fix the issue then I would like a defichain developer to look into the wallet and check the transaction and then i could send them proof of the easycrypto order i filed as well as time stamps of installation dates to confirm that it was me who created the wallet and brought the dfi. then they could get a seed phrase for the wallet and give me that, then i would be able to get into my wallet.

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.3
- Operating System (OS): Windows 10

#### Anything else we need to know?: idk if relevant but I have a youtube channel called "Pete Invests" just to confirm who I am and that I'm involved with crypto in positive ways.

 unfortunatly I lost them

**Comment by peteinvests** [comment]
Address: rGWRBZWBXioSFSA9WAWxR59ahWfRgAkkDK
TXID: 6DB6FB370BF4CF0A74E7C25974A6EFC85FD390A5298EDDC62F9EB9A6CA201D63

**Comment by peteinvests** [comment]
address: da4QbJxpcYMAjXuQCnPniTeFrRrcAQ6YwA

**Comment by izzycsy** [comment]
Hi @peteinvests , [v2.3.3](https://github.com/DeFiCh/app/releases/tag/v2.3.3) is out. Please read through the release notes before updating. If you have not sync to 100%, there was a node issue on 05/04/2021 that may have cause the `network error`, everything is back online now, you may try the following: 

**Option 1 — Reset & Reindex (sync from 0%)**
1. Settings > `Reset & Reindex` 

<img width="790" alt="Settings   Reset   Reindex" src="https://user-images.githubusercontent.com/65014479/113691297-ddae9d80-96fe-11eb-85e8-a888f16a8df3.png">

 
**Option 2 — Snapshot (sync from 90%+)**
1. Settings > `Reset & Reindex` 
2. Wait for app to start syncing
3. Ensure you’ve at least 27GB of extra space
2.  Click on `i` located at bottom-left corner of app screen 
3. Download Snapshot

<img width="244" alt="`i` to trigger Snapshot download" src="https://user-images.githubusercontent.com/65014479/113691572-2403fc80-96ff-11eb-94c9-1e7ebafd697f.png">

Please do not delete anything you're unfamiliar with, do you have your `wallet.dat`? 

Windows — `
C:\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat`

Please keep the `wallet.dat` & your `passphrase` safe.
