### ISSUE TITLE
Can't find any UTXO's for owner

### ISSUE THREAD

**Issue by nordi6000** [DeFiCh/app#74]
I have a open pool and will put more BTC to the pool. 
![image](https://user-images.githubusercontent.com/49670309/100790422-0a346f00-3418-11eb-90b3-cacad65a9582.png)

when i want to add liquidity the error message always comes up
![image](https://user-images.githubusercontent.com/49670309/100790662-639c9e00-3418-11eb-9dbd-668300ee1694.png)

I send BTC To this Address -> 8WaLRfGAYrvecoXUQ2haVRydMpvAYzU4ue  but no success!!

Any Help?

**Comment by izzycsy** [comment]
Hi @nordi6000 , have you updated to the latest v2.1.1? <https://github.com/DeFiCh/app/releases/tag/v2.1.1> 
Could you describe your user flow more in detail and what OS you're using? We need these information in order to investigate how to reproduce the issue. Thank you.

**Comment by nordi6000** [comment]
I have update to v2.1.3 now and it is working. I have the log files if you like to have?

**Comment by izzycsy** [comment]
@nordi6000 Great that's it's working for you!
