### ISSUE TITLE
Transaction issues. Unable to send coin to my other wallet 

### ISSUE THREAD

**Issue by MABRAHANTEE** [DeFiCh/app#742]
Can someone help me to get my defi wallet fixed??? I'm unable to make any transaction

![IMG_2539](https://user-images.githubusercontent.com/82133213/113967482-12a21980-97ff-11eb-8827-3f6fb9eac78d.jpg)

![IMG_2540](https://user-images.githubusercontent.com/82133213/113967485-15047380-97ff-11eb-9008-01aeeea3e2c5.jpg)

.

[Archive.zip](https://github.com/DeFiCh/app/files/6275917/Archive.zip)

**Comment by izzycsy** [comment]
Hi @MABRAHANTEE , thanks for your feedback. 

In your 1st screenshot, it appears that you are attempting to send BTC to a Bitcoin network address. BTC on DeFiChain is a DeFi Standard Token (DST) — in other words D-BTC, that is only transmittable to other DeFiChain addresses (usually starting with `8` or `d`). Try sending it through sites such as <cakedefi.com>, then to your own preferred exchange.   To swap from D-BTC to BTC, you can go through sites like <cakedefi.com> or swap D-BTC to DFI on DEX.

In your 2nd screenshot, it’s likely that you've insufficient utxoDFI balance (min. 1 DFI) — which is required to perform swap and all other functions. DFI exist in 2 forms; `utxoDFI` and `accountDFI`. utxoDFI is used to pay for transactions fees while rewards received from liquidity mining (for example) are in accountDFI.  May I know what's your `getbalance`?

**Comment by MABRAHANTEE** [comment]
Hi Bella,

The problem is that I have done previous transactions from that wallet to another plataform before. Now I can’t. Secondly my Balance represent over 400 dollars at least. I thought it was enough. Also, I can’t even add it to a pool chair either.  Down I’m sending you a screenshot of my balance. I pooled all the balance  I had in the pool to send it to my other wallet but now I can’t. How can I get the utxodefi coin to have enough to send everything out of this wallet. 
I really appreciate your help.


Michel Abrahante, RVT, RDMS, RDCS, CMRITO
Halton Vascular Lab
***@***.***
416-844-0128

**Comment by MABRAHANTEE** [comment]
It’s not letting me do anything at all. Everything is stuck there. 

Michel Abrahante, RVT, RDMS, RDCS, CMRITO
Halton Vascular Lab
***@***.***
416-844-0128

**Comment by izzycsy** [comment]
Hi @MABRAHANTEE , I can't see your screenshot, you can drag and drop it in the comment section on this thread. 

To convert accountDFI to utxoDFI, the simplest way would be via DeFi Wallet app.   
Firsty, check via CLI:  
`getbalance` — utxoDFI
`gettokenbalances` — accountDFI 

From your output 
```
gettokenbalances
[
  "3.123456768@0", — accountDFI
  "XXXXXXXXXX@2",
  "XXXXXXXXXX@5"
]
```

Send 1 DFI to yourself:
1. copy your address (the one that you're planning to use to DEX / add liquidity)
2. send DFI
3. 1 DFI
4. Paste the address 
5. Try the function again

By sending to yourself, you're converting your accountDFI to utxoDFI. utxoDFI is used for transaction fees.

**Comment by MABRAHANTEE** [comment]
hi Bella, 

Tried to do that and it is not letting me do it. it keep telling me that I do not have sufficient funds. I'm getting frustrated. This is not working.  Tried send myself DFI to two different address and did not work.

![image](https://user-images.githubusercontent.com/82133213/114101406-b210ec00-9893-11eb-9110-ea9b7aa322f8.png)
![image](https://user-images.githubusercontent.com/82133213/114101440-bc32ea80-9893-11eb-845e-bb7d52c4eab4.png)
![image](https://user-images.githubusercontent.com/82133213/114101475-c6ed7f80-9893-11eb-9da9-376210896685.png)
![image](https://user-images.githubusercontent.com/82133213/114101498-cfde5100-9893-11eb-8fa5-3d2aad8caf9b.png)
![image](https://user-images.githubusercontent.com/82133213/114101518-d8cf2280-9893-11eb-89d4-935d74bac8e2.png)

**Comment by John-Gee** [comment]
There's a Prefund TXNS button in the settings, maybe you could try that and see if that's any better.

(Nota: It'd be cleaner/clearer to take actual screenshots of the app instead of using a camera to take pictures.)

**Comment by wmbst** [comment]
Cannot help you with the insufficient funds issue.
But I saw, that you are trying to send BTC from your wallet to a Bitcoin addresses. 
This cannot work. Your BTC are tokens on the DFI chain and not native BTC on the Bitcoin chain.
If you have an about at CakeDefi you can send your BTC there and from there you can send them to a native BTC address.

**Comment by izzycsy** [comment]
Hi @MABRAHANTEE , from the steps provided previously, you have to check your uxtoDFI & accountDFI balance via the CLI. You don't have to create a new address to send DFI to yourself, continue to you your same address.

<img width="745" alt="CLI" src="https://user-images.githubusercontent.com/65014479/114191561-23799900-997f-11eb-9c3b-8339a6afb6f9.png">

As for sending BTC, @wmbst is right, the address you’re using is not a DeFiChain-friendly address. You can retrieve the DeFiChain address via <cakedefi.com>, try sending a small amount first to test.

1. Click on Balances in <cakedefi.com>
2. In the BTC row, click on Deposit button
3. You'll see the Transfer Network options `BTC` / `DeFiChain`
4. Under the QR Code states your DeFiChain address, copy it
5. Go back to DeFi Wallet > BTC wallet > Send
6. Paste your DeFiChain address into `To address` field

<img width="375" alt="Click DeFiChain   BTC" src="https://user-images.githubusercontent.com/65014479/114191837-6b002500-997f-11eb-8e6d-09df900799e0.png">
