### ISSUE TITLE
Suggested improvement: Send button

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#743]
Suggested improvement:

The Send button should not be pink while the lock is still closed. 

<img width="1026" alt="Bildschirmfoto 2021-04-08 um 12 06 55" src="https://user-images.githubusercontent.com/65536965/114009317-53cc1500-9863-11eb-8466-8d753fa047b1.png">

**Comment by izzycsy** [comment]
Hi @RobinTorque , thanks for the feedback, please give us time to investigate the issue.

**Comment by izzycsy** [comment]
Hi @RobinTorque , when user clicks on `send` wallet it'll follow up with a prompt for user to unlock wallet. It's the designated flow at the moment. If we grey it out, some users may think that there's an error. I'll be closing this issue, thank you for your feedback.
