### ISSUE TITLE
Linux: Snapshot not extracting in the right place

### ISSUE THREAD

**Issue by John-Gee** [DeFiCh/app#744]
#### What happened:
The app downloaded the snapshot in ~/snapshot, a little weird and unclean, also not necessarily the same partition as the defichain folder but that worked. Then the app extracted the 7z file to ~, so it created ~/blocks, ~/chainstate and ~/enhancedcs. The app then said it was going to use it, and instead just restarted the network sync.
#### What you expected to happen:
1- The app should extract the files in the correct folder.
2- If 1- fails, the app should be somehow aware of it and say that something went wrong not just silently ignore the error. At least it's able to continue the download, or stop if it's already full, and not restart it from scratch which is already that. With a clear message, the user can easily fix the issue by moving the folders to the correct place (as I did).

#### How to reproduce it (as minimally and precisely as possible):
Use the sync from snapshot functionality on a Linux box.
#### What are your environment parameters?

- DeFi Wallet Version: 2.3.3
- Operating System (OS): Arch Linux

#### Anything else we need to know?:

By a quick look at the code, this is what I'm thinking:

> const snapshotPath = path.join(getBaseFolder(), '../', SNAPSHOT_FOLDER);

So it depends on what getBaseFolder is, if it returns ~/.defi as I guess it would indeed download to ~/.defi/snapshot.. ie ~/snapshot.

Let's take a look:

getBaseFolder returns MAINNET_BASE_FOLDER, which on Linux is BASE_FILE_PATH, which is getCustomDebugLogFilePath(CONFIG_FILE_PATH), that in turn is either the empty string or config.datadir but I don't know where to find the ini functions. I do not have any datadir in my conf file, the only dir is walletdir, maybe that's the problem?

Then:

> try {
    log.info('Starting extraction...');
    const blocksPath = path.join(getBaseFolder(), '..');
    const child = spawn(UNZIP_FILE_PATH, [
      `x`,
      `${fileSizes.downloadPath}`,
      `-o${blocksPath}`,
      `-aoa`,
    ]);

explains why I see the blocks folder in ~/, but when it syncs that's not where it puts the blocks folder it goes to ~/.defi/ (I didn't check it in the code, but in my FS during network sync).

I'm glad to dig more if needed, but I'm guessing something here would be obvious to people with knowledge of this app or even just electron. Maybe @thedoublejay .

Thanks!

**Comment by izzycsy** [comment]
Hi @John-Gee , thanks for your feedback, please give us time to get back to you on the issue. In the mean time, you can add on your sharings to [Running the app as a webapp (e.g. from a Raspberry Pi)](https://github.com/DeFiCh/app/discussions/736), another user is also Linux; connecting you guys.

**Comment by John-Gee** [comment]
Yeah no worries, as I wrote I was able to easy workaround that problem myself so there is no rush on my end, just trying to get it better for people that don't have the skills/time to fix things. Thank you!

**Comment by thedoublejay** [comment]
Thanks for raising this @John-Gee. We'll take a look on this for Linux.

**Comment by John-Gee** [comment]
Cool thank you! I'll be happy to help with this if I can.

**Comment by thedoublejay** [comment]
Hi @John-Gee, I have a fix for this issue. Should be included on the next app release. Thanks!

**Comment by John-Gee** [comment]
Awesome, thank you @thedoublejay !

**Comment by thedoublejay** [comment]
Hi @John-Gee! If you have time, can you double verify if the fix is working on your end? We have a pre-release build here. Let us know if it's ok on your end. Thank you! - https://github.com/DeFiCh/app/releases/tag/v2.4.0-rc.3

**Comment by John-Gee** [comment]
Oh hey again @thedoublejay .

Hmmm, is the rc safe enough to load? I guess I can do that on an empty wallet anyway. Alright i'll bet back to you, likely not before a few hours, as it takes a while to download.

**Comment by John-Gee** [comment]
So I did download the snapshot from aria2c though as I was not patient enough to see that slow download... and used it with my standard wallet, hoping I wouldn't to have [censored].

Yup it worked fine this time, thank you!


I'll also paste my comment from TG:

> When I downloaded the latest snaphot from 2.4.0rc it was ~30Gb. When it extracted it took ~45Gb. After letting the wallet do I'm not sure what, I see my .defi folder at 2.5Gb. Is that expected?

**Comment by diegorodriguezv** [comment]
Congratulations on fixing this issue and the engineering work to reduce download size and synchronization time. My only suggestion would be to download the snapshot file to ~/.defi/snapshot instead of ~/snapshot to decrease pollution of the home directory. Well done!
