### ISSUE TITLE
Keep the DBs compressed

### ISSUE THREAD

**Issue by John-Gee** [DeFiCh/app#745]
#### What would you like to be added:
My FS is compressed with zstd, with that the defi folder only takes 38% of the space it would take otherwise. But FS compression is too much to ask for most people, so maybe the app could compress it directly with LZ4 or zstd or something fast like that.

#### Why is this needed:
I see a bunch of people having issues with the wallet taking too much space.
I know you are working on a light wallet, but compression could be a quick way to deal with that in the meantime. Decompression speed of the algorithms mentioned above shouldn't really be a problem for this kind of app, and maybe you could deliver it already compressed, like in the snapshot, so that compression performance is a non-issue.

**Comment by izzycsy** [comment]
Hi @John-Gee , thanks for your feedback, will share it with the team. 	In the mean time, you can post your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), share your findings with the community. Thank you! 

cc: @bvbfan @thedoublejay

**Comment by John-Gee** [comment]
Should I post that one over there too?

Thank you!
