### ISSUE TITLE
Can't add Liqudity to BTC Pool

### ISSUE THREAD

**Issue by dell1503** [DeFiCh/app#746]
#### What happened:
I unlock the Wallet. Went to "Liquditiy" and select the BTC Pool. I select add more, and then select the Amount.
When clicking on Next and execute, to add the Liquidity I receive the following error:
After showing the Progress "UTXO vorbereiten
Liquidität wird hinzugefügt"

The Error appears:
Bitte warte bis deine Transaktion dem nächsten Block hinzugefügt wurde, bevor du mit einer neuen Transaktion fortfährst.

#### What you expected to happen:
Transaction gets through.
Other transactions, SWAP e.g. are working.
I Just resynced!
#### What are your environment parameters?

- DeFi Wallet Version: 2.3.3
- Operating System (OS): Mac OS 11.2.3

#### Anything else we need to know?:

<img width="777" alt="Bildschirmfoto 2021-04-08 um 15 24 09" src="https://user-images.githubusercontent.com/20696826/114034628-a1a24680-987e-11eb-97de-72aebcfe479c.png">
[applog.log](https://github.com/DeFiCh/app/files/6278946/applog.log)

**Comment by John-Gee** [comment]
When you say SWAP work fine, is it on the same address? I just wonder if maybe that one does not have the utxo dfi to pay for the transaction.

**Comment by dell1503** [comment]
Swap from defi to btc worked on the same wallet. 
Or do you mean the reward Adresse?

**Comment by wmbst** [comment]
According to Wiki it could help, if you send some DFI within your wallet to your own address.
I am not a developer, but I think it is worth a try.

https://defichain-wiki.com/wiki/DeFi_Wallet_error_messages#Please_wait_until_your_transaction_has_been_added_to_the_next_block_before_proceeding_with_a_new_transaction.

**Comment by izzycsy** [comment]
Hi @dell1503 , it’s likely that you've insufficient utxoDFI balance (min. 1 DFI) — which is required to perform swap and all other functions. DFI exist in 2 forms; `utxoDFI` and `accountDFI`. utxoDFI is used to pay for transactions fees while rewards received from liquidity mining (for example) are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. To convert accountDFI to utxoDFI, the simplest way would be via DeFi Wallet app.   Firsty, check via CLI:  `getbalance` — utxoDFI
`gettokenbalances` — accountDFI 
From your output 
```
gettokenbalances
[
  "3.123456768@0", — accountDFI
  "XXXXXXXXXX@2",
  "XXXXXXXXXX@5"
]
```

Send 1 DFI to yourself:
1. copy your address (the one that you're planning to use to add liquidity)
2. send DFI
3. 1 DFI
4. Paste the address 
5. Try the function again

By sending to yourself, you're converting your accountDFI to utxoDFI. utxoDFI is used for transaction fees.

Regarding the issue [`v2.3.3 Unable to add liquidity`](https://github.com/DeFiCh/app/issues/704), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.

**Comment by dell1503** [comment]
> Hi @dell1503 , it’s likely that you've insufficient utxoDFI balance (min. 1 DFI) — which is required to perform swap and all other functions. DFI exist in 2 forms; `utxoDFI` and `accountDFI`. utxoDFI is used to pay for transactions fees while rewards received from liquidity mining (for example) are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. To convert accountDFI to utxoDFI, the simplest way would be via DeFi Wallet app. 
> 
> Firsty, check via CLI: 
> `getbalance` — utxoDFI
> 
> `gettokenbalances` — accountDFI
> 
> 
> From your output 
> 
> ```
> 
> gettokenbalances
> 
> [
> 
>   "3.123456768@0", — accountDFI
> 
>   "XXXXXXXXXX@2",
> 
>   "XXXXXXXXXX@5"
> 
> ]
> 
> ```
> 
> 
> 
> Send 1 DFI to yourself:
> 
> 1. copy your address (the one that you're planning to use to add liquidity)
> 
> 2. send DFI
> 
> 3. 1 DFI
> 
> 4. Paste the address 
> 
> 5. Try the function again
> 
> 
> 
> By sending to yourself, you're converting your accountDFI to utxoDFI. utxoDFI is used for transaction fees.
> 
> 
> 
> Regarding the issue [`v2.3.3 Unable to add liquidity`](https://github.com/DeFiCh/app/issues/704), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you. 

Thank you, where can I see the right source address?
I have multiple DEFI adress?
Is it the reward address?

**Comment by izzycsy** [comment]
Hi @dell1503 , you can try this via CLI: 

`listaccounts {} false false true` — breakdown of your token(s)

All the addresses you see are addresses with tokens on it, generally I use only 1 or max 2 addesses so I do not get confused. To remove addresses you can `cancel request`, and to add you can manually add them back. 

<img width="803" alt="#4 Receive   Cancel request" src="https://user-images.githubusercontent.com/65014479/114388414-3af69300-9bc6-11eb-94d4-f54578cc0c32.png">
