### ISSUE TITLE
Erhalte keine Coins mehr vom Liquidity

### ISSUE THREAD

**Issue by Pelz1982** [DeFiCh/app#748]
#### What happened:
[app logs.zip](https://github.com/DeFiCh/app/files/6290516/app.logs.zip)

#### What are your environment parameters?

- DeFi Wallet Version:
- Operating System (OS):

**Comment by Pelz1982** [comment]
What happened
 liquidity mine zahlt keine Erträge aus

app logs.zip
What you expected to happen:
How to reproduce it (as minimally and precisely as possible):
What are your environment parameters?

    DeFi Wallet Version:2.3.3
    Operating System (OS):win10

Anything else we need to know?:

**Comment by izzycsy** [comment]
Hi @Pelz1982 , did you select `include reward transactions` ?

<img width="776" alt="Include reward tx" src="https://user-images.githubusercontent.com/65014479/114304543-51d5b080-9b06-11eb-8e53-acb3cc022a69.png">

**Comment by izzycsy** [comment]
Hi @Pelz1982 , you may turn to DeFiChain’s telegram for how-to related issues: 

[DeFiChain Telegram (EN)](https://t.me/defiblockchain)

Thank you.
