### ISSUE TITLE
Win: App shows white screen + logo

### ISSUE THREAD

**Issue by rezaghiasi** [DeFiCh/app#750]
#### What happened: I have updated my desktop DeFi wallet to version 2.3.3 at first it struggled with downloading the snapshot and for a couple of times it gave me errors. then I decided to let it sync the blocks from scratch and it went up to 87% and again gave another error like node is disconnected. 
Now the whole app is not coming up again and it just shows the logo 

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.3
- Operating System (OS): macOS Big Sur (11.2.3) 

#### Anything else we need to know?:

[Archive.zip](https://github.com/DeFiCh/app/files/6290819/Archive.zip)

**Comment by John-Gee** [comment]
If you run the app from the command line, what does it say when you're just seeing the logo?

**Comment by rezaghiasi** [comment]
Here is a screenshot of command line and the application 

<img width="618" alt="Screenshot 2021-04-11 at 10 08 31 AM" src="https://user-images.githubusercontent.com/36978763/114295430-e19b4080-9aad-11eb-8ccd-b01daa948e11.png">

**Comment by John-Gee** [comment]
So from looking at your message and the code it seems your wallet_map.json file may have some trouble in there. That file is in your defi folder.

If you know your way around computers, maybe you can look at it and figure what's wrong.

If not, I'd be happy to help, but to be honest I don't know if anything in there is supposed to stay private...

**Comment by rezaghiasi** [comment]
Alright, let me have a look and get back to you 
thanks a lot

**Comment by John-Gee** [comment]
Sure thing!

**Comment by rezaghiasi** [comment]
I think I will be needing more help on this matter, lol 
how can we proceed?

**Comment by John-Gee** [comment]
Come to the DFI telegram and I can help you from there.

**Comment by thedoublejay** [comment]
Thanks for the help @John-Gee. @rezaghiasi as John pointed out, there might be some issue on your wallet_map.json. Need to check it for potential issues. You can post it here but you can delete some personal info like directory etc. Just need to view the structure

**Comment by Mabarkubus** [comment]
In my case the app doesn't open also, on my windows PC. Installed DeFi-Wallet-Setup-2.3.2 and DeFi-Wallet-Setup-2.3.3, but both the same. What do i have to do?

**Comment by gianlucast1** [comment]
My App dosen't open also. I have a Mac (macOS Big Sur (11.2.3)). What should i do?

**Comment by izzycsy** [comment]
Hi @Mabarkubus , did you use the `DeFi-Wallet-Setup-2.3.3.exe` file extension type? Please backup your `wallet.dat` before performing a reinstallation. 

Hi @gianlucast1 , for MacOS Big Sur, try removing the `.defi` file, here's a guide [MacOS Big Sur: Unable to open app after installation](https://github.com/DeFiCh/app/issues/765).

**Comment by Mabarkubus** [comment]
I still had made a backup of my wallet and tried severel times a reinstallation. I don't know what to do now?

**Comment by izzycsy** [comment]
Hi @Mabarkubus , can you check if you've sufficient storage? On Windows, currently it requires >100GB of storage. The team is working on a light wallet and reducing the storage size required.

**Comment by gianlucast1** [comment]
@izzycsy it's not working. I have the same problem, like on the screenshot in the massage from "rezaghiasi" 14 days ago.

**Comment by Mabarkubus** [comment]
Then this could be the reason, i'm only having 21GB of storage on Drive C...

**Comment by John-Gee** [comment]
> @izzycsy it's not working. I have the same problem, like on the screenshot in the massage from "rezaghiasi" 14 days ago.

You may want to start from scratch, with a proper backup of your wallet then.

**Comment by Mabarkubus** [comment]
...but i had the "older" versions of the app DeFi wallet before version 2.3.1 in use, so why is this problem now. I deleted a lot of software and files on my system, but the app doesn't work again...

**Comment by izzycsy** [comment]
Hi @Mabarkubus , that's because the blockchain grows and you're running the blocks yourself in your desktop app. We understand that it's taking a lot of storage space and the team is working on reducing it somehow, including a Light Wallet. Thank you for your understanding.

**Comment by gianlucast1** [comment]
> > @izzycsy it's not working. I have the same problem, like on the screenshot in the massage from "rezaghiasi" 14 days ago.
> 
> You may want to start from scratch, with a proper backup of your wallet then.

How can i do this?
Do you know how many storage i need on my mac Book to Start the Wallet? Now I have 32GB free. I don't know, but maybe I don't have enough space on my Mac.

**Comment by izzycsy** [comment]
Hi @gianlucast1 I doubt it's enough, currently it grew to this size. I would advice that you backup your `wallet.dat` and wait for a fix if you didn't manage to clear storage.

<img width="803" alt="Mac DeFi Wallet size" src="https://user-images.githubusercontent.com/65014479/116067935-3cdb4e80-a6bc-11eb-88e8-82ee32b9d7dc.png">

**Comment by gianlucast1** [comment]
Thx for the massage. Is it possible to download the Wallet with the Snapshot to an external hard drive and run the wallet on the hard drive?

**Comment by John-Gee** [comment]
Yes you can do that, the snapshot is about 29Gb and the blockchain around 80Gb, you'll need enough space for both before deleting the snapshot.

**Comment by gianlucast1** [comment]
Cool, thank you. So i will check it out.

**Comment by izzycsy** [comment]
Hi @rezaghiasi @Mabarkubus @gianlucast1 , [v2.3.4](https://github.com/DeFiCh/app/releases/tag/v2.3.4) is out. Please read through the release notes before updating. If your issue still persist, please send your logs here and explain what you faced, [`Unable to start blockchain`](https://github.com/DeFiCh/app/issues/833), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.
