### ISSUE TITLE
Deleted 3 folders > App not syncing

### ISSUE THREAD

**Issue by Alex080988** [DeFiCh/app#751]
Hi there, 
since 6 days i cannot enter my wallet in the defi-chainapp (V.2.3.3/Windows 10). I tried several advices from people out of the community,
which were not working. So I am writing you, because I am medium desperate.

The errors occured after the new version with the Snapshot-File.

I made enough space on an external storage,

installed the app new,

followed the instructions in the wiki (added lines in the defi.conf for having the archives in the external storage)

deleted "blocks", "chainstate" and "enhancedcs"

downloaded the snapshotfile "snapshot-mainnet-74648.zip" (26,7GB/ 28.723.036.160 Bytes)

tried to unpack the snapshot → Error

tried to sync normaly → Error

→ the app always is saying the the Blockchaindatabase is corruped

APP LOG:

> [2021-04-11 02:07:04.786] [IPC-RENDERER-info]  [setLockTimeout] "Starting update of lock timeout..."
> [2021-04-11 02:07:04.794] [IPC-RENDERER-info]  [Update Auto-lock Time] "Timeout updated to 300 seconds"
> [2021-04-11 02:07:06.841] [IPC-RENDERER-info]  [start] - Node started
> [2021-04-11 02:07:06.841] [IPC-RENDERER-info]  [start] - Sending node started to client
> [2021-04-11 02:07:07.028] [IPC-RENDERER-info]  Update for version 2.3.3 is not available (latest version: 2.3.3, downgrade is disallowed).
> [2021-04-11 02:07:07.030] [IPC-RENDERER-debug] checkForUpdatesAndNotify called, downloadPromise is null
> [2021-04-11 02:07:08.879] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
> [2021-04-11 02:07:10.854] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
> [2021-04-11 02:07:12.862] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
> [2021-04-11 02:07:14.861] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
> [2021-04-11 02:07:16.862] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
> [2021-04-11 02:07:18.855] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
> [2021-04-11 02:07:20.861] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
> [2021-04-11 02:07:22.860] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
> [2021-04-11 02:07:24.578] [IPC-RENDERER-error] [start] - Error on node connection: : Error opening block database.
> Please restart with -reindex or -reindex-chainstate to recover.
> [2021-04-11 02:07:24.606] [IPC-RENDERER-error] [startBinary] ": Error opening block database.\r\nPlease restart with -reindex or -reindex-chainstate to recover." → This option is greyed out for me in the app, which means I cannot do this.
> [2021-04-11 02:07:24.609] [IPC-RENDERER-info]  [Blockchain Status] {"success":false,"data":{"message":": Error opening block database.\r\nPlease restart with -reindex or -reindex-chainstate to recover.","isReindexReq":true,"walletMap":{"paths":["C:\\Users\\...\\Backup.dat","F:\\defichain\\wallets\\wallet.dat"],"nodeVersion":"1.6.2","hasSyncSPV":false,"paymentRequests":[{"address":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX1","label":"","id":"YYYYYYYYYY","ismine":true,"time":"2020-12-18T23:28:19.000Z","hdSeed":false},{"address":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX2","label":"","id":"YYYYYYYYYY","ismine":true,"time":"2020-12-20T00:19:37.000Z","hdSeed":true},{"address":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX3","label":"","id":"YYYYYYYYYY","ismine":true,"time":"2020-12-20T00:19:37.000Z","hdSeed":true},{"address":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX4","label":"ErhaltenDFI1","id":"YYYYYYYYYY","ismine":true,"time":"2020-12-20T00:19:37.000Z","hdSeed":true},{"address":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX5","label":"05042021","id":"YYYYYYYYYY","ismine":true,"time":"2020-12-20T00:19:37.000Z","hdSeed":true},{"address":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX6","label":"280321","id":"YYYYYYYYYY","ismine":true,"time":"2020-12-20T00:19:37.000Z","hdSeed":true},{"address":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX7","label":"DFI_ETH_BTC","id":"YYYYYYYYYY","ismine":true,"time":"2020-12-20T00:19:37.000Z","hdSeed":true}]}}}
> [2021-04-11 02:07:24.612] [IPC-RENDERER-error] [blockChainNotStarted - Not Running] ""
> [2021-04-11 02:07:24.860] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 503"
> [2021-04-11 02:07:25.430] [IPC-RENDERER-info]  [start] - Node is closed with code 1
> [2021-04-11 02:07:25.430] [IPC-RENDERER-error] [start] - Error occurred while closing node with code: 1
> [2021-04-11 02:07:25.436] [IPC-RENDERER-error] [startBinary] "Error occurred while closing node with code: 1"
> [2021-04-11 02:07:25.438] [IPC-RENDERER-info]  [Blockchain Status] {"success":false,"data":{"message":"Error occurred while closing node with code: 1","walletMap":{"paths":["C:\\Users\...\Backup.dat","F:\\defichain\\wallets\\wallet.dat"],"nodeVersion":"1.6.2","hasSyncSPV":false,"paymentRequests":[{"address":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","label":"","id":"YYYYYYYYYY","ismine":true,"time":"2020-12-18T23:28:19.000Z","hdSeed":false},{"address":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX1","label":"","id":"YYYYYYYYYY","ismine":true,"time":"2020-12-20T00:19:37.000Z","hdSeed":true},{"address":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX2","label":"","id":"YYYYYYYYYY","ismine":true,"time":"2020-12-20T00:19:37.000Z","hdSeed":true},{"address":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX3","label":"ErhaltenDFI1","id":"YYYYYYYYYY","ismine":true,"time":"2020-12-20T00:19:37.000Z","hdSeed":true},{"address":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX4","label":"05042021","id":"YYYYYYYYYY","ismine":true,"time":"2020-12-20T00:19:37.000Z","hdSeed":true},{"address":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX5","label":"280321","id":"YYYYYYYYYY","ismine":true,"time":"2020-12-20T00:19:37.000Z","hdSeed":true},{"address":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX6","label":"DFI_ETH_BTC","id":"YYYYYYYYYY","ismine":true,"time":"2020-12-20T00:19:37.000Z","hdSeed":true}]}}}
> [2021-04-11 02:07:25.440] [IPC-RENDERER-error] [blockChainNotStarted - Not Running] ""
> [2021-04-11 02:07:28.908] [IPC-RENDERER-error] [isBlockchainStarted] "Network Error"
> [2021-04-11 02:07:29.157] [IPC-RENDERER-error] [isBlockchainStarted] "Network Error"
> [2021-04-11 02:07:30.883] [IPC-RENDERER-error] [isBlockchainStarted] "Network Error"
> [2021-04-11 02:07:32.894] [IPC-RENDERER-error] [isBlockchainStarted] "Network Error"
> [2021-04-11 02:07:34.897] [IPC-RENDERER-error] [isBlockchainStarted] "Network Error"
> [2021-04-11 02:07:36.888] [IPC-RENDERER-error] [isBlockchainStarted] "Network Error"
> [2021-04-11 02:07:38.885] [IPC-RENDERER-error] [isBlockchainStarted] "Network Error"
> [2021-04-11 02:07:40.892] [IPC-RENDERER-error] [isBlockchainStarted] "Network Error"
> [2021-04-11 02:07:42.902] [IPC-RENDERER-error] [isBlockchainStarted] "Network Error"
> [2021-04-11 02:07:44.879] [IPC-RENDERER-error] [isBlockchainStarted] "Network Error"
> [2021-04-11 02:07:46.900] [IPC-RENDERER-error] [isBlockchainStarted] "Network Error"
> [2021-04-11 02:07:48.877] [IPC-RENDERER-error] [isBlockchainStarted] "Network Error"
> [2021-04-11 02:07:50.895] [IPC-RENDERER-error] [isBlockchainStarted] "Network Error"
> [2021-04-11 02:10:42.905] [IPC-RENDERER-error] [isBlockchainStarted] "Network Error"
> [2021-04-11 02:10:42.908] [IPC-RENDERER-info]  [Blockchain Status] "Unable to start blockchain"
> [2021-04-11 02:10:42.912] [IPC-RENDERER-error] [blockChainNotStarted - Not Running] "Unable to start blockchain"
> [2021-04-11 02:25:35.853] [IPC-RENDERER-info]  Available Space: 166320488448 - Remote Size: 28723033480
> [2021-04-11 02:25:35.861] [IPC-RENDERER-info]   "Snapshot download complete!"
> [2021-04-11 02:25:49.570] [IPC-RENDERER-info]  Starting extraction...
> [2021-04-11 02:25:49.810] [IPC-RENDERER-info]  7-Zip (a) 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
>
> Scanning the drive for archives:
> 1 file, 28723033480 bytes (27 GiB)
>
> Extracting archive: F:\defichain\snapshot\snapshot-mainnet-746484.zip

BINARY LOG:

>
> 2021-04-10T23:33:10Z Ignoring unknown configuration value rpcconnect
> 2021-04-10T23:33:10Z DeFi Blockchain version 1.6.2 (release build)
> 2021-04-10T23:33:10Z Assuming ancestors of block 9b257cb88630e422902ef2b17a3627ae2f786a5923df9c3bda4226f9551b1ea8 have valid signatures.
> 2021-04-10T23:33:10Z Setting nMinimumChainWork=000000000000000000000000000000000000000000003f2949bfe4efc275390c
> 2021-04-10T23:33:10Z Using the 'sse4(1way),sse41(4way),avx2(8way)' SHA256 implementation
> 2021-04-10T23:33:10Z Using RdSeed as additional entropy source
> 2021-04-10T23:33:10Z Using RdRand as an additional entropy source
> 2021-04-10T23:33:10Z Default data directory C:\...\DeFi Blockchain
> 2021-04-10T23:33:10Z Using data directory F:\defichain
> 2021-04-10T23:33:10Z Config file: C:\...defi\defi.conf
> 2021-04-10T23:33:10Z Using at most 125 automatic connections (2048 file descriptors available)
> 2021-04-10T23:33:10Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
> 2021-04-10T23:33:10Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
> 2021-04-10T23:33:10Z Using 8 threads for script verification
> 2021-04-10T23:33:10Z scheduler thread start
> 2021-04-10T23:33:10Z HTTP: creating work queue of depth 16
> 2021-04-10T23:33:10Z Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcauth for rpcauth auth generation.
> 2021-04-10T23:33:10Z Using rpcauth authentication.
> 2021-04-10T23:33:10Z HTTP: starting 4 worker threads
> 2021-04-10T23:33:10Z Using wallet directory C:/...\Desktop
> 2021-04-10T23:33:10Z init message: Verifying wallet(s)...
> 2021-04-10T23:33:10Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
> 2021-04-10T23:33:10Z Using wallet C:/...\Backup.dat
> 2021-04-10T23:33:10Z BerkeleyEnvironment::Open: LogDir=C:/...\database ErrorFile=C:/...\db.log  → I opend this. It's just an emty file
> 2021-04-10T23:33:10Z init message: Loading banlist...
> 2021-04-10T23:33:10Z Cache configuration:
> 2021-04-10T23:33:10Z * Using 2.0 MiB for block index database
> 2021-04-10T23:33:10Z * Using 8.0 MiB for chain state database
> 2021-04-10T23:33:10Z * Using 440.0 MiB for in-memory UTXO set (plus up to 286.1 MiB of unused mempool space)
> 2021-04-10T23:33:10Z Warning -acindex and -acindex-mineonly are set, -acindex will be used
> 2021-04-10T23:33:10Z init message: Loading block index...
> 2021-04-10T23:33:10Z Opening LevelDB in F:\defichain\blocks\index
> 2021-04-10T23:33:10Z Opened LevelDB successfully
> 2021-04-10T23:33:10Z Using obfuscation key for F:\defichain\blocks\index: 0000000000000000
> 2021-04-10T23:33:30Z LoadBlockIndexDB: last block file = 6
> 2021-04-10T23:33:30Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=25607, size=52775816, heights=720942...746484, time=2021-03-20...2021-03-31)
> 2021-04-10T23:33:30Z Checking all blk files are present...
> 2021-04-10T23:33:30Z Opening LevelDB in F:\defichain\chainstate
> 2021-04-10T23:33:30Z Opened LevelDB successfully
> 2021-04-10T23:33:30Z Using obfuscation key for F:\defichain\chainstate: ZZZZZZZZZZZZZZZZZZZ
> 2021-04-10T23:33:30Z Opening LevelDB in F:\defichain\criminals
> 2021-04-10T23:33:30Z Opened LevelDB successfully
> 2021-04-10T23:33:30Z Using obfuscation key for F:\defichain\criminals: 0000000000000000
> 2021-04-10T23:33:30Z Opening LevelDB in F:\defichain\enhancedcs
> 2021-04-10T23:33:31Z Fatal LevelDB error: Corruption: 19728 missing files; e.g.: F:\defichain\enhancedcs/000142.ldb
> 2021-04-10T23:33:31Z You can use -debug=leveldb to get more complete diagnostic messages
> 2021-04-10T23:33:31Z Fatal LevelDB error: Corruption: 19728 missing files; e.g.: F:\defichain\enhancedcs/000142.ldb → I guess this is a problem. But What can I do?
> 2021-04-10T23:33:31Z : Error opening block database.
> Please restart with -reindex or -reindex-chainstate to recover. → This option is greyed out for me in the app, which means I cannot do this.
> 2021-04-10T23:33:31Z Aborted block database rebuild. Exiting.
> 2021-04-10T23:33:31Z Shutdown: In progress...
> 2021-04-10T23:33:32Z scheduler thread interrupt
> 2021-04-10T23:33:32Z Shutdown: done
>
>
>
>
>
> 2021-04-10T23:37:55Z Ignoring unknown configuration value rpcconnect
> 2021-04-10T23:37:55Z DeFi Blockchain version 1.6.2 (release build)
> 2021-04-10T23:37:55Z Assuming ancestors of block 9b257cb88630e422902ef2b17a3627ae2f786a5923df9c3bda4226f9551b1ea8 have valid signatures.
> 2021-04-10T23:37:55Z Setting nMinimumChainWork=000000000000000000000000000000000000000000003f2949bfe4efc275390c
> 2021-04-10T23:37:55Z Using the 'sse4(1way),sse41(4way),avx2(8way)' SHA256 implementation
> 2021-04-10T23:37:55Z Using RdSeed as additional entropy source
> 2021-04-10T23:37:55Z Using RdRand as an additional entropy source
> 2021-04-10T23:37:55Z Default data directory C:\...\DeFi Blockchain
> 2021-04-10T23:37:55Z Using data directory F:\defichain
> 2021-04-10T23:37:55Z Config file: C:\...\.defi\defi.conf
> 2021-04-10T23:37:55Z Using at most 125 automatic connections (2048 file descriptors available)
> 2021-04-10T23:37:55Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
> 2021-04-10T23:37:55Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
> 2021-04-10T23:37:55Z Using 8 threads for script verification
> 2021-04-10T23:37:55Z scheduler thread start
> 2021-04-10T23:37:55Z HTTP: creating work queue of depth 16
> 2021-04-10T23:37:55Z Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcauth for rpcauth auth generation.
> 2021-04-10T23:37:55Z Using rpcauth authentication.
> 2021-04-10T23:37:55Z HTTP: starting 4 worker threads
> 2021-04-10T23:37:55Z Using wallet directory C:/...
> 2021-04-10T23:37:55Z init message: Verifying wallet(s)...
> 2021-04-10T23:37:55Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
> 2021-04-10T23:37:55Z Using wallet C:/...\05042021.dat
> 2021-04-10T23:37:55Z BerkeleyEnvironment::Open: LogDir=C:/...\database ErrorFile=C:/...\db.log
> 2021-04-10T23:37:55Z Renamed Backup.dat to Backup.dat.ZZZZZZZZ.bak
> 2021-04-10T23:37:55Z BerkeleyEnvironment::Salvage: Database salvage found errors, all data may not be recoverable.
> 2021-04-10T23:37:55Z BerkeleyEnvironment::Salvage: WARNING: Unexpected end of file while reading salvage output.
> 2021-04-10T23:37:55Z Salvage(aggressive) found no records in Backup.dat.ZZZZZZZZ.bak.
> 2021-04-10T23:37:55Z Error: Backup.dat corrupt, salvage failed → should I also use an older Backup?
> 2021-04-10T23:37:55Z Shutdown: In progress...
> 2021-04-10T23:37:55Z scheduler thread interrupt
> 2021-04-10T23:37:55Z Shutdown: done
>
>
>
>
>
> 2021-04-11T00:07:06Z Ignoring unknown configuration value rpcconnect
> 2021-04-11T00:07:06Z DeFi Blockchain version 1.6.2 (release build)
> 2021-04-11T00:07:06Z Assuming ancestors of block 9b257cb88630e422902ef2b17a3627ae2f786a5923df9c3bda4226f9551b1ea8 have valid signatures.
> 2021-04-11T00:07:06Z Setting nMinimumChainWork=000000000000000000000000000000000000000000003f2949bfe4efc275390c
> 2021-04-11T00:07:06Z Using the 'sse4(1way),sse41(4way),avx2(8way)' SHA256 implementation
> 2021-04-11T00:07:06Z Using RdSeed as additional entropy source
> 2021-04-11T00:07:06Z Using RdRand as an additional entropy source
> 2021-04-11T00:07:06Z Default data directory C:\...\DeFi Blockchain
> 2021-04-11T00:07:06Z Using data directory F:\defichain
> 2021-04-11T00:07:06Z Config file: C:\...\.defi\defi.conf
> 2021-04-11T00:07:06Z Using at most 125 automatic connections (2048 file descriptors available)
> 2021-04-11T00:07:06Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
> 2021-04-11T00:07:06Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
> 2021-04-11T00:07:06Z Using 8 threads for script verification
> 2021-04-11T00:07:06Z scheduler thread start
> 2021-04-11T00:07:06Z HTTP: creating work queue of depth 16
> 2021-04-11T00:07:06Z Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcauth for rpcauth auth generation.
> 2021-04-11T00:07:06Z Using rpcauth authentication.
> 2021-04-11T00:07:06Z HTTP: starting 4 worker threads
> 2021-04-11T00:07:06Z Using wallet directory F:\defichain\wallets
> 2021-04-11T00:07:06Z init message: Verifying wallet(s)...
> 2021-04-11T00:07:06Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
> 2021-04-11T00:07:06Z Using wallet F:\defichain\wallets
> 2021-04-11T00:07:06Z BerkeleyEnvironment::Open: LogDir=F:\defichain\wallets\database ErrorFile=F:\defichain\wallets\db.log
> 2021-04-11T00:07:07Z init message: Loading banlist...
> 2021-04-11T00:07:07Z Cache configuration:
> 2021-04-11T00:07:07Z * Using 2.0 MiB for block index database
> 2021-04-11T00:07:07Z * Using 8.0 MiB for chain state database
> 2021-04-11T00:07:07Z * Using 440.0 MiB for in-memory UTXO set (plus up to 286.1 MiB of unused mempool space)
> 2021-04-11T00:07:07Z Warning -acindex and -acindex-mineonly are set, -acindex will be used
> 2021-04-11T00:07:07Z init message: Loading block index...
> 2021-04-11T00:07:07Z Opening LevelDB in F:\defichain\blocks\index
> 2021-04-11T00:07:07Z Opened LevelDB successfully
> 2021-04-11T00:07:07Z Using obfuscation key for F:\defichain\blocks\index: 0000000000000000
> 2021-04-11T00:07:23Z LoadBlockIndexDB: last block file = 6
> 2021-04-11T00:07:23Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=25607, size=52775816, heights=720942...746484, time=2021-03-20...2021-03-31)
> 2021-04-11T00:07:23Z Checking all blk files are present...
> 2021-04-11T00:07:23Z Opening LevelDB in F:\defichain\chainstate
> 2021-04-11T00:07:24Z Opened LevelDB successfully
> 2021-04-11T00:07:24Z Using obfuscation key for F:\defichain\chainstate: ZZZZZZZZZZZZZZZZZZZ
> 2021-04-11T00:07:24Z Opening LevelDB in F:\defichain\criminals
> 2021-04-11T00:07:24Z Opened LevelDB successfully
> 2021-04-11T00:07:24Z Using obfuscation key for F:\defichain\criminals: 0000000000000000
> 2021-04-11T00:07:24Z Opening LevelDB in F:\defichain\enhancedcs
> 2021-04-11T00:07:24Z Fatal LevelDB error: Corruption: 19728 missing files; e.g.: F:\defichain\enhancedcs/000142.ldb
> 2021-04-11T00:07:24Z You can use -debug=leveldb to get more complete diagnostic messages
> 2021-04-11T00:07:24Z Fatal LevelDB error: Corruption: 19728 missing files; e.g.: F:\defichain\enhancedcs/000142.ldb
> 2021-04-11T00:07:24Z : Error opening block database.
> Please restart with -reindex or -reindex-chainstate to recover.
> 2021-04-11T00:07:24Z Aborted block database rebuild. Exiting.
> 2021-04-11T00:07:24Z Shutdown: In progress...
> 2021-04-11T00:07:24Z scheduler thread interrupt
> 2021-04-11T00:07:24Z Shutdown: done

Hopefully you can help me with this issue.
Thank you for your work.
And stay healthy

sincerely

Alex

**Comment by izzycsy** [comment]
Hi @Alex080988 , thanks for your feedback, if I understood it correctly you're trying to install the Snapshot manually, to do this successfully, after deleting the `blocks`, `chainstate` and `enhancedcs` folders, try this:

1. Ensure app is not running 
2. Download the [Snapshot download](https://defi-snapshots-europe.s3.eu-central-1.amazonaws.com/snapshot-mainnet-738700.zip) manually  
3. Go to DeFi Blockchain (Windows) folder 
`C:\Users\<username>\AppData\Roaming\DeFi Blockchain` 

4. Unzip the downloaded Snapshot, replace the `individual respective folders` in the DeFi Blockchain (Windows) folder 
5. Open your app, and it should start syncing from 90%+

**Comment by thedoublejay** [comment]
Replied to your e-mail @Alex080988. Let me know if we can close your issue thanks!

**Comment by Alex080988** [comment]
Hi. 
Thanks a lot for the help. The solution was following. For some reason I had over and over currupted files in my blockchain-archive:

0. Downloading an other version of the snapshot-file and unpacked it manually
- Asia - https://defi-snapshots.s3-ap-southeast-1.amazonaws.com/snapshot-mainnet-762547.zip
- Europe - https://defi-snapshots-europe.s3.eu-central-1.amazonaws.com/snapshot-mainnet-762547.zip
1. When you open the app, it will show you re-index modal. Click on Sync Node.
2. App will restart, you will see that the app will sync from 0.
**3. Close the app properly**
4. Unzip the contents of the snapshot on your blockchain directory.
**5. Open the app again.**
6. sync starts from 90+%

Thanks a lot to Jose Jaime Adonis, who really was pacient with me for solving this ;)
More or less the same what izzyscy wrote (also thanks) - but opening and closing the app was really important
