### ISSUE TITLE
Do not corrupt the whole DB on poor app shutdown

### ISSUE THREAD

**Issue by John-Gee** [DeFiCh/app#754]
This may be better as a feature request or an idea in the discussion tab, but I feel this strongly needs to be taken care of ASAP, so a bug instead of an enhancement seems to match the priority.

#### What happened:

When the app is not cleanly shut down, it is very common to see the DB corrupted.

#### What you expected to happen:

Hopefully the DB would not corrupt so easily, thanks to atomic operations, checksums, maybe even parity (that might be too CPU intensive), etc.
If it really, really, gets corrupted and cannot be fixed, the app should only download the bits it needs, definitely not the whole thing again (bittorent style).

#### How to reproduce it (as minimally and precisely as possible):

1- Crash the app
2- Reopen it and get ready to sync from scratch...

**Comment by izzycsy** [comment]
Hi @John-Gee , thanks for your feedback, the team was aware of this and hence the implementation of this: 

<img width="1012" alt="Wait for app to quit itself" src="https://user-images.githubusercontent.com/65014479/114376698-768a6080-9bb8-11eb-95be-4e909bb080da.png">

Users need to be patient with the app as it's unlike centralised applications where you can force shut it down and reload it the next time. In conclusion, let the app close itself when you click `close app`. We appreciate your feedback and will inform the team of this, thank you!

**Comment by John-Gee** [comment]
Well, I don't know if that is correct. I would appreciate a technical reason why things must stay like this, but saying it's unlike CeFi apps is not really helpful. Other crypto wallets I've used don't have that problem to such a bad extent.
For instance I've just tried killing the process of the dogecoin-qt wallet right after syncing it and then restarting it, it was not fully synced anymore but took maybe a minute to be done. That's quite different. After that both sync'd dogecoin and litecoin wallets processes were killed and restarted multiple time with no trouble at all. What makes this wallet so much weaker and why is it acceptable?


The warning is no remedy, the other day power went down so my computer went off and I had to fully resync DeFiCh, no time to see that warning nor could I have done anything useful with it anyway. I'm thinking power cutting down is not that uncommon, especially with mobile devices.

**Comment by nippur72** [comment]
I also think this is a BIG issue - my computer did a shutdown for updates and when I reopened the Defi Wallet app it said "corrupted database"... :sad: There must be way, please consider reopening the issue.

**Comment by John-Gee** [comment]
And if there is no way, at least I'd love to know why.

**Comment by endeffects** [comment]
Please do not persist corrupt data to the blockchain file, use buffers, chunks or other technics to prevent this. It is really annoying!
