### ISSUE TITLE
Wallet is not Synchronizing

### ISSUE THREAD

**Issue by felik-panda** [DeFiCh/app#755]
#### What happened: My Windows was automatically updated last week, then my wallet started to sync again from 0%. After that my wallet can not sync until 100. When it reached 70% - 85%, it always show notification network error and pending balance failure. Could you help me? 

I also has attached my app log.

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.3
- Operating System (OS): Windows 10

#### Anything else we need to know?:

![1](https://user-images.githubusercontent.com/82272514/114355427-a8d89580-9b99-11eb-8a95-4ddc0f48acc9.png)
[applog.zip](https://github.com/DeFiCh/app/files/6294630/applog.zip)

**Comment by izzycsy** [comment]
Hi @felik-panda , can you try this method, it's manual but it's basically the same thing as using the automatic snapshot via the app. Please **backup your wallet.dat** before proceeding: 

**Snapshot (sync from 90%+)** 
 1. Ensure app is not running  
 2. Download the [Snapshot](https://defi-snapshots-europe.s3.eu-central-1.amazonaws.com/snapshot-mainnet-738700.zip) 
  3. In app, `RESET & REINDEX` via Settings

<img width="790" alt="Settings   Reset   Reindex" src="https://user-images.githubusercontent.com/65014479/114375835-a84ef780-9bb7-11eb-8c26-e423830803eb.png">

  4. Wait for 1%, close the app  
  5. Go to DeFi Blockchain (Windows) folder 
Windows — C: 
`C:\Users\<username>\AppData\Roaming\DeFi Blockchain`  
6. Unzip the downloaded Snapshot, drag and replace the folders `blocks`, `chainstate` and `enhancedcs` respectively in the DeFi Blockchain (Windows) folder 
6. Open the app, it should start synchronising from 90%+

**Comment by felik-panda** [comment]
Thank you for your reply, i will update you later.
