### ISSUE TITLE
Wallet freeze after comand "listmasternodes"

### ISSUE THREAD

**Issue by supervolot** [DeFiCh/app#758]
#### What are your environment parameters?

- DeFi Wallet Version: v2.3.3
- Operating System (OS): windows server 2019

**Comment by izzycsy** [comment]
Hi @supervolot , may I know what OS are you using — Windows / Mac? Can you send you app logs please. Thank you.

**Comment by nippur72** [comment]
today I had the same problem TWICE (I've learned how to restore the blockchain from backup).

I type the `listmasternodes` command in the CLI console and after a while the app became totally unresponsive. It was not possible to close it, so I had to kill the process from Windows' Task Manager. 

I was at the latest block.

**Comment by izzycsy** [comment]
Hi @nippur72 , thanks could you send your app logs for our team to investigate please? Thank you.
