### ISSUE TITLE
Unable to start blockchain

### ISSUE THREAD

**Issue by smac1990** [DeFiCh/app#760]
#### What are your environment parameters?

- DeFi Wallet Version: V 2.3.3
- Operating System (OS): OS macOS Big Sur - 20.3.0

**Comment by izzycsy** [comment]
Hi @smac1990 , regarding the issue [`
Unable to Start Blockchain`](https://github.com/DeFiCh/app/issues/733), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you. 

Try to reinstall the app (do not delete anything you’re unfamiliar with and keep your `wallet.dat` safe). If you haven’t already make a backup of your wallet.dat or have them on another repository, you may find it here: 

Mac — Go to Folder:  /Users/<username>/Library/Application Support/Defi/wallets 
<img width="822" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/114893312-27eef780-9e40-11eb-99d3-f44ac96c26d5.png">

Make a copy of the `wallets` folder, and paste in Documents (for example), so it’s easier to find it when restoring wallet. 

1. Download update from <https://defichain.com/downloads/>
2. Open `DeFi-Wallet-2.3.3.dmg` file
3. Drag and replace your current app

<img width="540" alt="Replace app1" src="https://user-images.githubusercontent.com/65014479/114892193-1fe28800-9e3f-11eb-96e7-5b849f154f8a.png">

<img width="538" alt="Replace app2" src="https://user-images.githubusercontent.com/65014479/114892214-23760f00-9e3f-11eb-90d8-25ff77a38fd9.png">

4. Go to System Preferences > Security & Privacy > `Open Anyway` 
<img width="665" alt="Open Anyway" src="https://user-images.githubusercontent.com/65014479/114892529-6e902200-9e3f-11eb-8108-599163e6a60d.png">

5. Restore wallet from backup (wallet.dat) – Guide the app to where where your `wallet.dat` is located

<img width="1021" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/114892563-78198a00-9e3f-11eb-90ec-9acb7f7165e1.png">
