### ISSUE TITLE
Unable to recall passphrase, unable to reset passphrase

### ISSUE THREAD

**Issue by aiteanu** [DeFiCh/app#761]
#### What happened:
I have created a new wallet and stored the backup on file "wallet.dat". After sending some coins on the wallet and tried to do some operations, the passphrase is requested in order to unlock. As I cannot remember the passphrase (tried several) I wanted to reset it, as indicated in the app ("Losing it means you need to reset DeFi app to default settings and restore your wallets again."). As there is no explicit option in the GUI to reset the app to default, I have uninstalled and re-installed it again (yes, with the long waiting for the sync...). When I restore the wallet and try to set a new passphrase, I get the following error: "Error: running with an encrypted wallet, but encryptwallet was called" (s. screenshot). 
![image](https://user-images.githubusercontent.com/49910464/114888761-d166c680-9e09-11eb-87cc-e5d79de1d901.png)
If I click "Later" the wallet is locked and cannot do anything further. 

#### What you expected to happen:
The new passphrase shall be accepted and set correctly. 

#### How to reproduce it (as minimally and precisely as possible):
Close current wallet. Open backup. Click on "lock" symbol in the upper left corner as long as apears as not locked. Enter a new passphrase. Click on Enable Locking. 

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.3
- Operating System (OS): Windows 10

#### Anything else we need to know?:
Is there another was to reset the app to the "default settings"?

**Comment by izzycsy** [comment]
Hi @aiteanu , to reset a new passphrase, you need your old passphrase, please try to recall it. Perhaps you written is down somewhere? The passphrase is crucial to unlocking your wallet and performing the functions. Losing it means you won't be able to use the functions.

**Comment by aiteanu** [comment]
Hi @izzycsy ! Thanks for the quick reply. At the moment I cannot remember putting a passphrase at all at the creation of the wallet. I'm vaguely remember that I have pressed the "Later" button. Normally I'm taking photos from all sensitive passwords. And I have tried all my typical passphrases. 
But anyway, if it is not possible to reset it, the indication on the window "Keep your passphrase safe. Losing it means you need to reset DeFi app to default settings and restore your wallets again." is somehow misleading. Is there anything that can be done?
One more point: the encryption was implemented recently. Could be possible, that the wallet was created with a previous version of the DeFiChain app?

**Comment by izzycsy** [comment]
Hi @aiteanu , creating the passphrase is a double confirmation process; like in the screenshot you sent, so if the app is prompting you for a passphrase it'd would mean you've created one. Yes, you can try to `Restore Wallet via Mnemonic Seed` then set a passphrase again, but only if it's an unencrypted wallet (no passphrase yet), I can't guarantee that your tx will appear because the team stop supporting of mnemonic seed since v2.3.0. Alternatively, you can try `Restore Wallet via Backup` using a `wallet.dat` that has not been encrypted.
