### ISSUE TITLE
issue sending coin to an external addres

### ISSUE THREAD

**Issue by MABRAHANTEE** [DeFiCh/app#770]
#### What are your environment parameters?

- DeFi Wallet Version:
- Operating System (OS):

**Comment by MABRAHANTEE** [comment]
hi there, 
why I cant send my btc out of my 
wallet

**Comment by MABRAHANTEE** [comment]
[IMG_2679.HEIC.zip](https://github.com/DeFiCh/app/files/6330923/IMG_2679.HEIC.zip)

**Comment by MABRAHANTEE** [comment]
[IMG_2680.HEIC.zip](https://github.com/DeFiCh/app/files/6330928/IMG_2680.HEIC.zip)

**Comment by izzycsy** [comment]
Hi @MABRAHANTEE , the address you’re using is not a DeFiChain-friendly address. You can retrieve the DeFiChain address via <cakedefi.com>, try sending a small amount first to test.

1. Click on Balances in <cakedefi.com>
2. In the BTC row, click on Deposit button
3. You'll see the Transfer Network options `BTC` / `DeFiChain`

<img width="375" alt="Click DeFiChain   BTC" src="https://user-images.githubusercontent.com/65014479/115211851-8e229580-a132-11eb-84df-b1cb27b407f9.png">

4. Under the QR Code states your DeFiChain address, copy it
5. Go back to DeFi Wallet > BTC wallet > Send
6. Paste your DeFiChain address into DeFi Wallet `To address` field

For future enquiries on how to use the wallet, you can ask the community on [DeFiChain Telegram (EN)](https://t.me/defiblockchain).
