### ISSUE TITLE
bip32 dependency causes seg fault when launched with electron

### ISSUE THREAD

**Issue by prasannavl** [DeFiCh/app#772]
Recently, I noticed building and running this with electron on Linux x64_86 arch on Debian derived OSes with the newer versions of node to cause segfault without much any information.

Node version: v12.21.0 

- Electron worked fine by itself.
- Running bare electron with the generated wallet app causes segfault prevent it from starting up with no information. 
- Since running with electron itself segfaults, all derivatives including AppImage builds segfault. 
- Attaching [package-lock.json](https://github.com/DeFiCh/app/files/6331283/package-lock.json.tar.gz) for exact version info of packages.

Running with gdb:

```
Starting program: /home/logx/src/repos/defichain/app/dist/linux-unpacked/defi-wallet 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff41ca700 (LWP 772090)]
[Detaching after fork from child process 772091]
[Detaching after fork from child process 772092]
[Detaching after fork from child process 772093]
[New Thread 0x7ffff39c9700 (LWP 772096)]
[New Thread 0x7ffff31c8700 (LWP 772097)]
[New Thread 0x7ffff29c7700 (LWP 772098)]
[New Thread 0x7ffff19c5700 (LWP 772100)]
[New Thread 0x7ffff21c6700 (LWP 772099)]
[New Thread 0x7ffff11c4700 (LWP 772101)]
[New Thread 0x7ffff016c700 (LWP 772102)]
[New Thread 0x7fffef96b700 (LWP 772103)]
[New Thread 0x7fffef16a700 (LWP 772104)]
[New Thread 0x7fffee969700 (LWP 772105)]
[New Thread 0x7ffff0964700 (LWP 772106)]

Thread 1 "defi-wallet" received signal SIGSEGV, Segmentation fault.
0x00007fffeafac93e in ?? () from /lib/x86_64-linux-gnu/libnode.so.72
(gdb) b
Breakpoint 1 at 0x7fffeafac93e
(gdb) bt
#0  0x00007fffeafac93e in  () at /lib/x86_64-linux-gnu/libnode.so.72
#1  0x00007ffff7fe1fe2 in call_init
    (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffdba8, env=env@entry=0x115db8cf3180) at dl-init.c:72
#2  0x00007ffff7fe20e9 in call_init (env=0x115db8cf3180, argv=0x7fffffffdba8, argc=1, l=<optimized out>) at dl-init.c:30
#3  _dl_init (main_map=0x115db8d87000, argc=1, argv=0x7fffffffdba8, env=0x115db8cf3180) at dl-init.c:119
#4  0x00007ffff62a22bd in __GI__dl_catch_exception (exception=<optimized out>, operate=<optimized out>, args=<optimized out>)
    at dl-error-skeleton.c:182
#5  0x00007ffff7fe6058 in dl_open_worker (a=a@entry=0x7fffffff8420) at dl-open.c:758
#6  0x00007ffff62a2260 in __GI__dl_catch_exception
    (exception=0x7fffffff8400, operate=0x7ffff7fe5ca0 <dl_open_worker>, args=0x7fffffff8420) at dl-error-skeleton.c:208
#7  0x00007ffff7fe58fa in _dl_open
    (file=0x115db8f6aab0 "/tmp/.org.chromium.Chromium.YdfiJH", mode=-2147483647, caller_dlopen=0x55555cc8d009, nsid=-2, argc=1, argv=0x7fffffff8400, env=0x115db8cf3180) at dl-open.c:837
#8  0x00007ffff7951258 in dlopen_doit (a=a@entry=0x7fffffff8640) at dlopen.c:66
#9  0x00007ffff62a2260 in __GI__dl_catch_exception
    (exception=exception@entry=0x7fffffff85e0, operate=0x7ffff7951200 <dlopen_doit>, args=0x7fffffff8640) at dl-error-skeleton.c:208
#10 0x00007ffff62a231f in __GI__dl_catch_error
    (objname=0x115db8dc22b0, errstring=0x115db8dc22b8, mallocedp=0x115db8dc22a8, operate=<optimized out>, args=<optimized out>)
    at dl-error-skeleton.c:227
#11 0x00007ffff7951a65 in _dlerror_run (operate=operate@entry=0x7ffff7951200 <dlopen_doit>, args=args@entry=0x7fffffff8640)
    at dlerror.c:170
#12 0x00007ffff79512e4 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#13 0x000055555cc8d009 in  ()
#14 0x0000000000000000 in  ()
```

The solution is to remove the `bip32` package that's used for mnemonic.

**Comment by prasannavl** [comment]
The reason for this: https://github.com/bitcoinjs/bip32/issues/39

Outdated secp256k1 on bip32.

**Comment by izzycsy** [comment]
Hi @prasannavl , thanks for your feedback, for future post (if it's not a suspected bug) you can post your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), share your findings with the community. In the mean time, I'll provide a link to [Running the app as a webapp (e.g. from a Raspberry Pi)](https://github.com/DeFiCh/app/discussions/736) , there are other community members in discussion on an idea that is Linux-related. Thank you.

cc: @thedoublejay

**Comment by prasannavl** [comment]
Thanks @izzycsy. Noted - just a quick clarification that this however is a bug that prevents the project from running in later versions of node due to bip32 libary that uses deprecated Chromium APIs that have been removed in newer versions. 

Possible AIs: 
- bip32 dep needs to be fixed
- defiwallet needs to drop that as a dependency
- Pin to node versions perhaps with something like, https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines as temporary solution.

**Comment by izzycsy** [comment]
Hi @prasannavl , thank you, the team has been notified of this.
