### ISSUE TITLE
Error on blockHeight 759000

### ISSUE THREAD

**Issue by moneymining83** [DeFiCh/app#777]
#### What happened:
Hello,
i have a big Probleme.

The Defi App has a Error at block 759000.
I would fix it with Snapshot, with normal sync nood, reindex. Everytime the same issue and it takes 3 days at all.
Now i make reset and reindex. It load a lil bit quicker but if that dont work too, i have a very expensiv problem.
I have 4 Backups, the last from 08.04.21.

#### What you expected to happen:
Block error occured.
The issue occurred several times, but when the last nood was loaded (not all blocks) it worked again.

#### How to reproduce it (as minimally and precisely as possible):

1. open app
2. new Blocks loading
3. Block error
4. at Block 759000 the App says: Coruppte block database, sync nood or snapshot
5. No possibility to load all blocks.

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.3
- Operating System (OS): Windows 10 Home 64 Bit

#### Anything else we need to know?:

Please help me.
Thanks bevor.

[Logs.zip](https://github.com/DeFiCh/app/files/6352862/Logs.zip)

**Comment by izzycsy** [comment]
Hi @moneymining83 , thanks for your feedback, can you check your storage capacity? It might be because you ran out of storage / due to an internet connection issue.

**Comment by izzycsy** [comment]
Hi @moneymining83 , you can try to add some nodes. In the [DeFiChain-Wiki](https://defichain-wiki.com/wiki/Addnode) there is an article how to do this. or simply try via the CLI:
`addnode seed.mydeficha.in:8555 add`

**Comment by izzycsy** [comment]
HI @moneymining83 , regarding the issue [`Unable to sync to 100% #853`](https://github.com/DeFiCh/app/issues/853), we can further discuss on the issue there. We would like to keep same issues in one thread. We'll update when the team has a fix ready. Thank you.
