### ISSUE TITLE
password not working, any way to recover? I have old passphrase written down

### ISSUE THREAD

**Issue by marklark2** [DeFiCh/app#784]
HI there, as title says, I changed my password and right away wrote it down in several places.  When I went to add funds about a day later it won't work.  Is there any way to recover or reset password?

**Comment by izzycsy** [comment]
Hi @marklark2 , unfortunately no, your passphrase is like your mnemonic seed, nobody would have access to it except for yourself. Please try to remember, there's no limit to trying.
