### ISSUE TITLE
Win: Stuck on blockHeight 746484

### ISSUE THREAD

**Issue by itmlgife** [DeFiCh/app#785]
#### What happened:
Hi, I have been trying recently to install the DefiChain app on Windows 10 and I seem to be unable to have the application syncing the blocks. I tried many things including using the snapshot, re-indexing, but the progress bar does not seem to make any progress.

#### What you expected to happen:
I would expect the progress bar to increase the sync number to 100% and the wallet app to start functioning.

#### How to reproduce it (as minimally and precisely as possible):
The issue appears to occur systematically during any install of the app. I have currently installed version 2.3.3.

The steps have been:
  1. Download the installation package from Github (DeFi-Wallet-Setup-2.3.3.exe)
  2. Install the application following the installation guide
  3. Running the application
  4. Clicking on the i on top of the progress bar
  5. Clicking on the sync with snapshot button
  6. After the snapshot is loaded, the progress bar moves to 90%+ and it is stuck there for days

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.3
- Operating System (OS): Windows 10 Pro

#### Anything else we need to know?:

1 - I tried the installation also having the Firewall disabled, but it didn't make a difference
2 - I checked the event viewer on Windows and I can find some DCOM configuration related issues that appear to be correlated with the local activation privileges on a specific component. These messages are logged as warning and are fired every time the DefiChain App is executed.

[bin.log](https://github.com/DeFiCh/app/files/6366694/bin.log)
[app.log](https://github.com/DeFiCh/app/files/6366695/app.log)
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user DESKTOP-0QMM46Q\Gianluca SID (S-1-5-21-2225747369-428820186-1959840793-1002) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.

**Comment by RIPAC** [comment]
I have the same problem on a Mac. It was working this morning and now says "Unable to Start Blockchain" What's this? How do I fix? I see your comment about writting /triage accepted but how do I use that, where do I write that?

**Comment by izzycsy** [comment]
Hi @itmlgife , thanks for your feedback, can you check if you've sufficient storage? On Windows it currently requires >100GB of space. The team is working on a light wallet and reducing the storage needed to run the app. Please give us time to investigate your logs, can you send your app config as well? 

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/115959481-fb716480-a53e-11eb-9305-a519f13f68ea.png">

Hi @RIPAC , could you also check your storage? On Mac, it currently requires >50GB of space. 

Regarding the issue [`Unable to Start Blockchain`](https://github.com/DeFiCh/app/issues/733), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.

**Comment by itmlgife** [comment]
Hi Bella, thanks for coming back to me. Attached the logs from this morning and the config file. 
I confirm that I have 300GB free on this machine.
I can also confirm that the app has been running since yesterday and it is stuck synchronizing since block 746484, which is the number I since the snapshot was loaded.

[logs.zip](https://github.com/DeFiCh/app/files/6369662/logs.zip)

**Comment by izzycsy** [comment]
Hi @itmlgife , if the snapshot has been successfully downloaded, when you click `RESET & REINDEX` it should bring you to start again at block 746484. Can you try again and let me know the result? Please give us time to investigate the logs. Thank you.

<img width="790" alt="Settings   Reset   Reindex" src="https://user-images.githubusercontent.com/65014479/115992610-21f7d400-a601-11eb-8932-94104cc950dd.png">

**Comment by itmlgife** [comment]
Hi Bella, I did click on reset & index. The app performed a reset, reloaded the content from the snapshot and unfortunately it is again stuck at block 746484. It is now probably 2 hours that it is sitting there with no progress. 

I am sending you the logs again, in case they are useful. Thanks!

[logs.zip](https://github.com/DeFiCh/app/files/6372052/logs.zip)

**Comment by Odynius** [comment]
I'm having kind of the same problem. Trying to use the DeFi Wallet App on Win10, and can't synchronize with the blockchain. The synchronization fails at random points and when i try to use the snapshot it says unable to connect or something.

**Comment by izzycsy** [comment]
Hi @Odynius , it could be the lack of storage (approx. 130GB) or bad internet connection. Our team is working on reducing the storage required and Light Wallet. Thank you for your patience.

**Comment by Odynius** [comment]
Yeah, thanks, i just saw that, too. Is it possible to save everything on the HDD? My C:\ won't have enough space.

**Comment by izzycsy** [comment]
Hi @Odynius , yes I would think it's possible. Please make a backup of your wallet.dat before proceeding with reinstallation. For Windows you can specify where to store your application. Regarding the issue [`Win: Reinstalling on D:`](https://github.com/DeFiCh/app/issues/673), we can further discuss on the issue there, I've provided a step by step guide in that thread.  Let’s keep this thread related to what the original author opened. Thank you for your understanding.

**Comment by itmlgife** [comment]
Hi Bella,

I did as you asked. Once I used the first instruction the block number on the bottom side of the screen went back to 746483 and once I used the last command it went to 746484.

[Screenshots.zip](https://github.com/DeFiCh/app/files/6376739/Screenshots.zip)

**Comment by itmlgife** [comment]
And sorry, yes...I did receive null and null after running each operation. 

Finally, since I ran the commands, the counter is stuck at 746484.

Thanks for your help so far!

**Comment by izzycsy** [comment]
Hi @itmlgife , please give us time to investigate. Thank you.

**Comment by itmlgife** [comment]
Hi Bella, this message is to let you know that I found what to do to unlock the synchronization. While watching one of the community projects (deficha.in masternode service) I stumbled across the guide to install the master node in the defichain wiki that was linked from the website of deficha.in.

In the instructions there was a suggestion to add a node to the wallet manually using the addnode command. For example: addnode "45.157.177.82:8555" "add".

I gave it a try and it worked. Once I added the node manually and getconnectioncount came back to be 1...it started synchronizing.

Let me know if any of this does not make sense. Is it normal that the Wallet does not discover automatically what nodes to connect to right after the installation?

Let me know. Thanks!

**Comment by izzycsy** [comment]
Hi @itmlgife , ah fantastic, thanks for the update. Yes it happens sometimes, usually the app tries to find peers to sync, when it fails it could need a boost hence `addnode`. You can find out more here: https://defichain-wiki.com/wiki/Addnode , the list is updated by the community. 

Good find! With that I'll be closing this issue. Thank you.
