### ISSUE TITLE
DEX: provide a meaningful error message

### ISSUE THREAD

**Issue by nippur72** [DeFiCh/app#788]
In DEX when the balance is zero (0) the app gives a vague error message "Something went wrong"... can we have a more meaningful and less scary message? See the picture below:

![image](https://user-images.githubusercontent.com/2598443/116066498-6ed2bd80-a688-11eb-8f10-d49112a0f566.png)

**Comment by izzycsy** [comment]
Hi @nippur72 , thanks for the feedback. Please give us time to update the error message.

**Comment by izzycsy** [comment]
Hi @nippur72 , [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a mandatory update. Please read through the release notes before updating. _This comment is to notify you about the update._
