### ISSUE TITLE
do not show "NaN" when dividing by zero

### ISSUE THREAD

**Issue by nippur72** [DeFiCh/app#789]
In DEX, when the amount is zero the app shows an ugly "NaN"... see the picture below

![image](https://user-images.githubusercontent.com/2598443/116067167-32539180-a689-11eb-8d25-b5bc62164e7c.png)

**Comment by izzycsy** [comment]
Hi @nippur72 , may I know how did you get to that screen? 

<img width="1019" alt="Screenshot 2021-04-26 at 6 42 29 PM" src="https://user-images.githubusercontent.com/65014479/116070506-4fa35280-a6bf-11eb-8b1e-98cb239b8467.png">

**Comment by nippur72** [comment]
yes, there was no receive address

**Comment by nippur72** [comment]
but it does it even when there is an address, I guess it's the 0 balance resulting in a division by zero
![image](https://user-images.githubusercontent.com/2598443/116106030-27612700-a6b2-11eb-823b-3f1b55873425.png)

**Comment by izzycsy** [comment]
Hi @nippur72 , thanks for your feedback, please give us time to improve the UX for this. Thank you.

**Comment by izzycsy** [comment]
Hi @nippur72 , [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a mandatory update. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @nippur72 , [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**. Please read through the release notes before updating. This issue has been resolved in this build. Thank you.
