### ISSUE TITLE
insufficient funds

### ISSUE THREAD

**Issue by hashrandy** [DeFiCh/app#79]
I have got 0.000089 BTC and 4.9 DFI in my wallet but I can neither LM, DEX nor send back the coins to cake. Get always the message 'insufficient funds". Is on the defi app an minimum amount? If not, what can I do. I attached the logs. best regards, [randy]
[bckpdfi.txt](https://github.com/DeFiCh/app/files/5630580/bckpdfi.txt)
[defiapp.log](https://github.com/DeFiCh/app/files/5630581/defiapp.log)
[defibin.log](https://github.com/DeFiCh/app/files/5630582/defibin.log)

**Comment by Yannick1712** [comment]
Did you try a little bit less than the max amount to have enough DFI to pay the fee for the transaction?

**Comment by izzycsy** [comment]
Hi @hashrandy , thanks for your feedback. May I know what OS you're using? Could you describe your user flow more? We need more details in order investigate how to reproduce this issue. In the mean time, kindly install the latest version of the app <https://github.com/DeFiCh/app/releases/tag/v2.1.1>.

@Yannick1712 thanks for your assistance!

**Comment by hashrandy** [comment]
hi, i tried to install the new version, but i got this error message:
![Screenshot 2020-12-03 114207](https://user-images.githubusercontent.com/75382745/100999189-b8493180-355c-11eb-995f-bfae48584b37.png)

**Comment by hashrandy** [comment]
OS ist Windows 10

**Comment by hashrandy** [comment]
How can I restart with reindex or reindex-chainstate?

**Comment by DanielHirsbrunner** [comment]
@hashrandy try this for reindexing: 
![image](https://user-images.githubusercontent.com/17408162/101261136-32341300-3735-11eb-9280-ca02d8937dc3.png)

**Comment by hashrandy** [comment]
sorry, that diesn't work. the error-meesage comes before seeing your screen. So I can't set options.

**Comment by izzycsy** [comment]
Hi @hashrandy , the team is investigating this issue, thank you for your understanding.

**Comment by izzycsy** [comment]
Hi @hashrandy , is the `insufficient funds` error still present with the new update v2.1.4?
<https://github.com/DeFiCh/app/releases/tag/v2.1.4>

**Comment by izzycsy** [comment]
Hi @hashrandy , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue w new information (include screenshots) and your app logs. Thank you.

**Comment by BastianReed** [comment]
i have the same issue since today with neuest version. 
i Have a Mac OS System.

**Comment by BastianReed** [comment]
> @hashrandy try this for reindexing:
> ![image](https://user-images.githubusercontent.com/17408162/101261136-32341300-3735-11eb-9280-ca02d8937dc3.png)

if i want to do this, the Pop Up Display Show: Restart Node...
This is hours displayed and nothing more happens.
