### ISSUE TITLE
My Wallet got error again and cannot synch to 100%

### ISSUE THREAD

**Issue by felik-panda** [DeFiCh/app#797]
#### How to reproduce it (as minimally and precisely as possible):

1. My Wallet  got error and started to sych from 0%.
2. I have experienced it before and reported it to gifthub, and you have told me how to solve this.  And i tried to use you methods again.
3. So I tried to reset and reindex, then i waited the synch to 1% then i close the app. 
4. I also has download the snapshot link that you have given to me and copied paste it to the defi folder.
5. The sych start from 90%+, but now it always stucked at 94% until 95%.

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.3
- Operating System (OS): Windows 10

#### Anything else we need to know?:

[Defi.zip](https://github.com/DeFiCh/app/files/6403975/Defi.zip)

**Comment by izzycsy** [comment]
Hi @felik-panda , can you check your storage? Currently the app requires 130GB. Snapshot is also automatic, no need to manually download anymore. Your PC is likely stuck at 94% because it cannot find storage. Quit the app first and make some space and open the app to continue syncing. 

<img width="244" alt="`i` to trigger Snapshot download" src="https://user-images.githubusercontent.com/65014479/116679248-e2543200-a9dc-11eb-8eda-d0b785a79a5b.png">

**Comment by felik-panda** [comment]
Hi, thanks for your respond! I have checked my Storage, I still have plenty free space. And when i opened my  wallet, it shows that corrupted  block data base detected. Do you have solution for this?
![corrupted](https://user-images.githubusercontent.com/82272514/116704664-dfb20680-a9f5-11eb-84f7-7392891726f9.png)
![Free space after reset reindex](https://user-images.githubusercontent.com/82272514/116704783-fbb5a800-a9f5-11eb-84f1-1a42bcf2847e.png)

**Comment by izzycsy** [comment]
Hi @felik-panda , did you turn off your anti-virus? Windows tend to have anti-virus installed, the anti-virus hooks into file system natively for real time detection which is a common cause of file related corruption issues.

**Comment by izzycsy** [comment]
Hi @felik-panda , [v2.3.5](https://github.com/DeFiCh/app/releases/tag/v2.3.5) is out. Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.
