### ISSUE TITLE
Failed to restore from snapshot

### ISSUE THREAD

**Issue by nippur72** [DeFiCh/app#799]
#### What happened:
After the snapshot download completed, the app closed, but on reopening it started sync from block 0 instead of 746484.

#### What you expected to happen:
Resync from block 746484

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.3
- Operating System (OS): Ubuntu 20.10 running inside Virtual Box VM

#### Anything else we need to know?:
If I try to download again the snapshot and repeat the process, a brief error notification appears as you can see in the image below:
![image](https://user-images.githubusercontent.com/2598443/116778158-981c9080-aa70-11eb-997c-94d6108ca3ce.png)

Attached is the log of the app: [log1.log](https://github.com/DeFiCh/app/files/6409304/log1.log)

**Comment by nippur72** [comment]
Additional detail: I now see that the snapshot file is not accessible: 
![image](https://user-images.githubusercontent.com/2598443/116779354-34956180-aa76-11eb-8c48-fc96e52a1deb.png)

**Comment by izzycsy** [comment]
Hi @nippur72 , can you try again, it should be back to normal.

**Comment by nippur72** [comment]
it got corrupted again when at around 95% of the sync. I'll wait for a more recent snapshot and I hope the next release will be more reliable.

**Comment by nippur72** [comment]
@izzycsy today i tried it again and it synchronized rather quickly in 1-2 hours (including snapshot download). I didn't change anything.
