### ISSUE TITLE
App does not start anymore after announcement of 2.1.1

### ISSUE THREAD

**Issue by Leon2023** [DeFiCh/app#80]
My App is stuck at starting screen since the announcement of the new version. After updating to 2.1.1 nothing has changed and the app still does not leave the loading screen.

[1.log](https://github.com/DeFiCh/app/files/5631037/1.log)

The other two logs  I was not able to attach.
![Unbenannte](https://user-images.githubusercontent.com/75386737/100909999-aff5e580-34cd-11eb-9356-e7ae73493804.PNG)

**Comment by izzycsy** [comment]
Hi @Leon2023 , thanks for your feedback. May I know what OS system you're using? Could you describe your user flow more? We need more details in order investigate how to reproduce this issue. Thank you.

**Comment by Leon2023** [comment]
> Hi @Leon2023 , thanks for your feedback. May I know what OS you're using? Could you describe your user flow more? We need more details in order investigate how to reproduce this issue. Thank you.



I'm Using Windows 10 64bit - I have started the App in the morning and everything worked - even though the loading screen took > 1 min as often to load but after that everything was fine. Then I saw Fabio announce the 2.11 so i wanted to restart the app to make the update but the loading screen did not disappear anymore. I tryed multiple times but even after 10 minutes there was still the loading screen. In the log it says something if find update error i think. I was not able to submit the other 2 logs as one was to large (> 100Mb) and the other one was not a accepted datatype. Hope that helps :)

**Comment by izzycsy** [comment]
@Leon2023 thanks for the information. Let us investigate this, in the mean time, you can try and see if the latest update v2.1.2 <https://github.com/DeFiCh/app/releases/tag/v2.1.2> solves the issue. Download and replace your current app. If you've more details & screenshots do send them. Thank you.

**Comment by Leon2023** [comment]
I did a completly fresh install with 2.1.3 and still the same issue - log is allot less crowded now though so it might be easier to detect the error - attached you'll find the newest log (i think its german though ...) it referrs to a comand "wmic " which is supposily w´ritten wrong but i have no idea from these logs.
[1.log](https://github.com/DeFiCh/app/files/5636692/1.log)

**Comment by izzycsy** [comment]
@Leon2023 Thanks for the feedback, please give us time to investigate this issue.

**Comment by izzycsy** [comment]
Hi @Leon2023 , could you export and send me your `Binary.log` file please? 

<img width="289" alt="Screenshot 2020-12-17 at 3 04 03 PM" src="https://user-images.githubusercontent.com/65014479/102454568-31767780-4079-11eb-9815-391322ad1445.png">

**Comment by Leon2023** [comment]
Dear Bella, the App now magically started working again. On another device it already worked directly after i have posted the issue but now it works on the device where the issue occurred as well - I don't know what you fixed or not but I think the Binary log would not help now that it works again, would it?

**Comment by izzycsy** [comment]
Hi @Leon2023 , I think it might help us investigate what went wrong. Could you please send your app log & Binary log please?
