### ISSUE TITLE
What Happened: It wont let me transfer my DOGE to another wallet...

### ISSUE THREAD

**Issue by Cisco2794** [DeFiCh/app#800]
[app logs.zip](https://github.com/DeFiCh/app/files/6410559/app.logs.zip)

#### How to reproduce it (as minimally and precisely as possible):

The continue button is grayed out which is hindering the transfer of my DOGE...

#### What are your environment parameters?

- DeFi Wallet Version:
- Operating System (OS):

**Comment by izzycsy** [comment]
Hi @Cisco2794 , how you transferred DOGE to DeFi Wallet, would be the same way to transfer it back out. Tokens transferred to DeFi App are wrapped. You need to transfer DOGE back to how you initially transferred it. You can ask how-to enquiries on [DeFiChain Telegram (EN)](https://t.me/defiblockchain).
