### ISSUE TITLE
Snapshot file on amazonaws not available / access denied

### ISSUE THREAD

**Issue by nippur72** [DeFiCh/app#801]
since May 1 the snapshot file is not available, the app tells "0 GB" and if you try to get from normal HTTPS it gives an "access denied error"

Perhaps #799 was caused by this ?

![image](https://user-images.githubusercontent.com/2598443/116806331-800a4700-ab2c-11eb-9dca-6f07ebefd558.png)

**Comment by chrsch** [comment]
I have the same problem on Windows.

**Comment by nippur72** [comment]
it is now available, I guess it was fixed so I'm closing this issue
