### ISSUE TITLE
Snapshot 0GB

### ISSUE THREAD

**Issue by charlesh9999** [DeFiCh/app#802]
Yesterday it forced me to reinstall all of the block data, i tried to do from snapshot but it just said the snapshot was 0.0GB so it downloaded nothing instantly

Let it run all day to download them manually, got to 91% after about 12 hours then said 'lost connection to node' or something of the sorts and refused to download and will not even launch now

you guys have probably heard this already so sorry if so, thanks for all the work you guys do!

**Comment by izzycsy** [comment]
Hi @charlesh9999 , the team is aware of this issue. Kindly wait for the upcoming release, an updated snapshot will be ready. Thank you for your patience. Look our for [DeFiChain Announcements (EN)]((https://t.me/defichain_announcements) for the latest updates.

**Comment by izzycsy** [comment]
Hi @charlesh9999 , [v2.3.5](https://github.com/DeFiCh/app/releases/tag/v2.3.5) is out. Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.
