### ISSUE TITLE
Sync stuck at o% Defi Wallet 2.3.3

### ISSUE THREAD

**Issue by gabriello79** [DeFiCh/app#805]
Hello I was running with my Mac Defi wallet and after a crash of my laptop I got the corrupted blockchain message. I re installed last version, added the node through CLI: 
addnode "62.75.139.29:8555" add
that I had to add also the first time, but still the sync is blocked at 0%.
Mac Big sur 11.23
What to do??
[APP LOG.log](https://github.com/DeFiCh/app/files/6414887/APP.LOG.log)

**Comment by izzycsy** [comment]
Hi @gabriello79 , did your app screen open? Please keep your `wallet.dat` safe.

**Comment by gabriello79** [comment]
Ciao @izzycsy no errors, the app just open and stays as shown in the picture
![image](https://user-images.githubusercontent.com/78435161/116927822-75e76600-ac5c-11eb-83bc-fc317bf610e0.png)

**Comment by izzycsy** [comment]
Hi @gabriello79 , there's no error. You can wait for it to sync to 100%, ensure good internet connection & leave your Mac unlocked. 

<img width="244" alt="`i` to trigger Snapshot download" src="https://user-images.githubusercontent.com/65014479/116928313-7c430580-ac8f-11eb-91ff-c057e42f686f.png">

Alternatively, you can use the snapshot download (27GB), but do note that when the app syncs to 100%, it'll take up about 130GB space. The team is working on reducing the storage in the next update and as well as a light wallet. Thank you for your patience!

**Comment by izzycsy** [comment]
Hi @gabriello79 , [v2.3.5](https://github.com/DeFiCh/app/releases/tag/v2.3.5) is out. Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.
