### ISSUE TITLE
Defi Wallet 2.3.3 öffnet, aber bleibt hängen

### ISSUE THREAD

**Issue by Rocky-81** [DeFiCh/app#806]
At first I had problems with synchronization and storage space. Now it gets stuck right at the beginning after opening it. I tried reinstalling it but with no result.

Are there any other suggested solutions?

![defi](https://user-images.githubusercontent.com/83607318/116917203-a1fbea80-ac4e-11eb-8b8d-d2b18b4f37e9.jpg)

**Comment by izzycsy** [comment]
Hi @Rocky-81 , can you check your current storage? The app currently requires at least 130GB of space. The team is working on reducing the storage required and as well as a light wallet. Regarding the issue [`Win: App shows white screen + logo`](https://github.com/DeFiCh/app/issues/750), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.
