### ISSUE TITLE
App's 7z included in Linux's appimage

### ISSUE THREAD

**Issue by John-Gee** [DeFiCh/app#807]
#### What happened:
When I extract the appimage of 2.3.3 I see this folder in it:
squashfs-root/resources/app.asar.unpacked/node_modules/7zip-bin/mac

it contains Mac binaries for 7za. Is there a reason to include those in an appimage for Linux?

**Comment by thedoublejay** [comment]
@John-Gee we're using a node package. I think it packages all binaries for mac, windows and linux.

**Comment by John-Gee** [comment]
@thedoublejay I don't see Windows in there, only Mac and Linux, for the various archs supported, and only for 7z not for the app itself.

If you think this is as expected feel free to close this of course.

Thank you.
