### ISSUE TITLE
Can't move coins...

### ISSUE THREAD

**Issue by Kevinwhits** [DeFiCh/app#809]
When I try to add funds to a liquidity pool I get the error message that says...

“Insufficient funds”

![1 (2)](https://user-images.githubusercontent.com/83730725/117212141-d1c20400-adae-11eb-8908-2b1566ab7093.jpg)

I've tried adding a new wallet and transferring all my coins to it and I get the error message. 

“Got error in handleFallbackSendToken: Insufficient token in account”

![2 (2)](https://user-images.githubusercontent.com/83730725/117212191-e3a3a700-adae-11eb-8939-d0e961d567a6.jpg)

When I try to move 10 DFI coins from Defi Chain to Cake (I have 125 DFI in my Defi Wallet) I also get the error message... 

“Insufficient UTXO DFI for transaction fees. Please send some DFI from an exchange or another wallet and try again.”

![3](https://user-images.githubusercontent.com/83730725/117212221-edc5a580-adae-11eb-8043-0ed2eae4579b.jpg)

I started noticed these error messages when I moved the Defi Blockchain to another drive because it was getting too big. 

I followed these directions.....https://defichain-wiki.com/wiki/Blockchain_folder

I've tried to Re-Index my wallet, I used a snapshot and it didn't help. 

I plan on trying to re-index my wallet again just using the slow way. If that doesn't work I'm thinking of deleting everything DEFI (except my wallet) and starting again from nothing. 

Any "better" ideas I could try would be “very” appreciated.

Thanks in advance, 

Kevin. 

Defi Wallet Version 2.3.3
Windows 10

(PS. I have 10 versions of a backup wallet in 4 locations because I'm scared of losing my money.)

[App_Logs.zip](https://github.com/DeFiCh/app/files/6430317/App_Logs.zip)

**Comment by izzycsy** [comment]
Hi @Kevinwhits , regarding 

> When I try to add funds to a liquidity pool I get the error message that says... “Insufficient funds”

It’s likely that you've insufficient utxoDFI balance (min. 1 DFI) — which is required to perform swap and all other functions. DFI exist in 2 forms; `utxoDFI` and `accountDFI`. utxoDFI is used to pay for transactions fees while rewards received from liquidity mining (for example) are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. More details in this [thread](https://github.com/DeFiCh/app/issues/704). 

To convert accountDFI to utxoDFI, the simplest way would be via DeFi Wallet app.   Firsty, check via CLI:  `getbalance` — utxoDFI
`gettokenbalances` — accountDFI 
From your output 
```
gettokenbalances
[
  "3.123456768@0", — accountDFI
  "XXXXXXXXXX@2",
  "XXXXXXXXXX@5"
]
```

Send 1 accountDFI to yourself:
1. copy your address (the one that you're planning to use to add liquidity)
2. Click `send DFI`
3. Input 1 DFI
4. Paste the address 
5. Try the function again

By sending to yourself, you're converting your accountDFI to utxoDFI. utxoDFI is used for transaction fees.

**Comment by izzycsy** [comment]
Regarding 

> I started noticed these error messages when I moved the Defi Blockchain to another drive because it was getting too big...

If you were to [change directory](https://defichain-wiki.com/wiki/Blockchain_folder), it could be that the path set. Perhaps you can ask in [DeFiChain Telegram (EN)](https://t.me/defiblockchain) and the community members who are using Windows can help. 

If you still have issues pertaining to the previous comment, [`v2.3.3 Unable to add liquidity`](https://github.com/DeFiCh/app/issues/704), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.
