### ISSUE TITLE
Pending balance network error. Balance appear and disappear.

### ISSUE THREAD

**Issue by Faucet1313** [DeFiCh/app#810]
Hello, 

After logging into my server i saw the balance showing 0 and a network error. I can sometime refresh the balance and it show the correct amount but it disappear some minutes later then i had to refresh again. I guess the connection is stable as i am using a vultr instance. 

- DeFi Wallet Version: 2.3.3
- Operating System (OS): Windows server 2016

Attached logs and screenshot.

![Network error](https://user-images.githubusercontent.com/83678739/117295312-fb912e80-ae73-11eb-9f01-ec5879175139.png)

[log.log](https://github.com/DeFiCh/app/files/6434187/log.log)

Thanks in advance.

**Comment by izzycsy** [comment]
Hi @Faucet1313 , make a backup for your `wallet.dat` just in case. Not sure if it's due to the [minimum specification requirements](https://defichain.com/learn/defi-app-how-to/#minimum-requirements). Please give us time to investigate this issue.

**Comment by izzycsy** [comment]
Hi @Faucet1313 , checked with the team, it's either due to the vultr VPS or your system lost connection.

**Comment by Faucet1313** [comment]
Thanks for checking my issue. It is a dedicated server, If i lost connection and i can connect to my server why the Defichain client can't reconnect too?

**Comment by izzycsy** [comment]
Hi @Faucet1313 , I don't have a definite answer as it could be due to your location, the peers nearby for the app to sync. You're running the node (wallet) by yourself afterall. You could wait for the next app update and maybe the issue will be resolved.

**Comment by Faucet1313** [comment]
Same issue with 2 different hosting and locations each server respect the minimum specification requirements and both running Windows server 2016. This time in the new server i saw that when i got this error "Pending balance failure" i can't connect to internet with firefox or internet explorer except if i close the defichain client so i tried to disable firewall, defender... But no success. I found an event that match the time of the balance error and i found this: 
![TCP error](https://user-images.githubusercontent.com/83678739/118055804-163e3880-b389-11eb-81a4-437ff75f1f2a.png)

**Comment by izzycsy** [comment]
Hi @Faucet1313 , could you send your feedback to  [`Network ERROR at new wallet 2.3.4`](https://github.com/DeFiCh/app/issues/849), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.
