### ISSUE TITLE
Masternode: copy-button required for Hash

### ISSUE THREAD

**Issue by nippur72** [DeFiCh/app#811]
#### What would you like to be added:
in "Masternode details" page (`MasterNodeDetailPage.tsx`) the `Hash` value is displayed with ellipsis (`...`) making not possible to copy it to clipboard. (I guess this is because it exceeds the 50 characters of `<KeyValueLi>`).

#### Why is this needed:
to copy the actual hash value to clipboard.

**Comment by izzycsy** [comment]
Hi @nippur72 , thanks for the feedback, please give us time to fix this UI issue.

**Comment by izzycsy** [comment]
Hi @izzycsy [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a mandatory update. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @nippur72 , [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by thedoublejay** [comment]
@nippur72 this should be fixed on the next app release. Thanks!

**Comment by izzycsy** [comment]
Hi @nippur72 [v2.5.2](https://github.com/DeFiCh/app/releases/tag/v2.5.2) is out. Please read through the release notes before updating. This issue has been resolved, thank you.
