### ISSUE TITLE
Incorrect balance shown in DEFI app

### ISSUE THREAD

**Issue by Koktongkt** [DeFiCh/app#823]
Hi developers,

I have bought around 670 DFI,  If i look at the current price of DFI ~4.8973 USD at 9 May, 2:40pm PST, the total balance in USD should be in 670 * 4.8974 = ~3281 USD. However, the current balance in USD is only 2947 USD. Please advise on this, thanks!

**Comment by izzycsy** [comment]
Hi @Koktongkt , you likely have to contact that exchange for your enquiry, users can't purchase DFI on DeFi Wallet. Perhaps you can seek advice on [DeFiChain Telegram (EN)](https://t.me/defiblockchain). This is not a bug issue. Thank you.

**Comment by tame81** [comment]
@Koktongkt, @izzycsy: The app displays the wrong balance sometimes (still).

Maybe it's the same issue as in:
https://github.com/DeFiCh/app/issues/542

The case has been closed, the problem persists.

**Comment by izzycsy** [comment]
Hi @Koktongkt @tame81 [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a mandatory update. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Koktongkt @tame81 , [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Koktongkt @tame81 , [v2.4.5](https://github.com/DeFiCh/app/releases/tag/v2.4.5) is out, this is a **mandatory update**.  Please read through the release notes before updating.

**Comment by izzycsy** [comment]
Hi @Koktongkt , [v2.5.0](https://github.com/DeFiCh/app/releases/tag/v2.5.0) is out. Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
