### ISSUE TITLE
Feat | Export to CSV file: split amount@token into two different columns

### ISSUE THREAD

**Issue by nippur72** [DeFiCh/app#827]
The `Amount` column in the .csv file is like this:

`"-0.00000543@DFI"`

in order to make it usable in a spreadsheet it would be handy if it was split in two columns:

`"-0.00000543","DFI"`

Also, the pool liquidity rows need separated columns for the two coins of the poolpair:

from:
`"-74.85612065@DFI,156.61498295@USDT-DFI"`
to:
`"-74.85612065","DFI","156.61498295","USDT-DFI"`

**Comment by izzycsy** [comment]
Hi @nippur72 , thanks for your feedback, could you add it to [Feat| Optimization of CSV export](https://github.com/DeFiCh/app/issues/640) please? We would like to keep same issues in one thread. Thank you. 

In the future, you can publish your idea (not bug related issue) on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner some support from the community, and the team can decide whether to implement the feature in the future. Thank you!

**Comment by nippur72** [comment]
sorry I hadn't noticed there was a similar issue open
