### ISSUE TITLE
2.3.4 All pages become "Loading...."

### ISSUE THREAD

**Issue by rolandwellinger** [DeFiCh/app#832]
#### What happened:
Update to DFI Wallet APP 2.3.4
Click on Liquidity => Loading....forever
Click on Transaction => Loading....forever
Click on DEX => No Coins in Pulldown
.....

#### What you expected to happen:
Works as before

#### How to reproduce it (as minimally and precisely as possible):
Open Wallet, try to view pages...

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.4
- Operating System (OS): Windows 10

#### Anything else we need to know?:

Worked before. No Problems on Update.

**Comment by rolandwellinger** [comment]
I had to exit the wallet and wait a while. After it was closed i reopen it but then the blockchain was corrupted :(. I restored the blockchain from a backup before the update. Then the app openend again. And since then it works. No more "Loading...."

**Comment by rolandwellinger** [comment]
Ok. It freezes again. It does not work. The App freezes after a while and currupt the blockchain. Urgent, please fix that!

**Comment by rolandwellinger** [comment]
Tried again. No Luck. Blockchain Sync stops after 1-2 Minutes. Debug-Log no Progress. App Freezes.

**Comment by nippur72** [comment]
here is my log: [nippur72_log.log](https://github.com/DeFiCh/app/files/6457144/nippur72_log.log)

**Comment by thedoublejay** [comment]
@nippur72 Based on your logs, it seems that the app is still loading. You've tried to manually force close the app which might cause the corrupted blockchain issue when it's not closed properly. I suggest you wait a bit for the app to load properly. 

In terms of blockchain corrupted, you can use the snapshot to restore the blockchain around 99% so your syncing will be faster.

**Comment by izzycsy** [comment]
Hi @rolandwellinger , please save and .zip the logs and send them so we can investigate. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/117780233-05e76a00-b272-11eb-9b99-59b5db39999b.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/117780241-07189700-b272-11eb-8e8e-0cf9ce295735.png">

**Comment by rolandwellinger** [comment]
I really like DFI. But the whole Thing have to be improved very hard to get mainstream.

**Comment by izzycsy** [comment]
Hi @rolandwellinger , you should not try to kill the app just because it's taking some time to load, this will cause you to having to resync from the start again. Is your issue still persisting? 

Hi @nippur72 , have multiple snapshot backups in your PC, personally after I sync to 100% after snapshot I delete it so that I save some storage on my computer, plus the team will update the snapshot as we move along. 

<img width="1016" alt="Snapshot successful   Delete snapshot   restart app" src="https://user-images.githubusercontent.com/65014479/117789901-629b5280-b27b-11eb-806b-530414de3237.png">

So having old snapshots is just taking up storage and potentially making my app face unknown issues. Regarding the `Loading...` can you check again? If your app is synced to 100%, it should reflect correctly after a moment.

**Comment by nippur72** [comment]
@izzycsy I reinstalled 2.3.4 upgrading from 2.3.3 (full sync) and now it works normally, it's no longer stuck in "loading..." and the app closes without affecting the blockchain database.

**Comment by Stonygan** [comment]
I have the same behaviour yesterday with version 2.3.3. dont think that is a problem of the new release, maybe some external APIs are unabailable.

**Comment by izzycsy** [comment]
Hi @rolandwellinger @nippur72 , regarding the issue [Network ERROR at new wallet 2.3.4 #849](https://github.com/DeFiCh/app/issues/849), we can further discuss on the issue there. We would like to keep same issues in one thread. We will update the thread from there. Thank you.

**Comment by supervolot** [comment]
> @thedoublejay I've 3 PC's running it LOL. I also recommend to DELTA-Copy the Chain with ROBOCOPY on the same PC's.
> 
> My Strategy in Detail
> 
> * Install App
> * Run App
> * Build Up the whole Chain
> * Quit App
> * Make a Copy-Script for the whole DefiChain Folder with ROBOCOPY /PURGE with name DefiChainClone
> * Once the full Copy is made, restart App
> * If you have Corruption then
> * Quit App or even Kill IT
> * Run an oposite Script DefiChainClone to DefiChain with ROBOCOPY /PURGE => Takes only few seconds to revert the Delta :)
> * Open App again and sync the few Blocks remaining since last Backup
> * Refresh the Clone from Time to Time in a few Seconds with the Script (App must be closed)
> * ! ROBOCOPY /PURGE DOES ONLY COPY NEW AND CHANGED FILES AND DELETE NO MORE EXISTING FILES :)

Hallo Roland, kannst Du den Befehl für Robocopy kurz reinschreiben, ich bekomm hier immer eine Fehlermeldung bei Kopierversuch?
