### ISSUE TITLE
Mac: Unable to start blockchain

### ISSUE THREAD

**Issue by baludwi** [DeFiCh/app#833]
#### What happened:
App stuck while starting. I updated to the new Version 2.3.4. Then everything works normally. I closed the App now I restart the App and it stuck while starting

#### What you expected to happen:
App starting normal.

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.4
- Operating System (OS): Mac OS 11.3.1

#### Anything else we need to know?:
![App_start_stuck](https://user-images.githubusercontent.com/47607779/117705026-d1b96e00-b1cb-11eb-84d6-8a147a80a631.jpg)

**Comment by Fabialfonso** [comment]
Excatly the same issue here ....

**Comment by thedoublejay** [comment]
Hey @Fabialfonso, can you help us investigate the issue with your logs? Thank you!

**Comment by izzycsy** [comment]
Hi @baludwi @Fabialfonso , please save your logs after the error occurs and send them here so the team can investigate. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/117774081-b1d98700-b26b-11eb-9e3f-54c38f5f29fa.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/117774090-b43be100-b26b-11eb-9470-3931601d7db9.png">

**Comment by Fabialfonso** [comment]
Log files.zip

**Comment by Fabialfonso** [comment]
[Log files.zip](https://github.com/DeFiCh/app/files/6457299/Log.files.zip)

**Comment by adrian-schnell** [comment]
I'm having the same issue

[Log Files.zip](https://github.com/DeFiCh/app/files/6457522/Log.Files.zip)

**Comment by adrian-schnell** [comment]
I'm having the same issue.
After the update it was running. This issue occurred after the first after closing and reopening the app.

downgrading to 2.3.3 doesn't solve this problem

**Comment by Mabarkubus** [comment]
I'm still having the problem, that the app doesn't start, even the first time after the new installation.

**Comment by izzycsy** [comment]
Hi @Mabarkubus @angelocastiglione , thanks for your feedback, please give us time to investigate this issue.

**Comment by adrian-schnell** [comment]
> Hi @adrian-schnell , could you send your app logs please?

[Logs.zip](https://github.com/DeFiCh/app/files/6464732/Logs.zip)

**Comment by baludwi** [comment]
I solved this issue! I found this wiki entry: https://defichain-wiki.com/wiki/Unable_to_start_blockchain

I backuped and deleted the files "defi.conf" and  "defi.ui.yaml" in folder "/Users/<<myname>>/.defi/". 
Then I started DeFi Wallet App. It start to download snapshot and now it works fine. I can close the App and restart without problems

**Comment by izzycsy** [comment]
Hi @Fabialfonso @baludwi @adrian-schnell @angelocastiglione @Mabarkubus , [v2.3.5](https://github.com/DeFiCh/app/releases/tag/v2.3.5) is out. Please read through the release notes before updating. Make a backup of your wallet.dat before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.
