### ISSUE TITLE
Add a tooltip to the new buttons (Swap, Send, Receive)

### ISSUE THREAD

**Issue by Kolibri1990** [DeFiCh/app#837]
Hello together,

I think for new users it would be helpfull to have tooltips on the buttons.
They don't know what this could be before clicking them.

![image](https://user-images.githubusercontent.com/66674482/117842854-9c218d00-b27e-11eb-9413-3dd4bb2aff0c.png)

Swap , Send , Receive

Not difficult to implement but shows great effect.

**Comment by izzycsy** [comment]
Hi @Kolibri1990 , thanks for your feedback! You may publish your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner some support from the community, and the team can decide whether to implement the feature in the future. Thank you!

**Comment by Kolibri1990** [comment]
Hey @izzycsy , 
thanks for response. 
I did not know that the issues here in repo are only for bugs sorry. 
Will post my ideas and suggestions for improvement in the idea thread in the future!
