### ISSUE TITLE
Add DeFiChain Analytics link to the Help Page

### ISSUE THREAD

**Issue by Kolibri1990** [DeFiCh/app#838]
I think the correct page for the link from Daniel's defichain-analytics would be on the Help page. or at least additionally that would be top.

![image](https://user-images.githubusercontent.com/66674482/117849653-d0984780-b284-11eb-97c0-5e08981a72ef.png)

**Comment by izzycsy** [comment]
Hi @Kolibri1990 , DeFiChain Analytics is currently added to DEX screen. Posting non-bug related issues here will eventually turn stale. You can publish your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner some support from the community, and the team can decide whether to implement the feature in the future. Thank you!
