### ISSUE TITLE
Mac: Unable to open app

### ISSUE THREAD

**Issue by lescha1983** [DeFiCh/app#839]
[Ohne Titel.log 2.zip](https://github.com/DeFiCh/app/files/6460616/Ohne.Titel.log.2.zip)

#### What are your environment parameters?

- DeFi Wallet Version:
- Operating System (OS): (Mac 11.2.3 (20D91))

#### Anything else we need to know?:

[](url)

**Comment by izzycsy** [comment]
Hi @lescha1983 , thanks for your feedback, the team is aware and are currently investigating.

**Comment by izzycsy** [comment]
Hi @lescha1983 , [v2.3.5](https://github.com/DeFiCh/app/releases/tag/v2.3.5) is out. Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.
