### ISSUE TITLE
Error in the display of yields: APY instead of APR

### ISSUE THREAD

**Issue by Kolibri1990** [DeFiCh/app#840]
#### What happened:

In the new wallet the display of the returns is still wrong. The returns are APR and **not** APY. 

#### What you expected to happen:

You only have to change APY in APR... thats all.

#### How to reproduce it (as minimally and precisely as possible):

Open the wallet.

#### What are your environment parameters?

- DeFi Wallet Version: All versions
- Operating System (OS): All OS

**Comment by izzycsy** [comment]
Hi @Kolibri1990 , thanks for your feedback, the team is aware and are currently investigating.

**Comment by diegorodriguezv** [comment]
I noticed the web site (https://defichain.com/dex/) shows the rate as APR but the App and the screenshots show APY.
I don't know which is correct. Could someone explain why one or the other? 
I have looked around but I can't find which is the number of periods for the calculation. Is it monthly? Daily? Each 12 hours? (https://app.cakedefi.com/ says Rewards every 12 hours)

**Comment by Kolibri1990** [comment]
Hey @diegorodriguezv 

As with cake, the return on LM on the DeFi Wallet is an APR and not an APY.

It is wrong on the DEX page (https://dex.defichain.com/mainnet/pool) and also the DeFi Wallet.

The values are right but the naming is wrong.

**Comment by izzycsy** [comment]
Hi @diegorodriguezv you can ask the community [DeFiChain Telegram (EN)](https://t.me/defiblockchain) on such enquiries. 

Thanks @Kolibri1990 !

**Comment by izzycsy** [comment]
Hi @Kolibri1990 @diegorodriguezv @wmbst @adrian-schnell [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a mandatory update. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by sandrich** [comment]
When is this going to happen? APY is wrong and misleading.

**Comment by nick-preda** [comment]
so to be clear, app should be also showing APR, as the website already shows correctly that is APR

**Comment by izzycsy** [comment]
Hi @sandrich , the team is working on it, kindly refer to [DeFiChain Announcements (EN)](https://t.me/defichain_announcements) for the latest updates. Thank you.

**Comment by thedoublejay** [comment]
Hi, we have updated this on the latest app release v2.4.2, please have a look. thank you - https://defichain.com/downloads/
