### ISSUE TITLE
Unable to send BTC from defiChain desktop App

### ISSUE THREAD

**Issue by atorrez777** [DeFiCh/app#843]
The button is grayed out I followed all the different posts suggested on this site, changing token to coin, I even swapped btc to defi and still cannot get my bitCoin out. This issue seems to have been going on for a long time, is there an easy fix? I spend literally 6 hours today. Can you please help me move my bitCoin back to cakeDefi?

![image](https://user-images.githubusercontent.com/84059519/117918116-4b6e5c00-b29f-11eb-9104-6de4d5b64ab5.png)

**Comment by izzycsy** [comment]
Hi @atorrez777 , the address you’re using is likely not a DeFiChain-friendly address. You can retrieve the DeFiChain address via <cakedefi.com>, try sending a small amount first to test.

1. Click on Balances in <cakedefi.com>
2. In the BTC row, click on Deposit button
3. You'll see the Transfer Network options `BTC` / `DeFiChain`

<img width="375" alt="Click DeFiChain   BTC" src="https://user-images.githubusercontent.com/65014479/117921152-cc226c00-b322-11eb-939e-d01067d4ca71.png">

4. Under the QR Code states your DeFiChain address, copy it
5. Go back to DeFi Wallet > dBTC wallet > Send
6. Paste your DeFiChain address into DeFi Wallet `To address` field

**Comment by atorrez777** [comment]
Bella,

 

I followed the instructions you sent me and I still get the same ‘the continue button’ is grayed out.

**Comment by atorrez777** [comment]
I followed the directions you mentioned about and the 'Continue' button was not grayed out anymore and it let me continue but then I got this error "Got error in handleFallBackSendToken: Got error in accountToAccount - handleFallbackSendTonken: Insufficient funnds (see screenshot)
![image](https://user-images.githubusercontent.com/84059519/118218498-61f5ee00-b42c-11eb-93e1-f9296bef62b7.png)

**Comment by atorrez777** [comment]
Can someone please help me with this? I'm still not able to withdraw my bitcoin.

**Comment by izzycsy** [comment]
Hi @atorrez777 , thanks for your screenshot, kindly wait for the synchronisation to reach 100% and try again.

**Comment by atorrez777** [comment]
It finished synchronisation and I'm getting the same result, I feel like I made a mistake choosing this as my wallet, I didn't know if would be this complicated, can you please help me. I included a new screenshot

![image](https://user-images.githubusercontent.com/84059519/119084105-0db3b680-b9b6-11eb-9e30-7ae5722a0498.png)

**Comment by izzycsy** [comment]
Hi @atorrez777 , what you're experiencing is part of decentralisation and it's normal, you can actually seek help from the community via [DeFiChain Telegram (EN)](https://t.me/defiblockchain). 

It’s likely that you've insufficient utxoDFI balance (min. 1 DFI) — which is required to perform swap and all other functions. DFI exist in 2 forms; `utxoDFI` and `tokenDFI`. utxoDFI is used to pay for transactions fees while rewards received from liquidity mining (for example) are in tokenDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. To convert tokenDFI to utxoDFI, the simplest way would be via DeFi Wallet app.   

Firstly, check via CLI: 
`getbalance` — utxoDFI
`gettokenbalances` — tokenDFI 

or the app UI should indicate to you:

<img width="987" alt="utxoDFI   tokenDFI" src="https://user-images.githubusercontent.com/65014479/119116592-f5e23e00-ba5a-11eb-9c55-22d3e87e4d6b.png">


From your output in the CLI: 

```
gettokenbalances
[
  "3.123456768@0", — tokenDFI
  "XXXXXXXXXX@2",
  "XXXXXXXXXX@5"
]
```

Send 1 tokenDFI to yourself:
1. Copy your address (the receive address that you're planning to send you dBTC out to your `xxxQMc7xxx`)
2. Click `send DFI`
3. Input 1 DFI
4. Paste the address 
5. Try sending dBTC again

By sending to yourself (step 1 – 4), you're converting your tokenDFI to utxoDFI. utxoDFI is used for transaction fees.

**Comment by izzycsy** [comment]
Hi @atorrez777 , [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a mandatory update. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by atorrez777** [comment]
Bella,

 

Please help me move my bitcoin out, how much utxo do I need to send out 0.02044881 of my BTC? (see screenshots)

**Comment by izzycsy** [comment]
Hi @atorrez777 , on the blockchain the amount you transfer does not matter, there's no % fee on DeFi Wallet. It's definitely less than 1 DFI. At the moment to unwrap your dBTC, you'll have to transfer to Cakedefi > to your desired exchange.

**Comment by atorrez777** [comment]
Bella,

 

I’m trying to transfer my dBTC to my cakedefi wallet address like you suggested on DeFiChain address (Screenshot#1) and I still get the error insufficient funds message? (Screenshot#2)  I have enough utxo, defi, and Token (screenshot#3). Why do I still get the error?

 

 

 

Screenshot#1:



 

 

 

 

Screenshot#2:



 

 

 

 

Screenshot#3:

**Comment by izzycsy** [comment]
Hi @atorrez777 , can you resend your comment. The screenshots attached are blank.

**Comment by atorrez777** [comment]
Bella,

 

I’m trying to transfer my dBTC to my cakedefi wallet address like you suggested on DeFiChain address (Screenshot#1) and I still get the error insufficient funds message? (Screenshot#2)  I have enough utxo, defi, and Token (screenshot#3). Why do I still get the error?

 

NOTE: I’ve included the screenshots as attachments, let me know if you see them now.

**Comment by izzycsy** [comment]
Hi @atorrez777 , this is what I see from your comment above: 

![Screenshot 2021-06-02 at 4 09 15 AM](https://user-images.githubusercontent.com/65014479/120384134-5a08da00-c358-11eb-8f1c-0aa62c8fbe43.png)

Can you drag and drop your screenshots again please? Providing an example for you below. Thank you

<img width="671" alt="3 Drag and drop" src="https://user-images.githubusercontent.com/65014479/120384193-6ab95000-c358-11eb-83eb-6bf18e87e356.png">

**Comment by atorrez777** [comment]
Bella, I'm dropping the screenshots here, let me know if you get them.
![Screenshot_1](https://user-images.githubusercontent.com/84059519/120385981-e8d81100-c2dc-11eb-8424-82cd976bfda8.png)
![Screenshot_2](https://user-images.githubusercontent.com/84059519/120385990-ebd30180-c2dc-11eb-92b7-cca035ffd685.png)
![Screenshot_3](https://user-images.githubusercontent.com/84059519/120386004-ee355b80-c2dc-11eb-9345-95a08dd62d98.png)

**Comment by izzycsy** [comment]
Hi @atorrez777 , [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**. Please read through the release notes before updating.

Can you try sending a smaller dBTC amount?

**Comment by atorrez777** [comment]
Bella,The lowest dBTC amount it lets me enter before it lets me continue is 0.00000547Unfortunately I get the exact same message, like I don't have any utxo but I have more than 4 utxo.
-------- Original message --------From: Bella ***@***.***> Date: 6/2/21  5:48 AM  (GMT-08:00) To: DeFiCh/app ***@***.***> Cc: atorrez777 ***@***.***>, Mention ***@***.***> Subject: Re: [DeFiCh/app] Unable to send BTC from defiChain desktop App (#843) 
Hi @atorrez777 , v2.4.2 is out, this is a mandatory update. Please read through the release notes before updating.
Can you try sending a smaller dBTC amount?

**Comment by izzycsy** [comment]
Hi @atorrez777 , do you have multiple addresses? If so, 

1. Choose 1 main address, `copy` it
2. Send DFI
3. Input 1 DFI (try with small amount first)
4. Paste your address (from step 1)
5. Send

See if you can send dBTC after that.

**Comment by atorrez777** [comment]
Bella,
I tried sending 1 defi and I still get insufficient fund error
![08](https://user-images.githubusercontent.com/84059519/120877537-e212fd80-c56b-11eb-8889-b18334219b31.PNG)

**Comment by atorrez777** [comment]
I chose to send only 1 defi and I still get this Insufficient funds error even though I have enough defi, utxo, token (see screenshot)
![Screenshot_3](https://user-images.githubusercontent.com/84059519/120877609-52ba1a00-c56c-11eb-8263-833aad0dfffb.png)

**Comment by atorrez777** [comment]
Bella,
I also tried sending 0.5 defi and I still get the insufficient error message.

![09](https://user-images.githubusercontent.com/84059519/120877715-ea1f6d00-c56c-11eb-86ee-51a3ea8a3c3d.png)
![Screenshot_2](https://user-images.githubusercontent.com/84059519/120877719-ef7cb780-c56c-11eb-8e39-523ad3916b6b.png)

**Comment by izzycsy** [comment]
Hi @atorrez777 , what version are you on? Can you try updating to the latest [v2.4.5](https://github.com/DeFiCh/app/releases/tag/v2.4.5) then try again. Also, do you have multiple addresses? You can check via CLI:
listaccounts {} false false true — breakdown of your token(s)

**Comment by atorrez777** [comment]
Bella,
After upgrading to version 'v2.4.5' I was able to send my dBTC to cakedefi with no problem. Thank you for your help!
