### ISSUE TITLE
2.3.5 - Stop Synching (Socket Errors)

### ISSUE THREAD

**Issue by rolandwellinger** [DeFiCh/app#855]
#### Actual behavior:
Upgrading to 2.3.5
Start the App
Wait a few hours
App stopping Sync with Blockchain
=> SOCKET ERROR
=> Get unsresponsive
=> Close
=> Corrupt Blockchain

#### Expected behavior:
Works flawlessly

#### How to reproduce it (as minimally and precisely as possible):
Install and let it run, maybe on a System with not such huge CPU Power

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.4
- Operating System (OS): Windows 10
– Current free storage capacity: 100GB

#### Anything else we need to know?
I've downgraded to 2.3.3
Please take SURE that 2.3.3 will work until 2.3.5 is fixed! THANKS

**Comment by supervolot** [comment]
> #### Actual behavior:
> Upgrading to 2.3.5
> Start the App
> Wait a few hours
> App stopping Sync with Blockchain
> => SOCKET ERROR
> => Get unsresponsive
> => Close
> => Corrupt Blockchain
> 
> #### Expected behavior:
> Works flawlessly
> 
> #### How to reproduce it (as minimally and precisely as possible):
> Install and let it run, maybe on a System with not such huge CPU Power
> 
> #### What are your environment parameters?
> * DeFi Wallet Version: 2.3.4
> * Operating System (OS): Windows 10
>   – Current free storage capacity: 100GB
> 
> #### Anything else we need to know?
> I've downgraded to 2.3.3
> Please take SURE that 2.3.3 will work until 2.3.5 is fixed! THANKS

Hi Roland, Du kannst den Bug mit der "Corrupt Blockchain" beheben indem Du vor schließen der Wallet in der Konsole mit "stop" die node beendest und erst danach die Wallet schließt. So mache ich es jetzt immer. 
[main.log](https://github.com/DeFiCh/app/files/6478744/main.log)

**Comment by rolandwellinger** [comment]
@supervolot 
Danke für den Tip. Aber das löst nicht das Problem wenn mal der Strom ausfällt. Dafür ist der tägliche Deltabackup der eigenen Chain genial. Geht sehr schnell...

**Comment by rolandwellinger** [comment]
@supervolot Habe ich hier in dem Issue beschrieben https://github.com/DeFiCh/app/issues/832

**Comment by cosecit** [comment]
Same issue
Version 2.3.3 works well
Version 2.3.4 & 2.3.5 have the syncing issue. The sync stops on different Block, then the App can not be closed, then an resync is required.

**Comment by 1987FL** [comment]
Dear @supervolot
I am facing the same issue as well.
With my new laptop and after downloading 2.3.5 it doesn`t start sync 0.00%. I tried your recommandotion : "vor schließen der Wallet in der Konsole mit "stop" die node beendest und erst danach die Wallet schließt", but it doesn`t work. Also I tried to in the setting "Reset & Reindex".

Would be great to get some support :-)

Best regards.

**Comment by supervolot** [comment]
> Dear @supervolot
> I am facing the same issue as well.
> With my new laptop and after downloading 2.3.5 it doesn`t start sync 0.00%. I tried your recommandotion : "vor schließen der Wallet in der Konsole mit "stop" die node beendest und erst danach die Wallet schließt", but it doesn`t work. Also I tried to in the setting "Reset & Reindex".
> 
> Would be great to get some support :-)
> 
> Best regards.

Hi @1987FL you should load the snapshot first (you will find the turorial here  https://defichain-wiki.com/wiki/Fullnode ) then the wallet wil work.

**Comment by 1987FL** [comment]
Dear @supervolot,
Thanks for your reply and help. I followed your instructions as they are written in DeFiWiki, but I couldn't solve my issue. Snyc stops at 97,69%.
The point here is, I have only my seed (24 words) and the simple backup file *.dat which I created during running version 2.3.0. Now I have a complete new laptop and try to recover my seed.

I would be extremely grateful if you can help me

**Comment by izzycsy** [comment]
Hi @1987FL , synchronisation for the last new blocks will take time — took me an hour. You can try to add node. In [DeFiChain-Wiki](https://defichain-wiki.com/wiki/Addnode) the article guides you on how to do this, or simply try via the CLI:
`addnode "seed.mydeficha.in:8555" add`

**Comment by izzycsy** [comment]
Hi @rolandwellinger @supervolot @cosecit @1987FL , update [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
