### ISSUE TITLE
XRP

### ISSUE THREAD

**Issue by ChingN** [DeFiCh/app#856]
Can DeFi Wallet Version 2.3.3 store XRP?

**Comment by rolandwellinger** [comment]
No it can't

**Comment by izzycsy** [comment]
Hi @ChingN , posting non-bug related issues here will eventually turn stale. You can publish your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner some support from the community, and the team can decide whether to implement the feature in the future. Thank you!
