### ISSUE TITLE
ERROR: ConnectBlock()

### ISSUE THREAD

**Issue by skorilo** [DeFiCh/app#858]
#### Actual behavior:
reindex
#### How to reproduce it (as minimally and precisely as possible):

[err04.txt.zip](https://github.com/DeFiCh/app/files/6489489/err04.txt.zip), "network error!" and I have to restart it with reindex

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.5
- Operating System (OS): macOS Mojave
– Current free storage capacity: 159 GB

#### Anything else we need to know?
this was fourth time

**Comment by izzycsy** [comment]
Hi @skorilo , do you have screenshot of the error? Was your app synced to 100%?

**Comment by skorilo** [comment]
Hi @Bella,

I didn't have it, the node is 100% synchronized, it's a red exclamation point with a network error message and I don't think it communicates with other nodes. Somehow the connection is cut ... and until it restarts I lose a few blocks. 
I still have a logs if it helps. This is an example with the DeFi 2.3.4 version. Here always appears the message "socket recv error Connection reset by peer (54)" message that I can not assign to any connection, and it is curious that when I run only "defid" these messages are very rare.

Best regards

**Comment by izzycsy** [comment]
Hi @skorilo , regarding the issue [`Network ERROR at new wallet 2.3.4 #849`](https://github.com/DeFiCh/app/issues/849), we can further discuss on the issue there. We would like to keep same issues in one thread. You could send your logs there, there's also a current workaround that may resolve your issue, if it doesn't it would mean you're facing another type of `network error`, which requires further investigation. Thank you.
