### ISSUE TITLE
Update to Defi2.3.5 Unable to Start Blockchain

### ISSUE THREAD

**Issue by luzettemok1** [DeFiCh/app#860]
#### What are your environment parameters?

- DeFi Wallet Version: 2.3.5
- Operating System (OS): macOS Big Sur version 11.2.3
– Current free storage capacity: 44.9

#### Anything else we need to know?

[logs.zip](https://github.com/DeFiCh/app/files/6490990/logs.zip)

**Comment by izzycsy** [comment]
Hi @luzettemok1 , currently the app requires at least 120 GB storage, and if you're using the snapshot to speed up the sync to the latest block, it require 40.5GB.

<img width="1017" alt="Snapshot (Europe)" src="https://user-images.githubusercontent.com/65014479/118489603-9aa90680-b74f-11eb-8dab-a267cfe001a0.png">

DeFi Wallet should prompt you about the option to delete snapshot after snapshot has been successful. 

<img width="1017" alt="v2 3 5 Snapshot successful 842677" src="https://user-images.githubusercontent.com/65014479/118489685-b57b7b00-b74f-11eb-9ec4-392d87ffcf90.png">

It's likely that you've insufficient storage, hence the `Unable to start blockchain` error. You could either try to make more space for the app or wait for the Light Wallet to be released. Please backup your wallet.dat in the mean time. 

Mac: Go to folder
`/Users/<username>/Library/Application Support/Defi/wallets`

<img width="439" alt="Defi folder route" src="https://user-images.githubusercontent.com/65014479/118490085-2327a700-b750-11eb-828d-087137eecf1d.png">

<img width="822" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/118490019-14d98b00-b750-11eb-844f-2f34a378c05f.png">

Regarding the issue [`Unable to sync to 100% #853`](https://github.com/DeFiCh/app/issues/853), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.

**Comment by luzettemok1** [comment]
Thanks so much! Is there a set date for which the Light Wallet is going to be launched for my reference to download?
