### ISSUE TITLE
ReImport/reindex data Issues (Linux)

### ISSUE THREAD

**Issue by Tobeworks** [DeFiCh/app#861]
#### Actual behavior:
After importing a snapshot, the data folders (enhancedcs, blocks, chainstate) are not in the right directory (.defi). Found them in the home directory of the current user and had to move them into the ./.defi directory. App doesn`t auto reopen.
After moving data and open the app manually everything works as expected.

#### Expected behavior:
After importing a snapshot the app asks for closing and should re-open with the imported data. App should start indexing.

#### How to reproduce it (as minimally and precisely as possible):
Reindex by using a snapshot under Ubuntu (or Debian).

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.5
- Operating System (OS): Ubuntu 20.04.2 LTS
– Current free storage capacity: ca. 800GB

**Comment by izzycsy** [comment]
Hi @Tobeworks , currently snapshot is automatic process within the app and you need not have to manually import it to your data folders. 

<img width="1017" alt="v2 3 5 Snapshot successful 842677" src="https://user-images.githubusercontent.com/65014479/118618387-25dcd780-b7f6-11eb-9ea9-07588b124b59.png">

Upon successful installation of the snapshot, the app would prompt you to delete it so as to save some storage. 

<img width="1017" alt="Snapshot (Europe)" src="https://user-images.githubusercontent.com/65014479/118618378-22495080-b7f6-11eb-8d1f-e7a4ecdb5383.png">

Thanks for your feedback. For future Linux related post (if it's not a suspected bug) you can post your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), share your findings with the community. In the mean time, I'll provide a link to [Linux: Running the app as a webapp (e.g. from a Raspberry Pi) #736](https://github.com/DeFiCh/app/discussions/736) , there are other community members in discussion on an idea that might interest you.
