### ISSUE TITLE
USD / EUR prices would be awesome to have them somewhere

### ISSUE THREAD

**Issue by frankred** [DeFiCh/app#862]
#### Which feature is your request related to?
It would be nice to have EUR/USD convertion prices of each crypto wallet (prices that come from dex (USDT convertion rates). 
And also a total sum over all cryptos.

![image](https://user-images.githubusercontent.com/1528623/118542245-0b9ded80-b753-11eb-9272-d4c61da4bbf0.png)

**Comment by izzycsy** [comment]
HI @frankred , posting non-bug related issues here will eventually turn stale. You can publish your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner some support from the community, and the team can decide whether to implement the feature in the future. Thank you!
