### ISSUE TITLE
Frequently corrupt database detected. I feel like I can reinstall the snapshot every day.

### ISSUE THREAD

**Issue by SKapi1985** [DeFiCh/app#864]
#### What are your environment parameters?

- DeFi Wallet Version: 2.3.5
- Operating System (OS): Windows 10
– Current free storage capacity: 737 GB

#### Anything else we need to know?

[DefiWallet.zip](https://github.com/DeFiCh/app/files/6500354/DefiWallet.zip)

**Comment by izzycsy** [comment]
Hi @SKapi1985 , thanks for your feedback and logs, it seems like you've insufficient disk space. Check your C: drive or the drive where you store DeFi Wallet. Currently the app requires 120GB of storage excluding temporary storage should you apply snapshot (40.51GB). Kindly clear storage and try again or wait for the Light Wallet. Please keep your wallet.dat safe.  Should you need to switch directory for the DeFi Wallet, this source might help: https://defichain-wiki.com/wiki/Blockchain_folder  Alternatively, you can wait for Light Wallet.

**Comment by SKapi1985** [comment]
Hi @izzycsy, do you have seen my storage? -> 737 GB free capacity!

**Comment by SKapi1985** [comment]
And Again! The Synchronisation was 100% succesfully. After adding liquidity to a pool, which was successful, the app stalled again. The individual tabs did not work correctly (data was not loaded under Dex, liquidity and credit) and when the app was restarted, the database was reported as corrupt again :-( 

And I can start from scratch...

**Comment by Faucet1313** [comment]
I also have this issue everyday. If i close the defi wallet correctly most of the time when i open it again the blockchain is corrupted and i have to apply the snapshot.

DeFi Wallet Version: 2.3.5
Windows server 2019

**Comment by izzycsy** [comment]
Hi @SKapi1985 , yes I've seen the storage you've stated. I'd like to confirm that your app & files are currently on the same drive with 737 GB free capacity? As for Windows the drives are partition into various drives (C: D: E: etc). After investigating your logs, it seems that your app is having problems linking to your `wallet.dat` which are in various drives — C:, D: and E:. Try to have all files in the same drive. You seem to face [Network Error](https://github.com/DeFiCh/app/issues/849) — as some other users are experiencing as well, the team is currently investigating the Network Error issue, and you can see the discussion more in the thread. 

Hi @Faucet1313 , as I understand your issues is with regards to the [Network Error](https://github.com/DeFiCh/app/issues/849) , we can further discuss on the issue there as would like to keep same issues in one thread. Thank you.

**Comment by Faucet1313** [comment]
Hi @izzycsy, No it is a different issue. Most of the time when i close the wallet even very carefully (Checking active process etc..) even without this network error i have to apply the snapshot again almost everyday. I did not write about the corrupted blockchain in issue [#849](https://github.com/DeFiCh/app/issues/849) because it is not related to the network error.

**Comment by SKapi1985** [comment]
Hello @izzycsy, yes I had to manually set up drive D: according to your explanation for the snapshot, because the app automatically installs itself on C: without asking beforehand. But my drive C: is an SSD drive and therefore quite small in terms of storage space. A previous query during the installation would be desirable. Likewise, the specification of the required storage space.

**Comment by supervolot** [comment]
I have the same problem, every 1-2 days node stop and freeze, after restart a corrupt database :-( this bug is ver frustrating

**Comment by Faucet1313** [comment]
@supervolot yes so frustrating... Happened even without the node disconnected or network error. I will maybe move to linux.

**Comment by izzycsy** [comment]
Hi @Faucet1313 @SKapi1985 , the team is in the midst of testing the next update, I'll update you guys when it's ready, it should resolve your issues. You may refer to [DeFiChain Announcements (EN)](https://t.me/defichain_announcements) as well. Thank you.

**Comment by endeffects** [comment]
I have the same problem, still if i close the app gracefully. Please stop writing invalid / unfinished blocks to the chain file or improve the recovery by removing the last blocks instead of redownloading the whole chain again.

**Comment by izzycsy** [comment]
Hi @SKapi1985 @Faucet1313 @supervolot @endeffects , [v2.4.0]https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out. Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
