### ISSUE TITLE
Synchronization stops at block 842677 after applying the snapshot from Wednesday, May 12, 2021 7:59 AM

### ISSUE THREAD

**Issue by SKapi1985** [DeFiCh/app#866]
#### What are your environment parameters?

- DeFi Wallet Version: 2.3.5
- Operating System (OS): Win 10
– Current free storage capacity: 643 GB
[Logs.zip](https://github.com/DeFiCh/app/files/6507101/Logs.zip)

**Comment by pplin810** [comment]
Hi,  sorry, i am new to the community.  I have exactly the same issue.  Synchronizion stops at block842677 after applying the snapshot.  DeFi Wallet Version: 2.3.5
Operating System (OS): Win 10
– Current free storage capacity: 7GB
[app logs.zip.zip](https://github.com/DeFiCh/app/files/6507362/app.logs.zip.zip)

**Comment by izzycsy** [comment]
Hi @SKapi1985 , you can try to add some nodes. In the [DeFiChain-Wiki](https://defichain-wiki.com/wiki/Addnode) there is an article how to do this. or simply try via the CLI:
`addnode seed.mydeficha.in:8555 add` 

Hi @pplin810 , you've insufficient storage. Currently the app requires 120GB of storage excluding temporary storage should you apply snapshot (40.51GB). Kindly clear storage and try again or wait for the Light Wallet. Please keep your `wallet.dat` safe.

Regarding the issue [`Unable to sync to 100%`](https://github.com/DeFiCh/app/issues/853), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.

**Comment by SKapi1985** [comment]
> 
> 
> Hi @SKapi1985 , you can try to add some nodes. In the [DeFiChain-Wiki](https://defichain-wiki.com/wiki/Addnode) there is an article how to do this. or simply try via the CLI:
> `addnode seed.mydeficha.in:8555 add`
> 
> Hi @pplin810 , you've insufficient storage. Currently the app requires 120GB of storage excluding temporary storage should you apply snapshot (40.51GB). Kindly clear storage and try again or wait for the Light Wallet. Please keep your `wallet.dat` safe.
> 
> Regarding the issue [`Unable to sync to 100%`](https://github.com/DeFiCh/app/issues/853), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.

Thank you @izzycsy. Now the synchronisation is going on :-)

**Comment by blackstormtrader** [comment]
Hi @SKapi1985 , you can try to add some nodes. In the [DeFiChain-Wiki](https://defichain-wiki.com/wiki/Addnode) there is an article how to do this. or simply try via the CLI:
"addnode seed.mydeficha.in:8555 add"


This worked for me, so far its syncing from 0% - 60% in 30 min. just got a lil left to go. I also didnt do the snapshot from the app interface, instead thru manual dl and extraction available by instruction at the bottom of this page https://defichain-wiki.com/wiki/Fullnode#Blockchain_Snapshot_Service
