### ISSUE TITLE
Synch does not start

### ISSUE THREAD

**Issue by waywardone1** [DeFiCh/app#867]
<!--
I installed the defi wallet app, everything ok.
But the synchronisation does not start.
I enabled the firewall already, but it will not start.
0.00 % and it will not go forward...

What yould be the problem ? 

Thanks for the help.

**Comment by blackstormtrader** [comment]
try adding addnode seed.mydeficha.in:8555 add to the command line and make sure you have 250gb or more free ssd space. Also, the snapshot helps I think that its a faster dl, you can do it manually directions here https://defichain-wiki.com/wiki/Fullnode#Blockchain_Snapshot_Service, scroll all the way down, or can do in the app, mines syncing just had to let it do its thing. I did hte snapshot before adding the command to the CL

**Comment by yungmann** [comment]
Guys i found it, you just have to open the CLI, and manually add nodes for the blockchain to sync to them 
just run these commands:

addnode 45.157.177.82:8555 add
addnode 24.134.79.25:8555 add
addnode 77.56.65.5:855 add
addnode 85.214.55.116:855 add

do not worry about the answer "null", if you type them twice it should answer "node already added"

then type   getconnectioncount   to see to how many nodes you are connected

here is a list of some public nodes you can connect to 
http://cmk.mydeficha.in/mydefichain/check_mk/dashboard.py?name=dfi_fullnodes_public

**Comment by waywardone1** [comment]
> try adding addnode seed.mydeficha.in:8555 add to the command line and make sure you have 250gb or more free ssd space. Also, the snapshot helps I think that its a faster dl, you can do it manually directions here https://defichain-wiki.com/wiki/Fullnode#Blockchain_Snapshot_Service, scroll all the way down, or can do in the app, mines syncing just had to let it do its thing. I did hte snapshot before adding the command to the CL

Thank you, i will try later.
But does someone know, why this problem appears ? 

Before i installed Windows new, i had no problems... ( 17.05.21)

**Comment by Ausafari** [comment]
Having the same problem for the past two days. The snapshot was downloading at one point, but froze at 47%. Now it won't even start. Tried the previous version of the app, tried the command line solution above - nada.

**Comment by izzycsy** [comment]
Hi @blackstormtrader @yungmann thank you, if you don't mind we would like to keep the same issues in one thread, kindly copy and paste your feedback to the issue below.

@Ausafari @waywardone1 , regarding the issue [`Unable to sync to 100%`](https://github.com/DeFiCh/app/issues/853), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.
