### ISSUE TITLE
Defi Wallet - Blockchain not syncing 

### ISSUE THREAD

**Issue by yungmann** [DeFiCh/app#868]
Hello 

I have tried to install the Defi Wallet on 2 different computers (respectively Mac and Windows) and none of them has been able to sync the blockchain.
Needless to say i tried to intall a previous versions (2.3.3), same problem.

In the debug Logs it appears that the app can not find any peer to connect to.

I did another install on a server running Debian, it went smoothly in under 10 minutes.

I want to run a masternode on the server but keep my wallet on an offline computer, therefore i'd really like to be able to install the Defi Wallet app somewhere 

Any clue ?

Thanks a lot 
Best 

EDIT !!!!!!!

Guys i found it, you just have to open the CLI, and manually add nodes for the blockchain to sync to them
just run these commands:

addnode 45.157.177.82:8555 add
addnode 24.134.79.25:8555 add
addnode 77.56.65.5:855 add
addnode 85.214.55.116:855 add

do not worry about the answer "null", if you type them twice it should answer "node already added"

then type getconnectioncount to see to how many nodes you are connected

here is a list of some public nodes you can connect to
http://cmk.mydeficha.in/mydefichain/check_mk/dashboard.py?name=dfi_fullnodes_public

**Comment by yungmann** [comment]
And here are the logs :)

Thanks !
[logs.zip](https://github.com/DeFiCh/app/files/6511808/logs.zip)

**Comment by jas32096** [comment]
Thanks for your edit @yungmann. Adding the nodes manually seems to be working

**FYI**: Here's the normal link to the nodes: http://status.defichain-masternode.com/

**Comment by izzycsy** [comment]
Hi @yungmann , thanks for your edit, regarding the issue [`Unable to sync to 100%`](https://github.com/DeFiCh/app/issues/853), we can further discuss on the issue there. We would like to keep same issues in one thread. Kindly paste your feedback in the link provided. Thank you.
