### ISSUE TITLE
Syncing issue with 2.3.5 defi chain app

### ISSUE THREAD

**Issue by blackstormtrader** [DeFiCh/app#869]
Actual behavior: 
defi chain app is not functioning correctly. the sync is will not complete once I can get it to start. the pc will freeze entirely, forcing me to use another drive with another os, or the sync itself will simply freeze and Ill get a corruption notification regarding the sync. this last attempt left my nvme drive frozen disallowing me to boot into the os. 

Expected behavior: 
the sync is supposed to complete once started allowing me to access the wallet app. 

How to reproduce it (as minimally and precisely as possible): 
Im just installing the app on a new os, new nvme drive, and once installed, attempting to sync as normal. 

Please provide steps on how to reproduce the issue: 
- Install an os on large enough drive above 500gb. 
- update os installing drivers and supportive software, creating restore point. 
- install defi chain app. 
- start defi chain app and the app will attempt to sync.
- in CL enter "addnode seed.mydeficha.in:8555 add" to add a list of nodes (otherwise the sync does nothing, sits at 0%)
- wait for the sync to start, usually takes a few moments but it will start. 
- wait for the sync to complete. I can get to 70 - 80% progress then sync corruption error or computer freezes.

What are your environment parameters:
- DeFi Wallet Version: 2.3.5
- Operating System (OS): windows 10 pro
- Current free storage capacity: 500gb nvme 

Anything else we need to know?
Not that I can think of at this time 

I am not able to log into that drive's os to even get the log sorry. Just that even after a fresh brand new nvme drive with 500gb capacity and a bare bones install, you can still experience issues. In my case, Im locked out of my recent build. I will be re installing win 10 on that nvme today, again, and attempting to get my $ out of defi chain app as soon as possible.

**Comment by blackstormtrader** [comment]
To update, the frozen nvme drive is corrupted and I cant even log into a secondary drive as long as the nvme is connected, to format it. I cant get my security linux usb sticks to work, cant get my windows recovery usb to work, cant get into bios to select drive to boot from. 

Only option I see atm is to return the nvme drive at the store and ask for a replacement, if they let me do this.

**Comment by izzycsy** [comment]
Hi @blackstormtrader , kindly make a backup of your `wallets` folder before bringing your nvme drive back to the store. 

To find your `wallet.dat` if you've not specify a folder. 

**DeFi Blockchain**
`C:\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\`

<img width="822" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/119003301-2fb23680-b9c0-11eb-9443-8e965c621f6f.png">

Steps to synchronisation: 

**Option 1 — Reset & Reindex (sync from 0%)**
  1. Settings > `Reset & Reindex` — which was what you did

 **Option 2 — Snapshot (sync from 90%+)** 
 1. Settings > Reset & Reindex 
 2.  Wait for app to start syncing 
 3.  Ensure you’ve at least 40.51GB of extra space 
 4. Click on `i` located at bottom-left corner of app screen  
 
<img width="244" alt="`i` to trigger Snapshot download" src="https://user-images.githubusercontent.com/65014479/119002988-efeb4f00-b9bf-11eb-85d8-b9daa2d011ee.png">

 5. Download Snapshot 

<img width="1017" alt="Snapshot (Europe)" src="https://user-images.githubusercontent.com/65014479/119003017-f7aaf380-b9bf-11eb-96f3-61f8b2a27e48.png">

<img width="1017" alt="v2 3 5 Snapshot successful 842677" src="https://user-images.githubusercontent.com/65014479/119003036-fbd71100-b9bf-11eb-9b42-a854489e1ae8.png">

Regarding the issue [`Unable to sync to 100%`](https://github.com/DeFiCh/app/issues/853), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.

**Comment by blackstormtrader** [comment]
Yea sorry, I made a post there with some details. cheers.
