### ISSUE TITLE
app does not sync

### ISSUE THREAD

**Issue by helhimm** [DeFiCh/app#871]
since yesterday snapshot does not open my wallet using 2.3.5
if it gets to show the wallet it will not sync, stuck at 97,57%

tried to load 2.3.2, sync does not work

see at Telegraph that many people have the same problem

**Comment by izzycsy** [comment]
Hi @helhimm , you can try to add node. In [DeFiChain-Wiki](https://defichain-wiki.com/wiki/Addnode) the article guides you on how to do this, or simply try via the CLI:
`addnode "seed.mydeficha.in:8555" add` 

Regarding the issue [`Unable to sync to 100% #853`](https://github.com/DeFiCh/app/issues/853), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.
