### ISSUE TITLE
Missing Transactions in app/export

### ISSUE THREAD

**Issue by AndErazor** [DeFiCh/app#872]
Actual behavior: 
List of transactions in defi Wallet is incomplete. I did some swaps and changes to my LM allocation during the crash 2 days ago. Some of these transaction are not shown in the transaction overview and are also missing in the export despite being executed. I even installed the definition app on an additional Mac (brand new, full sync without snapshot, takes 2 days btw with 1GB Internet connection and fully speced Mac mini M1 so this will soon become a problem too) and here even less transactions are displayed as on my primary Mac with the same wallet.dat while balances are ok and in sync. How is this even possible that two devices with the same wallet show different transactions but the same balances

Expected behavior:
All transactions are listed correctly to enable proper reporting and tax filing.

- DeFi Wallet Version: 2.3.5
- Operating System (OS): Mac OS
- Current free storage capacity: plenty on both devices

This issue with inconsistent transaction data is known for a while now, however so far I was always able to reconstruct all transactions by puzzling them together from transactions being displayed under the different assets. This is not the case this time. There are transactions (Swaps, and LM add/remove) completely missing. I would suggest this to be considered a high priority issue, as displaying of transaction history is one of the most essential functions of a wallet and a key requirement to keep track of crypto trades.

**Comment by izzycsy** [comment]
Hi @AndErazor , thanks for your feedback, you could use [DeFiChain Portfolio](https://defichain-wiki.com/wiki/DeFiChain-Portfolio) to monitor the tx history. I understand it's a hassle, the team is investigating on the issue [`DFI: Missing tx history on UI #734`](	https://github.com/DeFiCh/app/issues/734). We can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.
