### ISSUE TITLE
Insufficent Balance

### ISSUE THREAD

**Issue by JoergHoffmann** [DeFiCh/app#873]
Why I cant make any transfers? It doesnt work internal between my intern adresses, nor transfer DFI to Cake. I have enough DFI and UTXO. I tried several times, external and internal. 

![image](https://user-images.githubusercontent.com/18046932/119122676-0da3cd00-ba2f-11eb-8914-9fc17598a538.png)

**Comment by JoergHoffmann** [comment]
![Insufficent Funds](https://user-images.githubusercontent.com/18046932/119257661-8ee19800-bbc6-11eb-8586-692b1693b732.JPG)

**Comment by izzycsy** [comment]
Hi @JoergHoffmann , do you have multiple addresses? 

From your output 
```
gettokenbalances
[
  "194.123456768@0", — tokenDFI
  "XXXXXXXXXX@2",
  "XXXXXXXXXX@5"
]
```

Send 10 tokenDFI to yourself:
1. Copy your address (the one that you're planning to use to send 90DFI from)
2. Click `send DFI`
3. Input 10 DFI
4. Paste the address (step 1)
5. Try the function again (send 90 DFI)

By sending to yourself, you're converting your tokenDFI to utxoDFI. 

Regarding your issue [`Insufficient funds`](https://github.com/DeFiCh/app/issues/704), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.

**Comment by JoergHoffmann** [comment]
Hello,
I have done the two transactions, 30 min. ago. In the end, I am still cant send any DFI to my Cake adress. Meanwhile I dissolved my DFI UDST LM pair Thats why the total amount of DFI is higher, then before. 
![DEFICHAIN2](https://user-images.githubusercontent.com/18046932/119513968-f63d4a80-bd74-11eb-871c-1f78873a07c7.png)

**Comment by JoergHoffmann** [comment]
same when I tried to add liquidity to the BTC- DFI pool. Not enough UTXO DFI. 
![DFI3](https://user-images.githubusercontent.com/18046932/119514822-a0b56d80-bd75-11eb-86f3-fe819a37d067.JPG)

**Comment by JoergHoffmann** [comment]
I cant Swap USDT to DFI. Not enough UTXO. 

![DFI4](https://user-images.githubusercontent.com/18046932/119516107-c0996100-bd76-11eb-89e9-60c93f6b8ed3.JPG)

**Comment by izzycsy** [comment]
Hi @JoergHoffmann , [v2.5.0](https://github.com/DeFiCh/app/releases/tag/v2.5.0) is out. Please read through the release notes before updating. Perhaps this might help you further: https://github.com/DeFiCh/app/discussions/846
