### ISSUE TITLE
Error with Wallet Balance

### ISSUE THREAD

**Issue by florianboschi** [DeFiCh/app#877]
I installed the updated version and since then I get an error each time the app syncs on my laptopo. It says error with wallet balance (Fehler
[app logs.zip](https://github.com/DeFiCh/app/files/6538296/app.logs.zip)
 mit Wallet Guthabern)

**Comment by Stonygan** [comment]
https://github.com/DeFiCh/app/issues/849

When you need your APP these days, try the workaround with spv=0. Otherwise wait for the new version this week, fix is included.

Please close this Issue when it solves your problem.

**Comment by florianboschi** [comment]
thank you I will wait and once it is resolved, close the issue.

**Comment by izzycsy** [comment]
Hi @florianboschi , as @Stonygan mentioned you may try the workaround, or wait for the team to resolve this issue in the next release. Regarding the issue [`Network ERROR at new wallet 2.3.4 #849`](https://github.com/DeFiCh/app/issues/849), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you. 

Refer to [DeFiChain Announcements (EN)](https://t.me/defichain_announcements) for official announcements.
