### ISSUE TITLE
Wallet 2.4.0 RC1 sync issues.

### ISSUE THREAD

**Issue by Faucet1313** [DeFiCh/app#878]
After downloading and installing the last version of the wallet i downloaded and installed the snapshot and got "Database corrupted" then i restart the app apply the snapshot again and since hour it is now freeze to "Looking for peers" and sync does not start. 

#### What are your environment parameters?

- DeFi Wallet Version: 2.4.0 RC1
- Operating System (OS): Windows server 2019
– Current free storage capacity: 300GB
[logs.log](https://github.com/DeFiCh/app/files/6538641/logs.log)

**Comment by izzycsy** [comment]
Hi @Faucet1313 , v2.4.0-rc1 is marked as a pre-release. It's still undergoing testing, please wait for [DeFiChain Announcements (EN)](https://t.me/defichain_announcements).
