### ISSUE TITLE
Hi Bella it is Michael from Telegram

### ISSUE THREAD

**Issue by michaelE123** [DeFiCh/app#881]
#### What are your environment parameters?

- DeFi Wallet Version: 2.3.4
- Operating System (OS): MAC OS 11.4
– Current free storage capacity: 1TB
[Archive.zip](https://github.com/DeFiCh/app/files/6552469/Archive.zip)

**Comment by izzycsy** [comment]
Hi @michaelE123 , regarding the issue [`DFI: Missing tx history on UI #734`](https://github.com/DeFiCh/app/issues/734), kindly send your logs there, we would like to keep same issues in one thread. Thank you.
