### ISSUE TITLE
Other snapshots enhancements

### ISSUE THREAD

**Issue by John-Gee** [DeFiCh/app#882]
#### Which feature is your request related to?
Snapshots

#### Is your request related to a problem? Please describe.
No

#### Describe the solution you'd like:
1- The app is offering me the choice of Europe or Asia to download from, which I'm in neither... Why not let CDN take care of that, and if somehow you cannot let the app decide what is best, instead of asking me when honestly I have no idea which is less worse?

2- Downloading in the wallet was much slower than doing it with aria2c, which got even faster when I added both aws locations to aria2c.

3- When extracting the snapshot, it'd be nice to know what % has been done so far/how much time left.

4- Can you not download to ~/snapshots but something more specific? That does not look clean to me nor am I keen on more folders in ~/ . Also is this location configurable in the config file? I have the space, but maybe others won't.

#### Additional context:

@thedoublejay 

Thank you!

**Comment by izzycsy** [comment]
Hi @John-Gee , [v2.4.0]https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a mandatory update. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by John-Gee** [comment]
Thanks!

**Comment by izzycsy** [comment]
Hi @John-Gee , [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @John-Gee , [v2.5.0](https://github.com/DeFiCh/app/releases/tag/v2.5.0) is out. Please read through the release notes before updating. The team has added more locations for the snapshot download, and are working on the Light Wallet at the moment, when it's ready it's unlikely that you'll need to run a full node. Posting non-bug related issues here will eventually turn stale. You can publish your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner some support from the community, and the team can decide whether to implement the feature (3–4) in the future. Thank you!

**Comment by John-Gee** [comment]
Very well, thank you @izzycsy !

But for the light wallet, I don't think it's a good idea to depend on that, so I'd be likely to keep running a full node instead.

**Comment by John-Gee** [comment]
@izzycsy getting back on this if you don't mind.

I tried today with 2.5.1 and indeed downloading the snapshot was much faster with a closer location to me!

I'll create a discussion as you said for the other points. Thanks again!
