### ISSUE TITLE
All my 3 Redundat Systems Crashed Today !!!!!

### ISSUE THREAD

**Issue by rolandwellinger** [DeFiCh/app#883]
#### Actual behavior:
3 Wallet Apps crashed today at 99% Sync!
2 of them 2.3.5
1 of them 2.3.3
NO LONGER ACCESS TO MY ACCOUNT AND COINS!!!!!

Errors:
NODE DISCONECTED => Corrupt
DEBUG-LOG => Last Blocks Corrupt! 

COME ON!

#### Expected behavior:
Should WORK!!!!

#### How to reproduce it (as minimally and precisely as possible):
Just let it Run!

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.5 and 2.3.3
- Operating System (OS): Windows 10
– Current free storage capacity: > 200GB

#### Anything else we need to know?
You really must fix that! It cannot be that we every day must fix the Blockchain by downloading a SnapShot. I've 3 System Running good for about 3 Days! THEN OUT OF NOTHING!!

**Comment by supervolot** [comment]
I have a stucked sync at Block 878369 on 2 Server ???

**Comment by supervolot** [comment]
> #### Actual behavior:
> 3 Wallet Apps crashed today at 99% Sync!
> 2 of them 2.3.5
> 1 of them 2.3.3
> NO LONGER ACCESS TO MY ACCOUNT AND COINS!!!!!
> 
> Errors:
> NODE DISCONECTED => Corrupt
> DEBUG-LOG => Last Blocks Corrupt!
> 
> COME ON!
> 
> #### Expected behavior:
> Should WORK!!!!
> 
> #### How to reproduce it (as minimally and precisely as possible):
> Just let it Run!
> 
> #### What are your environment parameters?
> * DeFi Wallet Version: 2.3.5 and 2.3.3
> * Operating System (OS): Windows 10
>   – Current free storage capacity: > 200GB
> 
> #### Anything else we need to know?
> You really must fix that! It cannot be that we every day must fix the Blockchain by downloading a SnapShot. I've 3 System Running good for about 3 Days! THEN OUT OF NOTHING!!

I install new new 2.4 rc3 and now sync wokrs again.

**Comment by izzycsy** [comment]
Hi @rolandwellinger , the next update should resolve storage issue, it's currently undergoing testing. In the mean time, please keep your `wallet.dat` safe. Regarding the issue [`Unable to sync to 100% #853`](https://github.com/DeFiCh/app/issues/853), we can further discuss on the issue there. We would like to keep same issues in one thread. We'll update the thread when the team has a fix ready. Thank you.

Hi @supervolot , kindly refrain from installing pre-releases, it’s still in the midst of testing, use it at your own discretion. I would strongly advice that you wait for the official [DeFiChain Announcements (EN)](https://t.me/defichain_announcements) for v2.4.0. Thank you for your understanding.
