### ISSUE TITLE
Liquidity & DEX: `Loading...`

### ISSUE THREAD

**Issue by nippur72** [DeFiCh/app#887]
#### Actual behavior:

wallet app is slow e.g. when switching from "balances" to "liquidity" it takes a long time ti display data (gets stuck on "Loading..."). After checking with task manager `defid.exe` has high CPU load (20% or so).

#### What are your environment parameters?

- DeFi Wallet Version: 2.4.0
- Operating System (OS): Win 10
– Current free storage capacity: 200 gigs

![image](https://user-images.githubusercontent.com/2598443/120043074-97ddc980-c00b-11eb-9b13-92c9ed587b17.png)

![image](https://user-images.githubusercontent.com/2598443/120043116-aaf09980-c00b-11eb-93b0-08df51780fea.png)

here is the [applog.log](https://github.com/DeFiCh/app/files/6563393/applog.log)

**Comment by nippur72** [comment]
and since `defid.exe` is stuck it won't let me swap:

![image](https://user-images.githubusercontent.com/2598443/120043603-88ab4b80-c00c-11eb-93ea-a2b547c9130e.png)

**Comment by izzycsy** [comment]
Hi @nippur72 , thanks for the screenshot and logs, please give us time to investigate. Both Liquidity and DEX takes about 1min to load with good internet connection before you can use. The team is looking into the issue.

**Comment by ian309699** [comment]
Hello,
I am having the exact same issue, with the same parameters as above 
   DeFi Wallet Version: 2.4.0
   Windows 10
   Current free storage capacity: 200 GB

It works fine, but it is painfully slow, Thanks for looking into it

**Comment by 2Dsirecrypto** [comment]
![DEXnothing](https://user-images.githubusercontent.com/80450348/120099060-c4652300-c17c-11eb-84f9-8d6af1cb324e.PNG)

My DEX does often not load at all.
This has always been an issue for me not just on latest V2.4.0

**Comment by RadioSteve-dev** [comment]
Same on my Windows 10 server, 12 processor, 24 GB RAM, 150 GB free disk space, Tier 3 datacenter in the USA, IONOS. Very slow, adding liquidity takes now about 10 minutes. One time I left the screen because I thought something went wrong. Then I could not do any other action anymore. Error message was that I would have to wait until the other transaction would be done. I waited about 2 hours. Nothing happend. Then I restored the wallet with snapshot. Hung at 99.98% for several hours. That gave me some sweat, because I have substantial funds on the wallet. Then I restored it 2 times again, and it could sync the second time to 100%. Then also the error message was gone. Now I am back to the slow behavior with 10 minutes for 1 single liquidity operation. It takes up to 20 minutes to show the withdrawals in the wallet sums!

**Comment by izzycsy** [comment]
Hi @ian309699 @2Dsirecrypto @RadioSteve-dev , can you save your logs and send them here please, thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/120116399-8a1a7680-c1ba-11eb-8473-3110f230927b.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/120116402-8be43a00-c1ba-11eb-8603-c68fa7d47d4d.png">

**Comment by ian309699** [comment]
[AppLogs.log](https://github.com/DeFiCh/app/files/6566776/AppLogs.log)

**Comment by ian309699** [comment]
The link for the logs is above. Hope this helps. Thanks

**Comment by RadioSteve-dev** [comment]
Binary log is not written to disk. Tried it 3 times.

**Comment by izzycsy** [comment]
Hi @RadioSteve-dev , you need to specify where to save the log files, in the example above, the files are saved to desktop then .zip together.

**Comment by RadioSteve-dev** [comment]
I am IT specialist and you can believe me, that I specified location and filenname. Still not written. App log is written, app config is written, no binary log.

**Comment by RadioSteve-dev** [comment]
I tried also with locked and unlocked wallet.

**Comment by ian309699** [comment]
The functions of the wallet seem to be getting worse.
Not only is it taking a very long time, it is now telling me that I have insufficient funds.
I have plenty of DFI, Also I have plenty of UTXO for the transaction fees. 
For Example, I tried to send some DFI to Cake. The app tells me I have insufficient funds When I try and send DFI to myself the app tells me I have insufficient funds

**Comment by RadioSteve-dev** [comment]
@ian309699 I have the same impression. I also have plenty of UTXOs and the wallet complains that I would not have enough. Then I send again 1 DFI to one of my wallet addresses and it does 1 more liquidity operation. But all takes between 10 and 60 minutes. Incredibly slow. I am on board since the very beginning, but this behavior of the app is new.

**Comment by RadioSteve-dev** [comment]
Ah, I remember that it did not accept even 1 DFI to be sent from my wallet to my own wallet address. THen I tried 2 DFI and it worked. Slowly.

**Comment by ian309699** [comment]
I tried to send 2 DFI to myself, and the app said I have insufficient UTXO.
Then I tried to send1 DFI to myself to fix the UTXO, and the app said I have an insufficient balance.
I feel like its trapped in a loop

**Comment by RadioSteve-dev** [comment]
A new experience. I tried just now again to add liquidity and it worked much smoother than some 8 hours ago. The liquidity op took 2 minutes and after 3 minutes in total it was reflected in my wallet data. That is bearable.

**Comment by ian309699** [comment]
I opened up my wallet on another computer, and sent my self 1 DFI, and it worked fine.
Then I went back to my other computer and sent 3 DFI to Cake, and it went through.
very strange.

**Comment by 2Dsirecrypto** [comment]
[app config.zip](https://github.com/DeFiCh/app/files/6567052/app.config.zip)
I opened the wallet again this morning waited for 1/2 hr still nothing 
I have attached my log files as requested

**Comment by ian309699** [comment]
Hi,

I upgraded to v2.4.1-rc.1.
My funds are still there updating with rewards. But I can only acccess BCH liquidity.
Also now It does not show receiving addresses in the app at all

**Comment by nippur72** [comment]
I upgraded to 2.4.1-rc1 as well, DEX & Liquidity now load quickly, tough occasionally it can take up to 30 seconds. But it's a great improvement.

@ian309699 I can see my `USDT-DFI` pool and all the receiving addresses. The only missing thing is the TX history (discussed in another issue).

**Comment by ian309699** [comment]
I cant even access BCH Liquidity anymore.
I have the wallet open on another computer, to test it out, and now it is showing two different DFI amounts, same wallet, same block, two amounts, and still no LM access or receiving addresses

**Comment by ian309699** [comment]
Now I have the same DFI amounts, I fixed that. But I still have the original problem, no LM and no receiving addresses

**Comment by izzycsy** [comment]
Hi @ian309699 , can you save your logs and send them please? 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/120289781-3d3abb00-c2f4-11eb-807c-51d06286c476.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/120289801-42980580-c2f4-11eb-881f-90c9e12ce8eb.png">

**Comment by ian309699** [comment]
here are the logs
[AppLogs.log](https://github.com/DeFiCh/app/files/6576735/AppLogs.log)

**Comment by izzycsy** [comment]
Hi @ian309699 , well received. Regarding the issue [`Recipient address is missing #904`](https://github.com/DeFiCh/app/issues/904), the team is in the midst of investigating and fixing, we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you. Also, please look out for the latest announcements on app releases on [DeFiChain Announcements (EN)](https://t.me/defichain_announcements).

**Comment by izzycsy** [comment]
Hi @nippur72 @ian309699 @2Dsirecrypto @RadioSteve-dev , [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**. Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.

**Comment by ian309699** [comment]
The update did not fix the issue 
My addresses are still missing
 and no Liquidity pools ... 
the coin amounts are correct and still updating, but no addresses or LM
here are the logs
[App Logs.log](https://github.com/DeFiCh/app/files/6585988/App.Logs.log)

**Comment by izzycsy** [comment]
Hi @ian309699 , can you try to `Rescan`? Regarding the issue [Recipient address is missing #904](https://github.com/DeFiCh/app/issues/904), the team is in the midst of investigating and fixing, we can further discuss on the issue there. We would like to keep same issues in one thread. You can post your logs there, thank you.

<img width="782" alt="Rescan" src="https://user-images.githubusercontent.com/65014479/120539323-0f4f9680-c41a-11eb-97b1-b0c616ee3e1d.png">

**Comment by nippur72** [comment]
@izzycsy I upgraded to 2.4.3 but the history it's still not there. Can we reopen this issue? Here are my [logs](https://github.com/DeFiCh/app/files/6593612/logs.zip)

![image](https://user-images.githubusercontent.com/2598443/120695041-2f7b6600-c4ab-11eb-828c-ba8ed21149d8.png)
