### ISSUE TITLE
Missing transactions after 2.4.0 upgrade

### ISSUE THREAD

**Issue by nippur72** [DeFiCh/app#889]
I don't know if this is related to #529 but I just upgraded from 2.3.5 to 2.4.0 and the past transactions are gone. It shows only the transactions after the upgrade.

#### What are your environment parameters?

- DeFi Wallet Version: 2.4.0
- Operating System (OS): Windows 10
- Current free storage capacity: 200 Gb

**Comment by izzycsy** [comment]
Hi @nippur72 , yes it's likely related, regarding the issue [`Missing tx history #529`](https://github.com/DeFiCh/app/issues/529), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.
