### ISSUE TITLE
Block Synchronization does not work

### ISSUE THREAD

**Issue by baludwi** [DeFiCh/app#89]
Hi,
in my defi-app (version 2.1.3) the synchronisation freezes at block. 468954 (98,26%). I wait for some hours but it does noch go forward. What can I do?

**Comment by izzycsy** [comment]
Hi @baludwi thanks for your feedback. May I know what OS you're using? Could you describe your user flow more? We need more details in order investigate how to reproduce this issue. Thank you!

**Comment by mroxso** [comment]
push. I got the same error on Linux AppImage (version 2.1.0 and above)

**Comment by baludwi** [comment]
Hi,

thanks for Your reply. The Problem is solved.

Bella Chew <notifications@github.com> schrieb am Fr. 4. Dez. 2020 um 09:18:
