### ISSUE TITLE
Removing 100% liquidity only removes from first address in wallet

### ISSUE THREAD

**Issue by romainhaenni** [DeFiCh/app#894]
#### Actual behavior:

I wanted to remove 100% from my LTC-DFI liquidity pool. My LTCDFI tokens are distributed on three addresses:
1. 22 LTCDFI
2. 77 LTCDFI
3. 510 LTCDFI

Only the 22 LTCDFI from the first address got removed and added to my balance, the rest is still in my liquidity pool generating rewards.

I tried several times to remove the rest from the liquidity pool. Even though I have got the confirmation message that the blockchain has accepted my removal, nothing happens afterwards (I have been waiting now for more than 12h for fullfilling my request).

#### Expected behavior:

I expect the wallet app to remove exactly my determined amount from all addresses with one request.

#### How to reproduce it (as minimally and precisely as possible):

1. Add liquidity distributed to more than one wallet address
2. Go to liquidity pool and remove 100%
3. Only the amount of one address gets removed the rest won't be affected
4. Repeat step 2., positive confirmation but nothing happens

#### What are your environment parameters?

- DeFi Wallet Version: 2.4.0
- Operating System (OS): macos 11.4, M1
– Current free storage capacity: 900GB

#### Anything else we need to know?

[Defi Wallet App Logs.zip](https://github.com/DeFiCh/app/files/6565856/Defi.Wallet.App.Logs.zip)

**Comment by izzycsy** [comment]
Hi @romainhaenni , thanks for your feedback, please give us time to investigate.

**Comment by romainhaenni** [comment]
restarted the app and could remove liquidity as expected..
