### ISSUE TITLE
Export logs already named and zipped

### ISSUE THREAD

**Issue by romainhaenni** [DeFiCh/app#895]
#### Which feature is your request related to?

Exporting logs.

#### Describe the solution you'd like:

Exporting logs right now needs me to save three files, name and zip them. I would rather like to save an already zipped file once. This zip contains all three log files already named accordingly:

Defi Wallet App Logs.zip:
  - App Config.conf
  - App Logs.log
  - Binary Logs.log

#### Describe alternatives you've considered: 

On user request, write all three log files into one file and upload it to some cloud storage. After upload, show a URL to this log file. This URL can be used to share this log file to anyone of need much easier instead of sharing a zip file.

#### Additional context:

I have created a github issue for a bug and you asked me to provide the app logs in a zipped format. It was a bit cumbersome to get these files, a workflow I think could be done much simpler for the user.

**Comment by izzycsy** [comment]
Hi @romainhaenni , thanks for you feedback, posting non-bug related issues here will eventually turn stale. You may publish your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner some support from the community, and the team can decide whether to implement the feature in the future. Thank you!
