### ISSUE TITLE
App tries to bind RPC Port to 8555, while its already bound to the P2P Service

### ISSUE THREAD

**Issue by muirglacier** [DeFiCh/app#897]
#### Actual behavior:

More and more people - both on Discord and Telegram - report that they find curiosities like that in their defi.conf

**[main]
rpcbind=127.0.0.1
rpcport=8555**

which ultimately leads to weird yet expected error messages like this in the log (in many cases accompanied by troublesome experiences either starting or using the app):

**Binding RPC on address 127.0.0.1 port 8555 failed.**

To clarify, the node's P2P functionality is - by default - listening on port 8555. When RPC tries to bind to the same port, it all goes pear shaped.

#### Expected behavior:

RPC on port 8554

#### What are your environment parameters?

- DeFi Wallet Version: 
- Operating System (OS):
– Current free storage capacity:

**Comment by izzycsy** [comment]
Hi @muirglacier , [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @muirglacier , posting non-bug related issues here will eventually turn stale. You can publish your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner some support from the community, and the team can decide whether to implement the feature in the future. Alternatively, you can contribute a PR to the project as well. Thank you!

**Comment by izzycsy** [comment]
Hi @muirglacier , update [v2.6.0](https://github.com/DeFiCh/app/releases/tag/v2.6.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @muirglacier , update [v2.6.1](https://github.com/DeFiCh/app/releases/tag/v2.6.1) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @muirglacier , update [v2.6.2](https://github.com/DeFiCh/app/releases/tag/v2.6.2) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @muirglacier , update [v2.6.3](https://github.com/DeFiCh/app/releases/tag/v2.6.3) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._
