### ISSUE TITLE
how to start the installation with reindex or reindex-chainstate?

### ISSUE THREAD

**Issue by hashrandy** [DeFiCh/app#90]
hi, i tried to install the latest version, but i got this error message:

**Comment by hashrandy** [comment]
![grafik](https://user-images.githubusercontent.com/75382745/101247147-d73ff300-3717-11eb-81b1-e962b9465aca.png)

**Comment by Yannick1712** [comment]
You can set the Reindex-Option in the wallet settings. Then the wallet will try to reindex.

**Comment by hashrandy** [comment]
Setting options is not possible because message stops the installaltion

**Comment by izzycsy** [comment]
Hi @hashrandy , thanks for your feedback. May I know the OS + version no. you're using? Please give us time to investigate this issue. We'll be releasing a new update coming up soon, we'll update on Telegram. Might be able to resolve your issue. Thank you for your patience!

**Comment by micegit** [comment]
Had the same issue. After restart of the APP and sync, APP window remains empty, only menu is visible.

**Comment by micegit** [comment]
![App_nach_sync](https://user-images.githubusercontent.com/76484252/102897833-ec7f8600-4468-11eb-8bcd-439ac7180772.JPG)

**Comment by izzycsy** [comment]
Hi @micegit , thanks for your feedback, could you send your app logs please? 
<img width="339" alt="App log" src="https://user-images.githubusercontent.com/65014479/103077641-1ec8e900-460b-11eb-9fd0-9e36dbe1dec4.png">

<img width="511" alt="Compress" src="https://user-images.githubusercontent.com/65014479/103077624-17a1db00-460b-11eb-892f-6f0f5e6f586a.png">

**Comment by izzycsy** [comment]
Hi @hashrandy @micegit , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue w new information (include screenshots) and your app logs. Thank you.
