### ISSUE TITLE
Unable to see Transactions other than first 9 on day I opened wallet (DFI) wallet

### ISSUE THREAD

**Issue by KrisKade** [DeFiCh/app#900]
#### What are your environment parameters?

- DeFi Wallet Version: 2.4.1
- Operating System (OS): 11.4
– Current free storage capacity:

**Comment by defijeff** [comment]
Can reproduce on Linux AppImage. However for me it was already broken in 2.3.5.

**Comment by thedoublejay** [comment]
Hi, there's an existing issue for the node side on this. https://github.com/DeFiCh/ain/issues/441. In case you need the full history, you may do a full re-index instead of using a snapshot.

**Comment by izzycsy** [comment]
Hi @KrisKade @defijeff , thanks for your feedback, regarding the issue [`Missing past tx history`](https://github.com/DeFiCh/app/issues/891), we can further discuss on the issue there. We would like to keep same issues in one thread. In the mean time you may use [DeFiChain Portfolio](https://defichain-wiki.com/wiki/DeFiChain-Portfolio) to monitor your tx history.
