### ISSUE TITLE
Own Masternodes not visible in 2.4.1

### ISSUE THREAD

**Issue by Stonygan** [DeFiCh/app#901]
#### Actual behavior:
After select Tab Masternodes, the own Masternodes are not shown in Mine. 
#### Expected behavior:
See all own Masternodes. 
#### How to reproduce it (as minimally and precisely as possible):
Click on Masternodetab

#### What are your environment parameters?

- DeFi Wallet Version: 2.4.1
- Operating System (OS):windows
– Current free storage capacity:

#### Anything else we need to know?
Masternode operates on a separate VPS.

**Comment by thedoublejay** [comment]
Hi @Stonygan, thanks for raising it. We'll take a look. Might be related to caching that we implemented for v2.4.1.

**Comment by defijeff** [comment]
Can reproduce on Linux AppImage too.

It should prompt to unlock the wallet for 3 yrs as but fails prompting to doing so within ~30 secs of having opened the app (this is the way it worked in 2.4.0 and earlier)

**Comment by Faucet1313** [comment]
Same issue for me with 2.4.1.

**Comment by toumby** [comment]
Same issue for me with 2.4.1.
