### ISSUE TITLE
Insufficient funds

### ISSUE THREAD

**Issue by 778010** [DeFiCh/app#903]
Hello, 
I've been getting the error message "Insufficient funds" for a long time when I try to use Dex or liquidity. 
I reinstalled the app and rebuilt the blockchain. 
The error message remains. 
I need help because I don't know what to do next. 

[app logs.zip](https://github.com/DeFiCh/app/files/6577743/app.logs.zip)
Best regards Jörg

**Comment by izzycsy** [comment]
Hi @778010 , it’s likely that you've insufficient utxoDFI balance (min. 1 DFI) — which is required to perform swap and all other functions. DFI exist in 2 forms; `utxoDFI` and `tokenDFI`. utxoDFI is used to pay for transactions fees while rewards received from liquidity mining (for example) are in tokenDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. To convert tokenDFI to utxoDFI, the simplest way would be via DeFi Wallet app.   

Firstly, check via CLI:  
`getbalance` — utxoDFI
`gettokenbalances` — tokenDFI 

From your output 
```
gettokenbalances
[
  "3.123456768@0", — tokenDFI
  "XXXXXXXXXX@2",
  "XXXXXXXXXX@5"
]
```

Send 1 tokenDFI to yourself:
1. Copy your address (the one that you're planning to use to add liquidity)
2. Click `send DFI`
3. Input 1 DFI
4. Paste the address (step 1)
5. Try the function again

By sending to yourself, you're converting your tokenDFI to utxoDFI. utxoDFI is used for transaction fees.

Regarding the issue [`Unable to add liquidity`](https://github.com/DeFiCh/app/issues/704), we can further discuss on the issue there should your issue persist. We would like to keep same issues in one thread. Thank you.
