### ISSUE TITLE
Recipient address is missing

### ISSUE THREAD

**Issue by Rocky-81** [DeFiCh/app#904]
When changing the token to Dex, the recipient's address is missing. how can you add this?

**Comment by izzycsy** [comment]
Hi @Rocky-81 , are you on v2.4.1? The team is aware of this issue and are currently fixing it. You can try to manually add it back, toggle-off the automatically create address. 

<img width="775" alt="Receive   Manually add address" src="https://user-images.githubusercontent.com/65014479/120372872-4eaeb200-c34a-11eb-8d6d-bc7a18956b5f.png">

**Comment by thedoublejay** [comment]
Hi @Rocky-81, we have released version v2.4.2 to address this issue - https://defichain.com/downloads/. 

What you can do is to force a `rescan` of addresses. It can be done by either of the two:
1. Apply snapshot (it will trigger rescan after)
2. Or go to Settings Page -> Advanced -> Rescan

**Comment by izzycsy** [comment]
Hi @Rocky-81 , [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by ian309699** [comment]
Hi @izzycsy I am going to try and rescan

 I'll let you know what happens..

**Comment by izzycsy** [comment]
Hi @ian309699 , sure thing, or you can you backup your current wallet, and try another `wallet.dat`. 

<img width="287" alt="Menu bar   Backup Wallet" src="https://user-images.githubusercontent.com/65014479/120489320-2080af00-c3ea-11eb-8157-153c4527a95a.png">

**Comment by ian309699** [comment]
Rescan did not work

I have updated to v2.4.2 and I am 100% synced, I even tried to use another wallet.dat file I have, and did the rescan again. It did not work

**Comment by thedoublejay** [comment]
Hi, we have a fix for this issue with v2.4.3. It's available now for download - https://github.com/DeFiCh/app/releases/tag/v2.4.3
