### ISSUE TITLE
DEX Swap Failure

### ISSUE THREAD

**Issue by happydayxxl** [DeFiCh/app#905]
#### Expected behavior: DEX Swap (DEFI -> USDT)
[logs.zip](https://github.com/DeFiCh/app/files/6580558/logs.zip)

#### What are your environment parameters?

- DeFi Wallet Version: 2.4.1
- Operating System (OS): windows 10
– Current free storage capacity: 200gb

#### Anything else we need to know?

I swapped 141 DEFI to USDT but I got no usdt out.
Transaktion: https://mainnet.defichain.io/#/DFI/mainnet/tx/7d49278f8a35534c1eeb31b096b5b82f7df410fd76996e3bc2e83a1e4d506395
Reddit post:
https://www.reddit.com/r/defiblockchain/comments/npq9j0/dex_swap_error/
[logs.zip](https://github.com/DeFiCh/app/files/6580560/logs.zip)

**Comment by happydayxxl** [comment]
![image](https://user-images.githubusercontent.com/85102028/120391000-b5be6d80-c32e-11eb-925a-18fa27705fff.png)
Screenshot no output is shown

**Comment by happydayxxl** [comment]
Hello izzycsy
Thanks for your response!
I also saw that this address: [dLkq..](https://dex.defichain.com/mainnet/address/dLkqkmhXUqoxiDNvXBpWvGSSEGxaoLtAwm) received it but this address not refleced my receiver addresses in my wallet.
I checked the cli with gettokenbalances and the 419.18350021 USDT are still missing. 
I also checked the command "listaccounthistory" and not found this address.
But how could i swap when the address [dLkq..](https://dex.defichain.com/mainnet/address/dLkqkmhXUqoxiDNvXBpWvGSSEGxaoLtAwm) not mine?

Do you have any other ideas to solve the problem?

**Comment by izzycsy** [comment]
Hi @happydayxxl , can you try adding back `dLkq...` to your receive address? 

<img width="775" alt="Receive   Manually add address" src="https://user-images.githubusercontent.com/65014479/120479672-cc250180-c3e0-11eb-9d46-e1ddb659c971.png">

In DEX, you've to state where to receive your tokens at. 

<img width="753" alt="DEX" src="https://user-images.githubusercontent.com/65014479/120479735-df37d180-c3e0-11eb-870a-8f94d3aed740.png">

Based on your logs, `dLkq...` does belong to you. 

{"address":"dLkq...","label":"DEFI","id":"9XXX","ismine":true,"time":"2021-03-14T09:39:36.000Z","hdSeed":true},

**Comment by izzycsy** [comment]
Hi @happydayxxl , alternatively, you can update to  [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2), this is a **mandatory update** anyway. Please read through the release notes before updating. In this build includes a fix for any missing address issue that some users were facing.

**Comment by happydayxxl** [comment]
Hello thanks for responsing again :)
I tried to add the address but an error occours:
Invalid address. Please check this belongs to you.
![image](https://user-images.githubusercontent.com/85102028/120487421-3eccb780-c3b6-11eb-8838-79055cf6e981.png)

**Comment by happydayxxl** [comment]
hi, @izzycsy i also rescan the node with the newest version of the app but unfortunately without success. After that I tried again to add the address, but again "invalid address".

**Comment by izzycsy** [comment]
Hi @happydayxxl , can you backup your current wallet, and try another `wallet.dat`? 

<img width="287" alt="Menu bar   Backup Wallet" src="https://user-images.githubusercontent.com/65014479/120489320-2080af00-c3ea-11eb-8157-153c4527a95a.png">

**Comment by happydayxxl** [comment]
Now see the exchanged values! I haven't looked into the second wallet for a while...
I've been using the two wallets for half a year, but this never happens. 
THANKS A LOT @izzycsy !

**Comment by happydayxxl** [comment]
THANKS AGAIN FOR THE SUPPORT!

**Comment by izzycsy** [comment]
Hi @happydayxxl , make a new backup and continue using the new backup. Please keep your wallet.dat safe. Thank you.
