### ISSUE TITLE
w/ Mac and App 2.4.2 rc1 - new transactions not showing

### ISSUE THREAD

**Issue by AndiyNW** [DeFiCh/app#906]
#### How to reproduce it (as minimally and precisely as possible): Don't know yet, will add some liquidity later today, when mining produced some DFIs again 
[Logs-20210602.zip](https://github.com/DeFiCh/app/files/6580961/Logs-20210602.zip)

#### What are your environment parameters?

- DeFi Wallet Version: 2.4.2 rc1
- Operating System (OS): OSX latest, 11.4
– Current free storage capacity: 500+ GB

**Comment by AndiyNW** [comment]
Good morning,

so as said, I did just before some DFI DEX to get dBTC and added liquidity to the pool and the show up now in the transactions, the ones from yesterday 20210601 are still missing in the history! 😢

**Comment by AndiyNW** [comment]
Update:

I kept the wallet app open and magically, the transactions from today just before disappeared! I attach the logs for checking and the screenshots for proof!

<img width="1677" alt="Screenshot 2021-06-02 at 09 33 11" src="https://user-images.githubusercontent.com/25152510/120442694-3197d480-c386-11eb-8011-8b7909573aff.png">
<img width="1025" alt="Screenshot 2021-06-02 at 09 22 53" src="https://user-images.githubusercontent.com/25152510/120442702-33fa2e80-c386-11eb-95f4-ee67ade88f7b.png">
<img width="1024" alt="Screenshot 2021-06-02 at 09 22 35" src="https://user-images.githubusercontent.com/25152510/120442705-3492c500-c386-11eb-8c79-e8e2fa0a4614.png">
<img width="1025" alt="Screenshot 2021-06-02 at 09 22 17" src="https://user-images.githubusercontent.com/25152510/120442709-352b5b80-c386-11eb-8ef0-558f9caddb91.png">
<img width="1027" alt="Screenshot 2021-06-02 at 09 20 20" src="https://user-images.githubusercontent.com/25152510/120442716-35c3f200-c386-11eb-9cba-262e23768962.png">

[Logs-20210602-0933.zip](https://github.com/DeFiCh/app/files/6582848/Logs-20210602-0933.zip)

**Comment by izzycsy** [comment]
Hi @AndiyNW , kindly refrain from installing `pre-releases`, it’s still in the midst of testing, use it at your own discretion. I would strongly advice that you wait for the official [DeFiChain Announcements (EN)](https://t.me/defichain_announcements). Thank you for your understanding.
 The latest version is [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2).

**Comment by AndiyNW** [comment]
Hi Bella @izzycsy 

well, it happened with the official 2.4.2 rc1 from yesterday too, as mentioned in my original post, second, the app said update available, which I then did in the morning, which brought me to 2.4.3 rc1, so it wasn't intentionally, but yep, can go guess, manually to 2.4.2 and provide the same case again, as I'm sure it's still there!

ciao
andiy

**Comment by izzycsy** [comment]
Hi @AndiyNW , thanks for the update, yes I think it was due to the v2.4.2-rc1 announcement. Kindly switch to v2.4.0 for your safety. Thank you!

**Comment by AndiyNW** [comment]
Hi Bella,

jFYI, upgraded now to 2.4.3 and did a reindex from Snapshot, took around 30 minutes and now all my transactions are back, including the two missing ones from yesterday and the day before! Thanks and great job girls and guys! 👍🏻😎

ciao
Andiy
