### ISSUE TITLE
LM pool pair missing in version 2.4.2

### ISSUE THREAD

**Issue by heider89** [DeFiCh/app#907]
#### Actual behavior: As per title, the LM pool pair (ETH-DFI) is missing as shown below.
![image](https://user-images.githubusercontent.com/85205030/120409446-81c16780-c383-11eb-9671-b03015446c5f.png)

#### What are your environment parameters?

- DeFi Wallet Version: 2.4.2
- Operating System (OS): Windows 10
– Current free storage capacity: 268GB

#### Anything else we need to know?
1. My transactions/contribution to the LM pool pair (ETH-DFI) is also missing under the transactions tab.
2. My saved address(es) are missing.

[logs_heider89.zip](https://github.com/DeFiCh/app/files/6581408/logs_heider89.zip)

**Comment by lawerfx** [comment]
I also have this issue but 2 of my 5 LM pools show the others don't show

**Comment by thedoublejay** [comment]
Hi @lawerfx @heider89, we have a new update to fix this issue. You may download v2.4.3 from here https://github.com/DeFiCh/app/releases/tag/v2.4.3
