### ISSUE TITLE
Heavy harddisk load when exporting / showing transaction (incl. rewards)

### ISSUE THREAD

**Issue by MaReCoding** [DeFiCh/app#908]
#### Actual behavior:
When I try to export all transactions (including the rewards) the app generates extrem high harddisk loads and it seems as if the wallet reads the whole blockchain.
The same happens in the transaction dialog when you check the button "Include rewards"

#### Expected behavior:
Like in the version 2.3.x, all transactions showed up nearly instantly.

#### How to reproduce it (as minimally and precisely as possible):
1. Open wallet
2. Wait for finishing the sync
3. Open dialog "Transactions"
4. Check "Include rewards"
5. -->Wait nearly 8 minutes (on my PC with a very fast ssd)
6. Click "Export data"
7. Check "Include rewards"
8. Again wait... 

#### What are your environment parameters?

- DeFi Wallet Version: 2.4.2
- Operating System (OS): macOS Big Sur 11.4
– Current free storage capacity: 230GB
- System: Macbook pro (M1 Chip)

#### Anything else we need to know?
- Because I need the transaction history I did a reindex with "checkpoints=0" with the version 2.4.0, so my blockchain folder has a size of approx. 116GB
- See attached file. The process defid reads with 280MB/s and in total 180GB without finishing to show up the transaction history. 
- <img width="963" alt="Bildschirmfoto 2021-06-02 um 06 54 13" src="https://user-images.githubusercontent.com/76392517/120435413-fabdc080-c37d-11eb-8d70-8a4147ae5c9e.png">

- After more than 1 hour the defid process read out 1,65TB and still loads with 275MB/s. (see screenshot 2)
- I coul download the transaction history, but all rewards on one specific address are missing...
<img width="961" alt="Bildschirmfoto 2021-06-02 um 08 37 07" src="https://user-images.githubusercontent.com/76392517/120435406-f85b6680-c37d-11eb-9987-c173e65d7cf4.png">

**Comment by izzycsy** [comment]
Hi @MaReCoding , in v2.4.2 storage has been optimised and should not take up that much any more (~12GB), can you try to `Reset & Reindex`? 

Settings > `Show wallet helper options` > `RESET & REINDEX`

<img width="782" alt="Reset   Reindex" src="https://user-images.githubusercontent.com/65014479/120486144-540e0a00-c3e7-11eb-8943-30e6bba97a19.png">

**Comment by nico89-exp** [comment]
I think checkpoints=0 setting re-increases the size. My disk is big enough so that doesn't matter to me.

For me the history issue is similar. The rewards and commissions (r&c) history is important for taxation reasons. So I want it back. 

Showing and exporting r&c in the app makes the app very slow. I can export at the end, but R&C are only included for one of my addresses, so several are missing. I think this is linked to the "listaccounthistory" issue in ain by Daniel.

**Comment by izzycsy** [comment]
Hi @nico89-exp , has it been reduced in the latest [v2.5.0](https://github.com/DeFiCh/app/releases/tag/v2.5.0)? Kindly remember to `backup wallet` before updating. 

<img width="269" alt="Menu bar   Backup Wallet" src="https://user-images.githubusercontent.com/65014479/121952002-3f8a2400-cd8e-11eb-9779-617f15cdb668.png">

**Comment by nico89-exp** [comment]
Hi @izzycsy   thanks for getting back. Discload is back to normal when showing transactions. However I still don’t get the full R&C history.

**Comment by izzycsy** [comment]
Hi @nico89-exp , can you try [v2.5.1](https://github.com/DeFiCh/app/releases/tag/v2.5.1), a kind reminder to `backup wallet` before updating. Several users have reported that their tx history is back. Regarding the issue [`Missing tx history`](https://github.com/DeFiCh/app/issues/891), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.
