### ISSUE TITLE
DFI not received

### ISSUE THREAD

**Issue by domedesign55** [DeFiCh/app#91]
hello. i have been missing DFI for several days. have not arrived on my DefiChain wallet. 

[app_log.log](https://github.com/DeFiCh/app/files/5647983/app_log.log)

[binary_log.log](https://github.com/DeFiCh/app/files/5647984/binary_log.log)

[app_config.zip](https://github.com/DeFiCh/app/files/5647988/app_config.zip)

**Comment by izzycsy** [comment]
Hi @domedesign55 , may I know what OS you're using? Could you describe your user flow more? Are you on Mainnet / Testnet? Screenshots would also help! We need more details in order investigate how to reproduce this issue. Thank you.

**Comment by domedesign55** [comment]
hello thanks for the feedback.

OS X EL Capitan Version 10.11.6

I am on Mainnet.

![0FE3E883-7DC4-471D-905E-4D6D1911DF65](https://user-images.githubusercontent.com/43755059/101503924-eec6e800-3972-11eb-8d0c-61dfe660db42.jpg)
![IMG_8281](https://user-images.githubusercontent.com/43755059/101503935-f1c1d880-3972-11eb-84ec-3c093527cbd2.jpg)
![IMG_8272](https://user-images.githubusercontent.com/43755059/101503948-f4bcc900-3972-11eb-9a8b-e07601c5ebb2.jpg)
![IMG_8275 (1)](https://user-images.githubusercontent.com/43755059/101503957-f71f2300-3972-11eb-8aa3-6d0a5ecd619b.jpg)
![IMG_8277](https://user-images.githubusercontent.com/43755059/101503973-fa1a1380-3972-11eb-8eec-f361ce3d2e9c.jpg)
![IMG_8282](https://user-images.githubusercontent.com/43755059/101503984-fdad9a80-3972-11eb-83e0-258dfeb4350e.jpg)

**Comment by izzycsy** [comment]
@domedesign55 , well noted, thank you for the explanation. Let us investigate this, thank you for your patience!

**Comment by domedesign55** [comment]
thank you! 

I have reinstalled the defi app.
synchronize has also worked.

862 defi have arrived! 
dfi send also works from dfi app.

only from cake, dfi send still does not go to defi app
this is the only problem yet.


![IMG_8291](https://user-images.githubusercontent.com/43755059/101783051-11cfd400-3afa-11eb-8f70-86f84f794152.jpg)
![22FB87D1-6D7D-490B-8DA5-08B4A365589C](https://user-images.githubusercontent.com/43755059/101783061-14322e00-3afa-11eb-8f81-c439abf60649.jpg)
![IMG_8289 (1)](https://user-images.githubusercontent.com/43755059/101783069-15fbf180-3afa-11eb-9265-f6d599e6ab14.jpg)
