### ISSUE TITLE
Last-page button for transaction history

### ISSUE THREAD

**Issue by dnamurphy** [DeFiCh/app#911]
#### Which feature is your request related to?
Inspecting transaction histories

#### Is your request related to a problem? Please describe.
No

#### Describe the solution you'd like:
- A button to move to the page containing the earliest transactions, when provided with the list of transactions made under a certain token (either under "Balances" or "Transactions")
- Please also consider moving (or replicating) the page forward/back controls to the top (above the transaction list) - this means users don't have to click, scroll-to-bottom, click, scroll-to-bottom to advance page by page

#### Describe alternatives you've considered: 
Current usage is to click repeatedly on the ">" button (after a scroll to the bottom of the page). 
The other alternative is to export to CSV and inspect outside of the wallet. 

#### Additional context:
There is currently a "newest transactions" button: |<  (ie. go to the first page)
Including an "oldest transaction" button that takes you to the final page would be both consistent in the current UI (where it is used in the toplevel listing of all tokens) and more user-friendly for those looking at earlier transactions.

Many thanks!

**Comment by izzycsy** [comment]
Hi @dnamurphy , thanks for your feedback, please give us time to investigate and consider the feature enhancement suggested.

**Comment by izzycsy** [comment]
Hi @dnamurphy , thanks for your feedback, may I suggest that you publish your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner some support from the community, and the team can decide whether to implement the feature in the future, as posting non-bug related issues here will eventually turn stale. Thank you!
