### ISSUE TITLE
2.4.4 - Masternodes do not show up after startup

### ISSUE THREAD

**Issue by defijeff** [DeFiCh/app#917]
#### Actual behavior:
After select Tab Masternodes, the own Masternodes are not shown in Mine.
This is the same issue as #901 in 2.4.1
There is no prompt to enter the password to unlock the wallet for 3yrs within the first minute after startup.
Reverting back to 2.4.3 works.

#### Expected behavior:
See all own Masternodes.

#### How to reproduce it (as minimally and precisely as possible):
See all own Masternodes.

#### What are your environment parameters?

DeFi Wallet Version: 2.4.4
Operating System (OS):Linux Appimage
– Current free storage capacity: - 

#### Anything else we need to know?

spv=0 is still set at the moment

**Comment by izzycsy** [comment]
Hi @defijeff , can you save your logs and send them for investigation please? Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/120749064-795d5e00-c536-11eb-8be5-af4181f74b48.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/120749075-7bbfb800-c536-11eb-9023-45b30692e726.png">

**Comment by defijeff** [comment]
Thanks, I'm aware I was using a pre-release version. I'm doing so because there were some fixes to generating blocks which were important, also I find it important to have more testers to get issues detected and resolved more quickly.

I've now updated to the release version of 2.4.4 and can confirm that it's now working. The prompt to enter the password comes up right away and the masternodes show.
