### ISSUE TITLE
Node 2.4.4 corrupt Database after snapshot 895284.zip

### ISSUE THREAD

**Issue by supervolot** [DeFiCh/app#919]
#### What are your environment parameters?

- DeFi Wallet Version: 2.4.4
- Operating System (OS): WIN10
– Current free storage capacity:

**Comment by izzycsy** [comment]
Hi @supervolot , please try again, we've updated the snapshot to begin at 893194.

**Comment by izzycsy** [comment]
Hi @supervolot , regarding the issue [`Sync Stuck`](https://github.com/DeFiCh/app/issues/910), if your issue persist, we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.
