### ISSUE TITLE
Mac: 2.4.5 unable to start blockchain

### ISSUE THREAD

**Issue by c8400** [DeFiCh/app#921]
Actual behavior: V2.4.4 on mac is unable to start the blockchain. The app doesn't want to close neither. I need to do a force close action.
[applogs.log](https://github.com/DeFiCh/app/files/6597670/applogs.log)e
[binary logs.log](https://github.com/DeFiCh/app/files/6597671/binary.logs.log)

 I've tried restarting my laptop with no luck.

What are your environment parameters?

- DeFi Wallet Version: 2.4.4
- Operating System (OS): Mac os Catalina
– Current free storage capacity: 83 GB

**Comment by supervolot** [comment]
I got my servers live again. I change to SPV=1 line in the defi.conf; and delete all folders (except "wallet") and start the wallet with snapshot 893149.zip

**Comment by izzycsy** [comment]
Hi @c8400 , the team is investigating on the issue. Please refer to [DeFiChain Announcements (EN)](https://t.me/defichain_announcements) for the latest update. Thank you.

**Comment by thedoublejay** [comment]
Hi @c8400, can you please try these steps?

1. Very important: Backup your wallet.dat (Make sure you have a copy of your wallet.dat)
2. Go to your Blockchain Folder (https://defichain-wiki.com/wiki/Blockchain_folder)
3. Delete all files and folders except wallets
4. Download v2.4.5 and install it (https://defichain.com/downloads/)
5. Once app starts, it will sync from scratch or force a re-index. You may download the latest snapshot (893149).
6. Sync from Snapshot

**Comment by c8400** [comment]
followed above steps.
The app loaded for a long time after downloading the snapshot.
Seems to work 100% again, thanks.
