### ISSUE TITLE
Windows: 2.4.5 Sync stalled

### ISSUE THREAD

**Issue by arnaudom** [DeFiCh/app#922]
After updating from 2.4.3, the synchronization seems to halt. Currently at block 894241.

The application log states:

> [2021-06-04 20:19:51.927] [IPC-MAIN-info]  [Starting Electron App] OS Windows 8.1 - 6.3.9600
> [2021-06-04 20:19:52.416] [IPC-MAIN-info]  Checking for update
> [2021-06-04 20:19:53.531] [IPC-RENDERER-info]   "[Starting App] App is running with version 2.4.4"
> [2021-06-04 20:19:53.896] [IPC-RENDERER-info]  [start] - Starting node connection...
> [2021-06-04 20:19:54.339] [IPC-RENDERER-info]  Current Node: 1.7.6 New Node: 1.7.6
> [2021-06-04 20:19:54.685] [IPC-RENDERER-info]  [setLockTimeout] "Starting update of lock timeout..."
> [2021-06-04 20:19:55.138] [IPC-RENDERER-info]  [Update Auto-lock Time] "Timeout updated to 300 seconds"
> [2021-06-04 20:19:57.003] [IPC-RENDERER-info]  [start] - Node start initiated
> [2021-06-04 20:19:57.582] [IPC-RENDERER-info]  [start] - Node started
> [2021-06-04 20:19:58.107] [IPC-RENDERER-info]  [start] - Sending node started to client
> [2021-06-04 20:19:58.721] [IPC-RENDERER-info]  Update for version 2.4.4 is not available (latest version: 2.4.4, downgrade is disallowed).
> [2021-06-04 20:19:59.420] [IPC-RENDERER-debug] checkForUpdatesAndNotify called, downloadPromise is null
> [2021-06-04 20:20:02.086] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
> [2021-06-04 20:20:04.062] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
> [2021-06-04 20:20:06.061] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
> [2021-06-04 20:20:08.061] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
> [2021-06-04 20:20:10.066] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
> [2021-06-04 20:20:12.061] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
> [2021-06-04 20:20:14.063] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
> [2021-06-04 20:20:16.065] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
> [2021-06-04 20:20:19.274] [IPC-RENDERER-info]  [Blockchain Status] "blockchain started successfully"
> [2021-06-04 20:20:27.756] [IPC-RENDERER-error]  "Request failed with status code 400"
> [2021-06-04 20:20:40.705] [IPC-RENDERER-error] [getBlockSyncInfo] "Request failed with status code 503"
> [2021-06-04 20:20:42.342] [IPC-RENDERER-error] [getBlockSyncInfo] "Request failed with status code 503"

- DeFi Wallet Version: 2.4.4
- Operating System (OS): windows
– Current free storage capacity: 317GB

**Comment by supervolot** [comment]
My 2.4.3 stopps Synchronizing at 99.84% ; after update to 2.4.4. Database is corrupt and Snapshot dont work

**Comment by supervolot** [comment]
I got my servers live again. I delete the SPV=0 line in the defi.conf

**Comment by nippur72** [comment]
I had the same issue and did as @supervolot suggested, wallet is now functional

**Comment by izzycsy** [comment]
Hi @arnaudom @nippur72 @supervolot , the team is working on the issue. Please refer to [DeFiChain Announcements (EN)](https://t.me/defichain_announcements) for the latest update. Thank you.

**Comment by ian309699** [comment]
I did the v2.4.4 update and now it says it is Unable to start blockchain. I have included my app logs. Hopefully they help
[APP LOGS.log](https://github.com/DeFiCh/app/files/6601089/APP.LOGS.log)

**Comment by Faucet1313** [comment]
Had the same issue guys the upgrade to 2.4.5 fixed the issue for me.

**Comment by nippur72** [comment]
I now upgraded to 2.4.5, clean starting from snapshot and it is working OK

**Comment by itmlgife** [comment]
Hi, Win10 when I upgraded from 2.4.4 to 2.4.5 I got unable to start blockchain. The debug.log file included the error below so I cleared the blockchain folder and re-installed the app. After the sync, everything appears to be fine.

Logs attached.
[debug.345.zip](https://github.com/DeFiCh/app/files/6601533/debug.345.zip)


021-06-04T22:08:37Z UpdateTip: new best=c5441f584f467a797f3b0391ec9dbd65ad2925bb3853063d4f272e916d2dd3c6 height=870946 version=0x20000000 log2_work=80.953083 tx=2957959 date='2021-05-24T10:39:09Z' progress=0.941848 cache=0.0MiB(8txo)
2021-06-04T22:08:37Z ERROR: ConnectBlock(): ApplyCustomTx on 7f0c2d4aba26e74b61264f8de2b23c754db24953f6b0f62315c0b9b67683cd98 failed with AddPoolLiquidityTx: Exceeds max ratio slippage protection of 3%
2021-06-04T22:08:37Z ERROR: ConnectTip: ConnectBlock 2e5b7ca1c1c6301f720d36a0dd15e574dfbd23bd309bb3b09697c0b7ebec62b0 failed,  (code 0)
2021-06-04T22:08:37Z Failed to connect best block ( (code 0))
2021-06-04T22:08:37Z tor: Thread interrupt
2021-06-04T22:08:37Z addcon thread exit
2021-06-04T22:08:37Z torcontrol thread exit
2021-06-04T22:08:37Z opencon thread exit
2021-06-04T22:08:37Z dnsseed thread exit
2021-06-04T22:08:37Z Shutdown: In progress...
2021-06-04T22:08:37Z net thread exit
2021-06-04T22:08:37Z msghand thread exit
2021-06-04T22:08:38Z scheduler thread interrupt
2021-06-04T22:08:38Z [wallet.dat] Releasing wallet
2021-06-04T22:08:38Z Shutdown: done

**Comment by GM82b** [comment]
[app logs.zip](https://github.com/DeFiCh/app/files/6601552/app.logs.zip)
Unable to start blockchain. The app stucked after upgrade to 2.4.5 and then don't restart. All was fine till 2.4.4

**Comment by John-Gee** [comment]
@supervolot 's way worked here as well, as it did yesterday with 2.4.4. 
I'm not on Windows, so this does not seem related to the OS.

**Comment by itmlgife** [comment]
> @supervolot 's way worked here as well, as it did yesterday with 2.4.4.
> I'm not on Windows, so this does not seem related to the OS.

I confirm that worked for me as well. I did it on Win 10.

**Comment by izzycsy** [comment]
Hi @GM82b , well received, please give us time to investigate.

**Comment by arnaudom** [comment]
I upgreded to v2.4.5.
Looks like there is still an error with sync connection. Hanging at block 894310.

[2021-06-05 08:09:34.684] [IPC-RENDERER-info]   "[Starting App] App is running with **version 2.4.5**"
[2021-06-05 08:09:35.303] [IPC-RENDERER-info]  [start] - Starting node connection...
[2021-06-05 08:09:35.875] [IPC-RENDERER-info]  Current Node: 1.7.6 New Node: 1.7.7
[2021-06-05 08:09:36.503] [IPC-RENDERER-info]  [setLockTimeout] "Starting update of lock timeout..."
[2021-06-05 08:09:39.173] [IPC-RENDERER-info]  [start] - Node start initiated
[2021-06-05 08:09:39.619] [IPC-RENDERER-info]  [start] - Node started
[2021-06-05 08:09:40.116] [IPC-RENDERER-info]  [start] - Sending node started to client
[2021-06-05 08:09:40.635] [IPC-RENDERER-info]  Update for version 2.4.5 is not available (latest version: 2.4.5, downgrade is disallowed).
[2021-06-05 08:09:41.175] [IPC-RENDERER-debug] checkForUpdatesAndNotify called, downloadPromise is null
[2021-06-05 08:09:41.746] [IPC-RENDERER-info]  [Update Auto-lock Time] "Timeout updated to 300 seconds"
[2021-06-05 08:09:44.316] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
[2021-06-05 08:09:46.313] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
[2021-06-05 08:09:48.308] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
[2021-06-05 08:09:50.307] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
[2021-06-05 08:09:52.309] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
[2021-06-05 08:09:54.309] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
[2021-06-05 08:09:56.307] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
[2021-06-05 08:09:58.308] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
[2021-06-05 08:10:00.309] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 500"
[2021-06-05 08:10:02.684] [IPC-RENDERER-info]  [Blockchain Status] "blockchain started successfully"
[2021-06-05 08:10:25.603] [IPC-RENDERER-error]  "**Request failed with status code 400**"

**Comment by ian309699** [comment]
I just did the v2.4.5 update, and the same thing..Unable to start blockchain. I downloaded the logs again
[AppLogs.log](https://github.com/DeFiCh/app/files/6601815/AppLogs.log)

**Comment by EtudAHART** [comment]
I also recently updated to 2.4.4. and begun to receive the "Unable to start blockchain" error.  I updated to 2.4.5 in hopes this would fix the error but I am still receiving. Thank you for any guidance. 
[AppLog.log](https://github.com/DeFiCh/app/files/6601841/AppLog.log)

**Comment by aasmck** [comment]
After the update, I also receive the error message Unable to the blockchain. Nothing works anymore. Mac storage space enough, I hope we can be helped. During synchronization, the node was disconnected immediately. Nothing opens after closing the app and restarting the wallet. Blockchain cannot be started, will then be displayed as an error! I've already uninstalled and play the app, always the same

**Comment by thedoublejay** [comment]
Hi @GM82b, can you delete your debug.log in your wallet app and try to restart the app?

**Comment by thedoublejay** [comment]
Hi @ian309699 and @EtudAHART, can you please provide us with your debug.log/binary.log? Thank you

**Comment by thedoublejay** [comment]
For all users who are facing the "Unable to Start Blockchain" issue. You may do these steps:
1. Very important: Backup your wallet.dat (Make sure you have a copy of your wallet.dat)
2. Go to your Blockchain Folder (https://defichain-wiki.com/wiki/Blockchain_folder)
3. Delete all files and folders except wallets
4. Download v2.4.5 and install it (https://defichain.com/downloads/)
5. Once app starts, it will sync from scratch or force a re-index. You may download the latest snapshot (893149).
6. Sync from Snapshot

**Comment by arnaudom** [comment]
My latest attempt:

- select "reindex wallet" from menu;
- stop and restarted the application;
- downloaded the snapshot directly from [address 893149.zip](https://defi-snapshots-europe.s3.eu-central-1.amazonaws.com/snapshot-mainnet-893149.zip)  - the wallet did not proposed the download when resyncing from 0;
- upacked into chain folder;
- restarted wallet after unpacked;

the synchronization did restart as normal. I noticed some delays at blk 893410 if this is relevant.

**Comment by thedoublejay** [comment]
@arnaudom yes there might be some delay. How's your syncing now? Did it go past 839410?

**Comment by arnaudom** [comment]
@thedoublejay yes 100% now. Thank you.

**Comment by GM82b** [comment]
> Hi @GM82b, can you delete your debug.log in your wallet app and try to restart the app?

this doesn't work. Then i deleted folder and reinstalled and now it works. Thanks

**Comment by EtudAHART** [comment]
> @EtudAHART, can you please provide us with your debug.log/binary.log? Thank you

@thedoublejay thedoublejay 
[Binary Log.log](https://github.com/DeFiCh/app/files/6602523/Binary.Log.log)
[AppLog.log](https://github.com/DeFiCh/app/files/6602524/AppLog.log)

Thank you for your help.

**Comment by itmlgife** [comment]
> Hi, Win10 when I upgraded from 2.4.4 to 2.4.5 I got unable to start blockchain. The debug.log file included the error below so I cleared the blockchain folder and re-installed the app. After the sync, everything appears to be fine.
> 
> Logs attached.
> [debug.345.zip](https://github.com/DeFiCh/app/files/6601533/debug.345.zip)
> 
> 021-06-04T22:08:37Z UpdateTip: new best=c5441f584f467a797f3b0391ec9dbd65ad2925bb3853063d4f272e916d2dd3c6 height=870946 version=0x20000000 log2_work=80.953083 tx=2957959 date='2021-05-24T10:39:09Z' progress=0.941848 cache=0.0MiB(8txo)
> 2021-06-04T22:08:37Z ERROR: ConnectBlock(): ApplyCustomTx on 7f0c2d4aba26e74b61264f8de2b23c754db24953f6b0f62315c0b9b67683cd98 failed with AddPoolLiquidityTx: Exceeds max ratio slippage protection of 3%
> 2021-06-04T22:08:37Z ERROR: ConnectTip: ConnectBlock 2e5b7ca1c1c6301f720d36a0dd15e574dfbd23bd309bb3b09697c0b7ebec62b0 failed, (code 0)
> 2021-06-04T22:08:37Z Failed to connect best block ( (code 0))
> 2021-06-04T22:08:37Z tor: Thread interrupt
> 2021-06-04T22:08:37Z addcon thread exit
> 2021-06-04T22:08:37Z torcontrol thread exit
> 2021-06-04T22:08:37Z opencon thread exit
> 2021-06-04T22:08:37Z dnsseed thread exit
> 2021-06-04T22:08:37Z Shutdown: In progress...
> 2021-06-04T22:08:37Z net thread exit
> 2021-06-04T22:08:37Z msghand thread exit
> 2021-06-04T22:08:38Z scheduler thread interrupt
> 2021-06-04T22:08:38Z [wallet.dat] Releasing wallet
> 2021-06-04T22:08:38Z Shutdown: done

Hi Bella, I would like to provide additional context on this. Yesterday I cleared the blockchain folder and re-installed the application and re-synced using the snapshot. This morning the app is again not loading things. The debug.log file shows new errors.

The latest errors look like:
2021-06-05T14:09:27Z InvalidChainFound: invalid block=361b0c48661bf1788c5726d11b6a9a3ca0bd3d5515791fac0313184eafccc981  height=897817  log2_work=81.061502  date=2021-06-05T11:27:11Z
2021-06-05T14:09:27Z InvalidChainFound:  current best=23b898955ce546ff910fb19a86d3bdc1c320a96e7e55233603d2facd05e8c6bd  height=897816  log2_work=81.0615  date=2021-06-05T11:30:54Z
2021-06-05T14:09:27Z ERROR: ConnectTip: ConnectBlock 361b0c48661bf1788c5726d11b6a9a3ca0bd3d5515791fac0313184eafccc981 failed, high-hash, proof of stake failed (code 16)

I am attaching the log:
[debug.zip](https://github.com/DeFiCh/app/files/6602651/debug.zip)

**Comment by ian309699** [comment]
@thedoublejay I did the steps you suggested and the blockchain has been stuck at 897865 for over 12 hrs  now

**Comment by EtudAHART** [comment]
@thedoublejay  I found the proper blockchain folder and followed your instructions. Syncing now. Thank you once again.

**Comment by ian309699** [comment]
@thedoublejay I started over and did the steps you suggested again, it has synced and my addresses are all there. It works 100% now.
Thank You
