### ISSUE TITLE
Unable to Start Blockchain mac 2.4.5 

### ISSUE THREAD

**Issue by aasmck** [DeFiCh/app#926]
Bei der Synchronisierung wurde der Knoten sofort getrennt. Nach dem Schließen der App und dem Neustart der Brieftasche öffnet sich nichts. Blockchain kann nicht gestartet werden, wird dann als Fehler angezeigt! Ich habe die App bereits deinstalliert und wiedergeben, immer dasselbe, bitte helfen Sie mir

**Comment by thedoublejay** [comment]
Hi @aasmck, there's been an issue reported for this. We're currently investigating it. Thank you

**Comment by thedoublejay** [comment]
Hi @aasmck, you may follow these steps:

1. Very important: Backup your wallet.dat (Make sure you have a copy of your wallet.dat)
2. Go to your Blockchain Folder (https://defichain-wiki.com/wiki/Blockchain_folder)
3. Delete all files and folders except wallets
4. Download v2.4.5 and install it (https://defichain.com/downloads/)
5. Once app starts, it will sync from scratch or force a re-index. You may download the latest snapshot (893149).
6. Sync from Snapshot

**Comment by aasmck** [comment]
Thanks, it's running again. I hope it's going a little more stable again now
