### ISSUE TITLE
rewards missing

### ISSUE THREAD

**Issue by helhimm** [DeFiCh/app#929]
Since Yesterday it seems that reards on DEX are missing , I should get apr 83 DFI on rewards for the day however its only about 60 DFI showing. Please investigate and let me know what's going on.

**Comment by happydayxxl** [comment]
Same here the rewards not matching to the apy

**Comment by izzycsy** [comment]
Hi @happydayxxl , you can refer to this link to understand why: https://youtu.be/rx5aO4lN-y0?t=655

For future why-enquiries, you may ask on [DeFiChain Telegram (EN)](https://t.me/defiblockchain).

[v2.5.1](https://github.com/DeFiCh/app/releases/tag/v2.5.1) is out. Please read through the release notes before updating. `Backup wallet` before updating, thank you.
