### ISSUE TITLE
How to using more than 1 wallet to single defi wallet

### ISSUE THREAD

**Issue by angelocastiglione** [DeFiCh/app#930]
I am using more than 1 wallet on my defi wallet app and for change wallet I change manually defi.conf files

Each defi.conf file contain the information to login to a single wallet

Example defi.conf (1)
rpcauth=AAAAA
rpcuser=AAAAA
rpcpassword=123
wallet=Wallet1
walletdir=/home/angelo/wallet1

Example defi.conf (2)
rpcauth=BBBBB
rpcuser=BBBBB
rpcpassword=456
wallet=Wallet2
walletdir=/home/angelo/wallet2

For sent and receive dfi i dont have any issue, also I am using dex and liquidity without issue, but when I using pre-fun txns function automatically sent 0.01 to all my wallet (wallet 1 + wallet 2 + wallet 3 + wallet 4 etc etc) not only the current wallet that i am using. I dont know where defi wallet save my own address that I have used.

There are better solution for admin more than 1 wallet separately ? If is possible I dont want to run more virtual machine

Thanks for suggestion

![utxo](https://user-images.githubusercontent.com/82758166/120898979-a17bb880-c62d-11eb-8afb-7769d65bbd9b.png)

**Comment by izzycsy** [comment]
Hi @angelocastiglione , here's how you can run more than 1 wallet on the same app. For example, you're on wallet 1, and want to go to wallet 2: 

1. Click `Exit Wallet` icon 
<img width="236" alt="Exit Wallet" src="https://user-images.githubusercontent.com/65014479/120934352-9c536200-c730-11eb-95ca-1a965f349b40.png">

2. You should be prompted to `Backup Wallet` 1, kindly backup then exit

<img width="498" alt="BACKUP   EXIT" src="https://user-images.githubusercontent.com/65014479/120934508-12f05f80-c731-11eb-8b39-9be3618bb871.png">


3. After backing up, `Restore wallet via backup` > Select wallet 2's `wallet.dat`

<img width="1021" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/120934365-b1c88c00-c730-11eb-9650-ca179c765866.png">

Continue using wallet 2 from there. Thank you.

You may turn to DeFiChain’s telegram for how-to related issues: 
[DeFiChain Telegram (EN)](https://t.me/defiblockchain)
