### ISSUE TITLE
debug.log file gets to big (>25GB)

### ISSUE THREAD

**Issue by Darkman-Q-Tester** [DeFiCh/app#931]
While having issues with my update to 2.4.5 I checked my Blockchain folder and found the debug.log file is huge (>25GB).
I created a zip file and it is still 191MB.

I have enough SSD space but I guess this debug.log file should never get that big.

DeFi Wallet Version: 2.4.5
Operating System (OS): windows 10 Pro 20H2 (Build 19042.985)

![grafik](https://user-images.githubusercontent.com/77509687/120916690-4ab4c400-c6ab-11eb-9b5b-67cc63926c35.png)

**Comment by nordi6000** [comment]
At me the same 157 GB with Wallet 2.4.0
![image](https://user-images.githubusercontent.com/49670309/120929341-01836500-c6e9-11eb-8615-e0b33d91142c.png)

**Comment by izzycsy** [comment]
Hi @Darkman-Q-Tester , thanks for your feedback, please give us time to investigate. 

@nordi6000 , thanks as well, please backup you wallet and update to the latest [v2.4.5](https://github.com/DeFiCh/app/releases/tag/v2.4.5) in the meantime.

**Comment by nordi6000** [comment]
@izzycsy okay, I have install wallet v2.4.5

**Comment by thedoublejay** [comment]
Hi @nordi6000  @Darkman-Q-Tester, older versions of node <1.7.7 causes loop in some parts of the code causing huge binary logs. If you use v2.4.5, you may delete your current debug.log as it will be re-created.

**Comment by Darkman-Q-Tester** [comment]
Yes, clear, Logfile deleted and new one was created. Fine for me.

**Comment by thedoublejay** [comment]
Thanks for the update. This will be fixed for new node versions. In case you encounter this, feel free to delete the debug.log and it will be re-created.
