### ISSUE TITLE
Oh no! The network error is back!

### ISSUE THREAD

**Issue by Faucet1313** [DeFiCh/app#937]
#### Actual behavior:

Hi, 

The network error and balance failure is back. Today i got a bad surprise when i checked my server i saw this network error again. This time it does not corrupt the blockchain i just restarted the client and it seem to work now. It is very similar to [#849](https://github.com/DeFiCh/app/issues/849)

Edit: After restarting the client have trouble while syncing. Block is not really stuck but the client not fully syncing 100% since few hours. 
![sync](https://user-images.githubusercontent.com/83678739/120941008-aa998200-c720-11eb-88c4-8527d5680154.png)

![Networkerror](https://user-images.githubusercontent.com/83678739/120934069-27b30000-c6fd-11eb-8010-46f12adf3597.png)

[app.log](https://github.com/DeFiCh/app/files/6604604/app.log)

#### What are your environment parameters?

- DeFi Wallet Version: 2.4.5
- Operating System (OS): Windows server 2016
– Current free storage capacity: 200GB

**Comment by izzycsy** [comment]
Hi @Faucet1313 , thanks for your feedback, please give us time to investigate.

**Comment by thedoublejay** [comment]
Hi @Faucet1313, can we get your debug/binary log? Thank you

**Comment by Faucet1313** [comment]
Hi @thedoublejay, Sure here you go. By the way i just got the error again.
[debug.log](https://github.com/DeFiCh/app/files/6612704/debug.log)

**Comment by supervolot** [comment]
Same bug on my 2 server on WIN 2019 after running the app a day

**Comment by Faucet1313** [comment]
Running the 2.5.0 ALPHA1 since yesterday with no issue. Im now updating to the 2.5.0 final.

**Comment by thedoublejay** [comment]
Thanks for the update @Faucet1313!

**Comment by Faucet1313** [comment]
Hi, @thedoublejay, @izzycsy. Same issue with the 2.5.0
![2 5 0](https://user-images.githubusercontent.com/83678739/121415646-4406a500-c968-11eb-9475-b8a8bf35514f.png)
[debug.log](https://github.com/DeFiCh/app/files/6626344/debug.log)
[app.log](https://github.com/DeFiCh/app/files/6626355/app.log)

**Comment by izzycsy** [comment]
Hi @Faucet1313 , can you try the latest version [v2.5.1](https://github.com/DeFiCh/app/releases/tag/v2.5.1). Please `backup wallet` before updating. Thank you.

**Comment by Faucet1313** [comment]
Hi @izzycsy, Running the 2.5.1 with firewall ON since 3-4 days. I just updated to the 2.5.2

**Comment by izzycsy** [comment]
Hi @Faucet1313 , thanks for the update, I'll be closing the issue. If it occurs again, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
