### ISSUE TITLE
Wallet-recovery via seed failed

### ISSUE THREAD

**Issue by lJay-Jayl** [DeFiCh/app#941]
#### Actual behavior: 
If I try to recover my wallet with my seed words it shows a complete false state of my assets.

#### Expected behavior: 
Complete restore of all funds.

#### How to reproduce it (as minimally and precisely as possible): 
Reinstall of the DeFi wallet app on a new Windows System. 100% Sync of the Blockchain and restore wallet with seed. Tryed it two times.
If I use the Backup-File my wallet shows the right ammount and all Assets.

#### What are your environment parameters?

- DeFi Wallet Version: 2.4.5
- Operating System (OS): Windows 10 (20H2)
– Current free storage capacity: 728 GB

**Comment by thedoublejay** [comment]
Hi @lJay-Jayl, your wallet.dat/backup is encrypted therefore it has a different private key than the mnemonic seed.

**Comment by lJay-Jayl** [comment]
Hi @thedoublejay, is there a way to restore my "encrypted" wallet with a seed? Can I get the seed for my current encrypted wallet?
Kind regards
Jay-Jay

**Comment by izzycsy** [comment]
Hi @lJay-Jayl , no mnemonic seed and wallet.dat are separate ways to restore your wallet. By restoring with mnemonic seed, your wallet will display the amounts before encryption (setting your wallet passphrase) began. By restoring via wallet backup (wallet.dat), your wallet will display balanced after encryption, hence it's good to make backups every once in a while.

**Comment by lJay-Jayl** [comment]
@izzycsy, thx for the detailed explaination. Now I got it. 
A short hint in the App could be usefull. (mnemonic seed only for unencrypted wallets...) and a restore for encrypted wallets is only via backed up wallet.dat possible...

Thx to DeFi-Team for the quick help.

Kind regards
Jay-Jay

**Comment by izzycsy** [comment]
Hi @lJay-Jayl , thanks for your feedback. DeFi Wallet does not have this feature at the moment but you may open on on GitHub Discussions <https://github.com/DeFiCh/app/discussions> and we can discuss from there; along with the community. 

For future how-to related issues, you may ask to DeFiChain’s telegram [DeFiChain Telegram (EN)](https://t.me/defiblockchain) the community would definitely help explain!
