### ISSUE TITLE
DeFi Wallet V.2.4.5 - Unable to start blockchain

### ISSUE THREAD

**Issue by Stressfrei** [DeFiCh/app#942]
[app log.zip](https://github.com/DeFiCh/app/files/6607468/app.log.zip)

#### Actual behavior:
I can't open the DeFi App with the failure: Unable to start blockchain

#### Expected behavior:
I have deinstall and reinstall the app. The same problem

#### How to reproduce it (as minimally and precisely as possible):
Start the app

#### What are your environment parameters?

- DeFi Wallet Version:  2.4.5
- Operating System (OS): Windows 10 Pro - Windows Feature Experience Pack 120.2212.2020.0
– Current free storage capacity: 304GB

#### Anything else we need to know?
Log files attached

**Comment by izzycsy** [comment]
Hi @Stressfrei , here's how you can [reinstall](https://github.com/DeFiCh/app/issues/922#issuecomment-855181098). Please backup your `wallets` folder before deleting anything. Regarding the issue [`Windows: 2.4.5 Sync stalled #922`](https://github.com/DeFiCh/app/issues/922), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.
