### ISSUE TITLE
Add liquidity to LP not valid --> amount of coins in Wallet ist not shown correctly in DefiWallet App

### ISSUE THREAD

**Issue by seb18781** [DeFiCh/app#943]
#### Actual behavior:

There is a #BUG in calculating amounts of coins: Please see the following transaction: https://mainnet.defichain.io/#/DFI/mainnet/tx/62cb53cdad8eb5c4eaebf07e647f04d55a3d1dca55d401dc41691a55367cc5e3

https://dex.defichain.com/mainnet/tx/62cb53cdad8eb5c4eaebf07e647f04d55a3d1dca55d401dc41691a55367cc5e3

The Transaction was not valid (skipped), but I have not got my coins back.

![image](https://user-images.githubusercontent.com/69623583/120996198-68a32700-c786-11eb-97d4-b0972552030a.png)

#### Expected behavior:

The calculated amount of coins shown in the DefiWallet should incorporate coins which were not sent correctly and are thus still in your wallet.

#### How to reproduce it (as minimally and precisely as possible):

please see links above

#### What are your environment parameters?

- DeFi Wallet Version: 2.4.5
- Operating System (OS): Win10
– Current free storage capacity: >50GB

#### Anything else we need to know?

-

**Comment by seb18781** [comment]
I think, this issue could be linked with #925

**Comment by izzycsy** [comment]
Hi @seb18781 , can you further elaborate on the issue you're facing? You added liquidity (dBTC-DFI) in the app and the amount is not reflected on your wallet? Regarding the issue https://github.com/DeFiCh/app/issues/925, we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.

**Comment by seb18781** [comment]
the issue was merged with #925
