### ISSUE TITLE
After reinstallation, dETH and dETH/DFI not showing

### ISSUE THREAD

**Issue by jaspo77** [DeFiCh/app#945]
My dETH and dETH/DFI liquidity are missing after updating to 2.4.5

####Actual behavior: My dETH and dETH/DFI liquidity pool holdings are gone.

####Expected behavior:  The correct amount of both should appear

#### How to reproduce it (as minimally and precisely as possible):

1. Uninstall prior version to 2.4.5, including all associated files.
2. Install 2.4.5
3. Restore wallet via mnemonic phrase words
4. Dowload snapshot and restart app.
5. Wait for the sync to complete.

#### What are your environment parameters?

- DeFi Wallet Version: 2.4.5
- Operating System (OS): macOS Catalina
[missingETH_logs.zip](https://github.com/DeFiCh/app/files/6612192/missingETH_logs.zip)

– Current free storage capacity:  228/479 GB

**Comment by izzycsy** [comment]
Hi @jaspo77 , you need to restore via wallet backup for the right balance to appear due to your wallet being encrypted. 

<img width="1021" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/121150579-3bce3d00-c876-11eb-9d54-567a95c8f0b1.png">
