### ISSUE TITLE
Bitcoins not arrived

### ISSUE THREAD

**Issue by Spiddey** [DeFiCh/app#953]
Hi there, I clicked under "Guthaben" onto Bitcoin, then onto "Empfangen" and used that address to send me bitcoin from Bittrex. The coins have not arrived. Whats the issue here?

**Comment by izzycsy** [comment]
Hi @Spiddey , coins being sent to DeFi Wallet is wrapped — dBTC in your case. Currently you can only send BTC via Cakedefi, which upon arrival to DeFi Wallet will be wrapped to dBTC. Likewise, when you send it back to your exchange, it'll be DeFi Wallet > Cakedefi > Bittrex. Only DFI can be directly sent from Bittrex (or any other exchange that supports it). 

You may turn to DeFiChain’s telegram for how-to related issues: 
[DeFiChain Telegram (EN)](https://t.me/defiblockchain)

**Comment by Spiddey** [comment]
So bad! so how do I get my Bitcoins sent from Bittrex that should have been credited onto my Defi Chain Wallet back to the Bittrex Account then? Can you help me out in this matter?

**Comment by izzycsy** [comment]
Hi @Spiddey , we do not have control over exchanges and the team does try to prompt them to reopen their services. This will likely answer your doubts: https://www.youtube.com/watch?v=rx5aO4lN-y0
