### ISSUE TITLE
Snapshot not install if change the blochckain data folder

### ISSUE THREAD

**Issue by angelocastiglione** [DeFiCh/app#955]
- DeFi Wallet Version: 2.5.0
- Operating System (OS): Windows 10
– Current free storage capacity: 500GB

If change the directory of the blockchain data using command on defi.conf

datadir=D:\DeFi Blockchain

The snapshot is not working because is donwloaded on the old folder 

C:\Users\<username>\AppData\Roaming\DeFi Blockchain

and is not installed on "D:\DeFi Blockchain"

**Comment by izzycsy** [comment]
Hi @angelocastiglione , should you need to switch directory for the DeFi Wallet, this source might help: https://defichain-wiki.com/wiki/Blockchain_folder

By default it's store in the C: drive for Windows. Always `backup wallet` before proceeding with moving of folders etc. 

<img width="269" alt="Menu bar   Backup Wallet" src="https://user-images.githubusercontent.com/65014479/121924196-40ab5900-cd6e-11eb-889b-f90ff4618676.png">

You need not save the snapshot as its purpose is to help you sync to 100% faster, to understand more you may refer to: https://github.com/DeFiCh/app/discussions/899

**Comment by angelocastiglione** [comment]
Yes i have follow the guide https://defichain-wiki.com/wiki/Blockchain_folder

I have changed the defi.conf and using this command

"datadir=D:\DeFi Blockchain"

And using this command the blochain data will download at this new path D:\DeFi Blockchain

But if I try to donwload the snapshot, will donwload to old directory on C: and not install to new path

**Comment by memzila** [comment]
hi @angelocastiglione . Where have you put the datadir setting. Before the main section or in the main section?
I have mine before the main section and it has downloaded the snapshot in a subfolder in the defichain folder from the the datadir setting. I'm working on windows.

.....
datadir=D:\DefiWallet\Chain
checkpoints=629500

[main]
rpcbind=127.0.0.1
rpcport=8555
.....

**Comment by angelocastiglione** [comment]
Ok thanks for the info.

**Comment by izzycsy** [comment]
Hi @angelocastiglione , has your issue been resolved?

**Comment by izzycsy** [comment]
Hi @angelocastiglione , update [v2.6.0](https://github.com/DeFiCh/app/releases/tag/v2.6.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @angelocastiglione , update [v2.6.2](https://github.com/DeFiCh/app/releases/tag/v2.6.2) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @angelocastiglione , update [v2.6.3](https://github.com/DeFiCh/app/releases/tag/v2.6.3) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @angelocastiglione , update [v2.7.0](https://github.com/DeFiCh/app/releases/tag/v2.7.0) is out, this is a **mandatory update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @angelocastiglione , regarding the issue [`Changing snapshot folder`](https://github.com/DeFiCh/app/issues/1072), we can further discuss on the issue there. We would like to keep related issues in one thread. Thank you.
