### ISSUE TITLE
Splippage impact on dex trade

### ISSUE THREAD

**Issue by angelocastiglione** [DeFiCh/app#956]
It would be very convenient if of the dex trade the impact of the expected slippage was indìcated.

Also if a maximum % of slippage could also be set.

Have any suggestion?

**Comment by izzycsy** [comment]
Hi @angelocastiglione , non-bug issues will turn stale, for future feature improvement related ideas, you can publish it on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner some support from the community, and the team can decide whether to implement the feature in the future. I'd suggest that you move this to Github Discussions. Thank you!
