### ISSUE TITLE
Can't sign TX

### ISSUE THREAD

**Issue by Rafa-el08** [DeFiCh/app#958]
#### Actual behavior: Send transaction today twice from Defi-Wallet to Cakedefi which were not processed. Although the transaction is reported on the chain it is not executed (and not documented under transactions in the Defi Wallet).

At the same time I receive the following error message in the Konsole when trying to switch tokens into coins: Can't sign TX: [{"txid":"17bb994871ed87d654295014400e51892a74b15517549da21b084290b00052c1","vout":1,"witness":[],"scriptSig":"1600146b03c3cfa5683e3bd7ff577bf431595cd85ef9d6","sequence":4294967295,"error":"Witness program hash mismatch"}]

#### How to reproduce it (as minimally and precisely as possible): 
I tried again and entered the same transfer another time. Again no result. I then posed the issue on Telegram - where I was answered by a scammer (see security issue that i posed).

#### What are your environment parameters?

- DeFi Wallet Version: 2.4.5
- Operating System (OS): 10.15.7
– Current free storage capacity: 
[2021-06_DefiChain_Überweisung.pdf](https://github.com/DeFiCh/app/files/6642839/2021-06_DefiChain_Uberweisung.pdf)

**Comment by izzycsy** [comment]
Hi @Rafa-el08 , I'm assuming this [ticket](https://github.com/DeFiCh/app/issues/957) belongs to you, one with the logs and one without. Regarding error message `Can't sign TX` — your transaction did not went through, it might you've [insufficient utxoDFI](https://github.com/DeFiCh/app/discussions/846). Try sending yourself 1DFI and try again. 

And yes, good that you spotted scammer, the team will never send you a DM on Telegram.

**Comment by izzycsy** [comment]
Hi @Rafa-el08 , regarding the issue [`Can't sign tx`](https://github.com/DeFiCh/app/issues/982), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.
