### ISSUE TITLE
Wallet unlocking and adding to LP, clunky interface

### ISSUE THREAD

**Issue by ck-kc** [DeFiCh/app#962]
Which feature is your request related to?

UX issue

Is your request related to a problem? Please describe.

Add to LP steps (wallet locked:)
1) Select 'Liquidity' from left hand menu
2) Click on '+' by chosen LP 'Add or remove liquidity' column
3) Select amounts and click 'Continue'
4) Wallet locked message appears
5) Unlock wallet with password
6) You are returned to the start and have to repeat all the steps.

#### Describe the solution you'd like:

Don't reset selected LP pair and quantities after unlocking wallet

**Comment by izzycsy** [comment]
Hi @ck-kc , thanks for your feedback, posting non-bug related issues here will eventually turn stale. You can publish your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner some support from the community, and the team can decide whether to implement the feature in the future. The price of the liquidity poolPairs before adding is time sensitive hence a reset if you fall out the timeout. However, you can increase the wallet timeout to 60minutes to prevent an auto-timeout in the future. Your feedback is well received, thank you!

**Comment by ck-kc** [comment]
Timeout is not what I was referring to. I was referring to the situation
where the wallet is locked to begin with.
