### ISSUE TITLE
DFI transaction stuck since more than a week now. Transactions do not seem to be safe.

### ISSUE THREAD

**Issue by CryptoCHBS** [DeFiCh/app#963]
#### Actual behavior: At the 6th of June I wanted to send some DFI to my Cake wallet. First, the transaction failed, because the block duration was almost 10 min at this time and my wallet was already locked again, once the transaction was ready to be processed.
I tried it again later and the transaction was shown as successful. My account balance was reduced by the transaction amount.
 
However, my DFI never reached my CAKE wallet, where I sent it to. Below you can see the transaction from my log file (see entire log file attached). I have double checked my cake address and it is correct. Unfortunately I cannot see any transactions in my wallet because I am facing the "missing tx history" issue.
 
 
2021-06-06 23:08:02.727] [IPC-RENDERER-info]   {"regularDFIAfterTxFee":"45.05672945"}
[2021-06-06 23:08:02.743] [IPC-RENDERER-info]   {"toAddress":"dLAvkYXEJSg68ABZzMq68eL7mBDVTbnxVq","sendAmount":"45","subtractfeefromamount":false,"utxoDFI":"45.05672945"}
[2021-06-06 23:08:02.784] [IPC-RENDERER-info]   "sent dfi successfull=======9ef53e3a096835a71f0863b68535d7545fc5534e8603447f9e26d7042717e453"

If you check the above txid from the log, you will not find it in the block explorer. It seems there was a faulty block, where the transaction got stuck in?

#### Expected behavior:
Transaction comes trough as initiated.

#### How to reproduce it (as minimally and precisely as possible):

1. go to balance and click "send"
2. unlock wallet (if applicable)
3. enter DFI amount and target wallet address
4. Confirm & initiate transaction

#### What are your environment parameters?

- DeFi Wallet Version: 2.4.5; now 2.5.0
- Operating System (OS): Win10
– Current free storage capacity: enough
[defichain log.log](https://github.com/DeFiCh/app/files/6648440/defichain.log.log)
![2021-06-11 10_25_25-Settings](https://user-images.githubusercontent.com/85545447/121896426-91e12b80-cd21-11eb-9fa7-3ae55cd46b9b.png)

**Comment by izzycsy** [comment]
Hi @CryptoCHBS , you may not be facing the missing tx history issue since your tx from 7 – 11 Jun appeared. Can you filter your Transactions to DFI so that I can have clearer picture for investigation? Based on the txid you provided `9ef53e3a096835a71f0863b68535d7545fc5534e8603447f9e26d7042717e453` does not reflect on the explorer, after some investigation, and the following are the transactions that got through to `dLAv...`. 

[txid](https://mainnet.defichain.io/#/DFI/mainnet/address/dLAvkYXEJSg68ABZzMq68eL7mBDVTbnxVq): 
07/06/2021, 2DFI = `22d5d6380ea77a0609b5aced4e73273551f4aa0eb981cfc278958f34652ec926`
08/06/2021, 18DFI = `769648cad765ceba4df2e22bd4e2afb586a2c25c31dbeeef029796c36183af3d`
11/06/2021, 36DFI = `70b1d76822649c5c5ceaa8880b24d029c7b30b88c5ac278504a5aa77bff2184f`
12/06/2021, 17DFI = `02abf4817446b0beffdcf8c6eaf5b41e5ac046e622ea44b00efebf54643b7e60`
14/04/2021, 26DFI = `c74f3c4e565c81e50e9749cd3ce5305653da496c56c8654c5b3d7c3cd92a06a0`


On CakeDefi side, was there a Deposit & Withdrawal delay? If so, you likely just have to wait.

**Comment by CryptoCHBS** [comment]
Hi @izzycsy,
attached you can see the entire DFI transaction history since beginning of June, that is being displayed in my Defi Wallet. As you can see, it only shows the Account to UTXO swaps, but not the actual transaction to Cake.
Take this one as an example: 07/06/2021, 2DFI = 22d5d6380ea77a0609b5aced4e73273551f4aa0eb981cfc278958f34652ec926
The Account to UTXO swap is displayed in the wallet, but not the outgoing transaction to Cake. This one can only be found in the log as you did above.

To your question: I was in contact with Fabrizio from Cake support and he concluded that the transaction did not reach cake. So there is no deposit/ withdrawal delay. And as you can see I made some further transactions to cake after. They all went through within minutes.

So the big question is: where are the 45 DFI that have left my wallet and did not reach cake? And why is the log showing a txid (9ef53e3a096835a71f0863b68535d7545fc5534e8603447f9e26d7042717e453), that cannot be found in the block explorer?

Thanks again for your help.
Take care and best regards,
René


![2021-06-15 09_18_53-Movies   TV](https://user-images.githubusercontent.com/85545447/122009883-d371e500-cdba-11eb-8b57-1a4a0e18581e.png)
![2021-06-15 09_19_17-Movies   TV](https://user-images.githubusercontent.com/85545447/122009885-d40a7b80-cdba-11eb-91c1-9860d6d3a5c3.png)
![2021-06-15 09_18_19-Movies   TV](https://user-images.githubusercontent.com/85545447/122009887-d40a7b80-cdba-11eb-939d-533a1a6de70f.png)

**Comment by CryptoCHBS** [comment]
Any updates here?
It seems to me that this is not treated with the right priority. Are you aware what this means for DeFi Chain?
COINS ARE LOST SINCE 2 WEEKS AND NOBODY IS INVESTIGATING.  If nothing happens here, I need to make it public and warn people to not loose theirs funds!

**Comment by izzycsy** [comment]
Hi @CryptoCHBS , please give us time to investigate. Can you send your Binary Log & App Config as well please? Thank you.

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/122682242-ec4f2000-d22a-11eb-886a-f6f4ce7b282a.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/122682262-05f06780-d22b-11eb-9e8c-215f6eb590d0.png">

**Comment by CryptoCHBS** [comment]
Hi Bella,
sure, please find attached the binary log and app config file.
Reg. the missing tx history: Now that I have updated the wallet to 2.5.2, it shows the outgoing "sent" transactions. So it seems I was facing a similar issue. But its fine now.

Ragarding the missing 45 DFI: I have no screenshot of my wallet balance before and after the transaction. But the log file does proof, that my balance was lowered by 45 DFI, right? How can it be, that it shows "sent dfi successful" in the log and the block is not valid?? 

2021-06-06 23:08:02.727] [IPC-RENDERER-info] {"regularDFIAfterTxFee":"45.05672945"}
[2021-06-06 23:08:02.743] [IPC-RENDERER-info] {"toAddress":"dLAvkYXEJSg68ABZzMq68eL7mBDVTbnxVq","sendAmount":"45","subtractfeefromamount":false,"utxoDFI":"45.05672945"}
[2021-06-06 23:08:02.784] [IPC-RENDERER-info] "sent dfi successfull=======9ef53e3a096835a71f0863b68535d7545fc5534e8603447f9e26d7042717e453"

[Binary log.log](https://github.com/DeFiCh/app/files/6708900/Binary.log.log)

**Comment by izzycsy** [comment]
Hi @CryptoCHBS , log well received. Please give us time to investigate. In the mean time, can you `reindex`. 

**How to Reindex:** 
1. Go to the app's Menu Bar > Wallet > `Reindex Wallet`
- you may choose to `Backup Wallet` first if you have not made a backup before

<img width="271" alt="Menu bar   Re-index Wallet" src="https://user-images.githubusercontent.com/65014479/121924385-6f293400-cd6e-11eb-9a42-018d888680e6.png">


<img width="1015" alt="Snapshot (Europe) v2 5 0" src="https://user-images.githubusercontent.com/65014479/121924461-7e0fe680-cd6e-11eb-8c1e-8ceaf28270e9.png">


2. Node will proceed to restart
3. After which, at the bottom left hand corner, click on `i` to trigger Snapshot

<img width="244" alt="`i` to trigger Snapshot download" src="https://user-images.githubusercontent.com/65014479/120772648-1a5a1200-c553-11eb-8e2b-a5c5f68e3c89.png">


4. During the snapshot download, the app will download and unpack the snapshot contents. 

**It is recommended:** 
- ensure sufficient storage (temporary) for snapshot 
- to leave the app running with good internet connection
- turn off auto-lock / screen saver on your PC to prevent interruption

<img width="1015" alt="Downloading Snapshot 906633" src="https://user-images.githubusercontent.com/65014479/121924494-89631200-cd6e-11eb-8c96-618f92c55610.png">


5. When snapshot is unpacked & successful, user may select `DELETE SNAPSHOT & RESTART`

<img width="1017" alt="Snapshot successful 906633" src="https://user-images.githubusercontent.com/65014479/121924524-9253e380-cd6e-11eb-9716-1bfb6b4fd3f1.png">


6. After your app restarts, synchronisation should begin at ~90%, leave your app running till it reaches 100%.

**Comment by CryptoCHBS** [comment]
Hi @izzycsy,
the reindexing has worked.. The missing 45 DFI were added to the balance again and I could send them to Cake successfully now.
Thank you for all of your great hep and patience.
Jut for my understanding: Do you have any idea how this technically happened? I am curious :-)
Cheers,
René
