### ISSUE TITLE
Blockchain timestamps are out of order

### ISSUE THREAD

**Issue by mat42x** [DeFiCh/app#965]
#### Actual behavior:
Timestamps of blockchain are out of order:

<img width="761" alt="Screen Shot 2021-06-15 at 15 27 18" src="https://user-images.githubusercontent.com/27078075/122052416-56f8f980-cdee-11eb-98da-9390381e9f33.png">

#### Expected behavior:
Timestamps of blockchain is ascending.

#### What are your environment parameters?

- DeFi Wallet Version: 2.5.1
- Operating System (OS): MacOS
– Current free storage capacity:

**Comment by izzycsy** [comment]
Hi @mat42x , thanks for your feedback. This might help you understand why: https://www.youtube.com/watch?v=pAMz6Ou5vaU
