### ISSUE TITLE
Wrong output from getmasternodeblocks

### ISSUE THREAD

**Issue by Stonygan** [DeFiCh/app#966]
#### Actual behavior:
getmasternodeblocks {"operatorAddress":"xxxxx"}

output: 
All Blocks created from the specified Masternode. -> correct
Returns the block in which the MN was created with TX -> wrong

#### Expected behavior:
Command only retutns minted blocks, not block of creation.

#### How to reproduce it (as minimally and precisely as possible):

getmasternodeblocks {"operatorAddress":"8xxxxx"}

#### What are your environment parameters?

- DeFi Wallet Version: 2.5.1
- Operating System (OS): Win10

**Comment by izzycsy** [comment]
Hi @Stonygan , thanks for your feedback, please give us time to investigate.

**Comment by izzycsy** [comment]
Hi @Stonygan , update [v2.6.1](https://github.com/DeFiCh/app/releases/tag/v2.6.1) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Stonygan , update [v2.6.2](https://github.com/DeFiCh/app/releases/tag/v2.6.2) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by Stonygan** [comment]
Problem is not better now, with getmasternodeblocks it displays the block of the creation, but it displays no blocks after the last fork on August 5. Only the blocks before.

https://github.com/DeFiCh/ain/issues/694

**Comment by izzycsy** [comment]
Hi @Stonygan , thanks for the update, regarding the issue [`getmasternodeblocks give no blocks after Eunos Paya`](https://github.com/DeFiCh/ain/issues/694), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.
