### ISSUE TITLE
Can't create new receive address

### ISSUE THREAD

**Issue by Tapo2065** [DeFiCh/app#967]
I can't seem to create a new receive address. I can fill in the address label. Select Automatically generate new address. I can toggle show advanced options and I can click on the create button, but I'm getting nothing. No errors or messages of any kind, just as though I didn't click the button.
![Capture](https://user-images.githubusercontent.com/85985291/122171812-0928d380-ce78-11eb-9428-975575ca7cfe.JPG)

**Comment by Tapo2065** [comment]
Forgot to attach log
[log.log](https://github.com/DeFiCh/app/files/6660841/log.log)

**Comment by izzycsy** [comment]
Hi @Tapo2065 , thanks for opening the issue. You need to wait for your app to reach 100% before you can perform any functions in the app. You may use [Snapshot](https://github.com/DeFiCh/app/discussions/899) for a faster synchronisation process. Simple click on the `i` icon at the bottom left hand corner of the app's screen.

**Comment by Tapo2065** [comment]
Hi Izzy, thanks for your reply.  Sorry I should have explained, this issue was occurring last night after I had installed the software and had used the Europe snapshot then completed the remaining sync.  I have since re-indexed the wallet in the hope that it might resolve the issue, and this time have just left the sync to complete on it's own.  It's currently at 67%, so when it's complete I'll try again and let you know if it works.

**Comment by izzycsy** [comment]
Hi @Tapo2065 , sure, you can update here when you reach 100%. If the issues still persists, please save all logs and send them here. Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/122204093-508f7e00-ced1-11eb-99d4-36f3f9cc14dc.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/122204103-52594180-ced1-11eb-9e07-2f5a84590186.png">

**Comment by Tapo2065** [comment]
Thanks Izzy.  I've used the snapshot again to speed things up.  Issue is still the same.  Logs and new screenshot attached.  Many thanks.
![Screenshot](https://user-images.githubusercontent.com/85985291/122211946-32108f00-ce9f-11eb-8fef-d59199132bf3.JPG)
[App logs.zip](https://github.com/DeFiCh/app/files/6662639/App.logs.zip)

**Comment by izzycsy** [comment]
Hi @Tapo2065 , can you try another `wallet.dat`? I'll provide the steps. You should be able to find other wallet.dat in the `wallets` folder, unless you've been storing elsewhere. 

For Windows, the wallets folder is located here:
C: `\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat`

In the wallets folder you'll likely see wallet-bak-123456789 as well, these are additional backups.

<img width="822" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/122271024-894f4780-cf11-11eb-9d6a-247e85c9b937.png">

1. In the app, `Exit Wallet` 
<img width="236" alt="Exit Wallet" src="https://user-images.githubusercontent.com/65014479/122268801-18a72b80-cf0f-11eb-9a2c-7a0f36595111.png">

2. `Restore Wallet via Backup`
Select another wallet.dat in the `wallets` folder or where you've specified your other backups. 

<img width="1021" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/122268837-23fa5700-cf0f-11eb-9dd8-54f108ca8476.png">

**Comment by izzycsy** [comment]
Hi @Tapo2065 , may I check, are you installing the app for the first time? No funds being transferred yet right? If so, try to reinstall. Otherwise, please make a **backup** of your wallet first before reinstalling. 

Ensure that your firewall is turned off as it might disrupt the app trying to run properly.

Steps here: https://github.com/DeFiCh/app/discussions/964

**Comment by Tapo2065** [comment]
Thanks Izzy,

Restoring a backed up wallet seems to have done the trick.

Many thanks.

**Comment by izzycsy** [comment]
Hi @Tapo2065 , great, you can create another wallet backup just in case. 

![image](https://user-images.githubusercontent.com/65014479/122409299-9de51b80-cfb5-11eb-9b84-05f96f16fe48.png)
