### ISSUE TITLE
App doenst start and gets freezed while showing logo

### ISSUE THREAD

**Issue by whoisstu** [DeFiCh/app#968]
App gets freezed while opening. I just see the logo in the middle with the actual version (2.5.1). 

I´ve got this problem since a long time. I was hoping, that it gets repaired with new versions... 

I think it startet since my laptop crashed once and then after installing a new version 2.3.?

In the logs are mentioned something with an old version, I´ve got the feeling, that even after deleting the old version, there is still something left and the app tries to use it.

- DeFi Wallet Version: 2.5.1
- Operating System (OS): Windows
- Current free storage capacity: 250 GB

With friendly regards!

[Logs 16.06.2021.log](https://github.com/DeFiCh/app/files/6662942/Logs.16.06.2021.log)

**Comment by izzycsy** [comment]
Hi @whoisstu , if you're facing the issue where you only see the logo, check that your firewall is turned off — it should be turned off when running the app. If the issue persists, you can try to reinstall. **Please `backup wallet` first and the whole `wallets` folder.** For windows, it's located here (or unless you've specified another folder on your PC): 

C: `\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets`

Refer to full instructions here: https://github.com/DeFiCh/app/discussions/964

**Comment by cryptolaus** [comment]
Hi

Tried to reinstall and turned off firewall while starting / running the app. App still freezes while showing the logo animation. How can i tell the app NOT to  load my "corrupted" .dat file ?
