### ISSUE TITLE
insufficient funds

### ISSUE THREAD

**Issue by Michael41981** [DeFiCh/app#97]
Hello dear defi team,
I have a user account here with you and got the Defi-App, because I wanted to add a LM.

I have done the following :
Downloaded the app and installed it
Defi bought via Latoken and sent to the app ( see later screenshot )
BTC sent to Cake, this about defichain about cake sent to the app (see screenshot) and payout here in the portal.

both amounts Defi and BTC amount can be seen in the wallet app ( see screenshot )

but now comes the problem, when you add a LM, the app always says insufficient funds, this is also the case when I was under zb 50 defi still stay in the Balcane.

then I wanted to swoop the BTC to defi in the app, there are also insufficient resources, as if the Btc were not there, so I searched with the transcation number in the app on the defi blockchain in explorer mode for the sent defi and BTc (see screenshot)

in case of transcation number of the defi
at the transcation number of the Btc via Cake with Defichain to the app it is 0,003.....defi , this should be more defi, because it is 0,009.... btc were, ( see payment in the Cake Portal )

somehow it is logical, that when adding a LM, there are always insufficient resources, because the app displays the value correctly, but the value on the blockchain is much less. I hope you understand what I mean and my train of thought.

Please help me to find out what to do or what the problem might be.
so create the screenshot

1. send defi to the app what the blockchain shows
2. screenshot of the Defi-App Stand BTC and Defi
3. send Btc to the app which shows the blockchain .

Thanks in advance for your answer and help and stay healthy.

[App Logs.log](https://github.com/DeFiCh/app/files/5654067/App.Logs.log)
![Defi-Screenshot2](https://user-images.githubusercontent.com/75630346/101380329-a5649300-38b5-11eb-993a-9e22a2a49c76.png)
![Screenshot der BTC senden üner defchain zur App](https://user-images.githubusercontent.com/75630346/101380339-a7c6ed00-38b5-11eb-9d29-c7a7fd448baa.png)
![Wallet](https://user-images.githubusercontent.com/75630346/101380357-abf30a80-38b5-11eb-9825-631d8d1606dd.jpg)

**Comment by izzycsy** [comment]
Hi @Michael41981 , thank you for the feedback, please give us time to investigate this issue.

**Comment by Michael41981** [comment]
the said problem is not fixed yet , can please finally find a solution approach , as it is very troublesome when you can not use the app as it is supposed to be. Thanks in advance

**Comment by domedesign55** [comment]
press once on add liquidity. 
input left select DFI and right input BTC.

at BTC press MAX...( maximum)
if insufficient resources is written press now left on MAX at DFI.


now it should be balanced.

**Comment by Michael41981** [comment]
this is unfortunately not the problem , the curtain they describe can be locked , in both currencies to max.

the problem is that although in the app , the DEfi and Btc are displayed 

but it is as in the value would not be there ... swap is not possible , no matter in what currency , whether def in Eth or BTc , and Btc swap in defi . 

create a LM is possible up to their described point , this can one but then nichtg abgeschlossen , then comes , as well as when trying to swap , insufficient funds 

windows 10 ...... 

Translated with www.DeepL.com/Translator (free version)

**Comment by domedesign55** [comment]
maybe you have to try 5-15 wait until it is loaded at the LM.

I hope the support can help you.

best regards, defi user

**Comment by izzycsy** [comment]
@Michael41981 , we're still investigating your issue, however I'd like to provide an update, DeFiChain will be releasing an update soon, this may resolve your issue. I'll keep this Issue open so we can follow up with each other. Thank you for your patience.

Appreciate the help! @domedesign55

**Comment by izzycsy** [comment]
Hi @Michael41981 , is the `insufficient funds` error still present with the new update v2.1.4? 
<https://github.com/DeFiCh/app/releases/tag/v2.1.4>

**Comment by 1987FL** [comment]
> @Michael41981 , we're still investigating your issue, however I'd like to provide an update, DeFiChain will be releasing an update soon, this may resolve your issue. I'll keep this Issue open so we can follow up with each other. Thank you for your patience.
> 
> Appreciate the help! @domedesign55

Hey izzycsy, 
same issue "insufficient funds" is shown also in 2.1.15 theses days. How you fixed the bug in the past?  I would be appreciate to get a solution for this pending issue.

Best regards!
