### ISSUE TITLE
DEX Withdrawl transaction not visible

### ISSUE THREAD

**Issue by DiabloBestHusky** [DeFiCh/app#975]
#### Actual behavior: 
Yesterday I did a swap at DEX from DFI to LTC, after that I withdraw the dLTC to a Cake account.
Transaction was working, I received the LTC at Cake but the transaction history at DEX just show 0.299 DFI in and out but not the LTC.
LTC was booked out from DEX wallet exactly but it is no transaction hystory for this visible until now.

Trans Hash: 805a90f8f073fa1e313ec2b1c3482dfab7170ef4409aae9e3f1a5d4f23220619

#### What are your environment parameters?

- DeFi Wallet Version: 2.5.1
- Operating System (OS): windows 10
– Current free storage capacity: > 80 GB

**Comment by izzycsy** [comment]
Hi @DiabloBestHusky  regarding the issue [`Missing tx history`](https://github.com/DeFiCh/app/issues/891), we can further discuss on the issue there. We would like to keep same issues in one thread. Take a screenshot, save your app logs and send them there. Thank you.

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/122461886-7eb2b200-cfe6-11eb-8cfa-56823d3a028c.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/122461891-807c7580-cfe6-11eb-96f6-cfb4d88428e0.png">
