### ISSUE TITLE
Cannot send DFI: Test AccountToUtxosTx execution failed: tx must have at least one input from account owner

### ISSUE THREAD

**Issue by alebree** [DeFiCh/app#976]
#### Actual behavior:

I restored my wallet on my PC want want to send some DFI to another address. Then the mentioned error comes up. I have enough UTXOs (3.6) and enough tokens to send them.

#### How to reproduce it (as minimally and precisely as possible):

1. I restored my wallet on another PC (windows) trough mnemonic seed
2. want to send some DFI to another address.
3. I get the this error message: **Cannot send DFI: Test AccountToUtxosTx execution failed: tx must have at least one input from account owner**.
 
#### What are your environment parameters?
- DeFi Wallet Version: 2.5.1
- Operating System (OS): Windows 10
– Current free storage capacity: 70 GB

![DFI_error](https://user-images.githubusercontent.com/22911886/122533565-010c9780-d022-11eb-9031-b2f36793bd8d.png)

**Comment by izzycsy** [comment]
Hi @alebree , do you have multiple addresses? If so, send your DFI to 1 of the addresses and use it for your utxoDFI fees, the transaction should go through then.
