### ISSUE TITLE
Newly created Addresses via in-app CLI do not appear in receive list

### ISSUE THREAD

**Issue by DerFuchs** [DeFiCh/app#977]
#### Actual behavior:
When creating a (legacy) DFI address using the in-app CLI, the newly created address does not appear in the "receive" list of the app:

`$ getnewaddress "name" legacy`

When using `$ dumpprivkey <address>` a private key gets printed.
Restarting the app doesn't bring up the new address, either.

#### Expected behavior:
The new address should appear in the "receive" list

#### How to reproduce it (as minimally and precisely as possible):

In-App CLI:

`$ getnewaddress "name" legacy`
--> Results in an `<address>`

`$ dumpprivkey <address>`
--> Results in a private key

Navigate to "Balances" -> "DFI" -> "RECEIVE" -> no new `<address>` in List

#### What are your environment parameters?

- DeFi Wallet Version: 2.5.1
- Operating System (OS): MacOS 11.3, MacBook Air with M1 chip
- Current free storage capacity: 853 GB

#### Anything else we need to know?

Same behavior when creating a regular (non-legacy) address

**Comment by izzycsy** [comment]
Hi @DerFuchs , if you want to create an address via CLI: 

In CLI: 
1. Unlock your wallet if you've a passphrase
2. `getnewaddress` — this would be your newly created address
3. dumpprivkey <dULR...> 

To view it in app: 
4. Go to Receive > `NEW ADDRESS`
5. Toggle-off Automatically generate a new address

<img width="791" alt="Do not auto create address" src="https://user-images.githubusercontent.com/65014479/122609886-4deb7f00-d0b1-11eb-978e-b978ffd42352.png">

Alternatively, you can do it via in app:  Go to Receive > `NEW ADDRESS`

<img width="793" alt="Create address" src="https://user-images.githubusercontent.com/65014479/122610250-e41fa500-d0b1-11eb-8e0b-8391304cba9d.png">

For how-to enquiries, you can ask the community via [DeFiChain Telegram (EN)](https://t.me/defiblockchain)
