### ISSUE TITLE
My .dat file isn't working with the latest wallet version

### ISSUE THREAD

**Issue by Morhpois01** [DeFiCh/app#980]
#### Actual behavior:
With the latest wallet version, I get the following error:
"BerkeleyBatch: Error -30974, can't open database Stand1105.dat" After trying to unlock my wallet.

After U-Zyn told me that my file could be corrupted. I installed wallet version 2.3.3 last night and downloaded the snapshot which the wallet asked me to (from 2 month ago). But after downloading the snapshot and adding the right path and name of my wallet in the config file, I was able to after restarting to see my wallet and to even unlock my wallet without any error.

Currently the wallet is still by 89% and isn't fully synced but this shows me that my file is working. Just not with the newest wallet version.

Since we had s hardfork recently, I'm not sure if this wallet version will be fully synced at all, but please let me know what to do with my file.

#### What are your environment parameters?

- DeFi Wallet Version: 
- Operating System (OS):
– Current free storage capacity:

**Comment by izzycsy** [comment]
Hi @Morhpois01 , if you managed to sync to 100%, `backup wallet`, save it it Documents or any folder which you've access to, then close the app and install [v2.5.2](https://github.com/DeFiCh/app/releases/tag/v2.5.2). 

<img width="269" alt="Menu bar   Backup Wallet" src="https://user-images.githubusercontent.com/65014479/122753414-d1c98500-d2c4-11eb-8733-89be3ef1fc26.png">

If you face an updating issue such as `node is disconnected`, refer to this link on [how to reinstall](https://github.com/DeFiCh/app/discussions/964).

**Comment by angelocastiglione** [comment]
Try to create new wallet .dat importing private key of your wallet damaged.

**Comment by izzycsy** [comment]
Hi @Morhpois01 @angelocastiglione , update [v2.6.0](https://github.com/DeFiCh/app/releases/tag/v2.6.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Morhpois01 @angelocastiglione , update [v2.6.1](https://github.com/DeFiCh/app/releases/tag/v2.6.1) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Morhpois01 @angelocastiglione , update [v2.6.2](https://github.com/DeFiCh/app/releases/tag/v2.6.2) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Morhpois01 @angelocastiglione , update [v2.6.3](https://github.com/DeFiCh/app/releases/tag/v2.6.3) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Morhpois01 @angelocastiglione , update [v2.7.0](https://github.com/DeFiCh/app/releases/tag/v2.7.0) is out, this is a **mandatory update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Morhpois01 @angelocastiglione , update [v2.7.1](https://github.com/DeFiCh/app/releases/tag/v2.7.1) is out, this is a **mandatory update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Morhpois01 @angelocastiglione , update [v2.9.1](https://github.com/DeFiCh/app/releases/tag/v2.9.1) is out, this is a **mandatory update**. Kindly `backup wallet` and read through the release notes before updating. _This comment is to notify you about the update._
