### ISSUE TITLE
Add-on auth TX failed: Insufficient funds

### ISSUE THREAD

**Issue by dell1503** [DeFiCh/app#982]
#### Actual behavior:
I try to Convert or send any DFI. I always receive the error
<img width="798" alt="Bildschirmfoto 2021-06-22 um 13 17 32" src="https://user-images.githubusercontent.com/20696826/122917600-7cda4d00-d35e-11eb-8b99-e2913fa43f7c.png">

#### Expected behavior:
Can Send to Transaction.

#### How to reproduce it (as minimally and precisely as possible):

I receive always the the same error. I simply just try send my self some DFI no transfer.
I send myself already 2 DFI, See Balance:
<img width="714" alt="Bildschirmfoto 2021-06-22 um 13 16 28" src="https://user-images.githubusercontent.com/20696826/122917768-aabf9180-d35e-11eb-80c0-217518b1395e.png">

I tried the following Guide:
https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

```
getbalance
2.99828291
```

```
gettokenbalances {} true true

{
  "DFI": 277.30827445,
  ........
}
```
When try to  convert via 'accounttoutxos' I receive the following error:
```
 accounttoutxos dKBPCKjpPvtQCpHQP5tsYkEnaB1cnH93aA {"dKBPCKjpPvtQCpHQP5tsYkEnaB1cnH93aA":"1.0@DFI"} 
```

The Adress has the amount available.
```
listaccounts {} false false true

[
  {
    "key": "a9143f2f968043e5b9824608775489f74fb40308cf0f87@0",
    "owner": "dKBPCKjpPvtQCpHQP5tsYkEnaB1cnH93aA",
    "amount": "4.04765201@DFI"
  },
  {
    "key": "a9143f2f968043e5b9824608775489f74fb40308cf0f87@2",
    "owner": "dKBPCKjpPvtQCpHQP5tsYkEnaB1cnH93aA",
    "amount": "0.00000063@BTC"
  },
  {
    "key": "a9143f2f968043e5b9824608775489f74fb40308cf0f87@5",
    "owner": "dKBPCKjpPvtQCpHQP5tsYkEnaB1cnH93aA",
    "amount": "1.80395299@BTC-DFI"
  },
  {……………
]
```

#### What are your environment parameters?

- DeFi Wallet Version: 2.5.2
- Operating System (OS): Mac OSX
– Current free storage capacity: 300GB

#### Anything else we need to know?

[Archiv.zip](https://github.com/DeFiCh/app/files/6693881/Archiv.zip)

**Comment by izzycsy** [comment]
Hi @dell1503 , can you try sending a smaller amount to `dKBP...`. 

You may instead refer to this guide on converting your tokenDFI to utxoDFI: https://github.com/DeFiCh/app/discussions/846

**Comment by dell1503** [comment]
Dear @izzycsy ,

Thank you very much.
I tried that before, now somehow it worked. Honestly, I have no clue what changed.
I was not able to transfer the first 1 DFI and then the test.

Sorry to bother you with that.

**Comment by izzycsy** [comment]
Hi @dell1503 , might just be a block was not yet created for your transaction. Glad it's fixed. Thanks for the update.

**Comment by dell1503** [comment]
Hi Again, again same issue...

I dont get it.....
Again the same issue. But just with one DEFI.
![Bildschirmfoto 2021-07-03 um 17 43 39](https://user-images.githubusercontent.com/20696826/124359700-5d78d500-dc26-11eb-8339-6c1b0103c062.png)
![Bildschirmfoto 2021-07-03 um 17 42 51](https://user-images.githubusercontent.com/20696826/124359702-5e116b80-dc26-11eb-8952-0695fe4af3cf.png)

Is there a way to remove my multiple address? when I do this Guide: https://github.com/DeFiCh/app/discussions/846
I have plany adressess. I don't know why.

Thanks for help

**Comment by izzycsy** [comment]
Hi @dell1503 , you can click cancel request. However, during each update the app will retrieve any address that's link to your `wallet.dat`. You can ignore the ones you don't use, and stick to 1 address. 

<img width="803" alt="#4 Receive   Cancel request" src="https://user-images.githubusercontent.com/65014479/124389193-aad56f00-dd18-11eb-9865-f2478d54c7f7.png">

**Comment by mat42x** [comment]
I have the same problem. No idea what I can do...

**Comment by dell1503** [comment]
Today, I tried again, and it just worked... why?

**Comment by izzycsy** [comment]
Hi @mat42x , do you have multiple addresses? 

Hi @dell1503 , the reasons ranges. It could be too many tx in that block / too many addresses on your wallet.dat so the app has trouble sourcing for utxoDFI, bad connection, or simply insufficient DFI (minimum 1). The additional comment made in this post might help explain further: https://github.com/DeFiCh/app/discussions/846

**Comment by izzycsy** [comment]
Hi @mat42x @dell1503 , update [v2.6.0](https://github.com/DeFiCh/app/releases/tag/v2.6.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @mat42x @dell1503 , update [v2.6.1](https://github.com/DeFiCh/app/releases/tag/v2.6.1) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @mat42x @dell1503 , update [v2.6.2](https://github.com/DeFiCh/app/releases/tag/v2.6.2) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @mat42x @dell1503 , update [v2.6.3](https://github.com/DeFiCh/app/releases/tag/v2.6.3) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @mat42x @dell1503 has your issue been resolved?

**Comment by supervolot** [comment]
I have the same problem, sending DFI dont work. 
I tried also accounttoutxos but here i get the error "min relay fee not met, 246 < 284 (code 66)" ???

**Comment by supervolot** [comment]
I have made the update to 2.6.5 an now the "accounttoutuxos" worked fine

**Comment by ab3dat** [comment]
Hi,
I'm getting this error message since updating to 2.6.5.
I have enough DFIs in UTXO and also as Tokens.
I already tried to send smaller amounts and also accounttoutxos, but nothing worked.

**Comment by izzycsy** [comment]
Hi @ab3dat , do you have multiple addresses? Can you try to see if this guide will help you: https://github.com/DeFiCh/app/discussions/846
