### ISSUE TITLE
Start Message "An error occured while checking for software update"

### ISSUE THREAD

**Issue by Darkman-Q-Tester** [DeFiCh/app#983]
#### Actual behavior:
When starting Defi Wallet this message is displayed every time, although I have already installed the latest version.
Even if I download and install again message will come again.
![grafik](https://user-images.githubusercontent.com/77509687/122917769-ab582800-d35e-11eb-8313-4d2be68b110d.png)

#### Expected behavior:
Message should not be displayed if latest version is installed

#### How to reproduce it (as minimally and precisely as possible):
Launch the app after manual install

- DeFi Wallet Version: 2.5.2
- Operating System (OS): Win 10 Pro
– Current free storage capacity: 500GB

#### Anything else we need to know?
There was an issue with automatic update so I had to install it manually.
[log.zip](https://github.com/DeFiCh/app/files/6693893/log.zip)

**Comment by izzycsy** [comment]
Hi @Darkman-Q-Tester , can you send your binary log too please? In the mean time, you can try to replace the `app` manually. 

1. `Backup wallet` first 
<img width="269" alt="Menu bar   Backup Wallet" src="https://user-images.githubusercontent.com/65014479/123062887-825b9400-d43f-11eb-980d-1291f411d637.png">


2. Go to the [latest app release](https://github.com/DeFiCh/app/releases/tag/v2.5.2) 

3. Download `DeFi-Wallet-Setup-2.5.2.exe`

4. Replace the **app icon only**

<img width="532" alt="Replace app1" src="https://user-images.githubusercontent.com/65014479/123063211-c77fc600-d43f-11eb-88ea-0e656e6430ca.png">


Kindly ensure that your firewall is turned off and internet connection is stable.

**Comment by Darkman-Q-Tester** [comment]
Thank you, I did already manually.
See attached the binary log.
[binary.zip](https://github.com/DeFiCh/app/files/6701430/binary.zip)

**Comment by izzycsy** [comment]
Hi @Darkman-Q-Tester , there could've been an outage on GitHub when you had this error, hence the app kept checking if there's an update available. Do you still encounter it?

**Comment by Darkman-Q-Tester** [comment]
Issue is gone. Thank you
