### ISSUE TITLE
Wallet Console setlabel function fails on label argument containing space character

### ISSUE THREAD

**Issue by mcd33d** [DeFiCh/app#985]
#### Which feature is your request related to?
Console: "setlabel" command does not take label argument with spaces. 
eg: setlabel "dPxxxxxxxxxxxxxxxxxxxxxx" "2021 DFI" ends in display of help text to setlabel function (fails), while:
setlabel "dPxxxxxxxxxxxxxxxxxxxxxx" "2021_DFI" works perfectly.

#### Describe the solution you'd like:
GUI provides possibility to use spaces as label character.

**Comment by izzycsy** [comment]
Hi @mcd33d , thanks for your feedback. DeFi Wallet does not have this feature at the moment but you may open on on GitHub Discussions <https://github.com/DeFiCh/app/discussions> and we can discuss from there; along with the community. You can label your address when creating it via the app. Thank you. 

<img width="775" alt="Receive   Manually add address" src="https://user-images.githubusercontent.com/65014479/123557012-0a83c580-d7c1-11eb-9f46-50a6cd655291.png">
