### ISSUE TITLE
Transaction (incl. Rewards) shows non existing Rewards

### ISSUE THREAD

**Issue by nico89-exp** [DeFiCh/app#989]
#### Actual behavior:
In Transactions tab when Include Rewards is checked the very recent rewards are shown. Also in export of transactions these rewards are included for different wallet addresses for every block.

The wallet contains no LP token (they have been moved to completely different wallet some hours before). Token in wallet don't increase, so the shown rewards are actually not received in the wallet, just shown in the history.

<img width="1005" alt="Screenshot 2021-07-06" src="https://user-images.githubusercontent.com/80567701/124571337-fc304c00-de47-11eb-8944-2dbcd4b79f47.png">

#### Expected behavior:
Transaction tab and export should only show really existing rewards.

#### How to reproduce it (as minimally and precisely as possible):
Go the transactions tab and check include rewards checkbox.

#### What are your environment parameters?

- DeFi Wallet Version: 2.5.2
- Operating System (OS): macOS 11.4
- Current free storage capacity: 500 GB

#### Anything else we need to know?
Exporting longer history (checkpoints=0, full reindex) also shows rewards in addresses of the wallet that where not holding any LP token anymore.

**Comment by izzycsy** [comment]
Hi @nico89-exp , it could be because the address is tagged to your wallet.dat. You can try to `reset & reindex` followed by [snapshot](https://github.com/DeFiCh/app/discussions/899) so you can sync to 100% faster. Please backup wallet prior to reindexing.

**Comment by nico89-exp** [comment]
Hi @izzycsy I did a full reset & reindex. 

Still in the **export** including rewards from current block I see Rewards and Commissions for one address from my wallet. However this address is not holding any LP token and actually stays at zero balance. So the R&C are listed in the transaction history export but are not really coming to the address.

In the transactions tab in the app I don't see these R&C listed since I moved the LP token to another address. 

Any ideas?

**Comment by izzycsy** [comment]
Hi @nico89-exp , can you try `rescan` via settings? 

<img width="782" alt="Rescan" src="https://user-images.githubusercontent.com/65014479/127330507-bae39be4-20a8-46eb-9e10-c4a0a0c9ebe1.png">

**Comment by nico89-exp** [comment]
HI @izzycsy Done, no changes. Still export shows non existing R&C every block. I did a rescan also before the reset & reindex and did it again just now.

**Comment by izzycsy** [comment]
Hi @nico89-exp , I'm trying to reproduce your issue on my end, can you check & confirm the following: 
1. the address is shown on your the app's Receive Address screen, if yes proceed to answer **2**

<img width="1002" alt="DFI wallet   Receive   New Address" src="https://user-images.githubusercontent.com/65014479/127362380-0a17eab8-ac6f-44ce-b735-d9eaeed035e3.png">


2. In Transactions, after filtering to DFI, since you want to export the rewards / commissions and it's given in DFI, before clicking `EXPORT` did you toggle `include reward transactions`? 

<img width="777" alt="Include Rewards" src="https://user-images.githubusercontent.com/65014479/127362322-a80d45f4-141e-41e8-9829-a0e5ca144fb5.png">

**Comment by nico89-exp** [comment]
Hi @izzycsy Thanks a lot for your support!

1. Yes, the address is shown
2. I cannot filter to DFI, the dropdown is empty. So I keep "All". I guess this is due to the fact that the wallet contains no funds anymore. All have been moved away. And I toogled "Include reward transactions" before. I even waited until CPU load of defid was low again before clicking the "Export" button. If you click while CPU load is high, most transactions are missing in the csv.

Strange thing is, that these "ghost" rewards I see in the csv file are not listed in the Transactions tab in the app. Further I tried a manual export via defi-CLI.exe with `listaccounthistory`. Here the "ghost" rewards are not listed.

**Comment by izzycsy** [comment]
Hi @nico89-exp , could you:
1. send a screenshot of not being able to `filter to DFI` 
2. provide the output of `listaccounts {} false false true` — this shows a breakdown of your tokens
3. send your logs

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/127457871-84af8070-4857-475b-bbb1-0d67edfda5ae.png">

I would like to understand if the tokens are in your wallet.dat, or could it be a UI issue that you cannot filter DFI.

**Comment by nico89-exp** [comment]
Hi @izzycsy 

Can I send this through a more private channel to you? As I said, the wallet is completly empty now, so no tokens are there any more. I just need to export the complete history for tax documentation. I know that the history export is not working properly since a while.

**Comment by izzycsy** [comment]
Hi @nico89-exp , sure you can find me from the main [DeFiChain Telegram (EN)](https://t.me/defiblockchain). @imnotabell , I'll be removing my username  here, after I've received a dm from you.

**Comment by izzycsy** [comment]
Hi @nico89-exp , update [v2.6.0](https://github.com/DeFiCh/app/releases/tag/v2.6.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @nico89-exp , update [v2.6.1](https://github.com/DeFiCh/app/releases/tag/v2.6.1) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @nico89-exp , update [v2.6.2](https://github.com/DeFiCh/app/releases/tag/v2.6.2) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @nico89-exp , update [v2.6.3](https://github.com/DeFiCh/app/releases/tag/v2.6.3) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._
